LIA_RAL: LIA_SpkTools/include/AccumulateStat.h File Reference
AccumulateStat.h File Reference
#include <alize.h>
#include "liatools.h"
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, Seg *seg, Config &config)
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, double &weight, Config &config)
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, Seg *seg, double &weight, Config &config)
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, SegCluster &selectedSegments, double &weight, Config &config)
LIA_SPKTOOLS_API double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
LIA_SPKTOOLS_API double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, Seg *seg, Config &config)
LIA_SPKTOOLS_API double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API double accumulateStatEMUnThreaded (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, SegCluster &selectedSegments, double &weight, Config &config)
LIA_SPKTOOLS_API void accumulateStatFrame (FrameAcc &frameAcc, FeatureServer &fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
LIA_SPKTOOLS_API void accumulateStatFrame (FrameAcc &frameAcc, FeatureServer &fs, Seg *seg, Config &config)
LIA_SPKTOOLS_API void accumulateStatFrame (FrameAcc &frameAcc, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API double areaHisto (const Histo &histo, unsigned long bin)
LIA_SPKTOOLS_API double areaHisto (const Histo &histo, unsigned long bin, double nonObserved)
LIA_SPKTOOLS_API double linearInterpolation (double val, double lower, double higher)
LIA_SPKTOOLS_API void freezeHistoTab (Histo *&histoT)
LIA_SPKTOOLS_API void initHistoTab (Histo *&histoT, unsigned long size, unsigned long nbBins)
LIA_SPKTOOLS_API void computeHistoTab (Histo *histoT, unsigned long size)
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, Seg *seg, Config &config)
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file AccumulateStat.h.
Function Documentation
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 453 of file AccumulateStat.cpp.
Referenced by normFeat().
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 465 of file AccumulateStat.cpp.
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 471 of file AccumulateStat.cpp.
LIA_SPKTOOLS_API double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 103 of file AccumulateStat.cpp.
References log().
Referenced by accumulateStatEM(), accumulateStatEMUnThreaded(), adaptModel(), adaptModelEM(), clusteringCriterionWithoutWorldInitOneGaus(), crossValid(), energyDetector(), mixtureInitBySplit(), modelBasedadaptModel(), modelBasedadaptModelEM(), trainModel(), and trainModelStream().
LIA_SPKTOOLS_API double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, Seg * seg, Config & config)
Definition at line 116 of file AccumulateStat.cpp.
References accumulateStatEM().
LIA_SPKTOOLS_API double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, SegCluster & selectedSegments, Config & config)
Definition at line 131 of file AccumulateStat.cpp.
References accumulateStatEMUnThreaded().
LIA_SPKTOOLS_API double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, SegCluster & selectedSegments, double & weight, Config & config)
Definition at line 143 of file AccumulateStat.cpp.
References accumulateStatEM(), and verbose.
LIA_SPKTOOLS_API double accumulateStatEMUnThreaded (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, SegCluster & selectedSegments, Config & config)
Definition at line 121 of file AccumulateStat.cpp.
References accumulateStatEM().
Referenced by accumulateStatEM().
LIA_SPKTOOLS_API void accumulateStatFrame (FrameAcc & frameAcc, FeatureServer & fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 387 of file AccumulateStat.cpp.
Referenced by accumulateStatFrame(), cms(), computeMeanCov(), computeWindowParam(), globalMeanCov(), infoFeat(), mixtureInit(), and normFeat().
LIA_SPKTOOLS_API void accumulateStatFrame (FrameAcc & frameAcc, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 398 of file AccumulateStat.cpp.
References accumulateStatFrame().
LIA_SPKTOOLS_API void accumulateStatFrame (FrameAcc & frameAcc, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 404 of file AccumulateStat.cpp.
References accumulateStatFrame().
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 69 of file AccumulateStat.cpp.
References debug.
Referenced by accumulateStatLLK(), clrCrit(), gllrCrit(), and meanLikelihood().
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, Seg * seg, Config & config)
Definition at line 82 of file AccumulateStat.cpp.
References accumulateStatLLK().
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, SegCluster & selectedSegments, Config & config)
Definition at line 88 of file AccumulateStat.cpp.
References accumulateStatLLK().
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, double & weight, Config & config)
Definition at line 344 of file AccumulateStat.cpp.
References debug.
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, Seg * seg, double & weight, Config & config)
Definition at line 363 of file AccumulateStat.cpp.
References accumulateStatLLK().
LIA_SPKTOOLS_API void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, SegCluster & selectedSegments, double & weight, Config & config)
Definition at line 371 of file AccumulateStat.cpp.
References accumulateStatLLK().
LIA_SPKTOOLS_API double areaHisto (const Histo & histo, unsigned long bin)
Definition at line 424 of file AccumulateStat.cpp.
Referenced by centralSpace(), main(), scoreWarping(), and warping().
LIA_SPKTOOLS_API double areaHisto (const Histo & histo, unsigned long bin, double nonObserved)
Definition at line 428 of file AccumulateStat.cpp.
LIA_SPKTOOLS_API void computeHistoTab (Histo * histoT, unsigned long size)
Definition at line 448 of file AccumulateStat.cpp.
Referenced by normFeat().
LIA_SPKTOOLS_API void freezeHistoTab (Histo *& histoT)
Definition at line 438 of file AccumulateStat.cpp.
Referenced by normFeat().
LIA_SPKTOOLS_API void initHistoTab (Histo *& histoT, unsigned long size, unsigned long nbBins)
Definition at line 442 of file AccumulateStat.cpp.
Referenced by normFeat().
LIA_SPKTOOLS_API double linearInterpolation (double val, double lower, double higher)
Definition at line 432 of file AccumulateStat.cpp.
Referenced by scoreWarping(), and warping().