LIA_RAL: LIA_SpkTools/src/AccumulateStat.cpp File Reference
AccumulateStat.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
Macros
#define ALIZE_GeneralTools_cpp
Functions
void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, Seg *seg, Config &config)
void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, SegCluster &selectedSegments, Config &config)
double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, Seg *seg, Config &config)
double accumulateStatEMUnThreaded (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, SegCluster &selectedSegments, Config &config)
double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, SegCluster &selectedSegments, Config &config)
double accumulateStatEM (StatServer &ss, FeatureServer &fs, MixtureStat &emAcc, SegCluster &selectedSegments, double &weight, Config &config)
void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, double &weight, Config &config)
void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, Seg *seg, double &weight, Config &config)
void accumulateStatLLK (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, SegCluster &selectedSegments, double &weight, Config &config)
void accumulateStatFrame (FrameAcc &frameAcc, FeatureServer &fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
void accumulateStatFrame (FrameAcc &frameAcc, FeatureServer &fs, Seg *seg, Config &config)
void accumulateStatFrame (FrameAcc &frameAcc, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
double areaHisto (const Histo &histo, unsigned long bin)
double areaHisto (const Histo &histo, unsigned long bin, double nonObserved)
double linearInterpolation (double val, double lower, double higher)
void freezeHistoTab (Histo *&histoT)
void initHistoTab (Histo *&histoT, unsigned long size, unsigned long nbBins)
void computeHistoTab (Histo *histoT, unsigned long size)
void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, Seg *seg, Config &config)
void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
Macro Definition Documentation
#define ALIZE_GeneralTools_cpp
Definition at line 55 of file AccumulateStat.cpp.
Function Documentation
void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 453 of file AccumulateStat.cpp.
Referenced by accumulateHistoFrame(), and normFeat().
void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 465 of file AccumulateStat.cpp.
References accumulateHistoFrame().
void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 471 of file AccumulateStat.cpp.
References accumulateHistoFrame().
double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 103 of file AccumulateStat.cpp.
References log().
Referenced by accumulateStatEM(), accumulateStatEMUnThreaded(), adaptModel(), adaptModelEM(), clusteringCriterionWithoutWorldInitOneGaus(), crossValid(), energyDetector(), mixtureInitBySplit(), modelBasedadaptModel(), modelBasedadaptModelEM(), trainModel(), and trainModelStream().
double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, Seg * seg, Config & config)
Definition at line 116 of file AccumulateStat.cpp.
References accumulateStatEM().
double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, SegCluster & selectedSegments, Config & config)
Definition at line 131 of file AccumulateStat.cpp.
References accumulateStatEMUnThreaded().
double accumulateStatEM (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, SegCluster & selectedSegments, double & weight, Config & config)
Definition at line 143 of file AccumulateStat.cpp.
References accumulateStatEM(), and verbose.
double accumulateStatEMUnThreaded (StatServer & ss, FeatureServer & fs, MixtureStat & emAcc, SegCluster & selectedSegments, Config & config)
Definition at line 121 of file AccumulateStat.cpp.
References accumulateStatEM().
Referenced by accumulateStatEM().
void accumulateStatFrame (FrameAcc & frameAcc, FeatureServer & fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 387 of file AccumulateStat.cpp.
Referenced by accumulateStatFrame(), cms(), computeMeanCov(), computeWindowParam(), globalMeanCov(), infoFeat(), mixtureInit(), and normFeat().
void accumulateStatFrame (FrameAcc & frameAcc, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 398 of file AccumulateStat.cpp.
References accumulateStatFrame().
void accumulateStatFrame (FrameAcc & frameAcc, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 404 of file AccumulateStat.cpp.
References accumulateStatFrame().
void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 69 of file AccumulateStat.cpp.
References debug.
Referenced by accumulateStatLLK(), clrCrit(), gllrCrit(), and meanLikelihood().
void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, Seg * seg, Config & config)
Definition at line 82 of file AccumulateStat.cpp.
References accumulateStatLLK().
void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, SegCluster & selectedSegments, Config & config)
Definition at line 88 of file AccumulateStat.cpp.
References accumulateStatLLK().
void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, double & weight, Config & config)
Definition at line 344 of file AccumulateStat.cpp.
References debug.
void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, Seg * seg, double & weight, Config & config)
Definition at line 363 of file AccumulateStat.cpp.
References accumulateStatLLK().
void accumulateStatLLK (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, SegCluster & selectedSegments, double & weight, Config & config)
Definition at line 371 of file AccumulateStat.cpp.
References accumulateStatLLK().
double areaHisto (const Histo & histo, unsigned long bin)
Definition at line 424 of file AccumulateStat.cpp.
Referenced by areaHisto(), centralSpace(), main(), scoreWarping(), and warping().
double areaHisto (const Histo & histo, unsigned long bin, double nonObserved)
Definition at line 428 of file AccumulateStat.cpp.
References areaHisto().
void computeHistoTab (Histo * histoT, unsigned long size)
Definition at line 448 of file AccumulateStat.cpp.
Referenced by normFeat().
void freezeHistoTab (Histo *& histoT)
Definition at line 438 of file AccumulateStat.cpp.
Referenced by normFeat().
void initHistoTab (Histo *& histoT, unsigned long size, unsigned long nbBins)
Definition at line 442 of file AccumulateStat.cpp.
Referenced by normFeat().
double linearInterpolation (double val, double lower, double higher)
Definition at line 432 of file AccumulateStat.cpp.
Referenced by scoreWarping(), and warping().