LIA_RAL: LIA_SpkSeg/AcousticSegmentation/src/AcousticSegmentation.cpp File Reference
AcousticSegmentation.cpp File Reference
Short description of the speech activity detection (SAD) behavior.
#include "Tools.h"
#include "AcousticSegmentation.h"
Macros
#define ALIZE_AcousticSegmentation_cpp
Functions
void segAdaptationClass (Config &config, MAPCfg &mapCfg, hmm &actualHMM, ObjectRefVector &classModelTab, SegServer &previousSeg, SegServer &actualSeg, StatServer &ss, FeatureServer &fs, MixtureServer &ms)
Adapts the gmm models of the n-state HMM according to the current segmentation.
bool isStopAcousticSegmentation (Config &config, SegServer &previousSeg, SegServer &segmentServer, DoubleVector &actualViterbiProb, DoubleVector &previousViterbiProb, hmm &actualHMM)
Verifies whether the stop criteria (for adaptation/decoding step) are reached.
void aggregateSegment (SegServer &segmentServer)
Aggregate successive segments labeled in the same way.
void applyLengthRules (Config config, SegServer &segmentServer, hmm &actualHMM)
Apply length rules on the segments according to the config file.
void AcousticSegmentationProcess (Config &config, SegServer &resegOutputServer, SegServer &segmentServer, StatServer &ss, MixtureServer &ms, FeatureServer &fs, LabelServer &labelServer)
The iterative SAD process (Speech Activity Detection)
void launchAcousticSegmentationProcess (Config &config)
Launching of the iterative SAD (Speech Activity Detection) process.
Detailed Description
Short description of the speech activity detection (SAD) behavior.
Author
LIA
Version
2.0
Date
june 2011
The iterative SAD process is based on Viterbi decoding and model adaptation applied to a n-state HMM.
The n states represent the acoustic events expected in the signal (e.g: speech, music, speech+music, narrow/wide band, ...). They are each initialized with a GMM model trained on appropriate, separate data using an EM/ML algorithm (see LIA_SpkDet packages for the GMM model training). State transition probabilities are fixed according to the parameters transitionMethod and gammaTransition.
Finally, minimum duration rules are applied in order to refine the acoustic segmentation yielded by the iterative process (possibility of replacing too short segments with adjacent segment class).
Definition in file AcousticSegmentation.cpp.
Macro Definition Documentation
#define ALIZE_AcousticSegmentation_cpp
Definition at line 71 of file AcousticSegmentation.cpp.
Function Documentation
void AcousticSegmentationProcess (Config & config, SegServer & resegOutputServer, SegServer & segmentServer, StatServer & ss, MixtureServer & ms, FeatureServer & fs, LabelServer & labelServer)
The iterative SAD process (Speech Activity Detection)
Definition at line 258 of file AcousticSegmentation.cpp.
References applyLengthRules(), computeTransitions(), displayAllSegments(), hmm::getNbState(), isStopAcousticSegmentation(), hmm::LoadState(), segAdaptationClass(), verbose, verboseLevel, and viterbiDecoding().
Referenced by launchAcousticSegmentationProcess().
void aggregateSegment (SegServer & segmentServer)
Aggregate successive segments labeled in the same way.
Attention
This procedure is run only if the parameter aggregateSegment is set to true.
Definition at line 144 of file AcousticSegmentation.cpp.
References endSeg(), and verbose.
Referenced by applyLengthRules().
void applyLengthRules (Config config, SegServer & segmentServer, hmm & actualHMM)
Apply length rules on the segments according to the config file.
Remarks
The successive segments with a same label for which the accumulated length is lower to the parameter class<n>Length are re-labelled with the previous label.
If the parameter aggregateSegment is set to true, the successive segments are aggregated within the same label.
Definition at line 177 of file AcousticSegmentation.cpp.
References aggregateSegment(), endSeg(), hmm::getLength(), hmm::getNbState(), hmm::getStateName(), and verbose.
Referenced by AcousticSegmentationProcess().
bool isStopAcousticSegmentation (Config & config, SegServer & previousSeg, SegServer & segmentServer, DoubleVector & actualViterbiProb, DoubleVector & previousViterbiProb, hmm & actualHMM)
Verifies whether the stop criteria (for adaptation/decoding step) are reached.
Returns
True if the segmentations (previous and current) between two consecutive SAD iterations are identical otherwise false
Remarks
The comparison between both segmentations is defined by :
the difference in the number of speakers
the difference in values of the Viterbi paths according to an epsilon value given in the configuration file
Attention
The parameter decodingEpsilon is required for step 2.
The value of the parameter decodingEpsilon defines the absolute margin of acceptable difference in values of Viterbi paths between both segmentations.
Definition at line 115 of file AcousticSegmentation.cpp.
References debug, isDifferentSegmentation(), isLessEpsilon(), and verbose.
Referenced by AcousticSegmentationProcess().
void launchAcousticSegmentationProcess (Config & config)
Launching of the iterative SAD (Speech Activity Detection) process.
Definition at line 354 of file AcousticSegmentation.cpp.
References AcousticSegmentationProcess(), displayAllSegmentsFromRef(), initializeClusters(), saveAcousticSegmentation(), verbose, and verifyClusterFile().
Referenced by main().
void segAdaptationClass (Config & config, MAPCfg & mapCfg, hmm & actualHMM, ObjectRefVector & classModelTab, SegServer & previousSeg, SegServer & actualSeg, StatServer & ss, FeatureServer & fs, MixtureServer & ms)
Adapts the gmm models of the n-state HMM according to the current segmentation.
Definition at line 82 of file AcousticSegmentation.cpp.
References adaptModel(), hmm::getDensity(), NoDataSpeakerVerification(), hmm::setDensity(), and verbose.
Referenced by AcousticSegmentationProcess().