LIA_RAL: LIA_SpkSeg/AcousticSegmentation/include/AcousticSegmentation.h File Reference
AcousticSegmentation.h File Reference
Declaration of speech activity detection (SAD) functions.
#include <alize.h>
Functions
void segAdaptationClass (Config &, MAPCfg &, hmm &, ObjectRefVector &, SegServer &, SegServer &, StatServer &, FeatureServer &, MixtureServer &)
Adapts the gmm models of the n-state HMM according to the current segmentation.
bool isStopAcousticSegmentation (Config &, SegServer &, SegServer &, DoubleVector &, DoubleVector &, hmm &)
Verifies whether the stop criteria (for adaptation/decoding step) are reached.
void aggregateSegment (SegServer &)
Aggregate successive segments labeled in the same way.
void applyLengthRules (Config, SegServer &, hmm &)
Apply length rules on the segments according to the config file.
void AcousticSegmentationProcess (Config &, SegServer &, SegServer &, StatServer &, MixtureServer &, FeatureServer &, LabelServer &)
The iterative SAD process (Speech Activity Detection)
void launchAcousticSegmentationProcess (Config &)
Launching of the iterative SAD (Speech Activity Detection) process.
Detailed Description
Declaration of speech activity detection (SAD) functions.
Author
LIA
Version
2.0
Date
june 2011
Definition in file AcousticSegmentation.h.
Function Documentation
void AcousticSegmentationProcess (Config & , SegServer & , SegServer & , StatServer & , MixtureServer & , FeatureServer & , LabelServer &)
The iterative SAD process (Speech Activity Detection)
Definition at line 258 of file AcousticSegmentation.cpp.
References applyLengthRules(), computeTransitions(), displayAllSegments(), hmm::getNbState(), isStopAcousticSegmentation(), hmm::LoadState(), segAdaptationClass(), verbose, verboseLevel, and viterbiDecoding().
Referenced by launchAcousticSegmentationProcess().
void aggregateSegment (SegServer & segmentServer)
Aggregate successive segments labeled in the same way.
Attention
This procedure is run only if the parameter aggregateSegment is set to true.
Definition at line 144 of file AcousticSegmentation.cpp.
References endSeg(), and verbose.
Referenced by applyLengthRules().
void applyLengthRules (Config config, SegServer & segmentServer, hmm & actualHMM)
Apply length rules on the segments according to the config file.
Remarks
The successive segments with a same label for which the accumulated length is lower to the parameter class<n>Length are re-labelled with the previous label.
If the parameter aggregateSegment is set to true, the successive segments are aggregated within the same label.
Definition at line 177 of file AcousticSegmentation.cpp.
References aggregateSegment(), endSeg(), hmm::getLength(), hmm::getNbState(), hmm::getStateName(), and verbose.
Referenced by AcousticSegmentationProcess().
bool isStopAcousticSegmentation (Config & config, SegServer & previousSeg, SegServer & segmentServer, DoubleVector & actualViterbiProb, DoubleVector & previousViterbiProb, hmm & actualHMM)
Verifies whether the stop criteria (for adaptation/decoding step) are reached.
Returns
True if the segmentations (previous and current) between two consecutive SAD iterations are identical otherwise false
Remarks
The comparison between both segmentations is defined by :
the difference in the number of speakers
the difference in values of the Viterbi paths according to an epsilon value given in the configuration file
Attention
The parameter decodingEpsilon is required for step 2.
The value of the parameter decodingEpsilon defines the absolute margin of acceptable difference in values of Viterbi paths between both segmentations.
Definition at line 115 of file AcousticSegmentation.cpp.
References debug, isDifferentSegmentation(), isLessEpsilon(), and verbose.
Referenced by AcousticSegmentationProcess().
void launchAcousticSegmentationProcess (Config &)
Launching of the iterative SAD (Speech Activity Detection) process.
Definition at line 354 of file AcousticSegmentation.cpp.
References AcousticSegmentationProcess(), displayAllSegmentsFromRef(), initializeClusters(), saveAcousticSegmentation(), verbose, and verifyClusterFile().
Referenced by main().
void segAdaptationClass (Config & , MAPCfg & , hmm & , ObjectRefVector & , SegServer & , SegServer & , StatServer & , FeatureServer & , MixtureServer &)
Adapts the gmm models of the n-state HMM according to the current segmentation.
Definition at line 82 of file AcousticSegmentation.cpp.
References adaptModel(), hmm::getDensity(), NoDataSpeakerVerification(), hmm::setDensity(), and verbose.
Referenced by AcousticSegmentationProcess().