LIA_RAL: include/Eigen/src/plugins/ArrayCwiseUnaryOps.h File Reference
ArrayCwiseUnaryOps.h File Reference
Macros
#define EIGEN_MAKE_SCALAR_CWISE_UNARY_OP(METHOD_NAME, FUNCTOR)
#define EIGEN_MAKE_SCALAR_CWISE_UNARY_OP(METHOD_NAME, FUNCTOR)
Functions
EIGEN_STRONG_INLINE const
CwiseUnaryOp
< internal::scalar_abs_op
< Scalar >, const Derived > abs () const
EIGEN_STRONG_INLINE const
CwiseUnaryOp
< internal::scalar_abs2_op
< Scalar >, const Derived > abs2 () const
const CwiseUnaryOp
< internal::scalar_exp_op
< Scalar >, const Derived > exp () const
const CwiseUnaryOp
< internal::scalar_log_op
< Scalar >, const Derived > log () const
const CwiseUnaryOp
< internal::scalar_sqrt_op
< Scalar >, const Derived > sqrt () const
const CwiseUnaryOp
< internal::scalar_cos_op
< Scalar >, const Derived > cos () const
const CwiseUnaryOp
< internal::scalar_sin_op
< Scalar >, const Derived > sin () const
const CwiseUnaryOp
< internal::scalar_acos_op
< Scalar >, const Derived > acos () const
const CwiseUnaryOp
< internal::scalar_asin_op
< Scalar >, const Derived > asin () const
const CwiseUnaryOp
< internal::scalar_tan_op
< Scalar >, Derived > tan () const
const CwiseUnaryOp
< internal::scalar_pow_op
< Scalar >, const Derived > pow (const Scalar &exponent) const
const CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const Derived > inverse () const
const CwiseUnaryOp
< internal::scalar_square_op
< Scalar >, const Derived > square () const
const CwiseUnaryOp
< internal::scalar_cube_op
< Scalar >, const Derived > cube () const
Macro Definition Documentation
#define EIGEN_MAKE_SCALAR_CWISE_UNARY_OP (METHOD_NAME, FUNCTOR)
Value:
inline const CwiseUnaryOp<std::binder2nd<FUNCTOR<Scalar> >, const Derived> \
  METHOD_NAME(const Scalar& s) const { \
    return CwiseUnaryOp<std::binder2nd<FUNCTOR<Scalar> >, const Derived> \
            (derived(), std::bind2nd(FUNCTOR<Scalar>(), s)); \
  }
#define EIGEN_MAKE_SCALAR_CWISE_UNARY_OP (METHOD_NAME, FUNCTOR)
Value:
inline const CwiseUnaryOp<std::binder2nd<FUNCTOR<Scalar> >, const Derived> \
  METHOD_NAME(const Scalar& s) const { \
    return CwiseUnaryOp<std::binder2nd<FUNCTOR<Scalar> >, const Derived> \
            (derived(), std::bind2nd(FUNCTOR<Scalar>(), s)); \
  }
Definition at line 189 of file ArrayCwiseUnaryOps.h.
Function Documentation
EIGEN_STRONG_INLINE const CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> abs () const
Returns
an expression of the coefficient-wise absolute value of *this
Example:
Output:
See Also
abs2()
Definition at line 11 of file ArrayCwiseUnaryOps.h.
Referenced by Eigen::HouseholderQR< MatrixType >::absDeterminant(), Eigen::ColPivHouseholderQR< MatrixType >::absDeterminant(), Eigen::FullPivHouseholderQR< MatrixType >::absDeterminant(), Eigen::Hyperplane< _Scalar, _AmbientDim >::absDistance(), Eigen::QuaternionBase< Derived >::angularDistance(), badSv(), Eigen::internal::bicgstab(), Eigen::MatrixBase< Derived >::blueNorm(), Eigen::cdiv(), Eigen::ColPivHouseholderQR< MatrixType >::compute(), Eigen::FullPivHouseholderQR< MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::EigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute(), DistribNorm::computeMeanStd(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::ComplexSchur< _MatrixType >::computeShift(), Eigen::internal::conjugate_gradient(), CovIntra(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::ei_abs(), Eigen::internal::EIGEN_MATHFUNC_RETVAL(), Eigen::internal::solve_retval< LDLT< _MatrixType, _UpLo >, Rhs >::evalTo(), Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::internal::image_retval< FullPivLU< _MatrixType > >::evalTo(), Eigen::IncompleteLUT< _Scalar >::factorize(), findNearestLLRInMatrix(), Eigen::RealSchur< _MatrixType >::findSmallSubdiagEntry(), Eigen::RealSchur< _MatrixType >::initFrancisQRStep(), Eigen::Hyperplane< _Scalar, _AmbientDim >::intersection(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::isApprox(), Eigen::MatrixBase< Derived >::isDiagonal(), Eigen::MatrixBase< Derived >::isLowerTriangular(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::isMuchSmallerThan(), Eigen::MatrixBase< Derived >::isUpperTriangular(), Eigen::internal::AmbiVector< _Scalar, _Index >::Iterator::Iterator(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::scalar_abs_op< Scalar >::operator()(), Eigen::internal::AmbiVector< _Scalar, _Index >::Iterator::operator++(), Eigen::internal::pabs(), Eigen::PardisoImpl< PardisoLU< MatrixType > >::pardisoInit(), Eigen::SparseSparseProduct< LhsNested, RhsNested >::pruned(), Eigen::IncompleteLUT< _Scalar >::QuickSplit(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), Eigen::FullPivHouseholderQR< _MatrixType >::rank(), Eigen::FullPivLU< _MatrixType >::rank(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 4 >::run(), Eigen::internal::abs_impl< Scalar >::run(), Eigen::internal::norm1_default_impl< Scalar, NumTraits< Scalar >::IsComplex >::run(), Eigen::internal::norm1_default_impl< Scalar, false >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::hypot_impl< Scalar >::run(), Eigen::QuaternionBase< Derived >::slerp(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), Eigen::internal::tridiagonal_qr_step(), and Eigen::internal::ldlt_inplace< Lower >::unblocked().
EIGEN_STRONG_INLINE const CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> abs2 () const
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
Output:
See Also
abs(), square()
Definition at line 24 of file ArrayCwiseUnaryOps.h.
Referenced by Eigen::MatrixBase< Derived >::blueNorm(), Eigen::ColPivHouseholderQR< MatrixType >::compute(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), Eigen::SimplicialLLT< _MatrixType, _UpLo >::determinant(), Eigen::SimplicialCholesky< _MatrixType, _UpLo >::determinant(), Eigen::ei_abs2(), Eigen::internal::EIGEN_MATHFUNC_RETVAL(), Eigen::IncompleteLUT< _Scalar >::factorize(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >::isApprox(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >::isMuchSmallerThan(), Eigen::MatrixBase< Derived >::isOrthogonal(), Eigen::internal::llt_rank_update_lower(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::scalar_abs2_op< Scalar >::operator()(), Eigen::internal::real_2x2_jacobi_svd(), Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run(), Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::stable_norm_kernel(), Eigen::internal::tridiagonal_qr_step(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
const CwiseUnaryOp<internal::scalar_acos_op<Scalar>, const Derived> acos () const inline
Returns
an expression of the coefficient-wise arc cosine of *this.
Example:
Output:
See Also
cos(), asin()
Definition at line 103 of file ArrayCwiseUnaryOps.h.
Referenced by Eigen::Quaternion< _Scalar >::angularDistance(), Eigen::QuaternionBase< Derived >::angularDistance(), Eigen::internal::scalar_acos_op< Scalar >::operator()(), Eigen::AngleAxis< Scalar >::operator=(), Eigen::internal::pacos(), Eigen::Quaternion< _Scalar >::slerp(), and Eigen::QuaternionBase< Derived >::slerp().
const CwiseUnaryOp<internal::scalar_asin_op<Scalar>, const Derived> asin () const inline
Returns
an expression of the coefficient-wise arc sine of *this.
Example:
Output:
See Also
sin(), acos()
Definition at line 116 of file ArrayCwiseUnaryOps.h.
Referenced by Eigen::internal::scalar_asin_op< Scalar >::operator()(), and Eigen::internal::pasin().
const CwiseUnaryOp<internal::scalar_cos_op<Scalar>, const Derived> cos () const inline
Returns
an expression of the coefficient-wise cosine of *this.
Example:
Output:
See Also
sin(), acos()
Definition at line 76 of file ArrayCwiseUnaryOps.h.
Referenced by boxMullerGenerator(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::ei_cos(), Eigen::internal::scalar_cos_op< Scalar >::operator()(), Eigen::QuaternionBase< Derived >::operator=(), and Eigen::internal::pcos().
const CwiseUnaryOp<internal::scalar_cube_op<Scalar>, const Derived> cube () const inline
Returns
an expression of the coefficient-wise cube of *this.
Example:
Output:
See Also
square(), pow()
Definition at line 184 of file ArrayCwiseUnaryOps.h.
const CwiseUnaryOp<internal::scalar_exp_op<Scalar>, const Derived> exp () const inline
Returns
an expression of the coefficient-wise exponential of *this.
Example:
Output:
See Also
pow(), log(), sin(), cos()
Definition at line 37 of file ArrayCwiseUnaryOps.h.
Referenced by TopGauss::compute(), Eigen::ei_exp(), expandLLR(), Kernel::k_function(), Kernel::kernel_rbf(), likelihoodGD(), Eigen::internal::scalar_exp_op< Scalar >::operator()(), Eigen::internal::pexp(), sigmoid_predict(), sigmoid_train(), WMAP(), WMAPGMM(), and WMAPGMMFixedPriors().
const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> inverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
Output:
See Also
operator/(), operator*()
Definition at line 158 of file ArrayCwiseUnaryOps.h.
const CwiseUnaryOp<internal::scalar_log_op<Scalar>, const Derived> log () const inline
Returns
an expression of the coefficient-wise logarithm of *this.
Example:
Output:
See Also
exp()
Definition at line 50 of file ArrayCwiseUnaryOps.h.
Referenced by accumulateStatEM(), accumulateStatViterbi(), adaptModelEMweightedFrames(), bicCrit(), boxMullerGenerator(), computeEntropy(), ComputePath(), createAndInitializeViterbiAccum(), Eigen::ei_log(), likelihoodGD(), likelihoodLoss(), Eigen::internal::scalar_log_op< Scalar >::operator()(), PldaTest::pldaMeanScoring(), PldaTest::pldaNativeScoring(), PldaTest::pldaScoringUnThreaded(), Eigen::internal::plog(), Eigen::internal::significant_decimals_default_impl< Scalar, NumTraits< Scalar >::IsInteger >::run(), and sigmoid_train().
const CwiseUnaryOp<internal::scalar_pow_op<Scalar>, const Derived> pow (const Scalar & exponent) const inline
Returns
an expression of the coefficient-wise power of *this to the given exponent.
Example:
Output:
See Also
exp(), log()
Definition at line 143 of file ArrayCwiseUnaryOps.h.
Referenced by Eigen::MatrixBase< Derived >::blueNorm(), computeFusion(), computeMAPOccDep(), computeModelBasedMAPOccDep(), computeWindowParam(), Eigen::ei_pow(), Eigen::internal::scalar_binary_pow_op< Scalar, OtherScalar >::operator()(), Eigen::internal::scalar_pow_op< Scalar >::operator()(), Eigen::internal::lpNorm_selector< Derived, p >::run(), and Eigen::internal::pow_default_impl< Scalar, NumTraits< Scalar >::IsInteger >::run().
const CwiseUnaryOp<internal::scalar_sin_op<Scalar>, const Derived> sin () const inline
Returns
an expression of the coefficient-wise sine of *this.
Example:
Output:
See Also
cos(), asin()
Definition at line 90 of file ArrayCwiseUnaryOps.h.
Referenced by Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::ei_sin(), Eigen::internal::scalar_sin_op< Scalar >::operator()(), Eigen::QuaternionBase< Derived >::operator=(), Eigen::internal::psin(), and Eigen::QuaternionBase< Derived >::slerp().
const CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> sqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Output:
See Also
pow(), square()
Definition at line 63 of file ArrayCwiseUnaryOps.h.
Referenced by FactorAnalysisStat::_init(), Eigen::internal::bicgstab(), Eigen::MatrixBase< Derived >::blueNorm(), boxMullerGenerator(), clusteringCriterionWithoutWorldInitOneGaus(), Eigen::EigenSolver< _MatrixType >::compute(), computeAdaptedTnorm(), computeAndStoreZnormParam(), DistribNorm::computeMeanStd(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots(), computeRSqrt(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::ComplexSchur< _MatrixType >::computeShift(), ComputeTestLFA(), computeWindowParam(), Eigen::internal::conjugate_gradient(), PldaTest::cosineDistance(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::distance(), Eigen::ei_sqrt(), Eigen::internal::EIGEN_MATHFUNC_RETVAL(), energyDetector(), error_bound(), Eigen::AlignedBox< _Scalar, _AmbientDim >::exteriorDistance(), Eigen::IncompleteLUT< _Scalar >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), getKLVector(), getMeanNorm(), getWeightNorm(), JFAAcc::initD(), lanczos_step(), PldaDev::lengthNorm(), PldaTest::lengthNorm(), Eigen::internal::llt_rank_update_lower(), loadTnormParam(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), mapDataToDistrib(), Eigen::internal::minimum_degree_ordering(), mixtureInitBySplit(), Eigen::MatrixBase< Derived >::norm(), Eigen::SparseMatrixBase< Derived >::norm(), normalizeMixture(), TVAcc::normStatisticsUnThreaded(), TVAcc::normTMatrix(), Eigen::internal::scalar_hypot_op< Scalar >::operator()(), Eigen::internal::scalar_sqrt_op< Scalar >::operator()(), Eigen::AngleAxis< Scalar >::operator=(), Eigen::MatrixBase< Derived >::operatorNorm(), TVAcc::orthonormalizeT(), JFAAcc::orthonormalizeV(), outputWeightVector(), predict(), Eigen::internal::psqrt(), purge(), Eigen::internal::real_2x2_jacobi_svd(), ritvec(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::internal::hypot_impl< Scalar >::run(), Eigen::internal::sqrt_default_impl< Scalar, NumTraits< Scalar >::IsInteger >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run(), Scoring(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), PldaDev::sphericalNuisanceNormalization(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), Eigen::MatrixBase< Derived >::stableNorm(), startv(), stpone(), svd_random2(), svdLAS2(), svm_svr_probability(), TrainTargetLFA(), TurnDetection(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), updateMeanAndCovParam(), and WMAP().
const CwiseUnaryOp<internal::scalar_square_op<Scalar>, const Derived> square () const inline
Returns
an expression of the coefficient-wise square of *this.
Example:
Output:
See Also
operator/(), operator*(), abs2()
Definition at line 171 of file ArrayCwiseUnaryOps.h.
const CwiseUnaryOp<internal::scalar_tan_op<Scalar>, Derived> tan () const inline
Returns
an expression of the coefficient-wise tan of *this.
Example:
Output:
See Also
cos(), sin()
Definition at line 129 of file ArrayCwiseUnaryOps.h.
Referenced by Eigen::internal::scalar_tan_op< Scalar >::operator()(), and Eigen::internal::ptan().