LIA_RAL: include/Eigen/src/plugins/BlockMethods.h File Reference
BlockMethods.h File Reference
Classes
struct NColsBlockXpr< N >
struct ConstNColsBlockXpr< N >
struct NRowsBlockXpr< N >
struct ConstNRowsBlockXpr< N >
Macros
#define EIGEN_BLOCKMETHODS_H
Typedefs
typedef Block< Derived,
internal::traits< Derived >
::RowsAtCompileTime,
1,!IsRowMajor > ColXpr
typedef const Block< const
Derived, internal::traits
< Derived >::RowsAtCompileTime,
1,!IsRowMajor > ConstColXpr
typedef Block< Derived,
1, internal::traits< Derived >
::ColsAtCompileTime,
IsRowMajor > RowXpr
typedef const Block< const
Derived, 1, internal::traits
< Derived >::ColsAtCompileTime,
IsRowMajor > ConstRowXpr
typedef Block< Derived,
internal::traits< Derived >
::RowsAtCompileTime, Dynamic,!IsRowMajor > ColsBlockXpr
typedef const Block< const
Derived, internal::traits
< Derived >::RowsAtCompileTime,
Dynamic,!IsRowMajor > ConstColsBlockXpr
typedef Block< Derived,
Dynamic, internal::traits
< Derived >::ColsAtCompileTime,
IsRowMajor > RowsBlockXpr
typedef const Block< const
Derived, Dynamic,
internal::traits< Derived >
::ColsAtCompileTime,
IsRowMajor > ConstRowsBlockXpr
Functions
Block< Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
Block< Derived > topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topRightCorner () const
Block< Derived > topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topLeftCorner () const
Block< Derived > bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomRightCorner () const
Block< Derived > bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomLeftCorner () const
RowsBlockXpr topRows (Index n)
template<int N>
NRowsBlockXpr< N >::Type topRows ()
template<int N>
ConstNRowsBlockXpr< N >::Type topRows () const
RowsBlockXpr bottomRows (Index n)
template<int N>
NRowsBlockXpr< N >::Type bottomRows ()
template<int N>
ConstNRowsBlockXpr< N >::Type bottomRows () const
RowsBlockXpr middleRows (Index startRow, Index numRows)
template<int N>
NRowsBlockXpr< N >::Type middleRows (Index startRow)
template<int N>
ConstNRowsBlockXpr< N >::Type middleRows (Index startRow) const
ColsBlockXpr leftCols (Index n)
template<int N>
NColsBlockXpr< N >::Type leftCols ()
template<int N>
ConstNColsBlockXpr< N >::Type leftCols () const
ColsBlockXpr rightCols (Index n)
template<int N>
NColsBlockXpr< N >::Type rightCols ()
template<int N>
ConstNColsBlockXpr< N >::Type rightCols () const
ColsBlockXpr middleCols (Index startCol, Index numCols)
template<int N>
NColsBlockXpr< N >::Type middleCols (Index startCol)
template<int N>
ConstNColsBlockXpr< N >::Type middleCols (Index startCol) const
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows,
BlockCols > block (Index startRow, Index startCol)
template<int BlockRows, int BlockCols>
const Block< const Derived,
BlockRows, BlockCols > block (Index startRow, Index startCol) const
ColXpr col (Index i)
RowXpr row (Index i)
Macro Definition Documentation
#define EIGEN_BLOCKMETHODS_H
Definition at line 13 of file DenseBase.h.
Typedef Documentation
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ColsBlockXpr
Definition at line 23 of file BlockMethods.h.
typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ColXpr
Definition at line 17 of file BlockMethods.h.
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> ConstColsBlockXpr
Definition at line 24 of file BlockMethods.h.
typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> ConstColXpr
Definition at line 18 of file BlockMethods.h.
typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowsBlockXpr
Definition at line 27 of file BlockMethods.h.
typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> ConstRowXpr
Definition at line 21 of file BlockMethods.h.
typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowsBlockXpr
Definition at line 26 of file BlockMethods.h.
typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> RowXpr
Definition at line 20 of file BlockMethods.h.
Function Documentation
const Block< const Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
This is the const version of block(Index,Index,Index,Index).
Definition at line 54 of file BlockMethods.h.
Referenced by Eigen::internal::kernel_retval< FullPivLU< _MatrixType > >::evalTo(), and Eigen::CommaInitializer< XprType >::operator,().
template<int BlockRows, int BlockCols> Block<Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters BlockRows and BlockCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 534 of file BlockMethods.h.
template<int BlockRows, int BlockCols> const Block<const Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index).
Definition at line 541 of file BlockMethods.h.
const Block< const Derived > bottomLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of bottomLeftCorner(Index, Index).
Definition at line 214 of file BlockMethods.h.
template<int CRows, int CCols> Block<Derived, CRows, CCols> bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 235 of file BlockMethods.h.
template<int CRows, int CCols> const Block<const Derived, CRows, CCols> bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
Definition at line 242 of file BlockMethods.h.
const Block< const Derived > bottomRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of bottomRightCorner(Index, Index).
Definition at line 169 of file BlockMethods.h.
template<int CRows, int CCols> Block<Derived, CRows, CCols> bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 190 of file BlockMethods.h.
template<int CRows, int CCols> const Block<const Derived, CRows, CCols> bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
Definition at line 197 of file BlockMethods.h.
ConstRowsBlockXpr bottomRows (Index n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of bottomRows(Index).
Definition at line 302 of file BlockMethods.h.
template<int N> NRowsBlockXpr<N>::Type bottomRows () inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 323 of file BlockMethods.h.
template<int N> ConstNRowsBlockXpr<N>::Type bottomRows () const inline
This is the const version of bottomRows<int>().
Definition at line 330 of file BlockMethods.h.
ConstColXpr col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See Also
row(), class Block
This is the const version of col().
Definition at line 552 of file BlockMethods.h.
Referenced by Eigen::MatrixBase< Derived >::applyHouseholderOnTheRight(), Eigen::MatrixBase< Derived >::applyOnTheRight(), Eigen::Reverse< MatrixType, Direction >::coeff(), Eigen::ProductBase< SelfadjointProductMatrix< Lhs, LhsMode, false, Rhs, RhsMode, false >, Lhs, Rhs >::coeff(), Eigen::CoeffBasedProduct< LhsNested, RhsNested, NestingFlags >::coeff(), Eigen::Reverse< MatrixType, Direction >::coeffRef(), Eigen::SparseTriangularView< MatrixType, Mode >::InnerIterator::col(), Eigen::SparseTriangularView< MatrixType, Mode >::ReverseInnerIterator::col(), Eigen::SwapWrapper< ExpressionType >::copyPacket(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyPacket(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyPacketByOuterInner(), Eigen::internal::solve_retval< FullPivHouseholderQR< _MatrixType >, Rhs >::evalTo(), Eigen::IncompleteLUT< _Scalar >::keep_diag::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::SimplicialCholeskyBase< Derived >::keep_diag::operator()(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::Flagged< ExpressionType, Added, Removed >::packet(), Eigen::Reverse< MatrixType, Direction >::packet(), Eigen::TransposeImpl< MatrixType, Dense >::packet(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), Eigen::TransposeImpl< MatrixType, Sparse >::InnerIterator::row(), Eigen::TransposeImpl< MatrixType, Sparse >::ReverseInnerIterator::row(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, RowMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, RowMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, ColMajor >::run(), Eigen::internal::sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Upper), UnrollCount, ClearOpposite >::run(), Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite >::run(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::Flagged< ExpressionType, Added, Removed >::writePacket(), Eigen::Reverse< MatrixType, Direction >::writePacket(), Eigen::TransposeImpl< MatrixType, Dense >::writePacket(), and Eigen::DenseCoeffsBase< Derived, WriteAccessors >::writePacket().
ConstColsBlockXpr leftCols (Index n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of leftCols(Index).
Definition at line 392 of file BlockMethods.h.
Referenced by Eigen::internal::solve_retval< HouseholderQR< _MatrixType >, Rhs >::evalTo().
template<int N> NColsBlockXpr<N>::Type leftCols () inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 413 of file BlockMethods.h.
template<int N> ConstNColsBlockXpr<N>::Type leftCols () const inline
This is the const version of leftCols<int>().
Definition at line 420 of file BlockMethods.h.
ConstColsBlockXpr middleCols (Index startCol, Index numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of middleCols(Index,Index).
Definition at line 481 of file BlockMethods.h.
template<int N> NColsBlockXpr<N>::Type middleCols (Index startCol) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block
Parameters
startCol the index of the first column in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 503 of file BlockMethods.h.
template<int N> ConstNColsBlockXpr<N>::Type middleCols (Index startCol) const inline
This is the const version of middleCols<int>().
Definition at line 510 of file BlockMethods.h.
ConstRowsBlockXpr middleRows (Index startRow, Index numRows) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
numRows the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of middleRows(Index,Index).
Definition at line 347 of file BlockMethods.h.
template<int N> NRowsBlockXpr<N>::Type middleRows (Index startRow) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block
Parameters
startRow the index of the first row in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 369 of file BlockMethods.h.
template<int N> ConstNRowsBlockXpr<N>::Type middleRows (Index startRow) const inline
This is the const version of middleRows<int>().
Definition at line 376 of file BlockMethods.h.
ConstColsBlockXpr rightCols (Index n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of rightCols(Index).
Definition at line 436 of file BlockMethods.h.
template<int N> NColsBlockXpr<N>::Type rightCols () inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 457 of file BlockMethods.h.
template<int N> ConstNColsBlockXpr<N>::Type rightCols () const inline
This is the const version of rightCols<int>().
Definition at line 464 of file BlockMethods.h.
ConstRowXpr row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See Also
col(), class Block
This is the const version of row().
Definition at line 569 of file BlockMethods.h.
Referenced by Eigen::MatrixBase< Derived >::applyHouseholderOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::Reverse< MatrixType, Direction >::coeff(), Eigen::CoeffBasedProduct< LhsNested, RhsNested, NestingFlags >::coeff(), Eigen::Reverse< MatrixType, Direction >::coeffRef(), Eigen::TransposeImpl< MatrixType, Sparse >::InnerIterator::col(), Eigen::TransposeImpl< MatrixType, Sparse >::ReverseInnerIterator::col(), Eigen::SparseDenseOuterProduct< Lhs, Rhs, Tr >::InnerIterator::col(), Eigen::SwapWrapper< ExpressionType >::copyPacket(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyPacket(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyPacketByOuterInner(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::NestByValue< ExpressionType >::packet(), Eigen::Flagged< ExpressionType, Added, Removed >::packet(), Eigen::Reverse< MatrixType, Direction >::packet(), Eigen::TransposeImpl< MatrixType, Dense >::packet(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), Eigen::IncompleteLUT< _Scalar >::QuickSplit(), Eigen::SparseTriangularView< MatrixType, Mode >::InnerIterator::row(), Eigen::SparseDenseOuterProduct< Lhs, Rhs, Tr >::InnerIterator::row(), Eigen::SparseTriangularView< MatrixType, Mode >::ReverseInnerIterator::row(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Upper), UnrollCount, ClearOpposite >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite >::run(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::NestByValue< ExpressionType >::writePacket(), Eigen::Flagged< ExpressionType, Added, Removed >::writePacket(), Eigen::Reverse< MatrixType, Direction >::writePacket(), Eigen::TransposeImpl< MatrixType, Dense >::writePacket(), and Eigen::DenseCoeffsBase< Derived, WriteAccessors >::writePacket().
const Block< const Derived > topLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of topLeftCorner(Index, Index).
Definition at line 124 of file BlockMethods.h.
template<int CRows, int CCols> Block<Derived, CRows, CCols> topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 145 of file BlockMethods.h.
template<int CRows, int CCols> const Block<const Derived, CRows, CCols> topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
Definition at line 152 of file BlockMethods.h.
const Block< const Derived > topRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of topRightCorner(Index, Index).
Definition at line 78 of file BlockMethods.h.
template<int CRows, int CCols> Block<Derived, CRows, CCols> topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 99 of file BlockMethods.h.
template<int CRows, int CCols> const Block<const Derived, CRows, CCols> topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
Definition at line 106 of file BlockMethods.h.
ConstRowsBlockXpr topRows (Index n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
This is the const version of topRows(Index).
Definition at line 258 of file BlockMethods.h.
template<int N> NRowsBlockXpr<N>::Type topRows () inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 279 of file BlockMethods.h.
template<int N> ConstNRowsBlockXpr<N>::Type topRows () const inline
This is the const version of topRows<int>().
Definition at line 286 of file BlockMethods.h.