LIA_RAL: LIA_Utils/BNGram/include/BNGram.h File Reference
BNGram.h File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
Classes
struct BNgramNode
class BNgram
Functions
void testBNgram (Config &config)
Function Documentation
void testBNgram (Config & config)
Definition at line 167 of file BNGram.cpp.
References BNgram::addSymb(), BNgram::beginSeq(), BNgram::endSeq(), and BNgram::show().
Referenced by main().