LIA_RAL: Eigen::Cwise< ExpressionType > Class Template Reference
Eigen::Cwise< ExpressionType > Class Template Reference
Pseudo expression providing additional coefficient-wise operations.
#include <Cwise.h>
Public Types
typedef internal::traits
< ExpressionType >::Scalar Scalar
typedef internal::conditional
< internal::must_nest_by_value
< ExpressionType >::ret,
ExpressionType, const
ExpressionType & >::type ExpressionTypeNested
typedef CwiseUnaryOp
< internal::scalar_add_op
< Scalar >, ExpressionType > ScalarAddReturnType
Public Member Functions
Cwise (const ExpressionType &matrix)
const ExpressionType & _expression () const
template<typename OtherDerived >
const EIGEN_CWISE_PRODUCT_RETURN_TYPE (ExpressionType, OtherDerived) operator*(const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const EIGEN_CWISE_BINOP_RETURN_TYPE (internal::scalar_quotient_op) operator/(const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const
EIGEN_CWISE_BINOP_RETURN_TYPE()
internal::scalar_min_op() min (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const
EIGEN_CWISE_BINOP_RETURN_TYPE()
internal::scalar_max_op() max (const MatrixBase< OtherDerived > &other) const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_abs_op) abs() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_abs2_op) abs2() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_square_op) square() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_cube_op) cube() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_inverse_op) inverse() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_sqrt_op) sqrt() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_exp_op) exp() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_log_op) log() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_cos_op) cos() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_sin_op) sin() const
const EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_pow_op) pow(const Scalar &exponent) const
const ScalarAddReturnType operator+ (const Scalar &scalar) const
ExpressionType & operator+= (const Scalar &scalar)
const ScalarAddReturnType operator- (const Scalar &scalar) const
ExpressionType & operator-= (const Scalar &scalar)
template<typename OtherDerived >
ExpressionType & operator*= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
ExpressionType & operator/= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
const EIGEN_CWISE_BINOP_RETURN_TYPE (std::less) operator<(const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const EIGEN_CWISE_BINOP_RETURN_TYPE (std::less_equal) operator<
template<typename OtherDerived >
const EIGEN_CWISE_BINOP_RETURN_TYPE (std::greater) operator>(const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const EIGEN_CWISE_BINOP_RETURN_TYPE (std::greater_equal) operator>
template<typename OtherDerived >
const EIGEN_CWISE_BINOP_RETURN_TYPE (std::equal_to) operator
template<typename OtherDerived >
const EIGEN_CWISE_BINOP_RETURN_TYPE (std::not_equal_to) operator!
const EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::less) operator<(Scalar s) const
const EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::less_equal) operator<
const EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::greater) operator>(Scalar s) const
const EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::greater_equal) operator>
const EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::equal_to) operator
const EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::not_equal_to) operator!
Protected Attributes
ExpressionTypeNested m_matrix
Related Functions
(Note that these are not member functions.)
const ScalarAddReturnType operator+ (const Scalar &scalar, const Cwise &mat)
Detailed Description
template<typename ExpressionType>
class Eigen::Cwise< ExpressionType >
Pseudo expression providing additional coefficient-wise operations.
Parameters
ExpressionType the type of the object on which to do coefficient-wise operations
This class represents an expression with additional coefficient-wise features. It is the return type of MatrixBase::cwise() and most of the time this is the only way it is used.
Example:
Output:
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizingEigen by defining the preprocessor symbol EIGEN_CWISE_PLUGIN.
See Also
MatrixBase::cwise() const, MatrixBase::cwise()
Definition at line 50 of file Cwise.h.
Member Typedef Documentation
template<typename ExpressionType> typedef internal::conditional<internal::must_nest_by_value<ExpressionType>::ret, ExpressionType, const ExpressionType&>::type Eigen::Cwise< ExpressionType >::ExpressionTypeNested
Definition at line 56 of file Cwise.h.
template<typename ExpressionType> typedef internal::traits<ExpressionType>::Scalar Eigen::Cwise< ExpressionType >::Scalar
Definition at line 54 of file Cwise.h.
template<typename ExpressionType> typedef CwiseUnaryOp<internal::scalar_add_op<Scalar>, ExpressionType> Eigen::Cwise< ExpressionType >::ScalarAddReturnType
Definition at line 57 of file Cwise.h.
Constructor & Destructor Documentation
template<typename ExpressionType> Eigen::Cwise< ExpressionType >::Cwise (const ExpressionType & matrix) inline
Definition at line 59 of file Cwise.h.
Member Function Documentation
template<typename ExpressionType> const ExpressionType& Eigen::Cwise< ExpressionType >::_expression () const inline
Definition at line 62 of file Cwise.h.
References Eigen::Cwise< ExpressionType >::m_matrix.
Referenced by Eigen::Cwise< ExpressionType >::max(), and Eigen::Cwise< ExpressionType >::min().
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE (internal::scalar_quotient_op) const
Referenced by Eigen::Cwise< ExpressionType >::max(), and Eigen::Cwise< ExpressionType >::min().
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE (std::less) const
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE (std::less_equal)
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE (std::greater) const
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE (std::greater_equal)
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE (std::equal_to)
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE (std::not_equal_to)
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::less) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::less_equal)
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::greater) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::greater_equal)
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::equal_to)
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_COMP_TO_SCALAR_RETURN_TYPE (std::not_equal_to)
template<typename ExpressionType> template<typename OtherDerived > const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_PRODUCT_RETURN_TYPE (ExpressionType , OtherDerived) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_abs_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_abs2_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_square_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_cube_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_inverse_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_sqrt_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_exp_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_log_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_cos_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_sin_op) const
template<typename ExpressionType> const Eigen::Cwise< ExpressionType >::EIGEN_CWISE_UNOP_RETURN_TYPE (internal::scalar_pow_op) const
template<typename ExpressionType> template<typename OtherDerived > const EIGEN_CWISE_BINOP_RETURN_TYPE() internal::scalar_max_op() Eigen::Cwise< ExpressionType >::max (const MatrixBase< OtherDerived > & other) const inline
Deprecated:
ArrayBase::max()
Definition at line 81 of file Cwise.h.
References Eigen::Cwise< ExpressionType >::_expression(), and Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE().
template<typename ExpressionType> template<typename OtherDerived > const EIGEN_CWISE_BINOP_RETURN_TYPE() internal::scalar_min_op() Eigen::Cwise< ExpressionType >::min (const MatrixBase< OtherDerived > & other) const inline
Deprecated:
ArrayBase::min()
Definition at line 75 of file Cwise.h.
References Eigen::Cwise< ExpressionType >::_expression(), and Eigen::Cwise< ExpressionType >::EIGEN_CWISE_BINOP_RETURN_TYPE().
template<typename ExpressionType> template<typename OtherDerived > ExpressionType& Eigen::Cwise< ExpressionType >::operator*= (const MatrixBase< OtherDerived > & other) inline
template<typename ExpressionType> const ScalarAddReturnType Eigen::Cwise< ExpressionType >::operator+ (const Scalar & scalar) const
template<typename ExpressionType > ExpressionType & Eigen::Cwise< ExpressionType >::operator+= (const Scalar & scalar) inline
Deprecated:
ArrayBase::operator+=(Scalar)
Definition at line 276 of file CwiseOperators.h.
template<typename ExpressionType > const Cwise< ExpressionType >::ScalarAddReturnType Eigen::Cwise< ExpressionType >::operator- (const Scalar & scalar) const inline
Deprecated:
ArrayBase::operator-(Scalar)
Definition at line 284 of file CwiseOperators.h.
template<typename ExpressionType > ExpressionType & Eigen::Cwise< ExpressionType >::operator-= (const Scalar & scalar) inline
Deprecated:
ArrayBase::operator-=(Scalar)
Definition at line 291 of file CwiseOperators.h.
template<typename ExpressionType > template<typename OtherDerived > ExpressionType & Eigen::Cwise< ExpressionType >::operator/= (const MatrixBase< OtherDerived > & other) inline
Deprecated:
ArrayBase::operator/=()
Definition at line 81 of file CwiseOperators.h.
Friends And Related Function Documentation
template<typename ExpressionType> const ScalarAddReturnType operator+ (const Scalar & scalar, const Cwise< ExpressionType > & mat) friend
Definition at line 101 of file Cwise.h.
Member Data Documentation
template<typename ExpressionType> ExpressionTypeNested Eigen::Cwise< ExpressionType >::m_matrix protected
Definition at line 160 of file Cwise.h.
Referenced by Eigen::Cwise< ExpressionType >::_expression().
The documentation for this class was generated from the following files:
include/Eigen/src/Eigen2Support/Cwise.h
include/Eigen/src/Eigen2Support/CwiseOperators.h