LIA_RAL: Eigen::PermutationBase< Derived > Class Template Reference
Eigen::PermutationBase< Derived > Class Template Reference
Base class for permutations.
#include <PermutationMatrix.h>
Public Types
enum {
Flags = Traits::Flags, CoeffReadCost = Traits::CoeffReadCost, RowsAtCompileTime = Traits::RowsAtCompileTime, ColsAtCompileTime = Traits::ColsAtCompileTime,
MaxRowsAtCompileTime = Traits::MaxRowsAtCompileTime, MaxColsAtCompileTime = Traits::MaxColsAtCompileTime
}
typedef Traits::IndicesType IndicesType
typedef Traits::Scalar Scalar
typedef Traits::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime,
0, MaxRowsAtCompileTime,
MaxColsAtCompileTime > DenseMatrixType
typedef PermutationMatrix
< IndicesType::SizeAtCompileTime,
IndicesType::MaxSizeAtCompileTime,
Index > PlainPermutationType
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
template<typename OtherDerived >
Derived & operator= (const PermutationBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const TranspositionsBase< OtherDerived > &tr)
Derived & operator= (const PermutationBase &other)
Index rows () const
Index cols () const
Index size () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
const IndicesType & indices () const
IndicesType & indices ()
void resize (Index size)
void setIdentity ()
void setIdentity (Index size)
Derived & applyTranspositionOnTheLeft (Index i, Index j)
Derived & applyTranspositionOnTheRight (Index i, Index j)
Transpose< PermutationBase > inverse () const
Transpose< PermutationBase > transpose () const
template<typename Other >
PlainPermutationType operator* (const PermutationBase< Other > &other) const
template<typename Other >
PlainPermutationType operator* (const Transpose< PermutationBase< Other > > &other) const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
template<typename OtherDerived >
void assignTranspose (const PermutationBase< OtherDerived > &other)
template<typename Lhs , typename Rhs >
void assignProduct (const Lhs &lhs, const Rhs &rhs)
Private Types
typedef internal::traits< Derived > Traits
typedef EigenBase< Derived > Base
Friends
template<typename Other >
PlainPermutationType operator* (const Transpose< PermutationBase< Other > > &other, const PermutationBase &perm)
Detailed Description
template<typename Derived>
class Eigen::PermutationBase< Derived >
Base class for permutations.
Parameters
Derived the derived class
This class is the base class for all expressions representing a permutation matrix, internally stored as a vector of integers. The convention followed here is that if is a permutation, the corresponding permutation matrix is such that if is the canonical basis, we have:
This convention ensures that for any two permutations , we have:
Permutation matrices are square and invertible.
Notice that in addition to the member functions and operators listed here, there also are non-member operator* to multiply any kind of permutation object with any kind of matrix expression (MatrixBase) on either side.
See Also
class PermutationMatrix, class PermutationWrapper
Definition at line 53 of file PermutationMatrix.h.
Member Typedef Documentation
template<typename Derived> typedef EigenBase<Derived> Eigen::PermutationBase< Derived >::Base private
Definition at line 56 of file PermutationMatrix.h.
template<typename Derived> typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime,0,MaxRowsAtCompileTime,MaxColsAtCompileTime> Eigen::PermutationBase< Derived >::DenseMatrixType
Definition at line 72 of file PermutationMatrix.h.
template<typename Derived> typedef Traits::Index Eigen::PermutationBase< Derived >::Index
Definition at line 70 of file PermutationMatrix.h.
template<typename Derived> typedef Traits::IndicesType Eigen::PermutationBase< Derived >::IndicesType
Definition at line 60 of file PermutationMatrix.h.
template<typename Derived> typedef PermutationMatrix<IndicesType::SizeAtCompileTime,IndicesType::MaxSizeAtCompileTime,Index> Eigen::PermutationBase< Derived >::PlainPermutationType
Definition at line 74 of file PermutationMatrix.h.
template<typename Derived> typedef Traits::Scalar Eigen::PermutationBase< Derived >::Scalar
Definition at line 69 of file PermutationMatrix.h.
template<typename Derived> typedef internal::traits<Derived> Eigen::PermutationBase< Derived >::Traits private
Definition at line 55 of file PermutationMatrix.h.
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
Flags
CoeffReadCost
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 61 of file PermutationMatrix.h.
Member Function Documentation
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::applyTranspositionOnTheLeft (Index i, Index j) inline
Multiplies *this by the transposition on the left.
Returns
a reference to *this.
Warning
This is much slower than applyTranspositionOnTheRight(int,int): this has linear complexity and requires a lot of branching.
See Also
applyTranspositionOnTheRight(int,int)
Definition at line 171 of file PermutationMatrix.h.
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight (Index i, Index j) inline
Multiplies *this by the transposition on the right.
Returns
a reference to *this.
This is a fast operation, it only consists in swapping two indices.
See Also
applyTranspositionOnTheLeft(int,int)
Definition at line 190 of file PermutationMatrix.h.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=().
template<typename Derived> template<typename Lhs , typename Rhs > void Eigen::PermutationBase< Derived >::assignProduct (const Lhs & lhs, const Rhs & rhs) inline protected
Definition at line 221 of file PermutationMatrix.h.
Referenced by Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::PermutationMatrix().
template<typename Derived> template<typename OtherDerived > void Eigen::PermutationBase< Derived >::assignTranspose (const PermutationBase< OtherDerived > & other) inline protected
Definition at line 216 of file PermutationMatrix.h.
template<typename Derived> Index Eigen::PermutationBase< Derived >::cols (void) const inline
Returns
the number of columns
Definition at line 111 of file PermutationMatrix.h.
template<typename Derived> template<typename DenseDerived > void Eigen::PermutationBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const inline
Definition at line 118 of file PermutationMatrix.h.
template<typename Derived> const IndicesType& Eigen::PermutationBase< Derived >::indices () const inline
const version of indices().
Definition at line 136 of file PermutationMatrix.h.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::assignProduct(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::assignTranspose(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::cols(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::evalTo(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::resize(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::rows(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::size().
template<typename Derived> IndicesType& Eigen::PermutationBase< Derived >::indices () inline
Returns
a reference to the stored array representing the permutation.
Definition at line 138 of file PermutationMatrix.h.
template<typename Derived> Transpose<PermutationBase> Eigen::PermutationBase< Derived >::inverse () const inline
Returns
the inverse permutation matrix.
Note
Definition at line 201 of file PermutationMatrix.h.
template<typename Derived> template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const PermutationBase< Other > & other) const inline
Returns
the product permutation matrix.
Note
Definition at line 235 of file PermutationMatrix.h.
template<typename Derived> template<typename Other > PlainPermutationType Eigen::PermutationBase< Derived >::operator* (const Transpose< PermutationBase< Other > > & other) const inline
Returns
the product of a permutation with another inverse permutation.
Note
Definition at line 243 of file PermutationMatrix.h.
template<typename Derived> template<typename OtherDerived > Derived& Eigen::PermutationBase< Derived >::operator= (const PermutationBase< OtherDerived > & other) inline
Copies the other permutation into *this
Definition at line 80 of file PermutationMatrix.h.
Referenced by Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=().
template<typename Derived> template<typename OtherDerived > Derived& Eigen::PermutationBase< Derived >::operator= (const TranspositionsBase< OtherDerived > & tr) inline
Assignment from the Transpositions tr
Definition at line 88 of file PermutationMatrix.h.
template<typename Derived> Derived& Eigen::PermutationBase< Derived >::operator= (const PermutationBase< Derived > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
Definition at line 100 of file PermutationMatrix.h.
template<typename Derived> void Eigen::PermutationBase< Derived >::resize (Index size) inline
Resizes to given size.
Definition at line 142 of file PermutationMatrix.h.
Referenced by Eigen::internal::minimum_degree_ordering(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity().
template<typename Derived> Index Eigen::PermutationBase< Derived >::rows (void) const inline
Returns
the number of rows
Definition at line 108 of file PermutationMatrix.h.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::assignProduct(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::assignTranspose(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::evalTo().
template<typename Derived> void Eigen::PermutationBase< Derived >::setIdentity () inline
Sets *this to be the identity permutation matrix
Definition at line 148 of file PermutationMatrix.h.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity().
template<typename Derived> void Eigen::PermutationBase< Derived >::setIdentity (Index size) inline
Sets *this to be the identity permutation matrix of given size.
Definition at line 156 of file PermutationMatrix.h.
template<typename Derived> Index Eigen::PermutationBase< Derived >::size () const inline
Returns
the size of a side of the respective square matrix, i.e., the number of indices
Definition at line 114 of file PermutationMatrix.h.
Referenced by Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::_solve(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::dumpMemory(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity().
template<typename Derived> DenseMatrixType Eigen::PermutationBase< Derived >::toDenseMatrix () const inline
Returns
a Matrix object initialized from this permutation matrix. Notice that it is inefficient to return this Matrix object by value. For efficiency, favor using the Matrix constructor taking EigenBase objects.
Definition at line 130 of file PermutationMatrix.h.
template<typename Derived> Transpose<PermutationBase> Eigen::PermutationBase< Derived >::transpose () const inline
Returns
the tranpose permutation matrix.
Note
Definition at line 207 of file PermutationMatrix.h.
Friends And Related Function Documentation
template<typename Derived> template<typename Other > PlainPermutationType operator* (const Transpose< PermutationBase< Other > > & other, const PermutationBase< Derived > & perm) friend
Returns
the product of an inverse permutation with another permutation.
Note
Definition at line 251 of file PermutationMatrix.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/PermutationMatrix.h