LIA_RAL: Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
Represents a diagonal matrix with its storage.
#include <DiagonalMatrix.h>
Public Types
typedef internal::traits
< DiagonalMatrix >
::DiagonalVectorType DiagonalVectorType
typedef const DiagonalMatrix & Nested
typedef _Scalar Scalar
typedef internal::traits
< DiagonalMatrix >
::StorageKind StorageKind
typedef internal::traits
< DiagonalMatrix >::Index Index
Public Types inherited from Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >
enum
typedef internal::traits
< DiagonalMatrix< _Scalar,
SizeAtCompileTime,
MaxSizeAtCompileTime >
>::DiagonalVectorType DiagonalVectorType
typedef DiagonalVectorType::Scalar Scalar
typedef
DiagonalVectorType::RealScalar RealScalar
typedef internal::traits
< DiagonalMatrix< _Scalar,
SizeAtCompileTime,
MaxSizeAtCompileTime >
>::StorageKind StorageKind
typedef internal::traits
< DiagonalMatrix< _Scalar,
SizeAtCompileTime,
MaxSizeAtCompileTime >
>::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime,
0, MaxRowsAtCompileTime,
MaxColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType DenseType
typedef DiagonalMatrix< Scalar,
DiagonalVectorType::SizeAtCompileTime,
DiagonalVectorType::MaxSizeAtCompileTime > PlainObject
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
const DiagonalVectorType & diagonal () const
DiagonalVectorType & diagonal ()
DiagonalMatrix ()
DiagonalMatrix (Index dim)
DiagonalMatrix (const Scalar &x, const Scalar &y)
DiagonalMatrix (const Scalar &x, const Scalar &y, const Scalar &z)
template<typename OtherDerived >
DiagonalMatrix (const DiagonalBase< OtherDerived > &other)
DiagonalMatrix (const DiagonalMatrix &other)
template<typename OtherDerived >
DiagonalMatrix (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
DiagonalMatrix & operator= (const DiagonalBase< OtherDerived > &other)
DiagonalMatrix & operator= (const DiagonalMatrix &other)
void resize (Index size)
void setZero ()
void setZero (Index size)
void setIdentity ()
void setIdentity (Index size)
Public Member Functions inherited from Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >
const DiagonalMatrix< _Scalar,
SizeAtCompileTime,
MaxSizeAtCompileTime > & derived () const
DiagonalMatrix< _Scalar,
SizeAtCompileTime,
MaxSizeAtCompileTime > & derived ()
DenseMatrixType toDenseMatrix () const
void evalTo (MatrixBase< DenseDerived > &other) const
void addTo (MatrixBase< DenseDerived > &other) const
void subTo (MatrixBase< DenseDerived > &other) const
const DiagonalVectorType & diagonal () const
DiagonalVectorType & diagonal ()
Index rows () const
Index cols () const
const DiagonalProduct
< MatrixDerived,
DiagonalMatrix< _Scalar,
SizeAtCompileTime,
MaxSizeAtCompileTime >
, OnTheLeft > operator* (const MatrixBase< MatrixDerived > &matrix) const
const DiagonalWrapper< const
CwiseUnaryOp
< internal::scalar_multiple_op
< Scalar >, const
DiagonalVectorType > > operator* (const Scalar &scalar) const
const DiagonalWrapper< const
CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const
DiagonalVectorType > > inverse () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
DiagonalVectorType m_diagonal
Detailed Description
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime>
class Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >
Represents a diagonal matrix with its storage.
Parameters
_Scalar the type of coefficients
SizeAtCompileTime the dimension of the matrix, or Dynamic
MaxSizeAtCompileTime the dimension of the matrix, or Dynamic. This parameter is optional and defaults to SizeAtCompileTime. Most of the time, you do not need to specify it.
See Also
class DiagonalWrapper
Definition at line 130 of file DiagonalMatrix.h.
Member Typedef Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::DiagonalVectorType Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalVectorType
Definition at line 135 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::Index Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::Index
Definition at line 139 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef const DiagonalMatrix& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::Nested
Definition at line 136 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef _Scalar Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::Scalar
Definition at line 137 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> typedef internal::traits<DiagonalMatrix>::StorageKind Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::StorageKind
Definition at line 138 of file DiagonalMatrix.h.
Constructor & Destructor Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix () inline
Default constructor without initialization
Definition at line 154 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (Index dim) inline
Constructs a diagonal matrix with given dimension
Definition at line 157 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const Scalar & x, const Scalar & y) inline
2D constructor.
Definition at line 160 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const Scalar & x, const Scalar & y, const Scalar & z) inline
3D constructor.
Definition at line 163 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const DiagonalBase< OtherDerived > & other) inline
Copy constructor.
Definition at line 167 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & other) inline
copy constructor. prevent a default copy constructor from hiding the other templated constructor
Definition at line 171 of file DiagonalMatrix.h.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix (const MatrixBase< OtherDerived > & other) inline explicit
generic constructor from expression of the diagonal coefficients
Definition at line 176 of file DiagonalMatrix.h.
Member Function Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> const DiagonalVectorType& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal () const inline
const version of diagonal().
Definition at line 149 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
Referenced by Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=().
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> DiagonalVectorType& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal () inline
Returns
a reference to the stored vector of diagonal coefficients.
Definition at line 151 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> template<typename OtherDerived > DiagonalMatrix& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator= (const DiagonalBase< OtherDerived > & other) inline
Copy operator.
Definition at line 181 of file DiagonalMatrix.h.
References Eigen::DiagonalBase< Derived >::diagonal(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> DiagonalMatrix& Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator= (const DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
Definition at line 191 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize (Index size) inline
Resizes to given size.
Definition at line 199 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity () inline
Sets this matrix to be the identity matrix of the current size.
Definition at line 205 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity (Index size) inline
Sets this matrix to be the identity matrix of the given size.
Definition at line 207 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero () inline
Sets all coefficients to zero.
Definition at line 201 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> void Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero (Index size) inline
Resizes and sets all coefficients to zero.
Definition at line 203 of file DiagonalMatrix.h.
References Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal.
Member Data Documentation
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime> DiagonalVectorType Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::m_diagonal protected
Definition at line 144 of file DiagonalMatrix.h.
Referenced by Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::resize(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setIdentity(), and Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::setZero().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/DiagonalMatrix.h