LIA_RAL: Eigen::internal::AmbiVector< _Scalar, _Index > Class Template Reference
Eigen::internal::AmbiVector< _Scalar, _Index > Class Template Reference
#include <AmbiVector.h>
Classes
class Iterator
struct ListEl
Public Types
typedef _Scalar Scalar
typedef _Index Index
typedef NumTraits< Scalar >::Real RealScalar
Public Member Functions
AmbiVector (Index size)
void init (double estimatedDensity)
void init (int mode)
Index nonZeros () const
void setBounds (Index start, Index end)
void setZero ()
void restart ()
Scalar & coeffRef (Index i)
Scalar & coeff (Index i)
~AmbiVector ()
void resize (Index size)
Index size () const
Protected Member Functions
void reallocate (Index size)
void reallocateSparse ()
Protected Attributes
Scalar * m_buffer
Scalar m_zero
Index m_size
Index m_start
Index m_end
Index m_allocatedSize
Index m_allocatedElements
Index m_mode
Index m_llStart
Index m_llCurrent
Index m_llSize
Detailed Description
template<typename _Scalar, typename _Index>
class Eigen::internal::AmbiVector< _Scalar, _Index >
Definition at line 23 of file AmbiVector.h.
Member Typedef Documentation
template<typename _Scalar , typename _Index > typedef _Index Eigen::internal::AmbiVector< _Scalar, _Index >::Index
Definition at line 27 of file AmbiVector.h.
template<typename _Scalar , typename _Index > typedef NumTraits<Scalar>::Real Eigen::internal::AmbiVector< _Scalar, _Index >::RealScalar
Definition at line 28 of file AmbiVector.h.
template<typename _Scalar , typename _Index > typedef _Scalar Eigen::internal::AmbiVector< _Scalar, _Index >::Scalar
Definition at line 26 of file AmbiVector.h.
Constructor & Destructor Documentation
template<typename _Scalar , typename _Index > Eigen::internal::AmbiVector< _Scalar, _Index >::AmbiVector (Index size) inline
Definition at line 30 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _Index >::resize().
template<typename _Scalar , typename _Index > Eigen::internal::AmbiVector< _Scalar, _Index >::~AmbiVector () inline
Definition at line 52 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _Index >::m_buffer.
Member Function Documentation
template<typename _Scalar , typename _Index > _Scalar & Eigen::internal::AmbiVector< _Scalar, _Index >::coeff (Index i)
Definition at line 251 of file AmbiVector.h.
References eigen_assert, EIGEN_RESTRICT, Eigen::IsDense, and Eigen::IsSparse.
template<typename _Scalar , typename _Index > _Scalar & Eigen::internal::AmbiVector< _Scalar, _Index >::coeffRef (Index i)
Definition at line 182 of file AmbiVector.h.
References eigen_assert, eigen_internal_assert, EIGEN_RESTRICT, Eigen::internal::AmbiVector< _Scalar, _Index >::ListEl::index, Eigen::IsDense, Eigen::IsSparse, Eigen::internal::AmbiVector< _Scalar, _Index >::ListEl::next, and Eigen::internal::AmbiVector< _Scalar, _Index >::ListEl::value.
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::init (double estimatedDensity)
Definition at line 134 of file AmbiVector.h.
References Eigen::IsDense, and Eigen::IsSparse.
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::init (int mode)
Definition at line 143 of file AmbiVector.h.
References Eigen::IsSparse.
template<typename _Scalar , typename _Index > _Index Eigen::internal::AmbiVector< _Scalar, _Index >::nonZeros () const
Returns
the number of non zeros in the current sub vector
Definition at line 125 of file AmbiVector.h.
References Eigen::IsSparse.
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate (Index size) inline protected
Definition at line 65 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _Index >::m_allocatedElements, Eigen::internal::AmbiVector< _Scalar, _Index >::m_buffer, Eigen::internal::AmbiVector< _Scalar, _Index >::m_end, Eigen::internal::AmbiVector< _Scalar, _Index >::m_size, Eigen::internal::AmbiVector< _Scalar, _Index >::m_start, and Eigen::internal::AmbiVector< _Scalar, _Index >::size().
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::resize().
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::reallocateSparse () inline protected
Definition at line 86 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _Index >::m_allocatedElements, Eigen::internal::AmbiVector< _Scalar, _Index >::m_buffer, Eigen::internal::AmbiVector< _Scalar, _Index >::m_size, and min().
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::resize (Index size) inline
Definition at line 54 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _Index >::m_allocatedSize, Eigen::internal::AmbiVector< _Scalar, _Index >::m_size, Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate(), and Eigen::internal::AmbiVector< _Scalar, _Index >::size().
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::AmbiVector().
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::restart ()
Must be called whenever we might perform a write access with an index smaller than the previous one.
Don't worry, this function is extremely cheap.
Definition at line 159 of file AmbiVector.h.
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::setBounds (Index start, Index end) inline
Specifies a sub-vector to work on
Definition at line 42 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _Index >::m_end, and Eigen::internal::AmbiVector< _Scalar, _Index >::m_start.
Referenced by Eigen::internal::sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >::run().
template<typename _Scalar , typename _Index > void Eigen::internal::AmbiVector< _Scalar, _Index >::setZero ()
Set all coefficients of current subvector to zero
Definition at line 166 of file AmbiVector.h.
References eigen_assert, Eigen::IsDense, and Eigen::IsSparse.
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::size () const inline
Definition at line 61 of file AmbiVector.h.
References Eigen::internal::AmbiVector< _Scalar, _Index >::m_size.
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate(), and Eigen::internal::AmbiVector< _Scalar, _Index >::resize().
Member Data Documentation
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_allocatedElements protected
Definition at line 114 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate(), and Eigen::internal::AmbiVector< _Scalar, _Index >::reallocateSparse().
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_allocatedSize protected
Definition at line 113 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::resize().
template<typename _Scalar , typename _Index > Scalar* Eigen::internal::AmbiVector< _Scalar, _Index >::m_buffer protected
Definition at line 108 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _Index >::reallocateSparse(), and Eigen::internal::AmbiVector< _Scalar, _Index >::~AmbiVector().
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_end protected
Definition at line 112 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate(), and Eigen::internal::AmbiVector< _Scalar, _Index >::setBounds().
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_llCurrent protected
Definition at line 119 of file AmbiVector.h.
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_llSize protected
Definition at line 120 of file AmbiVector.h.
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_llStart protected
Definition at line 118 of file AmbiVector.h.
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_mode protected
Definition at line 115 of file AmbiVector.h.
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_size protected
Definition at line 110 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _Index >::reallocateSparse(), Eigen::internal::AmbiVector< _Scalar, _Index >::resize(), and Eigen::internal::AmbiVector< _Scalar, _Index >::size().
template<typename _Scalar , typename _Index > Index Eigen::internal::AmbiVector< _Scalar, _Index >::m_start protected
Definition at line 111 of file AmbiVector.h.
Referenced by Eigen::internal::AmbiVector< _Scalar, _Index >::reallocate(), and Eigen::internal::AmbiVector< _Scalar, _Index >::setBounds().
template<typename _Scalar , typename _Index > Scalar Eigen::internal::AmbiVector< _Scalar, _Index >::m_zero protected
Definition at line 109 of file AmbiVector.h.
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCore/AmbiVector.h