LIA_RAL: Eigen::Reverse< MatrixType, Direction > Class Template Reference
Eigen::Reverse< MatrixType, Direction > Class Template Reference
Expression of the reverse of a vector or matrix.
#include <Reverse.h>
Public Types
typedef
internal::dense_xpr_base
< Reverse >::type Base
Public Member Functions
Reverse (const MatrixType &matrix)
Index rows () const
Index cols () const
Index innerStride () const
Scalar & operator() (Index row, Index col)
Scalar & coeffRef (Index row, Index col)
CoeffReturnType coeff (Index row, Index col) const
CoeffReturnType coeff (Index index) const
Scalar & coeffRef (Index index)
Scalar & operator() (Index index)
template<int LoadMode>
const PacketScalar packet (Index row, Index col) const
template<int LoadMode>
void writePacket (Index row, Index col, const PacketScalar &x)
template<int LoadMode>
const PacketScalar packet (Index index) const
template<int LoadMode>
void writePacket (Index index, const PacketScalar &x)
const internal::remove_all
< typename MatrixType::Nested >
::type & nestedExpression () const
Protected Types
enum {
PacketSize = internal::packet_traits<Scalar>::size, IsColMajor = !IsRowMajor, ReverseRow = (Direction == Vertical) || (Direction == BothDirections), ReverseCol = (Direction == Horizontal) || (Direction == BothDirections),
OffsetRow = ReverseRow && IsColMajor ? PacketSize : 1, OffsetCol = ReverseCol && IsRowMajor ? PacketSize : 1, ReversePacket
}
typedef
internal::reverse_packet_cond
< PacketScalar, ReversePacket > reverse_packet
Protected Attributes
MatrixType::Nested m_matrix
Detailed Description
template<typename MatrixType, int Direction>
class Eigen::Reverse< MatrixType, Direction >
Expression of the reverse of a vector or matrix.
Parameters
MatrixType the type of the object of which we are taking the reverse
This class represents an expression of the reverse of a vector. It is the return type of MatrixBase::reverse() and VectorwiseOp::reverse() and most of the time this is the only way it is used.
See Also
MatrixBase::reverse(), VectorwiseOp::reverse()
Definition at line 70 of file Reverse.h.
Member Typedef Documentation
template<typename MatrixType , int Direction> typedef internal::dense_xpr_base<Reverse>::type Eigen::Reverse< MatrixType, Direction >::Base
Definition at line 75 of file Reverse.h.
template<typename MatrixType , int Direction> typedef internal::reverse_packet_cond<PacketScalar,ReversePacket> Eigen::Reverse< MatrixType, Direction >::reverse_packet protected
Definition at line 95 of file Reverse.h.
Member Enumeration Documentation
template<typename MatrixType , int Direction> anonymous enum protected
Enumerator
PacketSize
IsColMajor
ReverseRow
ReverseCol
OffsetRow
OffsetCol
ReversePacket
Definition at line 84 of file Reverse.h.
Constructor & Destructor Documentation
template<typename MatrixType , int Direction> Eigen::Reverse< MatrixType, Direction >::Reverse (const MatrixType & matrix) inline
Definition at line 98 of file Reverse.h.
Member Function Documentation
template<typename MatrixType , int Direction> CoeffReturnType Eigen::Reverse< MatrixType, Direction >::coeff (Index row, Index col) const inline
Definition at line 122 of file Reverse.h.
References col(), and row().
template<typename MatrixType , int Direction> CoeffReturnType Eigen::Reverse< MatrixType, Direction >::coeff (Index index) const inline
Definition at line 128 of file Reverse.h.
template<typename MatrixType , int Direction> Scalar& Eigen::Reverse< MatrixType, Direction >::coeffRef (Index row, Index col) inline
Definition at line 116 of file Reverse.h.
References col(), and row().
template<typename MatrixType , int Direction> Scalar& Eigen::Reverse< MatrixType, Direction >::coeffRef (Index index) inline
Definition at line 133 of file Reverse.h.
template<typename MatrixType , int Direction> Index Eigen::Reverse< MatrixType, Direction >::cols (void) const inline
Definition at line 103 of file Reverse.h.
template<typename MatrixType , int Direction> Index Eigen::Reverse< MatrixType, Direction >::innerStride () const inline
Definition at line 105 of file Reverse.h.
template<typename MatrixType , int Direction> const internal::remove_all<typename MatrixType::Nested>::type& Eigen::Reverse< MatrixType, Direction >::nestedExpression () const inline
Definition at line 174 of file Reverse.h.
template<typename MatrixType , int Direction> Scalar& Eigen::Reverse< MatrixType, Direction >::operator() (Index row, Index col) inline
Definition at line 110 of file Reverse.h.
References eigen_assert.
template<typename MatrixType , int Direction> Scalar& Eigen::Reverse< MatrixType, Direction >::operator() (Index index) inline
Definition at line 138 of file Reverse.h.
References eigen_assert.
template<typename MatrixType , int Direction> template<int LoadMode> const PacketScalar Eigen::Reverse< MatrixType, Direction >::packet (Index row, Index col) const inline
Definition at line 145 of file Reverse.h.
References col(), and row().
template<typename MatrixType , int Direction> template<int LoadMode> const PacketScalar Eigen::Reverse< MatrixType, Direction >::packet (Index index) const inline
Definition at line 162 of file Reverse.h.
References Eigen::internal::preverse().
template<typename MatrixType , int Direction> Index Eigen::Reverse< MatrixType, Direction >::rows (void) const inline
Definition at line 102 of file Reverse.h.
template<typename MatrixType , int Direction> template<int LoadMode> void Eigen::Reverse< MatrixType, Direction >::writePacket (Index row, Index col, const PacketScalar & x) inline
Definition at line 153 of file Reverse.h.
References col(), and row().
template<typename MatrixType , int Direction> template<int LoadMode> void Eigen::Reverse< MatrixType, Direction >::writePacket (Index index, const PacketScalar & x) inline
Definition at line 168 of file Reverse.h.
References Eigen::internal::preverse().
Member Data Documentation
template<typename MatrixType , int Direction> MatrixType::Nested Eigen::Reverse< MatrixType, Direction >::m_matrix protected
Definition at line 180 of file Reverse.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/Reverse.h