LIA_RAL: Eigen::SparseVector< _Scalar, _Flags, _Index > Class Template Reference
Eigen::SparseVector< _Scalar, _Flags, _Index > Class Template Reference
a sparse vector class
#include <SparseUtil.h>
Classes
class InnerIterator
class ReverseInnerIterator
Public Types
enum { IsColVector = internal::traits<SparseVector>::IsColVector }
enum { Options = _Options }
typedef SparseMatrixBase
< SparseVector > SparseBase
Public Types inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >
enum
typedef internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Scalar Scalar
typedef
internal::packet_traits
< Scalar >::type PacketScalar
typedef internal::traits
< SparseVector< _Scalar,
_Options, _Index >
>::StorageKind StorageKind
typedef internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Index Index
typedef
internal::add_const_on_value_type_if_arithmetic
< typename
internal::packet_traits
< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef EigenBase
< SparseVector< _Scalar,
_Options, _Index > > Base
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, CwiseUnaryOp
< internal::scalar_conjugate_op
< Scalar >, Eigen::Transpose
< const SparseVector< _Scalar,
_Options, _Index >
> >, Transpose< const
SparseVector< _Scalar,
_Options, _Index > > >::type AdjointReturnType
typedef SparseMatrix< Scalar,
Flags &RowMajorBit?RowMajor:ColMajor > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional
< _HasDirectAccess, const
Scalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp
< internal::scalar_constant_op
< Scalar >, Matrix< Scalar,
Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar,
EIGEN_SIZE_MAX(RowsAtCompileTime,
ColsAtCompileTime),
EIGEN_SIZE_MAX(RowsAtCompileTime,
ColsAtCompileTime)> SquareMatrixType
typedef CwiseUnaryOp
< internal::scalar_multiple_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > ScalarMultipleReturnType
typedef CwiseUnaryOp
< internal::scalar_quotient1_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > ScalarQuotient1ReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, const
CwiseUnaryOp
< internal::scalar_conjugate_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
>, const SparseVector
< _Scalar, _Options, _Index >
& >::type ConjugateReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, const
CwiseUnaryOp
< internal::scalar_real_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
>, const SparseVector
< _Scalar, _Options, _Index >
& >::type RealReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, CwiseUnaryView
< internal::scalar_real_ref_op
< Scalar >, SparseVector
< _Scalar, _Options, _Index >
>, SparseVector< _Scalar,
_Options, _Index > & >::type NonConstRealReturnType
typedef CwiseUnaryOp
< internal::scalar_imag_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > ImagReturnType
typedef CwiseUnaryView
< internal::scalar_imag_ref_op
< Scalar >, SparseVector
< _Scalar, _Options, _Index > > NonConstImagReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
internal::CompressedStorage
< Scalar, Index > & _data ()
internal::CompressedStorage
< Scalar, Index > & _data () const
EIGEN_STRONG_INLINE Index rows () const
EIGEN_STRONG_INLINE Index cols () const
EIGEN_STRONG_INLINE Index innerSize () const
EIGEN_STRONG_INLINE Index outerSize () const
EIGEN_STRONG_INLINE const Scalar * valuePtr () const
EIGEN_STRONG_INLINE Scalar * valuePtr ()
EIGEN_STRONG_INLINE const Index * innerIndexPtr () const
EIGEN_STRONG_INLINE Index * innerIndexPtr ()
Scalar coeff (Index row, Index col) const
Scalar coeff (Index i) const
Scalar & coeffRef (Index row, Index col)
Scalar & coeffRef (Index i)
void setZero ()
Index nonZeros () const
void startVec (Index outer)
Scalar & insertBackByOuterInner (Index outer, Index inner)
Scalar & insertBack (Index i)
Scalar & insert (Index row, Index col)
Scalar & insert (Index i)
void reserve (Index reserveSize)
void finalize ()
void prune (Scalar reference, RealScalar epsilon=NumTraits< RealScalar >::dummy_precision())
void resize (Index rows, Index cols)
void resize (Index newSize)
void resizeNonZeros (Index size)
SparseVector ()
SparseVector (Index size)
SparseVector (Index rows, Index cols)
template<typename OtherDerived >
SparseVector (const SparseMatrixBase< OtherDerived > &other)
SparseVector (const SparseVector &other)
void swap (SparseVector &other)
SparseVector & operator= (const SparseVector &other)
template<typename OtherDerived >
SparseVector & operator= (const SparseMatrixBase< OtherDerived > &other)
template<typename Lhs , typename Rhs >
SparseVector & operator= (const SparseSparseProduct< Lhs, Rhs > &product)
~SparseVector ()
Scalar sum () const
EIGEN_DEPRECATED void startFill (Index reserve)
EIGEN_DEPRECATED Scalar & fill (Index r, Index c)
EIGEN_DEPRECATED Scalar & fill (Index i)
EIGEN_DEPRECATED Scalar & fillrand (Index r, Index c)
EIGEN_DEPRECATED Scalar & fillrand (Index i)
EIGEN_DEPRECATED void endFill ()
Public Member Functions inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >
SparseVector< _Scalar,
_Options, _Index > & operator= (const EigenBase< OtherDerived > &other)
SparseVector< _Scalar,
_Options, _Index > & operator= (const ReturnByValue< OtherDerived > &other)
SparseVector< _Scalar,
_Options, _Index > & operator= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar,
_Options, _Index > & operator= (const SparseVector< _Scalar, _Options, _Index > &other)
SparseVector< _Scalar,
_Options, _Index > & operator= (const SparseSparseProduct< Lhs, Rhs > &product)
const SparseVector< _Scalar,
_Options, _Index > & derived () const
SparseVector< _Scalar,
_Options, _Index > & derived ()
SparseVector< _Scalar,
_Options, _Index > & const_cast_derived () const
const CwiseUnaryOp
< internal::scalar_opposite_op
< typename internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Scalar >
, const SparseVector< _Scalar,
_Options, _Index > > operator- () const
const ScalarMultipleReturnType operator* (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const SparseVector
< _Scalar, _Options, _Index > > operator* (const std::complex< Scalar > &scalar) const
const
SparseSparseProductReturnType
< SparseVector< _Scalar,
_Options, _Index >
, OtherDerived >::Type operator* (const SparseMatrixBase< OtherDerived > &other) const
const SparseDiagonalProduct
< SparseVector< _Scalar,
_Options, _Index >
, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const
SparseDenseProductReturnType
< SparseVector< _Scalar,
_Options, _Index >
, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_quotient1_op
< typename internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Scalar >
, const SparseVector< _Scalar,
_Options, _Index > > operator/ (const Scalar &scalar) const
internal::cast_return_type
< SparseVector< _Scalar,
_Options, _Index >, const
CwiseUnaryOp
< internal::scalar_cast_op
< typename internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Scalar,
NewType >, const SparseVector
< _Scalar, _Options, _Index >
> >::type cast () const
ConjugateReturnType conjugate () const
RealReturnType real () const
NonConstRealReturnType real ()
const ImagReturnType imag () const
NonConstImagReturnType imag ()
const CwiseUnaryOp
< CustomUnaryOp, const
SparseVector< _Scalar,
_Options, _Index > > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
const CwiseUnaryView
< CustomViewOp, const
SparseVector< _Scalar,
_Options, _Index > > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp< CustomBinaryOp,
const SparseVector< _Scalar,
_Options, _Index >, const
OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
EIGEN_STRONG_INLINE const
CwiseUnaryOp
< internal::scalar_abs_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseAbs () const
EIGEN_STRONG_INLINE const
CwiseUnaryOp
< internal::scalar_abs2_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseAbs2 () const
const CwiseUnaryOp
< internal::scalar_sqrt_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseSqrt () const
const CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseInverse () const
const CwiseUnaryOp
< std::binder1st
< std::equal_to< Scalar >
>, const SparseVector
< _Scalar, _Options, _Index > > cwiseEqual (const Scalar &s) const
const CwiseBinaryOp
< std::equal_to< Scalar >
, const SparseVector< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const EIGEN_CWISE_PRODUCT_RETURN_TYPE (SparseVector< _Scalar, _Options, _Index >, OtherDerived) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
const CwiseBinaryOp
< std::not_equal_to< Scalar >
, const SparseVector< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMin (const Scalar &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMax (const Scalar &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
Index rows () const
Index cols () const
Index size () const
Index nonZeros () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
SparseVector< _Scalar,
_Options, _Index > & markAsRValue ()
SparseMatrixBase ()
SparseVector< _Scalar,
_Options, _Index > & operator+= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar,
_Options, _Index > & operator-= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar,
_Options, _Index > & operator*= (const Scalar &other)
SparseVector< _Scalar,
_Options, _Index > & operator*= (const SparseMatrixBase< OtherDerived > &other)
SparseVector< _Scalar,
_Options, _Index > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const
EIGEN_SPARSE_CWISE_PRODUCT_RETURN_TYPE cwiseProduct (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct
< SparseVector< _Scalar,
_Options, _Index >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > &perm) const
const SparseTriangularView
< SparseVector< _Scalar,
_Options, _Index >, Mode > triangularView () const
const SparseSelfAdjointView
< SparseVector< _Scalar,
_Options, _Index >, UpLo > selfadjointView () const
SparseSelfAdjointView
< SparseVector< _Scalar,
_Options, _Index >, UpLo > selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
Transpose< SparseVector
< _Scalar, _Options, _Index > > transpose ()
const Transpose< const
SparseVector< _Scalar,
_Options, _Index > > transpose () const
const AdjointReturnType adjoint () const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, 1 > row (Index i)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, 1 > row (Index i) const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, 1 > col (Index j)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, 1 > col (Index j) const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, 1 > innerVector (Index outer)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, 1 > innerVector (Index outer) const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > subrows (Index start, Index size)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > subrows (Index start, Index size) const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > subcols (Index start, Index size)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > subcols (Index start, Index size) const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > middleRows (Index start, Index size)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > middleRows (Index start, Index size) const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > middleCols (Index start, Index size)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > middleCols (Index start, Index size) const
SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > innerVectors (Index outerStart, Index outerSize)
const SparseInnerVectorSet
< SparseVector< _Scalar,
_Options, _Index >, Dynamic > innerVectors (Index outerStart, Index outerSize) const
void evalTo (MatrixBase< DenseDerived > &dst) const
Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime > toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval
< SparseVector< _Scalar,
_Options, _Index > >::type eval () const
Scalar sum () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Public Attributes
internal::CompressedStorage
< Scalar, Index > m_data
Index m_size
Protected Member Functions
template<typename OtherDerived >
EIGEN_DONT_INLINE SparseVector & assign (const SparseMatrixBase< OtherDerived > &_other)
Protected Member Functions inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >
SparseVector< _Scalar,
_Options, _Index > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Friends
std::ostream & operator<< (std::ostream &s, const SparseVector &m)
Additional Inherited Members
Protected Attributes inherited from Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >
bool m_isRValue
Detailed Description
template<typename _Scalar, int _Flags = 0, typename _Index = int>
class Eigen::SparseVector< _Scalar, _Flags, _Index >
a sparse vector class
Template Parameters
_Scalar the scalar type, i.e. the type of the coefficients
See http://www.netlib.org/linalg/html_templates/node91.html for details on the storage scheme.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizingEigen by defining the preprocessor symbol EIGEN_SPARSEVECTOR_PLUGIN.
Definition at line 73 of file SparseUtil.h.
Member Typedef Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> typedef SparseMatrixBase<SparseVector> Eigen::SparseVector< _Scalar, _Flags, _Index >::SparseBase
Definition at line 62 of file SparseVector.h.
Member Enumeration Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> anonymous enum
Enumerator
IsColVector
Definition at line 63 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> anonymous enum
Enumerator
Options
Definition at line 65 of file SparseVector.h.
Constructor & Destructor Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::SparseVector () inline
Definition at line 191 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::resize().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::SparseVector (Index size) inline
Definition at line 193 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::resize().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::SparseVector (Index rows, Index cols) inline
Definition at line 195 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::resize().
template<typename _Scalar , int _Flags = 0, typename _Index = int> template<typename OtherDerived > Eigen::SparseVector< _Scalar, _Flags, _Index >::SparseVector (const SparseMatrixBase< OtherDerived > & other) inline
Definition at line 198 of file SparseVector.h.
References Eigen::SparseMatrixBase< Derived >::derived().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::SparseVector (const SparseVector< _Scalar, _Flags, _Index > & other) inline
Definition at line 204 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::~SparseVector () inline
Destructor
Definition at line 256 of file SparseVector.h.
Member Function Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> internal::CompressedStorage<Scalar,Index>& Eigen::SparseVector< _Scalar, _Flags, _Index >::_data () inline
Definition at line 72 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> internal::CompressedStorage<Scalar,Index>& Eigen::SparseVector< _Scalar, _Flags, _Index >::_data () const inline
Definition at line 73 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> template<typename OtherDerived > EIGEN_DONT_INLINE SparseVector& Eigen::SparseVector< _Scalar, _Flags, _Index >::assign (const SparseMatrixBase< OtherDerived > & _other) inline protected
Definition at line 306 of file SparseVector.h.
References Eigen::SparseMatrixBase< Derived >::derived(), Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >::Flags, Eigen::SparseVector< _Scalar, _Flags, _Index >::insert(), Eigen::SparseVector< _Scalar, _Flags, _Index >::reserve(), Eigen::SparseVector< _Scalar, _Flags, _Index >::resize(), Eigen::RowMajorBit, and Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >::size().
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::operator=().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar Eigen::SparseVector< _Scalar, _Flags, _Index >::coeff (Index row, Index col) const inline
Definition at line 88 of file SparseVector.h.
References eigen_assert, and Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::coeffRef().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar Eigen::SparseVector< _Scalar, _Flags, _Index >::coeff (Index i) const inline
Definition at line 93 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::at(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::coeffRef (Index row, Index col) inline
Definition at line 95 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::coeff(), eigen_assert, and Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::coeffRef (Index i) inline
Returns
a reference to the coefficient value at given index i This operation involes a log(rho*size) binary search. If the coefficient does not exist yet, then a sorted insertion into a sequential buffer is performed.
This insertion might be very costly if the number of nonzeros above i is large.
Definition at line 107 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::atWithInsertion(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Flags, _Index >::cols (void) const inline
Definition at line 78 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector, and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_size.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_DEPRECATED void Eigen::SparseVector< _Scalar, _Flags, _Index >::endFill () inline
Deprecated:
use finalize()
Definition at line 298 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::fill (Index r, Index c) inline
Deprecated:
use insertBack(Index,Index)
Definition at line 271 of file SparseVector.h.
References eigen_assert, and Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::fill (Index i) inline
Deprecated:
use insertBack(Index)
Definition at line 278 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::append(), Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, Eigen::internal::CompressedStorage< _Scalar, _Index >::size(), and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::fillrand (Index r, Index c) inline
Deprecated:
use insert(Index,Index)
Definition at line 285 of file SparseVector.h.
References eigen_assert, and Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_DEPRECATED Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::fillrand (Index i) inline
Deprecated:
use insert(Index)
Definition at line 292 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::insert().
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::finalize () inline
Definition at line 170 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE const Index* Eigen::SparseVector< _Scalar, _Flags, _Index >::innerIndexPtr () const inline
Definition at line 85 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::index(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE Index* Eigen::SparseVector< _Scalar, _Flags, _Index >::innerIndexPtr () inline
Definition at line 86 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::index(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Flags, _Index >::innerSize () const inline
Definition at line 79 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_size.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::insert (Index row, Index col) inline
Definition at line 140 of file SparseVector.h.
References Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >::col(), eigen_assert, Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector, and Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >::row().
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::assign(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::fillrand().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::insert (Index i) inline
Definition at line 147 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::index(), Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, Eigen::internal::CompressedStorage< _Scalar, _Index >::resize(), Eigen::internal::CompressedStorage< _Scalar, _Index >::size(), and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBack (Index i) inline
Definition at line 134 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::append(), Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, Eigen::internal::CompressedStorage< _Scalar, _Index >::size(), and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBackByOuterInner().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBackByOuterInner (Index outer, Index inner) inline
Definition at line 128 of file SparseVector.h.
References eigen_assert, EIGEN_UNUSED_VARIABLE, and Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBack().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::nonZeros () const inline
Returns
the number of non zero coefficients
Definition at line 120 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::size().
template<typename _Scalar , int _Flags = 0, typename _Index = int> SparseVector& Eigen::SparseVector< _Scalar, _Flags, _Index >::operator= (const SparseVector< _Scalar, _Flags, _Index > & other) inline
Definition at line 216 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, Eigen::SparseVector< _Scalar, _Flags, _Index >::resize(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::swap().
template<typename _Scalar , int _Flags = 0, typename _Index = int> template<typename OtherDerived > SparseVector& Eigen::SparseVector< _Scalar, _Flags, _Index >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
Definition at line 231 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::assign(), Eigen::SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >::RowsAtCompileTime, and Eigen::SparseMatrixBase< Derived >::transpose().
template<typename _Scalar , int _Flags = 0, typename _Index = int> template<typename Lhs , typename Rhs > SparseVector& Eigen::SparseVector< _Scalar, _Flags, _Index >::operator= (const SparseSparseProduct< Lhs, Rhs > & product) inline
Definition at line 241 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Flags, _Index >::outerSize () const inline
Definition at line 80 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::prune (Scalar reference, RealScalar epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Definition at line 172 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::prune().
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::reserve (Index reserveSize) inline
Definition at line 167 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::reserve().
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::assign().
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::resize (Index rows, Index cols) inline
Definition at line 177 of file SparseVector.h.
References eigen_assert, and Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::assign(), Eigen::SparseVector< _Scalar, _Flags, _Index >::operator=(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::SparseVector().
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::resize (Index newSize) inline
Definition at line 183 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::clear(), Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_size.
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::resizeNonZeros (Index size) inline
Definition at line 189 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::resize().
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE Index Eigen::SparseVector< _Scalar, _Flags, _Index >::rows (void) const inline
Definition at line 77 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector, and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_size.
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::setZero () inline
Definition at line 117 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::clear(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::startFill().
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_DEPRECATED void Eigen::SparseVector< _Scalar, _Flags, _Index >::startFill (Index reserve) inline
Deprecated:
use setZero() and reserve()
Definition at line 264 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, Eigen::internal::CompressedStorage< _Scalar, _Index >::reserve(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::setZero().
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::startVec (Index outer) inline
Definition at line 122 of file SparseVector.h.
References eigen_assert, and EIGEN_UNUSED_VARIABLE.
template<typename _Scalar , int _Options, typename _Index > internal::traits< SparseVector< _Scalar, _Options, _Index > >::Scalar Eigen::SparseVector< _Scalar, _Options, _Index >::sum () const
Overloaded for performance
Definition at line 37 of file SparseRedux.h.
References eigen_assert, and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map().
template<typename _Scalar , int _Flags = 0, typename _Index = int> void Eigen::SparseVector< _Scalar, _Flags, _Index >::swap (SparseVector< _Scalar, _Flags, _Index > & other) inline
Definition at line 210 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, Eigen::SparseVector< _Scalar, _Flags, _Index >::m_size, swap(), and Eigen::internal::CompressedStorage< _Scalar, _Index >::swap().
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::operator=().
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE const Scalar* Eigen::SparseVector< _Scalar, _Flags, _Index >::valuePtr () const inline
Definition at line 82 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
template<typename _Scalar , int _Flags = 0, typename _Index = int> EIGEN_STRONG_INLINE Scalar* Eigen::SparseVector< _Scalar, _Flags, _Index >::valuePtr () inline
Definition at line 83 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
Friends And Related Function Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> std::ostream& operator<< (std::ostream & s, const SparseVector< _Scalar, _Flags, _Index > & m) friend
Definition at line 247 of file SparseVector.h.
Member Data Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> internal::CompressedStorage<Scalar,Index> Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data
Definition at line 69 of file SparseVector.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::_data(), Eigen::SparseVector< _Scalar, _Flags, _Index >::coeff(), Eigen::SparseVector< _Scalar, _Flags, _Index >::coeffRef(), Eigen::SparseVector< _Scalar, _Flags, _Index >::fill(), Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::index(), Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::index(), Eigen::SparseVector< _Scalar, _Flags, _Index >::innerIndexPtr(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insert(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBack(), Eigen::SparseVector< _Scalar, _Flags, _Index >::nonZeros(), Eigen::SparseVector< _Scalar, _Flags, _Index >::operator=(), Eigen::SparseVector< _Scalar, _Flags, _Index >::prune(), Eigen::SparseVector< _Scalar, _Flags, _Index >::reserve(), Eigen::SparseVector< _Scalar, _Flags, _Index >::resize(), Eigen::SparseVector< _Scalar, _Flags, _Index >::resizeNonZeros(), Eigen::SparseVector< _Scalar, _Flags, _Index >::setZero(), Eigen::SparseVector< _Scalar, _Flags, _Index >::startFill(), Eigen::SparseVector< _Scalar, _Flags, _Index >::swap(), Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::value(), Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::value(), Eigen::SparseVector< _Scalar, _Flags, _Index >::valuePtr(), Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::valueRef(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::valueRef().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::m_size
Definition at line 70 of file SparseVector.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::cols(), Eigen::SparseVector< _Scalar, _Flags, _Index >::innerSize(), Eigen::SparseVector< _Scalar, _Flags, _Index >::resize(), Eigen::SparseVector< _Scalar, _Flags, _Index >::rows(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::swap().
The documentation for this class was generated from the following files:
include/Eigen/src/SparseCore/SparseUtil.h
include/Eigen/src/SparseCore/SparseVector.h
include/Eigen/src/SparseCore/SparseRedux.h