LIA_RAL: Eigen::HouseholderSequence< VectorsType, CoeffsType, Side > Class Template Reference
Eigen::HouseholderSequence< VectorsType, CoeffsType, Side > Class Template Reference
Sequence of Householder reflections acting on subspaces with decreasing size.
#include <ForwardDeclarations.h>
Public Types
typedef HouseholderSequence
< VectorsType, typename
internal::conditional
< NumTraits< Scalar >
::IsComplex, typename
internal::remove_all< typename
CoeffsType::ConjugateReturnType >
::type, CoeffsType >::type,
Side > ConjugateReturnType
Public Types inherited from Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >
typedef internal::traits
< HouseholderSequence
< VectorsType, CoeffsType,
Side > >::StorageKind StorageKind
typedef internal::traits
< HouseholderSequence
< VectorsType, CoeffsType,
Side > >::Index Index
Public Member Functions
HouseholderSequence (const VectorsType &v, const CoeffsType &h)
Constructor.
HouseholderSequence (const HouseholderSequence &other)
Copy constructor.
Index rows () const
Number of rows of transformation viewed as a matrix.
Index cols () const
Number of columns of transformation viewed as a matrix.
const EssentialVectorType essentialVector (Index k) const
Essential part of a Householder vector.
HouseholderSequence transpose () const
Transpose of the Householder sequence.
ConjugateReturnType conjugate () const
Complex conjugate of the Householder sequence.
ConjugateReturnType adjoint () const
Adjoint (conjugate transpose) of the Householder sequence.
ConjugateReturnType inverse () const
Inverse of the Householder sequence (equals the adjoint).
template<typename DestType >
void evalTo (DestType &dst) const
template<typename Dest , typename Workspace >
void evalTo (Dest &dst, Workspace &workspace) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest , typename Workspace >
void applyThisOnTheRight (Dest &dst, Workspace &workspace) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
template<typename Dest , typename Workspace >
void applyThisOnTheLeft (Dest &dst, Workspace &workspace) const
template<typename OtherDerived >
internal::matrix_type_times_scalar_type
< Scalar, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
Computes the product of a Householder sequence with a matrix.
HouseholderSequence & setLength (Index length)
Sets the length of the Householder sequence.
HouseholderSequence & setShift (Index shift)
Sets the shift of the Householder sequence.
Index length () const
Returns the length of the Householder sequence.
Index shift () const
Returns the shift of the Householder sequence.
Public Member Functions inherited from Eigen::EigenBase< HouseholderSequence< VectorsType, CoeffsType, Side > >
HouseholderSequence
< VectorsType, CoeffsType,
Side > & derived ()
const HouseholderSequence
< VectorsType, CoeffsType,
Side > & derived () const
HouseholderSequence
< VectorsType, CoeffsType,
Side > & const_cast_derived () const
const HouseholderSequence
< VectorsType, CoeffsType,
Side > & const_derived () const
Index rows () const
Index cols () const
Index size () const
void evalTo (Dest &dst) const
void addTo (Dest &dst) const
void subTo (Dest &dst) const
void applyThisOnTheRight (Dest &dst) const
void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
HouseholderSequence & setTrans (bool trans)
Sets the transpose flag.
bool trans () const
Returns the transpose flag.
Protected Attributes
VectorsType::Nested m_vectors
CoeffsType::Nested m_coeffs
bool m_trans
Index m_length
Index m_shift
Private Types
enum { RowsAtCompileTime = internal::traits<HouseholderSequence>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<HouseholderSequence>::ColsAtCompileTime, MaxRowsAtCompileTime = internal::traits<HouseholderSequence>::MaxRowsAtCompileTime, MaxColsAtCompileTime = internal::traits<HouseholderSequence>::MaxColsAtCompileTime }
typedef internal::traits
< HouseholderSequence >
::Scalar Scalar
typedef VectorsType::Index Index
typedef
internal::hseq_side_dependent_impl
< VectorsType, CoeffsType,
Side >::EssentialVectorType EssentialVectorType
Friends
template<typename _VectorsType , typename _CoeffsType , int _Side>
struct internal::hseq_side_dependent_impl
template<typename VectorsType2 , typename CoeffsType2 , int Side2>
class HouseholderSequence
Detailed Description
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft>
class Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >
Sequence of Householder reflections acting on subspaces with decreasing size.
Template Parameters
VectorsType type of matrix containing the Householder vectors
CoeffsType type of vector containing the Householder coefficients
Side either OnTheLeft (the default) or OnTheRight
This class represents a product sequence of Householder reflections where the first Householder reflection acts on the whole space, the second Householder reflection leaves the one-dimensional subspace spanned by the first unit vector invariant, the third Householder reflection leaves the two-dimensional subspace spanned by the first two unit vectors invariant, and so on up to the last reflection which leaves all but one dimensions invariant and acts only on the last dimension. Such sequences of Householder reflections are used in several algorithms to zero out certain parts of a matrix. Indeed, the methods HessenbergDecomposition::matrixQ(), Tridiagonalization::matrixQ(), HouseholderQR::householderQ(), and ColPivHouseholderQR::householderQ() all return a HouseholderSequence.
More precisely, the class HouseholderSequence represents an matrix of the form where the i-th Householder reflection is . The i-th Householder coefficient is a scalar and the i-th Householder vector is a vector of the form
The last entries of are called the essential part of the Householder vector.
Typical usages are listed below, where H is a HouseholderSequence:
A.applyOnTheRight(H);             // A = A * H
A.applyOnTheLeft(H);              // A = H * A
A.applyOnTheRight(H.adjoint());   // A = A * H^*
A.applyOnTheLeft(H.adjoint());    // A = H^* * A
MatrixXd Q = H;                   // conversion to a dense matrix
In addition to the adjoint, you can also apply the inverse (=adjoint), the transpose, and the conjugate operators.
See the documentation for HouseholderSequence(const VectorsType&, const CoeffsType&) for an example.
See Also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Definition at line 228 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> typedef HouseholderSequence< VectorsType, typename internal::conditional<NumTraits<Scalar>::IsComplex, typename internal::remove_all<typename CoeffsType::ConjugateReturnType>::type, CoeffsType>::type, Side > Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::ConjugateReturnType
Definition at line 135 of file HouseholderSequence.h.
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> typedef internal::hseq_side_dependent_impl<VectorsType,CoeffsType,Side>::EssentialVectorType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::EssentialVectorType private
Definition at line 125 of file HouseholderSequence.h.
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> typedef VectorsType::Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::Index private
Definition at line 122 of file HouseholderSequence.h.
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> typedef internal::traits<HouseholderSequence>::Scalar Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::Scalar private
Definition at line 121 of file HouseholderSequence.h.
Member Enumeration Documentation
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> anonymous enum private
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 115 of file HouseholderSequence.h.
Constructor & Destructor Documentation
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::HouseholderSequence (const VectorsType & v, const CoeffsType & h) inline
Constructor.
Parameters
[in] v Matrix containing the essential parts of the Householder vectors
[in] h Vector containing the Householder coefficients
Constructs the Householder sequence with coefficients given by h and vectors given by v. The i-th Householder coefficient is given by h(i) and the essential part of the i-th Householder vector is given by v(k,i) with k > i (the subdiagonal part of the i-th column). If v has fewer columns than rows, then the Householder sequence contains as many Householder reflections as there are columns.
Note
The HouseholderSequence object stores v and h by reference.
Example:
Output:
See Also
setLength(), setShift()
Definition at line 154 of file HouseholderSequence.h.
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::HouseholderSequence (const HouseholderSequence< VectorsType, CoeffsType, Side > & other) inline
Copy constructor.
Definition at line 161 of file HouseholderSequence.h.
Member Function Documentation
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> ConjugateReturnType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint () const inline
Adjoint (conjugate transpose) of the Householder sequence.
Definition at line 218 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::inverse().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename Dest > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft (Dest & dst) const inline
Definition at line 300 of file HouseholderSequence.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator*().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename Dest , typename Workspace > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft (Dest & dst, Workspace & workspace) const inline
Definition at line 308 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename Dest > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight (Dest & dst) const inline
Definition at line 280 of file HouseholderSequence.h.
Referenced by Eigen::operator*().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename Dest , typename Workspace > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight (Dest & dst, Workspace & workspace) const inline
Definition at line 288 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::cols (void) const inline
Number of columns of transformation viewed as a matrix.
Returns
Number of columns
This equals the dimension of the space that the transformation acts on.
Definition at line 180 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> ConjugateReturnType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate (void) const inline
Complex conjugate of the Householder sequence.
Definition at line 209 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> const EssentialVectorType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector (Index k) const inline
Essential part of a Householder vector.
Parameters
[in] k Index of Householder reflection
Returns
Vector containing non-trivial entries of k-th Householder vector
This function returns the essential part of the Householder vector . This is a vector of length containing the last entries of the vector
The index equals k + shift(), corresponding to the k-th column of the matrix v passed to the constructor.
See Also
setShift(), shift()
Definition at line 196 of file HouseholderSequence.h.
References eigen_assert, Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename DestType > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo (DestType & dst) const inline
Definition at line 227 of file HouseholderSequence.h.
References Eigen::AutoAlign, Eigen::ColMajor, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename Dest , typename Workspace > void Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo (Dest & dst, Workspace & workspace) const inline
Definition at line 236 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::cols(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::extract_data(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> ConjugateReturnType Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::inverse (void) const inline
Inverse of the Householder sequence (equals the adjoint).
Definition at line 224 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::length () const inline
Returns the length of the Householder sequence.
Definition at line 369 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename OtherDerived > internal::matrix_type_times_scalar_type<Scalar, OtherDerived>::Type Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator* (const MatrixBase< OtherDerived > & other) const inline
Computes the product of a Householder sequence with a matrix.
Parameters
[in] other Matrix being multiplied.
Returns
Expression object representing the product.
This function computes where is the Householder sequence represented by *this and is the matrix other.
Definition at line 327 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), and cast().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows (void) const inline
Number of rows of transformation viewed as a matrix.
Returns
Number of rows
This equals the dimension of the space that the transformation acts on.
Definition at line 174 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors, and Eigen::OnTheLeft.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::cols(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >::essentialVector(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> HouseholderSequence& Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength (Index length) inline
Sets the length of the Householder sequence.
Parameters
[in] length New value for the length.
By default, the length of the Householder sequence is set to the number of columns of the matrix v passed to the constructor, or the number of rows if that is smaller. After this function is called, the length equals length.
See Also
length()
Definition at line 346 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::length(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> HouseholderSequence& Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift (Index shift) inline
Sets the shift of the Householder sequence.
Parameters
[in] shift New value for the shift.
By default, a HouseholderSequence object represents and the i-th column of the matrix v passed to the constructor corresponds to the i-th Householder reflection. After this function is called, the object represents and the i-th column of v corresponds to the (shift+i)-th Householder reflection.
See Also
shift()
Definition at line 363 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::shift().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> HouseholderSequence& Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans (bool trans) inline protected
Sets the transpose flag.
Parameters
[in] trans New value of the transpose flag.
By default, the transpose flag is not set. If the transpose flag is set, then this object represents instead of .
See Also
trans()
Definition at line 385 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::trans().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::shift () const inline
Returns the shift of the Householder sequence.
Definition at line 370 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> bool Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::trans () const inline protected
Returns the transpose flag.
Definition at line 391 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> HouseholderSequence Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::transpose () const inline
Transpose of the Householder sequence.
Definition at line 203 of file HouseholderSequence.h.
References Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::HouseholderSequence, and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans.
Friends And Related Function Documentation
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename VectorsType2 , typename CoeffsType2 , int Side2> friend class HouseholderSequence friend
Definition at line 373 of file HouseholderSequence.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::transpose().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> template<typename _VectorsType , typename _CoeffsType , int _Side> friend struct internal::hseq_side_dependent_impl friend
Definition at line 335 of file HouseholderSequence.h.
Member Data Documentation
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> CoeffsType::Nested Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_coeffs protected
Definition at line 394 of file HouseholderSequence.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_length protected
Definition at line 396 of file HouseholderSequence.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::length(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setLength().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> Index Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_shift protected
Definition at line 397 of file HouseholderSequence.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setShift(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::shift().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> bool Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_trans protected
Definition at line 395 of file HouseholderSequence.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::adjoint(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheRight(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::setTrans(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::trans(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::transpose().
template<typename VectorsType, typename CoeffsType, int Side = OnTheLeft> VectorsType::Nested Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::m_vectors protected
Definition at line 393 of file HouseholderSequence.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::conjugate(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >::essentialVector(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), and Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::rows().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Householder/HouseholderSequence.h