LIA_RAL: Eigen::CwiseUnaryOp< UnaryOp, XprType > Class Template Reference
Eigen::CwiseUnaryOp< UnaryOp, XprType > Class Template Reference
Generic expression where a coefficient-wise unary operator is applied to an expression.
#include <CwiseUnaryOp.h>
Public Types
typedef CwiseUnaryOpImpl
< UnaryOp, XprType, typename
internal::traits< XprType >
::StorageKind >::Base Base
Public Member Functions
CwiseUnaryOp (const XprType &xpr, const UnaryOp &func=UnaryOp())
EIGEN_STRONG_INLINE Index rows () const
EIGEN_STRONG_INLINE Index cols () const
const UnaryOp & functor () const
const internal::remove_all
< typename XprType::Nested >
::type & nestedExpression () const
internal::remove_all< typename
XprType::Nested >::type & nestedExpression ()
Protected Attributes
XprType::Nested m_xpr
const UnaryOp m_functor
Detailed Description
template<typename UnaryOp, typename XprType>
class Eigen::CwiseUnaryOp< UnaryOp, XprType >
Generic expression where a coefficient-wise unary operator is applied to an expression.
Parameters
UnaryOp template functor implementing the operator
XprType the type of the expression to which we are applying the unary operator
This class represents an expression where a unary operator is applied to an expression. It is the return type of all operations taking exactly 1 input expression, regardless of the presence of other inputs such as scalars. For example, the operator* in the expression 3*matrix is considered unary, because only the right-hand side is an expression, and its return type is a specialization of CwiseUnaryOp.
Most of the time, this is the only way that it is used, so you typically don't have to name CwiseUnaryOp types explicitly.
See Also
MatrixBase::unaryExpr(const CustomUnaryOp &) const, class CwiseBinaryOp, class CwiseNullaryOp
Definition at line 59 of file CwiseUnaryOp.h.
Member Typedef Documentation
template<typename UnaryOp, typename XprType> typedef CwiseUnaryOpImpl<UnaryOp, XprType,typename internal::traits<XprType>::StorageKind>::Base Eigen::CwiseUnaryOp< UnaryOp, XprType >::Base
Definition at line 64 of file CwiseUnaryOp.h.
Constructor & Destructor Documentation
template<typename UnaryOp, typename XprType> Eigen::CwiseUnaryOp< UnaryOp, XprType >::CwiseUnaryOp (const XprType & xpr, const UnaryOp & func = UnaryOp()) inline
Definition at line 67 of file CwiseUnaryOp.h.
Member Function Documentation
template<typename UnaryOp, typename XprType> EIGEN_STRONG_INLINE Index Eigen::CwiseUnaryOp< UnaryOp, XprType >::cols () const inline
Definition at line 71 of file CwiseUnaryOp.h.
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
template<typename UnaryOp, typename XprType> const UnaryOp& Eigen::CwiseUnaryOp< UnaryOp, XprType >::functor () const inline
Returns
the functor representing the unary operation
Definition at line 74 of file CwiseUnaryOp.h.
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_functor.
Referenced by Eigen::internal::blas_traits< CwiseUnaryOp< scalar_multiple_op< Scalar >, NestedXpr > >::extractScalarFactor(), Eigen::internal::vml_assign_impl< Derived1, Derived2, UnaryOp, Traversal, Unrolling, InnerVectorizedTraversal >::run(), and Eigen::internal::vml_assign_impl< Derived1, Derived2, UnaryOp, Traversal, Unrolling, LinearVectorizedTraversal >::run().
template<typename UnaryOp, typename XprType> const internal::remove_all<typename XprType::Nested>::type& Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression () const inline
Returns
the nested expression
Definition at line 78 of file CwiseUnaryOp.h.
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
Referenced by Eigen::TransposeImpl< MatrixType, Dense >::data(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::extract(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_multiple_op< Scalar >, NestedXpr > >::extract(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_opposite_op< Scalar >, NestedXpr > >::extract(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >::extractScalarFactor(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_multiple_op< Scalar >, NestedXpr > >::extractScalarFactor(), Eigen::internal::blas_traits< CwiseUnaryOp< scalar_opposite_op< Scalar >, NestedXpr > >::extractScalarFactor(), Eigen::internal::vml_assign_impl< Derived1, Derived2, UnaryOp, Traversal, Unrolling, InnerVectorizedTraversal >::run(), and Eigen::internal::vml_assign_impl< Derived1, Derived2, UnaryOp, Traversal, Unrolling, LinearVectorizedTraversal >::run().
template<typename UnaryOp, typename XprType> internal::remove_all<typename XprType::Nested>::type& Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression () inline
Returns
the nested expression
Definition at line 82 of file CwiseUnaryOp.h.
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
template<typename UnaryOp, typename XprType> EIGEN_STRONG_INLINE Index Eigen::CwiseUnaryOp< UnaryOp, XprType >::rows () const inline
Definition at line 70 of file CwiseUnaryOp.h.
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
Member Data Documentation
template<typename UnaryOp, typename XprType> const UnaryOp Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_functor protected
Definition at line 86 of file CwiseUnaryOp.h.
Referenced by Eigen::CwiseUnaryOp< UnaryOp, XprType >::functor().
template<typename UnaryOp, typename XprType> XprType::Nested Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr protected
Definition at line 85 of file CwiseUnaryOp.h.
Referenced by Eigen::CwiseUnaryOp< UnaryOp, XprType >::cols(), Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression(), and Eigen::CwiseUnaryOp< UnaryOp, XprType >::rows().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/CwiseUnaryOp.h