LIA_RAL: WindowLLR Class Reference
WindowLLR Class Reference
Public Member Functions
WindowLLR (Config &config)
~WindowLLR ()
bool isSet ()
void setNbClient (unsigned long nClient)
unsigned long getIdxBegin ()
unsigned long getIdxEnd ()
void showConfig ()
void accLLR (unsigned long clientIdx, double llr)
double getLLR (unsigned long clientIdx)
bool isEnd ()
unsigned long wCount ()
void dec (unsigned long idxFrame)
WindowLLR (Config &config)
~WindowLLR ()
bool isSet ()
void setNbClient (unsigned long nClient)
unsigned long getIdxBegin ()
unsigned long getIdxEnd ()
void showConfig ()
void accLLR (unsigned long clientIdx, double llr)
double getLLR (unsigned long clientIdx)
bool isEnd ()
unsigned long wCount ()
void dec (unsigned long idxFrame)
Private Member Functions
void _initMem ()
void _freeMem ()
void _initMem ()
void _freeMem ()
Private Attributes
bool _set
unsigned long _size
unsigned long _dec
unsigned long _nClient
Matrix< double > * _llrM
DoubleVector * _accLlrA
ULongVector * _idxA
unsigned long _bIdx
unsigned long _count
Detailed Description
Definition at line 89 of file ComputeTest.cpp.
Constructor & Destructor Documentation
WindowLLR::WindowLLR (Config & config)
Definition at line 147 of file ComputeTest.cpp.
WindowLLR::~WindowLLR ()
Definition at line 167 of file ComputeTest.cpp.
WindowLLR::WindowLLR (Config & config)
WindowLLR::~WindowLLR ()
Member Function Documentation
void WindowLLR::_freeMem () private
void WindowLLR::_freeMem () private
Definition at line 137 of file ComputeTest.cpp.
void WindowLLR::_initMem () private
void WindowLLR::_initMem () private
Definition at line 121 of file ComputeTest.cpp.
Referenced by setNbClient().
void WindowLLR::accLLR (unsigned long clientIdx, double llr)
void WindowLLR::accLLR (unsigned long clientIdx, double llr)
Definition at line 201 of file ComputeTest.cpp.
Referenced by adaptModelEMweightedFrames(), and ComputeTest().
void WindowLLR::dec (unsigned long idxFrame)
void WindowLLR::dec (unsigned long idxFrame)
Definition at line 182 of file ComputeTest.cpp.
Referenced by adaptModelEMweightedFrames(), and ComputeTest().
unsigned long WindowLLR::getIdxBegin () inline
Definition at line 88 of file UnsupervisedTools.cpp.
References _bIdx, and _idxA.
unsigned long WindowLLR::getIdxBegin () inline
Definition at line 109 of file ComputeTest.cpp.
Referenced by ComputeTest().
unsigned long WindowLLR::getIdxEnd () inline
Definition at line 89 of file UnsupervisedTools.cpp.
References _bIdx, _count, _idxA, and _size.
unsigned long WindowLLR::getIdxEnd () inline
Definition at line 110 of file ComputeTest.cpp.
Referenced by ComputeTest().
double WindowLLR::getLLR (unsigned long clientIdx)
double WindowLLR::getLLR (unsigned long clientIdx)
Definition at line 207 of file ComputeTest.cpp.
Referenced by adaptModelEMweightedFrames(), and ComputeTest().
bool WindowLLR::isEnd ()
bool WindowLLR::isEnd ()
Definition at line 212 of file ComputeTest.cpp.
Referenced by adaptModelEMweightedFrames(), and ComputeTest().
bool WindowLLR::isSet () inline
Definition at line 86 of file UnsupervisedTools.cpp.
References _set.
bool WindowLLR::isSet () inline
Definition at line 107 of file ComputeTest.cpp.
Referenced by adaptModelEMweightedFrames(), and ComputeTest().
void WindowLLR::setNbClient (unsigned long nClient) inline
Definition at line 87 of file UnsupervisedTools.cpp.
References _initMem(), and _nClient.
void WindowLLR::setNbClient (unsigned long nClient) inline
Definition at line 108 of file ComputeTest.cpp.
Referenced by adaptModelEMweightedFrames(), and ComputeTest().
void WindowLLR::showConfig ()
void WindowLLR::showConfig ()
Definition at line 172 of file ComputeTest.cpp.
Referenced by adaptModelEMweightedFrames(), and ComputeTest().
unsigned long WindowLLR::wCount ()
unsigned long WindowLLR::wCount ()
Definition at line 177 of file ComputeTest.cpp.
Member Data Documentation
DoubleVector * WindowLLR::_accLlrA private
Definition at line 96 of file ComputeTest.cpp.
unsigned long WindowLLR::_bIdx private
Definition at line 98 of file ComputeTest.cpp.
Referenced by getIdxBegin(), and getIdxEnd().
unsigned long WindowLLR::_count private
Definition at line 99 of file ComputeTest.cpp.
Referenced by getIdxEnd().
unsigned long WindowLLR::_dec private
Definition at line 93 of file ComputeTest.cpp.
ULongVector * WindowLLR::_idxA private
Definition at line 97 of file ComputeTest.cpp.
Referenced by getIdxBegin(), and getIdxEnd().
Matrix< double > * WindowLLR::_llrM private
Definition at line 95 of file ComputeTest.cpp.
unsigned long WindowLLR::_nClient private
Definition at line 94 of file ComputeTest.cpp.
Referenced by setNbClient().
bool WindowLLR::_set private
Definition at line 91 of file ComputeTest.cpp.
Referenced by isSet().
unsigned long WindowLLR::_size private
Definition at line 92 of file ComputeTest.cpp.
Referenced by getIdxEnd().
The documentation for this class was generated from the following files:
LIA_SpkDet/ComputeTest/src/ComputeTest.cpp
LIA_SpkTools/src/UnsupervisedTools.cpp