LIA_RAL: Eigen::SwapWrapper< ExpressionType > Class Template Reference
Eigen::SwapWrapper< ExpressionType > Class Template Reference
#include <Swap.h>
Public Types
typedef
internal::dense_xpr_base
< SwapWrapper >::type Base
typedef
internal::packet_traits
< Scalar >::type Packet
typedef internal::conditional
< internal::is_lvalue
< ExpressionType >::value,
Scalar, const Scalar >::type ScalarWithConstIfNotLvalue
Public Member Functions
SwapWrapper (ExpressionType &xpr)
Index rows () const
Index cols () const
Index outerStride () const
Index innerStride () const
ScalarWithConstIfNotLvalue * data ()
const Scalar * data () const
Scalar & coeffRef (Index row, Index col)
Scalar & coeffRef (Index index)
Scalar & coeffRef (Index row, Index col) const
Scalar & coeffRef (Index index) const
template<typename OtherDerived >
void copyCoeff (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
void copyCoeff (Index index, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index index, const DenseBase< OtherDerived > &other)
ExpressionType & expression () const
Protected Attributes
ExpressionType & m_expression
Detailed Description
template<typename ExpressionType>
class Eigen::SwapWrapper< ExpressionType >
Definition at line 27 of file Swap.h.
Member Typedef Documentation
template<typename ExpressionType> typedef internal::dense_xpr_base<SwapWrapper>::type Eigen::SwapWrapper< ExpressionType >::Base
Definition at line 32 of file Swap.h.
template<typename ExpressionType> typedef internal::packet_traits<Scalar>::type Eigen::SwapWrapper< ExpressionType >::Packet
Definition at line 34 of file Swap.h.
template<typename ExpressionType> typedef internal::conditional< internal::is_lvalue<ExpressionType>::value, Scalar, const Scalar >::type Eigen::SwapWrapper< ExpressionType >::ScalarWithConstIfNotLvalue
Definition at line 47 of file Swap.h.
Constructor & Destructor Documentation
template<typename ExpressionType> Eigen::SwapWrapper< ExpressionType >::SwapWrapper (ExpressionType & xpr) inline
Definition at line 36 of file Swap.h.
Member Function Documentation
template<typename ExpressionType> Scalar& Eigen::SwapWrapper< ExpressionType >::coeffRef (Index row, Index col) inline
Definition at line 52 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> Scalar& Eigen::SwapWrapper< ExpressionType >::coeffRef (Index index) inline
Definition at line 57 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> Scalar& Eigen::SwapWrapper< ExpressionType >::coeffRef (Index row, Index col) const inline
Definition at line 62 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> Scalar& Eigen::SwapWrapper< ExpressionType >::coeffRef (Index index) const inline
Definition at line 67 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> Index Eigen::SwapWrapper< ExpressionType >::cols (void) const inline
Definition at line 39 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
Referenced by Eigen::SwapWrapper< ExpressionType >::copyCoeff(), and Eigen::SwapWrapper< ExpressionType >::copyPacket().
template<typename ExpressionType> template<typename OtherDerived > void Eigen::SwapWrapper< ExpressionType >::copyCoeff (Index row, Index col, const DenseBase< OtherDerived > & other) inline
Definition at line 73 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::cols(), eigen_internal_assert, Eigen::SwapWrapper< ExpressionType >::m_expression, and Eigen::SwapWrapper< ExpressionType >::rows().
template<typename ExpressionType> template<typename OtherDerived > void Eigen::SwapWrapper< ExpressionType >::copyCoeff (Index index, const DenseBase< OtherDerived > & other) inline
Definition at line 84 of file Swap.h.
References eigen_internal_assert, and Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> template<typename OtherDerived , int StoreMode, int LoadMode> void Eigen::SwapWrapper< ExpressionType >::copyPacket (Index row, Index col, const DenseBase< OtherDerived > & other) inline
Definition at line 94 of file Swap.h.
References col(), Eigen::SwapWrapper< ExpressionType >::cols(), eigen_internal_assert, Eigen::SwapWrapper< ExpressionType >::m_expression, row(), and Eigen::SwapWrapper< ExpressionType >::rows().
template<typename ExpressionType> template<typename OtherDerived , int StoreMode, int LoadMode> void Eigen::SwapWrapper< ExpressionType >::copyPacket (Index index, const DenseBase< OtherDerived > & other) inline
Definition at line 107 of file Swap.h.
References eigen_internal_assert, and Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> ScalarWithConstIfNotLvalue* Eigen::SwapWrapper< ExpressionType >::data () inline
Definition at line 49 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> const Scalar* Eigen::SwapWrapper< ExpressionType >::data () const inline
Definition at line 50 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> ExpressionType& Eigen::SwapWrapper< ExpressionType >::expression () const inline
Definition at line 118 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> Index Eigen::SwapWrapper< ExpressionType >::innerStride () const inline
Definition at line 41 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> Index Eigen::SwapWrapper< ExpressionType >::outerStride () const inline
Definition at line 40 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
template<typename ExpressionType> Index Eigen::SwapWrapper< ExpressionType >::rows (void) const inline
Definition at line 38 of file Swap.h.
References Eigen::SwapWrapper< ExpressionType >::m_expression.
Referenced by Eigen::SwapWrapper< ExpressionType >::copyCoeff(), and Eigen::SwapWrapper< ExpressionType >::copyPacket().
Member Data Documentation
template<typename ExpressionType> ExpressionType& Eigen::SwapWrapper< ExpressionType >::m_expression protected
Definition at line 121 of file Swap.h.
Referenced by Eigen::SwapWrapper< ExpressionType >::coeffRef(), Eigen::SwapWrapper< ExpressionType >::cols(), Eigen::SwapWrapper< ExpressionType >::copyCoeff(), Eigen::SwapWrapper< ExpressionType >::copyPacket(), Eigen::SwapWrapper< ExpressionType >::data(), Eigen::SwapWrapper< ExpressionType >::expression(), Eigen::SwapWrapper< ExpressionType >::innerStride(), Eigen::SwapWrapper< ExpressionType >::outerStride(), and Eigen::SwapWrapper< ExpressionType >::rows().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/Swap.h