LIA_RAL: Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar > Class Template Reference
Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar > Class Template Reference
#include <GeneralMatrixMatrix.h>
Public Member Functions
level3_blocking ()
DenseIndex mc () const
DenseIndex nc () const
DenseIndex kc () const
LhsScalar * blockA ()
RhsScalar * blockB ()
RhsScalar * blockW ()
Protected Attributes
LhsScalar * m_blockA
RhsScalar * m_blockB
RhsScalar * m_blockW
DenseIndex m_mc
DenseIndex m_nc
DenseIndex m_kc
Private Types
typedef _LhsScalar LhsScalar
typedef _RhsScalar RhsScalar
Detailed Description
template<typename _LhsScalar, typename _RhsScalar>
class Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >
Definition at line 17 of file GeneralMatrixMatrix.h.
Member Typedef Documentation
template<typename _LhsScalar, typename _RhsScalar> typedef _LhsScalar Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::LhsScalar private
Definition at line 243 of file GeneralMatrixMatrix.h.
template<typename _LhsScalar, typename _RhsScalar> typedef _RhsScalar Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::RhsScalar private
Definition at line 244 of file GeneralMatrixMatrix.h.
Constructor & Destructor Documentation
template<typename _LhsScalar, typename _RhsScalar> Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::level3_blocking () inline
Definition at line 257 of file GeneralMatrixMatrix.h.
Member Function Documentation
template<typename _LhsScalar, typename _RhsScalar> LhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA () inline
Definition at line 265 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run().
template<typename _LhsScalar, typename _RhsScalar> RhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB () inline
Definition at line 266 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run().
template<typename _LhsScalar, typename _RhsScalar> RhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockW () inline
Definition at line 267 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run().
template<typename _LhsScalar, typename _RhsScalar> DenseIndex Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc () const inline
Definition at line 263 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run().
template<typename _LhsScalar, typename _RhsScalar> DenseIndex Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc () const inline
Definition at line 261 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run().
template<typename _LhsScalar, typename _RhsScalar> DenseIndex Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::nc () const inline
Definition at line 262 of file GeneralMatrixMatrix.h.
Member Data Documentation
template<typename _LhsScalar, typename _RhsScalar> LhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_blockA protected
Definition at line 247 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::level3_blocking< conditional< StorageOrder==RowMajor, _RhsScalar, _LhsScalar >::type, conditional< StorageOrder==RowMajor, _LhsScalar, _RhsScalar >::type >::blockA().
template<typename _LhsScalar, typename _RhsScalar> RhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_blockB protected
Definition at line 248 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::level3_blocking< conditional< StorageOrder==RowMajor, _RhsScalar, _LhsScalar >::type, conditional< StorageOrder==RowMajor, _LhsScalar, _RhsScalar >::type >::blockB().
template<typename _LhsScalar, typename _RhsScalar> RhsScalar* Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_blockW protected
Definition at line 249 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::level3_blocking< conditional< StorageOrder==RowMajor, _RhsScalar, _LhsScalar >::type, conditional< StorageOrder==RowMajor, _LhsScalar, _RhsScalar >::type >::blockW().
template<typename _LhsScalar, typename _RhsScalar> DenseIndex Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_kc protected
Definition at line 253 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::level3_blocking< conditional< StorageOrder==RowMajor, _RhsScalar, _LhsScalar >::type, conditional< StorageOrder==RowMajor, _LhsScalar, _RhsScalar >::type >::kc().
template<typename _LhsScalar, typename _RhsScalar> DenseIndex Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_mc protected
Definition at line 251 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::level3_blocking< conditional< StorageOrder==RowMajor, _RhsScalar, _LhsScalar >::type, conditional< StorageOrder==RowMajor, _LhsScalar, _RhsScalar >::type >::mc().
template<typename _LhsScalar, typename _RhsScalar> DenseIndex Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::m_nc protected
Definition at line 252 of file GeneralMatrixMatrix.h.
Referenced by Eigen::internal::level3_blocking< conditional< StorageOrder==RowMajor, _RhsScalar, _LhsScalar >::type, conditional< StorageOrder==RowMajor, _LhsScalar, _RhsScalar >::type >::nc().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/products/GeneralMatrixMatrix.h