LIA_RAL: Eigen::Quaternion< _Scalar > Class Template Reference
Eigen::Quaternion< _Scalar > Class Template Reference
Geometry_Module
The quaternion class used to represent 3D orientations and rotations.
#include <Quaternion.h>
Public Types
typedef _Scalar Scalar
typedef Matrix< Scalar, 4, 1 > Coefficients
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef AngleAxis< Scalar > AngleAxisType
typedef _Scalar Scalar
typedef internal::traits
< Quaternion >::Coefficients Coefficients
typedef Base::AngleAxisType AngleAxisType
Public Types inherited from Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >
enum
typedef internal::traits
< Quaternion< _Scalar,
_Options > >::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::traits
< Quaternion< _Scalar,
_Options > >::Coefficients Coefficients
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef AngleAxis< Scalar > AngleAxisType
Public Types inherited from Eigen::RotationBase< Quaternion< _Scalar, _Options >, 3 >
enum
enum
typedef ei_traits< Quaternion
< _Scalar, _Options >
>::Scalar Scalar
typedef internal::traits
< Quaternion< _Scalar,
_Options > >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Types inherited from Eigen::RotationBase< Quaternion< _Scalar >, 3 >
enum
enum
typedef ei_traits< Quaternion
< _Scalar > >::Scalar Scalar
typedef internal::traits
< Quaternion< _Scalar >
>::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
Scalar x () const
Scalar y () const
Scalar z () const
Scalar w () const
Scalar & x ()
Scalar & y ()
Scalar & z ()
Scalar & w ()
const Block< const
Coefficients, 3, 1 > vec () const
Block< Coefficients, 3, 1 > vec ()
const Coefficients & coeffs () const
Coefficients & coeffs ()
Quaternion ()
Quaternion (Scalar w, Scalar x, Scalar y, Scalar z)
Quaternion (const Quaternion &other)
Quaternion (const AngleAxisType &aa)
template<typename Derived >
Quaternion (const MatrixBase< Derived > &other)
Quaternion & operator= (const Quaternion &other)
Quaternion & operator= (const AngleAxisType &aa)
template<typename Derived >
Quaternion & operator= (const MatrixBase< Derived > &m)
Quaternion & setIdentity ()
Scalar squaredNorm () const
Scalar norm () const
void normalize ()
Quaternion normalized () const
Scalar eigen2_dot (const Quaternion &other) const
Scalar angularDistance (const Quaternion &other) const
Matrix3 toRotationMatrix (void) const
template<typename Derived1 , typename Derived2 >
Quaternion & setFromTwoVectors (const MatrixBase< Derived1 > &a, const MatrixBase< Derived2 > &b)
Quaternion operator* (const Quaternion &q) const
Quaternion & operator*= (const Quaternion &q)
Quaternion inverse (void) const
Quaternion conjugate (void) const
Quaternion slerp (Scalar t, const Quaternion &other) const
template<typename Derived >
Vector3 operator* (const MatrixBase< Derived > &vec) const
template<typename NewScalarType >
internal::cast_return_type
< Quaternion, Quaternion
< NewScalarType > >::type cast () const
template<typename OtherScalarType >
Quaternion (const Quaternion< OtherScalarType > &other)
bool isApprox (const Quaternion &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
Quaternion ()
Quaternion (Scalar w, Scalar x, Scalar y, Scalar z)
Quaternion (const Scalar *data)
template<class Derived >
EIGEN_STRONG_INLINE Quaternion (const QuaternionBase< Derived > &other)
Quaternion (const AngleAxisType &aa)
template<typename Derived >
Quaternion (const MatrixBase< Derived > &other)
template<typename OtherScalar , int OtherOptions>
Quaternion (const Quaternion< OtherScalar, OtherOptions > &other)
Coefficients & coeffs ()
const Coefficients & coeffs () const
template<typename Derived >
Quaternion< Scalar >::Vector3 operator* (const MatrixBase< Derived > &v) const
template<typename Derived >
Quaternion< Scalar > & operator= (const MatrixBase< Derived > &xpr)
template<typename Derived1 , typename Derived2 >
Quaternion< Scalar > & setFromTwoVectors (const MatrixBase< Derived1 > &a, const MatrixBase< Derived2 > &b)
template<typename Derived1 , typename Derived2 >
Quaternion< Scalar, Options > FromTwoVectors (const MatrixBase< Derived1 > &a, const MatrixBase< Derived2 > &b)
Public Member Functions inherited from Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >
Scalar x () const
Scalar & x ()
Scalar y () const
Scalar & y ()
Scalar z () const
Scalar & z ()
Scalar w () const
Scalar & w ()
const VectorBlock< const
Coefficients, 3 > vec () const
VectorBlock< Coefficients, 3 > vec ()
const internal::traits
< Quaternion< _Scalar,
_Options > >::Coefficients & coeffs () const
internal::traits< Quaternion
< _Scalar, _Options >
>::Coefficients & coeffs ()
EIGEN_STRONG_INLINE
QuaternionBase< Quaternion
< _Scalar, _Options > > & operator= (const QuaternionBase< Quaternion< _Scalar, _Options > > &other)
EIGEN_STRONG_INLINE Quaternion
< _Scalar, _Options > & operator= (const QuaternionBase< OtherDerived > &other)
Quaternion< _Scalar, _Options > & operator= (const AngleAxisType &aa)
Quaternion< _Scalar, _Options > & operator= (const MatrixBase< OtherDerived > &m)
QuaternionBase & setIdentity ()
Scalar squaredNorm () const
Scalar norm () const
void normalize ()
Quaternion< Scalar > normalized () const
Scalar dot (const QuaternionBase< OtherDerived > &other) const
Scalar angularDistance (const QuaternionBase< OtherDerived > &other) const
Matrix3 toRotationMatrix () const
Quaternion< _Scalar, _Options > & setFromTwoVectors (const MatrixBase< Derived1 > &a, const MatrixBase< Derived2 > &b)
EIGEN_STRONG_INLINE Quaternion
< Scalar > operator* (const QuaternionBase< OtherDerived > &q) const
EIGEN_STRONG_INLINE Quaternion
< _Scalar, _Options > & operator*= (const QuaternionBase< OtherDerived > &q)
Quaternion< Scalar > inverse () const
Quaternion< Scalar > conjugate () const
Quaternion< Scalar > slerp (Scalar t, const QuaternionBase< OtherDerived > &other) const
bool isApprox (const QuaternionBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_STRONG_INLINE Vector3 _transformVector (Vector3 v) const
internal::cast_return_type
< Quaternion< _Scalar,
_Options >, Quaternion
< NewScalarType > >::type cast () const
Public Member Functions inherited from Eigen::RotationBase< Quaternion< _Scalar, _Options >, 3 >
const Quaternion< _Scalar,
_Options > & derived () const
Quaternion< _Scalar, _Options > & derived ()
const Quaternion< _Scalar,
_Options > & derived () const
Quaternion< _Scalar, _Options > & derived ()
RotationMatrixType toRotationMatrix () const
RotationMatrixType toRotationMatrix () const
Quaternion< _Scalar, _Options > inverse () const
Quaternion< _Scalar, _Options > inverse () const
Transform< Scalar, Dim > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const Scaling< Scalar, Dim > &s) const
Transform< Scalar, Dim > operator* (const Transform< Scalar, Dim > &t) const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_STRONG_INLINE
internal::rotation_base_generic_product_selector
< Quaternion< _Scalar,
_Options >, OtherDerived,
OtherDerived::IsVectorAtCompileTime >
::ReturnType operator* (const EigenBase< OtherDerived > &e) const
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
RotationMatrixType matrix () const
VectorType _transformVector (const OtherVectorType &v) const
Public Member Functions inherited from Eigen::RotationBase< Quaternion< _Scalar >, 3 >
const Quaternion< _Scalar > & derived () const
Quaternion< _Scalar > & derived ()
const Quaternion< _Scalar > & derived () const
Quaternion< _Scalar > & derived ()
RotationMatrixType toRotationMatrix () const
RotationMatrixType toRotationMatrix () const
Quaternion< _Scalar > inverse () const
Quaternion< _Scalar > inverse () const
Transform< Scalar, Dim > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const Scaling< Scalar, Dim > &s) const
Transform< Scalar, Dim > operator* (const Transform< Scalar, Dim > &t) const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_STRONG_INLINE
internal::rotation_base_generic_product_selector
< Quaternion< _Scalar >
, OtherDerived,
OtherDerived::IsVectorAtCompileTime >
::ReturnType operator* (const EigenBase< OtherDerived > &e) const
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
RotationMatrixType matrix () const
VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static Quaternion Identity ()
template<typename Derived1 , typename Derived2 >
static Quaternion FromTwoVectors (const MatrixBase< Derived1 > &a, const MatrixBase< Derived2 > &b)
Static Public Member Functions inherited from Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >
static Quaternion< Scalar > Identity ()
Static Protected Member Functions
static EIGEN_STRONG_INLINE void _check_template_params ()
Protected Attributes
Coefficients m_coeffs
Private Types
enum { IsAligned = internal::traits<Quaternion>::IsAligned }
typedef RotationBase
< Quaternion< _Scalar >, 3 > Base
typedef QuaternionBase
< Quaternion< _Scalar,
_Options > > Base
Detailed Description
template<typename _Scalar>
class Eigen::Quaternion< _Scalar >
The quaternion class used to represent 3D orientations and rotations.
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
This class represents a quaternion that is a convenient representation of orientations and rotations of objects in three dimensions. Compared to other representations like Euler angles or 3x3 matrices, quatertions offer the following advantages:
compact storage (4 scalars)
efficient to compose (28 flops),
stable spherical interpolation
The following two typedefs are provided for convenience:
Quaternionf for float
Quaterniond for double
See Also
class AngleAxis, class Transform
Definition at line 47 of file Quaternion.h.
Member Typedef Documentation
template<typename _Scalar> typedef AngleAxis<Scalar> Eigen::Quaternion< _Scalar >::AngleAxisType
the equivalent angle-axis type
Definition at line 66 of file Quaternion.h.
template<typename _Scalar> typedef Base::AngleAxisType Eigen::Quaternion< _Scalar >::AngleAxisType
Definition at line 239 of file Quaternion.h.
template<typename _Scalar> typedef RotationBase<Quaternion<_Scalar>,3> Eigen::Quaternion< _Scalar >::Base private
Definition at line 49 of file Quaternion.h.
template<typename _Scalar> typedef QuaternionBase<Quaternion<_Scalar,_Options> > Eigen::Quaternion< _Scalar >::Base private
Definition at line 229 of file Quaternion.h.
template<typename _Scalar> typedef Matrix<Scalar, 4, 1> Eigen::Quaternion< _Scalar >::Coefficients
the type of the Coefficients 4-vector
Definition at line 60 of file Quaternion.h.
template<typename _Scalar> typedef internal::traits<Quaternion>::Coefficients Eigen::Quaternion< _Scalar >::Coefficients
Definition at line 238 of file Quaternion.h.
template<typename _Scalar> typedef Matrix<Scalar,3,3> Eigen::Quaternion< _Scalar >::Matrix3
the equivalent rotation matrix type
Definition at line 64 of file Quaternion.h.
template<typename _Scalar> typedef _Scalar Eigen::Quaternion< _Scalar >::Scalar
the scalar type of the coefficients
Definition at line 57 of file Quaternion.h.
template<typename _Scalar> typedef _Scalar Eigen::Quaternion< _Scalar >::Scalar
Definition at line 233 of file Quaternion.h.
template<typename _Scalar> typedef Matrix<Scalar,3,1> Eigen::Quaternion< _Scalar >::Vector3
the type of a 3D vector
Definition at line 62 of file Quaternion.h.
Member Enumeration Documentation
template<typename _Scalar> anonymous enum private
Enumerator
IsAligned
Definition at line 230 of file Quaternion.h.
Constructor & Destructor Documentation
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion () inline
Default constructor leaving the quaternion uninitialized.
Definition at line 99 of file Quaternion.h.
Referenced by Eigen::Quaternion< _Scalar >::Identity(), and Eigen::Quaternion< _Scalar >::normalized().
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion (Scalar w, Scalar x, Scalar y, Scalar z) inline
Constructs and initializes the quaternion from its four coefficients w, x, y and z.
Warning
Note the order of the arguments: the real w coefficient first, while internally the coefficients are stored in the following order: [x, y, z, w]
Definition at line 108 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs, Eigen::Quaternion< _Scalar >::w(), Eigen::Quaternion< _Scalar >::x(), Eigen::Quaternion< _Scalar >::y(), and Eigen::Quaternion< _Scalar >::z().
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion (const Quaternion< _Scalar > & other) inline
Copy constructor
Definition at line 112 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion (const AngleAxisType & aa) inline explicit
Constructs and initializes a quaternion from the angle-axis aa
Definition at line 115 of file Quaternion.h.
template<typename _Scalar> template<typename Derived > Eigen::Quaternion< _Scalar >::Quaternion (const MatrixBase< Derived > & other) inline explicit
Constructs and initializes a quaternion from either:
a rotation matrix expression,
a 4D vector expression representing quaternion coefficients.
See Also
operator=(MatrixBase<Derived>)
Definition at line 123 of file Quaternion.h.
template<typename _Scalar> template<typename OtherScalarType > Eigen::Quaternion< _Scalar >::Quaternion (const Quaternion< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 192 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::coeffs(), and Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion () inline
Default constructor leaving the quaternion uninitialized.
Definition at line 242 of file Quaternion.h.
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion (Scalar w, Scalar x, Scalar y, Scalar z) inline
Constructs and initializes the quaternion from its four coefficients w, x, y and z.
Warning
Note the order of the arguments: the real w coefficient first, while internally the coefficients are stored in the following order: [x, y, z, w]
Definition at line 251 of file Quaternion.h.
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion (const Scalar * data) inline
Constructs and initialize a quaternion from the array data
Definition at line 254 of file Quaternion.h.
template<typename _Scalar> template<class Derived > EIGEN_STRONG_INLINE Eigen::Quaternion< _Scalar >::Quaternion (const QuaternionBase< Derived > & other) inline
Copy constructor
Definition at line 257 of file Quaternion.h.
template<typename _Scalar> Eigen::Quaternion< _Scalar >::Quaternion (const AngleAxisType & aa) inline explicit
Constructs and initializes a quaternion from the angle-axis aa
Definition at line 260 of file Quaternion.h.
template<typename _Scalar> template<typename Derived > Eigen::Quaternion< _Scalar >::Quaternion (const MatrixBase< Derived > & other) inline explicit
Constructs and initializes a quaternion from either:
a rotation matrix expression,
a 4D vector expression representing quaternion coefficients.
Definition at line 267 of file Quaternion.h.
template<typename _Scalar> template<typename OtherScalar , int OtherOptions> Eigen::Quaternion< _Scalar >::Quaternion (const Quaternion< OtherScalar, OtherOptions > & other) inline explicit
Explicit copy constructor with scalar conversion
Definition at line 271 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::coeffs().
Member Function Documentation
template<typename _Scalar> static EIGEN_STRONG_INLINE void Eigen::Quaternion< _Scalar >::_check_template_params () inline static protected
Definition at line 286 of file Quaternion.h.
References Eigen::DontAlign, and EIGEN_STATIC_ASSERT.
template<typename Scalar > Scalar Eigen::Quaternion< Scalar >::angularDistance (const Quaternion< _Scalar > & other) const inline
Returns
the angle (in radian) between two rotations
See Also
eigen2_dot()
Definition at line 404 of file Quaternion.h.
References acos(), and Eigen::ei_abs().
template<typename _Scalar> template<typename NewScalarType > internal::cast_return_type<Quaternion,Quaternion<NewScalarType> >::type Eigen::Quaternion< _Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 187 of file Quaternion.h.
template<typename _Scalar> const Coefficients& Eigen::Quaternion< _Scalar >::coeffs () const inline
Returns
a read-only vector expression of the coefficients (x,y,z,w)
Definition at line 93 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
Referenced by Eigen::Quaternion< _Scalar >::Quaternion(), Eigen::ei_quaternion_assign_impl< Other, 3, 3 >::run(), Eigen::ei_quaternion_assign_impl< Other, 4, 1 >::run(), and Eigen::Quaternion< _Scalar >::slerp().
template<typename _Scalar> Coefficients& Eigen::Quaternion< _Scalar >::coeffs () inline
Returns
a vector expression of the coefficients (x,y,z,w)
Definition at line 96 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Coefficients& Eigen::Quaternion< _Scalar >::coeffs () inline
Definition at line 277 of file Quaternion.h.
template<typename _Scalar> const Coefficients& Eigen::Quaternion< _Scalar >::coeffs () const inline
Definition at line 278 of file Quaternion.h.
template<typename Scalar > Quaternion< Scalar > Eigen::Quaternion< Scalar >::conjugate (void) const inline
Returns
the conjugate of the *this which is equal to the multiplicative inverse if the quaternion is normalized. The conjugate of a quaternion represents the opposite rotation.
See Also
Quaternion::inverse()
Definition at line 395 of file Quaternion.h.
References Quaternion, and Eigen::internal::y.
template<typename _Scalar> Scalar Eigen::Quaternion< _Scalar >::eigen2_dot (const Quaternion< _Scalar > & other) const inline
Returns
the dot product of *this and other Geometrically speaking, the dot product of two unit quaternions corresponds to the cosine of half the angle between the two rotations.
See Also
angularDistance()
Definition at line 161 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> template<typename Derived1 , typename Derived2 > static Quaternion Eigen::Quaternion< _Scalar >::FromTwoVectors (const MatrixBase< Derived1 > & a, const MatrixBase< Derived2 > & b) static
template<typename _Scalar> template<typename Derived1 , typename Derived2 > Quaternion<Scalar,Options> Eigen::Quaternion< _Scalar >::FromTwoVectors (const MatrixBase< Derived1 > & a, const MatrixBase< Derived2 > & b)
Returns a quaternion representing a rotation between the two arbitrary vectors a and b. In other words, the built rotation represent a rotation sending the line of direction a to the line of direction b, both lines passing through the origin.
Returns
resulting quaternion
Note that the two input vectors do not have to be normalized, and do not need to have the same norm.
Definition at line 630 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::setFromTwoVectors().
template<typename _Scalar> static Quaternion Eigen::Quaternion< _Scalar >::Identity () inline static
Returns
a quaternion representing an identity rotation
See Also
MatrixBase::Identity()
Definition at line 133 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::Quaternion().
template<typename Scalar > Quaternion< Scalar > Eigen::Quaternion< Scalar >::inverse (void) const inline
Returns
the multiplicative inverse of *this Note that in most cases, i.e., if you simply want the opposite rotation, and/or the quaternion is normalized, then it is enough to use the conjugate.
See Also
Quaternion::conjugate()
Definition at line 375 of file Quaternion.h.
References conjugate(), and Quaternion.
template<typename _Scalar> bool Eigen::Quaternion< _Scalar >::isApprox (const Quaternion< _Scalar > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 199 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Scalar Eigen::Quaternion< _Scalar >::norm () const inline
Returns
the norm of the quaternion's coefficients
See Also
Quaternion::squaredNorm(), MatrixBase::norm()
Definition at line 147 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> void Eigen::Quaternion< _Scalar >::normalize (void) inline
Normalizes the quaternion *this
See Also
normalized(), MatrixBase::normalize()
Definition at line 151 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Quaternion Eigen::Quaternion< _Scalar >::normalized () const inline
Returns
a normalized version of *this
See Also
normalize(), MatrixBase::normalized()
Definition at line 154 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs, and Eigen::Quaternion< _Scalar >::Quaternion().
template<typename Scalar > Quaternion< Scalar > Eigen::Quaternion< Scalar >::operator* (const Quaternion< _Scalar > & other) const inline
Returns
the concatenation of two rotations as a quaternion-quaternion product
Definition at line 228 of file Quaternion.h.
References Eigen::ei_quaternion_product().
template<typename _Scalar> template<typename Derived > Vector3 Eigen::Quaternion< _Scalar >::operator* (const MatrixBase< Derived > & vec) const
template<typename _Scalar> template<typename Derived > Quaternion<Scalar>::Vector3 Eigen::Quaternion< _Scalar >::operator* (const MatrixBase< Derived > & v) const inline
Rotation of a vector by a quaternion.
Remarks
If the quaternion is used to rotate several points (>1) then it is much more efficient to first convert it to a 3x3 Matrix. Comparison of the operation cost for n transformations:
Quaternion: 30n
Via a Matrix3: 24 + 15n
Definition at line 250 of file Quaternion.h.
template<typename Scalar > Quaternion< Scalar > & Eigen::Quaternion< Scalar >::operator*= (const Quaternion< _Scalar > & other) inline
See Also
operator*(Quaternion)
Definition at line 235 of file Quaternion.h.
template<typename Scalar > Quaternion< Scalar > & Eigen::Quaternion< Scalar >::operator= (const Quaternion< _Scalar > & other) inline
Definition at line 263 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename Scalar > Quaternion< Scalar > & Eigen::Quaternion< Scalar >::operator= (const AngleAxisType & aa) inline
Set *this from an angle-axis aa and returns a reference to *this
Definition at line 272 of file Quaternion.h.
References Eigen::AngleAxis< Scalar >::angle(), Eigen::AngleAxis< Scalar >::axis(), Eigen::ei_cos(), and Eigen::ei_sin().
template<typename _Scalar> template<typename Derived > Quaternion& Eigen::Quaternion< _Scalar >::operator= (const MatrixBase< Derived > & m)
template<typename _Scalar> template<typename Derived > Quaternion<Scalar>& Eigen::Quaternion< _Scalar >::operator= (const MatrixBase< Derived > & xpr) inline
Set *this from the expression xpr:
if xpr is a 4x1 vector, then xpr is assumed to be a quaternion
if xpr is a 3x3 matrix, then xpr is assumed to be rotation matrix and xpr is converted to a quaternion
Definition at line 287 of file Quaternion.h.
template<typename _Scalar> template<typename Derived1 , typename Derived2 > Quaternion& Eigen::Quaternion< _Scalar >::setFromTwoVectors (const MatrixBase< Derived1 > & a, const MatrixBase< Derived2 > & b)
Referenced by Eigen::Quaternion< _Scalar >::FromTwoVectors().
template<typename _Scalar> template<typename Derived1 , typename Derived2 > Quaternion<Scalar>& Eigen::Quaternion< _Scalar >::setFromTwoVectors (const MatrixBase< Derived1 > & a, const MatrixBase< Derived2 > & b) inline
Sets *this to be a quaternion representing a rotation sending the vector a to the vector b.
Returns
a reference to *this.
Note that the two input vectors do not have to be normalized.
Definition at line 338 of file Quaternion.h.
References Eigen::ei_isApprox(), Eigen::ei_sqrt(), Eigen::MatrixBase< Derived >::normalized(), and Eigen::PlainObjectBase< Derived >::setZero().
template<typename _Scalar> Quaternion& Eigen::Quaternion< _Scalar >::setIdentity () inline
See Also
Quaternion::Identity(), MatrixBase::setIdentity()
Definition at line 137 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename Scalar > Quaternion< Scalar > Eigen::Quaternion< Scalar >::slerp (Scalar t, const Quaternion< _Scalar > & other) const
Returns
the spherical linear interpolation between the two quaternions *this and other at the parameter t
Definition at line 416 of file Quaternion.h.
References acos(), Eigen::Quaternion< _Scalar >::coeffs(), Eigen::ei_abs(), and Eigen::ei_sin().
template<typename _Scalar> Scalar Eigen::Quaternion< _Scalar >::squaredNorm () const inline
Returns
the squared norm of the quaternion's coefficients
See Also
Quaternion::norm(), MatrixBase::squaredNorm()
Definition at line 142 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename Scalar > Quaternion< Scalar >::Matrix3 Eigen::Quaternion< Scalar >::toRotationMatrix (void) const inline
Convert the quaternion to a 3x3 rotation matrix
Definition at line 296 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::internal::y.
template<typename _Scalar> const Block<const Coefficients,3,1> Eigen::Quaternion< _Scalar >::vec () const inline
Returns
a read-only vector expression of the imaginary part (x,y,z)
Definition at line 87 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
Referenced by Eigen::AngleAxis< Scalar >::operator=().
template<typename _Scalar> Block<Coefficients,3,1> Eigen::Quaternion< _Scalar >::vec () inline
Returns
a vector expression of the imaginary part (x,y,z)
Definition at line 90 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Scalar Eigen::Quaternion< _Scalar >::w () const inline
Returns
the w coefficient
Definition at line 75 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeff(), and Eigen::Quaternion< _Scalar >::m_coeffs.
Referenced by Eigen::ei_quaternion_product(), Eigen::AngleAxis< Scalar >::operator=(), Eigen::Quaternion< _Scalar >::Quaternion(), and Eigen::ei_quaternion_assign_impl< Other, 3, 3 >::run().
template<typename _Scalar> Scalar& Eigen::Quaternion< _Scalar >::w () inline
Returns
a reference to the w coefficient
Definition at line 84 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Scalar Eigen::Quaternion< _Scalar >::x () const inline
Returns
the x coefficient
Definition at line 69 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeff(), and Eigen::Quaternion< _Scalar >::m_coeffs.
Referenced by Eigen::ei_quaternion_product(), Eigen::Quaternion< _Scalar >::Quaternion(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, float, Aligned >::run(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run(), and Eigen::ei_quaternion_assign_impl< Other, 3, 3 >::run().
template<typename _Scalar> Scalar& Eigen::Quaternion< _Scalar >::x () inline
Returns
a reference to the x coefficient
Definition at line 78 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Scalar Eigen::Quaternion< _Scalar >::y () const inline
Returns
the y coefficient
Definition at line 71 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeff(), and Eigen::Quaternion< _Scalar >::m_coeffs.
Referenced by Eigen::ei_quaternion_product(), Eigen::Quaternion< _Scalar >::Quaternion(), and Eigen::ei_quaternion_assign_impl< Other, 3, 3 >::run().
template<typename _Scalar> Scalar& Eigen::Quaternion< _Scalar >::y () inline
Returns
a reference to the y coefficient
Definition at line 80 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::Quaternion< _Scalar >::m_coeffs.
template<typename _Scalar> Scalar Eigen::Quaternion< _Scalar >::z () const inline
Returns
the z coefficient
Definition at line 73 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeff(), and Eigen::Quaternion< _Scalar >::m_coeffs.
Referenced by Eigen::ei_quaternion_product(), Eigen::Quaternion< _Scalar >::Quaternion(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run(), and Eigen::ei_quaternion_assign_impl< Other, 3, 3 >::run().
template<typename _Scalar> Scalar& Eigen::Quaternion< _Scalar >::z () inline
Returns
a reference to the z coefficient
Definition at line 82 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::Quaternion< _Scalar >::m_coeffs.
Member Data Documentation
template<typename _Scalar> Coefficients Eigen::Quaternion< _Scalar >::m_coeffs protected
Definition at line 203 of file Quaternion.h.
Referenced by Eigen::Quaternion< _Scalar >::coeffs(), Eigen::Quaternion< _Scalar >::eigen2_dot(), Eigen::Quaternion< _Scalar >::isApprox(), Eigen::Quaternion< _Scalar >::norm(), Eigen::Quaternion< _Scalar >::normalize(), Eigen::Quaternion< _Scalar >::normalized(), Eigen::Quaternion< _Scalar >::operator=(), Eigen::Quaternion< _Scalar >::Quaternion(), Eigen::Quaternion< _Scalar >::setIdentity(), Eigen::Quaternion< _Scalar >::squaredNorm(), Eigen::Quaternion< _Scalar >::vec(), Eigen::Quaternion< _Scalar >::w(), Eigen::Quaternion< _Scalar >::x(), Eigen::Quaternion< _Scalar >::y(), and Eigen::Quaternion< _Scalar >::z().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigen2Support/Geometry/Quaternion.h