LIA_RAL: JFAAcc Class Reference
JFAAcc Class Reference
#include <AccumulateJFAStat.h>
Public Member Functions
JFAAcc (String &, Config &)
JFAAcc (XList &, Config &)
JFAAcc (String &, Config &, String)
JFAAcc (XList &, Config &, String)
virtual ~JFAAcc ()
virtual String getClassName () const
void computeAndAccumulateJFAStat (Config &config)
void computeAndAccumulateJFAStatUnThreaded (Config &config)
void computeAndAccumulateJFAStat (FeatureServer &fs, Config &config)
void computeAndAccumulateJFAStat (SegCluster &sc, FeatureServer &fs, Config &config)
void resetAcc ()
void resetTmpAcc ()
void resetTmpAcc (String task)
void loadEV (const String &file, Config &config)
void loadEV (Matrix< double > &mat, Config &config)
void loadEC (const String &, Config &)
void loadEC (Matrix< double > &mat, Config &config)
void loadD (const String &file, Config &config)
void loadD (DoubleVector &vec)
void loadN (Config &)
void loadN_h (Config &)
void loadF_X (Config &)
void loadF_X_h (Config &)
void initEV (Config &)
void initEC (Config &)
void initD (Config &)
void initVU ()
void saveV (const String &file, Config &config)
void saveU (const String &file, Config &config)
void saveD (const String &file, Config &config)
void estimateVEVT (Config &config)
void estimateVEVTUnThreaded ()
void estimateUEUT (Config &config)
void estimateUEUTUnThreaded ()
void estimateVUEVUT (Config &)
void estimateVUEVUTUnThreaded ()
void getVY (DoubleVector &vy, String &file)
void getVY (DoubleVector &file, unsigned long spk)
void getVUYX (DoubleVector &vuyx, String &file)
void getVUYX (DoubleVector &vuyx, unsigned long spk)
void getDZ (DoubleVector &dz, unsigned long spk)
void getUX (DoubleVector &ux, unsigned long session)
void getUX (DoubleVector &ux, String &file)
void getVYplusDZ (DoubleVector &vyplusdz, String &file)
void getVYplusDZ (DoubleVector &, unsigned long spk)
void getMplusDZ (DoubleVector &MplusDZ, String &file)
void getMplusDZ (DoubleVector &MplusDZ, unsigned long spk)
void getMplusVY (DoubleVector &MplusVY, String &file)
void getMplusVY (DoubleVector &MplusVY, unsigned long spk)
void getMplusUX (DoubleVector &MplusUX, String &file)
void getMplusUX (DoubleVector &MplusUX, unsigned long session)
void getMplusVYplusDZ (DoubleVector &, String &file)
void getMplusVYplusDZ (DoubleVector &, unsigned long spk)
void getMplusVUYX (DoubleVector &MplusVUYX, String &file)
void getMplusVUYX (DoubleVector &MplusVUYX, unsigned long spk)
void estimateAndInverseL_EV (Config &)
void estimateAndInverseLUnThreaded_EV ()
void estimateAndInverseL_EC (Config &)
void estimateAndInverseLUnThreaded_EC ()
void estimateAndInverseL_VU (Config &)
void estimateAndInverseLUnThreaded_VU ()
void estimateYandV (Config &)
void estimateYandVUnThreaded ()
void estimateY (Config &)
void estimateYUnThreaded ()
void estimateXandU (Config &)
void estimateXandUUnThreaded ()
void estimateX (Config &)
void estimateXUnThreaded ()
void estimateU ()
void estimateZandD ()
void estimateYX ()
void estimateZ ()
void estimateZMAP (double tau)
void updateVestimate ()
void updateUestimate ()
XList & getXList ()
unsigned long getNSpeakers ()
unsigned long getNSessions ()
unsigned long getNDistrib ()
unsigned long getVectSize ()
unsigned long getSvSize ()
unsigned long getRankEV ()
unsigned long getRankEC ()
DoubleVector & getUbmMeans ()
DoubleVector & getUbmInvVar ()
Matrix< double > getV ()
Matrix< double > getU ()
DoubleVector getD ()
Matrix< double > getVU ()
Matrix< double > getY ()
Matrix< double > getX ()
Matrix< double > getZ ()
Matrix< double > getYX ()
void saveX (String xFilename, Config &)
void saveY (String yFilename, Config &)
void saveZ (String zFilename, Config &)
void splitYX ()
void storeAccs ()
void restoreAccs ()
void substractMplusDZ (Config &config)
void substractMplusDZUnThreaded ()
void substractMplusVY (Config &)
void substractMplusVYUnThreaded ()
void substractUX (Config &config)
void substractUXUnThreaded ()
void substractMplusUX ()
void substractMplusVUYX ()
void substractMplusVYplusDZ (Config &)
void substractMplusVYplusDZUnThreaded ()
void substractMplusDZByChannel ()
void getSpeakerModel (MixtureGD &mixture, String &file)
Fonction qui renvoie le modele M_s_h=M+Vy + Dz+Ux.
void normalizeFeatures (alize::SegCluster &segCluster, alize::FeatureServer &featureServer, alize::Config &config)
Normalize features with a smooth mixture transformation o't=ot-sum(P(c|ot)Uc.x)
void substractUXfromFeatures (FeatureServer &fs, Config &config)
void orthonormalizeV ()
void saveAccs (Config &config)
Save Accumulators on disk.
double getLLK (SegCluster &selectedSegments, MixtureGD &model, FeatureServer &fs, Config &config)
void verifyEMLK (Config &config)
Matrix< double > & getN ()
Matrix< double > & getN_h ()
Matrix< double > & getF_X ()
Matrix< double > & getF_X_h ()
Public Attributes
JFATranslate _ndxTable
Association between filename and indexes of speaker and sessions.
Private Member Functions
void _init (XList &list, Config &config)
void _init (XList &list, Config &config, String task)
Private Attributes
MixtureServer _ms
StatServer _ss
XList _fileList
unsigned long _vectSize
unsigned long _n_distrib
unsigned long _svSize
unsigned long _rankEC
unsigned long _rankEV
unsigned long _n_speakers
unsigned long _n_sessions
RealVector< double > _ubm_means
UBM SVs.
RealVector< double > _ubm_invvar
Matrix< double > _matN
Accumulators.
Matrix< double > _N_h
Matrix< double > _F_X
Matrix< double > _F_X_h
Matrix< double > _cN
Copy of accumulators.
Matrix< double > _cN_h
Matrix< double > _cF_X
Matrix< double > _cF_X_h
RealVector< double > _D
JFA Objects.
Matrix< double > _V
Matrix< double > _matU
Matrix< double > _VU
Matrix< double > _Z
Matrix< double > _Y
Matrix< double > _matX
Matrix< double > _YX
RefVector< DoubleSquareMatrix > _vEvT
Accumulators for VSigmaVT.
RefVector< DoubleSquareMatrix > _uEuT
Accumulators for USigmaUT.
RefVector< DoubleSquareMatrix > _vuEvuT
Accumulators for VUSigmaVUT.
RefVector< DoubleSquareMatrix > _l_spk_inv
Accumulators for L EigenVoices and EigenChannel matrices.
RefVector< DoubleSquareMatrix > _l_sess_inv
RefVector< DoubleSquareMatrix > _l_yx_inv
RefVector< DoubleSquareMatrix > _Aev
Accumulators.
Matrix< double > _Cev
RefVector< DoubleSquareMatrix > _Aec
Matrix< double > _Cec
Detailed Description
This class represents a accumulator of statistics. A JFAAcc contains the accumulators needed for Joint Factor Analysis estimation
Author
Anthony Larcher alarc.nosp@m.her@.nosp@m.i2r.a.nosp@m.-sta.nosp@m.r.edu.nosp@m..sg
Version
1.0
Date
2010
Definition at line 174 of file AccumulateJFAStat.h.
Constructor & Destructor Documentation
JFAAcc::JFAAcc (String & featFilename, Config & config)
Definition at line 94 of file AccumulateJFAStat.cpp.
References _init(), and verboseLevel.
JFAAcc::JFAAcc (XList & ndx, Config & config)
Definition at line 139 of file AccumulateJFAStat.cpp.
References _init().
JFAAcc::JFAAcc (String & featFilename, Config & config, String task)
Definition at line 118 of file AccumulateJFAStat.cpp.
References _init(), and verboseLevel.
JFAAcc::JFAAcc (XList & ndx, Config & config, String task)
Definition at line 146 of file AccumulateJFAStat.cpp.
References _init().
JFAAcc::~JFAAcc () virtual
Definition at line 153 of file AccumulateJFAStat.cpp.
References _Aec, _Aev, _l_sess_inv, _l_spk_inv, _l_yx_inv, _uEuT, _vEvT, and _vuEvuT.
Member Function Documentation
void JFAAcc::_init (XList & list, Config & config) private
main fonction to initialise the accumulator
Parameters
list the XList containing speakers and sessions filenames
config config filename
Convert the NDX file
Load the UBM
Read NDX file
Create UBM supervectors
Create and initialise statistics acumulators
Create and initialise statistics acumulators
Initialise Matrices
Create the accumulators for L matrices computation
Create accumulators to compute and inverse L matrices for Eigenvoices
Create accumulators to compute and inverse L matrices for EigenChannel
Create accumulators to compute and inverse L matrices for training phase
Create accumulators to compute the EigenVoices matrix
Create accumulators to compute the EigenChannel matrix
Definition at line 168 of file AccumulateJFAStat.cpp.
References _Aec, _Aev, _Cec, _Cev, _cF_X, _cF_X_h, _cN, _cN_h, _D, _F_X, _F_X_h, _fileList, _l_sess_inv, _l_spk_inv, _l_yx_inv, _matN, _matU, _matX, _ms, _n_distrib, _N_h, _n_sessions, _n_speakers, _ndxTable, _rankEC, _rankEV, _svSize, _ubm_invvar, _ubm_means, _uEuT, _V, _vectSize, _vEvT, _VU, _vuEvuT, _Y, _YX, and _Z.
Referenced by JFAAcc().
void JFAAcc::_init (XList & list, Config & config, String task) private
main fonction to initialise the accumulator for I-Vector processing
Parameters
list the XList containing speakers and sessions filenames
config config filename
Convert the NDX file
Load the UBM
Read NDX file
Create UBM supervectors
Create and initialise statistics acumulators
Create and initialise statistics acumulators
Initialise Matrices
Create the accumulators for L matrices computation
Create accumulators to compute and inverse L matrices for Eigenvoices
Create accumulators to compute and inverse L matrices for training phase
Create accumulators to compute the EigenVoices matrix
Create accumulators to compute the EigenChannel matrix
Definition at line 303 of file AccumulateJFAStat.cpp.
References _Aec, _Aev, _Cec, _Cev, _cF_X, _cF_X_h, _cN, _cN_h, _D, _F_X, _F_X_h, _fileList, _l_sess_inv, _l_spk_inv, _l_yx_inv, _matN, _matU, _matX, _ms, _n_distrib, _N_h, _n_sessions, _n_speakers, _ndxTable, _rankEC, _rankEV, _svSize, _ubm_invvar, _ubm_means, _uEuT, _V, _vectSize, _vEvT, _VU, _vuEvuT, _Y, _YX, and _Z.
void JFAAcc::computeAndAccumulateJFAStat (Config & config)
main fonction to accumulate statistics
Parameters
config config filename
Definition at line 501 of file AccumulateJFAStat.cpp.
References computeAndAccumulateJFAStatUnThreaded().
Referenced by computeAndAccumulateJFAStat(), ComputeJFAStats(), ComputeTestDotProduct(), ComputeTestJFA(), ComputeTestLFA(), EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), EstimateDMatrix(), normFeatLFA(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::computeAndAccumulateJFAStat (FeatureServer & fs, Config & config)
Threaded fonction to accumulate statistics
Parameters
config config filenameFonction to accumulate statistics
fs featureserver containing the required data
config config filename
Definition at line 766 of file AccumulateJFAStat.cpp.
References _fileList, computeAndAccumulateJFAStat(), initializeClusters(), and verifyClusterFile().
void JFAAcc::computeAndAccumulateJFAStat (SegCluster & sc, FeatureServer & fs, Config & config)
Fonction to accumulate statistics
Parameters
sc SegCluster containing the selected segments
fs featureserver containing the required data
config config filename
Fast access to vector and matrices array
Compute Occupations and Statistics
Idx of the first frame of the current file in the feature server
Definition at line 777 of file AccumulateJFAStat.cpp.
References _F_X, _F_X_h, _fileList, _matN, _ms, _n_distrib, _N_h, _ss, _svSize, _vectSize, JFATranslate::locNb(), JFATranslate::sessionNb(), and verboseLevel.
void JFAAcc::computeAndAccumulateJFAStatUnThreaded (Config & config)
Unthreaded fonction to accumulate statistics
Parameters
config config filename
Create and initialise the feature server
Create and initialise feature clusters
Fast access to vector and matrices array
Idx of the first frame of the current file in the feature server
Definition at line 515 of file AccumulateJFAStat.cpp.
References _F_X, _F_X_h, _fileList, _matN, _ms, _n_distrib, _N_h, _ss, _svSize, _vectSize, initializeClusters(), JFATranslate::locNb(), JFATranslate::sessionNb(), verboseLevel, and verifyClusterFile().
Referenced by computeAndAccumulateJFAStat().
void JFAAcc::estimateAndInverseL_EC (Config & config)
Compute the inverse of L matrices for EigenChannel estimation
Parameters
config config filename
Definition at line 2127 of file AccumulateJFAStat.cpp.
References estimateAndInverseLUnThreaded_EC().
Referenced by ComputeTestDotProduct(), ComputeTestJFA(), ComputeTestLFA(), EigenChannelJFA(), EigenChannelLFA(), EstimateDMatrix(), and normFeatLFA().
void JFAAcc::estimateAndInverseL_EV (Config & config)
Compute the inverse of L matrices for EigenVoice estimation
Parameters
config config filename
Definition at line 1959 of file AccumulateJFAStat.cpp.
References estimateAndInverseLUnThreaded_EV().
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::estimateAndInverseL_VU (Config & config)
Compute the inverse of L matrices for EigenChannel and EigenVoice estimation
Parameters
config config filename
Definition at line 2289 of file AccumulateJFAStat.cpp.
References estimateAndInverseLUnThreaded_VU().
Referenced by TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::estimateAndInverseLUnThreaded_EC ()
Compute the inverse of L matrices for EigenChannel estimation without threads
Definition at line 2137 of file AccumulateJFAStat.cpp.
References _l_sess_inv, _n_distrib, _N_h, _n_sessions, _rankEC, _uEuT, and verboseLevel.
Referenced by estimateAndInverseL_EC().
void JFAAcc::estimateAndInverseLUnThreaded_EV ()
Compute the inverse of L matrices for EigenVoice estimation without threads
Definition at line 1970 of file AccumulateJFAStat.cpp.
References _l_spk_inv, _matN, _n_distrib, _n_speakers, _rankEV, _vEvT, and verboseLevel.
Referenced by estimateAndInverseL_EV().
void JFAAcc::estimateAndInverseLUnThreaded_VU ()
Compute the inverse of L matrices for EigenChannel and EigenVoice estimation without threads
Definition at line 2300 of file AccumulateJFAStat.cpp.
References _l_yx_inv, _matN, _n_distrib, _n_speakers, _rankEC, _vuEvuT, and verboseLevel.
Referenced by estimateAndInverseL_VU().
void JFAAcc::estimateU ()
Estimate the EigenChannel Matrix
Definition at line 3424 of file AccumulateJFAStat.cpp.
References _Aec, _Cec, _F_X_h, _l_sess_inv, _matU, _matX, _n_distrib, _N_h, _n_sessions, _rankEC, _svSize, _ubm_invvar, and verboseLevel.
Referenced by EigenChannelLFA().
void JFAAcc::estimateUEUT (Config & config)
Compute the UEUt matrices
Parameters
config config filename
Definition at line 1415 of file AccumulateJFAStat.cpp.
References estimateUEUTUnThreaded().
Referenced by ComputeTestDotProduct(), ComputeTestJFA(), ComputeTestLFA(), EigenChannelJFA(), EigenChannelLFA(), EstimateDMatrix(), and normFeatLFA().
void JFAAcc::estimateUEUTUnThreaded ()
Compute the UEUt matrices without threads
Compute _uEuT matrices
Definition at line 1425 of file AccumulateJFAStat.cpp.
References _matU, _n_distrib, _rankEC, _ubm_invvar, _uEuT, _vectSize, and verboseLevel.
Referenced by estimateUEUT().
void JFAAcc::estimateVEVT (Config & config)
Compute the VEVt matrices
Parameters
config config filename
Definition at line 1255 of file AccumulateJFAStat.cpp.
References estimateVEVTUnThreaded().
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::estimateVEVTUnThreaded ()
Compute the VEVt matrices without threads
Compute _vEvT matrices
Definition at line 1266 of file AccumulateJFAStat.cpp.
References _n_distrib, _rankEV, _ubm_invvar, _V, _vectSize, _vEvT, and verboseLevel.
Referenced by estimateVEVT().
void JFAAcc::estimateVUEVUT (Config & config)
Compute the VUEVUt matrices
Parameters
config config filename
Definition at line 1573 of file AccumulateJFAStat.cpp.
References estimateVUEVUTUnThreaded().
Referenced by TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::estimateVUEVUTUnThreaded ()
Compute the VUEVUt matrices without threads
Compute _uEuT matrices
Definition at line 1584 of file AccumulateJFAStat.cpp.
References _n_distrib, _rankEC, _ubm_invvar, _vectSize, _VU, _vuEvuT, and verboseLevel.
Referenced by estimateVUEVUT().
void JFAAcc::estimateX (Config & config)
Estimate X components
Parameters
config config filename
Definition at line 3252 of file AccumulateJFAStat.cpp.
References estimateXUnThreaded().
Referenced by ComputeTestDotProduct(), ComputeTestJFA(), ComputeTestLFA(), EigenChannelLFA(), EstimateDMatrix(), and normFeatLFA().
void JFAAcc::estimateXandU (Config & config)
Estimate EigenChannel matrix and X components
Parameters
config config filename
Definition at line 3030 of file AccumulateJFAStat.cpp.
References estimateXandUUnThreaded().
Referenced by EigenChannelJFA().
void JFAAcc::estimateXandUUnThreaded ()
Estimate EigenChannel matrix and X components without threads
Definition at line 3040 of file AccumulateJFAStat.cpp.
References _Aec, _Cec, _F_X_h, _l_sess_inv, _matU, _matX, _n_distrib, _N_h, _n_sessions, _rankEC, _svSize, _ubm_invvar, and verboseLevel.
Referenced by estimateXandU().
void JFAAcc::estimateXUnThreaded ()
Estimate X components without threads
Definition at line 3262 of file AccumulateJFAStat.cpp.
References _F_X_h, _l_sess_inv, _matU, _matX, _n_sessions, _rankEC, _svSize, _ubm_invvar, and verboseLevel.
Referenced by estimateX().
void JFAAcc::estimateY (Config & config)
Estimate Y components
Parameters
config config filename
Definition at line 2857 of file AccumulateJFAStat.cpp.
References estimateYUnThreaded().
Referenced by EigenChannelJFA(), EigenChannelLFA(), and EstimateDMatrix().
void JFAAcc::estimateYandV (Config & config)
Estimate EigenVoice matrix and Y components
Parameters
config config filename
Definition at line 2457 of file AccumulateJFAStat.cpp.
References estimateYandVUnThreaded().
Referenced by EigenVoice().
void JFAAcc::estimateYandVUnThreaded ()
Estimate EigenVoice matrix and Y components without threads
Definition at line 2467 of file AccumulateJFAStat.cpp.
References _Aev, _Cev, _F_X, _l_spk_inv, _matN, _n_distrib, _n_speakers, _rankEV, _svSize, _ubm_invvar, _V, _Y, verboseLevel, and Eigen::internal::y.
Referenced by estimateYandV().
void JFAAcc::estimateYUnThreaded ()
Estimate Y components without threads
Definition at line 2867 of file AccumulateJFAStat.cpp.
References _F_X, _l_spk_inv, _n_speakers, _rankEV, _svSize, _ubm_invvar, _V, _Y, verboseLevel, and Eigen::internal::y.
Referenced by estimateY().
void JFAAcc::estimateYX ()
Estimate the X and Y components
Definition at line 3518 of file AccumulateJFAStat.cpp.
References _F_X, _l_yx_inv, _n_speakers, _rankEC, _svSize, _ubm_invvar, _VU, _YX, and verboseLevel.
Referenced by TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::estimateZ ()
Estimate the Z components Matrix
Definition at line 3550 of file AccumulateJFAStat.cpp.
References _D, _F_X, _matN, _n_distrib, _n_speakers, _ubm_invvar, _vectSize, _Z, and verboseLevel.
Referenced by TrainTargetJFA().
void JFAAcc::estimateZandD ()
Estimate the D Matrix and Z components
Definition at line 3480 of file AccumulateJFAStat.cpp.
References _D, _F_X, _matN, _n_distrib, _n_speakers, _svSize, _ubm_invvar, _vectSize, _Z, and verboseLevel.
Referenced by EstimateDMatrix().
void JFAAcc::estimateZMAP (double tau)
Estimate the Z components Matrix using the MAP paradigm
Parameters
tau Maximum A Posteriori regulation factor
Definition at line 3576 of file AccumulateJFAStat.cpp.
References _D, _F_X, _matN, _n_distrib, _n_speakers, _ubm_invvar, _vectSize, _Z, and verboseLevel.
Referenced by ComputeTestLFA(), EigenChannelLFA(), normFeatLFA(), and TrainTargetLFA().
String JFAAcc::getClassName () const virtual
Definition at line 165 of file AccumulateJFAStat.cpp.
DoubleVector JFAAcc::getD ()
Return the D Matrix
Definition at line 3706 of file AccumulateJFAStat.cpp.
References _D.
void JFAAcc::getDZ (DoubleVector & dz, unsigned long spk)
Get the DZ supervector for a given speaker
Parameters
dz DoubleVector to fill with the supervector
spk index of the speaker
Compute DZ for speaker spk
Definition at line 1779 of file AccumulateJFAStat.cpp.
References _D, _svSize, and _Z.
Matrix< double > & JFAAcc::getF_X ()
Return the First order speaker statistic Matrix
Definition at line 3761 of file AccumulateJFAStat.cpp.
References _F_X.
Referenced by ComputeTestDotProduct().
Matrix< double > & JFAAcc::getF_X_h ()
Return the First order sessions statistic Matrix
Definition at line 3766 of file AccumulateJFAStat.cpp.
References _F_X_h.
double JFAAcc::getLLK (SegCluster & selectedSegments, MixtureGD & model, FeatureServer & fs, Config & config)
Compute LLK
Parameters
selectedSegments segment cluster to process
model GMM model
config config filename
Definition at line 4803 of file AccumulateJFAStat.cpp.
References _ss, and verboseLevel.
Referenced by verifyEMLK().
void JFAAcc::getMplusDZ (DoubleVector & MplusDZ, String & file)
Get the MplusDZ supervector for a given featurefile
Parameters
MplusDZ DoubleVector to fill with the supervector
file name of the feature file
Definition at line 1849 of file AccumulateJFAStat.cpp.
References _D, _ndxTable, _svSize, _ubm_means, _Z, and JFATranslate::locNb().
Referenced by substractMplusDZByChannel(), and substractMplusDZUnThreaded().
void JFAAcc::getMplusDZ (DoubleVector & MplusDZ, unsigned long spk)
Get the MplusDZ supervector for a given featurefile
Parameters
MplusDZ DoubleVector to fill with the supervector
spk index of the speaker
Definition at line 1860 of file AccumulateJFAStat.cpp.
References _D, _svSize, _ubm_means, and _Z.
void JFAAcc::getMplusUX (DoubleVector & MplusUX, String & file)
Get the MplusUX supervector for a given featurefile
Parameters
MplusUX DoubleVector to fill with the supervector
file name of the feature file
Definition at line 1891 of file AccumulateJFAStat.cpp.
References _svSize, _ubm_means, and getUX().
Referenced by substractMplusUX().
void JFAAcc::getMplusUX (DoubleVector & MplusUX, unsigned long session)
Get the MplusUX supervector for a given session
Parameters
MplusUX DoubleVector to fill with the supervector
spk index of the session
Definition at line 1902 of file AccumulateJFAStat.cpp.
References _svSize, _ubm_means, and getUX().
void JFAAcc::getMplusVUYX (DoubleVector & MplusVUYX, String & file)
Get the MplusVUYX supervector for a given featurefile
Parameters
MplusVUYX DoubleVector to fill with the supervector
file name of the feature file
Definition at line 1937 of file AccumulateJFAStat.cpp.
References _svSize, _ubm_means, and getVUYX().
Referenced by substractMplusVUYX().
void JFAAcc::getMplusVUYX (DoubleVector & MplusVUYX, unsigned long spk)
Get the MplusVUYX supervector for a given speaker
Parameters
MplusVUYX DoubleVector to fill with the supervector
index of the speaker
Definition at line 1948 of file AccumulateJFAStat.cpp.
References _svSize, _ubm_means, and getVUYX().
void JFAAcc::getMplusVY (DoubleVector & MplusVY, String & file)
Get the MplusVY supervector for a given featurefile
Parameters
MplusVY DoubleVector to fill with the supervector
file name of the feature file
Definition at line 1869 of file AccumulateJFAStat.cpp.
References _svSize, _ubm_means, and getVY().
Referenced by substractMplusVYUnThreaded().
void JFAAcc::getMplusVY (DoubleVector & MplusVY, unsigned long spk)
Get the MplusVY supervector for a given speaker
Parameters
MplusVY DoubleVector to fill with the supervector
spk index of the speaker
Definition at line 1880 of file AccumulateJFAStat.cpp.
References _svSize, _ubm_means, and getVY().
void JFAAcc::getMplusVYplusDZ (DoubleVector & Sp, String & file)
Get the MplusVYplusDZ supervector for a given featurefile
Parameters
MplusVYplusDZ DoubleVector to fill with the supervector
file name of the feature file
Definition at line 1913 of file AccumulateJFAStat.cpp.
References _D, _ndxTable, _svSize, _ubm_means, _Z, getVY(), and JFATranslate::locNb().
Referenced by getSpeakerModel(), substractMplusVYplusDZUnThreaded(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::getMplusVYplusDZ (DoubleVector & Sp, unsigned long spk)
Get the MplusVYplusDZ supervector for a given speaker
Parameters
MplusVYplusDZ DoubleVector to fill with the supervector
index of the speaker
Definition at line 1926 of file AccumulateJFAStat.cpp.
References _D, _svSize, _ubm_means, _Z, and getVY().
Matrix< double > & JFAAcc::getN ()
Return the Null order speaker statistic Matrix
Definition at line 3751 of file AccumulateJFAStat.cpp.
References _matN.
Referenced by ComputeTestDotProduct().
Matrix< double > & JFAAcc::getN_h ()
Return the Null order sessions statistic Matrix
Definition at line 3756 of file AccumulateJFAStat.cpp.
References _N_h.
unsigned long JFAAcc::getNDistrib ()
Return the number of distribution of the Universal Backgroud Model
Definition at line 3661 of file AccumulateJFAStat.cpp.
Referenced by ComputeTestDotProduct().
unsigned long JFAAcc::getNSessions ()
Return the number of sessions of the JFAAcc
Definition at line 3656 of file AccumulateJFAStat.cpp.
unsigned long JFAAcc::getNSpeakers ()
Return the number of speakers of the JFAAcc
Definition at line 3651 of file AccumulateJFAStat.cpp.
unsigned long JFAAcc::getRankEC ()
Return the rank of the EigenChannel Matrix
Definition at line 3681 of file AccumulateJFAStat.cpp.
unsigned long JFAAcc::getRankEV ()
Return the rank of the EigenVoice Matrix
Definition at line 3676 of file AccumulateJFAStat.cpp.
void JFAAcc::getSpeakerModel (MixtureGD & mixture, String & file)
Fonction qui renvoie le modele M_s_h=M+Vy + Dz+Ux.
Return the speaker model (M + VY + DZ) for a given feature file
Parameters
mixture mixture to fill with the speaker model
file name of the feature file
Definition at line 4605 of file AccumulateJFAStat.cpp.
References _svSize, getMplusVYplusDZ(), getUX(), and svToModel().
Referenced by normalizeFeatures(), and verifyEMLK().
unsigned long JFAAcc::getSvSize ()
Return the dimension of the supervectors
Definition at line 3671 of file AccumulateJFAStat.cpp.
Referenced by ComputeTestDotProduct(), TrainTargetJFA(), and TrainTargetLFA().
Matrix< double > JFAAcc::getU ()
Return the EigenChannel Matrix
Definition at line 3701 of file AccumulateJFAStat.cpp.
References _matU.
Referenced by EstimateDMatrix().
DoubleVector & JFAAcc::getUbmInvVar ()
Return the Supervector of variances of the UBM
Definition at line 3691 of file AccumulateJFAStat.cpp.
References _ubm_invvar.
Referenced by TrainTargetJFA().
DoubleVector & JFAAcc::getUbmMeans ()
Return the Supervector of means of the UBM
Definition at line 3686 of file AccumulateJFAStat.cpp.
References _ubm_means.
void JFAAcc::getUX (DoubleVector & ux, unsigned long session)
Get the UX supervector for a given session
Parameters
ux DoubleVector to fill with the supervector
session index of the session
Compute UX for session ses
Definition at line 1788 of file AccumulateJFAStat.cpp.
References _matU, _matX, _rankEC, and _svSize.
Referenced by getMplusUX(), getSpeakerModel(), normalizeFeatures(), and substractUXUnThreaded().
void JFAAcc::getUX (DoubleVector & ux, String & file)
Get the UX supervector for a given session
Parameters
ux DoubleVector to fill with the supervector
file name of the feature file
Definition at line 1803 of file AccumulateJFAStat.cpp.
References _matU, _matX, _ndxTable, _rankEC, _svSize, and JFATranslate::sessionNb().
Matrix< double > JFAAcc::getV ()
Return the EigenVoice Matrix
Definition at line 3696 of file AccumulateJFAStat.cpp.
References _V.
Referenced by EigenChannelJFA(), EigenChannelLFA(), and EstimateDMatrix().
unsigned long JFAAcc::getVectSize ()
Return the dimension of feature vectors
Definition at line 3666 of file AccumulateJFAStat.cpp.
Matrix< double > JFAAcc::getVU ()
Definition at line 3711 of file AccumulateJFAStat.cpp.
References _VU.
void JFAAcc::getVUYX (DoubleVector & vuyx, String & file)
Get the VUYX supervector for a feature file
Parameters
vy DoubleVector to fill with the supervector
name of the feature file
Definition at line 1752 of file AccumulateJFAStat.cpp.
References _ndxTable, _rankEV, _svSize, _VU, _YX, and JFATranslate::locNb().
Referenced by getMplusVUYX().
void JFAAcc::getVUYX (DoubleVector & vuyx, unsigned long spk)
Get the VUYX supervector for a given speaker
Parameters
vuyx DoubleVector to fill with the supervector
spk index of the speaker
Definition at line 1766 of file AccumulateJFAStat.cpp.
References _rankEV, _svSize, _VU, and _YX.
void JFAAcc::getVY (DoubleVector & vy, String & file)
Get the VY supervector for a feature file
Parameters
vy DoubleVector to fill with the supervector
name of the feature file
Compute VY for the speaker corresponding to the given file given file
Definition at line 1726 of file AccumulateJFAStat.cpp.
References _ndxTable, _rankEV, _svSize, _V, _Y, JFATranslate::locNb(), and Eigen::internal::y.
Referenced by getMplusVY(), getMplusVYplusDZ(), and getVYplusDZ().
void JFAAcc::getVY (DoubleVector & file, unsigned long spk)
Get the supervector for a given speaker
Parameters
vy DoubleVector to fill with the supervector
spk index of the speaker
Compute VY for speaker spk
Definition at line 1740 of file AccumulateJFAStat.cpp.
References _rankEV, _svSize, _V, _Y, and Eigen::internal::y.
void JFAAcc::getVYplusDZ (DoubleVector & vyplusdz, String & file)
Get the VYplusDZ supervector for a given featurefile
Parameters
vyplusdz DoubleVector to fill with the supervector
file name of the feature file
Definition at line 1819 of file AccumulateJFAStat.cpp.
References _D, _ndxTable, _svSize, _Z, getVY(), and JFATranslate::locNb().
Referenced by TrainTargetJFA().
void JFAAcc::getVYplusDZ (DoubleVector & VYplusDZ, unsigned long spk)
Get the VYplusDZ supervector for a given speaker
Parameters
vyplusdz DoubleVector to fill with the supervector
spk index of the speaker
Definition at line 1834 of file AccumulateJFAStat.cpp.
References _D, _svSize, _Z, and getVY().
Matrix< double > JFAAcc::getX ()
Return the X matrix
Definition at line 3721 of file AccumulateJFAStat.cpp.
References _matX.
XList & JFAAcc::getXList ()
Return the XList
Definition at line 3646 of file AccumulateJFAStat.cpp.
References _fileList.
Matrix< double > JFAAcc::getY ()
Return the Y matrix
Definition at line 3716 of file AccumulateJFAStat.cpp.
References _Y.
Matrix< double > JFAAcc::getYX ()
Return the XY matrix
Definition at line 3731 of file AccumulateJFAStat.cpp.
References _YX.
Matrix< double > JFAAcc::getZ ()
Return the Z matrix
Definition at line 3726 of file AccumulateJFAStat.cpp.
References _Z.
void JFAAcc::initD (Config & config)
initialisation of the D Matrix
Definition at line 1176 of file AccumulateJFAStat.cpp.
References _D, _svSize, _ubm_invvar, boxMullerGenerator(), boxMullerGeneratorInit(), and sqrt().
Referenced by EigenChannelLFA(), and EstimateDMatrix().
void JFAAcc::initEC (Config & config)
Initialise the EigenChannel matrix by a Box-Muller random process
random initialisation of the EigenChannel Matrix
Definition at line 1129 of file AccumulateJFAStat.cpp.
References _matU, _rankEC, _svSize, _ubm_invvar, boxMullerGenerator(), boxMullerGeneratorInit(), and verboseLevel.
Referenced by EigenChannelJFA(), and EigenChannelLFA().
void JFAAcc::initEV (Config & config)
Initialise the EigenVoice matrix by a Box-Muller random process
random initialisation of the EigenVoices Matrix
Definition at line 1070 of file AccumulateJFAStat.cpp.
References _rankEV, _svSize, _ubm_invvar, _V, boxMullerGenerator(), boxMullerGeneratorInit(), and verboseLevel.
Referenced by EigenVoice().
void JFAAcc::initVU ()
Initialise the VU matrix, concatenate the V and U matrices
Definition at line 1227 of file AccumulateJFAStat.cpp.
References _matU, _V, and _VU.
Referenced by TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::loadD (const String & file, Config & config)
Load the D Matrix from a file
Parameters
file name of the matrix file
config config filename
load a D Matrix
Definition at line 997 of file AccumulateJFAStat.cpp.
References _D, and _svSize.
Referenced by ComputeTestDotProduct(), ComputeTestJFA(), ComputeTestLFA(), EstimateDMatrix(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::loadD (DoubleVector & vec)
Load the D Matrix from an existing DoubleVector
Parameters
vec matrix object
Definition at line 1016 of file AccumulateJFAStat.cpp.
References _D, and _svSize.
void JFAAcc::loadEC (const String & ecFilename, Config & config)
Load the EigenChannel Matrix from a file
Parameters
file name of the matrix file
config config filename
load an EigenChannel Matrix
Definition at line 970 of file AccumulateJFAStat.cpp.
References _matU, and _rankEC.
Referenced by ComputeTestDotProduct(), ComputeTestJFA(), ComputeTestLFA(), EigenChannelJFA(), EigenChannelLFA(), EstimateDMatrix(), normFeatLFA(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::loadEC (Matrix< double > & mat, Config & config)
Load the EigenChannel Matrix from an existing matrix
Parameters
mat matrix object
Definition at line 983 of file AccumulateJFAStat.cpp.
References _matU, and _rankEC.
void JFAAcc::loadEV (const String & file, Config & config)
Load the Eigenvoice Matrix from a file
Parameters
file name of the matrix file
config config filename
load an EigenVoices Matrix
Definition at line 930 of file AccumulateJFAStat.cpp.
References _rankEV, and _V.
Referenced by ComputeTestDotProduct(), ComputeTestJFA(), ComputeTestLFA(), EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), EstimateDMatrix(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::loadEV (Matrix< double > & mat, Config & config)
Load the Eigenvoice Matrix from an existing matrix
Parameters
mat matrix object
Definition at line 949 of file AccumulateJFAStat.cpp.
References _rankEV, and _V.
void JFAAcc::loadF_X (Config & config)
Load the first order statistics matrix of speakers
Parameters
config config filename
Definition at line 1048 of file AccumulateJFAStat.cpp.
References _F_X, _fileList, and _svSize.
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::loadF_X_h (Config & config)
Load the first order statistics matrix of sessions
Parameters
config config filename
Definition at line 1059 of file AccumulateJFAStat.cpp.
References _F_X_h, _fileList, and _svSize.
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::loadN (Config & config)
Load the null order statistics matrix of speakers
Parameters
config config filename
Definition at line 1025 of file AccumulateJFAStat.cpp.
References _fileList, _matN, and _n_distrib.
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::loadN_h (Config & config)
Load the null order statistics matrix of sessions
Parameters
config config filename
Definition at line 1036 of file AccumulateJFAStat.cpp.
References _fileList, _n_distrib, and _N_h.
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::normalizeFeatures (alize::SegCluster & segCluster, alize::FeatureServer & featureServer, alize::Config & config)
Normalize features with a smooth mixture transformation o't=ot-sum(P(c|ot)Uc.x)
Normalise features of a cluster by substracting the channel component
Parameters
segCluster segment cluster to process
featureServer feature server to use
config config filename
Definition at line 4623 of file AccumulateJFAStat.cpp.
References _ms, _n_distrib, _vectSize, getSpeakerModel(), getUX(), and verbose.
Referenced by substractUXfromFeatures().
void JFAAcc::orthonormalizeV ()
Orthonormalize the EigenVoice matrix
Definition at line 4700 of file AccumulateJFAStat.cpp.
References _rankEV, _svSize, _V, and sqrt().
Referenced by EigenVoice().
void JFAAcc::resetAcc ()
Function to reset the sufficient statistics accumulators
Definition at line 830 of file AccumulateJFAStat.cpp.
References _F_X, _F_X_h, _matN, _N_h, and verboseLevel.
void JFAAcc::resetTmpAcc ()
Reset the tempporary variables used for matrix estimations
Reinitialise accumulators for L matrices computation
Reinitialise accumulators for L matrices computation and inversion
Definition at line 839 of file AccumulateJFAStat.cpp.
References _Aec, _Aev, _Cec, _Cev, _l_sess_inv, _l_spk_inv, _n_distrib, _n_speakers, _uEuT, and _vEvT.
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), EstimateDMatrix(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::resetTmpAcc (String task)
Reset the tempporary variables used for matrix estimations
Reinitialise accumulators for L matrices computation
Reinitialise accumulators for L matrices computation
Reinitialise accumulators for L matrices computation and inversion
Definition at line 863 of file AccumulateJFAStat.cpp.
References _Aec, _Aev, _Cec, _Cev, _l_sess_inv, _l_spk_inv, _n_distrib, _n_speakers, _uEuT, and _vEvT.
void JFAAcc::restoreAccs ()
Restore the sufficient statistics accumulators
Definition at line 3786 of file AccumulateJFAStat.cpp.
References _cF_X, _cF_X_h, _cN, _cN_h, _F_X, _F_X_h, _matN, _N_h, and verboseLevel.
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), EstimateDMatrix(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::saveAccs (Config & config)
Save Accumulators on disk.
Save Accumulators on disk
Parameters
config config filename
Definition at line 4779 of file AccumulateJFAStat.cpp.
References _F_X, _F_X_h, _matN, _N_h, and verboseLevel.
Referenced by ComputeJFAStats(), EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::saveD (const String & file, Config & config)
Save the D matrix
Parameters
file name of the matrix file to save
Definition at line 1244 of file AccumulateJFAStat.cpp.
References _D, and _svSize.
Referenced by EstimateDMatrix().
void JFAAcc::saveU (const String & file, Config & config)
Save the EigenChannel matrix
Parameters
file name of the matrix file to save
Definition at line 1238 of file AccumulateJFAStat.cpp.
References _matU.
Referenced by EigenChannelJFA(), and EigenChannelLFA().
void JFAAcc::saveV (const String & file, Config & config)
Save the EigenVoice matrix
Parameters
file name of the matrix file to save
Definition at line 1232 of file AccumulateJFAStat.cpp.
References _V.
Referenced by EigenVoice().
void JFAAcc::saveX (String xFilename, Config & config)
Save matrix X
Parameters
xFilename filename to save the matrix
Definition at line 3736 of file AccumulateJFAStat.cpp.
References _matX.
Referenced by TrainTargetJFA().
void JFAAcc::saveY (String yFilename, Config & config)
Save matrix Y
Parameters
yFilename filename to save the matrix
Definition at line 3741 of file AccumulateJFAStat.cpp.
References _Y.
Referenced by TrainTargetJFA().
void JFAAcc::saveZ (String zFilename, Config & config)
Save matrix Z
Parameters
zFilename filename to save the matrix
Definition at line 3746 of file AccumulateJFAStat.cpp.
References _Z.
Referenced by TrainTargetJFA().
void JFAAcc::splitYX ()
Cut the XY matrix to obtain two matrices X and Y
Definition at line 3771 of file AccumulateJFAStat.cpp.
References _matX, _Y, and _YX.
Referenced by TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::storeAccs ()
Store the sufficient statistics accumulators for backup
Definition at line 3777 of file AccumulateJFAStat.cpp.
References _cF_X, _cF_X_h, _cN, _cN_h, _F_X, _F_X_h, _matN, _N_h, and verboseLevel.
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), EstimateDMatrix(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::substractMplusDZ (Config & config)
Substract the speaker component MplusDZ from the speaker statistics
Parameters
config config filename
Definition at line 3795 of file AccumulateJFAStat.cpp.
References substractMplusDZUnThreaded().
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), EstimateDMatrix(), TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::substractMplusDZByChannel ()
Substract the speaker component MplusDZ from the session statistics
Definition at line 3948 of file AccumulateJFAStat.cpp.
References _F_X_h, _fileList, _n_distrib, _N_h, _vectSize, getMplusDZ(), and verboseLevel.
Referenced by ComputeTestLFA(), and normFeatLFA().
void JFAAcc::substractMplusDZUnThreaded ()
Substract the speaker component MplusDZ from the speaker statistics without threads
Definition at line 3805 of file AccumulateJFAStat.cpp.
References _F_X, _matN, _n_distrib, _n_speakers, _vectSize, getMplusDZ(), and verboseLevel.
Referenced by substractMplusDZ().
void JFAAcc::substractMplusUX ()
Substract the channel component MplusUX from the speaker statistics
Parameters
config config filename
Definition at line 4336 of file AccumulateJFAStat.cpp.
References _F_X, _fileList, _n_distrib, _N_h, _vectSize, getMplusUX(), and verboseLevel.
Referenced by ComputeTestDotProduct(), ComputeTestLFA(), EigenChannelLFA(), and normFeatLFA().
void JFAAcc::substractMplusVUYX ()
Substract the channel component MplusUX from the speaker statistics without threads
Definition at line 4366 of file AccumulateJFAStat.cpp.
References _F_X, _matN, _n_distrib, _n_speakers, _vectSize, getMplusVUYX(), and verboseLevel.
Referenced by TrainTargetJFA(), and TrainTargetLFA().
void JFAAcc::substractMplusVY (Config & config)
Substract the speaker component MplusVYplusDZ from the speaker statistics
Parameters
config config filename
Definition at line 3978 of file AccumulateJFAStat.cpp.
References substractMplusVYUnThreaded().
Referenced by EstimateDMatrix().
void JFAAcc::substractMplusVYplusDZ (Config & config)
Substract the speaker component MplusVYplusDZ from the session statistics
Parameters
config config filename
Definition at line 4390 of file AccumulateJFAStat.cpp.
References substractMplusVYplusDZUnThreaded().
Referenced by ComputeTestDotProduct(), ComputeTestJFA(), EigenChannelJFA(), EigenChannelLFA(), and EstimateDMatrix().
void JFAAcc::substractMplusVYplusDZUnThreaded ()
Substract the speaker component MplusVYplusDZ from the session statistics without threads
Definition at line 4400 of file AccumulateJFAStat.cpp.
References _F_X_h, _fileList, _n_distrib, _N_h, _vectSize, getMplusVYplusDZ(), and verboseLevel.
Referenced by substractMplusVYplusDZ().
void JFAAcc::substractMplusVYUnThreaded ()
Substract the speaker component MplusVYplusDZ from the speaker statistics without threads
Definition at line 3988 of file AccumulateJFAStat.cpp.
References _F_X, _matN, _n_distrib, _n_speakers, _vectSize, getMplusVY(), and verboseLevel.
Referenced by substractMplusVY().
void JFAAcc::substractUX (Config & config)
Substract the channel component UX from the speaker statistics
Parameters
config config filename
Definition at line 4142 of file AccumulateJFAStat.cpp.
References substractUXUnThreaded().
Referenced by EigenChannelJFA(), EigenChannelLFA(), EigenVoice(), and EstimateDMatrix().
void JFAAcc::substractUXfromFeatures (FeatureServer & fs, Config & config)
Substract the Channel component from the features
Parameters
fs feature Server to use
config config filename
Definition at line 4689 of file AccumulateJFAStat.cpp.
References _fileList, initializeClusters(), normalizeFeatures(), and verifyClusterFile().
Referenced by ComputeTestJFA(), ComputeTestLFA(), and normFeatLFA().
void JFAAcc::substractUXUnThreaded ()
Substract the channel component UX from the speaker statistics without threads
Definition at line 4152 of file AccumulateJFAStat.cpp.
References _F_X, _fileList, _n_distrib, _N_h, _vectSize, getUX(), and verboseLevel.
Referenced by substractUX().
void JFAAcc::updateUestimate ()
Update the EigenChannel Matrix
Definition at line 3622 of file AccumulateJFAStat.cpp.
References _Aec, _Cec, _matU, _n_distrib, _rankEC, and _vectSize.
Referenced by EigenChannelJFA(), and EigenChannelLFA().
void JFAAcc::updateVestimate ()
Update the EigenVoice Matrix
Definition at line 3597 of file AccumulateJFAStat.cpp.
References _Aev, _Cev, _n_distrib, _rankEV, _V, and _vectSize.
Referenced by EigenVoice().
void JFAAcc::verifyEMLK (Config & config)
Compute LLK
Parameters
selectedSegments segment cluster to process
model GMM model
config config filename
Compute JFA model
Get LLK
Definition at line 4829 of file AccumulateJFAStat.cpp.
References _fileList, getLLK(), getSpeakerModel(), initializeClusters(), verboseLevel, and verifyClusterFile().
Referenced by EigenChannelJFA(), EigenChannelLFA(), and EigenVoice().
Member Data Documentation
RefVector<DoubleSquareMatrix> JFAAcc::_Aec private
Definition at line 232 of file AccumulateJFAStat.h.
Referenced by _init(), estimateU(), estimateXandUUnThreaded(), resetTmpAcc(), updateUestimate(), and ~JFAAcc().
RefVector<DoubleSquareMatrix> JFAAcc::_Aev private
Accumulators.
Definition at line 230 of file AccumulateJFAStat.h.
Referenced by _init(), estimateYandVUnThreaded(), resetTmpAcc(), updateVestimate(), and ~JFAAcc().
Matrix<double> JFAAcc::_Cec private
Definition at line 233 of file AccumulateJFAStat.h.
Referenced by _init(), estimateU(), estimateXandUUnThreaded(), resetTmpAcc(), and updateUestimate().
Matrix<double> JFAAcc::_Cev private
Definition at line 231 of file AccumulateJFAStat.h.
Referenced by _init(), estimateYandVUnThreaded(), resetTmpAcc(), and updateVestimate().
Matrix<double> JFAAcc::_cF_X private
Definition at line 203 of file AccumulateJFAStat.h.
Referenced by _init(), restoreAccs(), and storeAccs().
Matrix<double> JFAAcc::_cF_X_h private
Definition at line 204 of file AccumulateJFAStat.h.
Referenced by _init(), restoreAccs(), and storeAccs().
Matrix<double> JFAAcc::_cN private
Copy of accumulators.
Definition at line 201 of file AccumulateJFAStat.h.
Referenced by _init(), restoreAccs(), and storeAccs().
Matrix<double> JFAAcc::_cN_h private
Definition at line 202 of file AccumulateJFAStat.h.
Referenced by _init(), restoreAccs(), and storeAccs().
RealVector<double> JFAAcc::_D private
JFA Objects.
Definition at line 207 of file AccumulateJFAStat.h.
Referenced by _init(), estimateZ(), estimateZandD(), estimateZMAP(), getD(), getDZ(), getMplusDZ(), getMplusVYplusDZ(), getVYplusDZ(), initD(), loadD(), and saveD().
Matrix<double> JFAAcc::_F_X private
Definition at line 197 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), estimateYandVUnThreaded(), estimateYUnThreaded(), estimateYX(), estimateZ(), estimateZandD(), estimateZMAP(), getF_X(), loadF_X(), resetAcc(), restoreAccs(), saveAccs(), storeAccs(), substractMplusDZUnThreaded(), substractMplusUX(), substractMplusVUYX(), substractMplusVYUnThreaded(), and substractUXUnThreaded().
Matrix<double> JFAAcc::_F_X_h private
Definition at line 198 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), estimateU(), estimateXandUUnThreaded(), estimateXUnThreaded(), getF_X_h(), loadF_X_h(), resetAcc(), restoreAccs(), saveAccs(), storeAccs(), substractMplusDZByChannel(), and substractMplusVYplusDZUnThreaded().
XList JFAAcc::_fileList private
Definition at line 181 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), getXList(), loadF_X(), loadF_X_h(), loadN(), loadN_h(), substractMplusDZByChannel(), substractMplusUX(), substractMplusVYplusDZUnThreaded(), substractUXfromFeatures(), substractUXUnThreaded(), and verifyEMLK().
RefVector<DoubleSquareMatrix> JFAAcc::_l_sess_inv private
Definition at line 226 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EC(), estimateU(), estimateXandUUnThreaded(), estimateXUnThreaded(), resetTmpAcc(), and ~JFAAcc().
RefVector<DoubleSquareMatrix> JFAAcc::_l_spk_inv private
Accumulators for L EigenVoices and EigenChannel matrices.
Definition at line 225 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EV(), estimateYandVUnThreaded(), estimateYUnThreaded(), resetTmpAcc(), and ~JFAAcc().
RefVector<DoubleSquareMatrix> JFAAcc::_l_yx_inv private
Definition at line 227 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_VU(), estimateYX(), and ~JFAAcc().
Matrix<double> JFAAcc::_matN private
Accumulators.
Definition at line 195 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), estimateAndInverseLUnThreaded_EV(), estimateAndInverseLUnThreaded_VU(), estimateYandVUnThreaded(), estimateZ(), estimateZandD(), estimateZMAP(), getN(), loadN(), resetAcc(), restoreAccs(), saveAccs(), storeAccs(), substractMplusDZUnThreaded(), substractMplusVUYX(), and substractMplusVYUnThreaded().
Matrix<double> JFAAcc::_matU private
Definition at line 209 of file AccumulateJFAStat.h.
Referenced by _init(), estimateU(), estimateUEUTUnThreaded(), estimateXandUUnThreaded(), estimateXUnThreaded(), getU(), getUX(), initEC(), initVU(), loadEC(), saveU(), and updateUestimate().
Matrix<double> JFAAcc::_matX private
Definition at line 214 of file AccumulateJFAStat.h.
Referenced by _init(), estimateU(), estimateXandUUnThreaded(), estimateXUnThreaded(), getUX(), getX(), saveX(), and splitYX().
MixtureServer JFAAcc::_ms private
Definition at line 178 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), and normalizeFeatures().
unsigned long JFAAcc::_n_distrib private
Definition at line 183 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), estimateAndInverseLUnThreaded_EC(), estimateAndInverseLUnThreaded_EV(), estimateAndInverseLUnThreaded_VU(), estimateU(), estimateUEUTUnThreaded(), estimateVEVTUnThreaded(), estimateVUEVUTUnThreaded(), estimateXandUUnThreaded(), estimateYandVUnThreaded(), estimateZ(), estimateZandD(), estimateZMAP(), loadN(), loadN_h(), normalizeFeatures(), resetTmpAcc(), substractMplusDZByChannel(), substractMplusDZUnThreaded(), substractMplusUX(), substractMplusVUYX(), substractMplusVYplusDZUnThreaded(), substractMplusVYUnThreaded(), substractUXUnThreaded(), updateUestimate(), and updateVestimate().
Matrix<double> JFAAcc::_N_h private
Definition at line 196 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), estimateAndInverseLUnThreaded_EC(), estimateU(), estimateXandUUnThreaded(), getN_h(), loadN_h(), resetAcc(), restoreAccs(), saveAccs(), storeAccs(), substractMplusDZByChannel(), substractMplusUX(), substractMplusVYplusDZUnThreaded(), and substractUXUnThreaded().
unsigned long JFAAcc::_n_sessions private
Definition at line 188 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EC(), estimateU(), estimateXandUUnThreaded(), and estimateXUnThreaded().
unsigned long JFAAcc::_n_speakers private
Definition at line 187 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EV(), estimateAndInverseLUnThreaded_VU(), estimateYandVUnThreaded(), estimateYUnThreaded(), estimateYX(), estimateZ(), estimateZandD(), estimateZMAP(), resetTmpAcc(), substractMplusDZUnThreaded(), substractMplusVUYX(), and substractMplusVYUnThreaded().
JFATranslate JFAAcc::_ndxTable
Association between filename and indexes of speaker and sessions.
Definition at line 252 of file AccumulateJFAStat.h.
Referenced by _init(), getMplusDZ(), getMplusVYplusDZ(), getUX(), getVUYX(), getVY(), and getVYplusDZ().
unsigned long JFAAcc::_rankEC private
Definition at line 185 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EC(), estimateAndInverseLUnThreaded_VU(), estimateU(), estimateUEUTUnThreaded(), estimateVUEVUTUnThreaded(), estimateXandUUnThreaded(), estimateXUnThreaded(), estimateYX(), getUX(), initEC(), loadEC(), and updateUestimate().
unsigned long JFAAcc::_rankEV private
Definition at line 186 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EV(), estimateVEVTUnThreaded(), estimateYandVUnThreaded(), estimateYUnThreaded(), getVUYX(), getVY(), initEV(), loadEV(), orthonormalizeV(), and updateVestimate().
StatServer JFAAcc::_ss private
Definition at line 179 of file AccumulateJFAStat.h.
Referenced by computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), and getLLK().
unsigned long JFAAcc::_svSize private
Definition at line 184 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), estimateU(), estimateXandUUnThreaded(), estimateXUnThreaded(), estimateYandVUnThreaded(), estimateYUnThreaded(), estimateYX(), estimateZandD(), getDZ(), getMplusDZ(), getMplusUX(), getMplusVUYX(), getMplusVY(), getMplusVYplusDZ(), getSpeakerModel(), getUX(), getVUYX(), getVY(), getVYplusDZ(), initD(), initEC(), initEV(), loadD(), loadF_X(), loadF_X_h(), orthonormalizeV(), and saveD().
RealVector<double> JFAAcc::_ubm_invvar private
Definition at line 192 of file AccumulateJFAStat.h.
Referenced by _init(), estimateU(), estimateUEUTUnThreaded(), estimateVEVTUnThreaded(), estimateVUEVUTUnThreaded(), estimateXandUUnThreaded(), estimateXUnThreaded(), estimateYandVUnThreaded(), estimateYUnThreaded(), estimateYX(), estimateZ(), estimateZandD(), estimateZMAP(), getUbmInvVar(), initD(), initEC(), and initEV().
RealVector<double> JFAAcc::_ubm_means private
UBM SVs.
Definition at line 191 of file AccumulateJFAStat.h.
Referenced by _init(), getMplusDZ(), getMplusUX(), getMplusVUYX(), getMplusVY(), getMplusVYplusDZ(), and getUbmMeans().
RefVector<DoubleSquareMatrix> JFAAcc::_uEuT private
Accumulators for USigmaUT.
Definition at line 220 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EC(), estimateUEUTUnThreaded(), resetTmpAcc(), and ~JFAAcc().
Matrix<double> JFAAcc::_V private
Definition at line 208 of file AccumulateJFAStat.h.
Referenced by _init(), estimateVEVTUnThreaded(), estimateYandVUnThreaded(), estimateYUnThreaded(), getV(), getVY(), initEV(), initVU(), loadEV(), orthonormalizeV(), saveV(), and updateVestimate().
unsigned long JFAAcc::_vectSize private
Definition at line 182 of file AccumulateJFAStat.h.
Referenced by _init(), computeAndAccumulateJFAStat(), computeAndAccumulateJFAStatUnThreaded(), estimateUEUTUnThreaded(), estimateVEVTUnThreaded(), estimateVUEVUTUnThreaded(), estimateZ(), estimateZandD(), estimateZMAP(), normalizeFeatures(), substractMplusDZByChannel(), substractMplusDZUnThreaded(), substractMplusUX(), substractMplusVUYX(), substractMplusVYplusDZUnThreaded(), substractMplusVYUnThreaded(), substractUXUnThreaded(), updateUestimate(), and updateVestimate().
RefVector<DoubleSquareMatrix> JFAAcc::_vEvT private
Accumulators for VSigmaVT.
Definition at line 218 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_EV(), estimateVEVTUnThreaded(), resetTmpAcc(), and ~JFAAcc().
Matrix<double> JFAAcc::_VU private
Definition at line 210 of file AccumulateJFAStat.h.
Referenced by _init(), estimateVUEVUTUnThreaded(), estimateYX(), getVU(), getVUYX(), and initVU().
RefVector<DoubleSquareMatrix> JFAAcc::_vuEvuT private
Accumulators for VUSigmaVUT.
Definition at line 222 of file AccumulateJFAStat.h.
Referenced by _init(), estimateAndInverseLUnThreaded_VU(), estimateVUEVUTUnThreaded(), and ~JFAAcc().
Matrix<double> JFAAcc::_Y private
Definition at line 213 of file AccumulateJFAStat.h.
Referenced by _init(), estimateYandVUnThreaded(), estimateYUnThreaded(), getVY(), getY(), saveY(), and splitYX().
Matrix<double> JFAAcc::_YX private
Definition at line 215 of file AccumulateJFAStat.h.
Referenced by _init(), estimateYX(), getVUYX(), getYX(), and splitYX().
Matrix<double> JFAAcc::_Z private
Definition at line 212 of file AccumulateJFAStat.h.
Referenced by _init(), estimateZ(), estimateZandD(), estimateZMAP(), getDZ(), getMplusDZ(), getMplusVYplusDZ(), getVYplusDZ(), getZ(), and saveZ().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/AccumulateJFAStat.h
LIA_SpkTools/src/AccumulateJFAStat.cpp