LIA_RAL: Eigen::PlainObjectBase< Derived > Class Template Reference
Eigen::PlainObjectBase< Derived > Class Template Reference
Dense storage base class for matrices and arrays.
#include <PlainObjectBase.h>
Classes
struct StridedAlignedMapType
struct StridedConstAlignedMapType
struct StridedConstMapType
struct StridedMapType
Public Types
enum { Options = internal::traits<Derived>::Options }
enum { NeedsToAlign = SizeAtCompileTime != Dynamic && (internal::traits<Derived>::Flags & AlignedBit) != 0 }
typedef
internal::dense_xpr_base
< Derived >::type Base
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
typedef internal::traits
< Derived >::Scalar Scalar
typedef
internal::packet_traits
< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Derived DenseType
typedef Eigen::Map< Derived,
Unaligned > MapType
typedef const Eigen::Map
< const Derived, Unaligned > ConstMapType
typedef Eigen::Map< Derived,
Aligned > AlignedMapType
typedef const Eigen::Map
< const Derived, Aligned > ConstAlignedMapType
Public Member Functions
Base & base ()
const Base & base () const
EIGEN_STRONG_INLINE Index rows () const
EIGEN_STRONG_INLINE Index cols () const
EIGEN_STRONG_INLINE const Scalar & coeff (Index row, Index col) const
EIGEN_STRONG_INLINE const Scalar & coeff (Index index) const
EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_STRONG_INLINE const Scalar & coeffRef (Index row, Index col) const
EIGEN_STRONG_INLINE const Scalar & coeffRef (Index index) const
template<int LoadMode>
EIGEN_STRONG_INLINE PacketScalar packet (Index row, Index col) const
template<int LoadMode>
EIGEN_STRONG_INLINE PacketScalar packet (Index index) const
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketScalar &x)
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketScalar &x)
EIGEN_STRONG_INLINE const Scalar * data () const
EIGEN_STRONG_INLINE Scalar * data ()
EIGEN_STRONG_INLINE void resize (Index rows, Index cols)
void resize (Index size)
void resize (NoChange_t, Index cols)
void resize (Index rows, NoChange_t)
template<typename OtherDerived >
EIGEN_STRONG_INLINE void resizeLike (const EigenBase< OtherDerived > &_other)
EIGEN_STRONG_INLINE void conservativeResize (Index rows, Index cols)
EIGEN_STRONG_INLINE void conservativeResize (Index rows, NoChange_t)
EIGEN_STRONG_INLINE void conservativeResize (NoChange_t, Index cols)
EIGEN_STRONG_INLINE void conservativeResize (Index size)
template<typename OtherDerived >
EIGEN_STRONG_INLINE void conservativeResizeLike (const DenseBase< OtherDerived > &other)
EIGEN_STRONG_INLINE Derived & operator= (const PlainObjectBase &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator= (const ReturnByValue< OtherDerived > &func)
EIGEN_STRONG_INLINE PlainObjectBase ()
PlainObjectBase (internal::constructor_without_unaligned_array_assert)
EIGEN_STRONG_INLINE PlainObjectBase (Index size, Index rows, Index cols)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE PlainObjectBase (const EigenBase< OtherDerived > &other)
Derived & setConstant (Index size, const Scalar &value)
Derived & setConstant (Index rows, Index cols, const Scalar &value)
Derived & setZero (Index size)
Derived & setZero (Index rows, Index cols)
Derived & setOnes (Index size)
Derived & setOnes (Index rows, Index cols)
Derived & setRandom (Index size)
Derived & setRandom (Index rows, Index cols)
Static Public Member Functions
static EIGEN_STRONG_INLINE void _check_template_params ()
Map
These are convenience functions returning Map objects. The Map() static functions return unaligned Map objects, while the AlignedMap() functions return aligned Map objects and thus should be called only with 16-byte-aligned data pointers.
See Also
class Map
static ConstMapType Map (const Scalar *data)
static MapType Map (Scalar *data)
static ConstMapType Map (const Scalar *data, Index size)
static MapType Map (Scalar *data, Index size)
static ConstMapType Map (const Scalar *data, Index rows, Index cols)
static MapType Map (Scalar *data, Index rows, Index cols)
static ConstAlignedMapType MapAligned (const Scalar *data)
static AlignedMapType MapAligned (Scalar *data)
static ConstAlignedMapType MapAligned (const Scalar *data, Index size)
static AlignedMapType MapAligned (Scalar *data, Index size)
static ConstAlignedMapType MapAligned (const Scalar *data, Index rows, Index cols)
static AlignedMapType MapAligned (Scalar *data, Index rows, Index cols)
template<int Outer, int Inner>
static StridedConstMapType
< Stride< Outer, Inner >
>::type Map (const Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedMapType< Stride
< Outer, Inner > >::type Map (Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedConstMapType
< Stride< Outer, Inner >
>::type Map (const Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedMapType< Stride
< Outer, Inner > >::type Map (Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedConstMapType
< Stride< Outer, Inner >
>::type Map (const Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedMapType< Stride
< Outer, Inner > >::type Map (Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static
StridedConstAlignedMapType
< Stride< Outer, Inner >
>::type MapAligned (const Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedAlignedMapType
< Stride< Outer, Inner >
>::type MapAligned (Scalar *data, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static
StridedConstAlignedMapType
< Stride< Outer, Inner >
>::type MapAligned (const Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedAlignedMapType
< Stride< Outer, Inner >
>::type MapAligned (Scalar *data, Index size, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static
StridedConstAlignedMapType
< Stride< Outer, Inner >
>::type MapAligned (const Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
template<int Outer, int Inner>
static StridedAlignedMapType
< Stride< Outer, Inner >
>::type MapAligned (Scalar *data, Index rows, Index cols, const Stride< Outer, Inner > &stride)
Protected Member Functions
template<typename OtherDerived >
EIGEN_STRONG_INLINE void _resize_to_match (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & _set (const DenseBase< OtherDerived > &other)
Copies the value of the expression other into *this with automatic resizing.
template<typename OtherDerived >
EIGEN_STRONG_INLINE void _set_selector (const OtherDerived &other, const internal::true_type &)
template<typename OtherDerived >
EIGEN_STRONG_INLINE void _set_selector (const OtherDerived &other, const internal::false_type &)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & _set_noalias (const DenseBase< OtherDerived > &other)
template<typename T0 , typename T1 >
EIGEN_STRONG_INLINE void _init2 (Index rows, Index cols, typename internal::enable_if< Base::SizeAtCompileTime!=2, T0 >::type *=0)
template<typename T0 , typename T1 >
EIGEN_STRONG_INLINE void _init2 (const Scalar &x, const Scalar &y, typename internal::enable_if< Base::SizeAtCompileTime==2, T0 >::type *=0)
template<typename OtherDerived >
void _swap (DenseBase< OtherDerived > const &other)
Protected Attributes
DenseStorage< Scalar,
Base::MaxSizeAtCompileTime,
Base::RowsAtCompileTime,
Base::ColsAtCompileTime,
Options > m_storage
Private Types
enum { ThisConstantIsPrivateInPlainObjectBase }
Friends
template<typename PlainObjectType , int MapOptions, typename StrideType >
class Eigen::Map
class Eigen::Map< Derived, Unaligned >
class Eigen::Map< const Derived, Unaligned >
class Eigen::Map< Derived, Aligned >
class Eigen::Map< const Derived, Aligned >
template<typename MatrixTypeA , typename MatrixTypeB , bool SwapPointers>
struct internal::matrix_swap_impl
Detailed Description
template<typename Derived>
class Eigen::PlainObjectBase< Derived >
Dense storage base class for matrices and arrays.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizingEigen by defining the preprocessor symbol EIGEN_PLAINOBJECTBASE_PLUGIN.
See Also
TopicClassHierarchy
Definition at line 72 of file PlainObjectBase.h.
Member Typedef Documentation
template<typename Derived> typedef Eigen::Map<Derived, Aligned> Eigen::PlainObjectBase< Derived >::AlignedMapType
Definition at line 101 of file PlainObjectBase.h.
template<typename Derived> typedef internal::dense_xpr_base<Derived>::type Eigen::PlainObjectBase< Derived >::Base
Definition at line 77 of file PlainObjectBase.h.
template<typename Derived> typedef const Eigen::Map<const Derived, Aligned> Eigen::PlainObjectBase< Derived >::ConstAlignedMapType
Definition at line 103 of file PlainObjectBase.h.
template<typename Derived> typedef const Eigen::Map<const Derived, Unaligned> Eigen::PlainObjectBase< Derived >::ConstMapType
Definition at line 99 of file PlainObjectBase.h.
template<typename Derived> typedef Derived Eigen::PlainObjectBase< Derived >::DenseType
Definition at line 84 of file PlainObjectBase.h.
template<typename Derived> typedef internal::traits<Derived>::Index Eigen::PlainObjectBase< Derived >::Index
Definition at line 80 of file PlainObjectBase.h.
template<typename Derived> typedef Eigen::Map<Derived, Unaligned> Eigen::PlainObjectBase< Derived >::MapType
Definition at line 97 of file PlainObjectBase.h.
template<typename Derived> typedef internal::packet_traits<Scalar>::type Eigen::PlainObjectBase< Derived >::PacketScalar
Definition at line 82 of file PlainObjectBase.h.
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::PlainObjectBase< Derived >::RealScalar
Definition at line 83 of file PlainObjectBase.h.
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::PlainObjectBase< Derived >::Scalar
Definition at line 81 of file PlainObjectBase.h.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::PlainObjectBase< Derived >::StorageKind
Definition at line 79 of file PlainObjectBase.h.
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
Options
Definition at line 76 of file PlainObjectBase.h.
template<typename Derived> anonymous enum
Enumerator
NeedsToAlign
Definition at line 113 of file PlainObjectBase.h.
template<typename Derived> anonymous enum private
Enumerator
ThisConstantIsPrivateInPlainObjectBase
Definition at line 653 of file PlainObjectBase.h.
Constructor & Destructor Documentation
template<typename Derived> EIGEN_STRONG_INLINE Eigen::PlainObjectBase< Derived >::PlainObjectBase () inline explicit
Definition at line 403 of file PlainObjectBase.h.
template<typename Derived> Eigen::PlainObjectBase< Derived >::PlainObjectBase (internal::constructor_without_unaligned_array_assert) inline
Definition at line 412 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE Eigen::PlainObjectBase< Derived >::PlainObjectBase (Index size, Index rows, Index cols) inline
Definition at line 419 of file PlainObjectBase.h.
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Eigen::PlainObjectBase< Derived >::PlainObjectBase (const EigenBase< OtherDerived > & other) inline
See Also
MatrixBase::operator=(const EigenBase<OtherDerived>&)
Definition at line 438 of file PlainObjectBase.h.
Member Function Documentation
template<typename Derived> static EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_check_template_params () inline static
Definition at line 637 of file PlainObjectBase.h.
Referenced by Eigen::Array< Index, 64, 1, DontAlign >::Array(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase().
template<typename Derived> template<typename T0 , typename T1 > EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init2 (Index rows, Index cols, typename internal::enable_if< Base::SizeAtCompileTime!=2, T0 >::type * = 0) inline protected
Definition at line 603 of file PlainObjectBase.h.
template<typename Derived> template<typename T0 , typename T1 > EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_init2 (const Scalar & x, const Scalar & y, typename internal::enable_if< Base::SizeAtCompileTime==2, T0 >::type * = 0) inline protected
Definition at line 615 of file PlainObjectBase.h.
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_resize_to_match (const EigenBase< OtherDerived > & other) inline protected
Definition at line 548 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::lazyAssign(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::PlainObjectBase< Derived >::_set (const DenseBase< OtherDerived > & other) inline protected
Copies the value of the expression other into *this with automatic resizing.
*this might be resized to match the dimensions of other. If *this was a null matrix (not already initialized), it will be initialized.
Note that copying a row-vector into a vector (and conversely) is allowed. The resizing, if any, is then done in the appropriate way so that row-vectors remain row-vectors and vectors remain vectors.
See Also
operator=(const MatrixBase<OtherDerived>&), _set_noalias()
Definition at line 574 of file PlainObjectBase.h.
Referenced by Eigen::Array< Index, 64, 1, DontAlign >::operator=(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::PlainObjectBase< Derived >::_set_noalias (const DenseBase< OtherDerived > & other) inline protected
Definition at line 592 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set_selector(), and Eigen::Array< Index, 64, 1, DontAlign >::Array().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_set_selector (const OtherDerived & other, const internal::true_type &) inline protected
Definition at line 581 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::_set_selector (const OtherDerived & other, const internal::false_type &) inline protected
Definition at line 584 of file PlainObjectBase.h.
template<typename Derived> template<typename OtherDerived > void Eigen::PlainObjectBase< Derived >::_swap (DenseBase< OtherDerived > const & other) inline protected
Definition at line 629 of file PlainObjectBase.h.
template<typename Derived> Base& Eigen::PlainObjectBase< Derived >::base () inline
Definition at line 116 of file PlainObjectBase.h.
template<typename Derived> const Base& Eigen::PlainObjectBase< Derived >::base () const inline
Definition at line 117 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE const Scalar& Eigen::PlainObjectBase< Derived >::coeff (Index row, Index col) const inline
Definition at line 122 of file PlainObjectBase.h.
Referenced by Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::ComplexSchur< _MatrixType >::computeShift(), Eigen::RealSchur< _MatrixType >::initFrancisQRStep(), Eigen::Hyperplane< _Scalar, _AmbientDim >::intersection(), Eigen::Hyperplane< _Scalar, _AmbientDim >::offset(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::run(), Eigen::ComplexSchur< _MatrixType >::subdiagonalEntryIsNeglegible(), Eigen::Quaternion< _Scalar >::w(), Eigen::Quaternion< _Scalar >::x(), Eigen::Quaternion< _Scalar >::y(), and Eigen::Quaternion< _Scalar >::z().
template<typename Derived> EIGEN_STRONG_INLINE const Scalar& Eigen::PlainObjectBase< Derived >::coeff (Index index) const inline
Definition at line 130 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE Scalar& Eigen::PlainObjectBase< Derived >::coeffRef (Index row, Index col) inline
Definition at line 135 of file PlainObjectBase.h.
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::_compute(), Eigen::Transform< _Scalar, _Dim >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim >::computeScalingRotation(), Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo(), Eigen::RealSchur< _MatrixType >::initFrancisQRStep(), Eigen::Transform< _Scalar, _Dim >::inverse(), Eigen::Transform< _Scalar, _Dim >::operator=(), Eigen::RealSchur< _MatrixType >::performFrancisQRStep(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run(), Eigen::ComplexSchur< _MatrixType >::subdiagonalEntryIsNeglegible(), Eigen::AngleAxis< Scalar >::toRotationMatrix(), Eigen::QuaternionBase< Derived >::toRotationMatrix(), Eigen::Quaternion< _Scalar >::toRotationMatrix(), Eigen::Quaternion< _Scalar >::w(), Eigen::Quaternion< _Scalar >::x(), Eigen::Quaternion< _Scalar >::y(), and Eigen::Quaternion< _Scalar >::z().
template<typename Derived> EIGEN_STRONG_INLINE Scalar& Eigen::PlainObjectBase< Derived >::coeffRef (Index index) inline
Definition at line 143 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE const Scalar& Eigen::PlainObjectBase< Derived >::coeffRef (Index row, Index col) const inline
Definition at line 148 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE const Scalar& Eigen::PlainObjectBase< Derived >::coeffRef (Index index) const inline
Definition at line 156 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE Index Eigen::PlainObjectBase< Derived >::cols (void) const inline
Definition at line 120 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::internal::bicgstab(), Eigen::internal::conjugate_gradient(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize(), Eigen::internal::llt_rank_update_lower(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), and Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename Derived> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (Index rows, Index cols) inline
Resizes the matrix to rows x cols while leaving old values untouched.
The method is intended for matrices of dynamic size. If you only want to change the number of rows and/or of columns, you can use conservativeResize(NoChange_t, Index) or conservativeResize(Index, NoChange_t).
Matrices are resized relative to the top-left element. In case values need to be appended to the matrix they will be uninitialized.
Definition at line 321 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize().
template<typename Derived> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (Index rows, NoChange_t) inline
Resizes the matrix to rows x cols while leaving old values untouched.
As opposed to conservativeResize(Index rows, Index cols), this version leaves the number of columns unchanged.
In case the matrix is growing, new rows will be uninitialized.
Definition at line 333 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (NoChange_t , Index cols) inline
Resizes the matrix to rows x cols while leaving old values untouched.
As opposed to conservativeResize(Index rows, Index cols), this version leaves the number of rows unchanged.
In case the matrix is growing, new columns will be uninitialized.
Definition at line 346 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResize (Index size) inline
Resizes the vector to size while retaining old values.
. This method does not work for partially dynamic matrices when the static dimension is anything other than 1. For example it will not work with Matrix<double, 2, Dynamic>.
When values are appended, they will be uninitialized.
Definition at line 360 of file PlainObjectBase.h.
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::conservativeResizeLike (const DenseBase< OtherDerived > & other) inline
Resizes the matrix to rows x cols of other, while leaving old values untouched.
The method is intended for matrices of dynamic size. If you only want to change the number of rows and/or of columns, you can use conservativeResize(NoChange_t, Index) or conservativeResize(Index, NoChange_t).
Matrices are resized relative to the top-left element. In case values need to be appended to the matrix they will copied from other.
Definition at line 375 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE const Scalar* Eigen::PlainObjectBase< Derived >::data () const inline
Returns
a const pointer to the data array of this matrix
Definition at line 196 of file PlainObjectBase.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::clean(), Eigen::internal::UpperBidiagonalization< _MatrixType >::compute(), Eigen::internal::conservative_sparse_sparse_product_impl(), Eigen::Transform< _Scalar, _Dim >::data(), Eigen::PardisoImpl< PardisoLU< MatrixType > >::pardisoRelease(), and Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run().
template<typename Derived> EIGEN_STRONG_INLINE Scalar* Eigen::PlainObjectBase< Derived >::data () inline
Returns
a pointer to the data array of this matrix
Definition at line 200 of file PlainObjectBase.h.
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::PlainObjectBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other) inline
See Also
MatrixBase::lazyAssign()
Definition at line 390 of file PlainObjectBase.h.
template<typename Derived> static ConstMapType Eigen::PlainObjectBase< Derived >::Map (const Scalar * data) inline static
Definition at line 454 of file PlainObjectBase.h.
template<typename Derived> static MapType Eigen::PlainObjectBase< Derived >::Map (Scalar * data) inline static
Definition at line 456 of file PlainObjectBase.h.
template<typename Derived> static ConstMapType Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index size) inline static
Definition at line 458 of file PlainObjectBase.h.
template<typename Derived> static MapType Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index size) inline static
Definition at line 460 of file PlainObjectBase.h.
template<typename Derived> static ConstMapType Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index rows, Index cols) inline static
Definition at line 462 of file PlainObjectBase.h.
template<typename Derived> static MapType Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index rows, Index cols) inline static
Definition at line 464 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedConstMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, const Stride< Outer, Inner > & stride) inline static
Definition at line 481 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::Map (Scalar * data, const Stride< Outer, Inner > & stride) inline static
Definition at line 484 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedConstMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static
Definition at line 487 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static
Definition at line 490 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedConstMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::Map (const Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static
Definition at line 493 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::Map (Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static
Definition at line 496 of file PlainObjectBase.h.
template<typename Derived> static ConstAlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data) inline static
Definition at line 467 of file PlainObjectBase.h.
template<typename Derived> static AlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data) inline static
Definition at line 469 of file PlainObjectBase.h.
template<typename Derived> static ConstAlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index size) inline static
Definition at line 471 of file PlainObjectBase.h.
template<typename Derived> static AlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index size) inline static
Definition at line 473 of file PlainObjectBase.h.
template<typename Derived> static ConstAlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index rows, Index cols) inline static
Definition at line 475 of file PlainObjectBase.h.
template<typename Derived> static AlignedMapType Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index rows, Index cols) inline static
Definition at line 477 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedConstAlignedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, const Stride< Outer, Inner > & stride) inline static
Definition at line 500 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedAlignedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, const Stride< Outer, Inner > & stride) inline static
Definition at line 503 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedConstAlignedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static
Definition at line 506 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedAlignedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index size, const Stride< Outer, Inner > & stride) inline static
Definition at line 509 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedConstAlignedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::MapAligned (const Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static
Definition at line 512 of file PlainObjectBase.h.
template<typename Derived> template<int Outer, int Inner> static StridedAlignedMapType<Stride<Outer, Inner> >::type Eigen::PlainObjectBase< Derived >::MapAligned (Scalar * data, Index rows, Index cols, const Stride< Outer, Inner > & stride) inline static
Definition at line 515 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE Derived& Eigen::PlainObjectBase< Derived >::operator= (const PlainObjectBase< Derived > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
Definition at line 383 of file PlainObjectBase.h.
Referenced by Eigen::Array< Index, 64, 1, DontAlign >::operator=().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::PlainObjectBase< Derived >::operator= (const ReturnByValue< OtherDerived > & func) inline
Definition at line 397 of file PlainObjectBase.h.
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::PlainObjectBase< Derived >::operator= (const EigenBase< OtherDerived > & other) inline
Definition at line 429 of file PlainObjectBase.h.
template<typename Derived> template<int LoadMode> EIGEN_STRONG_INLINE PacketScalar Eigen::PlainObjectBase< Derived >::packet (Index row, Index col) const inline
Definition at line 163 of file PlainObjectBase.h.
template<typename Derived> template<int LoadMode> EIGEN_STRONG_INLINE PacketScalar Eigen::PlainObjectBase< Derived >::packet (Index index) const inline
Definition at line 173 of file PlainObjectBase.h.
template<typename Derived> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::resize (Index rows, Index cols) inline
Resizes *this to a rows x cols matrix.
This method is intended for dynamic-size matrices, although it is legal to call it on any matrix as long as fixed dimensions are left unchanged. If you only want to change the number of rows and/or of columns, you can use resize(NoChange_t, Index), resize(Index, NoChange_t).
If the current number of coefficients of *this exactly matches the product rows * cols, then no memory allocation is performed and the current values are left unchanged. In all other cases, including shrinking, the data is reallocated and all previous values are lost.
Example:
Output:
See Also
resize(Index) for vectors, resize(NoChange_t, Index), resize(Index, NoChange_t)
Definition at line 219 of file PlainObjectBase.h.
Referenced by Eigen::HessenbergDecomposition< _MatrixType >::_compute(), Eigen::Array< Index, 64, 1, DontAlign >::Array(), Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::DiagonalPreconditioner< _MatrixType >::factorize(), Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition(), Eigen::internal::householder_qr_inplace_blocked(), Eigen::internal::householder_qr_inplace_unblocked(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::initFactorization(), Eigen::ProductBase< SelfadjointProductMatrix< Lhs, LhsMode, false, Rhs, RhsMode, false >, Lhs, Rhs >::operator const PlainObject &(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike().
template<typename Derived> void Eigen::PlainObjectBase< Derived >::resize (Index size) inline
Resizes *this to a vector of length size
. This method does not work for partially dynamic matrices when the static dimension is anything other than 1. For example it will not work with Matrix<double, 2, Dynamic>.
Example:
Output:
See Also
resize(Index,Index), resize(NoChange_t, Index), resize(Index, NoChange_t)
Definition at line 244 of file PlainObjectBase.h.
template<typename Derived> void Eigen::PlainObjectBase< Derived >::resize (NoChange_t , Index cols) inline
Resizes the matrix, changing only the number of columns. For the parameter of type NoChange_t, just pass the special value NoChange as in the example below.
Example:
Output:
See Also
resize(Index,Index)
Definition at line 268 of file PlainObjectBase.h.
template<typename Derived> void Eigen::PlainObjectBase< Derived >::resize (Index rows, NoChange_t) inline
Resizes the matrix, changing only the number of rows. For the parameter of type NoChange_t, just pass the special value NoChange as in the example below.
Example:
Output:
See Also
resize(Index,Index)
Definition at line 281 of file PlainObjectBase.h.
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::resizeLike (const EigenBase< OtherDerived > & _other) inline
Resizes *this to have the same dimensions as other. Takes care of doing all the checking that's needed.
Note that copying a row-vector into a vector (and conversely) is allowed. The resizing, if any, is then done in the appropriate way so that row-vectors remain row-vectors and vectors remain vectors.
Definition at line 294 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match().
template<typename Derived> EIGEN_STRONG_INLINE Index Eigen::PlainObjectBase< Derived >::rows (void) const inline
Definition at line 119 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), and Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setConstant (Index size, const Scalar & value)
Resizes to the given size, and sets all coefficients in this expression to the given value.
Example:
Output:
See Also
MatrixBase::setConstant(const Scalar&), setConstant(Index,Index,const Scalar&), class CwiseNullaryOp, MatrixBase::Constant(const Scalar&)
Definition at line 348 of file CwiseNullaryOp.h.
Referenced by Eigen::RealSchur< _MatrixType >::computeShift(), Eigen::Scaling< _Scalar, _Dim >::Scaling(), Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull().
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setConstant (Index rows, Index cols, const Scalar & value)
Resizes to the given size, and sets all coefficients in this expression to the given value.
Parameters
rows the new number of rows
cols the new number of columns
value the value to which all coefficients are set
Example:
Output:
See Also
MatrixBase::setConstant(const Scalar&), setConstant(Index,const Scalar&), class CwiseNullaryOp, MatrixBase::Constant(const Scalar&)
Definition at line 367 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setOnes (Index size)
Resizes to the given size, and sets all coefficients in this expression to one.
Example:
Output:
See Also
MatrixBase::setOnes(), setOnes(Index,Index), class CwiseNullaryOp, MatrixBase::Ones()
Definition at line 641 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setOnes (Index rows, Index cols)
Resizes to the given size, and sets all coefficients in this expression to one.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See Also
MatrixBase::setOnes(), setOnes(Index), class CwiseNullaryOp, MatrixBase::Ones()
Definition at line 659 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setRandom (Index size)
Resizes to the given size, and sets all coefficients in this expression to random values.
Example:
Output:
See Also
MatrixBase::setRandom(), setRandom(Index,Index), class CwiseNullaryOp, MatrixBase::Random()
Definition at line 126 of file Random.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setRandom (Index rows, Index cols)
Resizes to the given size, and sets all coefficients in this expression to random values.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See Also
MatrixBase::setRandom(), setRandom(Index), class CwiseNullaryOp, MatrixBase::Random()
Definition at line 144 of file Random.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setZero (Index size)
Resizes to the given size, and sets all coefficients in this expression to zero.
Example:
Output:
See Also
DenseBase::setZero(), setZero(Index,Index), class CwiseNullaryOp, DenseBase::Zero()
Definition at line 515 of file CwiseNullaryOp.h.
Referenced by Eigen::SVD< MatrixType >::compute(), Eigen::Translation< Scalar, Dim >::operator*(), Eigen::Scaling< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator=(), Eigen::PardisoImpl< PardisoLU< MatrixType > >::PardisoImpl(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), and Eigen::Quaternion< _Scalar >::setFromTwoVectors().
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::PlainObjectBase< Derived >::setZero (Index rows, Index cols)
Resizes to the given size, and sets all coefficients in this expression to zero.
Parameters
rows the new number of rows
cols the new number of columns
Example:
Output:
See Also
DenseBase::setZero(), setZero(Index), class CwiseNullaryOp, DenseBase::Zero()
Definition at line 533 of file CwiseNullaryOp.h.
template<typename Derived> template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::writePacket (Index row, Index col, const PacketScalar & x) inline
Definition at line 180 of file PlainObjectBase.h.
template<typename Derived> template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::PlainObjectBase< Derived >::writePacket (Index index, const PacketScalar & x) inline
Definition at line 190 of file PlainObjectBase.h.
Friends And Related Function Documentation
template<typename Derived> template<typename PlainObjectType , int MapOptions, typename StrideType > friend class Eigen::Map friend
Definition at line 95 of file PlainObjectBase.h.
template<typename Derived> friend class Eigen::Map< const Derived, Aligned > friend
Definition at line 102 of file PlainObjectBase.h.
template<typename Derived> friend class Eigen::Map< const Derived, Unaligned > friend
Definition at line 98 of file PlainObjectBase.h.
template<typename Derived> friend class Eigen::Map< Derived, Aligned > friend
Definition at line 100 of file PlainObjectBase.h.
template<typename Derived> friend class Eigen::Map< Derived, Unaligned > friend
Definition at line 96 of file PlainObjectBase.h.
template<typename Derived> template<typename MatrixTypeA , typename MatrixTypeB , bool SwapPointers> friend struct internal::matrix_swap_impl friend
Definition at line 623 of file PlainObjectBase.h.
Member Data Documentation
template<typename Derived> DenseStorage<Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options> Eigen::PlainObjectBase< Derived >::m_storage protected
Definition at line 110 of file PlainObjectBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::cols(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::rows(), Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >::run(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/PlainObjectBase.h
include/Eigen/src/Core/CwiseNullaryOp.h
include/Eigen/src/Core/Random.h