LIA_RAL: Eigen::ColPivHouseholderQR< MatrixType > Class Template Reference
Eigen::ColPivHouseholderQR< MatrixType > Class Template Reference
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
#include <ForwardDeclarations.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
RowsAtCompileTime, Options,
MaxRowsAtCompileTime,
MaxRowsAtCompileTime > MatrixQType
typedef
internal::plain_diag_type
< MatrixType >::type HCoeffsType
typedef PermutationMatrix
< ColsAtCompileTime,
MaxColsAtCompileTime > PermutationType
typedef
internal::plain_row_type
< MatrixType, Index >::type IntRowVectorType
typedef
internal::plain_row_type
< MatrixType >::type RowVectorType
typedef
internal::plain_row_type
< MatrixType, RealScalar >
::type RealRowVectorType
typedef HouseholderSequence
< MatrixType, HCoeffsType >
::ConjugateReturnType HouseholderSequenceType
Public Member Functions
ColPivHouseholderQR ()
Default Constructor.
ColPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
ColPivHouseholderQR (const MatrixType &matrix)
template<typename Rhs >
const internal::solve_retval
< ColPivHouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ (void) const
const MatrixType & matrixQR () const
ColPivHouseholderQR & compute (const MatrixType &matrix)
const PermutationType & colsPermutation () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const internal::solve_retval
< ColPivHouseholderQR,
typename
MatrixType::IdentityReturnType > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
ColPivHouseholderQR & setThreshold (const RealScalar &threshold)
ColPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
PermutationType m_colsPermutation
IntRowVectorType m_colsTranspositions
RowVectorType m_temp
RealRowVectorType m_colSqNorms
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
Index m_det_pq
Detailed Description
template<typename MatrixType>
class Eigen::ColPivHouseholderQR< MatrixType >
Householder rank-revealing QR decomposition of a matrix with column-pivoting.
Parameters
MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, Q and R such that
by using Householder transformations. Here, P is a permutation matrix, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs column pivoting in order to be rank-revealing and improve numerical stability. It is slower than HouseholderQR, and faster than FullPivHouseholderQR.
See Also
MatrixBase::colPivHouseholderQr()
Definition at line 223 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::ColPivHouseholderQR< MatrixType >::HCoeffsType
Definition at line 53 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef HouseholderSequence<MatrixType,HCoeffsType>::ConjugateReturnType Eigen::ColPivHouseholderQR< MatrixType >::HouseholderSequenceType
Definition at line 58 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef MatrixType::Index Eigen::ColPivHouseholderQR< MatrixType >::Index
Definition at line 51 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef internal::plain_row_type<MatrixType, Index>::type Eigen::ColPivHouseholderQR< MatrixType >::IntRowVectorType
Definition at line 55 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef Matrix<Scalar, RowsAtCompileTime, RowsAtCompileTime, Options, MaxRowsAtCompileTime, MaxRowsAtCompileTime> Eigen::ColPivHouseholderQR< MatrixType >::MatrixQType
Definition at line 52 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef _MatrixType Eigen::ColPivHouseholderQR< MatrixType >::MatrixType
Definition at line 41 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::ColPivHouseholderQR< MatrixType >::PermutationType
Definition at line 54 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef internal::plain_row_type<MatrixType, RealScalar>::type Eigen::ColPivHouseholderQR< MatrixType >::RealRowVectorType
Definition at line 57 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType >::RealScalar
Definition at line 50 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::ColPivHouseholderQR< MatrixType >::RowVectorType
Definition at line 56 of file ColPivHouseholderQR.h.
template<typename MatrixType> typedef MatrixType::Scalar Eigen::ColPivHouseholderQR< MatrixType >::Scalar
Definition at line 49 of file ColPivHouseholderQR.h.
Member Enumeration Documentation
template<typename MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 42 of file ColPivHouseholderQR.h.
Constructor & Destructor Documentation
template<typename MatrixType> Eigen::ColPivHouseholderQR< MatrixType >::ColPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via ColPivHouseholderQR::compute(const MatrixType&).
Definition at line 66 of file ColPivHouseholderQR.h.
template<typename MatrixType> Eigen::ColPivHouseholderQR< MatrixType >::ColPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See Also
ColPivHouseholderQR()
Definition at line 81 of file ColPivHouseholderQR.h.
template<typename MatrixType> Eigen::ColPivHouseholderQR< MatrixType >::ColPivHouseholderQR (const MatrixType & matrix) inline
Definition at line 91 of file ColPivHouseholderQR.h.
Member Function Documentation
template<typename MatrixType > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See Also
logAbsDeterminant(), MatrixBase::determinant()
Definition at line 343 of file ColPivHouseholderQR.h.
References abs(), and eigen_assert.
template<typename MatrixType> Index Eigen::ColPivHouseholderQR< MatrixType >::cols (void) const inline
Definition at line 257 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), and Eigen::ColPivHouseholderQR< _MatrixType >::isInjective().
template<typename MatrixType> const PermutationType& Eigen::ColPivHouseholderQR< MatrixType >::colsPermutation () const inline
Definition at line 141 of file ColPivHouseholderQR.h.
template<typename MatrixType> ColPivHouseholderQR< MatrixType > & Eigen::ColPivHouseholderQR< MatrixType >::compute (const MatrixType & matrix)
Definition at line 359 of file ColPivHouseholderQR.h.
References abs(), abs2(), Eigen::ColPivHouseholderQR< MatrixType >::rows(), and swap().
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::ColPivHouseholderQR().
template<typename MatrixType> Index Eigen::ColPivHouseholderQR< MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 198 of file ColPivHouseholderQR.h.
template<typename MatrixType> const HCoeffsType& Eigen::ColPivHouseholderQR< MatrixType >::hCoeffs () const inline
Definition at line 258 of file ColPivHouseholderQR.h.
template<typename MatrixType > ColPivHouseholderQR< MatrixType >::HouseholderSequenceType Eigen::ColPivHouseholderQR< MatrixType >::householderQ (void) const
Returns
the matrix Q as a sequence of householder transformations
Definition at line 501 of file ColPivHouseholderQR.h.
References eigen_assert.
template<typename MatrixType> const internal::solve_retval<ColPivHouseholderQR, typename MatrixType::IdentityReturnType> Eigen::ColPivHouseholderQR< MatrixType >::inverse (void) const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
Definition at line 249 of file ColPivHouseholderQR.h.
template<typename MatrixType> bool Eigen::ColPivHouseholderQR< MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 211 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible().
template<typename MatrixType> bool Eigen::ColPivHouseholderQR< MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 236 of file ColPivHouseholderQR.h.
template<typename MatrixType> bool Eigen::ColPivHouseholderQR< MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 224 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible().
template<typename MatrixType > MatrixType::RealScalar Eigen::ColPivHouseholderQR< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See Also
absDeterminant(), MatrixBase::determinant()
Definition at line 351 of file ColPivHouseholderQR.h.
References eigen_assert.
template<typename MatrixType> const MatrixType& Eigen::ColPivHouseholderQR< MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
Definition at line 133 of file ColPivHouseholderQR.h.
template<typename MatrixType> RealScalar Eigen::ColPivHouseholderQR< MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of R.
Definition at line 327 of file ColPivHouseholderQR.h.
template<typename MatrixType> Index Eigen::ColPivHouseholderQR< MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See Also
rank()
Definition at line 318 of file ColPivHouseholderQR.h.
template<typename MatrixType> Index Eigen::ColPivHouseholderQR< MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 182 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), and Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective().
template<typename MatrixType> Index Eigen::ColPivHouseholderQR< MatrixType >::rows (void) const inline
Definition at line 256 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< MatrixType >::compute(), and Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective().
template<typename MatrixType> ColPivHouseholderQR& Eigen::ColPivHouseholderQR< MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
Definition at line 277 of file ColPivHouseholderQR.h.
template<typename MatrixType> ColPivHouseholderQR& Eigen::ColPivHouseholderQR< MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
Definition at line 292 of file ColPivHouseholderQR.h.
template<typename MatrixType> template<typename Rhs > const internal::solve_retval<ColPivHouseholderQR, Rhs> Eigen::ColPivHouseholderQR< MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition, if any exists.
Parameters
b the right-hand-side of the equation to solve.
Returns
a solution.
Note
The case where b is a matrix is not yet implemented. Also, this code is space inefficient.
Example:
Output:
Definition at line 123 of file ColPivHouseholderQR.h.
template<typename MatrixType> RealScalar Eigen::ColPivHouseholderQR< MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
Definition at line 302 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::rank(), and Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold().
Member Data Documentation
template<typename MatrixType> PermutationType Eigen::ColPivHouseholderQR< MatrixType >::m_colsPermutation protected
Definition at line 332 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation().
template<typename MatrixType> RealRowVectorType Eigen::ColPivHouseholderQR< MatrixType >::m_colSqNorms protected
Definition at line 335 of file ColPivHouseholderQR.h.
template<typename MatrixType> IntRowVectorType Eigen::ColPivHouseholderQR< MatrixType >::m_colsTranspositions protected
Definition at line 333 of file ColPivHouseholderQR.h.
template<typename MatrixType> Index Eigen::ColPivHouseholderQR< MatrixType >::m_det_pq protected
Definition at line 339 of file ColPivHouseholderQR.h.
template<typename MatrixType> HCoeffsType Eigen::ColPivHouseholderQR< MatrixType >::m_hCoeffs protected
Definition at line 331 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::hCoeffs().
template<typename MatrixType> bool Eigen::ColPivHouseholderQR< MatrixType >::m_isInitialized protected
Definition at line 336 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::ColPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::ColPivHouseholderQR< _MatrixType >::inverse(), Eigen::ColPivHouseholderQR< _MatrixType >::isInjective(), Eigen::ColPivHouseholderQR< _MatrixType >::isInvertible(), Eigen::ColPivHouseholderQR< _MatrixType >::isSurjective(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::ColPivHouseholderQR< _MatrixType >::nonzeroPivots(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), Eigen::ColPivHouseholderQR< _MatrixType >::solve(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
template<typename MatrixType> RealScalar Eigen::ColPivHouseholderQR< MatrixType >::m_maxpivot protected
Definition at line 337 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::maxPivot(), and Eigen::ColPivHouseholderQR< _MatrixType >::rank().
template<typename MatrixType> Index Eigen::ColPivHouseholderQR< MatrixType >::m_nonzero_pivots protected
Definition at line 338 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::nonzeroPivots(), and Eigen::ColPivHouseholderQR< _MatrixType >::rank().
template<typename MatrixType> RealScalar Eigen::ColPivHouseholderQR< MatrixType >::m_prescribedThreshold protected
Definition at line 337 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
template<typename MatrixType> MatrixType Eigen::ColPivHouseholderQR< MatrixType >::m_qr protected
Definition at line 330 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::cols(), Eigen::ColPivHouseholderQR< _MatrixType >::inverse(), Eigen::ColPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::ColPivHouseholderQR< _MatrixType >::rank(), Eigen::ColPivHouseholderQR< _MatrixType >::rows(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
template<typename MatrixType> RowVectorType Eigen::ColPivHouseholderQR< MatrixType >::m_temp protected
Definition at line 334 of file ColPivHouseholderQR.h.
template<typename MatrixType> bool Eigen::ColPivHouseholderQR< MatrixType >::m_usePrescribedThreshold protected
Definition at line 336 of file ColPivHouseholderQR.h.
Referenced by Eigen::ColPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::ColPivHouseholderQR< _MatrixType >::threshold().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/QR/ColPivHouseholderQR.h