LIA_RAL: Eigen::PardisoLDLT< _MatrixType, Options > Class Template Reference
Eigen::PardisoLDLT< _MatrixType, Options > Class Template Reference
A sparse direct Cholesky (LDLT) factorization and solver based on the PARDISO library.
#include <PardisoSupport.h>
Public Types
enum { UpLo = Options&(Upper|Lower) }
Public Types inherited from Eigen::PardisoImpl< Derived >
enum { ScalarIsComplex = NumTraits<Scalar>::IsComplex }
typedef Traits::MatrixType MatrixType
typedef Traits::Scalar Scalar
typedef Traits::RealScalar RealScalar
typedef Traits::Index Index
typedef SparseMatrix< Scalar,
RowMajor, Index > SparseMatrixType
typedef Matrix< Scalar,
Dynamic, 1 > VectorType
typedef Matrix< Index,
1, MatrixType::ColsAtCompileTime > IntRowVectorType
typedef Matrix< Index,
MatrixType::RowsAtCompileTime, 1 > IntColVectorType
typedef Array< Index,
64, 1, DontAlign > ParameterType
Public Member Functions
PardisoLDLT ()
PardisoLDLT (const MatrixType &matrix)
void getMatrix (const MatrixType &matrix)
Public Member Functions inherited from Eigen::PardisoImpl< Derived >
PardisoImpl ()
~PardisoImpl ()
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
ParameterType & pardisoParameterArray ()
Derived & analyzePattern (const MatrixType &matrix)
Derived & factorize (const MatrixType &matrix)
Derived & compute (const MatrixType &matrix)
template<typename Rhs >
const internal::solve_retval
< PardisoImpl, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const
internal::sparse_solve_retval
< PardisoImpl, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
Derived & derived ()
const Derived & derived () const
template<typename BDerived , typename XDerived >
bool _solve (const MatrixBase< BDerived > &b, MatrixBase< XDerived > &x) const
template<typename Rhs , typename DestScalar , int DestOptions, typename DestIndex >
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Protected Types
typedef PardisoImpl
< PardisoLDLT< MatrixType,
Options > > Base
typedef Base::Scalar Scalar
typedef Base::Index Index
typedef Base::RealScalar RealScalar
Private Member Functions
PardisoLDLT (PardisoLDLT &)
Friends
class PardisoImpl< PardisoLDLT< MatrixType, Options > >
Additional Inherited Members
Protected Member Functions inherited from Eigen::PardisoImpl< Derived >
void pardisoRelease ()
void pardisoInit (int type)
void manageErrorCode (Index error)
Protected Attributes inherited from Eigen::PardisoImpl< Derived >
SparseMatrixType m_matrix
ComputationInfo m_info
bool m_initialized
bool m_analysisIsOk
bool m_factorizationIsOk
Index m_type
Index m_msglvl
void * m_pt [64]
ParameterType m_iparm
IntColVectorType m_perm
Index m_size
Detailed Description
template<typename _MatrixType, int Options = Upper>
class Eigen::PardisoLDLT< _MatrixType, Options >
A sparse direct Cholesky (LDLT) factorization and solver based on the PARDISO library.
This class allows to solve for A.X = B sparse linear problems via a LDL^T Cholesky factorization using the Intel MKL PARDISO library. The sparse matrix A is assumed to be selfajoint and positive definite. For complex matrices, A can also be symmetric only, see the Options template parameter. The vectors or matrices X and B can be either dense or sparse.
Template Parameters
MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
Options can be any bitwise combination of Upper, Lower, and Symmetric. The default is Upper, meaning only the upper triangular part has to be used. Symmetric can be used for symmetric, non-selfadjoint complex matrices, the default being to assume a selfadjoint matrix. Upper|Lower can be used to tell both triangular parts can be used as input.
See Also
TutorialSparseDirectSolvers
Definition at line 39 of file PardisoSupport.h.
Member Typedef Documentation
template<typename _MatrixType , int Options = Upper> typedef PardisoImpl< PardisoLDLT<MatrixType,Options> > Eigen::PardisoLDLT< _MatrixType, Options >::Base protected
Definition at line 544 of file PardisoSupport.h.
template<typename _MatrixType , int Options = Upper> typedef Base::Index Eigen::PardisoLDLT< _MatrixType, Options >::Index protected
Definition at line 546 of file PardisoSupport.h.
template<typename _MatrixType , int Options = Upper> typedef Base::RealScalar Eigen::PardisoLDLT< _MatrixType, Options >::RealScalar protected
Definition at line 547 of file PardisoSupport.h.
template<typename _MatrixType , int Options = Upper> typedef Base::Scalar Eigen::PardisoLDLT< _MatrixType, Options >::Scalar protected
Definition at line 545 of file PardisoSupport.h.
Member Enumeration Documentation
template<typename _MatrixType , int Options = Upper> anonymous enum
Enumerator
UpLo
Definition at line 556 of file PardisoSupport.h.
Constructor & Destructor Documentation
template<typename _MatrixType , int Options = Upper> Eigen::PardisoLDLT< _MatrixType, Options >::PardisoLDLT () inline
Definition at line 558 of file PardisoSupport.h.
References Eigen::PardisoImpl< Derived >::pardisoInit(), Eigen::PardisoImpl< PardisoLDLT< MatrixType, Options > >::ScalarIsComplex, and Eigen::Symmetric.
template<typename _MatrixType , int Options = Upper> Eigen::PardisoLDLT< _MatrixType, Options >::PardisoLDLT (const MatrixType & matrix) inline
Definition at line 564 of file PardisoSupport.h.
References Eigen::PardisoImpl< Derived >::compute(), Eigen::PardisoImpl< Derived >::pardisoInit(), Eigen::PardisoImpl< PardisoLDLT< MatrixType, Options > >::ScalarIsComplex, and Eigen::Symmetric.
template<typename _MatrixType , int Options = Upper> Eigen::PardisoLDLT< _MatrixType, Options >::PardisoLDLT (PardisoLDLT< _MatrixType, Options > &) inline private
Definition at line 580 of file PardisoSupport.h.
Member Function Documentation
template<typename _MatrixType , int Options = Upper> void Eigen::PardisoLDLT< _MatrixType, Options >::getMatrix (const MatrixType & matrix) inline
Definition at line 571 of file PardisoSupport.h.
References Eigen::PardisoImpl< Derived >::m_matrix, Eigen::SparseMatrix< _Scalar, _Options, _Index >::resize(), and Eigen::SparseMatrixBase< Derived >::twistedBy().
Friends And Related Function Documentation
template<typename _MatrixType , int Options = Upper> friend class PardisoImpl< PardisoLDLT< MatrixType, Options > > friend
Definition at line 550 of file PardisoSupport.h.
The documentation for this class was generated from the following file:
include/Eigen/src/PardisoSupport/PardisoSupport.h