LIA_RAL: ScoreAccum Class Reference
ScoreAccum Class Reference
#include <GeneralTools.h>
Public Member Functions
ScoreAccum ()
~ScoreAccum ()
unsigned long getSize ()
void addAndAccumulate (const String &id, double score, unsigned long nbFrames)
double getScore (const String &id)
double getScore (unsigned long n)
String & getId (unsigned long n)
unsigned long getIndex (const String &id)
Private Attributes
unsigned long _nb
DoubleVector _score
ULongVector _nbFrame
XLine _id
Detailed Description
Definition at line 128 of file GeneralTools.h.
Constructor & Destructor Documentation
ScoreAccum::ScoreAccum () inline
Definition at line 134 of file GeneralTools.h.
ScoreAccum::~ScoreAccum () inline
Definition at line 135 of file GeneralTools.h.
Member Function Documentation
void ScoreAccum::addAndAccumulate (const String & id, double score, unsigned long nbFrames)
Definition at line 240 of file GeneralTools.cpp.
References _id, _nb, _nbFrame, and _score.
Referenced by ComputeTestByLabel(), and ComputeTestHisto().
String & ScoreAccum::getId (unsigned long n)
Definition at line 268 of file GeneralTools.cpp.
References _id, and _nb.
Referenced by ComputeTestByLabel().
unsigned long ScoreAccum::getIndex (const String & id)
Definition at line 257 of file GeneralTools.cpp.
References _id.
Referenced by getScore().
double ScoreAccum::getScore (const String & id)
Definition at line 254 of file GeneralTools.cpp.
References getIndex().
Referenced by ComputeTestByLabel(), and ComputeTestHisto().
double ScoreAccum::getScore (unsigned long n)
Definition at line 262 of file GeneralTools.cpp.
References _nbFrame, and _score.
unsigned long ScoreAccum::getSize () inline
Definition at line 136 of file GeneralTools.h.
Referenced by ComputeTestByLabel().
Member Data Documentation
XLine ScoreAccum::_id private
Definition at line 132 of file GeneralTools.h.
Referenced by addAndAccumulate(), getId(), and getIndex().
unsigned long ScoreAccum::_nb private
Definition at line 129 of file GeneralTools.h.
Referenced by addAndAccumulate(), and getId().
ULongVector ScoreAccum::_nbFrame private
Definition at line 131 of file GeneralTools.h.
Referenced by addAndAccumulate(), and getScore().
DoubleVector ScoreAccum::_score private
Definition at line 130 of file GeneralTools.h.
Referenced by addAndAccumulate(), and getScore().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/GeneralTools.h
LIA_SpkTools/src/GeneralTools.cpp