LIA_RAL: Eigen::HessenbergDecomposition< _MatrixType > Class Template Reference
Eigen::HessenbergDecomposition< _MatrixType > Class Template Reference
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
#include <HessenbergDecomposition.h>
Public Types
enum {
Size = MatrixType::RowsAtCompileTime, SizeMinusOne = Size == Dynamic ? Dynamic : Size - 1, Options = MatrixType::Options, MaxSize = MatrixType::MaxRowsAtCompileTime,
MaxSizeMinusOne = MaxSize == Dynamic ? Dynamic : MaxSize - 1
}
typedef _MatrixType MatrixType
Synonym for the template parameter _MatrixType.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef MatrixType::Index Index
typedef Matrix< Scalar,
SizeMinusOne, 1, Options
&~RowMajor, MaxSizeMinusOne, 1 > CoeffVectorType
Type for vector of Householder coefficients.
typedef HouseholderSequence
< MatrixType, CoeffVectorType >
::ConjugateReturnType HouseholderSequenceType
Return type of matrixQ()
typedef
internal::HessenbergDecompositionMatrixHReturnType
< MatrixType > MatrixHReturnType
Public Member Functions
HessenbergDecomposition (Index size=Size==Dynamic?2:Size)
Default constructor; the decomposition will be computed later.
HessenbergDecomposition (const MatrixType &matrix)
Constructor; computes Hessenberg decomposition of given matrix.
HessenbergDecomposition & compute (const MatrixType &matrix)
Computes Hessenberg decomposition of given matrix.
const CoeffVectorType & householderCoefficients () const
Returns the Householder coefficients.
const MatrixType & packedMatrix () const
Returns the internal representation of the decomposition.
HouseholderSequenceType matrixQ () const
Reconstructs the orthogonal matrix Q in the decomposition.
MatrixHReturnType matrixH () const
Constructs the Hessenberg matrix H in the decomposition.
Protected Attributes
MatrixType m_matrix
CoeffVectorType m_hCoeffs
VectorType m_temp
bool m_isInitialized
Private Types
typedef Matrix< Scalar,
1, Size, Options|RowMajor,
1, MaxSize > VectorType
typedef NumTraits< Scalar >::Real RealScalar
Static Private Member Functions
static void _compute (MatrixType &matA, CoeffVectorType &hCoeffs, VectorType &temp)
Detailed Description
template<typename _MatrixType>
class Eigen::HessenbergDecomposition< _MatrixType >
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
Template Parameters
_MatrixType the type of the matrix of which we are computing the Hessenberg decomposition
This class performs an Hessenberg decomposition of a matrix . In the real case, the Hessenberg decomposition consists of an orthogonal matrix and a Hessenberg matrix such that . An orthogonal matrix is a matrix whose inverse equals its transpose (). A Hessenberg matrix has zeros below the subdiagonal, so it is almost upper triangular. The Hessenberg decomposition of a complex matrix is with unitary (that is,).
Call the function compute() to compute the Hessenberg decomposition of a given matrix. Alternatively, you can use the HessenbergDecomposition(const MatrixType&) constructor which computes the Hessenberg decomposition at construction time. Once the decomposition is computed, you can use the matrixH() and matrixQ() functions to construct the matrices H and Q in the decomposition.
The documentation for matrixH() contains an example of the typical use of this class.
See Also
class ComplexSchur, class Tridiagonalization, QR Module
Definition at line 57 of file HessenbergDecomposition.h.
Member Typedef Documentation
template<typename _MatrixType> typedef Matrix<Scalar, SizeMinusOne, 1, Options & ~RowMajor, MaxSizeMinusOne, 1> Eigen::HessenbergDecomposition< _MatrixType >::CoeffVectorType
Type for vector of Householder coefficients.
This is column vector with entries of type Scalar. The length of the vector is one less than the size of MatrixType, if it is a fixed-side type.
Definition at line 82 of file HessenbergDecomposition.h.
template<typename _MatrixType> typedef HouseholderSequence<MatrixType,CoeffVectorType>::ConjugateReturnType Eigen::HessenbergDecomposition< _MatrixType >::HouseholderSequenceType
Return type of matrixQ()
Definition at line 85 of file HessenbergDecomposition.h.
template<typename _MatrixType> typedef MatrixType::Index Eigen::HessenbergDecomposition< _MatrixType >::Index
Definition at line 74 of file HessenbergDecomposition.h.
template<typename _MatrixType> typedef internal::HessenbergDecompositionMatrixHReturnType<MatrixType> Eigen::HessenbergDecomposition< _MatrixType >::MatrixHReturnType
Definition at line 87 of file HessenbergDecomposition.h.
template<typename _MatrixType> typedef _MatrixType Eigen::HessenbergDecomposition< _MatrixType >::MatrixType
Synonym for the template parameter _MatrixType.
Definition at line 62 of file HessenbergDecomposition.h.
template<typename _MatrixType> typedef NumTraits<Scalar>::Real Eigen::HessenbergDecomposition< _MatrixType >::RealScalar private
Definition at line 269 of file HessenbergDecomposition.h.
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::HessenbergDecomposition< _MatrixType >::Scalar
Scalar type for matrices of type MatrixType.
Definition at line 73 of file HessenbergDecomposition.h.
template<typename _MatrixType> typedef Matrix<Scalar, 1, Size, Options | RowMajor, 1, MaxSize> Eigen::HessenbergDecomposition< _MatrixType >::VectorType private
Definition at line 268 of file HessenbergDecomposition.h.
Member Enumeration Documentation
template<typename _MatrixType> anonymous enum
Enumerator
Size
SizeMinusOne
Options
MaxSize
MaxSizeMinusOne
Definition at line 64 of file HessenbergDecomposition.h.
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition (Index size = Size==Dynamic ? 2 : Size) inline
Default constructor; the decomposition will be computed later.
Parameters
[in] size The size of the matrix whose Hessenberg decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See Also
compute() for an example.
Definition at line 100 of file HessenbergDecomposition.h.
template<typename _MatrixType> Eigen::HessenbergDecomposition< _MatrixType >::HessenbergDecomposition (const MatrixType & matrix) inline
Constructor; computes Hessenberg decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Hessenberg decomposition is to be computed.
This constructor calls compute() to compute the Hessenberg decomposition.
See Also
matrixH() for an example.
Definition at line 118 of file HessenbergDecomposition.h.
Member Function Documentation
template<typename MatrixType > void Eigen::HessenbergDecomposition< MatrixType >::_compute (MatrixType & matA, CoeffVectorType & hCoeffs, VectorType & temp) static private
Definition at line 292 of file HessenbergDecomposition.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::PlainObjectBase< Derived >::resize().
Referenced by Eigen::HessenbergDecomposition< MatrixType >::compute(), and Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition().
template<typename _MatrixType> HessenbergDecomposition& Eigen::HessenbergDecomposition< _MatrixType >::compute (const MatrixType & matrix) inline
Computes Hessenberg decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Hessenberg decomposition is to be computed.
Returns
Reference to *this
The Hessenberg decomposition is computed by bringing the columns of the matrix successively in the required form using Householder reflections (see, e.g., Algorithm 7.4.2 in Golub & Van Loan, Matrix Computations). The cost is flops, where denotes the size of the given matrix.
This method reuses of the allocated data in the HessenbergDecomposition object.
Example:
Output:
Definition at line 150 of file HessenbergDecomposition.h.
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
template<typename _MatrixType> const CoeffVectorType& Eigen::HessenbergDecomposition< _MatrixType >::householderCoefficients () const inline
Returns the Householder coefficients.
Returns
a const reference to the vector of Householder coefficients
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The Householder coefficients allow the reconstruction of the matrix in the Hessenberg decomposition from the packed data.
See Also
packedMatrix(), Householder module
Definition at line 177 of file HessenbergDecomposition.h.
template<typename _MatrixType> MatrixHReturnType Eigen::HessenbergDecomposition< _MatrixType >::matrixH () const inline
Constructs the Hessenberg matrix H in the decomposition.
Returns
expression object representing the matrix H
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The object returned by this function constructs the Hessenberg matrix H when it is assigned to a matrix or otherwise evaluated. The matrix H is constructed from the packed matrix as returned by packedMatrix(): The upper part (including the subdiagonal) of the packed matrix contains the matrix H. It may sometimes be better to directly use the packed matrix instead of constructing the matrix H.
Example:
Output:
See Also
matrixQ(), packedMatrix()
Definition at line 260 of file HessenbergDecomposition.h.
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
template<typename _MatrixType> HouseholderSequenceType Eigen::HessenbergDecomposition< _MatrixType >::matrixQ (void) const inline
Reconstructs the orthogonal matrix Q in the decomposition.
Returns
object representing the matrix Q
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
This function returns a light-weight object of template class HouseholderSequence. You can either apply it directly to a matrix or you can convert it to a matrix of type MatrixType.
See Also
matrixH() for an example, class HouseholderSequence
Definition at line 232 of file HessenbergDecomposition.h.
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
template<typename _MatrixType> const MatrixType& Eigen::HessenbergDecomposition< _MatrixType >::packedMatrix () const inline
Returns the internal representation of the decomposition.
Returns
a const reference to a matrix with the internal representation of the decomposition.
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The returned matrix contains the following information:
the upper part and lower sub-diagonal represent the Hessenberg matrix H
the rest of the lower part contains the Householder vectors that, combined with Householder coefficients returned by householderCoefficients(), allows to reconstruct the matrix Q as . Here, the matrices are the Householder transformations where is the th Householder coefficient and is the Householder vector defined by with M the matrix returned by this function.
See LAPACK for further details on this packed storage.
Example:
Output:
See Also
householderCoefficients()
Definition at line 212 of file HessenbergDecomposition.h.
Member Data Documentation
template<typename _MatrixType> CoeffVectorType Eigen::HessenbergDecomposition< _MatrixType >::m_hCoeffs protected
Definition at line 274 of file HessenbergDecomposition.h.
Referenced by Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< MatrixType >::householderCoefficients(), and Eigen::HessenbergDecomposition< MatrixType >::matrixQ().
template<typename _MatrixType> bool Eigen::HessenbergDecomposition< _MatrixType >::m_isInitialized protected
Definition at line 276 of file HessenbergDecomposition.h.
Referenced by Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< MatrixType >::householderCoefficients(), Eigen::HessenbergDecomposition< MatrixType >::matrixH(), Eigen::HessenbergDecomposition< MatrixType >::matrixQ(), and Eigen::HessenbergDecomposition< MatrixType >::packedMatrix().
template<typename _MatrixType> MatrixType Eigen::HessenbergDecomposition< _MatrixType >::m_matrix protected
Definition at line 273 of file HessenbergDecomposition.h.
Referenced by Eigen::HessenbergDecomposition< MatrixType >::compute(), Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< MatrixType >::matrixQ(), and Eigen::HessenbergDecomposition< MatrixType >::packedMatrix().
template<typename _MatrixType> VectorType Eigen::HessenbergDecomposition< _MatrixType >::m_temp protected
Definition at line 275 of file HessenbergDecomposition.h.
Referenced by Eigen::HessenbergDecomposition< MatrixType >::compute(), and Eigen::HessenbergDecomposition< MatrixType >::HessenbergDecomposition().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigenvalues/HessenbergDecomposition.h