LIA_RAL: PldaModel Class Reference
PldaModel Class Reference
#include <PldaTools.h>
Public Member Functions
PldaModel ()
Constructors.
PldaModel (String mode, Config &config)
void initTrain (PldaDev, Config &)
void initTest (Config &)
virtual ~PldaModel ()
virtual String getClassName () const
void initModel (Config &config)
void initF (Config &config)
void splitPerSpeaker (unsigned long nbThread, RealVector< unsigned long > &startIndex)
void initG (Config &config)
void updateMean ()
void centerData ()
void updateModel (Config &)
void em_iteration (Config &config, unsigned long it)
void getExpectedValues (Config &, unsigned long it)
void getExpectedValuesUnThreaded (Config &)
void saveModel (Config &config)
void mStep (unsigned long it, Config &config)
void loadF (String filename, Config &config)
void loadG (String filename, Config &config)
void loadNoise (String filename, Config &config)
void loadOriginalMean (String filename, Config &config)
void loadDelta (String filename, Config &config)
void preComputation ()
void save (String filename, Config &config)
void load (String filename, Config &config)
Eigen::MatrixXd getFtweight ()
Eigen::MatrixXd getFtweightG ()
Eigen::MatrixXd getInvGtweightGplusEye ()
Eigen::MatrixXd getGtweight ()
Eigen::MatrixXd getF ()
unsigned long getRankF ()
unsigned long getRankG ()
PldaDev & getDev ()
Private Attributes
PldaDev _Dev
unsigned long _rankF
unsigned long _rankG
unsigned long _vectSize
Eigen::VectorXd _originalMean
Eigen::MatrixXd _F
Eigen::MatrixXd _G
Eigen::MatrixXd _Sigma
Eigen::VectorXd _Delta
Eigen::MatrixXd _sigmaObs
Eigen::MatrixXd _invSigma
Eigen::MatrixXd _Ftweight
Eigen::MatrixXd _Gtweight
Eigen::MatrixXd _GtweightG
Eigen::MatrixXd _FtweightG
Eigen::MatrixXd _invGtweightGplusEye
Eigen::MatrixXd _EhhSum
Eigen::MatrixXd _xhSum
Eigen::MatrixXd _Umx
Detailed Description
This class contains a PLDA model
Author
Anthony Larcher alarc.nosp@m.her@.nosp@m.i2r.a.nosp@m.-sta.nosp@m.r.edu.nosp@m..sg
Version
1.0
Date
2012
Definition at line 386 of file PldaTools.h.
Constructor & Destructor Documentation
PldaModel::PldaModel ()
Constructors.
Definition at line 2009 of file PldaTools.cpp.
PldaModel::PldaModel (String mode, Config & config)
Definition at line 2028 of file PldaTools.cpp.
PldaModel::~PldaModel () virtual
Definition at line 2169 of file PldaTools.cpp.
Member Function Documentation
void PldaModel::centerData ()
Definition at line 2297 of file PldaTools.cpp.
Referenced by IvTest(), and PLDA().
void PldaModel::em_iteration (Config & config, unsigned long it)
Definition at line 2329 of file PldaTools.cpp.
References verboseLevel.
Referenced by IvTest(), and PLDA().
String PldaModel::getClassName () const virtual
Definition at line 2173 of file PldaTools.cpp.
PldaDev & PldaModel::getDev ()
Definition at line 3010 of file PldaTools.cpp.
Referenced by IvTest().
void PldaModel::getExpectedValues (Config & config, unsigned long it)
Definition at line 2346 of file PldaTools.cpp.
void PldaModel::getExpectedValuesUnThreaded (Config & config)
Definition at line 2359 of file PldaTools.cpp.
References Eigen::EigenSolver< _MatrixType >::eigenvalues(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), and verboseLevel.
Eigen::MatrixXd PldaModel::getF ()
Definition at line 2995 of file PldaTools.cpp.
Referenced by PldaTest::pldaMeanScoring(), and PldaTest::pldaNativeScoring().
Eigen::MatrixXd PldaModel::getFtweight ()
Definition at line 2975 of file PldaTools.cpp.
Referenced by PldaTest::pldaMeanScoring(), and PldaTest::pldaNativeScoring().
Eigen::MatrixXd PldaModel::getFtweightG ()
Definition at line 2980 of file PldaTools.cpp.
Referenced by PldaTest::pldaMeanScoring(), and PldaTest::pldaNativeScoring().
Eigen::MatrixXd PldaModel::getGtweight ()
Definition at line 2990 of file PldaTools.cpp.
Referenced by PldaTest::pldaMeanScoring(), and PldaTest::pldaNativeScoring().
Eigen::MatrixXd PldaModel::getInvGtweightGplusEye ()
Definition at line 2985 of file PldaTools.cpp.
Referenced by PldaTest::pldaMeanScoring(), and PldaTest::pldaNativeScoring().
unsigned long PldaModel::getRankF ()
Definition at line 3000 of file PldaTools.cpp.
Referenced by PldaTest::pldaMeanScoring(), and PldaTest::pldaNativeScoring().
unsigned long PldaModel::getRankG ()
Definition at line 3005 of file PldaTools.cpp.
void PldaModel::initF (Config & config)
random initialisation of the EigenVoices Matrix
Definition at line 2206 of file PldaTools.cpp.
References boxMullerGenerator(), boxMullerGeneratorInit(), and verboseLevel.
void PldaModel::initG (Config & config)
random initialisation of the EigenVoices Matrix
Definition at line 2247 of file PldaTools.cpp.
References boxMullerGenerator(), boxMullerGeneratorInit(), and verboseLevel.
void PldaModel::initModel (Config & config)
Definition at line 2176 of file PldaTools.cpp.
References verboseLevel.
void PldaModel::initTest (Config & config)
Definition at line 2124 of file PldaTools.cpp.
References verboseLevel.
void PldaModel::initTrain (PldaDev dev, Config & config)
Definition at line 2043 of file PldaTools.cpp.
References PldaDev::getVectSize(), and verbose.
void PldaModel::load (String filename, Config & config)
void PldaModel::loadDelta (String filename, Config & config)
Load Mean vector
Parameters
filename name of the file to load
config the configuration
Definition at line 2938 of file PldaTools.cpp.
void PldaModel::loadF (String filename, Config & config)
Load EigenVoice matrix
Parameters
filename name of the file to load
config the configuration
Definition at line 2876 of file PldaTools.cpp.
References verboseLevel.
void PldaModel::loadG (String filename, Config & config)
Load EigenChannel matrix
Parameters
filename name of the file to load
config the configuration
Definition at line 2892 of file PldaTools.cpp.
References verboseLevel.
void PldaModel::loadNoise (String filename, Config & config)
Load Noise matrix
Parameters
filename name of the file to load
config the configuration
Definition at line 2913 of file PldaTools.cpp.
void PldaModel::loadOriginalMean (String filename, Config & config)
Load Original mean vector
Parameters
filename name of the file to load
config the configuration
Definition at line 2926 of file PldaTools.cpp.
void PldaModel::mStep (unsigned long it, Config & config)
Definition at line 2790 of file PldaTools.cpp.
References verboseLevel.
void PldaModel::preComputation ()
Precomputation of temporary variables
Definition at line 2950 of file PldaTools.cpp.
Referenced by PldaTest::pldaMeanScoring(), and PldaTest::pldaNativeScoring().
void PldaModel::save (String filename, Config & config)
void PldaModel::saveModel (Config & config)
Definition at line 2816 of file PldaTools.cpp.
Referenced by IvTest(), and PLDA().
void PldaModel::splitPerSpeaker (unsigned long nbThread, RealVector< unsigned long > & startIndex)
void PldaModel::updateMean ()
Definition at line 2290 of file PldaTools.cpp.
Referenced by PLDA().
void PldaModel::updateModel (Config & config)
Definition at line 2302 of file PldaTools.cpp.
Referenced by IvTest().
Member Data Documentation
Eigen::VectorXd PldaModel::_Delta private
Definition at line 403 of file PldaTools.h.
PldaDev PldaModel::_Dev private
Definition at line 391 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_EhhSum private
Definition at line 416 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_F private
Definition at line 400 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_Ftweight private
Definition at line 408 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_FtweightG private
Definition at line 411 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_G private
Definition at line 401 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_Gtweight private
Definition at line 409 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_GtweightG private
Definition at line 410 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_invGtweightGplusEye private
Definition at line 412 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_invSigma private
Definition at line 407 of file PldaTools.h.
Eigen::VectorXd PldaModel::_originalMean private
Definition at line 399 of file PldaTools.h.
unsigned long PldaModel::_rankF private
Definition at line 394 of file PldaTools.h.
unsigned long PldaModel::_rankG private
Definition at line 395 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_Sigma private
Definition at line 402 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_sigmaObs private
Definition at line 406 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_Umx private
Definition at line 418 of file PldaTools.h.
unsigned long PldaModel::_vectSize private
Definition at line 396 of file PldaTools.h.
Eigen::MatrixXd PldaModel::_xhSum private
Definition at line 417 of file PldaTools.h.
The documentation for this class was generated from the following files:
LIA_SpkTools/include/PldaTools.h
LIA_SpkTools/src/PldaTools.cpp