LIA_RAL: Eigen::SimplicialLLT< _MatrixType, _UpLo > Class Template Reference
Eigen::SimplicialLLT< _MatrixType, _UpLo > Class Template Reference
A direct sparse LLT Cholesky factorizations.
#include <SimplicialCholesky.h>
Public Types
enum { UpLo = _UpLo }
typedef _MatrixType MatrixType
typedef SimplicialCholeskyBase
< SimplicialLLT > Base
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef SparseMatrix< Scalar,
ColMajor, Index > CholMatrixType
typedef Matrix< Scalar,
Dynamic, 1 > VectorType
typedef internal::traits
< SimplicialLLT > Traits
typedef Traits::MatrixL MatrixL
typedef Traits::MatrixU MatrixU
Public Types inherited from Eigen::SimplicialCholeskyBase< SimplicialLLT< _MatrixType, _UpLo > >
enum
typedef internal::traits
< SimplicialLLT< _MatrixType,
_UpLo > >::MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef SparseMatrix< Scalar,
ColMajor, Index > CholMatrixType
typedef Matrix< Scalar,
Dynamic, 1 > VectorType
Public Member Functions
SimplicialLLT ()
SimplicialLLT (const MatrixType &matrix)
const MatrixL matrixL () const
const MatrixU matrixU () const
SimplicialLLT & compute (const MatrixType &matrix)
void analyzePattern (const MatrixType &a)
void factorize (const MatrixType &a)
Scalar determinant () const
Public Member Functions inherited from Eigen::SimplicialCholeskyBase< SimplicialLLT< _MatrixType, _UpLo > >
SimplicialCholeskyBase ()
SimplicialCholeskyBase (const MatrixType &matrix)
~SimplicialCholeskyBase ()
SimplicialLLT< _MatrixType,
_UpLo > & derived ()
const SimplicialLLT
< _MatrixType, _UpLo > & derived () const
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
const internal::solve_retval
< SimplicialCholeskyBase, Rhs > solve (const MatrixBase< Rhs > &b) const
const
internal::sparse_solve_retval
< SimplicialCholeskyBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
const PermutationMatrix
< Dynamic, Dynamic, Index > & permutationP () const
const PermutationMatrix
< Dynamic, Dynamic, Index > & permutationPinv () const
SimplicialLLT< _MatrixType,
_UpLo > & setShift (const RealScalar &offset, const RealScalar &scale=1)
void dumpMemory (Stream &s)
void _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Additional Inherited Members
Protected Member Functions inherited from Eigen::SimplicialCholeskyBase< SimplicialLLT< _MatrixType, _UpLo > >
void compute (const MatrixType &matrix)
void factorize (const MatrixType &a)
void factorize_preordered (const CholMatrixType &a)
void analyzePattern (const MatrixType &a, bool doLDLT)
void analyzePattern_preordered (const CholMatrixType &a, bool doLDLT)
void ordering (const MatrixType &a, CholMatrixType &ap)
Protected Attributes inherited from Eigen::SimplicialCholeskyBase< SimplicialLLT< _MatrixType, _UpLo > >
ComputationInfo m_info
bool m_isInitialized
bool m_factorizationIsOk
bool m_analysisIsOk
CholMatrixType m_matrix
VectorType m_diag
VectorXi m_parent
VectorXi m_nonZerosPerCol
PermutationMatrix< Dynamic,
Dynamic, Index > m_P
PermutationMatrix< Dynamic,
Dynamic, Index > m_Pinv
RealScalar m_shiftOffset
RealScalar m_shiftScale
Detailed Description
template<typename _MatrixType, int _UpLo = Lower>
class Eigen::SimplicialLLT< _MatrixType, _UpLo >
A direct sparse LLT Cholesky factorizations.
This class provides a LL^T Cholesky factorizations of sparse matrices that are selfadjoint and positive definite. The factorization allows for solving A.X = B where X and B can be either dense or sparse.
In order to reduce the fill-in, a symmetric permutation P is applied prior to the factorization such that the factorized matrix is P A P^-1.
Template Parameters
_MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
_UpLo the triangular part that will be used for the computations. It can be Lower or Upper. Default is Lower.
See Also
class SimplicialLDLT
Definition at line 304 of file SimplicialCholesky.h.
Member Typedef Documentation
template<typename _MatrixType , int _UpLo = Lower> typedef SimplicialCholeskyBase<SimplicialLLT> Eigen::SimplicialLLT< _MatrixType, _UpLo >::Base
Definition at line 367 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef SparseMatrix<Scalar,ColMajor,Index> Eigen::SimplicialLLT< _MatrixType, _UpLo >::CholMatrixType
Definition at line 371 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef MatrixType::Index Eigen::SimplicialLLT< _MatrixType, _UpLo >::Index
Definition at line 370 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef Traits::MatrixL Eigen::SimplicialLLT< _MatrixType, _UpLo >::MatrixL
Definition at line 374 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef _MatrixType Eigen::SimplicialLLT< _MatrixType, _UpLo >::MatrixType
Definition at line 365 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef Traits::MatrixU Eigen::SimplicialLLT< _MatrixType, _UpLo >::MatrixU
Definition at line 375 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef MatrixType::RealScalar Eigen::SimplicialLLT< _MatrixType, _UpLo >::RealScalar
Definition at line 369 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef MatrixType::Scalar Eigen::SimplicialLLT< _MatrixType, _UpLo >::Scalar
Definition at line 368 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef internal::traits<SimplicialLLT> Eigen::SimplicialLLT< _MatrixType, _UpLo >::Traits
Definition at line 373 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef Matrix<Scalar,Dynamic,1> Eigen::SimplicialLLT< _MatrixType, _UpLo >::VectorType
Definition at line 372 of file SimplicialCholesky.h.
Member Enumeration Documentation
template<typename _MatrixType , int _UpLo = Lower> anonymous enum
Enumerator
UpLo
Definition at line 366 of file SimplicialCholesky.h.
Constructor & Destructor Documentation
template<typename _MatrixType , int _UpLo = Lower> Eigen::SimplicialLLT< _MatrixType, _UpLo >::SimplicialLLT () inline
Default constructor
Definition at line 378 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> Eigen::SimplicialLLT< _MatrixType, _UpLo >::SimplicialLLT (const MatrixType & matrix) inline
Constructs and performs the LLT factorization of matrix
Definition at line 380 of file SimplicialCholesky.h.
Member Function Documentation
template<typename _MatrixType , int _UpLo = Lower> void Eigen::SimplicialLLT< _MatrixType, _UpLo >::analyzePattern (const MatrixType & a) inline
Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See Also
factorize()
Definition at line 408 of file SimplicialCholesky.h.
References Eigen::SimplicialCholeskyBase< Derived >::analyzePattern().
template<typename _MatrixType , int _UpLo = Lower> SimplicialLLT& Eigen::SimplicialLLT< _MatrixType, _UpLo >::compute (const MatrixType & matrix) inline
Computes the sparse Cholesky decomposition of matrix
Definition at line 396 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> Scalar Eigen::SimplicialLLT< _MatrixType, _UpLo >::determinant () const inline
Returns
the determinant of the underlying matrix from the current factorization
Definition at line 425 of file SimplicialCholesky.h.
References abs2(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::diagonal(), and Eigen::SimplicialCholeskyBase< Derived >::m_matrix.
template<typename _MatrixType , int _UpLo = Lower> void Eigen::SimplicialLLT< _MatrixType, _UpLo >::factorize (const MatrixType & a) inline
Performs a numeric decomposition of matrix
The given matrix must has the same sparcity than the matrix on which the symbolic decomposition has been performed.
See Also
analyzePattern()
Definition at line 419 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> const MatrixL Eigen::SimplicialLLT< _MatrixType, _UpLo >::matrixL () const inline
Returns
an expression of the factor L
Definition at line 384 of file SimplicialCholesky.h.
References eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk, and Eigen::SimplicialCholeskyBase< Derived >::m_matrix.
template<typename _MatrixType , int _UpLo = Lower> const MatrixU Eigen::SimplicialLLT< _MatrixType, _UpLo >::matrixU () const inline
Returns
an expression of the factor U (= L^*)
Definition at line 390 of file SimplicialCholesky.h.
References eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk, and Eigen::SimplicialCholeskyBase< Derived >::m_matrix.
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCholesky/SimplicialCholesky.h