LIA_RAL: Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator Class Reference
Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator Class Reference
#include <SparseVector.h>
Public Member Functions
ReverseInnerIterator (const SparseVector &vec, Index outer=0)
ReverseInnerIterator (const internal::CompressedStorage< Scalar, Index > &data)
ReverseInnerIterator & operator-- ()
Scalar value () const
Scalar & valueRef ()
Index index () const
Index row () const
Index col () const
operator bool () const
Protected Attributes
const
internal::CompressedStorage
< Scalar, Index > & m_data
Index m_id
const Index m_start
Detailed Description
template<typename _Scalar, int _Flags = 0, typename _Index = int>
class Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator
Definition at line 365 of file SparseVector.h.
Constructor & Destructor Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::ReverseInnerIterator (const SparseVector & vec, Index outer = 0) inline
Definition at line 368 of file SparseVector.h.
References eigen_assert, and EIGEN_UNUSED_VARIABLE.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::ReverseInnerIterator (const internal::CompressedStorage< Scalar, Index > & data) inline
Definition at line 375 of file SparseVector.h.
Member Function Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::col () const inline
Definition at line 386 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::index () const inline
Definition at line 384 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::index(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::operator bool () const inline
Definition at line 388 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> ReverseInnerIterator& Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::operator-- () inline
Definition at line 379 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::row () const inline
Definition at line 385 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::value () const inline
Definition at line 381 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::valueRef () inline
Definition at line 382 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
Member Data Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> const internal::CompressedStorage<Scalar,Index>& Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::m_data protected
Definition at line 391 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::m_id protected
Definition at line 392 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> const Index Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::m_start protected
Definition at line 393 of file SparseVector.h.
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCore/SparseVector.h