LIA_RAL: TabHisto Class Reference
TabHisto Class Reference
#include <GeneralTools.h>
Public Member Functions
TabHisto (unsigned long nbBins, unsigned long maxTargetLine)
~TabHisto ()
unsigned long getSize ()
void accumulateValueInTab (const String &id, double score)
Histo & getHisto (const String &id)
void computeHistoInTab (const String &id)
String & getId (unsigned long n)
unsigned long getIndex (const String &id)
Histo & getHistoFromVect (unsigned long n)
Private Attributes
unsigned long _nb
ObjectRefVector _tabHisto
XLine _id
Detailed Description
Definition at line 97 of file GeneralTools.h.
Constructor & Destructor Documentation
TabHisto::TabHisto (unsigned long nbBins, unsigned long maxTargetLine) inline
Definition at line 102 of file GeneralTools.h.
TabHisto::~TabHisto () inline
Definition at line 103 of file GeneralTools.h.
Member Function Documentation
void TabHisto::accumulateValueInTab (const String & id, double score)
Definition at line 157 of file GeneralTools.cpp.
References _id, _nb, debug, and getHistoFromVect().
Referenced by ComputeTestHisto().
void TabHisto::computeHistoInTab (const String & id)
Definition at line 169 of file GeneralTools.cpp.
References getHisto().
Referenced by ComputeTestHisto().
Histo & TabHisto::getHisto (const String & id)
Definition at line 181 of file GeneralTools.cpp.
References _nb, getHistoFromVect(), and getIndex().
Referenced by computeHistoInTab(), and ComputeTestHisto().
Histo & TabHisto::getHistoFromVect (unsigned long n)
Definition at line 152 of file GeneralTools.cpp.
References _tabHisto.
Referenced by accumulateValueInTab(), and getHisto().
String & TabHisto::getId (unsigned long n)
Definition at line 177 of file GeneralTools.cpp.
References _id, and _nb.
unsigned long TabHisto::getIndex (const String & id)
Definition at line 172 of file GeneralTools.cpp.
References _id.
Referenced by getHisto().
unsigned long TabHisto::getSize () inline
Definition at line 104 of file GeneralTools.h.
Member Data Documentation
XLine TabHisto::_id private
Definition at line 100 of file GeneralTools.h.
Referenced by accumulateValueInTab(), getId(), and getIndex().
unsigned long TabHisto::_nb private
Definition at line 98 of file GeneralTools.h.
Referenced by accumulateValueInTab(), getHisto(), and getId().
ObjectRefVector TabHisto::_tabHisto private
Definition at line 99 of file GeneralTools.h.
Referenced by getHistoFromVect().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/GeneralTools.h
LIA_SpkTools/src/GeneralTools.cpp