LIA_RAL: Eigen::VectorwiseOp< ExpressionType, Direction > Class Template Reference
Eigen::VectorwiseOp< ExpressionType, Direction > Class Template Reference
Pseudo expression providing partial reduction operations.
#include <ForwardDeclarations.h>
Classes
struct ExtendedType
struct ReduxReturnType
struct ReturnType
Public Types
enum { IsVertical = (Direction==Vertical) ? 1 : 0, IsHorizontal = (Direction==Horizontal) ? 1 : 0 }
enum { HNormalized_Size, HNormalized_SizeMinusOne = HNormalized_Size==Dynamic ? Dynamic : HNormalized_Size-1 }
typedef ExpressionType::Scalar Scalar
typedef ExpressionType::RealScalar RealScalar
typedef ExpressionType::Index Index
typedef internal::conditional
< internal::must_nest_by_value
< ExpressionType >::ret,
ExpressionType, ExpressionType & >
::type ExpressionTypeNested
typedef internal::remove_all
< ExpressionTypeNested >::type ExpressionTypeNestedCleaned
typedef Replicate
< ExpressionType, Direction==Vertical?Dynamic:1,
Direction==Horizontal?Dynamic:1 > ReplicateReturnType
typedef ExpressionType::PlainObject CrossReturnType
typedef Block< const
ExpressionType, Direction==Vertical?int(HNormalized_SizeMinusOne):int(internal::traits
< ExpressionType >
::RowsAtCompileTime),
Direction==Horizontal?int(HNormalized_SizeMinusOne):int(internal::traits
< ExpressionType >
::ColsAtCompileTime)> HNormalized_Block
typedef Block< const
ExpressionType, Direction==Vertical?1:int(internal::traits
< ExpressionType >
::RowsAtCompileTime),
Direction==Horizontal?1:int(internal::traits
< ExpressionType >
::ColsAtCompileTime)> HNormalized_Factors
typedef CwiseBinaryOp
< internal::scalar_quotient_op
< typename internal::traits
< ExpressionType >::Scalar >
, const HNormalized_Block,
const Replicate
< HNormalized_Factors,
Direction==Vertical?HNormalized_SizeMinusOne:1,
Direction==Horizontal?HNormalized_SizeMinusOne:1 > > HNormalizedReturnType
Public Member Functions
VectorwiseOp (ExpressionType &matrix)
const ExpressionType & _expression () const
template<typename BinaryOp >
const ReduxReturnType
< BinaryOp >::Type redux (const BinaryOp &func=BinaryOp()) const
const ReturnType
< internal::member_minCoeff >
::Type minCoeff () const
const ReturnType
< internal::member_maxCoeff >
::Type maxCoeff () const
const ReturnType
< internal::member_squaredNorm,
RealScalar >::Type squaredNorm () const
const ReturnType
< internal::member_norm,
RealScalar >::Type norm () const
const ReturnType
< internal::member_blueNorm,
RealScalar >::Type blueNorm () const
const ReturnType
< internal::member_stableNorm,
RealScalar >::Type stableNorm () const
const ReturnType
< internal::member_hypotNorm,
RealScalar >::Type hypotNorm () const
const ReturnType
< internal::member_sum >::Type sum () const
const ReturnType
< internal::member_mean >
::Type mean () const
const ReturnType
< internal::member_all >::Type all () const
const ReturnType
< internal::member_any >::Type any () const
const PartialReduxExpr
< ExpressionType,
internal::member_count< Index >
, Direction > count () const
const ReturnType
< internal::member_prod >
::Type prod () const
const Reverse< ExpressionType,
Direction > reverse () const
const ReplicateReturnType replicate (Index factor) const
template<int Factor>
const Replicate
< ExpressionType,(IsVertical?Factor:1),(IsHorizontal?Factor:1)> replicate (Index factor=Factor) const
template<typename OtherDerived >
ExpressionType & operator= (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
ExpressionType & operator+= (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
ExpressionType & operator-= (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
ExpressionType & operator*= (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
ExpressionType & operator/= (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE
CwiseBinaryOp
< internal::scalar_sum_op
< Scalar >, const
ExpressionTypeNestedCleaned,
const typename ExtendedType
< OtherDerived >::Type > operator+ (const DenseBase< OtherDerived > &other) const
template<typename OtherDerived >
CwiseBinaryOp
< internal::scalar_difference_op
< Scalar >, const
ExpressionTypeNestedCleaned,
const typename ExtendedType
< OtherDerived >::Type > operator- (const DenseBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE
CwiseBinaryOp
< internal::scalar_product_op
< Scalar >, const
ExpressionTypeNestedCleaned,
const typename ExtendedType
< OtherDerived >::Type > operator* (const DenseBase< OtherDerived > &other) const
template<typename OtherDerived >
CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const
ExpressionTypeNestedCleaned,
const typename ExtendedType
< OtherDerived >::Type > operator/ (const DenseBase< OtherDerived > &other) const
template<typename OtherDerived >
const CrossReturnType cross (const MatrixBase< OtherDerived > &other) const
const HNormalizedReturnType hnormalized () const
template<typename OtherDerived >
const VectorwiseOp
< ExpressionType, Direction >
::CrossReturnType cross (const MatrixBase< OtherDerived > &other) const
Protected Types
typedef internal::conditional
< Direction==Vertical,
typename
ExpressionType::ColXpr,
typename
ExpressionType::RowXpr >::type SubVector
Protected Member Functions
SubVector subVector (Index i)
Index subVectors () const
template<typename OtherDerived >
ExtendedType< OtherDerived >::Type extendedTo (const DenseBase< OtherDerived > &other) const
Protected Attributes
ExpressionTypeNested m_matrix
Detailed Description
template<typename ExpressionType, int Direction>
class Eigen::VectorwiseOp< ExpressionType, Direction >
Pseudo expression providing partial reduction operations.
Parameters
ExpressionType the type of the object on which to do partial reductions
Direction indicates the direction of the redux (Vertical or Horizontal)
This class represents a pseudo expression with partial reduction features. It is the return type of DenseBase::colwise() and DenseBase::rowwise() and most of the time this is the only way it is used.
Example:
Output:
See Also
DenseBase::colwise(), DenseBase::rowwise(), class PartialReduxExpr
Definition at line 213 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename ExpressionType, int Direction> typedef ExpressionType::PlainObject Eigen::VectorwiseOp< ExpressionType, Direction >::CrossReturnType
Definition at line 514 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef internal::conditional<internal::must_nest_by_value<ExpressionType>::ret, ExpressionType, ExpressionType&>::type Eigen::VectorwiseOp< ExpressionType, Direction >::ExpressionTypeNested
Definition at line 173 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef internal::remove_all<ExpressionTypeNested>::type Eigen::VectorwiseOp< ExpressionType, Direction >::ExpressionTypeNestedCleaned
Definition at line 174 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef Block<const ExpressionType, Direction==Vertical ? int(HNormalized_SizeMinusOne) : int(internal::traits<ExpressionType>::RowsAtCompileTime), Direction==Horizontal ? int(HNormalized_SizeMinusOne) : int(internal::traits<ExpressionType>::ColsAtCompileTime)> Eigen::VectorwiseOp< ExpressionType, Direction >::HNormalized_Block
Definition at line 528 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef Block<const ExpressionType, Direction==Vertical ? 1 : int(internal::traits<ExpressionType>::RowsAtCompileTime), Direction==Horizontal ? 1 : int(internal::traits<ExpressionType>::ColsAtCompileTime)> Eigen::VectorwiseOp< ExpressionType, Direction >::HNormalized_Factors
Definition at line 532 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef CwiseBinaryOp<internal::scalar_quotient_op<typename internal::traits<ExpressionType>::Scalar>, const HNormalized_Block, const Replicate<HNormalized_Factors, Direction==Vertical ? HNormalized_SizeMinusOne : 1, Direction==Horizontal ? HNormalized_SizeMinusOne : 1> > Eigen::VectorwiseOp< ExpressionType, Direction >::HNormalizedReturnType
Definition at line 538 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef ExpressionType::Index Eigen::VectorwiseOp< ExpressionType, Direction >::Index
Definition at line 171 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef ExpressionType::RealScalar Eigen::VectorwiseOp< ExpressionType, Direction >::RealScalar
Definition at line 170 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef Replicate<ExpressionType,Direction==Vertical?Dynamic:1,Direction==Horizontal?Dynamic:1> Eigen::VectorwiseOp< ExpressionType, Direction >::ReplicateReturnType
Definition at line 385 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef ExpressionType::Scalar Eigen::VectorwiseOp< ExpressionType, Direction >::Scalar
Definition at line 169 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> typedef internal::conditional<Direction==Vertical, typename ExpressionType::ColXpr, typename ExpressionType::RowXpr>::type Eigen::VectorwiseOp< ExpressionType, Direction >::SubVector protected
Definition at line 204 of file VectorwiseOp.h.
Member Enumeration Documentation
template<typename ExpressionType, int Direction> anonymous enum
Enumerator
IsVertical
IsHorizontal
Definition at line 193 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> anonymous enum
Enumerator
HNormalized_Size
HNormalized_SizeMinusOne
Definition at line 518 of file VectorwiseOp.h.
Constructor & Destructor Documentation
template<typename ExpressionType, int Direction> Eigen::VectorwiseOp< ExpressionType, Direction >::VectorwiseOp (ExpressionType & matrix) inline
Definition at line 239 of file VectorwiseOp.h.
Member Function Documentation
template<typename ExpressionType, int Direction> const ExpressionType& Eigen::VectorwiseOp< ExpressionType, Direction >::_expression () const inline
Definition at line 242 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_all>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::all (void) const inline
Returns
a row (or column) vector expression representing whether all coefficients of each respective column (or row) are true.
See Also
DenseBase::all()
Definition at line 344 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_any>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::any (void) const inline
Returns
a row (or column) vector expression representing whether at least one coefficient of each respective column (or row) is true.
See Also
DenseBase::any()
Definition at line 351 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_blueNorm,RealScalar>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::blueNorm () const inline
Returns
a row (or column) vector expression of the norm of each column (or row) of the referenced expression, using blue's algorithm.
See Also
DenseBase::blueNorm()
Definition at line 302 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const PartialReduxExpr<ExpressionType, internal::member_count<Index>, Direction> Eigen::VectorwiseOp< ExpressionType, Direction >::count () const inline
Returns
a row (or column) vector expression representing the number of true coefficients of each respective column (or row).
Example:
Output:
See Also
DenseBase::count()
Definition at line 361 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> template<typename OtherDerived > const VectorwiseOp<ExpressionType,Direction>::CrossReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::cross (const MatrixBase< OtherDerived > & other) const
Returns
a matrix expression of the cross product of each column or row of the referenced expression with the other vector.
The referenced matrix must have one dimension equal to 3. The result matrix has the same dimensions than the referenced one.
See Also
MatrixBase::cross()
Definition at line 101 of file OrthoMethods.h.
References Eigen::DenseBase< Derived >::col(), conjugate(), eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, Eigen::DenseBase< Derived >::row(), and Eigen::Vertical.
template<typename ExpressionType, int Direction> template<typename OtherDerived > const CrossReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::cross (const MatrixBase< OtherDerived > & other) const
template<typename ExpressionType, int Direction> template<typename OtherDerived > ExtendedType<OtherDerived>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::extendedTo (const DenseBase< OtherDerived > & other) const inline protected
Definition at line 225 of file VectorwiseOp.h.
References EIGEN_IMPLIES, EIGEN_STATIC_ASSERT, Eigen::Horizontal, and Eigen::Vertical.
template<typename ExpressionType , int Direction> const VectorwiseOp< ExpressionType, Direction >::HNormalizedReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::hnormalized () const inline
Returns
an expression of the homogeneous normalized vector of *this
Example:
Output:
See Also
MatrixBase::hnormalized()
Definition at line 176 of file Homogeneous.h.
References Eigen::Horizontal, and Eigen::Vertical.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_hypotNorm,RealScalar>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::hypotNorm () const inline
Returns
a row (or column) vector expression of the norm of each column (or row) of the referenced expression, avoiding underflow and overflow using a concatenation of hypot() calls.
See Also
DenseBase::hypotNorm()
Definition at line 320 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_maxCoeff>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::maxCoeff () const inline
Returns
a row (or column) vector expression of the largest coefficient of each column (or row) of the referenced expression.
Example:
Output:
See Also
DenseBase::maxCoeff()
Definition at line 273 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_mean>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::mean () const inline
Returns
a row (or column) vector expression of the mean of each column (or row) of the referenced expression.
See Also
DenseBase::mean()
Definition at line 337 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_minCoeff>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::minCoeff () const inline
Returns
a row (or column) vector expression of the smallest coefficient of each column (or row) of the referenced expression.
Example:
Output:
See Also
DenseBase::minCoeff()
Definition at line 263 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_norm,RealScalar>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::norm () const inline
Returns
a row (or column) vector expression of the norm of each column (or row) of the referenced expression.
Example:
Output:
See Also
DenseBase::norm()
Definition at line 293 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> template<typename OtherDerived > EIGEN_STRONG_INLINE CwiseBinaryOp<internal::scalar_product_op<Scalar>, const ExpressionTypeNestedCleaned, const typename ExtendedType<OtherDerived>::Type> Eigen::VectorwiseOp< ExpressionType, Direction >::operator* (const DenseBase< OtherDerived > & other) const inline
Returns the expression where each subvector is the product of the vector other by the corresponding subvector of *this
Definition at line 486 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_ARRAYXPR, EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > ExpressionType& Eigen::VectorwiseOp< ExpressionType, Direction >::operator*= (const DenseBase< OtherDerived > & other) inline
Multiples each subvector of *this by the vector other
Definition at line 436 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_ARRAYXPR, EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > EIGEN_STRONG_INLINE CwiseBinaryOp<internal::scalar_sum_op<Scalar>, const ExpressionTypeNestedCleaned, const typename ExtendedType<OtherDerived>::Type> Eigen::VectorwiseOp< ExpressionType, Direction >::operator+ (const DenseBase< OtherDerived > & other) const inline
Returns the expression of the sum of the vector other to each subvector of *this
Definition at line 461 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > ExpressionType& Eigen::VectorwiseOp< ExpressionType, Direction >::operator+= (const DenseBase< OtherDerived > & other) inline
Adds the vector other to each subvector of *this
Definition at line 418 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > CwiseBinaryOp<internal::scalar_difference_op<Scalar>, const ExpressionTypeNestedCleaned, const typename ExtendedType<OtherDerived>::Type> Eigen::VectorwiseOp< ExpressionType, Direction >::operator- (const DenseBase< OtherDerived > & other) const inline
Returns the expression of the difference between each subvector of *this and the vector other
Definition at line 473 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > ExpressionType& Eigen::VectorwiseOp< ExpressionType, Direction >::operator-= (const DenseBase< OtherDerived > & other) inline
Substracts the vector other to each subvector of *this
Definition at line 427 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const ExpressionTypeNestedCleaned, const typename ExtendedType<OtherDerived>::Type> Eigen::VectorwiseOp< ExpressionType, Direction >::operator/ (const DenseBase< OtherDerived > & other) const inline
Returns the expression where each subvector is the quotient of the corresponding subvector of *this by the vector other
Definition at line 500 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_ARRAYXPR, EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > ExpressionType& Eigen::VectorwiseOp< ExpressionType, Direction >::operator/= (const DenseBase< OtherDerived > & other) inline
Divides each subvector of *this by the vector other
Definition at line 447 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_ARRAYXPR, EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> template<typename OtherDerived > ExpressionType& Eigen::VectorwiseOp< ExpressionType, Direction >::operator= (const DenseBase< OtherDerived > & other) inline
Copies the vector other to each subvector of *this
Definition at line 408 of file VectorwiseOp.h.
References EIGEN_STATIC_ASSERT_SAME_XPR_KIND, and EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_prod>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::prod () const inline
Returns
a row (or column) vector expression of the product of each column (or row) of the referenced expression.
Example:
Output:
See Also
DenseBase::prod()
Definition at line 371 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> template<typename BinaryOp > const ReduxReturnType<BinaryOp>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::redux (const BinaryOp & func = BinaryOp()) const inline
Returns
a row or column vector expression of *this reduxed by func
The template parameter BinaryOp is the type of the functor of the custom redux operator. Note that func must be an associative operator.
See Also
class VectorwiseOp, DenseBase::colwise(), DenseBase::rowwise()
Definition at line 253 of file VectorwiseOp.h.
template<typename ExpressionType , int Direction> const VectorwiseOp< ExpressionType, Direction >::ReplicateReturnType Eigen::VectorwiseOp< ExpressionType, Direction >::replicate (Index factor) const
Returns
an expression of the replication of each column (or row) of *this
Example:
Output:
See Also
VectorwiseOp::replicate(), DenseBase::replicate(), class Replicate
Definition at line 169 of file Replicate.h.
References Eigen::Horizontal, and Eigen::Vertical.
template<typename ExpressionType, int Direction> template<int Factor> const Replicate<ExpressionType,(IsVertical?Factor:1),(IsHorizontal?Factor:1)> Eigen::VectorwiseOp< ExpressionType, Direction >::replicate (Index factor = Factor) const inline
Returns
an expression of the replication of each column (or row) of *this
Example:
Output:
See Also
VectorwiseOp::replicate(Index), DenseBase::replicate(), class Replicate
Definition at line 398 of file VectorwiseOp.h.
References Eigen::Horizontal, and Eigen::Vertical.
template<typename ExpressionType, int Direction> const Reverse<ExpressionType, Direction> Eigen::VectorwiseOp< ExpressionType, Direction >::reverse () const inline
Returns
a matrix expression where each column (or row) are reversed.
Example:
Output:
See Also
DenseBase::reverse()
Definition at line 382 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_squaredNorm,RealScalar>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::squaredNorm () const inline
Returns
a row (or column) vector expression of the squared norm of each column (or row) of the referenced expression.
Example:
Output:
See Also
DenseBase::squaredNorm()
Definition at line 283 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_stableNorm,RealScalar>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::stableNorm () const inline
Returns
a row (or column) vector expression of the norm of each column (or row) of the referenced expression, avoiding underflow and overflow.
See Also
DenseBase::stableNorm()
Definition at line 311 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> SubVector Eigen::VectorwiseOp< ExpressionType, Direction >::subVector (Index i) inline protected
Definition at line 205 of file VectorwiseOp.h.
template<typename ExpressionType, int Direction> Index Eigen::VectorwiseOp< ExpressionType, Direction >::subVectors () const inline protected
Definition at line 212 of file VectorwiseOp.h.
References Eigen::Vertical.
template<typename ExpressionType, int Direction> const ReturnType<internal::member_sum>::Type Eigen::VectorwiseOp< ExpressionType, Direction >::sum () const inline
Returns
a row (or column) vector expression of the sum of each column (or row) of the referenced expression.
Example:
Output:
See Also
DenseBase::sum()
Definition at line 330 of file VectorwiseOp.h.
Member Data Documentation
template<typename ExpressionType, int Direction> ExpressionTypeNested Eigen::VectorwiseOp< ExpressionType, Direction >::m_matrix protected
Definition at line 543 of file VectorwiseOp.h.
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Core/VectorwiseOp.h
include/Eigen/src/Core/Replicate.h
include/Eigen/src/Geometry/Homogeneous.h
include/Eigen/src/Geometry/OrthoMethods.h