LIA_RAL: Eigen::LU< MatrixType > Class Template Reference
Eigen::LU< MatrixType > Class Template Reference
#include <LU.h>
Public Types
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename
MatrixType::Scalar >::Real RealScalar
typedef Matrix< int,
1, MatrixType::ColsAtCompileTime,
MatrixType::Options,
1, MatrixType::MaxColsAtCompileTime > IntRowVectorType
typedef Matrix< int,
MatrixType::RowsAtCompileTime,
1, MatrixType::Options,
MatrixType::MaxRowsAtCompileTime, 1 > IntColVectorType
typedef Matrix< Scalar,
1, MatrixType::ColsAtCompileTime,
MatrixType::Options,
1, MatrixType::MaxColsAtCompileTime > RowVectorType
typedef Matrix< Scalar,
MatrixType::RowsAtCompileTime,
1, MatrixType::Options,
MatrixType::MaxRowsAtCompileTime, 1 > ColVectorType
typedef Matrix< typename
MatrixType::Scalar,
MatrixType::ColsAtCompileTime,
Dynamic, MatrixType::Options,
MatrixType::MaxColsAtCompileTime,
MatrixType::MaxColsAtCompileTime > KernelResultType
typedef Matrix< typename
MatrixType::Scalar,
MatrixType::RowsAtCompileTime,
Dynamic, MatrixType::Options,
MatrixType::MaxRowsAtCompileTime,
MatrixType::MaxColsAtCompileTime > ImageResultType
typedef FullPivLU< MatrixType > Base
Public Types inherited from Eigen::FullPivLU< MatrixType >
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename
MatrixType::Scalar >::Real RealScalar
typedef internal::traits
< MatrixType >::StorageKind StorageKind
typedef MatrixType::Index Index
typedef
internal::plain_row_type
< MatrixType, Index >::type IntRowVectorType
typedef
internal::plain_col_type
< MatrixType, Index >::type IntColVectorType
typedef PermutationMatrix
< ColsAtCompileTime,
MaxColsAtCompileTime > PermutationQType
typedef PermutationMatrix
< RowsAtCompileTime,
MaxRowsAtCompileTime > PermutationPType
Public Member Functions
template<typename T >
LU (const T &t)
template<typename OtherDerived , typename ResultType >
bool solve (const MatrixBase< OtherDerived > &b, ResultType *result) const
template<typename ResultType >
void computeInverse (ResultType *result) const
template<typename KernelMatrixType >
void computeKernel (KernelMatrixType *result) const
template<typename ImageMatrixType >
void computeImage (ImageMatrixType *result) const
const ImageResultType image () const
Public Member Functions inherited from Eigen::FullPivLU< MatrixType >
FullPivLU ()
Default Constructor.
FullPivLU (Index rows, Index cols)
Default Constructor with memory preallocation.
FullPivLU (const MatrixType &matrix)
FullPivLU & compute (const MatrixType &matrix)
const MatrixType & matrixLU () const
Index nonzeroPivots () const
RealScalar maxPivot () const
const PermutationPType & permutationP () const
const PermutationQType & permutationQ () const
const internal::kernel_retval
< FullPivLU > kernel () const
const internal::image_retval
< FullPivLU > image (const MatrixType &originalMatrix) const
template<typename Rhs >
const internal::solve_retval
< FullPivLU, Rhs > solve (const MatrixBase< Rhs > &b) const
internal::traits< MatrixType >
::Scalar determinant () const
FullPivLU & setThreshold (const RealScalar &threshold)
FullPivLU & setThreshold (Default_t)
RealScalar threshold () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const internal::solve_retval
< FullPivLU, typename
MatrixType::IdentityReturnType > inverse () const
MatrixType reconstructedMatrix () const
Index rows () const
Index cols () const
Public Attributes
const MatrixType & m_originalMatrix
Additional Inherited Members
Protected Attributes inherited from Eigen::FullPivLU< MatrixType >
MatrixType m_lu
PermutationPType m_p
PermutationQType m_q
IntColVectorType m_rowsTranspositions
IntRowVectorType m_colsTranspositions
Index m_det_pq
Index m_nonzero_pivots
RealScalar m_maxpivot
RealScalar m_prescribedThreshold
bool m_isInitialized
bool m_usePrescribedThreshold
Detailed Description
template<typename MatrixType>
class Eigen::LU< MatrixType >
Definition at line 16 of file LU.h.
Member Typedef Documentation
template<typename MatrixType> typedef FullPivLU<MatrixType> Eigen::LU< MatrixType >::Base
Definition at line 46 of file LU.h.
template<typename MatrixType> typedef Matrix<Scalar, MatrixType::RowsAtCompileTime, 1, MatrixType::Options, MatrixType::MaxRowsAtCompileTime, 1> Eigen::LU< MatrixType >::ColVectorType
Definition at line 25 of file LU.h.
template<typename MatrixType> typedef Matrix<typename MatrixType::Scalar, MatrixType::RowsAtCompileTime, Dynamic, MatrixType::Options, MatrixType::MaxRowsAtCompileTime, MatrixType::MaxColsAtCompileTime > Eigen::LU< MatrixType >::ImageResultType
Definition at line 44 of file LU.h.
template<typename MatrixType> typedef Matrix<int, MatrixType::RowsAtCompileTime, 1, MatrixType::Options, MatrixType::MaxRowsAtCompileTime, 1> Eigen::LU< MatrixType >::IntColVectorType
Definition at line 23 of file LU.h.
template<typename MatrixType> typedef Matrix<int, 1, MatrixType::ColsAtCompileTime, MatrixType::Options, 1, MatrixType::MaxColsAtCompileTime> Eigen::LU< MatrixType >::IntRowVectorType
Definition at line 22 of file LU.h.
template<typename MatrixType> typedef Matrix<typename MatrixType::Scalar, MatrixType::ColsAtCompileTime, Dynamic, MatrixType::Options, MatrixType::MaxColsAtCompileTime, MatrixType::MaxColsAtCompileTime > Eigen::LU< MatrixType >::KernelResultType
Definition at line 35 of file LU.h.
template<typename MatrixType> typedef NumTraits<typename MatrixType::Scalar>::Real Eigen::LU< MatrixType >::RealScalar
Definition at line 21 of file LU.h.
template<typename MatrixType> typedef Matrix<Scalar, 1, MatrixType::ColsAtCompileTime, MatrixType::Options, 1, MatrixType::MaxColsAtCompileTime> Eigen::LU< MatrixType >::RowVectorType
Definition at line 24 of file LU.h.
template<typename MatrixType> typedef MatrixType::Scalar Eigen::LU< MatrixType >::Scalar
Definition at line 20 of file LU.h.
Constructor & Destructor Documentation
template<typename MatrixType> template<typename T > Eigen::LU< MatrixType >::LU (const T & t) inline explicit
Definition at line 49 of file LU.h.
Member Function Documentation
template<typename MatrixType> template<typename ImageMatrixType > void Eigen::LU< MatrixType >::computeImage (ImageMatrixType * result) const inline
Definition at line 71 of file LU.h.
References Eigen::LU< MatrixType >::image(), and Eigen::LU< MatrixType >::m_originalMatrix.
template<typename MatrixType> template<typename ResultType > void Eigen::LU< MatrixType >::computeInverse (ResultType * result) const inline
Definition at line 59 of file LU.h.
References Eigen::FullPivLU< MatrixType >::cols(), Eigen::FullPivLU< MatrixType >::rows(), and Eigen::LU< MatrixType >::solve().
template<typename MatrixType> template<typename KernelMatrixType > void Eigen::LU< MatrixType >::computeKernel (KernelMatrixType * result) const inline
Definition at line 65 of file LU.h.
References Eigen::FullPivLU< MatrixType >::kernel().
template<typename MatrixType> const ImageResultType Eigen::LU< MatrixType >::image () const inline
Definition at line 76 of file LU.h.
References Eigen::LU< MatrixType >::m_originalMatrix.
Referenced by Eigen::LU< MatrixType >::computeImage().
template<typename MatrixType> template<typename OtherDerived , typename ResultType > bool Eigen::LU< MatrixType >::solve (const MatrixBase< OtherDerived > & b, ResultType * result) const inline
Definition at line 52 of file LU.h.
Referenced by Eigen::LU< MatrixType >::computeInverse().
Member Data Documentation
template<typename MatrixType> const MatrixType& Eigen::LU< MatrixType >::m_originalMatrix
Definition at line 81 of file LU.h.
Referenced by Eigen::LU< MatrixType >::computeImage(), and Eigen::LU< MatrixType >::image().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigen2Support/LU.h