LIA_RAL: Norm Class Reference
Norm Class Reference
Public Member Functions
bool findEntityInNorm (String, unsigned long &)
double getMean (unsigned long)
double getStd (unsigned long)
unsigned long getNb (unsigned long)
void print ()
unsigned long addSeg (String, double, double)
unsigned long findAddSeg (String, Config &)
void addScore (unsigned long, double, const String &)
void deleteAllDistribNorm ()
void setNormAndFreeDistrib ()
Norm (unsigned long)
Norm (unsigned long, char, double, double)
~Norm ()
String getClassName () const
Public Attributes
String idTest
double mu
double sigma
Private Member Functions
unsigned long findEntityIdxInNorm (String)
void moveEntity (unsigned long, unsigned long)
Private Attributes
NormSeg * normTab
unsigned long nbNorm
unsigned long nbNormMax
unsigned long idxLastFind
char _computeMode
double _percentH
double _percentL
Detailed Description
Definition at line 279 of file ComputeNorm.cpp.
Constructor & Destructor Documentation
Norm::Norm (unsigned long nbMax)
Definition at line 413 of file ComputeNorm.cpp.
Norm::Norm (unsigned long nbMax, char compute, double percentH, double percentL)
Definition at line 421 of file ComputeNorm.cpp.
Norm::~Norm ()
Definition at line 430 of file ComputeNorm.cpp.
Member Function Documentation
void Norm::addScore (unsigned long idx, double score, const String & imp)
Definition at line 317 of file ComputeNorm.cpp.
Referenced by getAllScores(), and getAllScoresFirstNormed().
unsigned long Norm::addSeg (String name, double mean, double std)
Definition at line 400 of file ComputeNorm.cpp.
References debug.
void Norm::deleteAllDistribNorm ()
Definition at line 321 of file ComputeNorm.cpp.
unsigned long Norm::findAddSeg (String name, Config & config)
Definition at line 384 of file ComputeNorm.cpp.
References debug.
Referenced by getAllScores(), and getAllScoresFirstNormed().
unsigned long Norm::findEntityIdxInNorm (String name) private
Definition at line 335 of file ComputeNorm.cpp.
bool Norm::findEntityInNorm (String name, unsigned long & idx)
Definition at line 350 of file ComputeNorm.cpp.
Referenced by ComputeNorm(), and getAllScoresFirstNormed().
String Norm::getClassName () const inline
Definition at line 1201 of file UnsupervisedTools.cpp.
double Norm::getMean (unsigned long ind)
Definition at line 372 of file ComputeNorm.cpp.
Referenced by ComputeNorm(), and getAllScoresFirstNormed().
unsigned long Norm::getNb (unsigned long ind)
Definition at line 380 of file ComputeNorm.cpp.
double Norm::getStd (unsigned long ind)
Definition at line 376 of file ComputeNorm.cpp.
Referenced by ComputeNorm(), and getAllScoresFirstNormed().
void Norm::moveEntity (unsigned long beg, unsigned long end) private
Definition at line 327 of file ComputeNorm.cpp.
References debug, and verboseLevel.
void Norm::print ()
Definition at line 365 of file ComputeNorm.cpp.
Referenced by ComputeNorm().
void Norm::setNormAndFreeDistrib ()
Definition at line 310 of file ComputeNorm.cpp.
Referenced by ComputeNorm().
Member Data Documentation
char Norm::_computeMode private
Definition at line 286 of file ComputeNorm.cpp.
double Norm::_percentH private
Definition at line 289 of file ComputeNorm.cpp.
double Norm::_percentL private
Definition at line 290 of file ComputeNorm.cpp.
String Norm::idTest
Definition at line 1198 of file UnsupervisedTools.cpp.
Referenced by computeAndStoreZnormParam(), and loadTnormParam().
unsigned long Norm::idxLastFind private
Definition at line 285 of file ComputeNorm.cpp.
double Norm::mu
Definition at line 1199 of file UnsupervisedTools.cpp.
Referenced by computeAndStoreZnormParam(), and loadTnormParam().
unsigned long Norm::nbNorm private
Definition at line 281 of file ComputeNorm.cpp.
unsigned long Norm::nbNormMax private
Definition at line 282 of file ComputeNorm.cpp.
NormSeg* Norm::normTab private
Definition at line 280 of file ComputeNorm.cpp.
double Norm::sigma
Definition at line 1200 of file UnsupervisedTools.cpp.
Referenced by computeAndStoreZnormParam(), and loadTnormParam().
The documentation for this class was generated from the following files:
LIA_SpkDet/ComputeNorm/src/ComputeNorm.cpp
LIA_SpkTools/src/UnsupervisedTools.cpp