LIA_RAL: TVTranslate Class Reference
TVTranslate Class Reference
#include <AccumulateTVStat.h>
Public Member Functions
TVTranslate ()
TVTranslate (XList &fileList)
~TVTranslate ()
ULongVector & locIndices (const String &file)
Return indices of speakers for a file.
ULongVector & sessIndices (const String &file)
Return indices of sessions for a file.
unsigned long locNb (const String &file)
unsigned long firstSession (unsigned long spk)
unsigned long numSession (unsigned long spk, unsigned long session)
unsigned long locNb (unsigned long idx)
unsigned long sessionNb (const String &file)
Private Member Functions
long _idxOfID (const String &file)
Private Attributes
XLine _id
ULongVector _locidx
ULongVector _sessionidx
RefVector< ULongVector > _locindices
RefVector< ULongVector > _sessindices
Detailed Description
This class represents an index of speakers and sessions A Transate contains the indexes of speakers and sessions
Author
Anthony Larcher alarc.nosp@m.her@.nosp@m.i2r.a.nosp@m.-sta.nosp@m.r.edu.nosp@m..sg
Version
1.0
Date
2012
Definition at line 78 of file AccumulateTVStat.h.
Constructor & Destructor Documentation
TVTranslate::TVTranslate () inline
Definition at line 95 of file AccumulateTVStat.h.
TVTranslate::TVTranslate (XList & fileList) inline
Fill structure with id and idxs
Definition at line 99 of file AccumulateTVStat.h.
TVTranslate::~TVTranslate () inline
Definition at line 126 of file AccumulateTVStat.h.
Member Function Documentation
long TVTranslate::_idxOfID (const String & file) inline private
Definition at line 86 of file AccumulateTVStat.h.
unsigned long TVTranslate::firstSession (unsigned long spk) inline
Return the idx of the first session of a speaker
Parameters
spk idx of the targeted speaker
Returns
the idx of the first session of a speaker spk
Definition at line 156 of file AccumulateTVStat.h.
ULongVector& TVTranslate::locIndices (const String & file) inline
Return indices of speakers for a file.
Definition at line 129 of file AccumulateTVStat.h.
Referenced by TVAcc::computeAndAccumulateTVStatUnThreaded().
unsigned long TVTranslate::locNb (const String & file) inline
Return the idx of speakers
Parameters
file name of the feature file
Returns
the idx of the given speaker
Definition at line 146 of file AccumulateTVStat.h.
Referenced by TVAcc::computeAndAccumulateTVStat(), TVAcc::computeAndAccumulateTVStatUnThreaded(), and TVAcc::getTW().
unsigned long TVTranslate::locNb (unsigned long idx) inline
Return the idx of speakers
Parameters
index of the feature file
Returns
the idx of the given speaker
Definition at line 178 of file AccumulateTVStat.h.
unsigned long TVTranslate::numSession (unsigned long spk, unsigned long session) inline
Return the idx of a given session of a speaker
Parameters
spk idx of the speaker
session number of the session for the given speaker
Returns
the idx of the session session of the speaker spk
Definition at line 167 of file AccumulateTVStat.h.
ULongVector& TVTranslate::sessIndices (const String & file) inline
Return indices of sessions for a file.
Definition at line 136 of file AccumulateTVStat.h.
Referenced by TVAcc::computeAndAccumulateTVStatUnThreaded().
unsigned long TVTranslate::sessionNb (const String & file) inline
Return the idx of a sessions
Parameters
file feature file
Returns
the idx of the session corresponding to the file
Definition at line 186 of file AccumulateTVStat.h.
Referenced by TVAcc::computeAndAccumulateTVStat(), and TVAcc::computeAndAccumulateTVStatUnThreaded().
Member Data Documentation
XLine TVTranslate::_id private
Definition at line 79 of file AccumulateTVStat.h.
ULongVector TVTranslate::_locidx private
Definition at line 80 of file AccumulateTVStat.h.
RefVector<ULongVector> TVTranslate::_locindices private
Definition at line 82 of file AccumulateTVStat.h.
RefVector<ULongVector> TVTranslate::_sessindices private
Definition at line 83 of file AccumulateTVStat.h.
ULongVector TVTranslate::_sessionidx private
Definition at line 81 of file AccumulateTVStat.h.
The documentation for this class was generated from the following file:
LIA_SpkTools/include/AccumulateTVStat.h