LIA_RAL: Cache Class Reference
Cache Class Reference
Classes
struct head_t
Public Member Functions
Cache (int l, long int size)
~Cache ()
int get_data (const int index, Qfloat **data, int len)
void swap_index (int i, int j)
Private Member Functions
void lru_delete (head_t *h)
void lru_insert (head_t *h)
Private Attributes
int l
long int size
head_t * head
head_t lru_head
Detailed Description
Definition at line 67 of file libsvm.cpp.
Constructor & Destructor Documentation
Cache::Cache (int l, long int size)
Definition at line 94 of file libsvm.cpp.
References head, l, lru_head, max(), Cache::head_t::next, Cache::head_t::prev, and size.
Cache::~Cache ()
Definition at line 103 of file libsvm.cpp.
References head, lru_head, and Cache::head_t::next.
Member Function Documentation
int Cache::get_data (const int index, Qfloat ** data, int len)
Definition at line 126 of file libsvm.cpp.
References Cache::head_t::data, head, Cache::head_t::len, lru_delete(), lru_head, lru_insert(), Cache::head_t::next, size, and swap().
Referenced by SVC_Q::get_Q(), ONE_CLASS_Q::get_Q(), and SVR_Q::get_Q().
void Cache::lru_delete (head_t * h) private
Definition at line 110 of file libsvm.cpp.
References Cache::head_t::next, and Cache::head_t::prev.
Referenced by get_data(), and swap_index().
void Cache::lru_insert (head_t * h) private
Definition at line 117 of file libsvm.cpp.
References lru_head, Cache::head_t::next, and Cache::head_t::prev.
Referenced by get_data(), and swap_index().
void Cache::swap_index (int i, int j)
Definition at line 156 of file libsvm.cpp.
References head, lru_delete(), lru_head, lru_insert(), Cache::head_t::next, size, and swap().
Referenced by SVC_Q::swap_index(), and ONE_CLASS_Q::swap_index().
Member Data Documentation
head_t* Cache::head private
Definition at line 88 of file libsvm.cpp.
Referenced by Cache(), get_data(), swap_index(), and ~Cache().
int Cache::l private
Definition at line 79 of file libsvm.cpp.
Referenced by Cache().
head_t Cache::lru_head private
Definition at line 89 of file libsvm.cpp.
Referenced by Cache(), get_data(), lru_insert(), swap_index(), and ~Cache().
long int Cache::size private
Definition at line 80 of file libsvm.cpp.
Referenced by Cache(), get_data(), and swap_index().
The documentation for this class was generated from the following file:
LIA_Utils/Svm/src/libsvm.cpp