LIA_RAL: Eigen::aligned_allocator< T > Class Template Reference
Eigen::aligned_allocator< T > Class Template Reference
STL compatible allocator to use with with 16 byte aligned types.
#include <Memory.h>
Classes
struct rebind
Public Types
typedef size_t size_type
typedef std::ptrdiff_t difference_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef T value_type
Public Member Functions
pointer address (reference value) const
const_pointer address (const_reference value) const
aligned_allocator ()
aligned_allocator (const aligned_allocator &)
template<class U >
aligned_allocator (const aligned_allocator< U > &)
~aligned_allocator ()
size_type max_size () const
pointer allocate (size_type num, const void *hint=0)
void construct (pointer p, const T &value)
void destroy (pointer p)
void deallocate (pointer p, size_type)
bool operator!= (const aligned_allocator< T > &) const
bool operator== (const aligned_allocator< T > &) const
Detailed Description
template<class T>
class Eigen::aligned_allocator< T >
STL compatible allocator to use with with 16 byte aligned types.
Example:
// Matrix4f requires 16 bytes alignment:
std::map< int, Matrix4f, std::less<int>,
          aligned_allocator<std::pair<const int, Matrix4f> > > my_map_mat4;
// Vector3f does not require 16 bytes alignment, no need to use Eigen's allocator:
std::map< int, Vector3f > my_map_vec3;
See Also
TopicStlContainers.
Definition at line 647 of file Memory.h.
Member Typedef Documentation
template<class T > typedef const T* Eigen::aligned_allocator< T >::const_pointer
Definition at line 653 of file Memory.h.
template<class T > typedef const T& Eigen::aligned_allocator< T >::const_reference
Definition at line 655 of file Memory.h.
template<class T > typedef std::ptrdiff_t Eigen::aligned_allocator< T >::difference_type
Definition at line 651 of file Memory.h.
template<class T > typedef T* Eigen::aligned_allocator< T >::pointer
Definition at line 652 of file Memory.h.
template<class T > typedef T& Eigen::aligned_allocator< T >::reference
Definition at line 654 of file Memory.h.
template<class T > typedef size_t Eigen::aligned_allocator< T >::size_type
Definition at line 650 of file Memory.h.
template<class T > typedef T Eigen::aligned_allocator< T >::value_type
Definition at line 656 of file Memory.h.
Constructor & Destructor Documentation
template<class T > Eigen::aligned_allocator< T >::aligned_allocator () inline
Definition at line 674 of file Memory.h.
template<class T > Eigen::aligned_allocator< T >::aligned_allocator (const aligned_allocator< T > &) inline
Definition at line 678 of file Memory.h.
template<class T > template<class U > Eigen::aligned_allocator< T >::aligned_allocator (const aligned_allocator< U > &) inline
Definition at line 683 of file Memory.h.
template<class T > Eigen::aligned_allocator< T >::~aligned_allocator () inline
Definition at line 687 of file Memory.h.
Member Function Documentation
template<class T > pointer Eigen::aligned_allocator< T >::address (reference value) const inline
Definition at line 664 of file Memory.h.
template<class T > const_pointer Eigen::aligned_allocator< T >::address (const_reference value) const inline
Definition at line 669 of file Memory.h.
template<class T > pointer Eigen::aligned_allocator< T >::allocate (size_type num, const void * hint = 0) inline
Definition at line 696 of file Memory.h.
References Eigen::internal::aligned_malloc(), and EIGEN_UNUSED_VARIABLE.
template<class T > void Eigen::aligned_allocator< T >::construct (pointer p, const T & value) inline
Definition at line 703 of file Memory.h.
template<class T > void Eigen::aligned_allocator< T >::deallocate (pointer p, size_type) inline
Definition at line 722 of file Memory.h.
References Eigen::internal::aligned_free().
template<class T > void Eigen::aligned_allocator< T >::destroy (pointer p) inline
Definition at line 717 of file Memory.h.
template<class T > size_type Eigen::aligned_allocator< T >::max_size () const inline
Definition at line 691 of file Memory.h.
References max().
template<class T > bool Eigen::aligned_allocator< T >::operator!= (const aligned_allocator< T > &) const inline
Definition at line 727 of file Memory.h.
template<class T > bool Eigen::aligned_allocator< T >::operator== (const aligned_allocator< T > &) const inline
Definition at line 730 of file Memory.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/util/Memory.h