LIA_RAL: Eigen::FullPivHouseholderQR< MatrixType > Class Template Reference
Eigen::FullPivHouseholderQR< MatrixType > Class Template Reference
Householder rank-revealing QR decomposition of a matrix with full pivoting.
#include <ForwardDeclarations.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef
internal::FullPivHouseholderQRMatrixQReturnType
< MatrixType > MatrixQReturnType
typedef
internal::plain_diag_type
< MatrixType >::type HCoeffsType
typedef Matrix< Index,
1, ColsAtCompileTime, RowMajor,
1, MaxColsAtCompileTime > IntRowVectorType
typedef PermutationMatrix
< ColsAtCompileTime,
MaxColsAtCompileTime > PermutationType
typedef
internal::plain_col_type
< MatrixType, Index >::type IntColVectorType
typedef
internal::plain_row_type
< MatrixType >::type RowVectorType
typedef
internal::plain_col_type
< MatrixType >::type ColVectorType
Public Member Functions
FullPivHouseholderQR ()
Default Constructor.
FullPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
FullPivHouseholderQR (const MatrixType &matrix)
template<typename Rhs >
const internal::solve_retval
< FullPivHouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
MatrixQReturnType matrixQ (void) const
const MatrixType & matrixQR () const
FullPivHouseholderQR & compute (const MatrixType &matrix)
const PermutationType & colsPermutation () const
const IntColVectorType & rowsTranspositions () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const internal::solve_retval
< FullPivHouseholderQR,
typename
MatrixType::IdentityReturnType > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
FullPivHouseholderQR & setThreshold (const RealScalar &threshold)
FullPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
IntColVectorType m_rows_transpositions
IntRowVectorType m_cols_transpositions
PermutationType m_cols_permutation
RowVectorType m_temp
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
RealScalar m_precision
Index m_det_pq
Detailed Description
template<typename MatrixType>
class Eigen::FullPivHouseholderQR< MatrixType >
Householder rank-revealing QR decomposition of a matrix with full pivoting.
Parameters
MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, Q and R such that
by using Householder transformations. Here, P is a permutation matrix, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs a very prudent full pivoting in order to be rank-revealing and achieve optimal numerical stability. The trade-off is that it is slower than HouseholderQR and ColPivHouseholderQR.
See Also
MatrixBase::fullPivHouseholderQr()
Definition at line 224 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename MatrixType> typedef internal::plain_col_type<MatrixType>::type Eigen::FullPivHouseholderQR< MatrixType >::ColVectorType
Definition at line 70 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::FullPivHouseholderQR< MatrixType >::HCoeffsType
Definition at line 65 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef MatrixType::Index Eigen::FullPivHouseholderQR< MatrixType >::Index
Definition at line 63 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef internal::plain_col_type<MatrixType, Index>::type Eigen::FullPivHouseholderQR< MatrixType >::IntColVectorType
Definition at line 68 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef Matrix<Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime> Eigen::FullPivHouseholderQR< MatrixType >::IntRowVectorType
Definition at line 66 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef internal::FullPivHouseholderQRMatrixQReturnType<MatrixType> Eigen::FullPivHouseholderQR< MatrixType >::MatrixQReturnType
Definition at line 64 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef _MatrixType Eigen::FullPivHouseholderQR< MatrixType >::MatrixType
Definition at line 53 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::FullPivHouseholderQR< MatrixType >::PermutationType
Definition at line 67 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::RealScalar
Definition at line 62 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::FullPivHouseholderQR< MatrixType >::RowVectorType
Definition at line 69 of file FullPivHouseholderQR.h.
template<typename MatrixType> typedef MatrixType::Scalar Eigen::FullPivHouseholderQR< MatrixType >::Scalar
Definition at line 61 of file FullPivHouseholderQR.h.
Member Enumeration Documentation
template<typename MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 54 of file FullPivHouseholderQR.h.
Constructor & Destructor Documentation
template<typename MatrixType> Eigen::FullPivHouseholderQR< MatrixType >::FullPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via FullPivHouseholderQR::compute(const MatrixType&).
Definition at line 77 of file FullPivHouseholderQR.h.
template<typename MatrixType> Eigen::FullPivHouseholderQR< MatrixType >::FullPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See Also
FullPivHouseholderQR()
Definition at line 93 of file FullPivHouseholderQR.h.
template<typename MatrixType> Eigen::FullPivHouseholderQR< MatrixType >::FullPivHouseholderQR (const MatrixType & matrix) inline
Definition at line 103 of file FullPivHouseholderQR.h.
Member Function Documentation
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See Also
logAbsDeterminant(), MatrixBase::determinant()
Definition at line 363 of file FullPivHouseholderQR.h.
References abs(), and eigen_assert.
template<typename MatrixType> Index Eigen::FullPivHouseholderQR< MatrixType >::cols (void) const inline
Definition at line 276 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel(), and Eigen::FullPivHouseholderQR< _MatrixType >::isInjective().
template<typename MatrixType> const PermutationType& Eigen::FullPivHouseholderQR< MatrixType >::colsPermutation () const inline
Definition at line 155 of file FullPivHouseholderQR.h.
template<typename MatrixType> FullPivHouseholderQR< MatrixType > & Eigen::FullPivHouseholderQR< MatrixType >::compute (const MatrixType & matrix)
Definition at line 379 of file FullPivHouseholderQR.h.
References abs(), Eigen::internal::isMuchSmallerThan(), min(), and Eigen::FullPivHouseholderQR< MatrixType >::rows().
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::FullPivHouseholderQR().
template<typename MatrixType> Index Eigen::FullPivHouseholderQR< MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 218 of file FullPivHouseholderQR.h.
template<typename MatrixType> const HCoeffsType& Eigen::FullPivHouseholderQR< MatrixType >::hCoeffs () const inline
Definition at line 277 of file FullPivHouseholderQR.h.
template<typename MatrixType> const internal::solve_retval<FullPivHouseholderQR, typename MatrixType::IdentityReturnType> Eigen::FullPivHouseholderQR< MatrixType >::inverse (void) const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
Definition at line 268 of file FullPivHouseholderQR.h.
template<typename MatrixType> bool Eigen::FullPivHouseholderQR< MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 231 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible().
template<typename MatrixType> bool Eigen::FullPivHouseholderQR< MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 256 of file FullPivHouseholderQR.h.
template<typename MatrixType> bool Eigen::FullPivHouseholderQR< MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 244 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible().
template<typename MatrixType > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See Also
absDeterminant(), MatrixBase::determinant()
Definition at line 371 of file FullPivHouseholderQR.h.
References eigen_assert.
template<typename MatrixType > FullPivHouseholderQR< MatrixType >::MatrixQReturnType Eigen::FullPivHouseholderQR< MatrixType >::matrixQ (void) const inline
Returns
Expression object representing the matrix Q
Definition at line 575 of file FullPivHouseholderQR.h.
References eigen_assert.
template<typename MatrixType> const MatrixType& Eigen::FullPivHouseholderQR< MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
Definition at line 147 of file FullPivHouseholderQR.h.
template<typename MatrixType> RealScalar Eigen::FullPivHouseholderQR< MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
Definition at line 346 of file FullPivHouseholderQR.h.
template<typename MatrixType> Index Eigen::FullPivHouseholderQR< MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See Also
rank()
Definition at line 337 of file FullPivHouseholderQR.h.
template<typename MatrixType> Index Eigen::FullPivHouseholderQR< MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 202 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::FullPivHouseholderQR< _MatrixType >::isInjective(), and Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective().
template<typename MatrixType> Index Eigen::FullPivHouseholderQR< MatrixType >::rows (void) const inline
Definition at line 275 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< MatrixType >::compute(), and Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective().
template<typename MatrixType> const IntColVectorType& Eigen::FullPivHouseholderQR< MatrixType >::rowsTranspositions () const inline
Definition at line 161 of file FullPivHouseholderQR.h.
template<typename MatrixType> FullPivHouseholderQR& Eigen::FullPivHouseholderQR< MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
Definition at line 296 of file FullPivHouseholderQR.h.
template<typename MatrixType> FullPivHouseholderQR& Eigen::FullPivHouseholderQR< MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
Definition at line 311 of file FullPivHouseholderQR.h.
template<typename MatrixType> template<typename Rhs > const internal::solve_retval<FullPivHouseholderQR, Rhs> Eigen::FullPivHouseholderQR< MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition, if any exists.
Parameters
b the right-hand-side of the equation to solve.
Returns
a solution.
Note
The case where b is a matrix is not yet implemented. Also, this code is space inefficient.
Example:
Output:
Definition at line 135 of file FullPivHouseholderQR.h.
template<typename MatrixType> RealScalar Eigen::FullPivHouseholderQR< MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
Definition at line 321 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::rank(), and Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold().
Member Data Documentation
template<typename MatrixType> PermutationType Eigen::FullPivHouseholderQR< MatrixType >::m_cols_permutation protected
Definition at line 353 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::colsPermutation().
template<typename MatrixType> IntRowVectorType Eigen::FullPivHouseholderQR< MatrixType >::m_cols_transpositions protected
Definition at line 352 of file FullPivHouseholderQR.h.
template<typename MatrixType> Index Eigen::FullPivHouseholderQR< MatrixType >::m_det_pq protected
Definition at line 359 of file FullPivHouseholderQR.h.
template<typename MatrixType> HCoeffsType Eigen::FullPivHouseholderQR< MatrixType >::m_hCoeffs protected
Definition at line 350 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::hCoeffs().
template<typename MatrixType> bool Eigen::FullPivHouseholderQR< MatrixType >::m_isInitialized protected
Definition at line 355 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::colsPermutation(), Eigen::FullPivHouseholderQR< _MatrixType >::dimensionOfKernel(), Eigen::FullPivHouseholderQR< _MatrixType >::inverse(), Eigen::FullPivHouseholderQR< _MatrixType >::isInjective(), Eigen::FullPivHouseholderQR< _MatrixType >::isInvertible(), Eigen::FullPivHouseholderQR< _MatrixType >::isSurjective(), Eigen::FullPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::FullPivHouseholderQR< _MatrixType >::nonzeroPivots(), Eigen::FullPivHouseholderQR< _MatrixType >::rank(), Eigen::FullPivHouseholderQR< _MatrixType >::rowsTranspositions(), Eigen::FullPivHouseholderQR< _MatrixType >::solve(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
template<typename MatrixType> RealScalar Eigen::FullPivHouseholderQR< MatrixType >::m_maxpivot protected
Definition at line 356 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::maxPivot(), and Eigen::FullPivHouseholderQR< _MatrixType >::rank().
template<typename MatrixType> Index Eigen::FullPivHouseholderQR< MatrixType >::m_nonzero_pivots protected
Definition at line 357 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::nonzeroPivots(), and Eigen::FullPivHouseholderQR< _MatrixType >::rank().
template<typename MatrixType> RealScalar Eigen::FullPivHouseholderQR< MatrixType >::m_precision protected
Definition at line 358 of file FullPivHouseholderQR.h.
template<typename MatrixType> RealScalar Eigen::FullPivHouseholderQR< MatrixType >::m_prescribedThreshold protected
Definition at line 356 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
template<typename MatrixType> MatrixType Eigen::FullPivHouseholderQR< MatrixType >::m_qr protected
Definition at line 349 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::cols(), Eigen::FullPivHouseholderQR< _MatrixType >::inverse(), Eigen::FullPivHouseholderQR< _MatrixType >::matrixQR(), Eigen::FullPivHouseholderQR< _MatrixType >::rank(), Eigen::FullPivHouseholderQR< _MatrixType >::rows(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
template<typename MatrixType> IntColVectorType Eigen::FullPivHouseholderQR< MatrixType >::m_rows_transpositions protected
Definition at line 351 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::rowsTranspositions().
template<typename MatrixType> RowVectorType Eigen::FullPivHouseholderQR< MatrixType >::m_temp protected
Definition at line 354 of file FullPivHouseholderQR.h.
template<typename MatrixType> bool Eigen::FullPivHouseholderQR< MatrixType >::m_usePrescribedThreshold protected
Definition at line 355 of file FullPivHouseholderQR.h.
Referenced by Eigen::FullPivHouseholderQR< _MatrixType >::setThreshold(), and Eigen::FullPivHouseholderQR< _MatrixType >::threshold().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/QR/FullPivHouseholderQR.h