LIA_RAL: Eigen::internal::CompressedStorage< _Scalar, _Index > Class Template Reference
Eigen::internal::CompressedStorage< _Scalar, _Index > Class Template Reference
#include <CompressedStorage.h>
Public Types
typedef _Scalar Scalar
typedef _Index Index
Public Member Functions
CompressedStorage ()
CompressedStorage (size_t size)
CompressedStorage (const CompressedStorage &other)
CompressedStorage & operator= (const CompressedStorage &other)
void swap (CompressedStorage &other)
~CompressedStorage ()
void reserve (size_t size)
void squeeze ()
void resize (size_t size, float reserveSizeFactor=0)
void append (const Scalar &v, Index i)
size_t size () const
size_t allocatedSize () const
void clear ()
Scalar & value (size_t i)
const Scalar & value (size_t i) const
Index & index (size_t i)
const Index & index (size_t i) const
Index searchLowerIndex (Index key) const
Index searchLowerIndex (size_t start, size_t end, Index key) const
Scalar at (Index key, Scalar defaultValue=Scalar(0)) const
Scalar atInRange (size_t start, size_t end, Index key, Scalar defaultValue=Scalar(0)) const
Scalar & atWithInsertion (Index key, Scalar defaultValue=Scalar(0))
void prune (Scalar reference, RealScalar epsilon=NumTraits< RealScalar >::dummy_precision())
Static Public Member Functions
static CompressedStorage Map (Index *indices, Scalar *values, size_t size)
Protected Types
typedef NumTraits< Scalar >::Real RealScalar
Protected Member Functions
void reallocate (size_t size)
Protected Attributes
Scalar * m_values
Index * m_indices
size_t m_size
size_t m_allocatedSize
Detailed Description
template<typename _Scalar, typename _Index>
class Eigen::internal::CompressedStorage< _Scalar, _Index >
Definition at line 22 of file CompressedStorage.h.
Member Typedef Documentation
template<typename _Scalar, typename _Index> typedef _Index Eigen::internal::CompressedStorage< _Scalar, _Index >::Index
Definition at line 27 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> typedef NumTraits<Scalar>::Real Eigen::internal::CompressedStorage< _Scalar, _Index >::RealScalar protected
Definition at line 31 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> typedef _Scalar Eigen::internal::CompressedStorage< _Scalar, _Index >::Scalar
Definition at line 26 of file CompressedStorage.h.
Constructor & Destructor Documentation
template<typename _Scalar, typename _Index> Eigen::internal::CompressedStorage< _Scalar, _Index >::CompressedStorage () inline
Definition at line 35 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> Eigen::internal::CompressedStorage< _Scalar, _Index >::CompressedStorage (size_t size) inline
Definition at line 39 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> Eigen::internal::CompressedStorage< _Scalar, _Index >::CompressedStorage (const CompressedStorage< _Scalar, _Index > & other) inline
Definition at line 45 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> Eigen::internal::CompressedStorage< _Scalar, _Index >::~CompressedStorage () inline
Definition at line 67 of file CompressedStorage.h.
Member Function Documentation
template<typename _Scalar, typename _Index> size_t Eigen::internal::CompressedStorage< _Scalar, _Index >::allocatedSize () const inline
Definition at line 102 of file CompressedStorage.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed().
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::append (const Scalar & v, Index i) inline
Definition at line 93 of file CompressedStorage.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::fill(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBack(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInner(), and Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInnerUnordered().
template<typename _Scalar, typename _Index> Scalar Eigen::internal::CompressedStorage< _Scalar, _Index >::at (Index key, Scalar defaultValue = Scalar(0)) const inline
Returns
the stored value at index key If the value does not exist, then the value defaultValue is returned without any insertion.
Definition at line 142 of file CompressedStorage.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::coeff().
template<typename _Scalar, typename _Index> Scalar Eigen::internal::CompressedStorage< _Scalar, _Index >::atInRange (size_t start, size_t end, Index key, Scalar defaultValue = Scalar(0)) const inline
Like at(), but the search is performed in the range [start,end)
Definition at line 155 of file CompressedStorage.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::coeff().
template<typename _Scalar, typename _Index> Scalar& Eigen::internal::CompressedStorage< _Scalar, _Index >::atWithInsertion (Index key, Scalar defaultValue = Scalar(0)) inline
Returns
a reference to the value at index key If the value does not exist, then the value defaultValue is inserted such that the keys are sorted.
Definition at line 170 of file CompressedStorage.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::coeffRef().
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::clear () inline
Definition at line 103 of file CompressedStorage.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::resize(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), Eigen::SparseVector< _Scalar, _Flags, _Index >::setZero(), and Eigen::SparseMatrix< Scalar, RowMajor >::setZero().
template<typename _Scalar, typename _Index> Index& Eigen::internal::CompressedStorage< _Scalar, _Index >::index (size_t i) inline
Definition at line 108 of file CompressedStorage.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::coeffRef(), Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::index(), Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::index(), Eigen::SparseVector< _Scalar, _Flags, _Index >::innerIndexPtr(), Eigen::SparseMatrix< Scalar, RowMajor >::innerIndexPtr(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insert(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::internal::CompressedStorage< Scalar, Index >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::prune(), and Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors().
template<typename _Scalar, typename _Index> const Index& Eigen::internal::CompressedStorage< _Scalar, _Index >::index (size_t i) const inline
Definition at line 109 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> static CompressedStorage Eigen::internal::CompressedStorage< _Scalar, _Index >::Map (Index * indices, Scalar * values, size_t size) inline static
Definition at line 111 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> CompressedStorage& Eigen::internal::CompressedStorage< _Scalar, _Index >::operator= (const CompressedStorage< _Scalar, _Index > & other) inline
Definition at line 51 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::prune (Scalar reference, RealScalar epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Definition at line 187 of file CompressedStorage.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::prune().
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::reallocate (size_t size) inline protected
Definition at line 205 of file CompressedStorage.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::reserve(), Eigen::internal::CompressedStorage< Scalar, Index >::resize(), and Eigen::internal::CompressedStorage< Scalar, Index >::squeeze().
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::reserve (size_t size) inline
Definition at line 73 of file CompressedStorage.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseVector< _Scalar, _Flags, _Index >::reserve(), Eigen::SparseMatrix< Scalar, RowMajor >::reserve(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::startFill().
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::resize (size_t size, float reserveSizeFactor = 0) inline
Definition at line 86 of file CompressedStorage.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::append(), Eigen::internal::CompressedStorage< Scalar, Index >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, Index >::CompressedStorage(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insert(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::internal::CompressedStorage< Scalar, Index >::operator=(), Eigen::internal::CompressedStorage< Scalar, Index >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::SparseVector< _Scalar, _Flags, _Index >::resizeNonZeros(), and Eigen::SparseMatrix< Scalar, RowMajor >::resizeNonZeros().
template<typename _Scalar, typename _Index> Index Eigen::internal::CompressedStorage< _Scalar, _Index >::searchLowerIndex (Index key) const inline
Returns
the largest k such that for all j in [0,k) index[j]<key
Definition at line 121 of file CompressedStorage.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::at(), Eigen::internal::CompressedStorage< Scalar, Index >::atInRange(), Eigen::internal::CompressedStorage< Scalar, Index >::atWithInsertion(), Eigen::SparseMatrix< Scalar, RowMajor >::coeffRef(), and Eigen::internal::CompressedStorage< Scalar, Index >::searchLowerIndex().
template<typename _Scalar, typename _Index> Index Eigen::internal::CompressedStorage< _Scalar, _Index >::searchLowerIndex (size_t start, size_t end, Index key) const inline
Returns
the largest k in [start,end) such that for all j in [start,k) index[j]<key
Definition at line 127 of file CompressedStorage.h.
template<typename _Scalar, typename _Index> size_t Eigen::internal::CompressedStorage< _Scalar, _Index >::size () const inline
Definition at line 101 of file CompressedStorage.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::fill(), Eigen::SparseMatrix< Scalar, RowMajor >::finalize(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insert(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBack(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::internal::CompressedStorage< Scalar, Index >::Map(), Eigen::SparseVector< _Scalar, _Flags, _Index >::nonZeros(), Eigen::SparseMatrix< Scalar, RowMajor >::nonZeros(), Eigen::internal::CompressedStorage< Scalar, Index >::operator=(), Eigen::internal::CompressedStorage< Scalar, Index >::prune(), Eigen::internal::CompressedStorage< Scalar, Index >::reallocate(), Eigen::internal::CompressedStorage< Scalar, Index >::reserve(), Eigen::internal::CompressedStorage< Scalar, Index >::resize(), and Eigen::SparseMatrix< Scalar, RowMajor >::startVec().
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::squeeze () inline
Definition at line 80 of file CompressedStorage.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed().
template<typename _Scalar, typename _Index> void Eigen::internal::CompressedStorage< _Scalar, _Index >::swap (CompressedStorage< _Scalar, _Index > & other) inline
Definition at line 59 of file CompressedStorage.h.
Referenced by Eigen::SparseVector< _Scalar, _Flags, _Index >::swap(), and Eigen::SparseMatrix< Scalar, RowMajor >::swap().
template<typename _Scalar, typename _Index> Scalar& Eigen::internal::CompressedStorage< _Scalar, _Index >::value (size_t i) inline
Definition at line 105 of file CompressedStorage.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::coeffRef(), Eigen::SparseVector< _Scalar, _Flags, _Index >::fill(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insert(), Eigen::SparseVector< _Scalar, _Flags, _Index >::insertBack(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::internal::CompressedStorage< Scalar, Index >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::value(), Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::value(), Eigen::SparseVector< _Scalar, _Flags, _Index >::valuePtr(), Eigen::SparseMatrix< Scalar, RowMajor >::valuePtr(), Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::valueRef(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::ReverseInnerIterator::valueRef().
template<typename _Scalar, typename _Index> const Scalar& Eigen::internal::CompressedStorage< _Scalar, _Index >::value (size_t i) const inline
Definition at line 106 of file CompressedStorage.h.
Member Data Documentation
template<typename _Scalar, typename _Index> size_t Eigen::internal::CompressedStorage< _Scalar, _Index >::m_allocatedSize protected
Definition at line 225 of file CompressedStorage.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::allocatedSize(), Eigen::internal::CompressedStorage< Scalar, Index >::Map(), Eigen::internal::CompressedStorage< Scalar, Index >::reallocate(), Eigen::internal::CompressedStorage< Scalar, Index >::reserve(), Eigen::internal::CompressedStorage< Scalar, Index >::resize(), Eigen::internal::CompressedStorage< Scalar, Index >::squeeze(), and Eigen::internal::CompressedStorage< Scalar, Index >::swap().
template<typename _Scalar, typename _Index> Index* Eigen::internal::CompressedStorage< _Scalar, _Index >::m_indices protected
Definition at line 223 of file CompressedStorage.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::append(), Eigen::internal::CompressedStorage< Scalar, Index >::at(), Eigen::internal::CompressedStorage< Scalar, Index >::atInRange(), Eigen::internal::CompressedStorage< Scalar, Index >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, Index >::index(), Eigen::internal::CompressedStorage< Scalar, Index >::Map(), Eigen::internal::CompressedStorage< Scalar, Index >::operator=(), Eigen::internal::CompressedStorage< Scalar, Index >::reallocate(), Eigen::internal::CompressedStorage< Scalar, Index >::searchLowerIndex(), Eigen::internal::CompressedStorage< Scalar, Index >::swap(), and Eigen::internal::CompressedStorage< Scalar, Index >::~CompressedStorage().
template<typename _Scalar, typename _Index> size_t Eigen::internal::CompressedStorage< _Scalar, _Index >::m_size protected
Definition at line 224 of file CompressedStorage.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::append(), Eigen::internal::CompressedStorage< Scalar, Index >::at(), Eigen::internal::CompressedStorage< Scalar, Index >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, Index >::clear(), Eigen::internal::CompressedStorage< Scalar, Index >::Map(), Eigen::internal::CompressedStorage< Scalar, Index >::operator=(), Eigen::internal::CompressedStorage< Scalar, Index >::reallocate(), Eigen::internal::CompressedStorage< Scalar, Index >::reserve(), Eigen::internal::CompressedStorage< Scalar, Index >::resize(), Eigen::internal::CompressedStorage< Scalar, Index >::searchLowerIndex(), Eigen::internal::CompressedStorage< Scalar, Index >::size(), Eigen::internal::CompressedStorage< Scalar, Index >::squeeze(), and Eigen::internal::CompressedStorage< Scalar, Index >::swap().
template<typename _Scalar, typename _Index> Scalar* Eigen::internal::CompressedStorage< _Scalar, _Index >::m_values protected
Definition at line 222 of file CompressedStorage.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::append(), Eigen::internal::CompressedStorage< Scalar, Index >::at(), Eigen::internal::CompressedStorage< Scalar, Index >::atInRange(), Eigen::internal::CompressedStorage< Scalar, Index >::atWithInsertion(), Eigen::internal::CompressedStorage< Scalar, Index >::Map(), Eigen::internal::CompressedStorage< Scalar, Index >::operator=(), Eigen::internal::CompressedStorage< Scalar, Index >::reallocate(), Eigen::internal::CompressedStorage< Scalar, Index >::swap(), Eigen::internal::CompressedStorage< Scalar, Index >::value(), and Eigen::internal::CompressedStorage< Scalar, Index >::~CompressedStorage().
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCore/CompressedStorage.h