LIA_RAL: Eigen::internal::BandMatrixBase< Derived > Class Template Reference
Eigen::internal::BandMatrixBase< Derived > Class Template Reference
#include <BandMatrix.h>
Classes
struct DiagonalIntReturnType
Public Types
enum {
Flags = internal::traits<Derived>::Flags, CoeffReadCost = internal::traits<Derived>::CoeffReadCost, RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime, MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime, Supers = internal::traits<Derived>::Supers, Subs = internal::traits<Derived>::Subs,
Options = internal::traits<Derived>::Options
}
typedef internal::traits
< Derived >::Scalar Scalar
typedef Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType::Index Index
typedef internal::traits
< Derived >::CoefficientsType CoefficientsType
typedef EigenBase< Derived > Base
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
Index supers () const
Index subs () const
const CoefficientsType & coeffs () const
CoefficientsType & coeffs ()
Block< CoefficientsType,
Dynamic, 1 > col (Index i)
Block< CoefficientsType,
1, SizeAtCompileTime > diagonal ()
const Block< const
CoefficientsType,
1, SizeAtCompileTime > diagonal () const
template<int N>
DiagonalIntReturnType< N >::Type diagonal ()
template<int N>
const DiagonalIntReturnType< N >
::Type diagonal () const
Block< CoefficientsType,
1, Dynamic > diagonal (Index i)
const Block< const
CoefficientsType, 1, Dynamic > diagonal (Index i) const
template<typename Dest >
void evalTo (Dest &dst) const
DenseMatrixType toDenseMatrix () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Protected Types
enum { DataRowsAtCompileTime, SizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime) }
Protected Member Functions
Index diagonalLength (Index i) const
Detailed Description
template<typename Derived>
class Eigen::internal::BandMatrixBase< Derived >
Definition at line 18 of file BandMatrix.h.
Member Typedef Documentation
template<typename Derived> typedef EigenBase<Derived> Eigen::internal::BandMatrixBase< Derived >::Base
Definition at line 37 of file BandMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::CoefficientsType Eigen::internal::BandMatrixBase< Derived >::CoefficientsType
Definition at line 36 of file BandMatrix.h.
template<typename Derived> typedef Matrix<Scalar,RowsAtCompileTime,ColsAtCompileTime> Eigen::internal::BandMatrixBase< Derived >::DenseMatrixType
Definition at line 34 of file BandMatrix.h.
template<typename Derived> typedef DenseMatrixType::Index Eigen::internal::BandMatrixBase< Derived >::Index
Definition at line 35 of file BandMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::internal::BandMatrixBase< Derived >::Scalar
Definition at line 33 of file BandMatrix.h.
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
Flags
CoeffReadCost
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Supers
Subs
Options
Definition at line 22 of file BandMatrix.h.
template<typename Derived> anonymous enum protected
Enumerator
DataRowsAtCompileTime
SizeAtCompileTime
Definition at line 40 of file BandMatrix.h.
Member Function Documentation
template<typename Derived> const CoefficientsType& Eigen::internal::BandMatrixBase< Derived >::coeffs () const inline
Returns
an expression of the underlying coefficient matrix
Definition at line 60 of file BandMatrix.h.
Referenced by Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::col(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal().
template<typename Derived> CoefficientsType& Eigen::internal::BandMatrixBase< Derived >::coeffs () inline
Returns
an expression of the underlying coefficient matrix
Definition at line 63 of file BandMatrix.h.
template<typename Derived> Block<CoefficientsType,Dynamic,1> Eigen::internal::BandMatrixBase< Derived >::col (Index i) inline
Returns
a vector expression of the i -th column, only the meaningful part is returned.
Warning
the internal storage must be column major.
Definition at line 68 of file BandMatrix.h.
template<typename Derived> Block<CoefficientsType,1,SizeAtCompileTime> Eigen::internal::BandMatrixBase< Derived >::diagonal () inline
Returns
a vector expression of the main diagonal
Definition at line 84 of file BandMatrix.h.
Referenced by Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo(), and Eigen::internal::TridiagonalMatrix< Scalar, Size, Options >::sub().
template<typename Derived> const Block<const CoefficientsType,1,SizeAtCompileTime> Eigen::internal::BandMatrixBase< Derived >::diagonal () const inline
Returns
a vector expression of the main diagonal (const version)
Definition at line 88 of file BandMatrix.h.
template<typename Derived> template<int N> DiagonalIntReturnType<N>::Type Eigen::internal::BandMatrixBase< Derived >::diagonal () inline
Returns
a vector expression of the N -th sub or super diagonal
Definition at line 109 of file BandMatrix.h.
template<typename Derived> template<int N> const DiagonalIntReturnType<N>::Type Eigen::internal::BandMatrixBase< Derived >::diagonal () const inline
Returns
a vector expression of the N -th sub or super diagonal
Definition at line 115 of file BandMatrix.h.
template<typename Derived> Block<CoefficientsType,1,Dynamic> Eigen::internal::BandMatrixBase< Derived >::diagonal (Index i) inline
Returns
a vector expression of the i -th sub or super diagonal
Definition at line 121 of file BandMatrix.h.
template<typename Derived> const Block<const CoefficientsType,1,Dynamic> Eigen::internal::BandMatrixBase< Derived >::diagonal (Index i) const inline
Returns
a vector expression of the i -th sub or super diagonal
Definition at line 128 of file BandMatrix.h.
template<typename Derived> Index Eigen::internal::BandMatrixBase< Derived >::diagonalLength (Index i) const inline protected
Definition at line 154 of file BandMatrix.h.
Referenced by Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal().
template<typename Derived> template<typename Dest > void Eigen::internal::BandMatrixBase< Derived >::evalTo (Dest & dst) const inline
Definition at line 134 of file BandMatrix.h.
Referenced by Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::toDenseMatrix().
template<typename Derived> Index Eigen::internal::BandMatrixBase< Derived >::subs () const inline
Returns
the number of sub diagonals
Definition at line 57 of file BandMatrix.h.
Referenced by Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::col(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo().
template<typename Derived> Index Eigen::internal::BandMatrixBase< Derived >::supers () const inline
Returns
the number of super diagonals
Definition at line 54 of file BandMatrix.h.
Referenced by Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::col(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo().
template<typename Derived> DenseMatrixType Eigen::internal::BandMatrixBase< Derived >::toDenseMatrix () const inline
Definition at line 145 of file BandMatrix.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/BandMatrix.h