LIA_RAL: Eigen::ParametrizedLine< _Scalar, _AmbientDim > Class Template Reference
Eigen::ParametrizedLine< _Scalar, _AmbientDim > Class Template Reference
Geometry_Module
A parametrized line.
#include <ParametrizedLine.h>
Public Types
enum { AmbientDimAtCompileTime = _AmbientDim }
enum { AmbientDimAtCompileTime = _AmbientDim, Options = _Options }
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< Scalar,
AmbientDimAtCompileTime, 1 > VectorType
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseIndex Index
typedef Matrix< Scalar,
AmbientDimAtCompileTime,
1, Options > VectorType
Public Member Functions
ParametrizedLine ()
ParametrizedLine (int _dim)
ParametrizedLine (const VectorType &origin, const VectorType &direction)
ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim > &hyperplane)
~ParametrizedLine ()
int dim () const
const VectorType & origin () const
VectorType & origin ()
const VectorType & direction () const
VectorType & direction ()
RealScalar squaredDistance (const VectorType &p) const
RealScalar distance (const VectorType &p) const
VectorType projection (const VectorType &p) const
Scalar intersection (const Hyperplane< _Scalar, _AmbientDim > &hyperplane)
template<typename NewScalarType >
internal::cast_return_type
< ParametrizedLine,
ParametrizedLine
< NewScalarType,
AmbientDimAtCompileTime >
>::type cast () const
template<typename OtherScalarType >
ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime > &other)
bool isApprox (const ParametrizedLine &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
ParametrizedLine ()
template<int OtherOptions>
ParametrizedLine (const ParametrizedLine< Scalar, AmbientDimAtCompileTime, OtherOptions > &other)
ParametrizedLine (Index _dim)
ParametrizedLine (const VectorType &origin, const VectorType &direction)
template<int OtherOptions>
ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane)
~ParametrizedLine ()
Index dim () const
const VectorType & origin () const
VectorType & origin ()
const VectorType & direction () const
VectorType & direction ()
RealScalar squaredDistance (const VectorType &p) const
RealScalar distance (const VectorType &p) const
VectorType projection (const VectorType &p) const
VectorType pointAt (Scalar t) const
template<int OtherOptions>
Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
VectorType intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<typename NewScalarType >
internal::cast_return_type
< ParametrizedLine,
ParametrizedLine
< NewScalarType,
AmbientDimAtCompileTime,
Options > >::type cast () const
template<typename OtherScalarType , int OtherOptions>
ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
bool isApprox (const ParametrizedLine &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
template<int OtherOptions>
_Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
_Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
ParametrizedLine< _Scalar,
_AmbientDim, _Options >
::VectorType intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
Static Public Member Functions
static ParametrizedLine Through (const VectorType &p0, const VectorType &p1)
static ParametrizedLine Through (const VectorType &p0, const VectorType &p1)
Protected Attributes
VectorType m_origin
VectorType m_direction
Detailed Description
template<typename _Scalar, int _AmbientDim>
class Eigen::ParametrizedLine< _Scalar, _AmbientDim >
A parametrized line.
A parametrized line is defined by an origin point and a unit direction vector such that the line corresponds to the set , .
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic.
A parametrized line is defined by an origin point and a unit direction vector such that the line corresponds to the set , .
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic.
Definition at line 29 of file ParametrizedLine.h.
Member Typedef Documentation
template<typename _Scalar, int _AmbientDim> typedef DenseIndex Eigen::ParametrizedLine< _Scalar, _AmbientDim >::Index
Definition at line 40 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> typedef NumTraits<Scalar>::Real Eigen::ParametrizedLine< _Scalar, _AmbientDim >::RealScalar
Definition at line 35 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> typedef NumTraits<Scalar>::Real Eigen::ParametrizedLine< _Scalar, _AmbientDim >::RealScalar
Definition at line 39 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> typedef _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::Scalar
Definition at line 34 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> typedef _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::Scalar
Definition at line 38 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,AmbientDimAtCompileTime,1> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::VectorType
Definition at line 36 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,AmbientDimAtCompileTime,1,Options> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::VectorType
Definition at line 41 of file ParametrizedLine.h.
Member Enumeration Documentation
template<typename _Scalar, int _AmbientDim> anonymous enum
Enumerator
AmbientDimAtCompileTime
Definition at line 33 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> anonymous enum
Enumerator
AmbientDimAtCompileTime
Options
Definition at line 34 of file ParametrizedLine.h.
Constructor & Destructor Documentation
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine () inline explicit
Default constructor without initialization
Definition at line 39 of file ParametrizedLine.h.
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim >::cast(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::Through().
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (int _dim) inline explicit
Constructs a dynamic-size line with _dim the dimension of the ambient space
Definition at line 43 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (const VectorType & origin, const VectorType & direction) inline
Initializes a parametrized line of direction direction and origin origin.
Warning
the vector direction is assumed to be normalized.
Definition at line 48 of file ParametrizedLine.h.
template<typename _Scalar , int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim > & hyperplane) inline explicit
Constructs a parametrized line from a 2D hyperplane
Warning
the ambient space must have dimension 2 such that the hyperplane actually describes a line
Definition at line 125 of file ParametrizedLine.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::~ParametrizedLine () inline
Definition at line 57 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> template<typename OtherScalarType > Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 102 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction, Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin, and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin().
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine () inline explicit
Default constructor without initialization
Definition at line 44 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (const ParametrizedLine< Scalar, AmbientDimAtCompileTime, OtherOptions > & other) inline
Definition at line 47 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (Index _dim) inline explicit
Constructs a dynamic-size line with _dim the dimension of the ambient space
Definition at line 53 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (const VectorType & origin, const VectorType & direction) inline
Initializes a parametrized line of direction direction and origin origin.
Warning
the vector direction is assumed to be normalized.
Definition at line 58 of file ParametrizedLine.h.
template<typename _Scalar , int _AmbientDim, int _Options> template<int OtherOptions> Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) inline explicit
Constructs a parametrized line from a 2D hyperplane
Warning
the ambient space must have dimension 2 such that the hyperplane actually describes a line
Definition at line 146 of file ParametrizedLine.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::~ParametrizedLine () inline
Definition at line 68 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> template<typename OtherScalarType , int OtherOptions> Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 122 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction, and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin.
Member Function Documentation
template<typename _Scalar, int _AmbientDim> template<typename NewScalarType > internal::cast_return_type<ParametrizedLine, ParametrizedLine<NewScalarType,AmbientDimAtCompileTime> >::type Eigen::ParametrizedLine< _Scalar, _AmbientDim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 94 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine().
template<typename _Scalar, int _AmbientDim> template<typename NewScalarType > internal::cast_return_type<ParametrizedLine, ParametrizedLine<NewScalarType,AmbientDimAtCompileTime,Options> >::type Eigen::ParametrizedLine< _Scalar, _AmbientDim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 114 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine().
template<typename _Scalar, int _AmbientDim> int Eigen::ParametrizedLine< _Scalar, _AmbientDim >::dim () const inline
Returns
the dimension in which the line holds
Definition at line 60 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction.
template<typename _Scalar, int _AmbientDim> Index Eigen::ParametrizedLine< _Scalar, _AmbientDim >::dim () const inline
Returns
the dimension in which the line holds
Definition at line 71 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction.
template<typename _Scalar, int _AmbientDim> const VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction () const inline
Definition at line 65 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::projection(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::squaredDistance().
template<typename _Scalar, int _AmbientDim> VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction () inline
Definition at line 66 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction.
template<typename _Scalar, int _AmbientDim> const VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction () const inline
Definition at line 76 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction.
template<typename _Scalar, int _AmbientDim> VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction () inline
Definition at line 77 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction.
template<typename _Scalar, int _AmbientDim> RealScalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::distance (const VectorType & p) const inline
Returns
the distance of a point p to its projection onto the line *this.
See Also
squaredDistance()
Definition at line 79 of file ParametrizedLine.h.
References Eigen::ei_sqrt(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::squaredDistance().
template<typename _Scalar, int _AmbientDim> RealScalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::distance (const VectorType & p) const inline
Returns
the distance of a point p to its projection onto the line *this.
See Also
squaredDistance()
Definition at line 90 of file ParametrizedLine.h.
References sqrt(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::squaredDistance().
template<typename _Scalar , int _AmbientDim> _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersection (const Hyperplane< _Scalar, _AmbientDim > & hyperplane) inline
Returns
the parameter value of the intersection between *this and the given hyperplane
Definition at line 135 of file ParametrizedLine.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Deprecated:
use intersectionParameter()
Returns
the parameter value of the intersection between *this and the given hyperplane
Definition at line 178 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> _Scalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the parameter value of the intersection between *this and the given hyperplane
Definition at line 166 of file ParametrizedLine.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> ParametrizedLine<_Scalar, _AmbientDim,_Options>::VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the point of the intersection between *this and the given hyperplane
Definition at line 188 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> bool Eigen::ParametrizedLine< _Scalar, _AmbientDim >::isApprox (const ParametrizedLine< _Scalar, _AmbientDim > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 112 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction, and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin.
template<typename _Scalar, int _AmbientDim> bool Eigen::ParametrizedLine< _Scalar, _AmbientDim >::isApprox (const ParametrizedLine< _Scalar, _AmbientDim > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 132 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction, and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin.
template<typename _Scalar, int _AmbientDim> const VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin () const inline
Definition at line 62 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::projection(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::squaredDistance().
template<typename _Scalar, int _AmbientDim> VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin () inline
Definition at line 63 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin.
template<typename _Scalar, int _AmbientDim> const VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin () const inline
Definition at line 73 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin.
template<typename _Scalar, int _AmbientDim> VectorType& Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin () inline
Definition at line 74 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin.
template<typename _Scalar , int _AmbientDim, int _Options> ParametrizedLine< _Scalar, _AmbientDim, _Options >::VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt (Scalar t) const inline
Returns
the point at t along this line
Definition at line 157 of file ParametrizedLine.h.
template<typename _Scalar, int _AmbientDim> VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the line *this.
Definition at line 82 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin().
template<typename _Scalar, int _AmbientDim> VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the line *this.
Definition at line 93 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin().
template<typename _Scalar, int _AmbientDim> RealScalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::squaredDistance (const VectorType & p) const inline
Returns
the squared distance of a point p to its projection onto the line *this.
See Also
distance()
Definition at line 71 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin().
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim >::distance().
template<typename _Scalar, int _AmbientDim> RealScalar Eigen::ParametrizedLine< _Scalar, _AmbientDim >::squaredDistance (const VectorType & p) const inline
Returns
the squared distance of a point p to its projection onto the line *this.
See Also
distance()
Definition at line 82 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin().
template<typename _Scalar, int _AmbientDim> static ParametrizedLine Eigen::ParametrizedLine< _Scalar, _AmbientDim >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a parametrized line going from p0 to p1.
Definition at line 54 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine().
template<typename _Scalar, int _AmbientDim> static ParametrizedLine Eigen::ParametrizedLine< _Scalar, _AmbientDim >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a parametrized line going from p0 to p1.
Definition at line 65 of file ParametrizedLine.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine().
Member Data Documentation
template<typename _Scalar, int _AmbientDim> VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_direction protected
Definition at line 117 of file ParametrizedLine.h.
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim >::dim(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::isApprox(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine().
template<typename _Scalar, int _AmbientDim> VectorType Eigen::ParametrizedLine< _Scalar, _AmbientDim >::m_origin protected
Definition at line 117 of file ParametrizedLine.h.
Referenced by Eigen::ParametrizedLine< _Scalar, _AmbientDim >::isApprox(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h