LIA_RAL: QMatrix Class Reference
QMatrix Class Reference abstract
Public Member Functions
virtual Qfloat * get_Q (int column, int len) const =0
virtual double * get_QD () const =0
virtual void swap_index (int i, int j) const =0
virtual ~QMatrix ()
Detailed Description
Definition at line 194 of file libsvm.cpp.
Constructor & Destructor Documentation
virtual QMatrix::~QMatrix () inline virtual
Definition at line 199 of file libsvm.cpp.
Member Function Documentation
virtual Qfloat* QMatrix::get_Q (int column, int len) const pure virtual
Implemented in SVR_Q, ONE_CLASS_Q, SVC_Q, and Kernel.
Referenced by Solver::reconstruct_gradient(), Solver::select_working_set(), Solver_NU::select_working_set(), and Solver::Solve().
virtual double* QMatrix::get_QD () const pure virtual
Implemented in SVR_Q, ONE_CLASS_Q, SVC_Q, and Kernel.
Referenced by Solver::Solve().
virtual void QMatrix::swap_index (int i, int j) const pure virtual
Implemented in SVR_Q, ONE_CLASS_Q, SVC_Q, and Kernel.
Referenced by Solver::swap_index().
The documentation for this class was generated from the following file:
LIA_Utils/Svm/src/libsvm.cpp