LIA_RAL: TrainCfg Class Reference
TrainCfg Class Reference
#include <TrainTools.h>
Public Member Functions
TrainCfg (Config &)
double getInitVarFloor ()
double getInitVarCeil ()
double getFinalVarFloor ()
double getFinalVarCeil ()
unsigned long getNbTrainIt ()
bool getNormalizeModel ()
bool getNormalizeModelMeanOnly ()
unsigned long getNormalizeModelNbIt ()
double getBaggedFrameProbability ()
double getBaggedFrameProbabilityInit ()
bool getComponentReduction ()
unsigned long getTargetDistribCount ()
void setInitVarFlooring (double v)
void setInitVarCeiling (double v)
void setFinalVarFlooring (double v)
void setFinalVarCeiling (double v)
void setNbTrainIt (unsigned long v)
void setNormalizeModel (bool v)
void setNormalizeModelMeanOnly (bool v)
void setNormalizeModelNbIt (unsigned long v)
void setBaggedFrameProbability (double v)
void setBaggedFrameProbabilityInit (double v)
void showConfig (ostream &)
Private Attributes
double _initVarianceFlooring
double _initVarianceCeiling
double _finalVarianceFlooring
double _finalVarianceCeiling
unsigned long _nbTrainIt
bool _normalizeModel
bool _normalizeModelMeanOnly
unsigned long _normalizeModelNbIt
double _baggedFrameProbability
double _baggedFrameProbabilityInit
bool _componentReduction
unsigned long _targetDistribCount
Detailed Description
Definition at line 122 of file TrainTools.h.
Constructor & Destructor Documentation
TrainCfg::TrainCfg (Config & config)
Definition at line 67 of file TrainTools.cpp.
References _baggedFrameProbability, _baggedFrameProbabilityInit, _componentReduction, _finalVarianceCeiling, _finalVarianceFlooring, _initVarianceCeiling, _initVarianceFlooring, _nbTrainIt, _normalizeModel, _normalizeModelMeanOnly, _normalizeModelNbIt, and _targetDistribCount.
Member Function Documentation
double TrainCfg::getBaggedFrameProbability () inline
Definition at line 145 of file TrainTools.h.
Referenced by trainModel(), and trainModelStream().
double TrainCfg::getBaggedFrameProbabilityInit () inline
Definition at line 146 of file TrainTools.h.
Referenced by mixtureInit().
bool TrainCfg::getComponentReduction () inline
Definition at line 147 of file TrainTools.h.
Referenced by trainModelStream().
double TrainCfg::getFinalVarCeil () inline
Definition at line 140 of file TrainTools.h.
Referenced by mixtureInitBySplit(), trainModel(), and trainModelStream().
double TrainCfg::getFinalVarFloor () inline
Definition at line 139 of file TrainTools.h.
Referenced by mixtureInitBySplit(), trainModel(), and trainModelStream().
double TrainCfg::getInitVarCeil () inline
Definition at line 138 of file TrainTools.h.
Referenced by mixtureInitBySplit(), trainModel(), and trainModelStream().
double TrainCfg::getInitVarFloor () inline
Definition at line 137 of file TrainTools.h.
Referenced by mixtureInitBySplit(), trainModel(), and trainModelStream().
unsigned long TrainCfg::getNbTrainIt () inline
Definition at line 141 of file TrainTools.h.
Referenced by clusteringCriterionWithoutWorldInitOneGaus(), mixtureInitBySplit(), trainModel(), and trainModelStream().
bool TrainCfg::getNormalizeModel () inline
Definition at line 142 of file TrainTools.h.
Referenced by mixtureInitBySplit(), trainModel(), and trainModelStream().
bool TrainCfg::getNormalizeModelMeanOnly () inline
Definition at line 143 of file TrainTools.h.
Referenced by normalizeMixture().
unsigned long TrainCfg::getNormalizeModelNbIt () inline
Definition at line 144 of file TrainTools.h.
Referenced by normalizeMixture().
unsigned long TrainCfg::getTargetDistribCount () inline
Definition at line 148 of file TrainTools.h.
Referenced by trainModelStream().
void TrainCfg::setBaggedFrameProbability (double v) inline
Definition at line 157 of file TrainTools.h.
Referenced by clusteringCriterion(), clusteringCriterionWithoutWorldInit(), learnModel(), learnModelFromBaggedFrame(), and learnModelFromSplit().
void TrainCfg::setBaggedFrameProbabilityInit (double v) inline
Definition at line 158 of file TrainTools.h.
Referenced by clusteringCriterionWithoutWorldInit(), and learnModelFromBaggedFrame().
void TrainCfg::setFinalVarCeiling (double v) inline
Definition at line 152 of file TrainTools.h.
void TrainCfg::setFinalVarFlooring (double v) inline
Definition at line 151 of file TrainTools.h.
Referenced by clusteringCriterionWithoutWorldInit(), and learnModelFromBaggedFrame().
void TrainCfg::setInitVarCeiling (double v) inline
Definition at line 150 of file TrainTools.h.
void TrainCfg::setInitVarFlooring (double v) inline
Definition at line 149 of file TrainTools.h.
Referenced by clusteringCriterionWithoutWorldInit(), and learnModelFromBaggedFrame().
void TrainCfg::setNbTrainIt (unsigned long v) inline
Definition at line 153 of file TrainTools.h.
Referenced by clusteringCriterion(), clusteringCriterionWithoutWorldInit(), clusteringCriterionWithoutWorldInitOneGaus(), learnModel(), learnModelFromBaggedFrame(), and learnModelFromSplit().
void TrainCfg::setNormalizeModel (bool v) inline
Definition at line 154 of file TrainTools.h.
void TrainCfg::setNormalizeModelMeanOnly (bool v) inline
Definition at line 155 of file TrainTools.h.
void TrainCfg::setNormalizeModelNbIt (unsigned long v) inline
Definition at line 156 of file TrainTools.h.
void TrainCfg::showConfig (ostream & st = cout)
Definition at line 94 of file TrainTools.cpp.
References _componentReduction, _finalVarianceCeiling, _finalVarianceFlooring, _initVarianceCeiling, _initVarianceFlooring, _nbTrainIt, _normalizeModel, _normalizeModelMeanOnly, _normalizeModelNbIt, and _targetDistribCount.
Referenced by mixtureInitBySplit(), trainModel(), and trainModelStream().
Member Data Documentation
double TrainCfg::_baggedFrameProbability private
Definition at line 131 of file TrainTools.h.
Referenced by TrainCfg().
double TrainCfg::_baggedFrameProbabilityInit private
Definition at line 132 of file TrainTools.h.
Referenced by TrainCfg().
bool TrainCfg::_componentReduction private
Definition at line 133 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
double TrainCfg::_finalVarianceCeiling private
Definition at line 126 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
double TrainCfg::_finalVarianceFlooring private
Definition at line 125 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
double TrainCfg::_initVarianceCeiling private
Definition at line 124 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
double TrainCfg::_initVarianceFlooring private
Definition at line 123 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
unsigned long TrainCfg::_nbTrainIt private
Definition at line 127 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
bool TrainCfg::_normalizeModel private
Definition at line 128 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
bool TrainCfg::_normalizeModelMeanOnly private
Definition at line 129 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
unsigned long TrainCfg::_normalizeModelNbIt private
Definition at line 130 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
unsigned long TrainCfg::_targetDistribCount private
Definition at line 134 of file TrainTools.h.
Referenced by showConfig(), and TrainCfg().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/TrainTools.h
LIA_SpkTools/src/TrainTools.cpp