LIA_RAL: Eigen::JacobiRotation< Scalar > Class Template Reference
Eigen::JacobiRotation< Scalar > Class Template Reference
Rotation given by a cosine-sine pair.
#include <ForwardDeclarations.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Public Member Functions
JacobiRotation ()
JacobiRotation (const Scalar &c, const Scalar &s)
Scalar & c ()
Scalar c () const
Scalar & s ()
Scalar s () const
JacobiRotation operator* (const JacobiRotation &other)
JacobiRotation transpose () const
JacobiRotation adjoint () const
template<typename Derived >
bool makeJacobi (const MatrixBase< Derived > &, typename Derived::Index p, typename Derived::Index q)
bool makeJacobi (RealScalar x, Scalar y, RealScalar z)
void makeGivens (const Scalar &p, const Scalar &q, Scalar *z=0)
Protected Member Functions
void makeGivens (const Scalar &p, const Scalar &q, Scalar *z, internal::true_type)
void makeGivens (const Scalar &p, const Scalar &q, Scalar *z, internal::false_type)
Protected Attributes
Scalar m_c
Scalar m_s
Detailed Description
template<typename Scalar>
class Eigen::JacobiRotation< Scalar >
Rotation given by a cosine-sine pair.
This class represents a Jacobi or Givens rotation. This is a 2D rotation in the plane J of angle defined by its cosine c and sine s as follow:
You can apply the respective counter-clockwise rotation to a column vector v by applying its adjoint on the left: that translates to the following Eigen code:
v.applyOnTheLeft(J.adjoint());
See Also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Definition at line 229 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename Scalar> typedef NumTraits<Scalar>::Real Eigen::JacobiRotation< Scalar >::RealScalar
Definition at line 37 of file Jacobi.h.
Constructor & Destructor Documentation
template<typename Scalar> Eigen::JacobiRotation< Scalar >::JacobiRotation () inline
Default constructor without any initialization.
Definition at line 40 of file Jacobi.h.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::operator*(), and Eigen::JacobiRotation< Scalar >::transpose().
template<typename Scalar> Eigen::JacobiRotation< Scalar >::JacobiRotation (const Scalar & c, const Scalar & s) inline
Construct a planar rotation from a cosine-sine pair (c, s).
Definition at line 43 of file Jacobi.h.
Member Function Documentation
template<typename Scalar> JacobiRotation Eigen::JacobiRotation< Scalar >::adjoint () const inline
Returns the adjoint transformation
Definition at line 61 of file Jacobi.h.
References Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::RealSchur< _MatrixType >::splitOffTwoRows().
template<typename Scalar> Scalar& Eigen::JacobiRotation< Scalar >::c () inline
Definition at line 45 of file Jacobi.h.
References Eigen::JacobiRotation< Scalar >::m_c.
Referenced by Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::internal::tridiagonal_qr_step().
template<typename Scalar> Scalar Eigen::JacobiRotation< Scalar >::c () const inline
Definition at line 46 of file Jacobi.h.
References Eigen::JacobiRotation< Scalar >::m_c.
template<typename Scalar > void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * z = 0)
Makes *this as a Givens rotation G such that applying to the left of the vector yields: .
The value of z is returned if z is not null (the default is null). Also note that G is built such that the cosine is always real.
Example:
Output:
This function implements the continuous Givens rotation generation algorithm found in Anderson (2000), Discontinuous Plane Rotations and the Symmetric Eigenvalue Problem. LAPACK Working Note 150, University of Tennessee, UT-CS-00-454, December 4, 2000.
See Also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Definition at line 145 of file Jacobi.h.
Referenced by Eigen::internal::llt_rank_update_lower(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::RealSchur< _MatrixType >::splitOffTwoRows(), and Eigen::internal::tridiagonal_qr_step().
template<typename Scalar > void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * z, internal::true_type) protected
Definition at line 153 of file Jacobi.h.
References abs(), abs2(), real(), and sqrt().
template<typename Scalar > void Eigen::JacobiRotation< Scalar >::makeGivens (const Scalar & p, const Scalar & q, Scalar * z, internal::false_type) protected
Definition at line 208 of file Jacobi.h.
References abs(), abs2(), and sqrt().
template<typename Scalar > template<typename Derived > bool Eigen::JacobiRotation< Scalar >::makeJacobi (const MatrixBase< Derived > & m, typename Derived::Index p, typename Derived::Index q) inline
Makes *this as a Jacobi rotation J such that applying J on both the right and left sides of the 2x2 selfadjoint matrix yields a diagonal matrix
Example:
Output:
See Also
JacobiRotation::makeJacobi(RealScalar, Scalar, RealScalar), MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Definition at line 123 of file Jacobi.h.
References real().
Referenced by Eigen::internal::real_2x2_jacobi_svd().
template<typename Scalar > bool Eigen::JacobiRotation< Scalar >::makeJacobi (RealScalar x, Scalar y, RealScalar z)
Makes *this as a Jacobi rotation J such that applying J on both the right and left sides of the selfadjoint 2x2 matrix yields a diagonal matrix
See Also
MatrixBase::makeJacobi(const MatrixBase<Derived>&, Index, Index), MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Definition at line 82 of file Jacobi.h.
References abs(), abs2(), and sqrt().
template<typename Scalar> JacobiRotation Eigen::JacobiRotation< Scalar >::operator* (const JacobiRotation< Scalar > & other) inline
Concatenates two planar rotation
Definition at line 51 of file Jacobi.h.
References Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
template<typename Scalar> Scalar& Eigen::JacobiRotation< Scalar >::s () inline
Definition at line 47 of file Jacobi.h.
References Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::internal::tridiagonal_qr_step().
template<typename Scalar> Scalar Eigen::JacobiRotation< Scalar >::s () const inline
Definition at line 48 of file Jacobi.h.
References Eigen::JacobiRotation< Scalar >::m_s.
template<typename Scalar> JacobiRotation Eigen::JacobiRotation< Scalar >::transpose () const inline
Returns the transposed transformation
Definition at line 58 of file Jacobi.h.
References Eigen::JacobiRotation< Scalar >::JacobiRotation(), Eigen::JacobiRotation< Scalar >::m_c, and Eigen::JacobiRotation< Scalar >::m_s.
Referenced by Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute(), and Eigen::internal::real_2x2_jacobi_svd().
Member Data Documentation
template<typename Scalar> Scalar Eigen::JacobiRotation< Scalar >::m_c protected
Definition at line 73 of file Jacobi.h.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::c(), Eigen::JacobiRotation< Scalar >::operator*(), and Eigen::JacobiRotation< Scalar >::transpose().
template<typename Scalar> Scalar Eigen::JacobiRotation< Scalar >::m_s protected
Definition at line 73 of file Jacobi.h.
Referenced by Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::operator*(), Eigen::JacobiRotation< Scalar >::s(), and Eigen::JacobiRotation< Scalar >::transpose().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Jacobi/Jacobi.h