LIA_RAL: Kernel Class Reference
Kernel Class Reference abstract
Public Member Functions
Kernel (int l, svm_node *const *x, const svm_parameter &param)
virtual ~Kernel ()
virtual Qfloat * get_Q (int column, int len) const =0
virtual double * get_QD () const =0
virtual void swap_index (int i, int j) const
Public Member Functions inherited from QMatrix
virtual ~QMatrix ()
Static Public Member Functions
static double k_function (const svm_node *x, const svm_node *y, const svm_parameter &param)
Protected Attributes
double(Kernel::* kernel_function)(int i, int j) const
Private Member Functions
double kernel_linear (int i, int j) const
double kernel_poly (int i, int j) const
double kernel_rbf (int i, int j) const
double kernel_sigmoid (int i, int j) const
double kernel_precomputed (int i, int j) const
Static Private Member Functions
static double dot (const svm_node *px, const svm_node *py)
Private Attributes
const svm_node ** x
double * x_square
const int kernel_type
const int degree
const double gamma
const double coef0
Detailed Description
Definition at line 202 of file libsvm.cpp.
Constructor & Destructor Documentation
Kernel::Kernel (int l, svm_node *const * x, const svm_parameter & param)
Definition at line 253 of file libsvm.cpp.
References clone(), dot(), kernel_function, kernel_linear(), kernel_poly(), kernel_precomputed(), kernel_rbf(), kernel_sigmoid(), kernel_type, LINEAR, POLY, PRECOMPUTED, RBF, SIGMOID, x, and x_square.
Kernel::~Kernel () virtual
Definition at line 288 of file libsvm.cpp.
References x, and x_square.
Member Function Documentation
double Kernel::dot (const svm_node * px, const svm_node * py) static private
Definition at line 294 of file libsvm.cpp.
References svm_node::index, and svm_node::value.
Referenced by k_function(), Kernel(), kernel_linear(), kernel_poly(), kernel_rbf(), and kernel_sigmoid().
virtual Qfloat* Kernel::get_Q (int column, int len) const pure virtual
Implements QMatrix.
Implemented in SVR_Q, ONE_CLASS_Q, and SVC_Q.
virtual double* Kernel::get_QD () const pure virtual
Implements QMatrix.
Implemented in SVR_Q, ONE_CLASS_Q, and SVC_Q.
double Kernel::k_function (const svm_node * x, const svm_node * y, const svm_parameter & param) static
Definition at line 316 of file libsvm.cpp.
References svm_parameter::coef0, svm_parameter::degree, dot(), exp(), svm_parameter::gamma, svm_node::index, svm_parameter::kernel_type, LINEAR, POLY, powi(), PRECOMPUTED, RBF, SIGMOID, svm_node::value, x, and Eigen::internal::y.
Referenced by svm_predict_values().
double Kernel::kernel_linear (int i, int j) const inline private
Definition at line 231 of file libsvm.cpp.
References dot().
Referenced by Kernel().
double Kernel::kernel_poly (int i, int j) const inline private
Definition at line 235 of file libsvm.cpp.
References coef0, degree, dot(), gamma, and powi().
Referenced by Kernel().
double Kernel::kernel_precomputed (int i, int j) const inline private
Definition at line 247 of file libsvm.cpp.
References svm_node::value.
Referenced by Kernel().
double Kernel::kernel_rbf (int i, int j) const inline private
Definition at line 239 of file libsvm.cpp.
References dot(), exp(), gamma, and x_square.
Referenced by Kernel().
double Kernel::kernel_sigmoid (int i, int j) const inline private
Definition at line 243 of file libsvm.cpp.
References coef0, dot(), and gamma.
Referenced by Kernel().
virtual void Kernel::swap_index (int i, int j) const inline virtual
Implements QMatrix.
Reimplemented in SVR_Q, ONE_CLASS_Q, and SVC_Q.
Definition at line 211 of file libsvm.cpp.
References swap(), and x_square.
Referenced by SVC_Q::swap_index(), and ONE_CLASS_Q::swap_index().
Member Data Documentation
const double Kernel::coef0 private
Definition at line 228 of file libsvm.cpp.
Referenced by kernel_poly(), and kernel_sigmoid().
const int Kernel::degree private
Definition at line 226 of file libsvm.cpp.
Referenced by kernel_poly().
const double Kernel::gamma private
Definition at line 227 of file libsvm.cpp.
Referenced by kernel_poly(), kernel_rbf(), and kernel_sigmoid().
double(Kernel::* Kernel::kernel_function)(int i, int j) const protected
Definition at line 218 of file libsvm.cpp.
Referenced by SVC_Q::get_Q(), ONE_CLASS_Q::get_Q(), SVR_Q::get_Q(), Kernel(), ONE_CLASS_Q::ONE_CLASS_Q(), SVC_Q::SVC_Q(), and SVR_Q::SVR_Q().
const int Kernel::kernel_type private
Definition at line 225 of file libsvm.cpp.
Referenced by Kernel().
const svm_node** Kernel::x private
Definition at line 221 of file libsvm.cpp.
Referenced by k_function(), Kernel(), and ~Kernel().
double* Kernel::x_square private
Definition at line 222 of file libsvm.cpp.
Referenced by Kernel(), kernel_rbf(), swap_index(), and ~Kernel().
The documentation for this class was generated from the following file:
LIA_Utils/Svm/src/libsvm.cpp