LIA_RAL: Eigen::TranspositionsBase< Derived > Class Template Reference
Eigen::TranspositionsBase< Derived > Class Template Reference
#include <Transpositions.h>
Public Types
typedef Traits::IndicesType IndicesType
typedef IndicesType::Scalar Index
Public Member Functions
Derived & derived ()
const Derived & derived () const
template<typename OtherDerived >
Derived & operator= (const TranspositionsBase< OtherDerived > &other)
Derived & operator= (const TranspositionsBase &other)
Index size () const
const Index & coeff (Index i) const
Index & coeffRef (Index i)
const Index & operator() (Index i) const
Index & operator() (Index i)
const Index & operator[] (Index i) const
Index & operator[] (Index i)
const IndicesType & indices () const
IndicesType & indices ()
void resize (int size)
void setIdentity ()
Transpose< TranspositionsBase > inverse () const
Transpose< TranspositionsBase > transpose () const
Private Types
typedef internal::traits< Derived > Traits
Detailed Description
template<typename Derived>
class Eigen::TranspositionsBase< Derived >
Definition at line 49 of file Transpositions.h.
Member Typedef Documentation
template<typename Derived> typedef IndicesType::Scalar Eigen::TranspositionsBase< Derived >::Index
Definition at line 56 of file Transpositions.h.
template<typename Derived> typedef Traits::IndicesType Eigen::TranspositionsBase< Derived >::IndicesType
Definition at line 55 of file Transpositions.h.
template<typename Derived> typedef internal::traits<Derived> Eigen::TranspositionsBase< Derived >::Traits private
Definition at line 51 of file Transpositions.h.
Member Function Documentation
template<typename Derived> const Index& Eigen::TranspositionsBase< Derived >::coeff (Index i) const inline
Direct access to the underlying index vector
Definition at line 84 of file Transpositions.h.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=().
template<typename Derived> Index& Eigen::TranspositionsBase< Derived >::coeffRef (Index i) inline
Direct access to the underlying index vector
Definition at line 86 of file Transpositions.h.
Referenced by Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity().
template<typename Derived> Derived& Eigen::TranspositionsBase< Derived >::derived () inline
Definition at line 58 of file Transpositions.h.
Referenced by Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), Eigen::operator*(), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=(), Eigen::Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, _PacketAccess >::operator=(), and Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose().
template<typename Derived> const Derived& Eigen::TranspositionsBase< Derived >::derived () const inline
Definition at line 59 of file Transpositions.h.
template<typename Derived> const IndicesType& Eigen::TranspositionsBase< Derived >::indices () const inline
const version of indices().
Definition at line 97 of file Transpositions.h.
Referenced by Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::coeff(), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::coeffRef(), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator()(), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator[](), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::resize(), Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity(), and Eigen::TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::size().
template<typename Derived> IndicesType& Eigen::TranspositionsBase< Derived >::indices () inline
Returns
a reference to the stored array representing the transpositions.
Definition at line 99 of file Transpositions.h.
template<typename Derived> Transpose<TranspositionsBase> Eigen::TranspositionsBase< Derived >::inverse () const inline
Returns
the inverse transformation
Definition at line 136 of file Transpositions.h.
template<typename Derived> const Index& Eigen::TranspositionsBase< Derived >::operator() (Index i) const inline
Direct access to the underlying index vector
Definition at line 88 of file Transpositions.h.
template<typename Derived> Index& Eigen::TranspositionsBase< Derived >::operator() (Index i) inline
Direct access to the underlying index vector
Definition at line 90 of file Transpositions.h.
template<typename Derived> template<typename OtherDerived > Derived& Eigen::TranspositionsBase< Derived >::operator= (const TranspositionsBase< OtherDerived > & other) inline
Copies the other transpositions into *this
Definition at line 63 of file Transpositions.h.
Referenced by Eigen::Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=(), and Eigen::TranspositionsWrapper< _IndicesType >::operator=().
template<typename Derived> Derived& Eigen::TranspositionsBase< Derived >::operator= (const TranspositionsBase< Derived > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
Definition at line 73 of file Transpositions.h.
template<typename Derived> const Index& Eigen::TranspositionsBase< Derived >::operator[] (Index i) const inline
Direct access to the underlying index vector
Definition at line 92 of file Transpositions.h.
template<typename Derived> Index& Eigen::TranspositionsBase< Derived >::operator[] (Index i) inline
Direct access to the underlying index vector
Definition at line 94 of file Transpositions.h.
template<typename Derived> void Eigen::TranspositionsBase< Derived >::resize (int size) inline
Resizes to given size.
Definition at line 102 of file Transpositions.h.
template<typename Derived> void Eigen::TranspositionsBase< Derived >::setIdentity () inline
Sets *this to represents an identity transformation
Definition at line 108 of file Transpositions.h.
template<typename Derived> Index Eigen::TranspositionsBase< Derived >::size () const inline
Returns
the number of transpositions
Definition at line 81 of file Transpositions.h.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=().
template<typename Derived> Transpose<TranspositionsBase> Eigen::TranspositionsBase< Derived >::transpose () const inline
Returns
the tranpose transformation
Definition at line 140 of file Transpositions.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/Transpositions.h