LIA_RAL: Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess > Class Template Reference
Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess > Class Template Reference
Expression of a fixed-size or dynamic-size block.
#include <Block.h>
Public Types
typedef
internal::dense_xpr_base
< Block >::type Base
Public Member Functions
Block (XprType &xpr, Index i)
Block (XprType &xpr, Index startRow, Index startCol)
Block (XprType &xpr, Index startRow, Index startCol, Index blockRows, Index blockCols)
Index rows () const
Index cols () const
Scalar & coeffRef (Index row, Index col)
const Scalar & coeffRef (Index row, Index col) const
EIGEN_STRONG_INLINE const
CoeffReturnType coeff (Index row, Index col) const
Scalar & coeffRef (Index index)
const Scalar & coeffRef (Index index) const
const CoeffReturnType coeff (Index index) const
template<int LoadMode>
PacketScalar packet (Index row, Index col) const
template<int LoadMode>
void writePacket (Index row, Index col, const PacketScalar &x)
template<int LoadMode>
PacketScalar packet (Index index) const
template<int LoadMode>
void writePacket (Index index, const PacketScalar &x)
const internal::remove_all
< typename XprType::Nested >
::type & nestedExpression () const
Index startRow () const
Index startCol () const
Protected Attributes
const XprType::Nested m_xpr
const
internal::variable_if_dynamic
< Index,
XprType::RowsAtCompileTime==1?0:Dynamic > m_startRow
const
internal::variable_if_dynamic
< Index,
XprType::ColsAtCompileTime==1?0:Dynamic > m_startCol
const
internal::variable_if_dynamic
< Index, RowsAtCompileTime > m_blockRows
const
internal::variable_if_dynamic
< Index, ColsAtCompileTime > m_blockCols
Detailed Description
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess>
class Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >
Expression of a fixed-size or dynamic-size block.
Parameters
XprType the type of the expression in which we are taking a block
BlockRows the number of rows of the block we are taking at compile time (optional)
BlockCols the number of columns of the block we are taking at compile time (optional)
_DirectAccessStatus
Definition at line 97 of file Block.h.
Member Typedef Documentation
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> typedef internal::dense_xpr_base<Block>::type Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::Base
Definition at line 102 of file Block.h.
Constructor & Destructor Documentation
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::Block (XprType & xpr, Index i) inline
Column or Row constructor
Definition at line 109 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::Block (XprType & xpr, Index startRow, Index startCol) inline
Fixed-size constructor
Definition at line 127 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::Block (XprType & xpr, Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Dynamic-size constructor
Definition at line 138 of file Block.h.
Member Function Documentation
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> EIGEN_STRONG_INLINE const CoeffReturnType Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeff (Index row, Index col) const inline
Definition at line 168 of file Block.h.
Referenced by Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::unblocked_lu().
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const CoeffReturnType Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeff (Index index) const inline
Definition at line 188 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Scalar& Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeffRef (Index row, Index col) inline
Definition at line 155 of file Block.h.
Referenced by Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::blocked_lu(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), and Eigen::internal::llt_inplace< Scalar, Lower >::unblocked().
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const Scalar& Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeffRef (Index row, Index col) const inline
Definition at line 162 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Scalar& Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeffRef (Index index) inline
Definition at line 173 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const Scalar& Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeffRef (Index index) const inline
Definition at line 181 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Index Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::cols () const inline
Definition at line 153 of file Block.h.
Referenced by Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::unblocked_lu().
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const internal::remove_all<typename XprType::Nested>::type& Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::nestedExpression () const inline
Definition at line 232 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> template<int LoadMode> PacketScalar Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::packet (Index row, Index col) const inline
Definition at line 196 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> template<int LoadMode> PacketScalar Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::packet (Index index) const inline
Definition at line 210 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Index Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::rows () const inline
Definition at line 152 of file Block.h.
Referenced by Eigen::internal::householder_qr_inplace_blocked(), and Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::unblocked_lu().
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Index Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::startCol () const inline
Definition at line 242 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> Index Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::startRow () const inline
Definition at line 237 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> template<int LoadMode> void Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::writePacket (Index row, Index col, const PacketScalar & x) inline
Definition at line 203 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> template<int LoadMode> void Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::writePacket (Index index, const PacketScalar & x) inline
Definition at line 218 of file Block.h.
Member Data Documentation
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const internal::variable_if_dynamic<Index, ColsAtCompileTime> Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::m_blockCols protected
Definition at line 253 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const internal::variable_if_dynamic<Index, RowsAtCompileTime> Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::m_blockRows protected
Definition at line 252 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const internal::variable_if_dynamic<Index, XprType::ColsAtCompileTime == 1 ? 0 : Dynamic> Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::m_startCol protected
Definition at line 251 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const internal::variable_if_dynamic<Index, XprType::RowsAtCompileTime == 1 ? 0 : Dynamic> Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::m_startRow protected
Definition at line 250 of file Block.h.
template<typename XprType, int BlockRows, int BlockCols, bool InnerPanel, bool HasDirectAccess> const XprType::Nested Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::m_xpr protected
Definition at line 249 of file Block.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/Block.h