LIA_RAL: TopGauss Class Reference
TopGauss Class Reference
#include <TopGauss.h>
Public Member Functions
TopGauss ()
~TopGauss ()
double compute (MixtureGD &, FeatureServer &, String &, Config &)
double get (MixtureGD &, FeatureServer &, String &, Config &)
double compute (MixtureGD &, String &, Config &)
RealVector< double > compute (MixtureGD &, FeatureServer &, Config &)
double get (MixtureGD &, String &, Config &)
RealVector< double > get (MixtureGD &, FeatureServer &, Config &)
void read (String &, Config &)
void write (String &, Config &)
ULongVector & nbg ()
ULongVector & idx ()
unsigned long frameToIdx (unsigned long &)
unsigned long nbgcnt ()
unsigned long nt ()
Private Attributes
ULongVector _idx
ULongVector _nbg
DoubleVector _snsw
DoubleVector _snsl
unsigned long _nt
unsigned long _nbgcnt
Detailed Description
Definition at line 74 of file TopGauss.h.
Constructor & Destructor Documentation
TopGauss::TopGauss () inline
Definition at line 85 of file TopGauss.h.
TopGauss::~TopGauss () inline
Definition at line 87 of file TopGauss.h.
Member Function Documentation
double TopGauss::compute (MixtureGD & UBM, FeatureServer & fs, String & featureFilename, Config & config)
Definition at line 136 of file TopGauss.cpp.
References _idx, _nbg, _nbgcnt, _nt, _snsl, _snsw, EPS_LK, exp(), idx(), initializeClusters(), totalFrame(), verbose, and verifyClusterFile().
Referenced by compute().
double TopGauss::compute (MixtureGD & UBM, String & featureFilename, Config & config)
Definition at line 112 of file TopGauss.cpp.
References _nbgcnt, _nt, compute(), and verbose.
RealVector< double > TopGauss::compute (MixtureGD & UBM, FeatureServer & fs, Config & config)
Definition at line 121 of file TopGauss.cpp.
References _idx, _nbgcnt, _nt, _snsw, compute(), verbose, and write().
unsigned long TopGauss::frameToIdx (unsigned long & f)
Definition at line 68 of file TopGauss.cpp.
References _nbg.
Referenced by get().
double TopGauss::get (MixtureGD & UBM, FeatureServer & fs, String & featureFilename, Config & config)
Definition at line 270 of file TopGauss.cpp.
References _idx, _nbg, _nbgcnt, _nt, _snsl, _snsw, frameToIdx(), initializeClusters(), nbg(), and verifyClusterFile().
double TopGauss::get (MixtureGD & UBM, String & featureFilename, Config & config)
Definition at line 215 of file TopGauss.cpp.
References _nbgcnt, _nt, and verbose.
RealVector< double > TopGauss::get (MixtureGD & UBM, FeatureServer & fs, Config & config)
Definition at line 202 of file TopGauss.cpp.
References _nbgcnt, _nt, read(), and verbose.
ULongVector& TopGauss::idx () inline
Definition at line 103 of file TopGauss.h.
Referenced by compute().
ULongVector& TopGauss::nbg () inline
Definition at line 101 of file TopGauss.h.
Referenced by get().
unsigned long TopGauss::nbgcnt () inline
Definition at line 106 of file TopGauss.h.
unsigned long TopGauss::nt () inline
Definition at line 108 of file TopGauss.h.
void TopGauss::read (String & featureFilename, Config & config)
Definition at line 76 of file TopGauss.cpp.
References _idx, _nbg, _nbgcnt, _nt, _snsl, _snsw, verbose, and verboseLevel.
Referenced by get().
void TopGauss::write (String & featureFilename, Config & config)
Definition at line 96 of file TopGauss.cpp.
References _idx, _nbg, _nbgcnt, _nt, _snsl, _snsw, and verbose.
Referenced by compute().
Member Data Documentation
ULongVector TopGauss::_idx private
Definition at line 76 of file TopGauss.h.
Referenced by compute(), get(), read(), and write().
ULongVector TopGauss::_nbg private
Definition at line 77 of file TopGauss.h.
Referenced by compute(), frameToIdx(), get(), read(), and write().
unsigned long TopGauss::_nbgcnt private
Definition at line 82 of file TopGauss.h.
Referenced by compute(), get(), read(), and write().
unsigned long TopGauss::_nt private
Definition at line 81 of file TopGauss.h.
Referenced by compute(), get(), read(), and write().
DoubleVector TopGauss::_snsl private
Definition at line 79 of file TopGauss.h.
Referenced by compute(), get(), read(), and write().
DoubleVector TopGauss::_snsw private
Definition at line 78 of file TopGauss.h.
Referenced by compute(), get(), read(), and write().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/TopGauss.h
LIA_SpkTools/src/TopGauss.cpp