LIA_RAL: MAPCfg Class Reference
MAPCfg Class Reference
#include <TrainTools.h>
Public Member Functions
MAPCfg (Config &)
String & getMethod ()
void showConfig (ostream &st)
bool getMeanAdapt ()
bool getVarAdapt ()
bool getWeightAdapt ()
double getMeanReg ()
double getVarReg ()
double getWeightReg ()
double getMeanAlpha ()
double getVarAlpha ()
double getWeightAlpha ()
unsigned long getNbTrainIt ()
unsigned long getNbEmIt ()
bool getNormalizeModel ()
bool getNormalizeModelMeanOnly ()
unsigned long getNormalizeModelNbIt ()
double getBaggedFrameProbability ()
void setMethod (String v)
void setMeanAdapt (bool v)
void setVarAdapt (bool v)
void setWeightAdapt (bool v)
void setMeanReg (double v)
void setVarReg (double v)
void setWeightReg (double v)
void setMeanAlpha (double v)
void setVarAlpha (double v)
void setWeightAlpha (double v)
void setNbTrainIt (unsigned long v)
void setNbEmIt (unsigned long v)
void setNormalizeModel (bool v)
void setNormalizeModelMeanOnly (bool v)
void setNormalizeModelNbIt (unsigned long v)
void setBaggedFrameProbability (double v)
Private Attributes
String _method
double _r [3]
bool _mean
bool _var
bool _weight
unsigned long _nbTrainIt
unsigned long _nbEmIt
bool _normalizeModel
bool _normalizeModelMeanOnly
unsigned long _normalizeModelNbIt
double _baggedFrameProbability
Detailed Description
Definition at line 74 of file TrainTools.h.
Constructor & Destructor Documentation
MAPCfg::MAPCfg (Config & config)
Definition at line 110 of file TrainTools.cpp.
References _baggedFrameProbability, _mean, _method, _nbEmIt, _nbTrainIt, _normalizeModel, _normalizeModelMeanOnly, _normalizeModelNbIt, _r, _var, and _weight.
Member Function Documentation
double MAPCfg::getBaggedFrameProbability () inline
Definition at line 102 of file TrainTools.h.
Referenced by adaptModel(), adaptModelEM(), modelBasedadaptModel(), and modelBasedadaptModelEM().
bool MAPCfg::getMeanAdapt () inline
Definition at line 88 of file TrainTools.h.
Referenced by computeMAPConst(), computeMAPConst2(), computeMAPOccDep(), computeModelBasedMAPOccDep(), and modifyMAPConfig().
double MAPCfg::getMeanAlpha () inline
Definition at line 94 of file TrainTools.h.
Referenced by computeMAPConst(), and computeMAPConst2().
double MAPCfg::getMeanReg () inline
Definition at line 91 of file TrainTools.h.
Referenced by computeMAPOccDep(), and computeModelBasedMAPOccDep().
String& MAPCfg::getMethod () inline
Definition at line 86 of file TrainTools.h.
Referenced by adaptModel(), and computeMAP().
unsigned long MAPCfg::getNbEmIt () inline
Definition at line 98 of file TrainTools.h.
Referenced by modelBasedadaptModel(), and modelBasedadaptModelEM().
unsigned long MAPCfg::getNbTrainIt () inline
Definition at line 97 of file TrainTools.h.
Referenced by adaptModel(), adaptModelEM(), and adaptModelMAP().
bool MAPCfg::getNormalizeModel () inline
Definition at line 99 of file TrainTools.h.
Referenced by adaptModel(), adaptModelMAP(), crossValid(), and modelBasedadaptModel().
bool MAPCfg::getNormalizeModelMeanOnly () inline
Definition at line 100 of file TrainTools.h.
Referenced by normalizeMixture().
unsigned long MAPCfg::getNormalizeModelNbIt () inline
Definition at line 101 of file TrainTools.h.
Referenced by normalizeMixture().
bool MAPCfg::getVarAdapt () inline
Definition at line 89 of file TrainTools.h.
Referenced by computeMAPConst(), computeMAPConst2(), computeMAPOccDep(), computeModelBasedMAPOccDep(), and modifyMAPConfig().
double MAPCfg::getVarAlpha () inline
Definition at line 95 of file TrainTools.h.
double MAPCfg::getVarReg () inline
Definition at line 92 of file TrainTools.h.
Referenced by computeMAPOccDep(), and computeModelBasedMAPOccDep().
bool MAPCfg::getWeightAdapt () inline
Definition at line 90 of file TrainTools.h.
Referenced by computeMAPConst(), computeMAPConst2(), computeMAPOccDep(), computeModelBasedMAPOccDep(), and modifyMAPConfig().
double MAPCfg::getWeightAlpha () inline
Definition at line 96 of file TrainTools.h.
double MAPCfg::getWeightReg () inline
Definition at line 93 of file TrainTools.h.
Referenced by computeMAPOccDep(), and computeModelBasedMAPOccDep().
void MAPCfg::setBaggedFrameProbability (double v) inline
Definition at line 118 of file TrainTools.h.
Referenced by clusteringCriterionByAdapt().
void MAPCfg::setMeanAdapt (bool v) inline
Definition at line 104 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::setMeanAlpha (double v) inline
Definition at line 110 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::setMeanReg (double v) inline
Definition at line 107 of file TrainTools.h.
Referenced by clusteringCriterionByAdapt(), and modifyMAPConfig().
void MAPCfg::setMethod (String v) inline
Definition at line 103 of file TrainTools.h.
Referenced by clusteringCriterionByAdapt(), and modifyMAPConfig().
void MAPCfg::setNbEmIt (unsigned long v) inline
Definition at line 114 of file TrainTools.h.
void MAPCfg::setNbTrainIt (unsigned long v) inline
Definition at line 113 of file TrainTools.h.
void MAPCfg::setNormalizeModel (bool v) inline
Definition at line 115 of file TrainTools.h.
void MAPCfg::setNormalizeModelMeanOnly (bool v) inline
Definition at line 116 of file TrainTools.h.
void MAPCfg::setNormalizeModelNbIt (unsigned long v) inline
Definition at line 117 of file TrainTools.h.
void MAPCfg::setVarAdapt (bool v) inline
Definition at line 105 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::setVarAlpha (double v) inline
Definition at line 111 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::setVarReg (double v) inline
Definition at line 108 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::setWeightAdapt (bool v) inline
Definition at line 106 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::setWeightAlpha (double v) inline
Definition at line 112 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::setWeightReg (double v) inline
Definition at line 109 of file TrainTools.h.
Referenced by modifyMAPConfig().
void MAPCfg::showConfig (ostream & st = cout)
Definition at line 148 of file TrainTools.cpp.
References _mean, _method, _nbTrainIt, _normalizeModel, _normalizeModelMeanOnly, _normalizeModelNbIt, _r, _var, and _weight.
Referenced by adaptModel(), computeMAP(), computeMAPOccDep(), computeModelBasedMAPOccDep(), and modelBasedadaptModel().
Member Data Documentation
double MAPCfg::_baggedFrameProbability private
Definition at line 83 of file TrainTools.h.
Referenced by MAPCfg().
bool MAPCfg::_mean private
Definition at line 77 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
String MAPCfg::_method private
Definition at line 75 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
unsigned long MAPCfg::_nbEmIt private
Definition at line 79 of file TrainTools.h.
Referenced by MAPCfg().
unsigned long MAPCfg::_nbTrainIt private
Definition at line 78 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
bool MAPCfg::_normalizeModel private
Definition at line 80 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
bool MAPCfg::_normalizeModelMeanOnly private
Definition at line 81 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
unsigned long MAPCfg::_normalizeModelNbIt private
Definition at line 82 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
double MAPCfg::_r[3] private
Definition at line 76 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
bool MAPCfg::_var private
Definition at line 77 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
bool MAPCfg::_weight private
Definition at line 77 of file TrainTools.h.
Referenced by MAPCfg(), and showConfig().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/TrainTools.h
LIA_SpkTools/src/TrainTools.cpp