LIA_RAL: Eigen::Hyperplane< _Scalar, _AmbientDim > Class Template Reference
Eigen::Hyperplane< _Scalar, _AmbientDim > Class Template Reference
Geometry_Module
A hyperplane.
#include <Hyperplane.h>
Public Types
enum { AmbientDimAtCompileTime = _AmbientDim }
enum { AmbientDimAtCompileTime = _AmbientDim, Options = _Options }
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< Scalar,
AmbientDimAtCompileTime, 1 > VectorType
typedef Matrix< Scalar, int(AmbientDimAtCompileTime)==Dynamic?Dynamic:int(AmbientDimAtCompileTime)+1, 1 > Coefficients
typedef Block< Coefficients,
AmbientDimAtCompileTime, 1 > NormalReturnType
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseIndex Index
typedef Matrix< Scalar,
AmbientDimAtCompileTime, 1 > VectorType
typedef Matrix< Scalar, Index(AmbientDimAtCompileTime)==Dynamic?Dynamic:Index(AmbientDimAtCompileTime)+1,
1, Options > Coefficients
typedef Block< Coefficients,
AmbientDimAtCompileTime, 1 > NormalReturnType
typedef const Block< const
Coefficients,
AmbientDimAtCompileTime, 1 > ConstNormalReturnType
Public Member Functions
Hyperplane ()
Hyperplane (int _dim)
Hyperplane (const VectorType &n, const VectorType &e)
Hyperplane (const VectorType &n, Scalar d)
Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > &parametrized)
~Hyperplane ()
int dim () const
void normalize (void)
Scalar signedDistance (const VectorType &p) const
Scalar absDistance (const VectorType &p) const
VectorType projection (const VectorType &p) const
const NormalReturnType normal () const
NormalReturnType normal ()
const Scalar & offset () const
Scalar & offset ()
const Coefficients & coeffs () const
Coefficients & coeffs ()
VectorType intersection (const Hyperplane &other)
template<typename XprType >
Hyperplane & transform (const MatrixBase< XprType > &mat, TransformTraits traits=Affine)
Hyperplane & transform (const Transform< Scalar, AmbientDimAtCompileTime > &t, TransformTraits traits=Affine)
template<typename NewScalarType >
internal::cast_return_type
< Hyperplane, Hyperplane
< NewScalarType,
AmbientDimAtCompileTime >
>::type cast () const
template<typename OtherScalarType >
Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime > &other)
bool isApprox (const Hyperplane &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
Hyperplane ()
template<int OtherOptions>
Hyperplane (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > &other)
Hyperplane (Index _dim)
Hyperplane (const VectorType &n, const VectorType &e)
Hyperplane (const VectorType &n, Scalar d)
Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > &parametrized)
~Hyperplane ()
Index dim () const
void normalize (void)
Scalar signedDistance (const VectorType &p) const
Scalar absDistance (const VectorType &p) const
VectorType projection (const VectorType &p) const
ConstNormalReturnType normal () const
NormalReturnType normal ()
const Scalar & offset () const
Scalar & offset ()
const Coefficients & coeffs () const
Coefficients & coeffs ()
VectorType intersection (const Hyperplane &other) const
template<typename XprType >
Hyperplane & transform (const MatrixBase< XprType > &mat, TransformTraits traits=Affine)
template<int TrOptions>
Hyperplane & transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > &t, TransformTraits traits=Affine)
template<typename NewScalarType >
internal::cast_return_type
< Hyperplane, Hyperplane
< NewScalarType,
AmbientDimAtCompileTime,
Options > >::type cast () const
template<typename OtherScalarType , int OtherOptions>
Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
template<int OtherOptions>
bool isApprox (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
Static Public Member Functions
static Hyperplane Through (const VectorType &p0, const VectorType &p1)
static Hyperplane Through (const VectorType &p0, const VectorType &p1, const VectorType &p2)
static Hyperplane Through (const VectorType &p0, const VectorType &p1)
static Hyperplane Through (const VectorType &p0, const VectorType &p1, const VectorType &p2)
Protected Attributes
Coefficients m_coeffs
Detailed Description
template<typename _Scalar, int _AmbientDim>
class Eigen::Hyperplane< _Scalar, _AmbientDim >
A hyperplane.
A hyperplane is an affine subspace of dimension n-1 in a space of dimension n. For example, a hyperplane in a plane is a line; a hyperplane in 3-space is a plane.
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic. Notice that the dimension of the hyperplane is _AmbientDim-1.
This class represents an hyperplane as the zero set of the implicit equation where is a unit normal vector of the plane (linear part) and is the distance (offset) to the origin.
Definition at line 33 of file Hyperplane.h.
Member Typedef Documentation
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,int(AmbientDimAtCompileTime)==Dynamic ? Dynamic : int(AmbientDimAtCompileTime)+1,1> Eigen::Hyperplane< _Scalar, _AmbientDim >::Coefficients
Definition at line 43 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,Index(AmbientDimAtCompileTime)==Dynamic ? Dynamic : Index(AmbientDimAtCompileTime)+1,1,Options> Eigen::Hyperplane< _Scalar, _AmbientDim >::Coefficients
Definition at line 48 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef const Block<const Coefficients,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim >::ConstNormalReturnType
Definition at line 50 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef DenseIndex Eigen::Hyperplane< _Scalar, _AmbientDim >::Index
Definition at line 44 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef Block<Coefficients,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim >::NormalReturnType
Definition at line 44 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef Block<Coefficients,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim >::NormalReturnType
Definition at line 49 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef NumTraits<Scalar>::Real Eigen::Hyperplane< _Scalar, _AmbientDim >::RealScalar
Definition at line 39 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef NumTraits<Scalar>::Real Eigen::Hyperplane< _Scalar, _AmbientDim >::RealScalar
Definition at line 43 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef _Scalar Eigen::Hyperplane< _Scalar, _AmbientDim >::Scalar
Definition at line 38 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef _Scalar Eigen::Hyperplane< _Scalar, _AmbientDim >::Scalar
Definition at line 42 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim >::VectorType
Definition at line 40 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,AmbientDimAtCompileTime,1> Eigen::Hyperplane< _Scalar, _AmbientDim >::VectorType
Definition at line 45 of file Hyperplane.h.
Member Enumeration Documentation
template<typename _Scalar, int _AmbientDim> anonymous enum
Enumerator
AmbientDimAtCompileTime
Definition at line 37 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> anonymous enum
Enumerator
AmbientDimAtCompileTime
Options
Definition at line 38 of file Hyperplane.h.
Constructor & Destructor Documentation
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane () inline explicit
Default constructor without initialization
Definition at line 47 of file Hyperplane.h.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::cast().
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (int _dim) inline explicit
Constructs a dynamic-size hyperplane with _dim the dimension of the ambient space
Definition at line 51 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const VectorType & n, const VectorType & e) inline
Construct a plane from its normal n and a point e onto the plane.
Warning
the vector normal is assumed to be normalized.
Definition at line 56 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const VectorType & n, Scalar d) inline
Constructs a plane from its normal n and distance to the origin d such that the algebraic equation of the plane is .
Warning
the vector normal is assumed to be normalized.
Definition at line 67 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > & parametrized) inline explicit
Constructs a hyperplane passing through the parametrized line parametrized. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
Definition at line 102 of file Hyperplane.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim >::offset(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin().
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::~Hyperplane () inline
Definition at line 108 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> template<typename OtherScalarType > Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 239 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane () inline explicit
Default constructor without initialization
Definition at line 53 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > & other) inline
Definition at line 56 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (Index _dim) inline explicit
Constructs a dynamic-size hyperplane with _dim the dimension of the ambient space
Definition at line 62 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const VectorType & n, const VectorType & e) inline
Construct a plane from its normal n and a point e onto the plane.
Warning
the vector normal is assumed to be normalized.
Definition at line 67 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const VectorType & n, Scalar d) inline
Constructs a plane from its normal n and distance to the origin d such that the algebraic equation of the plane is .
Warning
the vector normal is assumed to be normalized.
Definition at line 78 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > & parametrized) inline explicit
Constructs a hyperplane passing through the parametrized line parametrized. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
Definition at line 113 of file Hyperplane.h.
References Eigen::ParametrizedLine< _Scalar, _AmbientDim >::direction(), Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim >::offset(), and Eigen::ParametrizedLine< _Scalar, _AmbientDim >::origin().
template<typename _Scalar, int _AmbientDim> Eigen::Hyperplane< _Scalar, _AmbientDim >::~Hyperplane () inline
Definition at line 119 of file Hyperplane.h.
template<typename _Scalar, int _AmbientDim> template<typename OtherScalarType , int OtherOptions> Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 251 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
Member Function Documentation
template<typename _Scalar, int _AmbientDim> Scalar Eigen::Hyperplane< _Scalar, _AmbientDim >::absDistance (const VectorType & p) const inline
Returns
the absolute distance between the plane *this and a point p.
See Also
signedDistance()
Definition at line 127 of file Hyperplane.h.
References Eigen::ei_abs(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance().
template<typename _Scalar, int _AmbientDim> Scalar Eigen::Hyperplane< _Scalar, _AmbientDim >::absDistance (const VectorType & p) const inline
Returns
the absolute distance between the plane *this and a point p.
See Also
signedDistance()
Definition at line 138 of file Hyperplane.h.
References abs(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance().
template<typename _Scalar, int _AmbientDim> template<typename NewScalarType > internal::cast_return_type<Hyperplane, Hyperplane<NewScalarType,AmbientDimAtCompileTime> >::type Eigen::Hyperplane< _Scalar, _AmbientDim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 231 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane().
template<typename _Scalar, int _AmbientDim> template<typename NewScalarType > internal::cast_return_type<Hyperplane, Hyperplane<NewScalarType,AmbientDimAtCompileTime,Options> >::type Eigen::Hyperplane< _Scalar, _AmbientDim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 243 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane().
template<typename _Scalar, int _AmbientDim> const Coefficients& Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs () const inline
Returns
a constant reference to the coefficients c_i of the plane equation:
Definition at line 155 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::intersection().
template<typename _Scalar, int _AmbientDim> Coefficients& Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs () inline
Returns
a non-constant reference to the coefficients c_i of the plane equation:
Definition at line 160 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> const Coefficients& Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs () const inline
Returns
a constant reference to the coefficients c_i of the plane equation:
Definition at line 166 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> Coefficients& Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs () inline
Returns
a non-constant reference to the coefficients c_i of the plane equation:
Definition at line 171 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> int Eigen::Hyperplane< _Scalar, _AmbientDim >::dim () const inline
Returns
the dimension in which the plane holds
Definition at line 111 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::AmbientDimAtCompileTime, Eigen::Dynamic, and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> Index Eigen::Hyperplane< _Scalar, _AmbientDim >::dim () const inline
Returns
the dimension in which the plane holds
Definition at line 122 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::AmbientDimAtCompileTime, Eigen::Dynamic, and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> VectorType Eigen::Hyperplane< _Scalar, _AmbientDim >::intersection (const Hyperplane< _Scalar, _AmbientDim > & other) inline
Returns
the intersection of *this with other.
Warning
The ambient space must be a plane, i.e. have dimension 2, so that *this and other are lines.
Note
If other is approximately parallel to *this, this method will return any point on *this.
Definition at line 168 of file Hyperplane.h.
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs(), Eigen::ei_abs(), Eigen::ei_isMuchSmallerThan(), and EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
template<typename _Scalar, int _AmbientDim> VectorType Eigen::Hyperplane< _Scalar, _AmbientDim >::intersection (const Hyperplane< _Scalar, _AmbientDim > & other) const inline
Returns
the intersection of *this with other.
Warning
The ambient space must be a plane, i.e. have dimension 2, so that *this and other are lines.
Note
If other is approximately parallel to *this, this method will return any point on *this.
Definition at line 179 of file Hyperplane.h.
References abs(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::internal::isMuchSmallerThan().
template<typename _Scalar, int _AmbientDim> bool Eigen::Hyperplane< _Scalar, _AmbientDim >::isApprox (const Hyperplane< _Scalar, _AmbientDim > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 246 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> template<int OtherOptions> bool Eigen::Hyperplane< _Scalar, _AmbientDim >::isApprox (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 259 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> const NormalReturnType Eigen::Hyperplane< _Scalar, _AmbientDim >::normal () const inline
Returns
a constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
Definition at line 136 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersection(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersectionParameter(), Eigen::Hyperplane< _Scalar, _AmbientDim >::normalize(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine(), Eigen::Hyperplane< _Scalar, _AmbientDim >::projection(), Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance(), Eigen::Hyperplane< _Scalar, _AmbientDim >::Through(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::transform().
template<typename _Scalar, int _AmbientDim> NormalReturnType Eigen::Hyperplane< _Scalar, _AmbientDim >::normal () inline
Returns
a non-constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
Definition at line 141 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> ConstNormalReturnType Eigen::Hyperplane< _Scalar, _AmbientDim >::normal () const inline
Returns
a constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
Definition at line 147 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> NormalReturnType Eigen::Hyperplane< _Scalar, _AmbientDim >::normal () inline
Returns
a non-constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
Definition at line 152 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> void Eigen::Hyperplane< _Scalar, _AmbientDim >::normalize (void) inline
normalizes *this
Definition at line 114 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs, and Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
template<typename _Scalar, int _AmbientDim> void Eigen::Hyperplane< _Scalar, _AmbientDim >::normalize (void) inline
normalizes *this
Definition at line 125 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs, and Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
template<typename _Scalar, int _AmbientDim> const Scalar& Eigen::Hyperplane< _Scalar, _AmbientDim >::offset () const inline
Returns
the distance to the origin, which is also the "constant term" of the implicit equation
Warning
the vector normal is assumed to be normalized.
Definition at line 146 of file Hyperplane.h.
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersection(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::intersectionParameter(), Eigen::ParametrizedLine< _Scalar, _AmbientDim >::ParametrizedLine(), Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::transform().
template<typename _Scalar, int _AmbientDim> Scalar& Eigen::Hyperplane< _Scalar, _AmbientDim >::offset () inline
Returns
a non-constant reference to the distance to the origin, which is also the constant part of the implicit equation
Definition at line 150 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> const Scalar& Eigen::Hyperplane< _Scalar, _AmbientDim >::offset () const inline
Returns
the distance to the origin, which is also the "constant term" of the implicit equation
Warning
the vector normal is assumed to be normalized.
Definition at line 157 of file Hyperplane.h.
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> Scalar& Eigen::Hyperplane< _Scalar, _AmbientDim >::offset () inline
Returns
a non-constant reference to the distance to the origin, which is also the constant part of the implicit equation
Definition at line 161 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs.
template<typename _Scalar, int _AmbientDim> VectorType Eigen::Hyperplane< _Scalar, _AmbientDim >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the plane *this.
Definition at line 131 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance().
template<typename _Scalar, int _AmbientDim> VectorType Eigen::Hyperplane< _Scalar, _AmbientDim >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the plane *this.
Definition at line 142 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance().
template<typename _Scalar, int _AmbientDim> Scalar Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance (const VectorType & p) const inline
Returns
the signed distance between the plane *this and a point p.
See Also
absDistance()
Definition at line 122 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::absDistance(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::projection().
template<typename _Scalar, int _AmbientDim> Scalar Eigen::Hyperplane< _Scalar, _AmbientDim >::signedDistance (const VectorType & p) const inline
Returns
the signed distance between the plane *this and a point p.
See Also
absDistance()
Definition at line 133 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
template<typename _Scalar, int _AmbientDim> static Hyperplane Eigen::Hyperplane< _Scalar, _AmbientDim >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a hyperplane passing through the two points. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
Definition at line 77 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
template<typename _Scalar, int _AmbientDim> static Hyperplane Eigen::Hyperplane< _Scalar, _AmbientDim >::Through (const VectorType & p0, const VectorType & p1, const VectorType & p2) inline static
Constructs a hyperplane passing through the three points. The dimension of the ambient space is required to be exactly 3.
Definition at line 88 of file Hyperplane.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
template<typename _Scalar, int _AmbientDim> static Hyperplane Eigen::Hyperplane< _Scalar, _AmbientDim >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a hyperplane passing through the two points. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
Definition at line 88 of file Hyperplane.h.
References Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
template<typename _Scalar, int _AmbientDim> static Hyperplane Eigen::Hyperplane< _Scalar, _AmbientDim >::Through (const VectorType & p0, const VectorType & p1, const VectorType & p2) inline static
Constructs a hyperplane passing through the three points. The dimension of the ambient space is required to be exactly 3.
Definition at line 99 of file Hyperplane.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
template<typename _Scalar, int _AmbientDim> template<typename XprType > Hyperplane& Eigen::Hyperplane< _Scalar, _AmbientDim >::transform (const MatrixBase< XprType > & mat, TransformTraits traits = Affine) inline
Applies the transformation matrix mat to *this and returns a reference to *this.
Parameters
mat the Dim x Dim transformation matrix
traits specifies whether the matrix mat represents an Isometry or a more generic Affine transformation. The default is Affine.
Definition at line 196 of file Hyperplane.h.
References Eigen::Affine, ei_assert, Eigen::MatrixBase< Derived >::inverse(), Eigen::Isometry, and Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::transform().
template<typename _Scalar, int _AmbientDim> template<typename XprType > Hyperplane& Eigen::Hyperplane< _Scalar, _AmbientDim >::transform (const MatrixBase< XprType > & mat, TransformTraits traits = Affine) inline
Applies the transformation matrix mat to *this and returns a reference to *this.
Parameters
mat the Dim x Dim transformation matrix
traits specifies whether the matrix mat represents an Isometry or a more generic Affine transformation. The default is Affine.
Definition at line 207 of file Hyperplane.h.
References Eigen::Affine, eigen_assert, Eigen::MatrixBase< Derived >::inverse(), Eigen::Isometry, and Eigen::Hyperplane< _Scalar, _AmbientDim >::normal().
template<typename _Scalar, int _AmbientDim> Hyperplane& Eigen::Hyperplane< _Scalar, _AmbientDim >::transform (const Transform< Scalar, AmbientDimAtCompileTime > & t, TransformTraits traits = Affine) inline
Applies the transformation t to *this and returns a reference to *this.
Parameters
t the transformation of dimension Dim
traits specifies whether the transformation t represents an Isometry or a more generic Affine transformation. The default is Affine. Other kind of transformations are not supported.
Definition at line 216 of file Hyperplane.h.
References Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim >::offset(), Eigen::Hyperplane< _Scalar, _AmbientDim >::transform(), and Eigen::Transform< _Scalar, _Dim >::translation().
template<typename _Scalar, int _AmbientDim> template<int TrOptions> Hyperplane& Eigen::Hyperplane< _Scalar, _AmbientDim >::transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > & t, TransformTraits traits = Affine) inline
Applies the transformation t to *this and returns a reference to *this.
Parameters
t the transformation of dimension Dim
traits specifies whether the transformation t represents an Isometry or a more generic Affine transformation. The default is Affine. Other kind of transformations are not supported.
Definition at line 228 of file Hyperplane.h.
References Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim >::offset(), Eigen::Hyperplane< _Scalar, _AmbientDim >::transform(), and Eigen::Transform< _Scalar, _Dim >::translation().
Member Data Documentation
template<typename _Scalar, int _AmbientDim> Coefficients Eigen::Hyperplane< _Scalar, _AmbientDim >::m_coeffs protected
Definition at line 251 of file Hyperplane.h.
Referenced by Eigen::Hyperplane< _Scalar, _AmbientDim >::coeffs(), Eigen::Hyperplane< _Scalar, _AmbientDim >::dim(), Eigen::Hyperplane< _Scalar, _AmbientDim >::Hyperplane(), Eigen::Hyperplane< _Scalar, _AmbientDim >::isApprox(), Eigen::Hyperplane< _Scalar, _AmbientDim >::normal(), Eigen::Hyperplane< _Scalar, _AmbientDim >::normalize(), and Eigen::Hyperplane< _Scalar, _AmbientDim >::offset().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigen2Support/Geometry/Hyperplane.h