LIA_RAL: Eigen::SuperLU< _MatrixType > Class Template Reference
Eigen::SuperLU< _MatrixType > Class Template Reference
A sparse direct LU factorization and solver based on the SuperLU library.
#include <SuperLUSupport.h>
Public Types
typedef SuperLUBase
< _MatrixType, SuperLU > Base
typedef _MatrixType MatrixType
typedef Base::Scalar Scalar
typedef Base::RealScalar RealScalar
typedef Base::Index Index
typedef Base::IntRowVectorType IntRowVectorType
typedef Base::IntColVectorType IntColVectorType
typedef Base::LUMatrixType LUMatrixType
typedef TriangularView
< LUMatrixType, Lower|UnitDiag > LMatrixType
typedef TriangularView
< LUMatrixType, Upper > UMatrixType
Public Types inherited from Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
Dynamic, 1 > Vector
typedef Matrix< int,
1, MatrixType::ColsAtCompileTime > IntRowVectorType
typedef Matrix< int,
MatrixType::RowsAtCompileTime, 1 > IntColVectorType
typedef SparseMatrix< Scalar > LUMatrixType
Public Member Functions
SuperLU ()
SuperLU (const MatrixType &matrix)
~SuperLU ()
void analyzePattern (const MatrixType &matrix)
void factorize (const MatrixType &matrix)
template<typename Rhs , typename Dest >
void _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
const LMatrixType & matrixL () const
const UMatrixType & matrixU () const
const IntColVectorType & permutationP () const
const IntRowVectorType & permutationQ () const
Scalar determinant () const
Public Member Functions inherited from Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >
SuperLUBase ()
~SuperLUBase ()
SuperLU< _MatrixType > & derived ()
const SuperLU< _MatrixType > & derived () const
Index rows () const
Index cols () const
superlu_options_t & options ()
ComputationInfo info () const
Reports whether previous computation was successful.
void compute (const MatrixType &matrix)
const internal::solve_retval
< SuperLUBase, Rhs > solve (const MatrixBase< Rhs > &b) const
void analyzePattern (const MatrixType &)
void dumpMemory (Stream &s)
Protected Member Functions
void init ()
Protected Member Functions inherited from Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >
void initFactorization (const MatrixType &a)
void init ()
void extractData () const
void clearFactors ()
Private Member Functions
SuperLU (SuperLU &)
Additional Inherited Members
Protected Attributes inherited from Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >
LUMatrixType m_l
LUMatrixType m_u
IntColVectorType m_p
IntRowVectorType m_q
LUMatrixType m_matrix
SluMatrix m_sluA
SuperMatrix m_sluL
SuperMatrix m_sluU
SluMatrix m_sluB
SluMatrix m_sluX
SuperLUStat_t m_sluStat
superlu_options_t m_sluOptions
std::vector< int > m_sluEtree
Matrix< RealScalar, Dynamic, 1 > m_sluRscale
Matrix< RealScalar, Dynamic, 1 > m_sluCscale
Matrix< RealScalar, Dynamic, 1 > m_sluFerr
Matrix< RealScalar, Dynamic, 1 > m_sluBerr
char m_sluEqued
ComputationInfo m_info
bool m_isInitialized
int m_factorizationIsOk
int m_analysisIsOk
bool m_extractedDataAreDirty
Detailed Description
template<typename _MatrixType>
class Eigen::SuperLU< _MatrixType >
A sparse direct LU factorization and solver based on the SuperLU library.
This class allows to solve for A.X = B sparse linear problems via a direct LU factorization using the SuperLU library. The sparse matrix A must be squared and invertible. The vectors or matrices X and B can be either dense or sparse.
Template Parameters
_MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
See Also
TutorialSparseDirectSolvers
Definition at line 479 of file SuperLUSupport.h.
Member Typedef Documentation
template<typename _MatrixType> typedef SuperLUBase<_MatrixType,SuperLU> Eigen::SuperLU< _MatrixType >::Base
Definition at line 482 of file SuperLUSupport.h.
template<typename _MatrixType> typedef Base::Index Eigen::SuperLU< _MatrixType >::Index
Definition at line 486 of file SuperLUSupport.h.
template<typename _MatrixType> typedef Base::IntColVectorType Eigen::SuperLU< _MatrixType >::IntColVectorType
Definition at line 488 of file SuperLUSupport.h.
template<typename _MatrixType> typedef Base::IntRowVectorType Eigen::SuperLU< _MatrixType >::IntRowVectorType
Definition at line 487 of file SuperLUSupport.h.
template<typename _MatrixType> typedef TriangularView<LUMatrixType, Lower|UnitDiag> Eigen::SuperLU< _MatrixType >::LMatrixType
Definition at line 490 of file SuperLUSupport.h.
template<typename _MatrixType> typedef Base::LUMatrixType Eigen::SuperLU< _MatrixType >::LUMatrixType
Definition at line 489 of file SuperLUSupport.h.
template<typename _MatrixType> typedef _MatrixType Eigen::SuperLU< _MatrixType >::MatrixType
Definition at line 483 of file SuperLUSupport.h.
template<typename _MatrixType> typedef Base::RealScalar Eigen::SuperLU< _MatrixType >::RealScalar
Definition at line 485 of file SuperLUSupport.h.
template<typename _MatrixType> typedef Base::Scalar Eigen::SuperLU< _MatrixType >::Scalar
Definition at line 484 of file SuperLUSupport.h.
template<typename _MatrixType> typedef TriangularView<LUMatrixType, Upper> Eigen::SuperLU< _MatrixType >::UMatrixType
Definition at line 491 of file SuperLUSupport.h.
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::SuperLU< _MatrixType >::SuperLU () inline
Definition at line 495 of file SuperLUSupport.h.
References Eigen::SuperLU< _MatrixType >::init().
template<typename _MatrixType> Eigen::SuperLU< _MatrixType >::SuperLU (const MatrixType & matrix) inline
Definition at line 497 of file SuperLUSupport.h.
References Eigen::SuperLUBase< _MatrixType, Derived >::compute(), and Eigen::SuperLU< _MatrixType >::init().
template<typename _MatrixType> Eigen::SuperLU< _MatrixType >::~SuperLU () inline
Definition at line 503 of file SuperLUSupport.h.
template<typename _MatrixType> Eigen::SuperLU< _MatrixType >::SuperLU (SuperLU< _MatrixType > &) inline private
Definition at line 600 of file SuperLUSupport.h.
Member Function Documentation
template<typename MatrixType > template<typename Rhs , typename Dest > void Eigen::SuperLU< MatrixType >::_solve (const MatrixBase< Rhs > & b, MatrixBase< Dest > & dest) const
Definition at line 639 of file SuperLUSupport.h.
References eigen_assert, info(), Eigen::SluMatrix::Map(), Eigen::NumericalIssue, and Eigen::Success.
template<typename _MatrixType> void Eigen::SuperLU< _MatrixType >::analyzePattern (const MatrixType & matrix) inline
Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See Also
factorize()
Definition at line 513 of file SuperLUSupport.h.
References Eigen::SuperLUBase< _MatrixType, Derived >::analyzePattern(), Eigen::InvalidInput, Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_info, and Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_isInitialized.
template<typename MatrixType > SuperLU< MatrixType >::Scalar Eigen::SuperLU< MatrixType >::determinant () const
Definition at line 775 of file SuperLUSupport.h.
References eigen_assert.
template<typename MatrixType > void Eigen::SuperLU< MatrixType >::factorize (const MatrixType & matrix)
Performs a numeric decomposition of matrix
The given matrix must has the same sparcity than the matrix on which the symbolic decomposition has been performed.
See Also
analyzePattern()
Definition at line 604 of file SuperLUSupport.h.
References eigen_assert, info(), Eigen::InvalidInput, Eigen::NumericalIssue, and Eigen::Success.
template<typename _MatrixType> void Eigen::SuperLU< _MatrixType >::init () inline protected
Definition at line 587 of file SuperLUSupport.h.
References Eigen::SuperLUBase< _MatrixType, Derived >::init(), and Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_sluOptions.
Referenced by Eigen::SuperLU< _MatrixType >::SuperLU().
template<typename _MatrixType> const LMatrixType& Eigen::SuperLU< _MatrixType >::matrixL () const inline
Definition at line 534 of file SuperLUSupport.h.
References Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::extractData(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_extractedDataAreDirty, and Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_l.
template<typename _MatrixType> const UMatrixType& Eigen::SuperLU< _MatrixType >::matrixU () const inline
Definition at line 540 of file SuperLUSupport.h.
References Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::extractData(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_extractedDataAreDirty, and Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_u.
template<typename _MatrixType> const IntColVectorType& Eigen::SuperLU< _MatrixType >::permutationP () const inline
Definition at line 546 of file SuperLUSupport.h.
References Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::extractData(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_extractedDataAreDirty, and Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_p.
template<typename _MatrixType> const IntRowVectorType& Eigen::SuperLU< _MatrixType >::permutationQ () const inline
Definition at line 552 of file SuperLUSupport.h.
References Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::extractData(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_extractedDataAreDirty, and Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::m_q.
The documentation for this class was generated from the following file:
include/Eigen/src/SuperLUSupport/SuperLUSupport.h