LIA_RAL: Eigen::Translation< Scalar, Dim > Class Template Reference
Eigen::Translation< Scalar, Dim > Class Template Reference
Geometry_Module
Represents a translation transformation.
#include <ForwardDeclarations.h>
Public Types
enum { Dim = _Dim }
enum { Dim = _Dim }
typedef _Scalar Scalar
typedef Matrix< Scalar, Dim, 1 > VectorType
typedef Matrix< Scalar, Dim, Dim > LinearMatrixType
typedef Scaling< Scalar, Dim > ScalingType
typedef Transform< Scalar, Dim > TransformType
typedef _Scalar Scalar
typedef Matrix< Scalar, Dim, 1 > VectorType
typedef Matrix< Scalar, Dim, Dim > LinearMatrixType
typedef Transform< Scalar, Dim,
Affine > AffineTransformType
typedef Transform< Scalar, Dim,
Isometry > IsometryTransformType
Public Member Functions
Translation ()
Translation (const Scalar &sx, const Scalar &sy)
Translation (const Scalar &sx, const Scalar &sy, const Scalar &sz)
Translation (const VectorType &vector)
const VectorType & vector () const
VectorType & vector ()
Translation operator* (const Translation &other) const
TransformType operator* (const ScalingType &other) const
TransformType operator* (const LinearMatrixType &linear) const
template<typename Derived >
TransformType operator* (const RotationBase< Derived, Dim > &r) const
TransformType operator* (const TransformType &t) const
VectorType operator* (const VectorType &other) const
Translation inverse () const
Translation & operator= (const Translation &other)
template<typename NewScalarType >
internal::cast_return_type
< Translation, Translation
< NewScalarType, Dim > >::type cast () const
template<typename OtherScalarType >
Translation (const Translation< OtherScalarType, Dim > &other)
bool isApprox (const Translation &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
Translation ()
Translation (const Scalar &sx, const Scalar &sy)
Translation (const Scalar &sx, const Scalar &sy, const Scalar &sz)
Translation (const VectorType &vector)
Scalar x () const
Retruns the x-translation by value.
Scalar y () const
Retruns the y-translation by value.
Scalar z () const
Retruns the z-translation by value.
Scalar & x ()
Retruns the x-translation as a reference.
Scalar & y ()
Retruns the y-translation as a reference.
Scalar & z ()
Retruns the z-translation as a reference.
const VectorType & vector () const
VectorType & vector ()
const VectorType & translation () const
VectorType & translation ()
Translation operator* (const Translation &other) const
AffineTransformType operator* (const UniformScaling< Scalar > &other) const
template<typename OtherDerived >
AffineTransformType operator* (const EigenBase< OtherDerived > &linear) const
template<typename Derived >
IsometryTransformType operator* (const RotationBase< Derived, Dim > &r) const
template<int Mode, int Options>
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
VectorType operator* (const VectorType &other) const
Translation inverse () const
Translation & operator= (const Translation &other)
template<typename NewScalarType >
internal::cast_return_type
< Translation, Translation
< NewScalarType, Dim > >::type cast () const
template<typename OtherScalarType >
Translation (const Translation< OtherScalarType, Dim > &other)
bool isApprox (const Translation &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived>
Translation< Scalar, Dim >
::AffineTransformType operator* (const EigenBase< OtherDerived > &linear) const
Static Public Member Functions
static const Translation Identity ()
Protected Attributes
VectorType m_coeffs
Friends
TransformType operator* (const LinearMatrixType &linear, const Translation &t)
template<typename OtherDerived >
AffineTransformType operator* (const EigenBase< OtherDerived > &linear, const Translation &t)
Detailed Description
template<typename Scalar, int Dim>
class Eigen::Translation< Scalar, Dim >
Represents a translation transformation.
Parameters
_Scalar the scalar type, i.e., the type of the coefficients.
_Dim the dimension of the space, can be a compile time value or Dynamic
Note
This class is not aimed to be used to store a translation transformation, but rather to make easier the constructions and updates of Transform objects.
See Also
class Scaling, class Transform
Definition at line 237 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename Scalar, int Dim> typedef Transform<Scalar,Dim,Affine> Eigen::Translation< Scalar, Dim >::AffineTransformType
corresponding affine transformation type
Definition at line 43 of file Translation.h.
template<typename Scalar, int Dim> typedef Transform<Scalar,Dim,Isometry> Eigen::Translation< Scalar, Dim >::IsometryTransformType
corresponding isometric transformation type
Definition at line 45 of file Translation.h.
template<typename Scalar, int Dim> typedef Matrix<Scalar,Dim,Dim> Eigen::Translation< Scalar, Dim >::LinearMatrixType
corresponding linear transformation matrix type
Definition at line 40 of file Translation.h.
template<typename Scalar, int Dim> typedef Matrix<Scalar,Dim,Dim> Eigen::Translation< Scalar, Dim >::LinearMatrixType
corresponding linear transformation matrix type
Definition at line 41 of file Translation.h.
template<typename Scalar, int Dim> typedef _Scalar Eigen::Translation< Scalar, Dim >::Scalar
the scalar type of the coefficients
Definition at line 36 of file Translation.h.
template<typename Scalar, int Dim> typedef _Scalar Eigen::Translation< Scalar, Dim >::Scalar
the scalar type of the coefficients
Definition at line 37 of file Translation.h.
template<typename Scalar, int Dim> typedef Scaling<Scalar,Dim> Eigen::Translation< Scalar, Dim >::ScalingType
corresponding scaling transformation type
Definition at line 42 of file Translation.h.
template<typename Scalar, int Dim> typedef Transform<Scalar,Dim> Eigen::Translation< Scalar, Dim >::TransformType
corresponding affine transformation type
Definition at line 44 of file Translation.h.
template<typename Scalar, int Dim> typedef Matrix<Scalar,Dim,1> Eigen::Translation< Scalar, Dim >::VectorType
corresponding vector type
Definition at line 38 of file Translation.h.
template<typename Scalar, int Dim> typedef Matrix<Scalar,Dim,1> Eigen::Translation< Scalar, Dim >::VectorType
corresponding vector type
Definition at line 39 of file Translation.h.
Member Enumeration Documentation
template<typename Scalar, int Dim> anonymous enum
dimension of the space
Enumerator
Dim
Definition at line 34 of file Translation.h.
template<typename Scalar, int Dim> anonymous enum
dimension of the space
Enumerator
Dim
Definition at line 35 of file Translation.h.
Constructor & Destructor Documentation
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation () inline
Default constructor without initialization.
Definition at line 53 of file Translation.h.
Referenced by Eigen::Translation< Scalar, Dim >::Identity(), Eigen::Translation< Scalar, Dim >::inverse(), and Eigen::Translation< Scalar, Dim >::operator*().
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation (const Scalar & sx, const Scalar & sy) inline
Definition at line 55 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::Dim, ei_assert, and Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation (const Scalar & sx, const Scalar & sy, const Scalar & sz) inline
Definition at line 62 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::Dim, ei_assert, and Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation (const VectorType & vector) inline explicit
Constructs and initialize the scaling transformation from a vector of scaling coefficients
Definition at line 70 of file Translation.h.
template<typename Scalar, int Dim> template<typename OtherScalarType > Eigen::Translation< Scalar, Dim >::Translation (const Translation< OtherScalarType, Dim > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 129 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation () inline
Default constructor without initialization.
Definition at line 54 of file Translation.h.
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation (const Scalar & sx, const Scalar & sy) inline
Definition at line 56 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::Dim, eigen_assert, and Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation (const Scalar & sx, const Scalar & sy, const Scalar & sz) inline
Definition at line 63 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::Dim, eigen_assert, and Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Eigen::Translation< Scalar, Dim >::Translation (const VectorType & vector) inline explicit
Constructs and initialize the translation transformation from a vector of translation coefficients
Definition at line 71 of file Translation.h.
template<typename Scalar, int Dim> template<typename OtherScalarType > Eigen::Translation< Scalar, Dim >::Translation (const Translation< OtherScalarType, Dim > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 158 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
Member Function Documentation
template<typename Scalar, int Dim> template<typename NewScalarType > internal::cast_return_type<Translation,Translation<NewScalarType,Dim> >::type Eigen::Translation< Scalar, Dim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 124 of file Translation.h.
template<typename Scalar, int Dim> template<typename NewScalarType > internal::cast_return_type<Translation,Translation<NewScalarType,Dim> >::type Eigen::Translation< Scalar, Dim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 153 of file Translation.h.
template<typename Scalar, int Dim> static const Translation Eigen::Translation< Scalar, Dim >::Identity () inline static
Definition at line 145 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::Translation().
template<typename Scalar, int Dim> Translation Eigen::Translation< Scalar, Dim >::inverse (void) const inline
Returns
the inverse translation (opposite)
Definition at line 110 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs, and Eigen::Translation< Scalar, Dim >::Translation().
template<typename Scalar, int Dim> Translation Eigen::Translation< Scalar, Dim >::inverse (void) const inline
Returns
the inverse translation (opposite)
Definition at line 137 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs, and Eigen::Translation< Scalar, Dim >::Translation().
template<typename Scalar, int Dim> bool Eigen::Translation< Scalar, Dim >::isApprox (const Translation< Scalar, Dim > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 136 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> bool Eigen::Translation< Scalar, Dim >::isApprox (const Translation< Scalar, Dim > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 165 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Translation Eigen::Translation< Scalar, Dim >::operator* (const Translation< Scalar, Dim > & other) const inline
Concatenates two translation
Definition at line 76 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs, and Eigen::Translation< Scalar, Dim >::Translation().
template<typename Scalar , int Dim> Translation< Scalar, Dim >::TransformType Eigen::Translation< Scalar, Dim >::operator* (const ScalingType & other) const inline
Concatenates a translation and a scaling
Definition at line 152 of file Translation.h.
References Eigen::Scaling< _Scalar, _Dim >::coeffs(), Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Transform< _Scalar, _Dim >::matrix(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Transform< _Scalar, _Dim >::translation().
template<typename Scalar , int Dim> Translation< Scalar, Dim >::TransformType Eigen::Translation< Scalar, Dim >::operator* (const LinearMatrixType & linear) const inline
Concatenates a translation and a linear transformation
Definition at line 164 of file Translation.h.
References Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Transform< _Scalar, _Dim >::matrix(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Transform< _Scalar, _Dim >::translation().
template<typename Scalar, int Dim> template<typename Derived > TransformType Eigen::Translation< Scalar, Dim >::operator* (const RotationBase< Derived, Dim > & r) const inline
Definition at line 86 of file Translation.h.
References Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
template<typename Scalar, int Dim> Translation Eigen::Translation< Scalar, Dim >::operator* (const Translation< Scalar, Dim > & other) const inline
Concatenates two translation
Definition at line 94 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs, and Eigen::Translation< Scalar, Dim >::Translation().
template<typename Scalar , int Dim> Translation< Scalar, Dim >::AffineTransformType Eigen::Translation< Scalar, Dim >::operator* (const UniformScaling< Scalar > & other) const inline
Concatenates a translation and a uniform scaling
Definition at line 180 of file Translation.h.
References Eigen::UniformScaling< _Scalar >::factor(), Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Transform< _Scalar, _Dim >::matrix(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Transform< _Scalar, _Dim >::translation().
template<typename Scalar, int Dim> template<typename OtherDerived > AffineTransformType Eigen::Translation< Scalar, Dim >::operator* (const EigenBase< OtherDerived > & linear) const inline
Concatenates a translation and a linear transformation
template<typename Scalar , int Dim> Translation< Scalar, Dim >::TransformType Eigen::Translation< Scalar, Dim >::operator* (const TransformType & t) const inline
Concatenates a translation and an affine transformation
Definition at line 177 of file Translation.h.
References Eigen::Transform< _Scalar, _Dim >::pretranslate().
template<typename Scalar, int Dim> VectorType Eigen::Translation< Scalar, Dim >::operator* (const VectorType & other) const inline
Applies translation to vector
Definition at line 106 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> template<typename Derived > IsometryTransformType Eigen::Translation< Scalar, Dim >::operator* (const RotationBase< Derived, Dim > & r) const inline
Concatenates a translation and a rotation
Definition at line 106 of file Translation.h.
template<typename Scalar, int Dim> template<int Mode, int Options> Transform<Scalar,Dim,Mode> Eigen::Translation< Scalar, Dim >::operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline
Concatenates a translation and a transformation
Definition at line 125 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs, and Eigen::Transform< _Scalar, _Dim >::pretranslate().
template<typename Scalar, int Dim> VectorType Eigen::Translation< Scalar, Dim >::operator* (const VectorType & other) const inline
Applies translation to vector
Definition at line 133 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> template<typename OtherDerived> Translation<Scalar,Dim>::AffineTransformType Eigen::Translation< Scalar, Dim >::operator* (const EigenBase< OtherDerived > & linear) const inline
Definition at line 193 of file Translation.h.
References Eigen::EigenBase< Derived >::derived(), Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Transform< _Scalar, _Dim >::matrix(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::Transform< _Scalar, _Dim >::translation().
template<typename Scalar, int Dim> Translation& Eigen::Translation< Scalar, Dim >::operator= (const Translation< Scalar, Dim > & other) inline
Definition at line 112 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Translation& Eigen::Translation< Scalar, Dim >::operator= (const Translation< Scalar, Dim > & other) inline
Definition at line 139 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> const VectorType& Eigen::Translation< Scalar, Dim >::translation () const inline
Definition at line 90 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> VectorType& Eigen::Translation< Scalar, Dim >::translation () inline
Definition at line 91 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> const VectorType& Eigen::Translation< Scalar, Dim >::vector () const inline
Definition at line 72 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Scaling< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator*=(), and Eigen::Transform< _Scalar, _Dim >::operator=().
template<typename Scalar, int Dim> VectorType& Eigen::Translation< Scalar, Dim >::vector () inline
Definition at line 73 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> const VectorType& Eigen::Translation< Scalar, Dim >::vector () const inline
Definition at line 87 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> VectorType& Eigen::Translation< Scalar, Dim >::vector () inline
Definition at line 88 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Scalar Eigen::Translation< Scalar, Dim >::x () const inline
Retruns the x-translation by value.
Definition at line 74 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Scalar& Eigen::Translation< Scalar, Dim >::x () inline
Retruns the x-translation as a reference.
Definition at line 81 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Scalar Eigen::Translation< Scalar, Dim >::y () const inline
Retruns the y-translation by value.
Definition at line 76 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Scalar& Eigen::Translation< Scalar, Dim >::y () inline
Retruns the y-translation as a reference.
Definition at line 83 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Scalar Eigen::Translation< Scalar, Dim >::z () const inline
Retruns the z-translation by value.
Definition at line 78 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
template<typename Scalar, int Dim> Scalar& Eigen::Translation< Scalar, Dim >::z () inline
Retruns the z-translation as a reference.
Definition at line 85 of file Translation.h.
References Eigen::Translation< Scalar, Dim >::m_coeffs.
Friends And Related Function Documentation
template<typename Scalar, int Dim> TransformType operator* (const LinearMatrixType & linear, const Translation< Scalar, Dim > & t) friend
Concatenates a linear transformation and a translation
Definition at line 91 of file Translation.h.
template<typename Scalar, int Dim> template<typename OtherDerived > AffineTransformType operator* (const EigenBase< OtherDerived > & linear, const Translation< Scalar, Dim > & t) friend
Returns
the concatenation of a linear transformation l with the translation t
Definition at line 112 of file Translation.h.
Member Data Documentation
template<typename Scalar, int Dim> VectorType Eigen::Translation< Scalar, Dim >::m_coeffs protected
Definition at line 48 of file Translation.h.
Referenced by Eigen::Translation< Scalar, Dim >::inverse(), Eigen::Translation< Scalar, Dim >::isApprox(), Eigen::Translation< Scalar, Dim >::operator*(), Eigen::Translation< Scalar, Dim >::operator=(), Eigen::Translation< Scalar, Dim >::Translation(), Eigen::Translation< Scalar, Dim >::translation(), Eigen::Translation< Scalar, Dim >::vector(), Eigen::Translation< Scalar, Dim >::x(), Eigen::Translation< Scalar, Dim >::y(), and Eigen::Translation< Scalar, Dim >::z().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Eigen2Support/Geometry/Translation.h