LIA_RAL: PldaTest Class Reference
PldaTest Class Reference
#include <PldaTools.h>
Public Member Functions
PldaTest (String &, String &, Config &)
Constructors, load vectors from ASCII file or XList.
PldaTest (String &, Config &)
PldaTest (XList &, Config &)
PldaTest (Config &)
PldaTest ()
virtual ~PldaTest ()
virtual String getClassName () const
void load (Config &)
void splitPerModel (unsigned long nbThread, RealVector< unsigned long > &startIndex, RealVector< unsigned long > &startModel)
unsigned long getVectSize ()
unsigned long getModelsNumber ()
unsigned long getMaxEnrollmentSession ()
unsigned long getSegmentsNumber ()
Matrix< double > getModels ()
Matrix< double > getSegments ()
Matrix< double > getScores ()
BoolMatrix getTrials ()
String getModelName (unsigned long index)
String getSegmentName (unsigned long index)
void lengthNorm ()
void center (RealVector< double > &mu)
void rotateLeft (Matrix< double > &M)
void sphericalNuisanceNormalization (Config &config)
void cosineDistance (Config &config)
void mahalanobisDistance (Matrix< double > &Mah, Config &config)
void twoCovScoringMixPart (DoubleSquareMatrix &G, Config &config)
void twoCovScoringMixPartUnThreaded (DoubleSquareMatrix &G, Config &config)
void twoCovScoringMixPartThreaded (DoubleSquareMatrix &G, unsigned long NUM_THREADS)
void twoCovScoring (DoubleSquareMatrix &W, DoubleSquareMatrix &B, Config &config)
void pldaScoring (Config &config, Eigen::MatrixXd FTJF, double alpha_one, Eigen::MatrixXd K_one, unsigned long rankF)
void pldaScoringUnThreaded (Config &config, Eigen::MatrixXd FTJF, double alpha_one, Eigen::MatrixXd K_one, unsigned long rankF)
void pldaScoringThreaded (Config &config, Eigen::MatrixXd FTJF, double alpha_one, Eigen::MatrixXd K_one, unsigned long rankF, unsigned long NUM_THREADS)
void pldaNativeScoring (PldaModel &pldaModel, Config &config)
void pldaMeanScoring (PldaModel &pldaModel, Config &config)
void saveSegments (String outputDir, Config &config)
void saveVectors (String outputDir, Config &config)
Private Attributes
XList _fileList
unsigned long _vectSize
unsigned long _n_models
unsigned long _n_enrollment_segments
unsigned long _n_test_segments
unsigned long _n_enrollSessions_max
XLine _modelIDLine
XLine _modelSessionslLine
XLine _modelIndexLine
XLine _segLine
Matrix< double > _models
Data Matrix.
Matrix< double > _segments
Matrix< double > _scores
BoolMatrix _trials
Detailed Description
This class represents a accumulator of statistics. A PldaTest contains the enrollment and test i-vectors for testing estimation
Author
Anthony Larcher alarc.nosp@m.her@.nosp@m.i2r.a.nosp@m.-sta.nosp@m.r.edu.nosp@m..sg
Version
1.0
Date
2012
Definition at line 554 of file PldaTools.h.
Constructor & Destructor Documentation
PldaTest::PldaTest (String & ndxTrialsFilename, String & ndxModelId, Config & config)
Constructors, load vectors from ASCII file or XList.
Definition at line 3036 of file PldaTools.cpp.
PldaTest::PldaTest (String & ndxTrialsFilename, Config & config)
Definition at line 3170 of file PldaTools.cpp.
PldaTest::PldaTest (XList & testList, Config & config)
Definition at line 3324 of file PldaTools.cpp.
References verboseLevel.
PldaTest::PldaTest (Config & config)
Definition at line 3422 of file PldaTools.cpp.
PldaTest::PldaTest ()
Definition at line 3427 of file PldaTools.cpp.
PldaTest::~PldaTest () virtual
Definition at line 3430 of file PldaTools.cpp.
Member Function Documentation
void PldaTest::center (RealVector< double > & mu)
Substrac a vector to all vectors in the PldaTest object
Parameters
mu mean vector to remove from all vectors
Definition at line 3754 of file PldaTools.cpp.
void PldaTest::cosineDistance (Config & config)
Comppute test using cosine distance
Parameters
config the configuration
Definition at line 3842 of file PldaTools.cpp.
References sqrt().
Referenced by IvTest().
String PldaTest::getClassName () const virtual
Definition at line 3433 of file PldaTools.cpp.
unsigned long PldaTest::getMaxEnrollmentSession ()
Get the maximum number of enrollment segments
Definition at line 3666 of file PldaTools.cpp.
Referenced by IvTest().
String PldaTest::getModelName (unsigned long index)
Get the name of a model
Parameters
index is the index of the model in _modelIDLine
Definition at line 3696 of file PldaTools.cpp.
Referenced by IvTest().
Matrix< double > PldaTest::getModels ()
Get the matrix of models
Definition at line 3676 of file PldaTools.cpp.
unsigned long PldaTest::getModelsNumber ()
Get the number of models
Definition at line 3661 of file PldaTools.cpp.
Referenced by IvTest().
Matrix< double > PldaTest::getScores ()
Get the matrix of scores
Definition at line 3686 of file PldaTools.cpp.
Referenced by IvTest().
String PldaTest::getSegmentName (unsigned long index)
Get the name of a segment
Parameters
index is the index of the segment in _segLine
Definition at line 3701 of file PldaTools.cpp.
Referenced by IvTest().
Matrix< double > PldaTest::getSegments ()
Get the matrix of segments
Definition at line 3681 of file PldaTools.cpp.
unsigned long PldaTest::getSegmentsNumber ()
Get the number of test segments
Definition at line 3671 of file PldaTools.cpp.
Referenced by IvTest().
BoolMatrix PldaTest::getTrials ()
Get the matrix of trials
Definition at line 3691 of file PldaTools.cpp.
Referenced by IvTest().
unsigned long PldaTest::getVectSize ()
Get the size of data vectors
Definition at line 3656 of file PldaTools.cpp.
void PldaTest::lengthNorm ()
Normalize the length of all vectors to one (Euclidian Norm)
Definition at line 3706 of file PldaTools.cpp.
References sqrt(), and verboseLevel.
void PldaTest::load (Config & config)
Load PldaTest data from different sources
Parameters
config the configuration
Definition at line 3437 of file PldaTools.cpp.
References verboseLevel.
void PldaTest::mahalanobisDistance (Matrix< double > & Mah, Config & config)
Compute test using cosine distance
Definition at line 3882 of file PldaTools.cpp.
Referenced by IvTest().
void PldaTest::pldaMeanScoring (PldaModel & pldaModel, Config & config)
Compute test using Probabilistic Linear Discriminant Analysis and mean of enrollment sesisojns for each model
Parameters
pldaModel the PLDA generative model
config the configuration
Definition at line 4612 of file PldaTools.cpp.
References PldaModel::getF(), PldaModel::getFtweight(), PldaModel::getFtweightG(), PldaModel::getGtweight(), PldaModel::getInvGtweightGplusEye(), PldaModel::getRankF(), log(), and PldaModel::preComputation().
Referenced by IvTest().
void PldaTest::pldaNativeScoring (PldaModel & pldaModel, Config & config)
Compute test using Probabilistic Linear Discriminant Analysis native scoring
Parameters
pldaModel the PLDA generative model
config the configuration
Definition at line 4489 of file PldaTools.cpp.
References PldaModel::getF(), PldaModel::getFtweight(), PldaModel::getFtweightG(), PldaModel::getGtweight(), PldaModel::getInvGtweightGplusEye(), PldaModel::getRankF(), log(), and PldaModel::preComputation().
Referenced by IvTest().
void PldaTest::pldaScoring (Config & config, Eigen::MatrixXd FTJF, double alpha_one, Eigen::MatrixXd K_one, unsigned long rankF)
Definition at line 4175 of file PldaTools.cpp.
void PldaTest::pldaScoringThreaded (Config & config, Eigen::MatrixXd FTJF, double alpha_one, Eigen::MatrixXd K_one, unsigned long rankF, unsigned long NUM_THREADS)
void PldaTest::pldaScoringUnThreaded (Config & config, Eigen::MatrixXd FTJF, double alpha_one, Eigen::MatrixXd K_one, unsigned long rankF)
Definition at line 4186 of file PldaTools.cpp.
References log().
void PldaTest::rotateLeft (Matrix< double > & M)
Rotate the model and test vectors by multiplying on the left by M
Parameters
M the matrix to multiply
Definition at line 3770 of file PldaTools.cpp.
Referenced by IvNorm(), and IvTest().
void PldaTest::saveSegments (String outputDir, Config & config)
Save test segments vector after normalization
Parameters
outputDir output directory to store normalized vectors
config the configuration
Definition at line 4712 of file PldaTools.cpp.
References verboseLevel.
Referenced by IvNorm().
void PldaTest::saveVectors (String outputDir, Config & config)
Save enrollment and test segments vector after normalization
Parameters
outputDir output directory to store normalized vectors
config the configuration
Definition at line 4734 of file PldaTools.cpp.
References verboseLevel.
Referenced by IvNorm().
void PldaTest::sphericalNuisanceNormalization (Config & config)
Apply Spherical Nuisance Normalization
Parameters
config the configuration
Definition at line 3793 of file PldaTools.cpp.
References verboseLevel.
Referenced by IvNorm(), and IvTest().
void PldaTest::splitPerModel (unsigned long nbThread, RealVector< unsigned long > & startIndex, RealVector< unsigned long > & startModel)
Definition at line 3625 of file PldaTools.cpp.
void PldaTest::twoCovScoring (DoubleSquareMatrix & W, DoubleSquareMatrix & B, Config & config)
Compute test using two covariance model
Parameters
W the within class covariance matrix
B the between class covariance matrix
config the configuration
Definition at line 4083 of file PldaTools.cpp.
References verboseLevel.
Referenced by IvTest().
void PldaTest::twoCovScoringMixPart (DoubleSquareMatrix & G, Config & config)
Definition at line 3912 of file PldaTools.cpp.
void PldaTest::twoCovScoringMixPartThreaded (DoubleSquareMatrix & G, unsigned long NUM_THREADS)
void PldaTest::twoCovScoringMixPartUnThreaded (DoubleSquareMatrix & G, Config & config)
Definition at line 3923 of file PldaTools.cpp.
References verboseLevel.
Member Data Documentation
XList PldaTest::_fileList private
Definition at line 558 of file PldaTools.h.
XLine PldaTest::_modelIDLine private
Definition at line 565 of file PldaTools.h.
XLine PldaTest::_modelIndexLine private
Definition at line 567 of file PldaTools.h.
Matrix<double> PldaTest::_models private
Data Matrix.
Definition at line 571 of file PldaTools.h.
XLine PldaTest::_modelSessionslLine private
Definition at line 566 of file PldaTools.h.
unsigned long PldaTest::_n_enrollment_segments private
Definition at line 561 of file PldaTools.h.
unsigned long PldaTest::_n_enrollSessions_max private
Definition at line 563 of file PldaTools.h.
unsigned long PldaTest::_n_models private
Definition at line 560 of file PldaTools.h.
unsigned long PldaTest::_n_test_segments private
Definition at line 562 of file PldaTools.h.
Matrix<double> PldaTest::_scores private
Definition at line 573 of file PldaTools.h.
XLine PldaTest::_segLine private
Definition at line 568 of file PldaTools.h.
Matrix<double> PldaTest::_segments private
Definition at line 572 of file PldaTools.h.
BoolMatrix PldaTest::_trials private
Definition at line 574 of file PldaTools.h.
unsigned long PldaTest::_vectSize private
Definition at line 559 of file PldaTools.h.
The documentation for this class was generated from the following files:
LIA_SpkTools/include/PldaTools.h
LIA_SpkTools/src/PldaTools.cpp