LIA_RAL: Eigen::Transform< _Scalar, _Dim > Class Template Reference
Eigen::Transform< _Scalar, _Dim > Class Template Reference
Geometry_Module
Represents an homogeneous transformation in a N dimensional space.
#include <Transform.h>
Classes
struct construct_from_matrix
struct construct_from_matrix< OtherDerived, true >
Public Types
enum { TransformTimeDiagonalMode = ((Mode==int(Isometry))?Affine:int(Mode)) }
typedef _Scalar Scalar
typedef Matrix< Scalar, HDim,
HDim > MatrixType
typedef Matrix< Scalar, Dim, Dim > LinearMatrixType
typedef Block< MatrixType, Dim,
Dim > LinearPart
typedef const Block< const
MatrixType, Dim, Dim > ConstLinearPart
typedef Matrix< Scalar, Dim, 1 > VectorType
typedef Block< MatrixType, Dim, 1 > TranslationPart
typedef const Block< const
MatrixType, Dim, 1 > ConstTranslationPart
typedef Translation< Scalar, Dim > TranslationType
typedef Scaling< Scalar, Dim > ScalingType
typedef _Scalar Scalar
typedef DenseIndex Index
typedef
internal::make_proper_matrix_type
< Scalar, Rows, HDim, Options >
::type MatrixType
typedef const MatrixType ConstMatrixType
typedef Matrix< Scalar, Dim,
Dim, Options > LinearMatrixType
typedef Block< MatrixType, Dim,
Dim, int(Mode)==(AffineCompact)> LinearPart
typedef const Block
< ConstMatrixType, Dim, Dim,
int(Mode)==(AffineCompact)> ConstLinearPart
typedef internal::conditional
< int(Mode)==int(AffineCompact),
MatrixType &, Block
< MatrixType, Dim, HDim >
>::type AffinePart
typedef internal::conditional
< int(Mode)==int(AffineCompact),
const MatrixType &, const
Block< const MatrixType, Dim,
HDim > >::type ConstAffinePart
typedef Matrix< Scalar, Dim, 1 > VectorType
typedef Block< MatrixType, Dim,
1, int(Mode)==(AffineCompact)> TranslationPart
typedef const Block
< ConstMatrixType, Dim, 1, int(Mode)==(AffineCompact)> ConstTranslationPart
typedef Translation< Scalar, Dim > TranslationType
typedef Transform< Scalar, Dim,
TransformTimeDiagonalMode > TransformTimeDiagonalReturnType
typedef
internal::transform_take_affine_part
< Transform > take_affine_part
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (_Scalar, _Dim==Dynamic?Dynamic:(_Dim+1)*(_Dim+1)) enum
Transform ()
Transform (const Transform &other)
Transform (const TranslationType &t)
Transform (const ScalingType &s)
template<typename Derived >
Transform (const RotationBase< Derived, Dim > &r)
Transform & operator= (const Transform &other)
template<typename OtherDerived >
Transform (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform & operator= (const MatrixBase< OtherDerived > &other)
Scalar operator() (int row, int col) const
Scalar & operator() (int row, int col)
const MatrixType & matrix () const
MatrixType & matrix ()
ConstLinearPart linear () const
LinearPart linear ()
ConstTranslationPart translation () const
TranslationPart translation ()
template<typename OtherDerived >
const
ei_transform_product_impl
< OtherDerived, _Dim, _Dim+1 >
::ResultType operator* (const MatrixBase< OtherDerived > &other) const
const Transform operator* (const Transform &other) const
void setIdentity ()
template<typename OtherDerived >
Transform & scale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform & prescale (const MatrixBase< OtherDerived > &other)
Transform & scale (Scalar s)
Transform & prescale (Scalar s)
template<typename OtherDerived >
Transform & translate (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform & pretranslate (const MatrixBase< OtherDerived > &other)
template<typename RotationType >
Transform & rotate (const RotationType &rotation)
template<typename RotationType >
Transform & prerotate (const RotationType &rotation)
Transform & shear (Scalar sx, Scalar sy)
Transform & preshear (Scalar sx, Scalar sy)
Transform & operator= (const TranslationType &t)
Transform & operator*= (const TranslationType &t)
Transform operator* (const TranslationType &t) const
Transform & operator= (const ScalingType &t)
Transform & operator*= (const ScalingType &s)
Transform operator* (const ScalingType &s) const
template<typename Derived >
Transform & operator= (const RotationBase< Derived, Dim > &r)
template<typename Derived >
Transform & operator*= (const RotationBase< Derived, Dim > &r)
template<typename Derived >
Transform operator* (const RotationBase< Derived, Dim > &r) const
LinearMatrixType rotation () const
template<typename RotationMatrixType , typename ScalingMatrixType >
void computeRotationScaling (RotationMatrixType *rotation, ScalingMatrixType *scaling) const
template<typename ScalingMatrixType , typename RotationMatrixType >
void computeScalingRotation (ScalingMatrixType *scaling, RotationMatrixType *rotation) const
template<typename PositionDerived , typename OrientationType , typename ScaleDerived >
Transform & fromPositionOrientationScale (const MatrixBase< PositionDerived > &position, const OrientationType &orientation, const MatrixBase< ScaleDerived > &scale)
const MatrixType inverse (TransformTraits traits=Affine) const
const Scalar * data () const
Scalar * data ()
template<typename NewScalarType >
internal::cast_return_type
< Transform, Transform
< NewScalarType, Dim > >::type cast () const
template<typename OtherScalarType >
Transform (const Transform< OtherScalarType, Dim > &other)
bool isApprox (const Transform &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (_Scalar, _Dim==Dynamic?Dynamic:(_Dim+1)*(_Dim+1)) enum
Transform ()
Transform (const Transform &other)
Transform (const TranslationType &t)
Transform (const UniformScaling< Scalar > &s)
template<typename Derived >
Transform (const RotationBase< Derived, Dim > &r)
Transform & operator= (const Transform &other)
template<typename OtherDerived >
Transform (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Transform & operator= (const EigenBase< OtherDerived > &other)
template<int OtherOptions>
Transform (const Transform< Scalar, Dim, Mode, OtherOptions > &other)
template<int OtherMode, int OtherOptions>
Transform (const Transform< Scalar, Dim, OtherMode, OtherOptions > &other)
template<typename OtherDerived >
Transform (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Transform & operator= (const ReturnByValue< OtherDerived > &other)
Scalar operator() (Index row, Index col) const
Scalar & operator() (Index row, Index col)
const MatrixType & matrix () const
MatrixType & matrix ()
ConstLinearPart linear () const
LinearPart linear ()
ConstAffinePart affine () const
AffinePart affine ()
ConstTranslationPart translation () const
TranslationPart translation ()
template<typename OtherDerived >
EIGEN_STRONG_INLINE const
internal::transform_right_product_impl
< Transform, OtherDerived >
::ResultType operator* (const EigenBase< OtherDerived > &other) const
template<typename DiagonalDerived >
const
TransformTimeDiagonalReturnType operator* (const DiagonalBase< DiagonalDerived > &b) const
template<typename OtherDerived >
Transform & operator*= (const EigenBase< OtherDerived > &other)
const Transform operator* (const Transform &other) const
template<int OtherMode, int OtherOptions>
internal::transform_transform_product_impl
< Transform, Transform< Scalar,
Dim, OtherMode, OtherOptions >
>::ResultType operator* (const Transform< Scalar, Dim, OtherMode, OtherOptions > &other) const
void setIdentity ()
template<typename OtherDerived >
Transform & scale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform & prescale (const MatrixBase< OtherDerived > &other)
Transform & scale (Scalar s)
Transform & prescale (Scalar s)
template<typename OtherDerived >
Transform & translate (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform & pretranslate (const MatrixBase< OtherDerived > &other)
template<typename RotationType >
Transform & rotate (const RotationType &rotation)
template<typename RotationType >
Transform & prerotate (const RotationType &rotation)
Transform & shear (Scalar sx, Scalar sy)
Transform & preshear (Scalar sx, Scalar sy)
Transform & operator= (const TranslationType &t)
Transform & operator*= (const TranslationType &t)
Transform operator* (const TranslationType &t) const
Transform & operator= (const UniformScaling< Scalar > &t)
Transform & operator*= (const UniformScaling< Scalar > &s)
Transform< Scalar, Dim,(int(Mode)==int(Isometry)?Affine:Isometry)> operator* (const UniformScaling< Scalar > &s) const
Transform & operator*= (const DiagonalMatrix< Scalar, Dim > &s)
template<typename Derived >
Transform & operator= (const RotationBase< Derived, Dim > &r)
template<typename Derived >
Transform & operator*= (const RotationBase< Derived, Dim > &r)
template<typename Derived >
Transform operator* (const RotationBase< Derived, Dim > &r) const
const LinearMatrixType rotation () const
template<typename RotationMatrixType , typename ScalingMatrixType >
void computeRotationScaling (RotationMatrixType *rotation, ScalingMatrixType *scaling) const
template<typename ScalingMatrixType , typename RotationMatrixType >
void computeScalingRotation (ScalingMatrixType *scaling, RotationMatrixType *rotation) const
template<typename PositionDerived , typename OrientationType , typename ScaleDerived >
Transform & fromPositionOrientationScale (const MatrixBase< PositionDerived > &position, const OrientationType &orientation, const MatrixBase< ScaleDerived > &scale)
Transform inverse (TransformTraits traits=(TransformTraits) Mode) const
const Scalar * data () const
Scalar * data ()
template<typename NewScalarType >
internal::cast_return_type
< Transform, Transform
< NewScalarType, Dim, Mode,
Options > >::type cast () const
template<typename OtherScalarType >
Transform (const Transform< OtherScalarType, Dim, Mode, Options > &other)
bool isApprox (const Transform &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
void makeAffine ()
Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim,
Dim > linearExt ()
const Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim,
Dim > linearExt () const
Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim, 1 > translationExt ()
const Block< MatrixType, int(Mode)==int(Projective)?HDim:Dim, 1 > translationExt () const
template<typename OtherDerived >
Transform< Scalar, Dim > & scale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform< Scalar, Dim > & prescale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform< Scalar, Dim > & translate (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform< Scalar, Dim > & pretranslate (const MatrixBase< OtherDerived > &other)
template<typename RotationType >
Transform< Scalar, Dim > & rotate (const RotationType &rotation)
template<typename RotationType >
Transform< Scalar, Dim > & prerotate (const RotationType &rotation)
template<typename Derived >
Transform< Scalar, Dim > & operator= (const RotationBase< Derived, Dim > &r)
template<typename Derived>
Transform< Scalar, Dim > operator* (const RotationBase< Derived, Dim > &r) const
template<typename PositionDerived , typename OrientationType , typename ScaleDerived >
Transform< Scalar, Dim > & fromPositionOrientationScale (const MatrixBase< PositionDerived > &position, const OrientationType &orientation, const MatrixBase< ScaleDerived > &scale)
template<typename OtherDerived >
Transform< Scalar, Dim, Mode,
Options > & scale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform< Scalar, Dim, Mode,
Options > & prescale (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform< Scalar, Dim, Mode,
Options > & translate (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Transform< Scalar, Dim, Mode,
Options > & pretranslate (const MatrixBase< OtherDerived > &other)
template<typename RotationType >
Transform< Scalar, Dim, Mode,
Options > & rotate (const RotationType &rotation)
template<typename RotationType >
Transform< Scalar, Dim, Mode,
Options > & prerotate (const RotationType &rotation)
template<typename Derived >
Transform< Scalar, Dim, Mode,
Options > & operator= (const RotationBase< Derived, Dim > &r)
template<typename Derived>
Transform< Scalar, Dim, Mode,
Options > operator* (const RotationBase< Derived, Dim > &r) const
template<typename PositionDerived , typename OrientationType , typename ScaleDerived >
Transform< Scalar, Dim, Mode,
Options > & fromPositionOrientationScale (const MatrixBase< PositionDerived > &position, const OrientationType &orientation, const MatrixBase< ScaleDerived > &scale)
Static Public Member Functions
static const
MatrixType::IdentityReturnType Identity ()
static const Transform Identity ()
Returns an identity transformation.
Static Protected Member Functions
static EIGEN_STRONG_INLINE void check_template_params ()
Protected Attributes
MatrixType m_matrix
Friends
template<typename OtherDerived >
const ProductReturnType
< OtherDerived, MatrixType >
::Type operator* (const MatrixBase< OtherDerived > &a, const Transform &b)
Transform operator* (const LinearMatrixType &mat, const Transform &t)
template<typename OtherDerived >
const
internal::transform_left_product_impl
< OtherDerived, Mode, Options,
_Dim, _Dim+1 >::ResultType operator* (const EigenBase< OtherDerived > &a, const Transform &b)
template<typename DiagonalDerived >
TransformTimeDiagonalReturnType operator* (const DiagonalBase< DiagonalDerived > &a, const Transform &b)
Detailed Description
template<typename _Scalar, int _Dim>
class Eigen::Transform< _Scalar, _Dim >
Represents an homogeneous transformation in a N dimensional space.
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_Dim the dimension of the space
The homography is internally represented and stored as a (Dim+1)^2 matrix which is available through the matrix() method.
Conversion methods from/to Qt's QMatrix and QTransform are available if the preprocessor token EIGEN_QT_SUPPORT is defined.
See Also
class Matrix, class Quaternion
Template Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_Dim the dimension of the space
_Mode the type of the transformation. Can be:
Affine: the transformation is stored as a (Dim+1)^2 matrix, where the last row is assumed to be [0 ... 0 1].
AffineCompact: the transformation is stored as a (Dim)x(Dim+1) matrix.
Projective: the transformation is stored as a (Dim+1)^2 matrix without any assumption.
_Options has the same meaning as in class Matrix. It allows to specify DontAlign and/or RowMajor. These Options are passed directly to the underlying matrix type.
The homography is internally represented and stored by a matrix which is available through the matrix() method. To understand the behavior of this class you have to think a Transform object as its internal matrix representation. The chosen convention is right multiply:
v' = T * v
Therefore, an affine transformation matrix M is shaped like this:
Note that for a projective transformation the last row can be anything, and then the interpretation of different parts might be sightly different.
However, unlike a plain matrix, the Transform class provides many features simplifying both its assembly and usage. In particular, it can be composed with any other transformations (Transform,Translation,RotationBase,Matrix) and can be directly used to transform implicit homogeneous vectors. All these operations are handled via the operator*. For the composition of transformations, its principle consists to first convert the right/left hand sides of the product to a compatible (Dim+1)^2 matrix and then perform a pure matrix product. Of course, internally, operator* tries to perform the minimal number of operations according to the nature of each terms. Likewise, when applying the transform to non homogeneous vectors, the latters are automatically promoted to homogeneous one before doing the matrix product. The convertions to homogeneous representations are performed as follow:
Translation t (Dim)x(1):
Rotation R (Dim)x(Dim):
Linear Matrix L (Dim)x(Dim):
Affine Matrix A (Dim)x(Dim+1):
Column vector v (Dim)x(1):
Set of column vectors V1...Vn (Dim)x(n):
The concatenation of a Transform object with any kind of other transformation always returns a Transform object.
A little exception to the "as pure matrix product" rule is the case of the transformation of non homogeneous vectors by an affine transformation. In that case the last matrix row can be ignored, and the product returns non homogeneous vectors.
Since, for instance, a Dim x Dim matrix is interpreted as a linear transformation, it is not possible to directly transform Dim vectors stored in a Dim x Dim matrix. The solution is either to use a Dim x Dynamic matrix or explicitly request a vector transformation by making the vector homogeneous:
m' = T * m.colwise().homogeneous();
Note that there is zero overhead.
Conversion methods from/to Qt's QMatrix and QTransform are available if the preprocessor token EIGEN_QT_SUPPORT is defined.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizingEigen by defining the preprocessor symbol EIGEN_TRANSFORM_PLUGIN.
See Also
class Matrix, class Quaternion
Definition at line 43 of file Transform.h.
Member Typedef Documentation
template<typename _Scalar, int _Dim> typedef internal::conditional<int(Mode)==int(AffineCompact), MatrixType&, Block<MatrixType,Dim,HDim> >::type Eigen::Transform< _Scalar, _Dim >::AffinePart
type of read/write reference to the affine part of the transformation
Definition at line 203 of file Transform.h.
template<typename _Scalar, int _Dim> typedef internal::conditional<int(Mode)==int(AffineCompact), const MatrixType&, const Block<const MatrixType,Dim,HDim> >::type Eigen::Transform< _Scalar, _Dim >::ConstAffinePart
type of read reference to the affine part of the transformation
Definition at line 207 of file Transform.h.
template<typename _Scalar, int _Dim> typedef const Block<const MatrixType,Dim,Dim> Eigen::Transform< _Scalar, _Dim >::ConstLinearPart
type of read/write reference to the linear part of the transformation
Definition at line 60 of file Transform.h.
template<typename _Scalar, int _Dim> typedef const Block<ConstMatrixType,Dim,Dim,int(Mode)==(AffineCompact)> Eigen::Transform< _Scalar, _Dim >::ConstLinearPart
type of read reference to the linear part of the transformation
Definition at line 199 of file Transform.h.
template<typename _Scalar, int _Dim> typedef const MatrixType Eigen::Transform< _Scalar, _Dim >::ConstMatrixType
constified MatrixType
Definition at line 193 of file Transform.h.
template<typename _Scalar, int _Dim> typedef const Block<const MatrixType,Dim,1> Eigen::Transform< _Scalar, _Dim >::ConstTranslationPart
type of a read/write reference to the translation part of the rotation
Definition at line 66 of file Transform.h.
template<typename _Scalar, int _Dim> typedef const Block<ConstMatrixType,Dim,1,int(Mode)==(AffineCompact)> Eigen::Transform< _Scalar, _Dim >::ConstTranslationPart
type of a read reference to the translation part of the rotation
Definition at line 213 of file Transform.h.
template<typename _Scalar, int _Dim> typedef DenseIndex Eigen::Transform< _Scalar, _Dim >::Index
Definition at line 189 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Matrix<Scalar,Dim,Dim> Eigen::Transform< _Scalar, _Dim >::LinearMatrixType
type of the matrix used to represent the linear part of the transformation
Definition at line 56 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Matrix<Scalar,Dim,Dim,Options> Eigen::Transform< _Scalar, _Dim >::LinearMatrixType
type of the matrix used to represent the linear part of the transformation
Definition at line 195 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Block<MatrixType,Dim,Dim> Eigen::Transform< _Scalar, _Dim >::LinearPart
type of read/write reference to the linear part of the transformation
Definition at line 58 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Block<MatrixType,Dim,Dim,int(Mode)==(AffineCompact)> Eigen::Transform< _Scalar, _Dim >::LinearPart
type of read/write reference to the linear part of the transformation
Definition at line 197 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Matrix<Scalar,HDim,HDim> Eigen::Transform< _Scalar, _Dim >::MatrixType
type of the matrix used to represent the transformation
Definition at line 54 of file Transform.h.
template<typename _Scalar, int _Dim> typedef internal::make_proper_matrix_type<Scalar,Rows,HDim,Options>::type Eigen::Transform< _Scalar, _Dim >::MatrixType
type of the matrix used to represent the transformation
Definition at line 191 of file Transform.h.
template<typename _Scalar, int _Dim> typedef _Scalar Eigen::Transform< _Scalar, _Dim >::Scalar
the scalar type of the coefficients
Definition at line 50 of file Transform.h.
template<typename _Scalar, int _Dim> typedef _Scalar Eigen::Transform< _Scalar, _Dim >::Scalar
the scalar type of the coefficients
Definition at line 186 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Scaling<Scalar,Dim> Eigen::Transform< _Scalar, _Dim >::ScalingType
corresponding scaling transformation type
Definition at line 70 of file Transform.h.
template<typename _Scalar, int _Dim> typedef internal::transform_take_affine_part<Transform> Eigen::Transform< _Scalar, _Dim >::take_affine_part
Definition at line 263 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Transform<Scalar,Dim,TransformTimeDiagonalMode> Eigen::Transform< _Scalar, _Dim >::TransformTimeDiagonalReturnType
The return type of the product between a diagonal matrix and a transform
Definition at line 220 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Block<MatrixType,Dim,1> Eigen::Transform< _Scalar, _Dim >::TranslationPart
type of a read/write reference to the translation part of the rotation
Definition at line 64 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Block<MatrixType,Dim,1,int(Mode)==(AffineCompact)> Eigen::Transform< _Scalar, _Dim >::TranslationPart
type of a read/write reference to the translation part of the rotation
Definition at line 211 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Translation<Scalar,Dim> Eigen::Transform< _Scalar, _Dim >::TranslationType
corresponding translation type
Definition at line 68 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Translation<Scalar,Dim> Eigen::Transform< _Scalar, _Dim >::TranslationType
corresponding translation type
Definition at line 215 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Matrix<Scalar,Dim,1> Eigen::Transform< _Scalar, _Dim >::VectorType
type of a vector
Definition at line 62 of file Transform.h.
template<typename _Scalar, int _Dim> typedef Matrix<Scalar,Dim,1> Eigen::Transform< _Scalar, _Dim >::VectorType
type of a vector
Definition at line 209 of file Transform.h.
Member Enumeration Documentation
template<typename _Scalar, int _Dim> anonymous enum
Enumerator
TransformTimeDiagonalMode
Definition at line 218 of file Transform.h.
Constructor & Destructor Documentation
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform () inline
Default constructor without initialization of the coefficients.
Definition at line 79 of file Transform.h.
Referenced by Eigen::Transform< _Scalar, _Dim >::operator*().
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform (const Transform< _Scalar, _Dim > & other) inline
Definition at line 81 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform (const TranslationType & t) inline explicit
Definition at line 86 of file Transform.h.
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform (const ScalingType & s) inline explicit
Definition at line 87 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename Derived > Eigen::Transform< _Scalar, _Dim >::Transform (const RotationBase< Derived, Dim > & r) inline explicit
Definition at line 89 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Eigen::Transform< _Scalar, _Dim >::Transform (const MatrixBase< OtherDerived > & other) inline explicit
Constructs and initializes a transformation from a Dim^2 or a (Dim+1)^2 matrix.
Definition at line 116 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename OtherScalarType > Eigen::Transform< _Scalar, _Dim >::Transform (const Transform< OtherScalarType, Dim > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 263 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix, and Eigen::Transform< _Scalar, _Dim >::matrix().
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform () inline
Default constructor without initialization of the meaningful coefficients. If Mode==Affine, then the last row is set to [0 ... 0 1]
Definition at line 230 of file Transform.h.
References Eigen::Affine.
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform (const Transform< _Scalar, _Dim > & other) inline
Definition at line 237 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform (const TranslationType & t) inline explicit
Definition at line 243 of file Transform.h.
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::Transform (const UniformScaling< Scalar > & s) inline explicit
Definition at line 248 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename Derived > Eigen::Transform< _Scalar, _Dim >::Transform (const RotationBase< Derived, Dim > & r) inline explicit
Definition at line 254 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Eigen::Transform< _Scalar, _Dim >::Transform (const EigenBase< OtherDerived > & other) inline explicit
Constructs and initializes a transformation from a Dim^2 or a (Dim+1)^2 matrix.
Definition at line 267 of file Transform.h.
References Eigen::EigenBase< Derived >::derived(), and EIGEN_STATIC_ASSERT.
template<typename _Scalar, int _Dim> template<int OtherOptions> Eigen::Transform< _Scalar, _Dim >::Transform (const Transform< Scalar, Dim, Mode, OtherOptions > & other) inline
Definition at line 288 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::matrix().
template<typename _Scalar, int _Dim> template<int OtherMode, int OtherOptions> Eigen::Transform< _Scalar, _Dim >::Transform (const Transform< Scalar, Dim, OtherMode, OtherOptions > & other) inline
Definition at line 296 of file Transform.h.
References Eigen::Affine, Eigen::AffineCompact, EIGEN_IMPLIES, EIGEN_STATIC_ASSERT, Eigen::Isometry, Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Transform< _Scalar, _Dim >::matrix(), Eigen::Projective, and Eigen::Transform< _Scalar, _Dim >::translation().
template<typename _Scalar, int _Dim> template<typename OtherDerived > Eigen::Transform< _Scalar, _Dim >::Transform (const ReturnByValue< OtherDerived > & other) inline
Definition at line 337 of file Transform.h.
References Eigen::ReturnByValue< Derived >::evalTo().
template<typename _Scalar, int _Dim> template<typename OtherScalarType > Eigen::Transform< _Scalar, _Dim >::Transform (const Transform< OtherScalarType, Dim, Mode, Options > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 577 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::matrix().
Member Function Documentation
template<typename _Scalar, int _Dim> ConstAffinePart Eigen::Transform< _Scalar, _Dim >::affine () const inline
Returns
a read-only expression of the Dim x HDim affine part of the transformation
Definition at line 377 of file Transform.h.
Referenced by Eigen::internal::take_matrix_for_product< Transform< Scalar, Dim, Mode, Options > >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), and Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, HDim >::run().
template<typename _Scalar, int _Dim> AffinePart Eigen::Transform< _Scalar, _Dim >::affine () inline
Returns
a writable expression of the Dim x HDim affine part of the transformation
Definition at line 379 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename NewScalarType > internal::cast_return_type<Transform,Transform<NewScalarType,Dim> >::type Eigen::Transform< _Scalar, _Dim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 258 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename NewScalarType > internal::cast_return_type<Transform,Transform<NewScalarType,Dim,Mode,Options> >::type Eigen::Transform< _Scalar, _Dim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 572 of file Transform.h.
template<typename _Scalar, int _Dim> static EIGEN_STRONG_INLINE void Eigen::Transform< _Scalar, _Dim >::check_template_params () inline static protected
Definition at line 634 of file Transform.h.
References Eigen::DontAlign, EIGEN_STATIC_ASSERT, and Eigen::RowMajor.
template<typename Scalar , int Dim, int Mode, int Options> template<typename RotationMatrixType , typename ScalingMatrixType > void Eigen::Transform< Scalar, Dim, Mode, Options >::computeRotationScaling (RotationMatrixType * rotation, ScalingMatrixType * scaling) const
decomposes the linear part of the transformation as a product rotation x scaling, the scaling being not necessarily positive.
If either pointer is zero, the corresponding computation is skipped.
See Also
computeScalingRotation(), rotation(), class SVD
decomposes the linear part of the transformation as a product rotation x scaling, the scaling being not necessarily positive.
If either pointer is zero, the corresponding computation is skipped.
See Also
computeScalingRotation(), rotation(), class SVD
Definition at line 619 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::matrixU(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::matrixV(), and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::singularValues().
template<typename _Scalar, int _Dim> template<typename RotationMatrixType , typename ScalingMatrixType > void Eigen::Transform< _Scalar, _Dim >::computeRotationScaling (RotationMatrixType * rotation, ScalingMatrixType * scaling) const
template<typename Scalar , int Dim, int Mode, int Options> template<typename ScalingMatrixType , typename RotationMatrixType > void Eigen::Transform< Scalar, Dim, Mode, Options >::computeScalingRotation (ScalingMatrixType * scaling, RotationMatrixType * rotation) const
decomposes the linear part of the transformation as a product rotation x scaling, the scaling being not necessarily positive.
If either pointer is zero, the corresponding computation is skipped.
See Also
computeRotationScaling(), rotation(), class SVD
decomposes the linear part of the transformation as a product rotation x scaling, the scaling being not necessarily positive.
If either pointer is zero, the corresponding computation is skipped.
See Also
computeRotationScaling(), rotation(), class SVD
Definition at line 650 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::matrixU(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::matrixV(), and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::singularValues().
template<typename _Scalar, int _Dim> template<typename ScalingMatrixType , typename RotationMatrixType > void Eigen::Transform< _Scalar, _Dim >::computeScalingRotation (ScalingMatrixType * scaling, RotationMatrixType * rotation) const
template<typename _Scalar, int _Dim> const Scalar* Eigen::Transform< _Scalar, _Dim >::data () const inline
Returns
a const pointer to the column major internal matrix
Definition at line 248 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::data(), and Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> Scalar* Eigen::Transform< _Scalar, _Dim >::data () inline
Returns
a non-const pointer to the column major internal matrix
Definition at line 250 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::data(), and Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> const Scalar* Eigen::Transform< _Scalar, _Dim >::data () const inline
Returns
a const pointer to the column major internal matrix
Definition at line 562 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::data().
template<typename _Scalar, int _Dim> Scalar* Eigen::Transform< _Scalar, _Dim >::data () inline
Returns
a non-const pointer to the column major internal matrix
Definition at line 564 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::data().
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (_Scalar , _Dim = =Dynamic ? Dynamic : (_Dim+1)*(_Dim+1)) inline
< space dimension in which the transformation holds
< size of a respective homogeneous vector
Definition at line 46 of file Transform.h.
template<typename _Scalar, int _Dim> Eigen::Transform< _Scalar, _Dim >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (_Scalar , _Dim = =Dynamic ? Dynamic : (_Dim+1)*(_Dim+1)) inline
< space dimension in which the transformation holds
< size of a respective homogeneous vector
Definition at line 179 of file Transform.h.
References Eigen::AffineCompact.
template<typename _Scalar, int _Dim> template<typename PositionDerived , typename OrientationType , typename ScaleDerived > Transform& Eigen::Transform< _Scalar, _Dim >::fromPositionOrientationScale (const MatrixBase< PositionDerived > & position, const OrientationType & orientation, const MatrixBase< ScaleDerived > & scale)
template<typename _Scalar, int _Dim> template<typename PositionDerived , typename OrientationType , typename ScaleDerived > Transform& Eigen::Transform< _Scalar, _Dim >::fromPositionOrientationScale (const MatrixBase< PositionDerived > & position, const OrientationType & orientation, const MatrixBase< ScaleDerived > & scale)
template<typename _Scalar, int _Dim> template<typename PositionDerived , typename OrientationType , typename ScaleDerived > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::fromPositionOrientationScale (const MatrixBase< PositionDerived > & position, const OrientationType & orientation, const MatrixBase< ScaleDerived > & scale)
Convenient method to set *this from a position, orientation and scale of a 3D object.
Definition at line 674 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal().
template<typename _Scalar, int _Dim> template<typename PositionDerived , typename OrientationType , typename ScaleDerived > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::fromPositionOrientationScale (const MatrixBase< PositionDerived > & position, const OrientationType & orientation, const MatrixBase< ScaleDerived > & scale)
Convenient method to set *this from a position, orientation and scale of a 3D object.
Definition at line 1070 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal().
template<typename _Scalar, int _Dim> static const MatrixType::IdentityReturnType Eigen::Transform< _Scalar, _Dim >::Identity () inline static
Definition at line 184 of file Transform.h.
template<typename _Scalar, int _Dim> static const Transform Eigen::Transform< _Scalar, _Dim >::Identity () inline static
Returns an identity transformation.
Todo:
In the future this function should be returning a Transform expression.
Definition at line 498 of file Transform.h.
References Transform.
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > Eigen::Transform< Scalar, Dim, Mode, Options >::inverse (TransformTraits hint = Affine) const inline
Returns
the inverse transformation matrix according to some given knowledge on *this.
Parameters
traits allows to optimize the inversion process when the transformion is known to be not a general transformation. The possible values are:
Projective if the transformation is not necessarily affine, i.e., if the last row is not guaranteed to be [0 ... 0 1]
Affine is the default, the last row is assumed to be [0 ... 0 1]
Isometry if the transformation is only a concatenations of translations and rotations.
Warning
unless traits is always set to NoShear or NoScaling, this function requires the generic inverse method of MatrixBase defined in the LU module. If you forget to include this module, then you will get hard to debug linking errors.
See Also
MatrixBase::inverse()
Returns
the inverse transformation according to some given knowledge on *this.
Parameters
hint allows to optimize the inversion process when the transformation is known to be not a general transformation (optional). The possible values are:
Projective if the transformation is not necessarily affine, i.e., if the last row is not guaranteed to be [0 ... 0 1]
Affine if the last row can be assumed to be [0 ... 0 1]
Isometry if the transformation is only a concatenations of translations and rotations. The default is the template class parameter Mode.
Warning
unless traits is always set to NoShear or NoScaling, this function requires the generic inverse method of MatrixBase defined in the LU module. If you forget to include this module, then you will get hard to debug linking errors.
See Also
MatrixBase::inverse()
Definition at line 706 of file Transform.h.
References Eigen::Affine, Eigen::BottomLeft, Eigen::PlainObjectBase< Derived >::coeffRef(), ei_assert, Eigen::Isometry, Eigen::Projective, Eigen::TopLeft, and Eigen::TopRight.
template<typename _Scalar, int _Dim> Transform Eigen::Transform< _Scalar, _Dim >::inverse (TransformTraits traits = (TransformTraits) Mode) const inline
template<typename _Scalar, int _Dim> bool Eigen::Transform< _Scalar, _Dim >::isApprox (const Transform< _Scalar, _Dim > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 270 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> bool Eigen::Transform< _Scalar, _Dim >::isApprox (const Transform< _Scalar, _Dim > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 587 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> ConstLinearPart Eigen::Transform< _Scalar, _Dim >::linear () const inline
Returns
a read-only expression of the linear (linear) part of the transformation
Definition at line 148 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< Scalar, Dim >::operator*(), Eigen::Scaling< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::construct_from_matrix< OtherDerived, true >::run(), Eigen::internal::rotation_base_generic_product_selector< RotationDerived, DiagonalMatrix< Scalar, Dim, MaxDim >, false >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, Dim >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run(), Eigen::Hyperplane< _Scalar, _AmbientDim >::transform(), and Eigen::Transform< _Scalar, _Dim >::Transform().
template<typename _Scalar, int _Dim> LinearPart Eigen::Transform< _Scalar, _Dim >::linear () inline
Returns
a writable expression of the linear (linear) part of the transformation
Definition at line 150 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> ConstLinearPart Eigen::Transform< _Scalar, _Dim >::linear () const inline
Returns
a read-only expression of the linear part of the transformation
Definition at line 372 of file Transform.h.
template<typename _Scalar, int _Dim> LinearPart Eigen::Transform< _Scalar, _Dim >::linear () inline
Returns
a writable expression of the linear part of the transformation
Definition at line 374 of file Transform.h.
template<typename _Scalar, int _Dim> Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,Dim> Eigen::Transform< _Scalar, _Dim >::linearExt () inline
Definition at line 605 of file Transform.h.
template<typename _Scalar, int _Dim> const Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,Dim> Eigen::Transform< _Scalar, _Dim >::linearExt () const inline
Definition at line 611 of file Transform.h.
template<typename _Scalar, int _Dim> void Eigen::Transform< _Scalar, _Dim >::makeAffine () inline
Sets the last row to [0 ... 0 1]
Definition at line 592 of file Transform.h.
References Eigen::AffineCompact.
Referenced by Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), and Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run().
template<typename _Scalar, int _Dim> const MatrixType& Eigen::Transform< _Scalar, _Dim >::matrix () const inline
Returns
a read-only expression of the transformation matrix
Definition at line 143 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< Scalar, Dim >::operator*(), Eigen::Scaling< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::construct_from_matrix< OtherDerived, BigMatrix >::run(), Eigen::Transform< _Scalar, _Dim >::construct_from_matrix< OtherDerived, true >::run(), Eigen::internal::take_matrix_for_product< Transform< Scalar, Dim, Projective, Options > >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, HDim, HDim >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, Dim >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, HDim, 1 >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_construct_from_matrix< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, true >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, AffineCompact, LhsOptions >, Transform< Scalar, Dim, Projective, RhsOptions >, true >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, Projective, LhsOptions >, Transform< Scalar, Dim, AffineCompact, RhsOptions >, true >::run(), and Eigen::Transform< _Scalar, _Dim >::Transform().
template<typename _Scalar, int _Dim> MatrixType& Eigen::Transform< _Scalar, _Dim >::matrix () inline
Returns
a writable expression of the transformation matrix
Definition at line 145 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> const MatrixType& Eigen::Transform< _Scalar, _Dim >::matrix () const inline
Returns
a read-only expression of the transformation matrix
Definition at line 367 of file Transform.h.
template<typename _Scalar, int _Dim> MatrixType& Eigen::Transform< _Scalar, _Dim >::matrix () inline
Returns
a writable expression of the transformation matrix
Definition at line 369 of file Transform.h.
template<typename _Scalar, int _Dim> Scalar Eigen::Transform< _Scalar, _Dim >::operator() (int row, int col) const inline
shortcut for m_matrix(row,col);
See Also
MatrixBase::operaror(int,int) const
Definition at line 137 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> Scalar& Eigen::Transform< _Scalar, _Dim >::operator() (int row, int col) inline
shortcut for m_matrix(row,col);
See Also
MatrixBase::operaror(int,int)
Definition at line 140 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> Scalar Eigen::Transform< _Scalar, _Dim >::operator() (Index row, Index col) const inline
shortcut for m_matrix(row,col);
See Also
MatrixBase::operator(Index,Index) const
Definition at line 361 of file Transform.h.
template<typename _Scalar, int _Dim> Scalar& Eigen::Transform< _Scalar, _Dim >::operator() (Index row, Index col) inline
shortcut for m_matrix(row,col);
See Also
MatrixBase::operator(Index,Index)
Definition at line 364 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename OtherDerived > const ei_transform_product_impl<OtherDerived,_Dim,_Dim+1>::ResultType Eigen::Transform< _Scalar, _Dim >::operator* (const MatrixBase< OtherDerived > & other) const inline
Returns
an expression of the product between the transform *this and a matrix expression other
The right hand side other might be either:
a vector of size Dim,
an homogeneous vector of size Dim+1,
a transformation matrix of size Dim+1 x Dim+1.
Definition at line 167 of file Transform.h.
template<typename _Scalar, int _Dim> const Transform Eigen::Transform< _Scalar, _Dim >::operator* (const Transform< _Scalar, _Dim > & other) const inline
Contatenates two transformations
Definition at line 179 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix, Eigen::Transform< _Scalar, _Dim >::matrix(), and Eigen::Transform< _Scalar, _Dim >::Transform().
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > Eigen::Transform< Scalar, Dim, Mode, Options >::operator* (const TranslationType & t) const inline
Definition at line 541 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::translate(), and Eigen::Translation< Scalar, Dim >::vector().
template<typename Scalar , int Dim> Transform< Scalar, Dim > Eigen::Transform< Scalar, Dim >::operator* (const ScalingType & s) const inline
Definition at line 558 of file Transform.h.
References Eigen::Scaling< _Scalar, _Dim >::coeffs(), and Eigen::Transform< _Scalar, _Dim >::scale().
template<typename _Scalar, int _Dim> template<typename Derived > Transform Eigen::Transform< _Scalar, _Dim >::operator* (const RotationBase< Derived, Dim > & r) const inline
template<typename _Scalar, int _Dim> template<typename OtherDerived > EIGEN_STRONG_INLINE const internal::transform_right_product_impl<Transform, OtherDerived>::ResultType Eigen::Transform< _Scalar, _Dim >::operator* (const EigenBase< OtherDerived > & other) const inline
Returns
an expression of the product between the transform *this and a matrix expression other
The right hand side other might be either:
a vector of size Dim,
an homogeneous vector of size Dim+1,
a set of vectors of size Dim x Dynamic,
a set of homogeneous vectors of size Dim+1 x Dynamic,
a linear transformation matrix of size Dim x Dim,
an affine transformation matrix of size Dim x Dim+1,
a transformation matrix of size Dim+1 x Dim+1.
Definition at line 400 of file Transform.h.
References Eigen::EigenBase< Derived >::derived().
template<typename _Scalar, int _Dim> template<typename DiagonalDerived > const TransformTimeDiagonalReturnType Eigen::Transform< _Scalar, _Dim >::operator* (const DiagonalBase< DiagonalDerived > & b) const inline
Returns
The product expression of a transform a times a diagonal matrix b
The rhs diagonal matrix is interpreted as an affine scaling transformation. The product results in a Transform of the same type (mode) as the lhs only if the lhs mode is no isometry. In that case, the returned transform is an affinity.
Definition at line 423 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::linear().
template<typename _Scalar, int _Dim> const Transform Eigen::Transform< _Scalar, _Dim >::operator* (const Transform< _Scalar, _Dim > & other) const inline
Concatenates two transformations
Definition at line 452 of file Transform.h.
template<typename _Scalar, int _Dim> template<int OtherMode, int OtherOptions> internal::transform_transform_product_impl<Transform,Transform<Scalar,Dim,OtherMode,OtherOptions> >::ResultType Eigen::Transform< _Scalar, _Dim >::operator* (const Transform< Scalar, Dim, OtherMode, OtherOptions > & other) const inline
Concatenates two different transformations
Definition at line 485 of file Transform.h.
template<typename _Scalar, int _Dim> Transform Eigen::Transform< _Scalar, _Dim >::operator* (const TranslationType & t) const inline
template<typename _Scalar, int _Dim> Transform<Scalar,Dim,(int(Mode)==int(Isometry)?Affine:Isometry)> Eigen::Transform< _Scalar, _Dim >::operator* (const UniformScaling< Scalar > & s) const inline
Definition at line 533 of file Transform.h.
References Eigen::UniformScaling< _Scalar >::factor(), and Eigen::Transform< _Scalar, _Dim >::scale().
template<typename _Scalar, int _Dim> template<typename Derived > Transform Eigen::Transform< _Scalar, _Dim >::operator* (const RotationBase< Derived, Dim > & r) const inline
template<typename _Scalar, int _Dim> template<typename Derived> Transform<Scalar,Dim> Eigen::Transform< _Scalar, _Dim >::operator* (const RotationBase< Derived, Dim > & r) const inline
Definition at line 578 of file Transform.h.
References Eigen::RotationBase< Derived, _Dim >::derived(), and Eigen::Transform< _Scalar, _Dim >::rotate().
template<typename _Scalar, int _Dim> template<typename Derived> Transform<Scalar,Dim,Mode,Options> Eigen::Transform< _Scalar, _Dim >::operator* (const RotationBase< Derived, Dim > & r) const inline
Definition at line 978 of file Transform.h.
References Eigen::RotationBase< Derived, _Dim >::derived(), and Eigen::Transform< _Scalar, _Dim >::rotate().
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const TranslationType & t) inline
Definition at line 214 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::translate(), and Eigen::Translation< Scalar, Dim >::vector().
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const ScalingType & s) inline
Definition at line 218 of file Transform.h.
References Eigen::Scaling< _Scalar, _Dim >::coeffs(), and Eigen::Transform< _Scalar, _Dim >::scale().
template<typename _Scalar, int _Dim> template<typename Derived > Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const RotationBase< Derived, Dim > & r) inline
Definition at line 231 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::rotate(), and Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const EigenBase< OtherDerived > & other) inline
Definition at line 449 of file Transform.h.
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const TranslationType & t) inline
Definition at line 528 of file Transform.h.
References Eigen::Translation< Scalar, Dim >::vector().
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const UniformScaling< Scalar > & s) inline
Definition at line 532 of file Transform.h.
References Eigen::UniformScaling< _Scalar >::factor().
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const DiagonalMatrix< Scalar, Dim > & s) inline
Definition at line 540 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename Derived > Transform& Eigen::Transform< _Scalar, _Dim >::operator*= (const RotationBase< Derived, Dim > & r) inline
Definition at line 545 of file Transform.h.
References Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const Transform< _Scalar, _Dim > & other) inline
Definition at line 91 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const MatrixBase< OtherDerived > & other) inline
Set *this from a (Dim+1)^2 matrix.
Definition at line 123 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::operator= (const TranslationType & t) inline
Definition at line 531 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::setIdentity(), and Eigen::Translation< Scalar, Dim >::vector().
template<typename Scalar , int Dim> Transform< Scalar, Dim > & Eigen::Transform< Scalar, Dim >::operator= (const ScalingType & t) inline
Definition at line 549 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::Scaling< _Scalar, _Dim >::coeffs().
template<typename _Scalar, int _Dim> template<typename Derived > Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const RotationBase< Derived, Dim > & r) inline
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const Transform< _Scalar, _Dim > & other) inline
Definition at line 260 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const EigenBase< OtherDerived > & other) inline
Set *this from a Dim^2 or (Dim+1)^2 matrix.
Definition at line 278 of file Transform.h.
References Eigen::EigenBase< Derived >::derived(), and EIGEN_STATIC_ASSERT.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const ReturnByValue< OtherDerived > & other) inline
Definition at line 344 of file Transform.h.
References Eigen::ReturnByValue< Derived >::evalTo().
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const TranslationType & t) inline
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::operator= (const UniformScaling< Scalar > & t) inline
Definition at line 958 of file Transform.h.
References Eigen::UniformScaling< _Scalar >::factor(), and Eigen::PlainObjectBase< Derived >::setZero().
template<typename _Scalar, int _Dim> template<typename Derived > Transform& Eigen::Transform< _Scalar, _Dim >::operator= (const RotationBase< Derived, Dim > & r) inline
template<typename _Scalar, int _Dim> template<typename Derived > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::operator= (const RotationBase< Derived, Dim > & r) inline
Definition at line 567 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename Derived > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::operator= (const RotationBase< Derived, Dim > & r) inline
Definition at line 968 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename RotationType > Transform& Eigen::Transform< _Scalar, _Dim >::prerotate (const RotationType & rotation) inline
template<typename _Scalar, int _Dim> template<typename RotationType > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::prerotate (const RotationType & rotation)
Applies on the left the rotation represented by the rotation rotation to *this and returns a reference to *this.
See rotate() for further details.
See Also
rotate()
Definition at line 490 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename RotationType > Transform& Eigen::Transform< _Scalar, _Dim >::prerotate (const RotationType & rotation) inline
template<typename _Scalar, int _Dim> template<typename RotationType > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::prerotate (const RotationType & rotation)
Applies on the left the rotation represented by the rotation rotation to *this and returns a reference to *this.
See rotate() for further details.
See Also
rotate()
Definition at line 898 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::prescale (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), and Eigen::Scaling< _Scalar, _Dim >::operator*().
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::prescale (Scalar s) inline
Applies on the left a uniform scale of a factor c to *this and returns a reference to *this.
See Also
scale(Scalar)
Definition at line 420 of file Transform.h.
References Eigen::TopLeft.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::prescale (const MatrixBase< OtherDerived > & other)
Applies on the left the non uniform scale transformation represented by the vector other to *this and returns a reference to *this.
See Also
scale()
Definition at line 408 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal(), and EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::prescale (const MatrixBase< OtherDerived > & other) inline
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::prescale (Scalar s) inline
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::prescale (const MatrixBase< OtherDerived > & other)
Applies on the left the non uniform scale transformation represented by the vector other to *this and returns a reference to *this.
See Also
scale()
Definition at line 811 of file Transform.h.
References EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Isometry.
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::preshear (Scalar sx, Scalar sy)
Applies on the left the shear transformation represented by the vector other to *this and returns a reference to *this.
Warning
2D only.
See Also
shear()
Definition at line 519 of file Transform.h.
References EIGEN_STATIC_ASSERT.
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::preshear (Scalar sx, Scalar sy)
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::pretranslate (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::Translation< Scalar, Dim >::operator*().
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::pretranslate (const MatrixBase< OtherDerived > & other)
Applies on the left the translation matrix represented by the vector other to *this and returns a reference to *this.
See Also
translate()
Definition at line 447 of file Transform.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::pretranslate (const MatrixBase< OtherDerived > & other) inline
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::pretranslate (const MatrixBase< OtherDerived > & other)
Applies on the left the translation matrix represented by the vector other to *this and returns a reference to *this.
See Also
translate()
Definition at line 852 of file Transform.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Projective.
template<typename _Scalar, int _Dim> template<typename RotationType > Transform& Eigen::Transform< _Scalar, _Dim >::rotate (const RotationType & rotation) inline
Referenced by Eigen::Transform< _Scalar, _Dim >::operator*(), and Eigen::Transform< _Scalar, _Dim >::operator*=().
template<typename _Scalar, int _Dim> template<typename RotationType > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::rotate (const RotationType & rotation)
Applies on the right the rotation represented by the rotation rotation to *this and returns a reference to *this.
The template parameter RotationType is the type of the rotation which must be known by ei_toRotationMatrix<>.
Natively supported types includes:
any scalar (2D),
a Dim x Dim matrix expression,
a Quaternion (3D),
a AngleAxis (3D)
This mechanism is easily extendable to support user types such as Euler angles, or a pair of Quaternion for 4D rotations.
See Also
rotate(Scalar), class Quaternion, class AngleAxis, prerotate(RotationType)
Definition at line 474 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename RotationType > Transform& Eigen::Transform< _Scalar, _Dim >::rotate (const RotationType & rotation) inline
template<typename _Scalar, int _Dim> template<typename RotationType > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::rotate (const RotationType & rotation)
Applies on the right the rotation represented by the rotation rotation to *this and returns a reference to *this.
The template parameter RotationType is the type of the rotation which must be known by internal::toRotationMatrix<>.
Natively supported types includes:
any scalar (2D),
a Dim x Dim matrix expression,
a Quaternion (3D),
a AngleAxis (3D)
This mechanism is easily extendable to support user types such as Euler angles, or a pair of Quaternion for 4D rotations.
See Also
rotate(Scalar), class Quaternion, class AngleAxis, prerotate(RotationType)
Definition at line 882 of file Transform.h.
template<typename Scalar , int Dim, int Mode, int Options> const Transform< Scalar, Dim, Mode, Options >::LinearMatrixType Eigen::Transform< Scalar, Dim, Mode, Options >::rotation () const
Returns
the rotation part of the transformation
See Also
computeRotationScaling(), computeScalingRotation(), class SVD
Returns
the rotation part of the transformation
See Also
computeRotationScaling(), computeScalingRotation(), class SVD
Definition at line 598 of file Transform.h.
template<typename _Scalar, int _Dim> const LinearMatrixType Eigen::Transform< _Scalar, _Dim >::rotation () const
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::scale (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::Transform< _Scalar, _Dim >::operator*(), and Eigen::Transform< _Scalar, _Dim >::operator*=().
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::scale (Scalar s) inline
Applies on the right a uniform scale of a factor c to *this and returns a reference to *this.
See Also
prescale(Scalar)
Definition at line 395 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::scale (const MatrixBase< OtherDerived > & other)
Applies on the right the non uniform scale transformation represented by the vector other to *this and returns a reference to *this.
See Also
prescale()
Definition at line 383 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal(), and EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::scale (const MatrixBase< OtherDerived > & other) inline
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::scale (Scalar s) inline
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::scale (const MatrixBase< OtherDerived > & other)
Applies on the right the non uniform scale transformation represented by the vector other to *this and returns a reference to *this.
See Also
prescale()
Definition at line 784 of file Transform.h.
References Eigen::MatrixBase< Derived >::asDiagonal(), EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::Isometry.
template<typename _Scalar, int _Dim> void Eigen::Transform< _Scalar, _Dim >::setIdentity () inline
See Also
MatrixBase::setIdentity()
Definition at line 183 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
Referenced by Eigen::Transform< _Scalar, _Dim >::operator=().
template<typename _Scalar, int _Dim> void Eigen::Transform< _Scalar, _Dim >::setIdentity () inline
See Also
MatrixBase::setIdentity()
Definition at line 492 of file Transform.h.
template<typename Scalar , int Dim, int Mode, int Options> Transform< Scalar, Dim, Mode, Options > & Eigen::Transform< Scalar, Dim, Mode, Options >::shear (Scalar sx, Scalar sy)
Applies on the right the shear transformation represented by the vector other to *this and returns a reference to *this.
Warning
2D only.
See Also
preshear()
Definition at line 504 of file Transform.h.
References EIGEN_STATIC_ASSERT.
template<typename _Scalar, int _Dim> Transform& Eigen::Transform< _Scalar, _Dim >::shear (Scalar sx, Scalar sy)
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::translate (const MatrixBase< OtherDerived > & other) inline
Referenced by Eigen::Transform< _Scalar, _Dim >::operator*(), and Eigen::Transform< _Scalar, _Dim >::operator*=().
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim>& Eigen::Transform< _Scalar, _Dim >::translate (const MatrixBase< OtherDerived > & other)
Applies on the right the translation matrix represented by the vector other to *this and returns a reference to *this.
See Also
pretranslate()
Definition at line 433 of file Transform.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform& Eigen::Transform< _Scalar, _Dim >::translate (const MatrixBase< OtherDerived > & other) inline
template<typename _Scalar, int _Dim> template<typename OtherDerived > Transform<Scalar,Dim,Mode,Options>& Eigen::Transform< _Scalar, _Dim >::translate (const MatrixBase< OtherDerived > & other)
Applies on the right the translation matrix represented by the vector other to *this and returns a reference to *this.
See Also
pretranslate()
Definition at line 838 of file Transform.h.
References EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE.
template<typename _Scalar, int _Dim> ConstTranslationPart Eigen::Transform< _Scalar, _Dim >::translation () const inline
Returns
a read-only expression of the translation vector of the transformation
Definition at line 153 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
Referenced by Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< Scalar, Dim >::operator*(), Eigen::Scaling< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::construct_from_matrix< OtherDerived, true >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, Dim >::run(), Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::run(), Eigen::internal::transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >::run(), Eigen::internal::transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, Dim, HDim >::run(), Eigen::internal::transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >::run(), Eigen::Hyperplane< _Scalar, _AmbientDim >::transform(), and Eigen::Transform< _Scalar, _Dim >::Transform().
template<typename _Scalar, int _Dim> TranslationPart Eigen::Transform< _Scalar, _Dim >::translation () inline
Returns
a writable expression of the translation vector of the transformation
Definition at line 155 of file Transform.h.
References Eigen::Transform< _Scalar, _Dim >::m_matrix.
template<typename _Scalar, int _Dim> ConstTranslationPart Eigen::Transform< _Scalar, _Dim >::translation () const inline
Returns
a read-only expression of the translation vector of the transformation
Definition at line 382 of file Transform.h.
template<typename _Scalar, int _Dim> TranslationPart Eigen::Transform< _Scalar, _Dim >::translation () inline
Returns
a writable expression of the translation vector of the transformation
Definition at line 384 of file Transform.h.
template<typename _Scalar, int _Dim> Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,1> Eigen::Transform< _Scalar, _Dim >::translationExt () inline
Definition at line 618 of file Transform.h.
template<typename _Scalar, int _Dim> const Block<MatrixType,int(Mode)==int(Projective)?HDim:Dim,1> Eigen::Transform< _Scalar, _Dim >::translationExt () const inline
Definition at line 624 of file Transform.h.
Friends And Related Function Documentation
template<typename _Scalar, int _Dim> template<typename OtherDerived > const ProductReturnType<OtherDerived,MatrixType>::Type operator* (const MatrixBase< OtherDerived > & a, const Transform< _Scalar, _Dim > & b) friend
Returns
the product expression of a transformation matrix a times a transform b The transformation matrix a must have a Dim+1 x Dim+1 sizes.
Definition at line 174 of file Transform.h.
template<typename _Scalar, int _Dim> Transform operator* (const LinearMatrixType & mat, const Transform< _Scalar, _Dim > & t) friend
Definition at line 220 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename OtherDerived > const internal::transform_left_product_impl<OtherDerived,Mode,Options,_Dim,_Dim+1>::ResultType operator* (const EigenBase< OtherDerived > & a, const Transform< _Scalar, _Dim > & b) friend
Returns
the product expression of a transformation matrix a times a transform b
The left hand side other might be either:
a linear transformation matrix of size Dim x Dim,
an affine transformation matrix of size Dim x Dim+1,
a general transformation matrix of size Dim+1 x Dim+1.
Definition at line 412 of file Transform.h.
template<typename _Scalar, int _Dim> template<typename DiagonalDerived > TransformTimeDiagonalReturnType operator* (const DiagonalBase< DiagonalDerived > & a, const Transform< _Scalar, _Dim > & b) friend
Returns
The product expression of a diagonal matrix a times a transform b
The lhs diagonal matrix is interpreted as an affine scaling transformation. The product results in a Transform of the same type (mode) as the lhs only if the lhs mode is no isometry. In that case, the returned transform is an affinity.
Definition at line 438 of file Transform.h.
Member Data Documentation
template<typename _Scalar, int _Dim> MatrixType Eigen::Transform< _Scalar, _Dim >::m_matrix protected
Definition at line 74 of file Transform.h.
Referenced by Eigen::Transform< _Scalar, _Dim >::data(), Eigen::Transform< _Scalar, _Dim >::isApprox(), Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Transform< _Scalar, _Dim >::matrix(), Eigen::Transform< _Scalar, _Dim >::operator()(), Eigen::Transform< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator=(), Eigen::Transform< _Scalar, _Dim >::setIdentity(), Eigen::Transform< _Scalar, _Dim >::Transform(), and Eigen::Transform< _Scalar, _Dim >::translation().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigen2Support/Geometry/Transform.h