LIA_RAL: SequenceDecoder Class Reference
SequenceDecoder Class Reference
#include <SequenceExtractor.h>
Public Member Functions
SequenceDecoder (short int)
SequenceDecoder (const SequenceDecoder &)
SequenceDecoder operator= (const SequenceDecoder &)
~SequenceDecoder ()
short int getNbInputSymb ()
short int getNbOutputSeq ()
void setNbOutputSeq (unsigned long nb)
unsigned long getNbOutputSeqPart ()
void addSequence (Seq &, const short int)
void show ()
void toFile (ostream &)
void save (ostream &)
void load (istream &)
void decode (String, ostream &, unsigned long, unsigned long, bool, bool, BNgram &)
Private Member Functions
void _freeTree (SequenceDecoderNode *seed)
SequenceDecoderNode * _newNode (const SymbTab &symbTab, const short int outputSymb, SequenceDecoderNode *ch, SequenceDecoderNode *br)
SequenceDecoderNode * _findInsert (const SymbTab &symbTab, SequenceDecoderNode *ptr)
void _show (SequenceDecoderNode *, short int)
void _toFile (SequenceDecoderNode *, short int, Seq &, ostream &)
void _save (SequenceDecoderNode *, ostream &)
SequenceDecoderNode * _load (istream &)
bool _decode (SequenceDecoderNode *ptr, ReadMemory &inp, ostream &outputFile, unsigned long &begin, short int &)
Private Attributes
short int _nbInputSymb
unsigned long _nbOutputSeqPart
unsigned long _nbOutputSeq
SequenceDecoderNode * _seed
Detailed Description
Definition at line 166 of file SequenceExtractor.h.
Constructor & Destructor Documentation
SequenceDecoder::SequenceDecoder (short int nbInputSymb)
Definition at line 452 of file SequenceExtractor.cpp.
References _nbInputSymb, _nbOutputSeq, _nbOutputSeqPart, and _seed.
SequenceDecoder::SequenceDecoder (const SequenceDecoder & obj)
Definition at line 458 of file SequenceExtractor.cpp.
SequenceDecoder::~SequenceDecoder ()
Definition at line 466 of file SequenceExtractor.cpp.
References _freeTree(), and _seed.
Member Function Documentation
bool SequenceDecoder::_decode (SequenceDecoderNode * ptr, ReadMemory & inp, ostream & outputFile, unsigned long & begin, short int & decodedSeq) private
Definition at line 600 of file SequenceExtractor.cpp.
References SequenceDecoderNode::br, SequenceDecoderNode::ch, debug, ReadMemory::eof(), ReadMemory::getCurrentSymb(), ReadMemory::getIdx(), SymbTab::isIn(), ReadMemory::lecture(), SequenceDecoderNode::outputSymb, ReadMemory::setIdx(), and SequenceDecoderNode::symbTab.
Referenced by decode().
SequenceDecoderNode * SequenceDecoder::_findInsert (const SymbTab & symbTab, SequenceDecoderNode * ptr) private
Definition at line 485 of file SequenceExtractor.cpp.
References _newNode(), SequenceDecoderNode::br, and SequenceDecoderNode::symbTab.
Referenced by addSequence().
void SequenceDecoder::_freeTree (SequenceDecoderNode * seed) private
Definition at line 469 of file SequenceExtractor.cpp.
References SequenceDecoderNode::br, SequenceDecoderNode::ch, and SequenceDecoderNode::symbTab.
Referenced by ~SequenceDecoder().
SequenceDecoderNode * SequenceDecoder::_load (istream & inputFile) private
Definition at line 544 of file SequenceExtractor.cpp.
References _nbInputSymb, _newNode(), SequenceDecoderNode::br, SequenceDecoderNode::ch, SequenceDecoderNode::outputSymb, SymbTab::setSymb(), and SequenceDecoderNode::symbTab.
Referenced by load().
SequenceDecoderNode * SequenceDecoder::_newNode (const SymbTab & symbTab, const short int outputSymb, SequenceDecoderNode * ch, SequenceDecoderNode * br) private
Definition at line 476 of file SequenceExtractor.cpp.
References SequenceDecoderNode::br, SequenceDecoderNode::ch, SequenceDecoderNode::outputSymb, and SequenceDecoderNode::symbTab.
Referenced by _findInsert(), and _load().
void SequenceDecoder::_save (SequenceDecoderNode * ptr, ostream & outputFile) private
Definition at line 578 of file SequenceExtractor.cpp.
References SequenceDecoderNode::br, SequenceDecoderNode::ch, SymbTab::getNbSymb(), SymbTab::isIn(), SequenceDecoderNode::outputSymb, and SequenceDecoderNode::symbTab.
Referenced by save().
void SequenceDecoder::_show (SequenceDecoderNode * ptr, short int order) private
Definition at line 511 of file SequenceExtractor.cpp.
References SequenceDecoderNode::br, SequenceDecoderNode::ch, SequenceDecoderNode::outputSymb, show(), and SequenceDecoderNode::symbTab.
Referenced by show().
void SequenceDecoder::_toFile (SequenceDecoderNode * ptr, short int symb, Seq & currentSeq, ostream & outputFile) private
Definition at line 520 of file SequenceExtractor.cpp.
References Seq::add(), SequenceDecoderNode::br, SequenceDecoderNode::ch, Seq::getLength(), Seq::init(), SequenceDecoderNode::outputSymb, and SequenceDecoderNode::symbTab.
Referenced by toFile().
void SequenceDecoder::addSequence (Seq & sequence, const short int outputSymb)
Definition at line 495 of file SequenceExtractor.cpp.
References _findInsert(), _nbOutputSeqPart, _seed, SequenceDecoderNode::ch, Seq::getLength(), and SequenceDecoderNode::outputSymb.
Referenced by sequenceExtractor().
void SequenceDecoder::decode (String inputFilename, ostream & outputFile, unsigned long segBegin, unsigned long segLength, bool overlapMode, bool ngramMode, BNgram & ngram)
Definition at line 641 of file SequenceExtractor.cpp.
References _decode(), _seed, BNgram::addSymb(), BNgram::beginSeq(), BNgram::endSeq(), ReadMemory::getCurrentSymb(), ReadMemory::getIdx(), ReadMemory::lecture(), ReadMemory::notEof(), ReadMemory::setIdx(), and verbose.
Referenced by sequenceDecoder().
short int SequenceDecoder::getNbInputSymb () inline
Definition at line 184 of file SequenceExtractor.h.
References _nbInputSymb.
short int SequenceDecoder::getNbOutputSeq () inline
Definition at line 185 of file SequenceExtractor.h.
References _nbOutputSeq.
unsigned long SequenceDecoder::getNbOutputSeqPart () inline
Definition at line 187 of file SequenceExtractor.h.
References _nbOutputSeqPart.
void SequenceDecoder::load (istream & inputFile)
Definition at line 572 of file SequenceExtractor.cpp.
References _load(), _nbInputSymb, _nbOutputSeq, _nbOutputSeqPart, and _seed.
Referenced by sequenceDecoder().
SequenceDecoder SequenceDecoder::operator= (const SequenceDecoder & obj)
Definition at line 462 of file SequenceExtractor.cpp.
void SequenceDecoder::save (ostream & outputFile)
Definition at line 593 of file SequenceExtractor.cpp.
References _nbInputSymb, _nbOutputSeq, _nbOutputSeqPart, _save(), and _seed.
Referenced by sequenceExtractor().
void SequenceDecoder::setNbOutputSeq (unsigned long nb) inline
Definition at line 186 of file SequenceExtractor.h.
References _nbOutputSeq.
Referenced by sequenceExtractor().
void SequenceDecoder::show ()
Definition at line 508 of file SequenceExtractor.cpp.
References _seed, and _show().
Referenced by _show(), and sequenceExtractor().
void SequenceDecoder::toFile (ostream & outputFile)
Definition at line 537 of file SequenceExtractor.cpp.
References _nbInputSymb, _nbOutputSeq, _seed, _toFile(), and Seq::init().
Referenced by sequenceExtractor().
Member Data Documentation
short int SequenceDecoder::_nbInputSymb private
Definition at line 167 of file SequenceExtractor.h.
Referenced by _load(), getNbInputSymb(), load(), save(), SequenceDecoder(), and toFile().
unsigned long SequenceDecoder::_nbOutputSeq private
Definition at line 169 of file SequenceExtractor.h.
Referenced by getNbOutputSeq(), load(), save(), SequenceDecoder(), setNbOutputSeq(), and toFile().
unsigned long SequenceDecoder::_nbOutputSeqPart private
Definition at line 168 of file SequenceExtractor.h.
Referenced by addSequence(), getNbOutputSeqPart(), load(), save(), and SequenceDecoder().
SequenceDecoderNode* SequenceDecoder::_seed private
Definition at line 170 of file SequenceExtractor.h.
Referenced by addSequence(), decode(), load(), save(), SequenceDecoder(), show(), toFile(), and ~SequenceDecoder().
The documentation for this class was generated from the following files:
LIA_Utils/SequenceExtractor/include/SequenceExtractor.h
LIA_Utils/SequenceExtractor/src/SequenceExtractor.cpp