LIA_RAL: CommonPartTree Class Reference
CommonPartTree Class Reference
#include <SequenceExtractor.h>
Public Member Functions
CommonPartTree ()
CommonPartTree (const CommonPartTree &)
CommonPartTree operator= (const CommonPartTree &)
~CommonPartTree ()
void addNGram (NGram &nGram)
unsigned long findMaxSeq (Seq &)
unsigned long findMaxEndSeq (Seq &)
void suppressSeq (Seq &seq)
unsigned long getTotalChildCount ()
void setTotalCount (unsigned long total)
unsigned long getTotalCount ()
void show ()
Private Member Functions
void _freeTree (CommonPartTreeNode *seed)
CommonPartTreeNode * _newNode (const short int symb, const unsigned long count, CommonPartTreeNode *ch, CommonPartTreeNode *br)
CommonPartTreeNode * _findInsert (const short int symb, unsigned long count, CommonPartTreeNode *ptr)
unsigned long _findMaxSeq (CommonPartTreeNode *ptr, Seq &seq, short int &)
CommonPartTreeNode * _suppressSeq (CommonPartTreeNode *ptr, Seq &seq, short int order, unsigned long &childCountDelta)
void _show (CommonPartTreeNode *ptr, unsigned long order)
CommonPartTreeNode * _findPartSeq (Seq &, short int, CommonPartTreeNode *)
Private Attributes
CommonPartTreeNode * _seed
unsigned long _totalCount
unsigned long _totalChildCount
Detailed Description
Definition at line 130 of file SequenceExtractor.h.
Constructor & Destructor Documentation
CommonPartTree::CommonPartTree ()
Definition at line 75 of file SequenceExtractor.cpp.
References _seed, _totalChildCount, and _totalCount.
CommonPartTree::CommonPartTree (const CommonPartTree & obj)
Definition at line 81 of file SequenceExtractor.cpp.
CommonPartTree::~CommonPartTree ()
Definition at line 90 of file SequenceExtractor.cpp.
References _freeTree(), and _seed.
Member Function Documentation
CommonPartTreeNode * CommonPartTree::_findInsert (const short int symb, unsigned long count, CommonPartTreeNode * ptr) private
Definition at line 110 of file SequenceExtractor.cpp.
References _newNode(), CommonPartTreeNode::br, and CommonPartTreeNode::symb.
Referenced by addNGram().
unsigned long CommonPartTree::_findMaxSeq (CommonPartTreeNode * ptr, Seq & seq, short int & order) private
Definition at line 154 of file SequenceExtractor.cpp.
References CommonPartTreeNode::br, CommonPartTreeNode::ch, CommonPartTreeNode::count, Seq::setLength(), and CommonPartTreeNode::symb.
Referenced by findMaxEndSeq(), and findMaxSeq().
CommonPartTreeNode * CommonPartTree::_findPartSeq (Seq & seq, short int order, CommonPartTreeNode * ptr) private
Definition at line 139 of file SequenceExtractor.cpp.
References _seed, CommonPartTreeNode::br, CommonPartTreeNode::ch, Seq::getLength(), and CommonPartTreeNode::symb.
Referenced by findMaxEndSeq().
void CommonPartTree::_freeTree (CommonPartTreeNode * seed) private
Definition at line 93 of file SequenceExtractor.cpp.
References CommonPartTreeNode::br, and CommonPartTreeNode::ch.
Referenced by ~CommonPartTree().
CommonPartTreeNode * CommonPartTree::_newNode (const short int symb, const unsigned long count, CommonPartTreeNode * ch, CommonPartTreeNode * br) private
Definition at line 99 of file SequenceExtractor.cpp.
References CommonPartTreeNode::br, CommonPartTreeNode::ch, CommonPartTreeNode::count, CommonPartTreeNode::symb, and CommonPartTreeNode::totalChildCount.
Referenced by _findInsert().
void CommonPartTree::_show (CommonPartTreeNode * ptr, unsigned long order) private
Definition at line 238 of file SequenceExtractor.cpp.
References CommonPartTreeNode::br, CommonPartTreeNode::ch, CommonPartTreeNode::count, CommonPartTreeNode::symb, and CommonPartTreeNode::totalChildCount.
Referenced by show().
CommonPartTreeNode * CommonPartTree::_suppressSeq (CommonPartTreeNode * ptr, Seq & seq, short int order, unsigned long & childCountDelta) private
Definition at line 199 of file SequenceExtractor.cpp.
References CommonPartTreeNode::br, CommonPartTreeNode::ch, CommonPartTreeNode::count, Seq::getLength(), CommonPartTreeNode::symb, and CommonPartTreeNode::totalChildCount.
Referenced by suppressSeq().
void CommonPartTree::addNGram (NGram & nGram)
Definition at line 121 of file SequenceExtractor.cpp.
References _findInsert(), _seed, _totalChildCount, CommonPartTreeNode::ch, NGram::getCount(), NGram::getOrder(), NGram::getSize(), NGram::getSymbol(), and CommonPartTreeNode::totalChildCount.
unsigned long CommonPartTree::findMaxEndSeq (Seq & seq)
Definition at line 185 of file SequenceExtractor.cpp.
References _findMaxSeq(), _findPartSeq(), _seed, CommonPartTreeNode::ch, CommonPartTreeNode::count, findMaxSeq(), and Seq::getLength().
unsigned long CommonPartTree::findMaxSeq (Seq & seq)
Definition at line 178 of file SequenceExtractor.cpp.
References _findMaxSeq(), and _seed.
Referenced by findMaxEndSeq().
unsigned long CommonPartTree::getTotalChildCount () inline
Definition at line 151 of file SequenceExtractor.h.
References _totalChildCount.
unsigned long CommonPartTree::getTotalCount () inline
Definition at line 153 of file SequenceExtractor.h.
References _totalCount.
CommonPartTree CommonPartTree::operator= (const CommonPartTree & obj)
Definition at line 85 of file SequenceExtractor.cpp.
void CommonPartTree::setTotalCount (unsigned long total) inline
Definition at line 152 of file SequenceExtractor.h.
References _totalCount.
void CommonPartTree::show ()
Definition at line 244 of file SequenceExtractor.cpp.
References _seed, _show(), _totalChildCount, and _totalCount.
void CommonPartTree::suppressSeq (Seq & seq)
Definition at line 231 of file SequenceExtractor.cpp.
References _seed, _suppressSeq(), _totalChildCount, and Seq::getLength().
Member Data Documentation
CommonPartTreeNode* CommonPartTree::_seed private
Definition at line 131 of file SequenceExtractor.h.
Referenced by _findPartSeq(), addNGram(), CommonPartTree(), findMaxEndSeq(), findMaxSeq(), show(), suppressSeq(), and ~CommonPartTree().
unsigned long CommonPartTree::_totalChildCount private
Definition at line 133 of file SequenceExtractor.h.
Referenced by addNGram(), CommonPartTree(), getTotalChildCount(), show(), and suppressSeq().
unsigned long CommonPartTree::_totalCount private
Definition at line 132 of file SequenceExtractor.h.
Referenced by CommonPartTree(), getTotalCount(), setTotalCount(), and show().
The documentation for this class was generated from the following files:
LIA_Utils/SequenceExtractor/include/SequenceExtractor.h
LIA_Utils/SequenceExtractor/src/SequenceExtractor.cpp