LIA_RAL: Eigen::AlignedBox< _Scalar, _AmbientDim > Class Template Reference
Eigen::AlignedBox< _Scalar, _AmbientDim > Class Template Reference
Geometry_Module
An axis aligned box.
#include <AlignedBox.h>
Public Types
enum { AmbientDimAtCompileTime = _AmbientDim }
enum { AmbientDimAtCompileTime = _AmbientDim }
enum CornerType {
Min =0, Max =1, BottomLeft =0, BottomRight =1,
TopLeft =2, TopRight =3, BottomLeftFloor =0, BottomRightFloor =1,
TopLeftFloor =2, TopRightFloor =3, BottomLeftCeil =4, BottomRightCeil =5,
TopLeftCeil =6, TopRightCeil =7
}
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< Scalar,
AmbientDimAtCompileTime, 1 > VectorType
typedef _Scalar Scalar
typedef NumTraits< Scalar > ScalarTraits
typedef DenseIndex Index
typedef ScalarTraits::Real RealScalar
typedef ScalarTraits::NonInteger NonInteger
typedef Matrix< Scalar,
AmbientDimAtCompileTime, 1 > VectorType
Public Member Functions
AlignedBox ()
AlignedBox (int _dim)
AlignedBox (const VectorType &_min, const VectorType &_max)
AlignedBox (const VectorType &p)
~AlignedBox ()
int dim () const
bool isNull () const
void setNull ()
const VectorType &() min () const
VectorType &() min ()
const VectorType &() max () const
VectorType &() max ()
bool contains (const VectorType &p) const
bool contains (const AlignedBox &b) const
AlignedBox & extend (const VectorType &p)
AlignedBox & extend (const AlignedBox &b)
AlignedBox & clamp (const AlignedBox &b)
AlignedBox & translate (const VectorType &t)
Scalar squaredExteriorDistance (const VectorType &p) const
Scalar exteriorDistance (const VectorType &p) const
template<typename NewScalarType >
internal::cast_return_type
< AlignedBox, AlignedBox
< NewScalarType,
AmbientDimAtCompileTime >
>::type cast () const
template<typename OtherScalarType >
AlignedBox (const AlignedBox< OtherScalarType, AmbientDimAtCompileTime > &other)
bool isApprox (const AlignedBox &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
AlignedBox ()
AlignedBox (Index _dim)
template<typename OtherVectorType1 , typename OtherVectorType2 >
AlignedBox (const OtherVectorType1 &_min, const OtherVectorType2 &_max)
template<typename Derived >
AlignedBox (const MatrixBase< Derived > &a_p)
~AlignedBox ()
Index dim () const
bool isNull () const
void setNull ()
bool isEmpty () const
void setEmpty ()
const VectorType &() min () const
VectorType &() min ()
const VectorType &() max () const
VectorType &() max ()
const CwiseUnaryOp
< internal::scalar_quotient1_op
< Scalar >, const
CwiseBinaryOp
< internal::scalar_sum_op
< Scalar >, const VectorType,
const VectorType > > center () const
const CwiseBinaryOp
< internal::scalar_difference_op
< Scalar >, const VectorType,
const VectorType > sizes () const
Scalar volume () const
CwiseBinaryOp
< internal::scalar_difference_op
< Scalar >, const VectorType,
const VectorType > diagonal () const
VectorType corner (CornerType corner) const
VectorType sample () const
template<typename Derived >
bool contains (const MatrixBase< Derived > &a_p) const
bool contains (const AlignedBox &b) const
template<typename Derived >
AlignedBox & extend (const MatrixBase< Derived > &a_p)
AlignedBox & extend (const AlignedBox &b)
AlignedBox & clamp (const AlignedBox &b)
AlignedBox intersection (const AlignedBox &b) const
AlignedBox merged (const AlignedBox &b) const
template<typename Derived >
AlignedBox & translate (const MatrixBase< Derived > &a_t)
template<typename Derived >
Scalar squaredExteriorDistance (const MatrixBase< Derived > &a_p) const
Scalar squaredExteriorDistance (const AlignedBox &b) const
template<typename Derived >
NonInteger exteriorDistance (const MatrixBase< Derived > &p) const
NonInteger exteriorDistance (const AlignedBox &b) const
template<typename NewScalarType >
internal::cast_return_type
< AlignedBox, AlignedBox
< NewScalarType,
AmbientDimAtCompileTime >
>::type cast () const
template<typename OtherScalarType >
AlignedBox (const AlignedBox< OtherScalarType, AmbientDimAtCompileTime > &other)
bool isApprox (const AlignedBox &other, RealScalar prec=ScalarTraits::dummy_precision()) const
Protected Attributes
VectorType m_min
VectorType m_max
Detailed Description
template<typename _Scalar, int _AmbientDim>
class Eigen::AlignedBox< _Scalar, _AmbientDim >
An axis aligned box.
Parameters
_Scalar the type of the scalar coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic.
This class represents an axis aligned box as a pair of the minimal and maximal corners.
Parameters
_Scalar the type of the scalar coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic.
This class represents an axis aligned box as a pair of the minimal and maximal corners.
Definition at line 27 of file AlignedBox.h.
Member Typedef Documentation
template<typename _Scalar, int _AmbientDim> typedef DenseIndex Eigen::AlignedBox< _Scalar, _AmbientDim >::Index
Definition at line 35 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef ScalarTraits::NonInteger Eigen::AlignedBox< _Scalar, _AmbientDim >::NonInteger
Definition at line 37 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef NumTraits<Scalar>::Real Eigen::AlignedBox< _Scalar, _AmbientDim >::RealScalar
Definition at line 33 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef ScalarTraits::Real Eigen::AlignedBox< _Scalar, _AmbientDim >::RealScalar
Definition at line 36 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef _Scalar Eigen::AlignedBox< _Scalar, _AmbientDim >::Scalar
Definition at line 32 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef _Scalar Eigen::AlignedBox< _Scalar, _AmbientDim >::Scalar
Definition at line 33 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef NumTraits<Scalar> Eigen::AlignedBox< _Scalar, _AmbientDim >::ScalarTraits
Definition at line 34 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,AmbientDimAtCompileTime,1> Eigen::AlignedBox< _Scalar, _AmbientDim >::VectorType
Definition at line 34 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> typedef Matrix<Scalar,AmbientDimAtCompileTime,1> Eigen::AlignedBox< _Scalar, _AmbientDim >::VectorType
Definition at line 38 of file AlignedBox.h.
Member Enumeration Documentation
template<typename _Scalar, int _AmbientDim> anonymous enum
Enumerator
AmbientDimAtCompileTime
Definition at line 31 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> anonymous enum
Enumerator
AmbientDimAtCompileTime
Definition at line 32 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> enum Eigen::AlignedBox::CornerType
Define constants to name the corners of a 1D, 2D or 3D axis aligned bounding box
Enumerator
Min
1D names
Max
BottomLeft
Added names for 2D
BottomRight
TopLeft
TopRight
BottomLeftFloor
Added names for 3D
BottomRightFloor
TopLeftFloor
TopRightFloor
BottomLeftCeil
BottomRightCeil
TopLeftCeil
TopRightCeil
Definition at line 41 of file AlignedBox.h.
Constructor & Destructor Documentation
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox () inline explicit
Default constructor initializing a null box.
Definition at line 37 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AmbientDimAtCompileTime, Eigen::Dynamic, and Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull().
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::cast(), Eigen::AlignedBox< _Scalar, _AmbientDim >::intersection(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::merged().
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (int _dim) inline explicit
Constructs a null box with _dim the dimension of the ambient space.
Definition at line 41 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull().
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (const VectorType & _min, const VectorType & _max) inline
Constructs a box with extremities _min and _max.
Definition at line 45 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (const VectorType & p) inline explicit
Constructs a box containing a single point p.
Definition at line 48 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::~AlignedBox () inline
Definition at line 50 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> template<typename OtherScalarType > Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (const AlignedBox< OtherScalarType, AmbientDimAtCompileTime > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 126 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min, Eigen::AlignedBox< _Scalar, _AmbientDim >::max(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::min().
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox () inline explicit
Default constructor initializing a null box.
Definition at line 59 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AmbientDimAtCompileTime, Eigen::Dynamic, and Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty().
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (Index _dim) inline explicit
Constructs a null box with _dim the dimension of the ambient space.
Definition at line 63 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty().
template<typename _Scalar, int _AmbientDim> template<typename OtherVectorType1 , typename OtherVectorType2 > Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (const OtherVectorType1 & _min, const OtherVectorType2 & _max) inline
Constructs a box with extremities _min and _max.
Definition at line 68 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> template<typename Derived > Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (const MatrixBase< Derived > & a_p) inline explicit
Constructs a box containing a single point p.
Definition at line 72 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> Eigen::AlignedBox< _Scalar, _AmbientDim >::~AlignedBox () inline
Definition at line 79 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> template<typename OtherScalarType > Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox (const AlignedBox< OtherScalarType, AmbientDimAtCompileTime > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 275 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
Member Function Documentation
template<typename _Scalar, int _AmbientDim> template<typename NewScalarType > internal::cast_return_type<AlignedBox, AlignedBox<NewScalarType,AmbientDimAtCompileTime> >::type Eigen::AlignedBox< _Scalar, _AmbientDim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 118 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox().
template<typename _Scalar, int _AmbientDim> template<typename NewScalarType > internal::cast_return_type<AlignedBox, AlignedBox<NewScalarType,AmbientDimAtCompileTime> >::type Eigen::AlignedBox< _Scalar, _AmbientDim >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 267 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox().
template<typename _Scalar, int _AmbientDim> const CwiseUnaryOp<internal::scalar_quotient1_op<Scalar>, const CwiseBinaryOp<internal::scalar_sum_op<Scalar>, const VectorType, const VectorType> > Eigen::AlignedBox< _Scalar, _AmbientDim >::center () const inline
Returns
the center of the box
Definition at line 112 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::clamp (const AlignedBox< _Scalar, _AmbientDim > & b) inline
Clamps *this by the box b and returns a reference to *this.
Definition at line 91 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::clamp (const AlignedBox< _Scalar, _AmbientDim > & b) inline
Clamps *this by the box b and returns a reference to *this.
Definition at line 207 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::contains (const VectorType & p) const inline
Returns
true if the point p is inside the box *this.
Definition at line 75 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::contains (const AlignedBox< _Scalar, _AmbientDim > & b) const inline
Returns
true if the box b is entirely inside the box *this.
Definition at line 79 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min, Eigen::AlignedBox< _Scalar, _AmbientDim >::max(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::min().
template<typename _Scalar, int _AmbientDim> template<typename Derived > bool Eigen::AlignedBox< _Scalar, _AmbientDim >::contains (const MatrixBase< Derived > & a_p) const inline
Returns
true if the point p is inside the box *this.
Definition at line 178 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::contains (const AlignedBox< _Scalar, _AmbientDim > & b) const inline
Returns
true if the box b is entirely inside the box *this.
Definition at line 185 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> VectorType Eigen::AlignedBox< _Scalar, _AmbientDim >::corner (CornerType corner) const inline
Returns
the vertex of the bounding box at the corner defined by the corner-id corner. It works only for a 1D, 2D or 3D bounding box. For 1D bounding boxes corners are named by 2 enum constants: BottomLeft and BottomRight. For 2D bounding boxes, corners are named by 4 enum constants: BottomLeft, BottomRight, TopLeft, TopRight. For 3D bounding boxes, the following names are added: BottomLeftCeil, BottomRightCeil, TopLeftCeil, TopRightCeil.
Definition at line 142 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::dim(), EIGEN_STATIC_ASSERT, Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> CwiseBinaryOp< internal::scalar_difference_op<Scalar>, const VectorType, const VectorType> Eigen::AlignedBox< _Scalar, _AmbientDim >::diagonal () const inline
Returns
an expression for the bounding box diagonal vector if the length of the diagonal is needed: diagonal().norm() will provide it.
Definition at line 130 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::sizes().
template<typename _Scalar, int _AmbientDim> int Eigen::AlignedBox< _Scalar, _AmbientDim >::dim () const inline
Returns
the dimension in which the box holds
Definition at line 53 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AmbientDimAtCompileTime, Eigen::Dynamic, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::corner(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::sample().
template<typename _Scalar, int _AmbientDim> Index Eigen::AlignedBox< _Scalar, _AmbientDim >::dim () const inline
Returns
the dimension in which the box holds
Definition at line 82 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AmbientDimAtCompileTime, Eigen::Dynamic, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::extend (const VectorType & p) inline
Extends *this such that it contains the point p and returns a reference to *this.
Definition at line 83 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::extend (const AlignedBox< _Scalar, _AmbientDim > & b) inline
Extends *this such that it contains the box b and returns a reference to *this.
Definition at line 87 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> template<typename Derived > AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::extend (const MatrixBase< Derived > & a_p) inline
Extends *this such that it contains the point p and returns a reference to *this.
Definition at line 190 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::extend (const AlignedBox< _Scalar, _AmbientDim > & b) inline
Extends *this such that it contains the box b and returns a reference to *this.
Definition at line 199 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> Scalar Eigen::AlignedBox< _Scalar, _AmbientDim >::exteriorDistance (const VectorType & p) const inline
Returns
the distance between the point p and the box *this, and zero if p is inside the box.
See Also
squaredExteriorDistance()
Definition at line 108 of file AlignedBox.h.
References Eigen::ei_sqrt(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::squaredExteriorDistance().
template<typename _Scalar, int _AmbientDim> template<typename Derived > NonInteger Eigen::AlignedBox< _Scalar, _AmbientDim >::exteriorDistance (const MatrixBase< Derived > & p) const inline
Returns
the distance between the point p and the box *this, and zero if p is inside the box.
See Also
squaredExteriorDistance()
Definition at line 250 of file AlignedBox.h.
References sqrt(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::squaredExteriorDistance().
template<typename _Scalar, int _AmbientDim> NonInteger Eigen::AlignedBox< _Scalar, _AmbientDim >::exteriorDistance (const AlignedBox< _Scalar, _AmbientDim > & b) const inline
Returns
the distance between the boxes b and *this, and zero if the boxes intersect.
See Also
squaredExteriorDistance()
Definition at line 257 of file AlignedBox.h.
References sqrt(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::squaredExteriorDistance().
template<typename _Scalar, int _AmbientDim> AlignedBox Eigen::AlignedBox< _Scalar, _AmbientDim >::intersection (const AlignedBox< _Scalar, _AmbientDim > & b) const inline
Returns an AlignedBox that is the intersection of b and *this
Definition at line 215 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::isApprox (const AlignedBox< _Scalar, _AmbientDim > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 136 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::isApprox (const AlignedBox< _Scalar, _AmbientDim > & other, RealScalar prec = ScalarTraits::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 285 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::isEmpty () const inline
Returns
true if the box is empty.
Definition at line 91 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::isNull().
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::isNull () const inline
Returns
true if the box is null, i.e, empty.
Definition at line 56 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> bool Eigen::AlignedBox< _Scalar, _AmbientDim >::isNull () const inline
Deprecated:
use isEmpty
Definition at line 85 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::isEmpty().
template<typename _Scalar, int _AmbientDim> const VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::max () const inline
Returns
the maximal corner
Definition at line 70 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::contains().
template<typename _Scalar, int _AmbientDim> VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::max () inline
Returns
a non const reference to the maximal corner
Definition at line 72 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max.
template<typename _Scalar, int _AmbientDim> const VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::max () const inline
Returns
the maximal corner
Definition at line 105 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max.
template<typename _Scalar, int _AmbientDim> VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::max () inline
Returns
a non const reference to the maximal corner
Definition at line 107 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max.
template<typename _Scalar, int _AmbientDim> AlignedBox Eigen::AlignedBox< _Scalar, _AmbientDim >::merged (const AlignedBox< _Scalar, _AmbientDim > & b) const inline
Returns an AlignedBox that is the union of b and *this
Definition at line 219 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> const VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::min () const inline
Returns
the minimal corner
Definition at line 66 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::contains().
template<typename _Scalar, int _AmbientDim> VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::min () inline
Returns
a non const reference to the minimal corner
Definition at line 68 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> const VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::min () const inline
Returns
the minimal corner
Definition at line 101 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> VectorType&() Eigen::AlignedBox< _Scalar, _AmbientDim >::min () inline
Returns
a non const reference to the minimal corner
Definition at line 103 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> VectorType Eigen::AlignedBox< _Scalar, _AmbientDim >::sample () const inline
Returns
a random point inside the bounding box sampled with a uniform distribution
Definition at line 160 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::dim(), Eigen::GenericNumTraits< T >::IsInteger, Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> void Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty () inline
Makes *this an empty box.
Definition at line 94 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min, and Eigen::PlainObjectBase< Derived >::setConstant().
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull().
template<typename _Scalar, int _AmbientDim> void Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull () inline
Makes *this a null/empty box.
Definition at line 59 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min, max(), and Eigen::PlainObjectBase< Derived >::setConstant().
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox().
template<typename _Scalar, int _AmbientDim> void Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull () inline
Deprecated:
use setEmpty
Definition at line 88 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty().
template<typename _Scalar, int _AmbientDim> const CwiseBinaryOp< internal::scalar_difference_op<Scalar>, const VectorType, const VectorType> Eigen::AlignedBox< _Scalar, _AmbientDim >::sizes () const inline
Returns
the lengths of the sides of the bounding box. Note that this function does not get the same result for integral or floating scalar types: see
Definition at line 119 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::diagonal(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::volume().
template<typename Scalar , int AmbiantDim> Scalar Eigen::AlignedBox< Scalar, AmbiantDim >::squaredExteriorDistance (const VectorType & p) const inline
Returns
the squared distance between the point p and the box *this, and zero if p is inside the box.
See Also
exteriorDistance()
Definition at line 145 of file AlignedBox.h.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::exteriorDistance().
template<typename Scalar , int AmbientDim> template<typename Derived > Scalar Eigen::AlignedBox< Scalar, AmbientDim >::squaredExteriorDistance (const MatrixBase< Derived > & a_p) const inline
Returns
the squared distance between the point p and the box *this, and zero if p is inside the box.
See Also
exteriorDistance()
Definition at line 297 of file AlignedBox.h.
template<typename Scalar , int AmbientDim> Scalar Eigen::AlignedBox< Scalar, AmbientDim >::squaredExteriorDistance (const AlignedBox< _Scalar, _AmbientDim > & b) const inline
Returns
the squared distance between the boxes b and *this, and zero if the boxes intersect.
See Also
exteriorDistance()
Definition at line 319 of file AlignedBox.h.
template<typename _Scalar, int _AmbientDim> AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::translate (const VectorType & t) inline
Translate *this by the vector t and returns a reference to *this.
Definition at line 95 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> template<typename Derived > AlignedBox& Eigen::AlignedBox< _Scalar, _AmbientDim >::translate (const MatrixBase< Derived > & a_t) inline
Translate *this by the vector t and returns a reference to *this.
Definition at line 224 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max, and Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min.
template<typename _Scalar, int _AmbientDim> Scalar Eigen::AlignedBox< _Scalar, _AmbientDim >::volume () const inline
Returns
the volume of the bounding box
Definition at line 123 of file AlignedBox.h.
References Eigen::AlignedBox< _Scalar, _AmbientDim >::sizes().
Member Data Documentation
template<typename _Scalar, int _AmbientDim> VectorType Eigen::AlignedBox< _Scalar, _AmbientDim >::m_max protected
Definition at line 141 of file AlignedBox.h.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), Eigen::AlignedBox< _Scalar, _AmbientDim >::center(), Eigen::AlignedBox< _Scalar, _AmbientDim >::clamp(), Eigen::AlignedBox< _Scalar, _AmbientDim >::contains(), Eigen::AlignedBox< _Scalar, _AmbientDim >::corner(), Eigen::AlignedBox< _Scalar, _AmbientDim >::extend(), Eigen::AlignedBox< _Scalar, _AmbientDim >::intersection(), Eigen::AlignedBox< _Scalar, _AmbientDim >::isApprox(), Eigen::AlignedBox< _Scalar, _AmbientDim >::isEmpty(), Eigen::AlignedBox< _Scalar, _AmbientDim >::isNull(), Eigen::AlignedBox< _Scalar, _AmbientDim >::max(), Eigen::AlignedBox< _Scalar, _AmbientDim >::merged(), Eigen::AlignedBox< _Scalar, _AmbientDim >::sample(), Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty(), Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull(), Eigen::AlignedBox< _Scalar, _AmbientDim >::sizes(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::translate().
template<typename _Scalar, int _AmbientDim> VectorType Eigen::AlignedBox< _Scalar, _AmbientDim >::m_min protected
Definition at line 141 of file AlignedBox.h.
Referenced by Eigen::AlignedBox< _Scalar, _AmbientDim >::AlignedBox(), Eigen::AlignedBox< _Scalar, _AmbientDim >::center(), Eigen::AlignedBox< _Scalar, _AmbientDim >::clamp(), Eigen::AlignedBox< _Scalar, _AmbientDim >::contains(), Eigen::AlignedBox< _Scalar, _AmbientDim >::corner(), Eigen::AlignedBox< _Scalar, _AmbientDim >::dim(), Eigen::AlignedBox< _Scalar, _AmbientDim >::extend(), Eigen::AlignedBox< _Scalar, _AmbientDim >::intersection(), Eigen::AlignedBox< _Scalar, _AmbientDim >::isApprox(), Eigen::AlignedBox< _Scalar, _AmbientDim >::isEmpty(), Eigen::AlignedBox< _Scalar, _AmbientDim >::isNull(), Eigen::AlignedBox< _Scalar, _AmbientDim >::merged(), Eigen::AlignedBox< _Scalar, _AmbientDim >::min(), Eigen::AlignedBox< _Scalar, _AmbientDim >::sample(), Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty(), Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull(), Eigen::AlignedBox< _Scalar, _AmbientDim >::sizes(), and Eigen::AlignedBox< _Scalar, _AmbientDim >::translate().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigen2Support/Geometry/AlignedBox.h