LIA_RAL: Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo > Class Template Reference
Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo > Class Template Reference
#include <SparseSelfAdjointView.h>
Public Types
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef Matrix< Index, Dynamic, 1 > VectorI
typedef MatrixType::Nested MatrixTypeNested
typedef internal::remove_all
< MatrixTypeNested >::type _MatrixTypeNested
Public Types inherited from Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >
typedef internal::traits
< SparseSymmetricPermutationProduct
< MatrixType, UpLo >
>::StorageKind StorageKind
typedef internal::traits
< SparseSymmetricPermutationProduct
< MatrixType, UpLo > >::Index Index
Public Member Functions
SparseSymmetricPermutationProduct (const MatrixType &mat, const Perm &perm)
Index rows () const
Index cols () const
template<typename DestScalar , int Options, typename DstIndex >
void evalTo (SparseMatrix< DestScalar, Options, DstIndex > &_dest) const
template<typename DestType , unsigned int DestUpLo>
void evalTo (SparseSelfAdjointView< DestType, DestUpLo > &dest) const
Public Member Functions inherited from Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & derived ()
const
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & derived () const
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & const_cast_derived () const
const
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & const_derived () const
Index rows () const
Index cols () const
Index size () const
void evalTo (Dest &dst) const
void addTo (Dest &dst) const
void subTo (Dest &dst) const
void applyThisOnTheRight (Dest &dst) const
void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef PermutationMatrix
< Dynamic, Dynamic, Index > Perm
Protected Attributes
MatrixTypeNested m_matrix
const Perm & m_perm
Detailed Description
template<typename MatrixType, int UpLo>
class Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >
Definition at line 441 of file SparseSelfAdjointView.h.
Member Typedef Documentation
template<typename MatrixType, int UpLo> typedef internal::remove_all<MatrixTypeNested>::type Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::_MatrixTypeNested
Definition at line 452 of file SparseSelfAdjointView.h.
template<typename MatrixType, int UpLo> typedef MatrixType::Index Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::Index
Definition at line 446 of file SparseSelfAdjointView.h.
template<typename MatrixType, int UpLo> typedef MatrixType::Nested Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::MatrixTypeNested
Definition at line 451 of file SparseSelfAdjointView.h.
template<typename MatrixType, int UpLo> typedef PermutationMatrix<Dynamic,Dynamic,Index> Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::Perm protected
Definition at line 448 of file SparseSelfAdjointView.h.
template<typename MatrixType, int UpLo> typedef MatrixType::Scalar Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::Scalar
Definition at line 445 of file SparseSelfAdjointView.h.
template<typename MatrixType, int UpLo> typedef Matrix<Index,Dynamic,1> Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::VectorI
Definition at line 450 of file SparseSelfAdjointView.h.
Constructor & Destructor Documentation
template<typename MatrixType, int UpLo> Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::SparseSymmetricPermutationProduct (const MatrixType & mat, const Perm & perm) inline
Definition at line 454 of file SparseSelfAdjointView.h.
Member Function Documentation
template<typename MatrixType, int UpLo> Index Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::cols (void) const inline
Definition at line 459 of file SparseSelfAdjointView.h.
References Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix.
template<typename MatrixType, int UpLo> template<typename DestScalar , int Options, typename DstIndex > void Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo (SparseMatrix< DestScalar, Options, DstIndex > & _dest) const inline
Definition at line 462 of file SparseSelfAdjointView.h.
References Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices(), Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix, and Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_perm.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, UpLo >::operator=().
template<typename MatrixType, int UpLo> template<typename DestType , unsigned int DestUpLo> void Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo (SparseSelfAdjointView< DestType, DestUpLo > & dest) const inline
Definition at line 467 of file SparseSelfAdjointView.h.
References Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices(), Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix, Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_perm, and Eigen::SparseSelfAdjointView< MatrixType, UpLo >::matrix().
template<typename MatrixType, int UpLo> Index Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::rows (void) const inline
Definition at line 458 of file SparseSelfAdjointView.h.
References Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix.
Member Data Documentation
template<typename MatrixType, int UpLo> MatrixTypeNested Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix protected
Definition at line 473 of file SparseSelfAdjointView.h.
Referenced by Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::cols(), Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo(), and Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::rows().
template<typename MatrixType, int UpLo> const Perm& Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_perm protected
Definition at line 474 of file SparseSelfAdjointView.h.
Referenced by Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo().
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCore/SparseSelfAdjointView.h