LIA_RAL: Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
#include <JacobiSVD.h>
Public Types
typedef MatrixType::Index Index
Public Member Functions
void allocate (const JacobiSVD< MatrixType, HouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, HouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Attributes
HouseholderQR< MatrixType > m_qr
internal::plain_col_type
< MatrixType >::type m_workspace
Detailed Description
template<typename MatrixType>
class Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
Definition at line 248 of file JacobiSVD.h.
Member Typedef Documentation
template<typename MatrixType > typedef MatrixType::Index Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::Index
Definition at line 251 of file JacobiSVD.h.
Member Function Documentation
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate (const JacobiSVD< MatrixType, HouseholderQRPreconditioner > & svd) inline
Definition at line 253 of file JacobiSVD.h.
References Eigen::JacobiSVD< MatrixType, QRPreconditioner >::cols(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeThinU, and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::rows().
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run (JacobiSVD< MatrixType, HouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
Definition at line 263 of file JacobiSVD.h.
References Eigen::JacobiSVD< MatrixType, QRPreconditioner >::computeV(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeThinU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixV, and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
template<typename MatrixType > HouseholderQR<MatrixType> Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_qr private
Definition at line 281 of file JacobiSVD.h.
template<typename MatrixType > internal::plain_col_type<MatrixType>::type Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_workspace private
Definition at line 282 of file JacobiSVD.h.
The documentation for this class was generated from the following file:
include/Eigen/src/SVD/JacobiSVD.h