LIA_RAL: Solver_NU Class Reference
Solver_NU Class Reference
Public Member Functions
Solver_NU ()
void Solve (int l, const QMatrix &Q, const double *p, const schar *y, double *alpha, double Cp, double Cn, double eps, SolutionInfo *si, int shrinking)
Public Member Functions inherited from Solver
Solver ()
virtual ~Solver ()
void Solve (int l, const QMatrix &Q, const double *p_, const schar *y_, double *alpha_, double Cp, double Cn, double eps, SolutionInfo *si, int shrinking)
Private Member Functions
int select_working_set (int &i, int &j)
double calculate_rho ()
bool be_shrunk (int i, double Gmax1, double Gmax2, double Gmax3, double Gmax4)
void do_shrinking ()
Private Attributes
SolutionInfo * si
Additional Inherited Members
Protected Types inherited from Solver
enum { LOWER_BOUND, UPPER_BOUND, FREE }
Protected Member Functions inherited from Solver
double get_C (int i)
void update_alpha_status (int i)
bool is_upper_bound (int i)
bool is_lower_bound (int i)
bool is_free (int i)
void swap_index (int i, int j)
void reconstruct_gradient ()
Protected Attributes inherited from Solver
int active_size
schar * y
double * G
char * alpha_status
double * alpha
const QMatrix * Q
const double * QD
double eps
double Cp
double Cn
double * p
int * active_set
double * G_bar
int l
bool unshrink
Detailed Description
Definition at line 996 of file libsvm.cpp.
Constructor & Destructor Documentation
Solver_NU::Solver_NU () inline
Definition at line 999 of file libsvm.cpp.
Member Function Documentation
bool Solver_NU::be_shrunk (int i, double Gmax1, double Gmax2, double Gmax3, double Gmax4) private
Definition at line 1128 of file libsvm.cpp.
References Solver::G, Solver::is_lower_bound(), Solver::is_upper_bound(), and Solver::y.
Referenced by do_shrinking().
double Solver_NU::calculate_rho () private virtual
Reimplemented from Solver.
Definition at line 1200 of file libsvm.cpp.
References Solver::active_size, Solver::G, INF, Solver::is_lower_bound(), Solver::is_upper_bound(), max(), min(), Solver::SolutionInfo::r, si, and Solver::y.
void Solver_NU::do_shrinking () private virtual
Reimplemented from Solver.
Definition at line 1148 of file libsvm.cpp.
References Solver::active_size, be_shrunk(), Solver::eps, Solver::G, INF, Solver::is_lower_bound(), Solver::is_upper_bound(), Solver::l, max(), Solver::reconstruct_gradient(), Solver::swap_index(), Solver::unshrink, and Solver::y.
int Solver_NU::select_working_set (int & i, int & j) private virtual
Reimplemented from Solver.
Definition at line 1016 of file libsvm.cpp.
References Solver::active_size, Solver::eps, Solver::G, QMatrix::get_Q(), INF, Solver::is_lower_bound(), Solver::is_upper_bound(), max(), Solver::Q, Solver::QD, TAU, and Solver::y.
void Solver_NU::Solve (int l, const QMatrix & Q, const double * p, const schar * y, double * alpha, double Cp, double Cn, double eps, SolutionInfo * si, int shrinking) inline
Definition at line 1000 of file libsvm.cpp.
References si, and Solver::Solve().
Referenced by solve_nu_svc(), and solve_nu_svr().
Member Data Documentation
SolutionInfo* Solver_NU::si private
Definition at line 1008 of file libsvm.cpp.
Referenced by calculate_rho(), and Solve().
The documentation for this class was generated from the following file:
LIA_Utils/Svm/src/libsvm.cpp