LIA_RAL: Eigen::DenseBase< Derived > Class Template Reference
Eigen::DenseBase< Derived > Class Template Reference
Base class for all dense matrices, vectors, and arrays.
#include <DenseBase.h>
Classes
struct ConstFixedSegmentReturnType
struct ConstNColsBlockXpr
struct ConstNRowsBlockXpr
struct FixedSegmentReturnType
class InnerIterator
struct NColsBlockXpr
struct NRowsBlockXpr
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime, SizeAtCompileTime, MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime, MaxSizeAtCompileTime, IsVectorAtCompileTime, Flags = internal::traits<Derived>::Flags,
IsRowMajor = int(Flags) & RowMajorBit, InnerSizeAtCompileTime, CoeffReadCost = internal::traits<Derived>::CoeffReadCost, InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret,
OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { ThisConstantIsPrivateInPlainObjectBase }
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
The type of indices.
typedef internal::traits
< Derived >::Scalar Scalar
typedef
internal::packet_traits
< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef CwiseNullaryOp
< internal::scalar_constant_op
< Scalar >, Derived > ConstantReturnType
typedef CwiseNullaryOp
< internal::linspaced_op
< Scalar, false >, Derived > SequentialLinSpacedReturnType
typedef CwiseNullaryOp
< internal::linspaced_op
< Scalar, true >, Derived > RandomAccessLinSpacedReturnType
typedef Matrix< typename
NumTraits< typename
internal::traits< Derived >
::Scalar >::Real,
internal::traits< Derived >
::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef const Transpose< const
Derived > ConstTransposeReturnType
typedef VectorBlock< Derived > SegmentReturnType
typedef const VectorBlock
< const Derived > ConstSegmentReturnType
typedef
internal::add_const_on_value_type
< typename internal::eval
< Derived >::type >::type EvalReturnType
typedef VectorwiseOp< Derived,
Horizontal > RowwiseReturnType
typedef const VectorwiseOp
< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived,
Vertical > ColwiseReturnType
typedef const VectorwiseOp
< const Derived, Vertical > ConstColwiseReturnType
typedef Reverse< Derived,
BothDirections > ReverseReturnType
typedef const Reverse< const
Derived, BothDirections > ConstReverseReturnType
typedef Block< Derived,
internal::traits< Derived >
::RowsAtCompileTime,
1,!IsRowMajor > ColXpr
typedef const Block< const
Derived, internal::traits
< Derived >::RowsAtCompileTime,
1,!IsRowMajor > ConstColXpr
typedef Block< Derived,
1, internal::traits< Derived >
::ColsAtCompileTime,
IsRowMajor > RowXpr
typedef const Block< const
Derived, 1, internal::traits
< Derived >::ColsAtCompileTime,
IsRowMajor > ConstRowXpr
typedef Block< Derived,
internal::traits< Derived >
::RowsAtCompileTime, Dynamic,!IsRowMajor > ColsBlockXpr
typedef const Block< const
Derived, internal::traits
< Derived >::RowsAtCompileTime,
Dynamic,!IsRowMajor > ConstColsBlockXpr
typedef Block< Derived,
Dynamic, internal::traits
< Derived >::ColsAtCompileTime,
IsRowMajor > RowsBlockXpr
typedef const Block< const
Derived, Dynamic,
internal::traits< Derived >
::ColsAtCompileTime,
IsRowMajor > ConstRowsBlockXpr
Public Member Functions
Index nonZeros () const
Index outerSize () const
Index innerSize () const
void resize (Index size)
void resize (Index rows, Index cols)
template<typename OtherDerived >
Derived & operator= (const DenseBase< OtherDerived > &other)
Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
Derived & lazyAssign (const DenseBase< OtherDerived > &other)
CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
const Flagged< Derived, Added,
Removed > flagged () const
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
Eigen::Transpose< Derived > transpose ()
ConstTransposeReturnType transpose () const
void transposeInPlace ()
SegmentReturnType segment (Index start, Index size)
DenseBase::ConstSegmentReturnType segment (Index start, Index size) const
SegmentReturnType head (Index size)
DenseBase::ConstSegmentReturnType head (Index size) const
SegmentReturnType tail (Index size)
DenseBase::ConstSegmentReturnType tail (Index size) const
template<int Size>
FixedSegmentReturnType< Size >
::Type head ()
template<int Size>
ConstFixedSegmentReturnType
< Size >::Type head () const
template<int Size>
FixedSegmentReturnType< Size >
::Type tail ()
template<int Size>
ConstFixedSegmentReturnType
< Size >::Type tail () const
template<int Size>
FixedSegmentReturnType< Size >
::Type segment (Index start)
template<int Size>
ConstFixedSegmentReturnType
< Size >::Type segment (Index start) const
void fill (const Scalar &value)
Derived & setConstant (const Scalar &value)
Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setZero ()
Derived & setOnes ()
Derived & setRandom ()
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isMuchSmallerThan (const RealScalar &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isApproxToConstant (const Scalar &value, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isConstant (const Scalar &value, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isZero (RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isOnes (RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
Derived & operator*= (const Scalar &other)
Derived & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
void swap (const DenseBase< OtherDerived > &other, int=OtherDerived::ThisConstantIsPrivateInPlainObjectBase)
template<typename OtherDerived >
void swap (PlainObjectBase< OtherDerived > &other)
const NestByValue< Derived > nestByValue () const
const ForceAlignedAccess< Derived > forceAlignedAccess () const
ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
const internal::conditional
< Enable, ForceAlignedAccess
< Derived >, Derived & >::type forceAlignedAccessIf () const
template<bool Enable>
internal::conditional< Enable,
ForceAlignedAccess< Derived >
, Derived & >::type forceAlignedAccessIf ()
Scalar sum () const
Scalar mean () const
Scalar trace () const
Scalar prod () const
internal::traits< Derived >::Scalar minCoeff () const
internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
internal::result_of< BinaryOp(typename
internal::traits< Derived >
::Scalar)>::type redux (const BinaryOp &func) const
template<typename Visitor >
void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
CoeffReturnType value () const
bool all (void) const
bool any (void) const
Index count () const
ConstRowwiseReturnType rowwise () const
RowwiseReturnType rowwise ()
ConstColwiseReturnType colwise () const
ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
const Select< Derived,
ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived,
ThenDerived, typename
ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, typename ThenDerived::Scalar elseScalar) const
template<typename ElseDerived >
const Select< Derived,
typename
ElseDerived::ConstantReturnType,
ElseDerived > select (typename ElseDerived::Scalar thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
const Replicate< Derived,
RowFactor, ColFactor > replicate () const
const Replicate< Derived,
Dynamic, Dynamic > replicate (Index rowFacor, Index colFactor) const
ReverseReturnType reverse ()
ConstReverseReturnType reverse () const
void reverseInPlace ()
Block< Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const Block< const Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
Block< Derived > topRightCorner (Index cRows, Index cCols)
const Block< const Derived > topRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topRightCorner () const
Block< Derived > topLeftCorner (Index cRows, Index cCols)
const Block< const Derived > topLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topLeftCorner () const
Block< Derived > bottomRightCorner (Index cRows, Index cCols)
const Block< const Derived > bottomRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomRightCorner () const
Block< Derived > bottomLeftCorner (Index cRows, Index cCols)
const Block< const Derived > bottomLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomLeftCorner () const
RowsBlockXpr topRows (Index n)
ConstRowsBlockXpr topRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type topRows ()
template<int N>
ConstNRowsBlockXpr< N >::Type topRows () const
RowsBlockXpr bottomRows (Index n)
ConstRowsBlockXpr bottomRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type bottomRows ()
template<int N>
ConstNRowsBlockXpr< N >::Type bottomRows () const
RowsBlockXpr middleRows (Index startRow, Index numRows)
ConstRowsBlockXpr middleRows (Index startRow, Index numRows) const
template<int N>
NRowsBlockXpr< N >::Type middleRows (Index startRow)
template<int N>
ConstNRowsBlockXpr< N >::Type middleRows (Index startRow) const
ColsBlockXpr leftCols (Index n)
ConstColsBlockXpr leftCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type leftCols ()
template<int N>
ConstNColsBlockXpr< N >::Type leftCols () const
ColsBlockXpr rightCols (Index n)
ConstColsBlockXpr rightCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type rightCols ()
template<int N>
ConstNColsBlockXpr< N >::Type rightCols () const
ColsBlockXpr middleCols (Index startCol, Index numCols)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
template<int N>
NColsBlockXpr< N >::Type middleCols (Index startCol)
template<int N>
ConstNColsBlockXpr< N >::Type middleCols (Index startCol) const
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows,
BlockCols > block (Index startRow, Index startCol)
template<int BlockRows, int BlockCols>
const Block< const Derived,
BlockRows, BlockCols > block (Index startRow, Index startCol) const
ColXpr col (Index i)
ConstColXpr col (Index i) const
RowXpr row (Index i)
ConstRowXpr row (Index i) const
template<typename Dest >
void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_STRONG_INLINE const
CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_STRONG_INLINE const
CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_STRONG_INLINE const
CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (const CustomNullaryOp &func)
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, RealScalar prec) const
template<typename Func >
EIGEN_STRONG_INLINE
internal::result_of< Func(typename
internal::traits< Derived >
::Scalar)>::type redux (const Func &func) const
template<int Size>
DenseBase< Derived >::template
FixedSegmentReturnType< Size >
::Type segment (Index start)
template<int Size>
DenseBase< Derived >::template
ConstFixedSegmentReturnType
< Size >::Type segment (Index start) const
template<int Size>
DenseBase< Derived >::template
FixedSegmentReturnType< Size >
::Type head ()
template<int Size>
DenseBase< Derived >::template
ConstFixedSegmentReturnType
< Size >::Type head () const
template<int Size>
DenseBase< Derived >::template
FixedSegmentReturnType< Size >
::Type tail ()
template<int Size>
DenseBase< Derived >::template
ConstFixedSegmentReturnType
< Size >::Type tail () const
Public Member Functions inherited from Eigen::internal::special_scalar_op_base< Derived, internal::traits< Derived >::Scalar, NumTraits< internal::traits< Derived >::Scalar >::Real >
void operator* () const
Static Public Member Functions
static const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static const ConstantReturnType Constant (Index size, const Scalar &value)
static const ConstantReturnType Constant (const Scalar &value)
static const
SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
template<typename CustomNullaryOp >
static const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (const CustomNullaryOp &func)
static const ConstantReturnType Zero (Index rows, Index cols)
static const ConstantReturnType Zero (Index size)
static const ConstantReturnType Zero ()
static const ConstantReturnType Ones (Index rows, Index cols)
static const ConstantReturnType Ones (Index size)
static const ConstantReturnType Ones ()
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random (Index rows, Index cols)
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random (Index size)
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random ()
Protected Member Functions
template<typename OtherDerived >
void checkTransposeAliasing (const OtherDerived &other) const
DenseBase ()
Private Member Functions
DenseBase (int)
DenseBase (int, int)
template<typename OtherDerived >
DenseBase (const DenseBase< OtherDerived > &)
Related Functions
(Note that these are not member functions.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::DenseBase< Derived >
Base class for all dense matrices, vectors, and arrays.
This class is the base that is inherited by all dense objects (matrix, vector, arrays, and related expression types). The common Eigen API for dense objects is contained in this class.
Template Parameters
Derived is the derived type, e.g., a matrix type or an expression.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizingEigen by defining the preprocessor symbol EIGEN_DENSEBASE_PLUGIN.
See Also
TopicClassHierarchy
Definition at line 31 of file DenseBase.h.
Member Typedef Documentation
template<typename Derived> typedef DenseCoeffsBase<Derived> Eigen::DenseBase< Derived >::Base
Definition at line 57 of file DenseBase.h.
template<typename Derived> typedef Base::CoeffReturnType Eigen::DenseBase< Derived >::CoeffReturnType
Definition at line 88 of file DenseBase.h.
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::DenseBase< Derived >::ColsBlockXpr
Definition at line 24 of file DenseBase.h.
template<typename Derived> typedef VectorwiseOp<Derived, Vertical> Eigen::DenseBase< Derived >::ColwiseReturnType
Definition at line 449 of file DenseBase.h.
template<typename Derived> typedef Block<Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::DenseBase< Derived >::ColXpr
Definition at line 18 of file DenseBase.h.
template<typename Derived> typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>,Derived> Eigen::DenseBase< Derived >::ConstantReturnType
Definition at line 228 of file DenseBase.h.
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, Dynamic, !IsRowMajor> Eigen::DenseBase< Derived >::ConstColsBlockXpr
Definition at line 25 of file DenseBase.h.
template<typename Derived> typedef const VectorwiseOp<const Derived, Vertical> Eigen::DenseBase< Derived >::ConstColwiseReturnType
Definition at line 450 of file DenseBase.h.
template<typename Derived> typedef const Block<const Derived, internal::traits<Derived>::RowsAtCompileTime, 1, !IsRowMajor> Eigen::DenseBase< Derived >::ConstColXpr
Definition at line 19 of file DenseBase.h.
template<typename Derived> typedef const Reverse<const Derived, BothDirections> Eigen::DenseBase< Derived >::ConstReverseReturnType
Definition at line 481 of file DenseBase.h.
template<typename Derived> typedef const Block<const Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::ConstRowsBlockXpr
Definition at line 28 of file DenseBase.h.
template<typename Derived> typedef const VectorwiseOp<const Derived, Horizontal> Eigen::DenseBase< Derived >::ConstRowwiseReturnType
Definition at line 448 of file DenseBase.h.
template<typename Derived> typedef const Block<const Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::ConstRowXpr
Definition at line 22 of file DenseBase.h.
template<typename Derived> typedef const VectorBlock<const Derived> Eigen::DenseBase< Derived >::ConstSegmentReturnType
Definition at line 285 of file DenseBase.h.
template<typename Derived> typedef const Transpose<const Derived> Eigen::DenseBase< Derived >::ConstTransposeReturnType
Definition at line 274 of file DenseBase.h.
template<typename Derived> typedef Matrix<typename NumTraits<typename internal::traits<Derived>::Scalar>::Real, internal::traits<Derived>::ColsAtCompileTime, 1> Eigen::DenseBase< Derived >::EigenvaluesReturnType
Definition at line 234 of file DenseBase.h.
template<typename Derived> typedef internal::add_const_on_value_type<typename internal::eval<Derived>::type>::type Eigen::DenseBase< Derived >::EvalReturnType
Definition at line 366 of file DenseBase.h.
template<typename Derived> typedef internal::traits<Derived>::Index Eigen::DenseBase< Derived >::Index
The type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See Also
TopicPreprocessorDirectives.
Definition at line 51 of file DenseBase.h.
template<typename Derived> typedef internal::packet_traits<Scalar>::type Eigen::DenseBase< Derived >::PacketScalar
Definition at line 54 of file DenseBase.h.
template<typename Derived> typedef CwiseNullaryOp<internal::linspaced_op<Scalar,true>,Derived> Eigen::DenseBase< Derived >::RandomAccessLinSpacedReturnType
Definition at line 232 of file DenseBase.h.
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::DenseBase< Derived >::RealScalar
Definition at line 55 of file DenseBase.h.
template<typename Derived> typedef Reverse<Derived, BothDirections> Eigen::DenseBase< Derived >::ReverseReturnType
Definition at line 480 of file DenseBase.h.
template<typename Derived> typedef Block<Derived, Dynamic, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::RowsBlockXpr
Definition at line 27 of file DenseBase.h.
template<typename Derived> typedef VectorwiseOp<Derived, Horizontal> Eigen::DenseBase< Derived >::RowwiseReturnType
Definition at line 447 of file DenseBase.h.
template<typename Derived> typedef Block<Derived, 1, internal::traits<Derived>::ColsAtCompileTime, IsRowMajor> Eigen::DenseBase< Derived >::RowXpr
Definition at line 21 of file DenseBase.h.
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::Scalar
Definition at line 53 of file DenseBase.h.
template<typename Derived> typedef VectorBlock<Derived> Eigen::DenseBase< Derived >::SegmentReturnType
Definition at line 284 of file DenseBase.h.
template<typename Derived> typedef CwiseNullaryOp<internal::linspaced_op<Scalar,false>,Derived> Eigen::DenseBase< Derived >::SequentialLinSpacedReturnType
Definition at line 230 of file DenseBase.h.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::DenseBase< Derived >::StorageKind
Definition at line 43 of file DenseBase.h.
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See Also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
InnerSizeAtCompileTime
CoeffReadCost
This is a rough measure of how expensive it is to read one coefficient from this expression.
InnerStrideAtCompileTime
OuterStrideAtCompileTime
Definition at line 90 of file DenseBase.h.
template<typename Derived> anonymous enum
Enumerator
ThisConstantIsPrivateInPlainObjectBase
Definition at line 171 of file DenseBase.h.
Constructor & Destructor Documentation
template<typename Derived> Eigen::DenseBase< Derived >::DenseBase () inline protected
Default constructor. Do nothing.
Definition at line 513 of file DenseBase.h.
References EIGEN_IMPLIES, EIGEN_STATIC_ASSERT, Eigen::DenseBase< Derived >::IsRowMajor, Eigen::DenseBase< Derived >::MaxColsAtCompileTime, and Eigen::DenseBase< Derived >::MaxRowsAtCompileTime.
template<typename Derived> Eigen::DenseBase< Derived >::DenseBase (int) explicit private
template<typename Derived> Eigen::DenseBase< Derived >::DenseBase (int , int) private
template<typename Derived> template<typename OtherDerived > Eigen::DenseBase< Derived >::DenseBase (const DenseBase< OtherDerived > &) explicit private
Member Function Documentation
template<typename Derived > bool Eigen::DenseBase< Derived >::all (void) const inline
Returns
true if all coefficients are true
Example:
Output:
See Also
any(), Cwise::operator<()
Definition at line 79 of file BooleanRedux.h.
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
template<typename Derived > bool Eigen::DenseBase< Derived >::any (void) const inline
Returns
true if at least one coefficient is true
See Also
all()
Definition at line 105 of file BooleanRedux.h.
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
template<typename Derived> Block<Derived> Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
Definition at line 55 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename Derived> const Block<const Derived> Eigen::DenseBase< Derived >::block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block(Index,Index,Index,Index).
Definition at line 61 of file DenseBase.h.
template<typename Derived> template<int BlockRows, int BlockCols> Block<Derived, BlockRows, BlockCols> Eigen::DenseBase< Derived >::block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters BlockRows and BlockCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Output:
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 535 of file DenseBase.h.
template<typename Derived> template<int BlockRows, int BlockCols> const Block<const Derived, BlockRows, BlockCols> Eigen::DenseBase< Derived >::block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index).
Definition at line 542 of file DenseBase.h.
template<typename Derived> Block<Derived> Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 215 of file DenseBase.h.
template<typename Derived> const Block<const Derived> Eigen::DenseBase< Derived >::bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner(Index, Index).
Definition at line 221 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> Block<Derived, CRows, CCols> Eigen::DenseBase< Derived >::bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 236 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> const Block<const Derived, CRows, CCols> Eigen::DenseBase< Derived >::bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
Definition at line 243 of file DenseBase.h.
template<typename Derived> Block<Derived> Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 170 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename Derived> const Block<const Derived> Eigen::DenseBase< Derived >::bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner(Index, Index).
Definition at line 176 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> Block<Derived, CRows, CCols> Eigen::DenseBase< Derived >::bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 191 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> const Block<const Derived, CRows, CCols> Eigen::DenseBase< Derived >::bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
Definition at line 198 of file DenseBase.h.
References Eigen::DenseBase< Derived >::IsRowMajor, and Eigen::DenseBase< Derived >::IsVectorAtCompileTime.
template<typename Derived> RowsBlockXpr Eigen::DenseBase< Derived >::bottomRows (Index n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 303 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename Derived> ConstRowsBlockXpr Eigen::DenseBase< Derived >::bottomRows (Index n) const inline
This is the const version of bottomRows(Index).
Definition at line 309 of file DenseBase.h.
template<typename Derived> template<int N> NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::bottomRows () inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 324 of file DenseBase.h.
template<typename Derived> template<int N> ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::bottomRows () const inline
This is the const version of bottomRows<int>().
Definition at line 331 of file DenseBase.h.
template<typename Derived > template<typename OtherDerived > void Eigen::DenseBase< Derived >::checkTransposeAliasing (const OtherDerived & other) const protected
Definition at line 406 of file Transpose.h.
References Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run().
template<typename Derived> ColXpr Eigen::DenseBase< Derived >::col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Output:
See Also
row(), class Block
Definition at line 553 of file DenseBase.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::_solve(), Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), Eigen::DiagonalProduct< MatrixType, DiagonalType, ProductOrder >::packet(), Eigen::ArrayWrapper< ExpressionType >::packet(), Eigen::MatrixWrapper< ExpressionType >::packet(), Eigen::SVD< MatrixType >::solve(), Eigen::ArrayWrapper< ExpressionType >::writePacket(), and Eigen::MatrixWrapper< ExpressionType >::writePacket().
template<typename Derived> ConstColXpr Eigen::DenseBase< Derived >::col (Index i) const inline
This is the const version of col().
Definition at line 559 of file DenseBase.h.
template<typename Derived > const DenseBase< Derived >::ConstColwiseReturnType Eigen::DenseBase< Derived >::colwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See Also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 555 of file VectorwiseOp.h.
Referenced by Eigen::umeyama().
template<typename Derived > DenseBase< Derived >::ColwiseReturnType Eigen::DenseBase< Derived >::colwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See Also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 566 of file VectorwiseOp.h.
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index rows, Index cols, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
Definition at line 179 of file CwiseNullaryOp.h.
References Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index size, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
Definition at line 201 of file CwiseNullaryOp.h.
References Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (const Scalar & value) static
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
Definition at line 217 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_FIXED_SIZE, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > DenseBase< Derived >::Index Eigen::DenseBase< Derived >::count () const inline
Returns
the number of coefficients which evaluate to true
See Also
all(), any()
Definition at line 131 of file BooleanRedux.h.
template<typename Derived> EIGEN_STRONG_INLINE EvalReturnType Eigen::DenseBase< Derived >::eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Definition at line 372 of file DenseBase.h.
template<typename Derived> template<typename Dest > void Eigen::DenseBase< Derived >::evalTo (Dest &) const inline
Definition at line 506 of file DenseBase.h.
References EIGEN_STATIC_ASSERT.
template<typename Derived > EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::fill (const Scalar & value)
Alias for setConstant(): sets all coefficients in this expression to value.
See Also
setConstant(), Constant(), class CwiseNullaryOp
Definition at line 322 of file CwiseNullaryOp.h.
template<typename Derived > template<unsigned int Added, unsigned int Removed> const Flagged< Derived, Added, Removed > Eigen::DenseBase< Derived >::flagged () const inline
Returns
an expression of *this with added and removed flags
This is mostly for internal use.
See Also
class Flagged
Definition at line 133 of file Flagged.h.
template<typename Derived> const ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () const inline
template<typename Derived> ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () inline
template<typename Derived> template<bool Enable> const internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () const inline
template<typename Derived> template<bool Enable> internal::conditional<Enable,ForceAlignedAccess<Derived>,Derived&>::type Eigen::DenseBase< Derived >::forceAlignedAccessIf () inline
template<typename Derived > const WithFormat< Derived > Eigen::DenseBase< Derived >::format (const IOFormat & fmt) const inline
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See Also
class IOFormat, class WithFormat
Definition at line 118 of file IO.h.
template<typename Derived> template<int Size> DenseBase<Derived>::template FixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::head () inline
Returns
a fixed-size expression of the first coefficients of *this.
The template parameter Size is the number of coefficients in the block
Example:
Output:
See Also
class Block
Definition at line 236 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> template<int Size> DenseBase<Derived>::template ConstFixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::head () const inline
This is the const version of head<int>().
Definition at line 246 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > DenseBase< Derived >::SegmentReturnType Eigen::DenseBase< Derived >::head (Index size) inline
Returns
a dynamic-size expression of the first coefficients of *this.
Parameters
size the number of coefficients in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
Definition at line 143 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > DenseBase< Derived >::ConstSegmentReturnType Eigen::DenseBase< Derived >::head (Index size) const inline
This is the const version of head(Index).
Definition at line 152 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> template<int Size> FixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::head ()
template<typename Derived> template<int Size> ConstFixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::head () const
template<typename Derived> Index Eigen::DenseBase< Derived >::innerSize () const inline
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
Definition at line 197 of file DenseBase.h.
template<typename Derived > template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors and are considered to be approximately equal within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See Also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
Definition at line 98 of file Fuzzy.h.
References Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >::run().
template<typename Derived > bool Eigen::DenseBase< Derived >::isApproxToConstant (const Scalar & value, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
Definition at line 298 of file CwiseNullaryOp.h.
References Eigen::internal::isApprox().
template<typename Derived > bool Eigen::DenseBase< Derived >::isConstant (const Scalar & value, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
Definition at line 312 of file CwiseNullaryOp.h.
template<typename Derived> template<typename Derived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, RealScalar prec) const
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See Also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
Definition at line 120 of file Fuzzy.h.
References Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run().
template<typename Derived> bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const RealScalar & other, RealScalar prec = NumTraits< Scalar >::dummy_precision()) const
template<typename Derived > template<typename OtherDerived > bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than a vector within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See Also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
Definition at line 140 of file Fuzzy.h.
References Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run().
template<typename Derived > bool Eigen::DenseBase< Derived >::isOnes (RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Output:
See Also
class CwiseNullaryOp, Ones()
Definition at line 612 of file CwiseNullaryOp.h.
template<typename Derived > bool Eigen::DenseBase< Derived >::isZero (RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Output:
See Also
class CwiseNullaryOp, Zero()
Definition at line 482 of file CwiseNullaryOp.h.
References Eigen::internal::isMuchSmallerThan().
template<typename Derived> template<typename OtherDerived > Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
Copies other into *this without evaluating other.
Returns
a reference to *this.
Referenced by Eigen::DenseBase< Derived >::swap().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
Definition at line 485 of file Assign.h.
References debug, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_LVALUE, EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE, and Eigen::InvalidTraversal.
template<typename Derived> ColsBlockXpr Eigen::DenseBase< Derived >::leftCols (Index n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 393 of file DenseBase.h.
template<typename Derived> ConstColsBlockXpr Eigen::DenseBase< Derived >::leftCols (Index n) const inline
This is the const version of leftCols(Index).
Definition at line 399 of file DenseBase.h.
template<typename Derived> template<int N> NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::leftCols () inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 414 of file DenseBase.h.
template<typename Derived> template<int N> ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::leftCols () const inline
This is the const version of leftCols<int>().
Definition at line 421 of file DenseBase.h.
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::SequentialLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp
Definition at line 242 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Index size, const Scalar & low, const Scalar & high) static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp
Definition at line 276 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::SequentialLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
Definition at line 254 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (const Scalar & low, const Scalar & high) static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
Definition at line 288 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
template<typename Derived> template<int p> RealScalar Eigen::DenseBase< Derived >::lpNorm () const
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff () const
Returns
the maximum of all coefficients of *this
Definition at line 346 of file Redux.h.
template<typename Derived > template<typename IndexType > internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * row, IndexType * col) const
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
See Also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
Definition at line 209 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > template<typename IndexType > internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * index) const
Returns
the maximum of all coefficients of *this and puts in *index its location.
See Also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
Definition at line 226 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::mean () const
Returns
the mean of all coefficients of *this
See Also
trace(), prod(), sum()
Definition at line 370 of file Redux.h.
template<typename Derived> ColsBlockXpr Eigen::DenseBase< Derived >::middleCols (Index startCol, Index numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 482 of file DenseBase.h.
template<typename Derived> ConstColsBlockXpr Eigen::DenseBase< Derived >::middleCols (Index startCol, Index numCols) const inline
This is the const version of middleCols(Index,Index).
Definition at line 488 of file DenseBase.h.
template<typename Derived> template<int N> NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block
Parameters
startCol the index of the first column in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 504 of file DenseBase.h.
template<typename Derived> template<int N> ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleCols (Index startCol) const inline
This is the const version of middleCols<int>().
Definition at line 511 of file DenseBase.h.
template<typename Derived> RowsBlockXpr Eigen::DenseBase< Derived >::middleRows (Index startRow, Index numRows) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
numRows the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 348 of file DenseBase.h.
template<typename Derived> ConstRowsBlockXpr Eigen::DenseBase< Derived >::middleRows (Index startRow, Index numRows) const inline
This is the const version of middleRows(Index,Index).
Definition at line 354 of file DenseBase.h.
template<typename Derived> template<int N> NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block
Parameters
startRow the index of the first row in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 370 of file DenseBase.h.
template<typename Derived> template<int N> ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::middleRows (Index startRow) const inline
This is the const version of middleRows<int>().
Definition at line 377 of file DenseBase.h.
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff () const
Returns
the minimum of all coefficients of *this
Definition at line 337 of file Redux.h.
template<typename Derived > template<typename IndexType > internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * row, IndexType * col) const
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
See Also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visitor(), DenseBase::minCoeff()
Definition at line 175 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > template<typename IndexType > internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * index) const
Returns
the minimum of all coefficients of *this and puts in *index its location.
See Also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::minCoeff()
Definition at line 192 of file Visitor.h.
References Eigen::internal::coeff_visitor< Derived >::col, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, and Eigen::internal::coeff_visitor< Derived >::row.
template<typename Derived > const NestByValue< Derived > Eigen::DenseBase< Derived >::nestByValue () const inline
Returns
an expression of the temporary version of *this.
Definition at line 104 of file NestByValue.h.
template<typename Derived> Index Eigen::DenseBase< Derived >::nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
Definition at line 175 of file DenseBase.h.
template<typename Derived> template<typename CustomNullaryOp > EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, Derived> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
Definition at line 117 of file CwiseNullaryOp.h.
template<typename Derived> template<typename CustomNullaryOp > EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, Derived> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
Definition at line 140 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> template<typename CustomNullaryOp > EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, Derived> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
Definition at line 159 of file CwiseNullaryOp.h.
template<typename Derived> template<typename CustomNullaryOp > static const CwiseNullaryOp<CustomNullaryOp, Derived> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) static
Referenced by Eigen::DenseBase< Derived >::Constant(), Eigen::MatrixBase< Derived >::Identity(), and Eigen::DenseBase< Derived >::LinSpaced().
template<typename Derived> template<typename CustomNullaryOp > static const CwiseNullaryOp<CustomNullaryOp, Derived> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) static
template<typename Derived> template<typename CustomNullaryOp > static const CwiseNullaryOp<CustomNullaryOp, Derived> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) static
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index rows, Index cols) static
Returns
an expression of a matrix where all coefficients equal one.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
Output:
See Also
Ones(), Ones(Index), isOnes(), class Ones
Definition at line 557 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index size) static
Returns
an expression of a vector where all coefficients equal one.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
Output:
See Also
Ones(), Ones(Index,Index), isOnes(), class Ones
Definition at line 580 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones () static
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See Also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
Definition at line 597 of file CwiseNullaryOp.h.
template<typename Derived > Derived & Eigen::DenseBase< Derived >::operator*= (const Scalar & other) inline
Definition at line 172 of file SelfCwiseBinaryOp.h.
template<typename Derived > template<typename OtherDerived > Derived & Eigen::DenseBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
Definition at line 115 of file EigenBase.h.
References Eigen::EigenBase< Derived >::derived().
template<typename Derived > template<typename OtherDerived > Derived & Eigen::DenseBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
Definition at line 123 of file EigenBase.h.
References Eigen::EigenBase< Derived >::derived().
template<typename Derived > Derived & Eigen::DenseBase< Derived >::operator/= (const Scalar & other) inline
Definition at line 181 of file SelfCwiseBinaryOp.h.
template<typename Derived > CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const Scalar & s) inline
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Output:
See Also
CommaInitializer::finished(), class CommaInitializer
Definition at line 125 of file CommaInitializer.h.
template<typename Derived > template<typename OtherDerived > CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inline
See Also
operator<<(const Scalar&)
Definition at line 134 of file CommaInitializer.h.
template<typename Derived> template<typename OtherDerived > Derived& Eigen::DenseBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
Copies other into *this.
Returns
a reference to *this.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< Derived > & other)
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
Definition at line 547 of file Assign.h.
template<typename Derived > template<typename OtherDerived > Derived & Eigen::DenseBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
Definition at line 107 of file EigenBase.h.
References Eigen::EigenBase< Derived >::derived().
template<typename Derived > template<typename OtherDerived > Derived & Eigen::DenseBase< Derived >::operator= (const ReturnByValue< OtherDerived > & func)
Definition at line 80 of file ReturnByValue.h.
References Eigen::ReturnByValue< Derived >::evalTo().
template<typename Derived> template<typename OtherDerived > EIGEN_STRONG_INLINE Derived& Eigen::DenseBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
Definition at line 541 of file Assign.h.
template<typename Derived> Index Eigen::DenseBase< Derived >::outerSize () const inline
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See Also
rows(), cols(), IsVectorAtCompileTime.
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
Definition at line 186 of file DenseBase.h.
References Eigen::DenseBase< Derived >::IsRowMajor, and Eigen::DenseBase< Derived >::IsVectorAtCompileTime.
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::prod () const
Returns
the product of all coefficients of *this
Example:
Output:
See Also
sum(), mean(), trace()
Definition at line 384 of file Redux.h.
References Eigen::Dynamic.
template<typename Derived > const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Eigen::DenseBase< Derived >::Random (Index rows, Index cols) inline static
Returns
a random matrix expression
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index), MatrixBase::Random()
Definition at line 49 of file Random.h.
template<typename Derived > const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Eigen::DenseBase< Derived >::Random (Index size) inline static
Returns
a random vector expression
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random()
Definition at line 76 of file Random.h.
template<typename Derived > const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Eigen::DenseBase< Derived >::Random () inline static
Returns
a fixed-size random matrix or vector expression
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random(Index)
Definition at line 97 of file Random.h.
template<typename Derived> template<typename Func > EIGEN_STRONG_INLINE internal::result_of<Func(typename internal::traits<Derived>::Scalar)>::type Eigen::DenseBase< Derived >::redux (const Func & func) const
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current STL and TR1 functor styles are handled.
See Also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
Definition at line 326 of file Redux.h.
template<typename Derived> template<typename BinaryOp > internal::result_of<BinaryOp(typename internal::traits<Derived>::Scalar)>::type Eigen::DenseBase< Derived >::redux (const BinaryOp & func) const
Referenced by Eigen::internal::member_redux< BinaryOp, Scalar >::operator()().
template<typename Derived > template<int RowFactor, int ColFactor> const Replicate< Derived, RowFactor, ColFactor > Eigen::DenseBase< Derived >::replicate () const inline
Returns
an expression of the replication of *this
Example:
Output:
See Also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
Definition at line 139 of file Replicate.h.
template<typename Derived > const Replicate< Derived, Dynamic, Dynamic > Eigen::DenseBase< Derived >::replicate (Index rowFactor, Index colFactor) const inline
Returns
an expression of the replication of *this
Example:
Output:
See Also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
Definition at line 154 of file Replicate.h.
template<typename Derived> void Eigen::DenseBase< Derived >::resize (Index size) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
Definition at line 207 of file DenseBase.h.
References eigen_assert, and EIGEN_ONLY_USED_FOR_DEBUG.
Referenced by Eigen::TriangularBase< Derived >::evalToLazy().
template<typename Derived> void Eigen::DenseBase< Derived >::resize (Index rows, Index cols) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
Definition at line 217 of file DenseBase.h.
References EIGEN_ONLY_USED_FOR_DEBUG.
template<typename Derived > DenseBase< Derived >::ReverseReturnType Eigen::DenseBase< Derived >::reverse () inline
Returns
an expression of the reverse of *this.
Example:
Output:
Definition at line 191 of file Reverse.h.
template<typename Derived > const DenseBase< Derived >::ConstReverseReturnType Eigen::DenseBase< Derived >::reverse () const inline
This is the const version of reverse().
Definition at line 199 of file Reverse.h.
template<typename Derived > void Eigen::DenseBase< Derived >::reverseInPlace () inline
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional features:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API allows to avoid creating a temporary (the current implementation creates a temporary, but that could be avoided using swap)
it allows future optimizations (cache friendliness, etc.)
See Also
reverse()
Definition at line 217 of file Reverse.h.
template<typename Derived> ColsBlockXpr Eigen::DenseBase< Derived >::rightCols (Index n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 437 of file DenseBase.h.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename Derived> ConstColsBlockXpr Eigen::DenseBase< Derived >::rightCols (Index n) const inline
This is the const version of rightCols(Index).
Definition at line 443 of file DenseBase.h.
template<typename Derived> template<int N> NColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::rightCols () inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 458 of file DenseBase.h.
template<typename Derived> template<int N> ConstNColsBlockXpr<N>::Type Eigen::DenseBase< Derived >::rightCols () const inline
This is the const version of rightCols<int>().
Definition at line 465 of file DenseBase.h.
template<typename Derived> RowXpr Eigen::DenseBase< Derived >::row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Output:
See Also
col(), class Block
Definition at line 570 of file DenseBase.h.
Referenced by Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), Eigen::DiagonalProduct< MatrixType, DiagonalType, ProductOrder >::packet(), Eigen::ArrayWrapper< ExpressionType >::packet(), Eigen::MatrixWrapper< ExpressionType >::packet(), Eigen::ArrayWrapper< ExpressionType >::writePacket(), and Eigen::MatrixWrapper< ExpressionType >::writePacket().
template<typename Derived> ConstRowXpr Eigen::DenseBase< Derived >::row (Index i) const inline
This is the const version of row().
Definition at line 576 of file DenseBase.h.
template<typename Derived > const DenseBase< Derived >::ConstRowwiseReturnType Eigen::DenseBase< Derived >::rowwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Output:
See Also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 580 of file VectorwiseOp.h.
Referenced by Eigen::umeyama().
template<typename Derived > DenseBase< Derived >::RowwiseReturnType Eigen::DenseBase< Derived >::rowwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See Also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
Definition at line 591 of file VectorwiseOp.h.
template<typename Derived> template<int Size> DenseBase<Derived>::template FixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::segment (Index start) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
The template parameter Size is the number of coefficients in the block
Parameters
start the index of the first element of the sub-vector
Example:
Output:
See Also
class Block
Definition at line 206 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> template<int Size> DenseBase<Derived>::template ConstFixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::segment (Index start) const inline
This is the const version of segment<int>(Index).
Definition at line 216 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > DenseBase< Derived >::SegmentReturnType Eigen::DenseBase< Derived >::segment (Index start, Index size) inline
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
Parameters
start the first coefficient in the segment
size the number of coefficients in the segment
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, segment(Index)
Definition at line 111 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > DenseBase< Derived >::ConstSegmentReturnType Eigen::DenseBase< Derived >::segment (Index start, Index size) const inline
This is the const version of segment(Index,Index).
Definition at line 120 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> template<int Size> FixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::segment (Index start)
template<typename Derived> template<int Size> ConstFixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::segment (Index start) const
template<typename Derived > template<typename ThenDerived , typename ElseDerived > const Select< Derived, ThenDerived, ElseDerived > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
Output:
See Also
class Select
Definition at line 124 of file Select.h.
template<typename Derived > template<typename ThenDerived > const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, typename ThenDerived::Scalar elseScalar) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See Also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
Definition at line 138 of file Select.h.
template<typename Derived > template<typename ElseDerived > const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > Eigen::DenseBase< Derived >::select (typename ElseDerived::Scalar thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See Also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
Definition at line 153 of file Select.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setConstant (const Scalar & value)
Sets all coefficients in this expression to value.
See Also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
Definition at line 332 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (Index size, const Scalar & low, const Scalar & high)
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
Example:
Output:
See Also
CwiseNullaryOp
Definition at line 387 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (const Scalar & low, const Scalar & high)
Sets a linearly space vector.
The function fill *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
See Also
setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
Definition at line 404 of file CwiseNullaryOp.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setOnes ()
Sets all coefficients in this expression to one.
Example:
Output:
See Also
class CwiseNullaryOp, Ones()
Definition at line 625 of file CwiseNullaryOp.h.
template<typename Derived > Derived & Eigen::DenseBase< Derived >::setRandom () inline
Sets all coefficients in this expression to random values.
Example:
Output:
See Also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
Definition at line 110 of file Random.h.
template<typename Derived > EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setZero ()
Sets all coefficients in this expression to zero.
Example:
Output:
See Also
class CwiseNullaryOp, Zero()
Definition at line 499 of file CwiseNullaryOp.h.
Referenced by Eigen::DiagonalBase< Derived >::evalTo(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::evalTo(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::evalTo(), and Eigen::Transpose< PermutationBase< Derived > >::evalTo().
template<typename Derived > EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::sum () const
Returns
the sum of all coefficients of *this
See Also
trace(), prod(), mean()
Definition at line 357 of file Redux.h.
References Eigen::Dynamic.
template<typename Derived> template<typename OtherDerived > void Eigen::DenseBase< Derived >::swap (const DenseBase< OtherDerived > & other, int = OtherDerived::ThisConstantIsPrivateInPlainObjectBase) inline
swaps *this with the expression other.
Definition at line 384 of file DenseBase.h.
References Eigen::DenseBase< Derived >::lazyAssign().
Referenced by Eigen::TriangularBase< Derived >::evalTo(), and Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename Derived> template<typename OtherDerived > void Eigen::DenseBase< Derived >::swap (PlainObjectBase< OtherDerived > & other) inline
swaps *this with the matrix or array other.
Definition at line 394 of file DenseBase.h.
References Eigen::DenseBase< Derived >::lazyAssign().
template<typename Derived> template<int Size> DenseBase<Derived>::template FixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::tail () inline
Returns
a fixed-size expression of the last coefficients of *this.
The template parameter Size is the number of coefficients in the block
Example:
Output:
See Also
class Block
Definition at line 266 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> template<int Size> DenseBase<Derived>::template ConstFixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::tail () const inline
This is the const version of tail<int>.
Definition at line 276 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived > DenseBase< Derived >::SegmentReturnType Eigen::DenseBase< Derived >::tail (Index size) inline
Returns
a dynamic-size expression of the last coefficients of *this.
Parameters
size the number of coefficients in the block
Example:
Output:
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
Definition at line 175 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, true >::run(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
template<typename Derived > DenseBase< Derived >::ConstSegmentReturnType Eigen::DenseBase< Derived >::tail (Index size) const inline
This is the const version of tail(Index).
Definition at line 184 of file VectorBlock.h.
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
template<typename Derived> template<int Size> FixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::tail ()
template<typename Derived> template<int Size> ConstFixedSegmentReturnType<Size>::Type Eigen::DenseBase< Derived >::tail () const
template<typename Derived> Block<Derived> Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 125 of file DenseBase.h.
template<typename Derived> const Block<const Derived> Eigen::DenseBase< Derived >::topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner(Index, Index).
Definition at line 131 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> Block<Derived, CRows, CCols> Eigen::DenseBase< Derived >::topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 146 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> const Block<const Derived, CRows, CCols> Eigen::DenseBase< Derived >::topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
Definition at line 153 of file DenseBase.h.
template<typename Derived> Block<Derived> Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 79 of file DenseBase.h.
template<typename Derived> const Block<const Derived> Eigen::DenseBase< Derived >::topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner(Index, Index).
Definition at line 85 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> Block<Derived, CRows, CCols> Eigen::DenseBase< Derived >::topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 100 of file DenseBase.h.
template<typename Derived> template<int CRows, int CCols> const Block<const Derived, CRows, CCols> Eigen::DenseBase< Derived >::topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
Definition at line 107 of file DenseBase.h.
template<typename Derived> RowsBlockXpr Eigen::DenseBase< Derived >::topRows (Index n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 259 of file DenseBase.h.
template<typename Derived> ConstRowsBlockXpr Eigen::DenseBase< Derived >::topRows (Index n) const inline
This is the const version of topRows(Index).
Definition at line 265 of file DenseBase.h.
template<typename Derived> template<int N> NRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::topRows () inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block
Example:
Output:
See Also
class Block, block(Index,Index,Index,Index)
Definition at line 280 of file DenseBase.h.
template<typename Derived> template<int N> ConstNRowsBlockXpr<N>::Type Eigen::DenseBase< Derived >::topRows () const inline
This is the const version of topRows<int>().
Definition at line 287 of file DenseBase.h.
template<typename Derived> Scalar Eigen::DenseBase< Derived >::trace () const
template<typename Derived > Transpose< Derived > Eigen::DenseBase< Derived >::transpose () inline
Returns
an expression of the transpose of *this.
Example:
Output:
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See Also
transposeInPlace(), adjoint()
Definition at line 198 of file Transpose.h.
Referenced by Eigen::internal::dot_nocheck< T, U, true >::run().
template<typename Derived > const DenseBase< Derived >::ConstTransposeReturnType Eigen::DenseBase< Derived >::transpose () const inline
This is the const version of transpose().
Make sure you read the warning for transpose() !
See Also
transposeInPlace(), adjoint()
Definition at line 210 of file Transpose.h.
template<typename Derived > void Eigen::DenseBase< Derived >::transposeInPlace () inline
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix.
See Also
transpose(), adjoint(), adjointInPlace()
Definition at line 290 of file Transpose.h.
template<typename Derived> CoeffReturnType Eigen::DenseBase< Derived >::value () const inline
Returns
the unique coefficient of a 1x1 expression
Definition at line 434 of file DenseBase.h.
References EIGEN_STATIC_ASSERT_SIZE_1x1.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::evalTo().
template<typename Derived > template<typename Visitor > void Eigen::DenseBase< Derived >::visit (Visitor & visitor) const
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See Also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
Definition at line 77 of file Visitor.h.
References Eigen::Dynamic, and EIGEN_UNROLLING_LIMIT.
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index rows, Index cols) static
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
Output:
See Also
Zero(), Zero(Index)
Definition at line 428 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero (Index size) static
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
Output:
See Also
Zero(), Zero(Index,Index)
Definition at line 451 of file CwiseNullaryOp.h.
template<typename Derived > EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Zero () static
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
Output:
See Also
Zero(Index), Zero(Index,Index)
Definition at line 468 of file CwiseNullaryOp.h.
Friends And Related Function Documentation
template<typename Derived > std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See Also
DenseBase::format()
Definition at line 241 of file IO.h.
References EIGEN_DEFAULT_IO_FORMAT, and Eigen::internal::print_matrix().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/DenseBase.h
include/Eigen/src/Core/Assign.h
include/Eigen/src/Core/BooleanRedux.h
include/Eigen/src/Core/CommaInitializer.h
include/Eigen/src/Core/CwiseNullaryOp.h
include/Eigen/src/Core/EigenBase.h
include/Eigen/src/Core/Flagged.h
include/Eigen/src/Core/Fuzzy.h
include/Eigen/src/Core/IO.h
include/Eigen/src/Core/NestByValue.h
include/Eigen/src/Core/Random.h
include/Eigen/src/Core/Redux.h
include/Eigen/src/Core/Replicate.h
include/Eigen/src/Core/ReturnByValue.h
include/Eigen/src/Core/Reverse.h
include/Eigen/src/Core/Select.h
include/Eigen/src/Core/SelfCwiseBinaryOp.h
include/Eigen/src/Core/Transpose.h
include/Eigen/src/Core/VectorBlock.h
include/Eigen/src/Core/VectorwiseOp.h
include/Eigen/src/Core/Visitor.h