LIA_RAL: Eigen::HouseholderQR< MatrixType > Class Template Reference
Eigen::HouseholderQR< MatrixType > Class Template Reference
Householder QR decomposition of a matrix.
#include <ForwardDeclarations.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
RowsAtCompileTime,(MatrixType::Flags
&RowMajorBit)?RowMajor:ColMajor,
MaxRowsAtCompileTime,
MaxRowsAtCompileTime > MatrixQType
typedef
internal::plain_diag_type
< MatrixType >::type HCoeffsType
typedef
internal::plain_row_type
< MatrixType >::type RowVectorType
typedef HouseholderSequence
< MatrixType, HCoeffsType >
::ConjugateReturnType HouseholderSequenceType
Public Member Functions
HouseholderQR ()
Default Constructor.
HouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
HouseholderQR (const MatrixType &matrix)
template<typename Rhs >
const internal::solve_retval
< HouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ () const
const MatrixType & matrixQR () const
HouseholderQR & compute (const MatrixType &matrix)
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
RowVectorType m_temp
bool m_isInitialized
Detailed Description
template<typename MatrixType>
class Eigen::HouseholderQR< MatrixType >
Householder QR decomposition of a matrix.
Parameters
MatrixType the type of the matrix of which we are computing the QR decomposition
This class performs a QR decomposition of a matrix A into matrices Q and R such that
by using Householder transformations. Here, Q a unitary matrix and R an upper triangular matrix. The result is stored in a compact way compatible with LAPACK.
Note that no pivoting is performed. This is not a rank-revealing decomposition. If you want that feature, use FullPivHouseholderQR or ColPivHouseholderQR instead.
This Householder QR decomposition is faster, but less numerically stable and less feature-full than FullPivHouseholderQR or ColPivHouseholderQR.
See Also
MatrixBase::householderQr()
Definition at line 222 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename MatrixType> typedef internal::plain_diag_type<MatrixType>::type Eigen::HouseholderQR< MatrixType >::HCoeffsType
Definition at line 58 of file HouseholderQR.h.
template<typename MatrixType> typedef HouseholderSequence<MatrixType,HCoeffsType>::ConjugateReturnType Eigen::HouseholderQR< MatrixType >::HouseholderSequenceType
Definition at line 60 of file HouseholderQR.h.
template<typename MatrixType> typedef MatrixType::Index Eigen::HouseholderQR< MatrixType >::Index
Definition at line 56 of file HouseholderQR.h.
template<typename MatrixType> typedef Matrix<Scalar, RowsAtCompileTime, RowsAtCompileTime, (MatrixType::Flags&RowMajorBit) ? RowMajor : ColMajor, MaxRowsAtCompileTime, MaxRowsAtCompileTime> Eigen::HouseholderQR< MatrixType >::MatrixQType
Definition at line 57 of file HouseholderQR.h.
template<typename MatrixType> typedef _MatrixType Eigen::HouseholderQR< MatrixType >::MatrixType
Definition at line 46 of file HouseholderQR.h.
template<typename MatrixType> typedef MatrixType::RealScalar Eigen::HouseholderQR< MatrixType >::RealScalar
Definition at line 55 of file HouseholderQR.h.
template<typename MatrixType> typedef internal::plain_row_type<MatrixType>::type Eigen::HouseholderQR< MatrixType >::RowVectorType
Definition at line 59 of file HouseholderQR.h.
template<typename MatrixType> typedef MatrixType::Scalar Eigen::HouseholderQR< MatrixType >::Scalar
Definition at line 54 of file HouseholderQR.h.
Member Enumeration Documentation
template<typename MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 47 of file HouseholderQR.h.
Constructor & Destructor Documentation
template<typename MatrixType> Eigen::HouseholderQR< MatrixType >::HouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via HouseholderQR::compute(const MatrixType&).
Definition at line 68 of file HouseholderQR.h.
template<typename MatrixType> Eigen::HouseholderQR< MatrixType >::HouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See Also
HouseholderQR()
Definition at line 76 of file HouseholderQR.h.
template<typename MatrixType> Eigen::HouseholderQR< MatrixType >::HouseholderQR (const MatrixType & matrix) inline
Definition at line 82 of file HouseholderQR.h.
Member Function Documentation
template<typename MatrixType > MatrixType::RealScalar Eigen::HouseholderQR< MatrixType >::absDeterminant () const
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See Also
logAbsDeterminant(), MatrixBase::determinant()
Definition at line 174 of file HouseholderQR.h.
References abs(), and eigen_assert.
template<typename MatrixType> Index Eigen::HouseholderQR< MatrixType >::cols (void) const inline
Definition at line 163 of file HouseholderQR.h.
Referenced by Eigen::QR< MatrixType >::matrixQ(), and Eigen::QR< MatrixType >::matrixR().
template<typename MatrixType> HouseholderQR< MatrixType > & Eigen::HouseholderQR< MatrixType >::compute (const MatrixType & matrix)
Definition at line 313 of file HouseholderQR.h.
References Eigen::internal::householder_qr_inplace_blocked(), min(), and Eigen::HouseholderQR< MatrixType >::rows().
Referenced by Eigen::HouseholderQR< Eigen::Matrix >::HouseholderQR().
template<typename MatrixType> const HCoeffsType& Eigen::HouseholderQR< MatrixType >::hCoeffs () const inline
Definition at line 164 of file HouseholderQR.h.
template<typename MatrixType> HouseholderSequenceType Eigen::HouseholderQR< MatrixType >::householderQ (void) const inline
Definition at line 116 of file HouseholderQR.h.
Referenced by Eigen::QR< MatrixType >::matrixQ().
template<typename MatrixType > MatrixType::RealScalar Eigen::HouseholderQR< MatrixType >::logAbsDeterminant () const
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See Also
absDeterminant(), MatrixBase::determinant()
Definition at line 182 of file HouseholderQR.h.
References eigen_assert.
template<typename MatrixType> const MatrixType& Eigen::HouseholderQR< MatrixType >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored in a LAPACK-compatible way.
Definition at line 125 of file HouseholderQR.h.
Referenced by Eigen::QR< MatrixType >::matrixR().
template<typename MatrixType> Index Eigen::HouseholderQR< MatrixType >::rows (void) const inline
Definition at line 162 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< MatrixType >::compute(), and Eigen::QR< MatrixType >::matrixQ().
template<typename MatrixType> template<typename Rhs > const internal::solve_retval<HouseholderQR, Rhs> Eigen::HouseholderQR< MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
This method finds a solution x to the equation Ax=b, where A is the matrix of which *this is the QR decomposition, if any exists.
Parameters
b the right-hand-side of the equation to solve.
Returns
a solution.
Note
The case where b is a matrix is not yet implemented. Also, this code is space inefficient.
Example:
Output:
Definition at line 110 of file HouseholderQR.h.
Member Data Documentation
template<typename MatrixType> HCoeffsType Eigen::HouseholderQR< MatrixType >::m_hCoeffs protected
Definition at line 168 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< Eigen::Matrix >::hCoeffs(), and Eigen::HouseholderQR< Eigen::Matrix >::householderQ().
template<typename MatrixType> bool Eigen::HouseholderQR< MatrixType >::m_isInitialized protected
Definition at line 170 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< Eigen::Matrix >::householderQ(), Eigen::HouseholderQR< Eigen::Matrix >::matrixQR(), and Eigen::HouseholderQR< Eigen::Matrix >::solve().
template<typename MatrixType> MatrixType Eigen::HouseholderQR< MatrixType >::m_qr protected
Definition at line 167 of file HouseholderQR.h.
Referenced by Eigen::HouseholderQR< Eigen::Matrix >::cols(), Eigen::HouseholderQR< Eigen::Matrix >::householderQ(), Eigen::HouseholderQR< Eigen::Matrix >::matrixQR(), and Eigen::HouseholderQR< Eigen::Matrix >::rows().
template<typename MatrixType> RowVectorType Eigen::HouseholderQR< MatrixType >::m_temp protected
Definition at line 169 of file HouseholderQR.h.
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/QR/HouseholderQR.h