LIA_RAL: SymbTab Class Reference
SymbTab Class Reference
#include <SequenceExtractor.h>
Public Member Functions
void init (bool val=false)
void reserveMem ()
void setNbSymb (short int nbSymb)
SymbTab (short int nbSymb)
SymbTab ()
SymbTab (const SymbTab &)
~SymbTab ()
SymbTab & operator= (const SymbTab &symbTab)
bool operator== (const SymbTab &)
bool operator!= (const SymbTab &)
bool isIn (short int symb)
void setSymb (short int symb)
short int getNbSymb ()
void show ()
Private Attributes
short int _nbSymb
bool * _symbTab
Detailed Description
Definition at line 62 of file SequenceExtractor.h.
Constructor & Destructor Documentation
SymbTab::SymbTab (short int nbSymb) inline
Definition at line 69 of file SequenceExtractor.h.
References _nbSymb, init(), and reserveMem().
SymbTab::SymbTab () inline
Definition at line 70 of file SequenceExtractor.h.
References _nbSymb, and _symbTab.
SymbTab::SymbTab (const SymbTab & obj)
Definition at line 257 of file SequenceExtractor.cpp.
References _nbSymb, _symbTab, and reserveMem().
SymbTab::~SymbTab () inline
Definition at line 72 of file SequenceExtractor.h.
References _symbTab.
Member Function Documentation
short int SymbTab::getNbSymb () inline
Definition at line 78 of file SequenceExtractor.h.
References _nbSymb.
Referenced by SequenceDecoder::_save().
void SymbTab::init (bool val = false) inline
Definition at line 66 of file SequenceExtractor.h.
References _nbSymb, and _symbTab.
Referenced by SymbTab().
bool SymbTab::isIn (short int symb)
Definition at line 283 of file SequenceExtractor.cpp.
References _nbSymb, and _symbTab.
Referenced by SequenceDecoder::_decode(), and SequenceDecoder::_save().
bool SymbTab::operator!= (const SymbTab & obj)
Definition at line 277 of file SequenceExtractor.cpp.
References _nbSymb, and _symbTab.
SymbTab & SymbTab::operator= (const SymbTab & symbTab)
Definition at line 262 of file SequenceExtractor.cpp.
References _nbSymb, _symbTab, and reserveMem().
bool SymbTab::operator== (const SymbTab & obj)
Definition at line 271 of file SequenceExtractor.cpp.
References _nbSymb, and _symbTab.
void SymbTab::reserveMem ()
Definition at line 254 of file SequenceExtractor.cpp.
References _nbSymb, and _symbTab.
Referenced by Seq::_reserveMem(), operator=(), and SymbTab().
void SymbTab::setNbSymb (short int nbSymb) inline
Definition at line 68 of file SequenceExtractor.h.
References _nbSymb.
Referenced by Seq::_reserveMem().
void SymbTab::setSymb (short int symb)
Definition at line 291 of file SequenceExtractor.cpp.
References _nbSymb, and _symbTab.
Referenced by SequenceDecoder::_load().
void SymbTab::show ()
Definition at line 296 of file SequenceExtractor.cpp.
References _nbSymb, and _symbTab.
Referenced by Seq::show().
Member Data Documentation
short int SymbTab::_nbSymb private
Definition at line 63 of file SequenceExtractor.h.
Referenced by getNbSymb(), init(), isIn(), operator!=(), operator=(), operator==(), reserveMem(), setNbSymb(), setSymb(), show(), and SymbTab().
bool* SymbTab::_symbTab private
Definition at line 64 of file SequenceExtractor.h.
Referenced by init(), isIn(), operator!=(), operator=(), operator==(), reserveMem(), setSymb(), show(), SymbTab(), and ~SymbTab().
The documentation for this class was generated from the following files:
LIA_Utils/SequenceExtractor/include/SequenceExtractor.h
LIA_Utils/SequenceExtractor/src/SequenceExtractor.cpp