LIA_RAL: Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs > Class Template Reference
#include <GeneralBlockPanelKernel.h>
Classes
struct DoublePacket
Public Types
enum {
ConjLhs = _ConjLhs, ConjRhs = _ConjRhs, Vectorizable, RealPacketSize = Vectorizable ? packet_traits<RealScalar>::size : 1,
ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1, nr = 2, mr = 2 * ResPacketSize, WorkSpaceFactor = Vectorizable ? 2*nr*RealPacketSize : nr,
LhsProgress = ResPacketSize, RhsProgress = Vectorizable ? 2*ResPacketSize : 1
}
typedef std::complex< RealScalar > Scalar
typedef std::complex< RealScalar > LhsScalar
typedef std::complex< RealScalar > RhsScalar
typedef std::complex< RealScalar > ResScalar
typedef packet_traits
< RealScalar >::type RealPacket
typedef packet_traits< Scalar >
::type ScalarPacket
typedef conditional
< Vectorizable, RealPacket,
Scalar >::type LhsPacket
typedef conditional
< Vectorizable, DoublePacket,
Scalar >::type RhsPacket
typedef conditional
< Vectorizable, ScalarPacket,
Scalar >::type ResPacket
typedef conditional
< Vectorizable, DoublePacket,
Scalar >::type AccPacket
Public Member Functions
EIGEN_STRONG_INLINE void initAcc (Scalar &p)
EIGEN_STRONG_INLINE void initAcc (DoublePacket &p)
EIGEN_STRONG_INLINE void unpackRhs (DenseIndex n, const Scalar *rhs, Scalar *b)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, DoublePacket &dest) const
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, DoublePacket &c, RhsPacket &) const
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, ResPacket &c, RhsPacket &) const
EIGEN_STRONG_INLINE void acc (const Scalar &c, const Scalar &alpha, Scalar &r) const
EIGEN_STRONG_INLINE void acc (const DoublePacket &c, const ResPacket &alpha, ResPacket &r) const
Protected Attributes
conj_helper< LhsScalar,
RhsScalar, ConjLhs, ConjRhs > cj
Detailed Description
template<typename RealScalar, bool _ConjLhs, bool _ConjRhs>
class Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >
Definition at line 302 of file GeneralBlockPanelKernel.h.
Member Typedef Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacket,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::AccPacket
Definition at line 337 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,RealPacket, Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsPacket
Definition at line 334 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::LhsScalar
Definition at line 306 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<RealScalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RealPacket
Definition at line 326 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,ScalarPacket,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResPacket
Definition at line 336 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ResScalar
Definition at line 308 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef conditional<Vectorizable,DoublePacket,Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsPacket
Definition at line 335 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::RhsScalar
Definition at line 307 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::Scalar
Definition at line 305 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> typedef packet_traits<Scalar>::type Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::ScalarPacket
Definition at line 327 of file GeneralBlockPanelKernel.h.
Member Enumeration Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
RealPacketSize
ResPacketSize
nr
mr
WorkSpaceFactor
LhsProgress
RhsProgress
Definition at line 310 of file GeneralBlockPanelKernel.h.
Member Function Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const Scalar & c, const Scalar & alpha, Scalar & r) const inline
Definition at line 390 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc (const DoublePacket & c, const ResPacket & alpha, ResPacket & r) const inline
Definition at line 392 of file GeneralBlockPanelKernel.h.
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ConjLhs, Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ConjRhs, Eigen::internal::padd(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pmadd(), and Eigen::internal::psub().
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (Scalar & p) inline
Definition at line 339 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::initAcc (DoublePacket & p) inline
Definition at line 341 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
Definition at line 374 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, ResPacket & dest) const inline
Definition at line 365 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::loadRhs (const RhsScalar * b, DoublePacket & dest) const inline
Definition at line 367 of file GeneralBlockPanelKernel.h.
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ResPacketSize.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, DoublePacket & c, RhsPacket &) const inline
Definition at line 379 of file GeneralBlockPanelKernel.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd (const LhsPacket & a, const RhsPacket & b, ResPacket & c, RhsPacket &) const inline
Definition at line 385 of file GeneralBlockPanelKernel.h.
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::unpackRhs (DenseIndex n, const Scalar * rhs, Scalar * b) inline
Definition at line 351 of file GeneralBlockPanelKernel.h.
References imag(), real(), Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::ResPacketSize, and Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::Vectorizable.
Member Data Documentation
template<typename RealScalar , bool _ConjLhs, bool _ConjRhs> conj_helper<LhsScalar,RhsScalar,ConjLhs,ConjRhs> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::cj protected
Definition at line 421 of file GeneralBlockPanelKernel.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/products/GeneralBlockPanelKernel.h