LIA_RAL: Translate Class Reference
Translate Class Reference
Translate filename into loc and sent.
#include <FactorAnalysis.h>
Public Member Functions
Translate ()
Translate (XList &fileList)
Fill structure with id and idxs.
~Translate ()
unsigned long locNb (const String &file)
Get speaker nb.
unsigned long sessionNb (const String &file)
Get seesion nb.
Private Member Functions
long _idxOfID (const String &file)
idx in XLine
Private Attributes
XLine _id
ULongVector _locidx
ULongVector _sessionidx
Detailed Description
Translate filename into loc and sent.
Definition at line 73 of file FactorAnalysis.h.
Constructor & Destructor Documentation
Translate::Translate () inline
Definition at line 87 of file FactorAnalysis.h.
Translate::Translate (XList & fileList) inline
Fill structure with id and idxs.
Definition at line 90 of file FactorAnalysis.h.
Translate::~Translate () inline
Definition at line 104 of file FactorAnalysis.h.
Member Function Documentation
long Translate::_idxOfID (const String & file) inline private
idx in XLine
Definition at line 79 of file FactorAnalysis.h.
unsigned long Translate::locNb (const String & file) inline
Get speaker nb.
Definition at line 107 of file FactorAnalysis.h.
Referenced by FactorAnalysisStat::computeAndAccumulateGeneralFAStats(), FactorAnalysisStat::getFactorAnalysisModel(), FactorAnalysisStat::getMplusDY(), and FactorAnalysisStat::setYFromModel().
unsigned long Translate::sessionNb (const String & file) inline
Get seesion nb.
Definition at line 114 of file FactorAnalysis.h.
Referenced by FactorAnalysisStat::computeAndAccumulateGeneralFAStats(), FactorAnalysisStat::getUX(), and FactorAnalysisStat::getXEstimate().
Member Data Documentation
XLine Translate::_id private
Definition at line 74 of file FactorAnalysis.h.
ULongVector Translate::_locidx private
Definition at line 75 of file FactorAnalysis.h.
ULongVector Translate::_sessionidx private
Definition at line 76 of file FactorAnalysis.h.
The documentation for this class was generated from the following file:
LIA_SpkTools/include/FactorAnalysis.h