LIA_RAL: JFATranslate Class Reference
JFATranslate Class Reference
#include <AccumulateJFAStat.h>
Public Member Functions
JFATranslate ()
JFATranslate (XList &fileList)
~JFATranslate ()
unsigned long locNb (const String &file)
unsigned long firstSession (unsigned long spk)
unsigned long numSession (unsigned long spk, unsigned long session)
unsigned long locNb (unsigned long idx)
unsigned long sessionNb (const String &file)
Private Member Functions
long _idxOfID (const String &file)
idx in XLine
Private Attributes
XLine _id
ULongVector _locidx
ULongVector _sessionidx
Detailed Description
This class represents an index of speakers and sessions A Transate contains the indexes of speakers and sessions
Author
Anthony Larcher alarc.nosp@m.her@.nosp@m.i2r.a.nosp@m.-sta.nosp@m.r.edu.nosp@m..sg
Version
1.0
Date
2010
Definition at line 78 of file AccumulateJFAStat.h.
Constructor & Destructor Documentation
JFATranslate::JFATranslate () inline
Definition at line 95 of file AccumulateJFAStat.h.
JFATranslate::JFATranslate (XList & fileList) inline
Fill structure with id and idxs
Definition at line 99 of file AccumulateJFAStat.h.
JFATranslate::~JFATranslate () inline
Definition at line 113 of file AccumulateJFAStat.h.
Member Function Documentation
long JFATranslate::_idxOfID (const String & file) inline private
idx in XLine
Definition at line 86 of file AccumulateJFAStat.h.
unsigned long JFATranslate::firstSession (unsigned long spk) inline
Return the idx of the first session of a speaker
Parameters
spk idx of the targeted speaker
Returns
the idx of the first session of a speaker spk
Definition at line 129 of file AccumulateJFAStat.h.
unsigned long JFATranslate::locNb (const String & file) inline
Return the idx of speakers
Parameters
file name of the feature file
Returns
the idx of the given speaker
Definition at line 119 of file AccumulateJFAStat.h.
Referenced by JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::computeAndAccumulateJFAStatUnThreaded(), JFAAcc::getMplusDZ(), JFAAcc::getMplusVYplusDZ(), JFAAcc::getVUYX(), JFAAcc::getVY(), and JFAAcc::getVYplusDZ().
unsigned long JFATranslate::locNb (unsigned long idx) inline
Return the idx of speakers
Parameters
index of the feature file
Returns
the idx of the given speaker
Definition at line 151 of file AccumulateJFAStat.h.
unsigned long JFATranslate::numSession (unsigned long spk, unsigned long session) inline
Return the idx of a given session of a speaker
Parameters
spk idx of the speaker
session number of the session for the given speaker
Returns
the idx of the session session of the speaker spk
Definition at line 140 of file AccumulateJFAStat.h.
unsigned long JFATranslate::sessionNb (const String & file) inline
Return the idx of a sessions
Parameters
file feature file
Returns
the idx of the session corresponding to the file
Definition at line 159 of file AccumulateJFAStat.h.
Referenced by JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::computeAndAccumulateJFAStatUnThreaded(), and JFAAcc::getUX().
Member Data Documentation
XLine JFATranslate::_id private
Definition at line 79 of file AccumulateJFAStat.h.
ULongVector JFATranslate::_locidx private
Definition at line 80 of file AccumulateJFAStat.h.
ULongVector JFATranslate::_sessionidx private
Definition at line 81 of file AccumulateJFAStat.h.
The documentation for this class was generated from the following file:
LIA_SpkTools/include/AccumulateJFAStat.h