LIA_RAL: Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > Class Template Reference
Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > Class Template Reference
A conjugate gradient solver for sparse self-adjoint problems.
#include <ConjugateGradient.h>
Public Types
enum { UpLo = _UpLo }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef MatrixType::RealScalar RealScalar
typedef _Preconditioner Preconditioner
Public Types inherited from Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >
typedef internal::traits
< ConjugateGradient
< _MatrixType, _UpLo,
_Preconditioner >
>::MatrixType MatrixType
typedef internal::traits
< ConjugateGradient
< _MatrixType, _UpLo,
_Preconditioner >
>::Preconditioner Preconditioner
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef MatrixType::RealScalar RealScalar
Public Member Functions
ConjugateGradient ()
ConjugateGradient (const MatrixType &A)
~ConjugateGradient ()
template<typename Rhs , typename Guess >
const
internal::solve_retval_with_guess
< ConjugateGradient, Rhs,
Guess > solveWithGuess (const MatrixBase< Rhs > &b, const Guess &x0) const
template<typename Rhs , typename Dest >
void _solveWithGuess (const Rhs &b, Dest &x) const
template<typename Rhs , typename Dest >
void _solve (const Rhs &b, Dest &x) const
Public Member Functions inherited from Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >
ConjugateGradient< _MatrixType,
_UpLo, _Preconditioner > & derived ()
const ConjugateGradient
< _MatrixType, _UpLo,
_Preconditioner > & derived () const
IterativeSolverBase ()
IterativeSolverBase (const MatrixType &A)
~IterativeSolverBase ()
ConjugateGradient< _MatrixType,
_UpLo, _Preconditioner > & analyzePattern (const MatrixType &A)
ConjugateGradient< _MatrixType,
_UpLo, _Preconditioner > & factorize (const MatrixType &A)
ConjugateGradient< _MatrixType,
_UpLo, _Preconditioner > & compute (const MatrixType &A)
Index rows () const
Index cols () const
RealScalar tolerance () const
ConjugateGradient< _MatrixType,
_UpLo, _Preconditioner > & setTolerance (RealScalar tolerance)
Preconditioner & preconditioner ()
const Preconditioner & preconditioner () const
int maxIterations () const
ConjugateGradient< _MatrixType,
_UpLo, _Preconditioner > & setMaxIterations (int maxIters)
int iterations () const
RealScalar error () const
const internal::solve_retval
< ConjugateGradient
< _MatrixType, _UpLo,
_Preconditioner >, Rhs > solve (const MatrixBase< Rhs > &b) const
const
internal::sparse_solve_retval
< IterativeSolverBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
ComputationInfo info () const
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Private Types
typedef IterativeSolverBase
< ConjugateGradient > Base
Additional Inherited Members
Protected Member Functions inherited from Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >
void init ()
Protected Attributes inherited from Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >
const MatrixType * mp_matrix
Preconditioner m_preconditioner
int m_maxIterations
RealScalar m_tolerance
RealScalar m_error
int m_iterations
ComputationInfo m_info
bool m_isInitialized
bool m_analysisIsOk
bool m_factorizationIsOk
Detailed Description
template<typename _MatrixType, int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>>
class Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >
A conjugate gradient solver for sparse self-adjoint problems.
This class allows to solve for A.x = b sparse linear problems using a conjugate gradient algorithm. The sparse matrix A must be selfadjoint. The vectors x and b can be either dense or sparse.
Template Parameters
_MatrixType the type of the sparse matrix A, can be a dense or a sparse matrix.
_UpLo the triangular part that will be used for the computations. It can be Lower or Upper. Default is Lower.
_Preconditioner the type of the preconditioner. Default is DiagonalPreconditioner
The maximal number of iterations and tolerance value can be controlled via the setMaxIterations() and setTolerance() methods. The defaults are the size of the problem for the maximal number of iterations and NumTraits<Scalar>::epsilon() for the tolerance.
This class can be used as the direct solver classes. Here is a typical usage example:
int n = 10000;
VectorXd x(n), b(n);
SparseMatrix<double> A(n,n);
// fill A and b
ConjugateGradient<SparseMatrix<double> > cg;
cg.compute(A);
x = cg.solve(b);
std::cout << "#iterations:     " << cg.iterations() << std::endl;
std::cout << "estimated error: " << cg.error()      << std::endl;
// update b, and solve again
x = cg.solve(b);
By default the iterations start with x=0 as an initial guess of the solution. One can control the start using the solveWithGuess() method. Here is a step by step execution example starting with a random guess and printing the evolution of the estimated error:
x = VectorXd::Random(n);
cg.setMaxIterations(1);
int i = 0;
do {
  x = cg.solveWithGuess(b,x);
  std::cout << i << " : " << cg.error() << std::endl;
  ++i;
} while (cg.info()!=Success && i<100);
Note that such a step by step excution is slightly slower.
See Also
class SimplicialCholesky, DiagonalPreconditioner, IdentityPreconditioner
Definition at line 82 of file ConjugateGradient.h.
Member Typedef Documentation
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef IterativeSolverBase<ConjugateGradient> Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::Base private
Definition at line 146 of file ConjugateGradient.h.
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef MatrixType::Index Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::Index
Definition at line 155 of file ConjugateGradient.h.
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef _MatrixType Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::MatrixType
Definition at line 153 of file ConjugateGradient.h.
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef _Preconditioner Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::Preconditioner
Definition at line 157 of file ConjugateGradient.h.
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef MatrixType::RealScalar Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::RealScalar
Definition at line 156 of file ConjugateGradient.h.
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef MatrixType::Scalar Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::Scalar
Definition at line 154 of file ConjugateGradient.h.
Member Enumeration Documentation
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> anonymous enum
Enumerator
UpLo
Definition at line 159 of file ConjugateGradient.h.
Constructor & Destructor Documentation
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::ConjugateGradient () inline
Default constructor.
Definition at line 166 of file ConjugateGradient.h.
Referenced by Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::solveWithGuess().
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::ConjugateGradient (const MatrixType & A) inline
Initialize the solver with matrix A for further Ax=b solving.
This constructor is a shortcut for the default constructor followed by a call to compute().
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
Definition at line 178 of file ConjugateGradient.h.
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::~ConjugateGradient () inline
Definition at line 180 of file ConjugateGradient.h.
Member Function Documentation
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> template<typename Rhs , typename Dest > void Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::_solve (const Rhs & b, Dest & x) const inline
Definition at line 221 of file ConjugateGradient.h.
References Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::_solveWithGuess().
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> template<typename Rhs , typename Dest > void Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::_solveWithGuess (const Rhs & b, Dest & x) const inline
Definition at line 200 of file ConjugateGradient.h.
References Eigen::internal::conjugate_gradient(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::m_error, Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::m_info, Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::m_isInitialized, Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::m_iterations, Eigen::IterativeSolverBase< Derived >::m_preconditioner, Eigen::IterativeSolverBase< Derived >::m_tolerance, Eigen::IterativeSolverBase< Derived >::maxIterations(), Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::mp_matrix, Eigen::NoConvergence, and Eigen::Success.
Referenced by Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::_solve().
template<typename _MatrixType , int _UpLo = Lower, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> template<typename Rhs , typename Guess > const internal::solve_retval_with_guess<ConjugateGradient, Rhs, Guess> Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::solveWithGuess (const MatrixBase< Rhs > & b, const Guess & x0) const inline
Returns
the solution x of using the current decomposition of A x0 as an initial solution.
See Also
compute()
Definition at line 189 of file ConjugateGradient.h.
References Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::ConjugateGradient(), eigen_assert, Eigen::IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::m_isInitialized, and Eigen::IterativeSolverBase< Derived >::rows().
The documentation for this class was generated from the following file:
include/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h