LIA_RAL: ONE_CLASS_Q Class Reference
ONE_CLASS_Q Class Reference
Public Member Functions
ONE_CLASS_Q (const svm_problem &prob, const svm_parameter &param)
Qfloat * get_Q (int i, int len) const
double * get_QD () const
void swap_index (int i, int j) const
~ONE_CLASS_Q ()
Public Member Functions inherited from Kernel
Kernel (int l, svm_node *const *x, const svm_parameter &param)
virtual ~Kernel ()
Public Member Functions inherited from QMatrix
virtual ~QMatrix ()
Private Attributes
Cache * cache
double * QD
Additional Inherited Members
Static Public Member Functions inherited from Kernel
static double k_function (const svm_node *x, const svm_node *y, const svm_parameter &param)
Protected Attributes inherited from Kernel
double(Kernel::* kernel_function)(int i, int j) const
Detailed Description
Definition at line 1303 of file libsvm.cpp.
Constructor & Destructor Documentation
ONE_CLASS_Q::ONE_CLASS_Q (const svm_problem & prob, const svm_parameter & param) inline
Definition at line 1306 of file libsvm.cpp.
References cache, svm_parameter::cache_size, Kernel::kernel_function, svm_problem::l, and QD.
ONE_CLASS_Q::~ONE_CLASS_Q () inline
Definition at line 1339 of file libsvm.cpp.
References cache, and QD.
Member Function Documentation
Qfloat* ONE_CLASS_Q::get_Q (int i, int len) const inline virtual
Implements Kernel.
Definition at line 1315 of file libsvm.cpp.
References cache, Cache::get_data(), and Kernel::kernel_function.
double* ONE_CLASS_Q::get_QD () const inline virtual
Implements Kernel.
Definition at line 1327 of file libsvm.cpp.
References QD.
void ONE_CLASS_Q::swap_index (int i, int j) const inline virtual
Reimplemented from Kernel.
Definition at line 1332 of file libsvm.cpp.
References cache, QD, swap(), Cache::swap_index(), and Kernel::swap_index().
Member Data Documentation
Cache* ONE_CLASS_Q::cache private
Definition at line 1345 of file libsvm.cpp.
Referenced by get_Q(), ONE_CLASS_Q(), swap_index(), and ~ONE_CLASS_Q().
double* ONE_CLASS_Q::QD private
Definition at line 1346 of file libsvm.cpp.
Referenced by get_QD(), ONE_CLASS_Q(), swap_index(), and ~ONE_CLASS_Q().
The documentation for this class was generated from the following file:
LIA_Utils/Svm/src/libsvm.cpp