LIA_RAL: Eigen::JacobiSVD< MatrixType, QRPreconditioner > Class Template Reference
Eigen::JacobiSVD< MatrixType, QRPreconditioner > Class Template Reference
Two-sided Jacobi SVD decomposition of a rectangular matrix.
#include <ForwardDeclarations.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, DiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_DYNAMIC(RowsAtCompileTime,ColsAtCompileTime), MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime, MaxDiagSizeAtCompileTime = EIGEN_SIZE_MIN_PREFER_FIXED(MaxRowsAtCompileTime,MaxColsAtCompileTime), MatrixOptions = MatrixType::Options
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename
MatrixType::Scalar >::Real RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
RowsAtCompileTime,
MatrixOptions,
MaxRowsAtCompileTime,
MaxRowsAtCompileTime > MatrixUType
typedef Matrix< Scalar,
ColsAtCompileTime,
ColsAtCompileTime,
MatrixOptions,
MaxColsAtCompileTime,
MaxColsAtCompileTime > MatrixVType
typedef
internal::plain_diag_type
< MatrixType, RealScalar >
::type SingularValuesType
typedef
internal::plain_row_type
< MatrixType >::type RowType
typedef
internal::plain_col_type
< MatrixType >::type ColType
typedef Matrix< Scalar,
DiagSizeAtCompileTime,
DiagSizeAtCompileTime,
MatrixOptions,
MaxDiagSizeAtCompileTime,
MaxDiagSizeAtCompileTime > WorkMatrixType
Public Member Functions
JacobiSVD ()
Default Constructor.
JacobiSVD (Index rows, Index cols, unsigned int computationOptions=0)
Default Constructor with memory preallocation.
JacobiSVD (const MatrixType &matrix, unsigned int computationOptions=0)
Constructor performing the decomposition of given matrix.
JacobiSVD & compute (const MatrixType &matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
JacobiSVD & compute (const MatrixType &matrix)
Method performing the decomposition of given matrix using current options.
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
const SingularValuesType & singularValues () const
bool computeU () const
bool computeV () const
template<typename Rhs >
const internal::solve_retval
< JacobiSVD, Rhs > solve (const MatrixBase< Rhs > &b) const
Index nonzeroSingularValues () const
Index rows () const
Index cols () const
Protected Attributes
MatrixUType m_matrixU
MatrixVType m_matrixV
SingularValuesType m_singularValues
WorkMatrixType m_workMatrix
bool m_isInitialized
bool m_isAllocated
bool m_computeFullU
bool m_computeThinU
bool m_computeFullV
bool m_computeThinV
unsigned int m_computationOptions
Index m_nonzeroSingularValues
Index m_rows
Index m_cols
Index m_diagSize
internal::qr_preconditioner_impl
< MatrixType, QRPreconditioner,
internal::PreconditionIfMoreColsThanRows > m_qr_precond_morecols
internal::qr_preconditioner_impl
< MatrixType, QRPreconditioner,
internal::PreconditionIfMoreRowsThanCols > m_qr_precond_morerows
Private Member Functions
void allocate (Index rows, Index cols, unsigned int computationOptions)
Friends
template<typename __MatrixType , int _QRPreconditioner, bool _IsComplex>
struct internal::svd_precondition_2x2_block_to_be_real
template<typename __MatrixType , int _QRPreconditioner, int _Case, bool _DoAnything>
struct internal::qr_preconditioner_impl
Detailed Description
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner>
class Eigen::JacobiSVD< MatrixType, QRPreconditioner >
Two-sided Jacobi SVD decomposition of a rectangular matrix.
Parameters
MatrixType the type of the matrix of which we are computing the SVD decomposition
QRPreconditioner this optional parameter allows to specify the type of QR decomposition that will be used internally for the R-SVD step for non-square matrices. See discussion of possible values below.
SVD decomposition consists in decomposing any n-by-p matrix A as a product
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
This JacobiSVD decomposition computes only the singular values by default. If you want U or V, you need to ask for them explicitly.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
Here's an example demonstrating basic usage:
Output:
This JacobiSVD class is a two-sided Jacobi R-SVD decomposition, ensuring optimal reliability and accuracy. The downside is that it's slower than bidiagonalizing SVD algorithms for large square matrices; however its complexity is still where n is the smaller dimension and p is the greater dimension, meaning that it is still of the same order of complexity as the faster bidiagonalizing R-SVD algorithms. In particular, like any R-SVD, it takes advantage of non-squareness in that its complexity is only linear in the greater dimension.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, but the computation is guaranteed to terminate in finite (and reasonable) time.
The possible values for QRPreconditioner are:
ColPivHouseholderQRPreconditioner is the default. In practice it's very safe. It uses column-pivoting QR.
FullPivHouseholderQRPreconditioner, is the safest and slowest. It uses full-pivoting QR. Contrary to other QRs, it doesn't allow computing thin unitaries.
HouseholderQRPreconditioner is the fastest, and less safe and accurate than the pivoting variants. It uses non-pivoting QR. This is very similar in safety and accuracy to the bidiagonalization process used by bidiagonalizing SVD algorithms (since bidiagonalization is inherently non-pivoting). However the resulting SVD is still more reliable than bidiagonalizing SVDs because the Jacobi-based iterarive process is more reliable than the optimized bidiagonal SVD iterations.
NoQRPreconditioner allows not to use a QR preconditioner at all. This is useful if you know that you will only be computing JacobiSVD decompositions of square matrices. Non-square matrices require a QR preconditioner. Using this option will result in faster compilation and smaller executable code. It won't significantly speed up computation, since JacobiSVD is always checking if QR preconditioning is needed before applying it anyway.
See Also
MatrixBase::jacobiSvd()
Definition at line 225 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef internal::plain_col_type<MatrixType>::type Eigen::JacobiSVD< MatrixType, QRPreconditioner >::ColType
Definition at line 504 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef MatrixType::Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::Index
Definition at line 485 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef _MatrixType Eigen::JacobiSVD< MatrixType, QRPreconditioner >::MatrixType
Definition at line 482 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef Matrix<Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::MatrixUType
Definition at line 498 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef Matrix<Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::MatrixVType
Definition at line 501 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef NumTraits<typename MatrixType::Scalar>::Real Eigen::JacobiSVD< MatrixType, QRPreconditioner >::RealScalar
Definition at line 484 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef internal::plain_row_type<MatrixType>::type Eigen::JacobiSVD< MatrixType, QRPreconditioner >::RowType
Definition at line 503 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef MatrixType::Scalar Eigen::JacobiSVD< MatrixType, QRPreconditioner >::Scalar
Definition at line 483 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef internal::plain_diag_type<MatrixType, RealScalar>::type Eigen::JacobiSVD< MatrixType, QRPreconditioner >::SingularValuesType
Definition at line 502 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> typedef Matrix<Scalar, DiagSizeAtCompileTime, DiagSizeAtCompileTime, MatrixOptions, MaxDiagSizeAtCompileTime, MaxDiagSizeAtCompileTime> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::WorkMatrixType
Definition at line 507 of file JacobiSVD.h.
Member Enumeration Documentation
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
DiagSizeAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxDiagSizeAtCompileTime
MatrixOptions
Definition at line 486 of file JacobiSVD.h.
Constructor & Destructor Documentation
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::JacobiSVD () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via JacobiSVD::compute(const MatrixType&).
Definition at line 514 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::JacobiSVD (Index rows, Index cols, unsigned int computationOptions = 0) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See Also
JacobiSVD()
Definition at line 528 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::JacobiSVD (const MatrixType & matrix, unsigned int computationOptions = 0) inline
Constructor performing the decomposition of given matrix.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are ComputeFullU, ComputeThinU, ComputeFullV, ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
Definition at line 547 of file JacobiSVD.h.
Member Function Documentation
template<typename MatrixType , int QRPreconditioner> void Eigen::JacobiSVD< MatrixType, QRPreconditioner >::allocate (Index rows, Index cols, unsigned int computationOptions) private
Definition at line 679 of file JacobiSVD.h.
References Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, Eigen::Dynamic, eigen_assert, EIGEN_IMPLIES, Eigen::FullPivHouseholderQRPreconditioner, and min().
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::cols (void) const inline
Definition at line 653 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate().
template<typename MatrixType, int QRPreconditioner> JacobiSVD< MatrixType, QRPreconditioner > & Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute (const MatrixType & matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are ComputeFullU, ComputeThinU, ComputeFullV, ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
Definition at line 726 of file JacobiSVD.h.
References abs(), max(), Eigen::precision(), Eigen::internal::real_2x2_jacobi_svd(), swap(), and Eigen::JacobiRotation< Scalar >::transpose().
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::JacobiSVD().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> JacobiSVD& Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute (const MatrixType & matrix) inline
Method performing the decomposition of given matrix using current options.
Parameters
matrix the matrix to decompose
This method uses the current computationOptions, as already passed to the constructor or to compute(const MatrixType&, unsigned int).
Definition at line 574 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::computeU () const inline
Returns
true if U (full or thin) is asked for in this SVD decomposition
Definition at line 623 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::matrixU(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::solve().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::computeV () const inline
Returns
true if V (full or thin) is asked for in this SVD decomposition
Definition at line 625 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::matrixV(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run(), and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::solve().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> const MatrixUType& Eigen::JacobiSVD< MatrixType, QRPreconditioner >::matrixU () const inline
Returns
the U matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the U matrix is n-by-n if you asked for ComputeFullU, and is n-by-m if you asked for ComputeThinU.
The m first columns of U are the left singular vectors of the matrix being decomposed.
This method asserts that you asked for U to be computed.
Definition at line 588 of file JacobiSVD.h.
Referenced by Eigen::Transform< _Scalar, _Dim >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim >::computeScalingRotation(), and Eigen::umeyama().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> const MatrixVType& Eigen::JacobiSVD< MatrixType, QRPreconditioner >::matrixV () const inline
Returns
the V matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the V matrix is p-by-p if you asked for ComputeFullV, and is p-by-m if you asked for ComputeThinV.
The m first columns of V are the right singular vectors of the matrix being decomposed.
This method asserts that you asked for V to be computed.
Definition at line 604 of file JacobiSVD.h.
Referenced by Eigen::Transform< _Scalar, _Dim >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim >::computeScalingRotation(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), and Eigen::umeyama().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::nonzeroSingularValues () const inline
Returns
the number of singular values that are not exactly 0
Definition at line 646 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::rows (void) const inline
Definition at line 652 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> const SingularValuesType& Eigen::JacobiSVD< MatrixType, QRPreconditioner >::singularValues () const inline
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
Definition at line 616 of file JacobiSVD.h.
Referenced by Eigen::Transform< _Scalar, _Dim >::computeRotationScaling(), Eigen::Transform< _Scalar, _Dim >::computeScalingRotation(), and Eigen::umeyama().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> template<typename Rhs > const internal::solve_retval<JacobiSVD, Rhs> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::solve (const MatrixBase< Rhs > & b) const inline
Returns
a (least squares) solution of using the current SVD decomposition of A.
Parameters
b the right-hand-side of the equation to solve.
Note
Solving requires both U and V to be computed. Thin U and V are enough, there is no need for full U or V.
SVD solving is implicitly least-squares. Thus, this method serves both purposes of exact solving and least-squares solving. In other words, the returned solution is guaranteed to minimize the Euclidean norm .
Definition at line 638 of file JacobiSVD.h.
Friends And Related Function Documentation
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> template<typename __MatrixType , int _QRPreconditioner, int _Case, bool _DoAnything> friend struct internal::qr_preconditioner_impl friend
Definition at line 672 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> template<typename __MatrixType , int _QRPreconditioner, bool _IsComplex> friend struct internal::svd_precondition_2x2_block_to_be_real friend
Definition at line 670 of file JacobiSVD.h.
Member Data Documentation
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_cols protected
Definition at line 667 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::cols().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> unsigned int Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computationOptions protected
Definition at line 666 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullU protected
Definition at line 664 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeU(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullV protected
Definition at line 665 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeV(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeThinU protected
Definition at line 664 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeU(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeThinV protected
Definition at line 665 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::computeV(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_diagSize protected
Definition at line 667 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_isAllocated protected
Definition at line 663 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> bool Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_isInitialized protected
Definition at line 663 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::matrixU(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::matrixV(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::nonzeroSingularValues(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::singularValues(), and Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::solve().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> MatrixUType Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixU protected
Definition at line 659 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::matrixU(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> MatrixVType Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixV protected
Definition at line 660 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::matrixV(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), and Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_nonzeroSingularValues protected
Definition at line 667 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::nonzeroSingularValues().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> internal::qr_preconditioner_impl<MatrixType, QRPreconditioner, internal::PreconditionIfMoreColsThanRows> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_qr_precond_morecols protected
Definition at line 674 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> internal::qr_preconditioner_impl<MatrixType, QRPreconditioner, internal::PreconditionIfMoreRowsThanCols> Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_qr_precond_morerows protected
Definition at line 675 of file JacobiSVD.h.
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> Index Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_rows protected
Definition at line 667 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::rows().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> SingularValuesType Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_singularValues protected
Definition at line 661 of file JacobiSVD.h.
Referenced by Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::singularValues().
template<typename MatrixType, int QRPreconditioner = ColPivHouseholderQRPreconditioner> WorkMatrixType Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_workMatrix protected
Definition at line 662 of file JacobiSVD.h.
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), and Eigen::internal::qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/SVD/JacobiSVD.h