LIA_RAL: TabClientLine Class Reference
TabClientLine Class Reference
#include <GeneralTools.h>
Public Member Functions
unsigned long nbClientLine ()
String & getClientName (unsigned long)
MixtureGD & getClientModel (unsigned long)
unsigned long loadLine (XLine *, String="", bool=true, bool=false)
TabClientLine (MixtureServer &, Config &, unsigned long=CST_MAX_CLIENT_LINE)
~TabClientLine ()
Private Attributes
unsigned long nbMaxModelLine
MixtureServer * ms
Config * conf
MixtureGD ** tabModel
XLine * pline
unsigned long nbModelsLine
Detailed Description
Definition at line 78 of file GeneralTools.h.
Constructor & Destructor Documentation
TabClientLine::TabClientLine (MixtureServer & m, Config & config, unsigned long maxModel = CST_MAX_CLIENT_LINE)
Definition at line 135 of file GeneralTools.cpp.
References conf, ms, nbMaxModelLine, pline, and tabModel.
TabClientLine::~TabClientLine ()
Definition at line 144 of file GeneralTools.cpp.
References tabModel.
Member Function Documentation
MixtureGD & TabClientLine::getClientModel (unsigned long nClient)
Definition at line 78 of file GeneralTools.cpp.
References tabModel.
Referenced by ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), and ComputeTestNAP().
String & TabClientLine::getClientName (unsigned long nClient)
Definition at line 73 of file GeneralTools.cpp.
References pline.
Referenced by ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), and ComputeTestNAP().
unsigned long TabClientLine::loadLine (XLine * linep, String label = "", bool useDefaultClientModel = true, bool byUserRep = false)
Definition at line 90 of file GeneralTools.cpp.
References ms, nbMaxModelLine, nbModelsLine, pline, tabModel, and verbose.
Referenced by ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), and ComputeTestNAP().
unsigned long TabClientLine::nbClientLine ()
Definition at line 69 of file GeneralTools.cpp.
References nbModelsLine.
Referenced by ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), and ComputeTestNAP().
Member Data Documentation
Config* TabClientLine::conf private
Definition at line 81 of file GeneralTools.h.
Referenced by TabClientLine().
MixtureServer* TabClientLine::ms private
Definition at line 80 of file GeneralTools.h.
Referenced by loadLine(), and TabClientLine().
unsigned long TabClientLine::nbMaxModelLine private
Definition at line 79 of file GeneralTools.h.
Referenced by loadLine(), and TabClientLine().
unsigned long TabClientLine::nbModelsLine private
Definition at line 84 of file GeneralTools.h.
Referenced by loadLine(), and nbClientLine().
XLine* TabClientLine::pline private
Definition at line 83 of file GeneralTools.h.
Referenced by getClientName(), loadLine(), and TabClientLine().
MixtureGD** TabClientLine::tabModel private
Definition at line 82 of file GeneralTools.h.
Referenced by getClientModel(), loadLine(), TabClientLine(), and ~TabClientLine().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/GeneralTools.h
LIA_SpkTools/src/GeneralTools.cpp