LIA_RAL: Eigen::Transpose< MatrixType > Class Template Reference
Eigen::Transpose< MatrixType > Class Template Reference
Expression of the transpose of a matrix.
#include <Transpose.h>
Public Types
typedef TransposeImpl
< MatrixType, typename
internal::traits< MatrixType >
::StorageKind >::Base Base
Public Member Functions
Transpose (MatrixType &matrix)
Index rows () const
Index cols () const
const internal::remove_all
< typename MatrixType::Nested >
::type & nestedExpression () const
internal::remove_all< typename
MatrixType::Nested >::type & nestedExpression ()
Protected Attributes
MatrixType::Nested m_matrix
Detailed Description
template<typename MatrixType>
class Eigen::Transpose< MatrixType >
Expression of the transpose of a matrix.
Parameters
MatrixType the type of the object of which we are taking the transpose
This class represents an expression of the transpose of a matrix. It is the return type of MatrixBase::transpose() and MatrixBase::adjoint() and most of the time this is the only way it is used.
See Also
MatrixBase::transpose(), MatrixBase::adjoint()
Definition at line 57 of file Transpose.h.
Member Typedef Documentation
template<typename MatrixType> typedef TransposeImpl<MatrixType,typename internal::traits<MatrixType>::StorageKind>::Base Eigen::Transpose< MatrixType >::Base
Definition at line 62 of file Transpose.h.
Constructor & Destructor Documentation
template<typename MatrixType> Eigen::Transpose< MatrixType >::Transpose (MatrixType & matrix) inline
Definition at line 65 of file Transpose.h.
Member Function Documentation
template<typename MatrixType> Index Eigen::Transpose< MatrixType >::cols (void) const inline
Definition at line 70 of file Transpose.h.
template<typename MatrixType> const internal::remove_all<typename MatrixType::Nested>::type& Eigen::Transpose< MatrixType >::nestedExpression () const inline
Returns
the nested expression
Definition at line 74 of file Transpose.h.
Referenced by Eigen::internal::blas_traits< Transpose< NestedXpr > >::extract(), and Eigen::internal::blas_traits< Transpose< NestedXpr > >::extractScalarFactor().
template<typename MatrixType> internal::remove_all<typename MatrixType::Nested>::type& Eigen::Transpose< MatrixType >::nestedExpression () inline
Returns
the nested expression
Definition at line 78 of file Transpose.h.
template<typename MatrixType> Index Eigen::Transpose< MatrixType >::rows (void) const inline
Definition at line 69 of file Transpose.h.
Referenced by Eigen::Transpose< PermutationBase< Derived > >::evalTo().
Member Data Documentation
template<typename MatrixType> MatrixType::Nested Eigen::Transpose< MatrixType >::m_matrix protected
Definition at line 81 of file Transpose.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/Transpose.h