LIA_RAL: Eigen::SimplicialCholesky< _MatrixType, _UpLo > Class Template Reference
Eigen::SimplicialCholesky< _MatrixType, _UpLo > Class Template Reference
#include <SimplicialCholesky.h>
Public Types
enum { UpLo = _UpLo }
typedef _MatrixType MatrixType
typedef SimplicialCholeskyBase
< SimplicialCholesky > Base
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef SparseMatrix< Scalar,
ColMajor, Index > CholMatrixType
typedef Matrix< Scalar,
Dynamic, 1 > VectorType
typedef internal::traits
< SimplicialCholesky > Traits
typedef internal::traits
< SimplicialLDLT< MatrixType,
UpLo > > LDLTTraits
typedef internal::traits
< SimplicialLLT< MatrixType,
UpLo > > LLTTraits
Public Types inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< _MatrixType, _UpLo > >
enum
typedef internal::traits
< SimplicialCholesky
< _MatrixType, _UpLo >
>::MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef SparseMatrix< Scalar,
ColMajor, Index > CholMatrixType
typedef Matrix< Scalar,
Dynamic, 1 > VectorType
Public Member Functions
SimplicialCholesky ()
SimplicialCholesky (const MatrixType &matrix)
SimplicialCholesky & setMode (SimplicialCholeskyMode mode)
const VectorType vectorD () const
const CholMatrixType rawMatrix () const
SimplicialCholesky & compute (const MatrixType &matrix)
void analyzePattern (const MatrixType &a)
void factorize (const MatrixType &a)
template<typename Rhs , typename Dest >
void _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
Scalar determinant () const
Public Member Functions inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< _MatrixType, _UpLo > >
SimplicialCholeskyBase ()
SimplicialCholeskyBase (const MatrixType &matrix)
~SimplicialCholeskyBase ()
SimplicialCholesky
< _MatrixType, _UpLo > & derived ()
const SimplicialCholesky
< _MatrixType, _UpLo > & derived () const
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
const internal::solve_retval
< SimplicialCholeskyBase, Rhs > solve (const MatrixBase< Rhs > &b) const
const
internal::sparse_solve_retval
< SimplicialCholeskyBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
const PermutationMatrix
< Dynamic, Dynamic, Index > & permutationP () const
const PermutationMatrix
< Dynamic, Dynamic, Index > & permutationPinv () const
SimplicialCholesky
< _MatrixType, _UpLo > & setShift (const RealScalar &offset, const RealScalar &scale=1)
void dumpMemory (Stream &s)
void _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Protected Attributes
bool m_LDLT
Protected Attributes inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< _MatrixType, _UpLo > >
ComputationInfo m_info
bool m_isInitialized
bool m_factorizationIsOk
bool m_analysisIsOk
CholMatrixType m_matrix
VectorType m_diag
VectorXi m_parent
VectorXi m_nonZerosPerCol
PermutationMatrix< Dynamic,
Dynamic, Index > m_P
PermutationMatrix< Dynamic,
Dynamic, Index > m_Pinv
RealScalar m_shiftOffset
RealScalar m_shiftScale
Additional Inherited Members
Protected Member Functions inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< _MatrixType, _UpLo > >
void compute (const MatrixType &matrix)
void factorize (const MatrixType &a)
void factorize_preordered (const CholMatrixType &a)
void analyzePattern (const MatrixType &a, bool doLDLT)
void analyzePattern_preordered (const CholMatrixType &a, bool doLDLT)
void ordering (const MatrixType &a, CholMatrixType &ap)
Detailed Description
template<typename _MatrixType, int _UpLo = Lower>
class Eigen::SimplicialCholesky< _MatrixType, _UpLo >
Deprecated:
use SimplicialLDLT or class SimplicialLLT
See Also
class SimplicialLDLT, class SimplicialLLT
Definition at line 306 of file SimplicialCholesky.h.
Member Typedef Documentation
template<typename _MatrixType , int _UpLo = Lower> typedef SimplicialCholeskyBase<SimplicialCholesky> Eigen::SimplicialCholesky< _MatrixType, _UpLo >::Base
Definition at line 537 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef SparseMatrix<Scalar,ColMajor,Index> Eigen::SimplicialCholesky< _MatrixType, _UpLo >::CholMatrixType
Definition at line 541 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef MatrixType::Index Eigen::SimplicialCholesky< _MatrixType, _UpLo >::Index
Definition at line 540 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef internal::traits<SimplicialLDLT<MatrixType,UpLo> > Eigen::SimplicialCholesky< _MatrixType, _UpLo >::LDLTTraits
Definition at line 544 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef internal::traits<SimplicialLLT<MatrixType,UpLo> > Eigen::SimplicialCholesky< _MatrixType, _UpLo >::LLTTraits
Definition at line 545 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef _MatrixType Eigen::SimplicialCholesky< _MatrixType, _UpLo >::MatrixType
Definition at line 535 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef MatrixType::RealScalar Eigen::SimplicialCholesky< _MatrixType, _UpLo >::RealScalar
Definition at line 539 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef MatrixType::Scalar Eigen::SimplicialCholesky< _MatrixType, _UpLo >::Scalar
Definition at line 538 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef internal::traits<SimplicialCholesky> Eigen::SimplicialCholesky< _MatrixType, _UpLo >::Traits
Definition at line 543 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> typedef Matrix<Scalar,Dynamic,1> Eigen::SimplicialCholesky< _MatrixType, _UpLo >::VectorType
Definition at line 542 of file SimplicialCholesky.h.
Member Enumeration Documentation
template<typename _MatrixType , int _UpLo = Lower> anonymous enum
Enumerator
UpLo
Definition at line 536 of file SimplicialCholesky.h.
Constructor & Destructor Documentation
template<typename _MatrixType , int _UpLo = Lower> Eigen::SimplicialCholesky< _MatrixType, _UpLo >::SimplicialCholesky () inline
Definition at line 547 of file SimplicialCholesky.h.
template<typename _MatrixType , int _UpLo = Lower> Eigen::SimplicialCholesky< _MatrixType, _UpLo >::SimplicialCholesky (const MatrixType & matrix) inline
Definition at line 549 of file SimplicialCholesky.h.
References Eigen::SimplicialCholesky< _MatrixType, _UpLo >::compute().
Member Function Documentation
template<typename _MatrixType , int _UpLo = Lower> template<typename Rhs , typename Dest > void Eigen::SimplicialCholesky< _MatrixType, _UpLo >::_solve (const MatrixBase< Rhs > & b, MatrixBase< Dest > & dest) const inline
Definition at line 618 of file SimplicialCholesky.h.
References eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_diag, Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk, Eigen::SimplicialCholeskyBase< Derived >::m_info, Eigen::SimplicialCholesky< _MatrixType, _UpLo >::m_LDLT, Eigen::SimplicialCholeskyBase< Derived >::m_matrix, Eigen::SimplicialCholeskyBase< Derived >::m_P, Eigen::SimplicialCholeskyBase< Derived >::m_Pinv, Eigen::SimplicialCholeskyBase< SimplicialCholesky< _MatrixType, _UpLo > >::rows(), and Eigen::Success.
template<typename _MatrixType , int _UpLo = Lower> void Eigen::SimplicialCholesky< _MatrixType, _UpLo >::analyzePattern (const MatrixType & a) inline
Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See Also
factorize()
Definition at line 597 of file SimplicialCholesky.h.
References Eigen::SimplicialCholeskyBase< Derived >::analyzePattern(), and Eigen::SimplicialCholesky< _MatrixType, _UpLo >::m_LDLT.
template<typename _MatrixType , int _UpLo = Lower> SimplicialCholesky& Eigen::SimplicialCholesky< _MatrixType, _UpLo >::compute (const MatrixType & matrix) inline
Computes the sparse Cholesky decomposition of matrix
Definition at line 582 of file SimplicialCholesky.h.
References Eigen::SimplicialCholesky< _MatrixType, _UpLo >::m_LDLT.
Referenced by Eigen::SimplicialCholesky< _MatrixType, _UpLo >::SimplicialCholesky().
template<typename _MatrixType , int _UpLo = Lower> Scalar Eigen::SimplicialCholesky< _MatrixType, _UpLo >::determinant () const inline
Definition at line 654 of file SimplicialCholesky.h.
References abs2(), Eigen::SimplicialCholeskyBase< Derived >::m_diag, Eigen::SimplicialCholesky< _MatrixType, _UpLo >::m_LDLT, and Eigen::SimplicialCholeskyBase< Derived >::m_matrix.
template<typename _MatrixType , int _UpLo = Lower> void Eigen::SimplicialCholesky< _MatrixType, _UpLo >::factorize (const MatrixType & a) inline
Performs a numeric decomposition of matrix
The given matrix must has the same sparcity than the matrix on which the symbolic decomposition has been performed.
See Also
analyzePattern()
Definition at line 608 of file SimplicialCholesky.h.
References Eigen::SimplicialCholesky< _MatrixType, _UpLo >::m_LDLT.
template<typename _MatrixType , int _UpLo = Lower> const CholMatrixType Eigen::SimplicialCholesky< _MatrixType, _UpLo >::rawMatrix () const inline
Definition at line 576 of file SimplicialCholesky.h.
References eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk, and Eigen::SimplicialCholeskyBase< Derived >::m_matrix.
template<typename _MatrixType , int _UpLo = Lower> SimplicialCholesky& Eigen::SimplicialCholesky< _MatrixType, _UpLo >::setMode (SimplicialCholeskyMode mode) inline
Definition at line 555 of file SimplicialCholesky.h.
References Eigen::SimplicialCholesky< _MatrixType, _UpLo >::m_LDLT, Eigen::SimplicialCholeskyLDLT, and Eigen::SimplicialCholeskyLLT.
template<typename _MatrixType , int _UpLo = Lower> const VectorType Eigen::SimplicialCholesky< _MatrixType, _UpLo >::vectorD () const inline
Definition at line 572 of file SimplicialCholesky.h.
References eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_diag, and Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk.
Member Data Documentation
template<typename _MatrixType , int _UpLo = Lower> bool Eigen::SimplicialCholesky< _MatrixType, _UpLo >::m_LDLT protected
Definition at line 668 of file SimplicialCholesky.h.
Referenced by Eigen::SimplicialCholesky< _MatrixType, _UpLo >::_solve(), Eigen::SimplicialCholesky< _MatrixType, _UpLo >::analyzePattern(), Eigen::SimplicialCholesky< _MatrixType, _UpLo >::compute(), Eigen::SimplicialCholesky< _MatrixType, _UpLo >::determinant(), Eigen::SimplicialCholesky< _MatrixType, _UpLo >::factorize(), and Eigen::SimplicialCholesky< _MatrixType, _UpLo >::setMode().
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCholesky/SimplicialCholesky.h