LIA_RAL: Eigen::CholmodDecomposition< _MatrixType, _UpLo > Class Template Reference
Eigen::CholmodDecomposition< _MatrixType, _UpLo > Class Template Reference
A general Cholesky factorization and solver based on Cholmod.
#include <CholmodSupport.h>
Public Types
typedef _MatrixType MatrixType
Public Types inherited from Eigen::CholmodBase< _MatrixType, _UpLo, CholmodDecomposition< _MatrixType, _UpLo > >
enum
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType CholMatrixType
typedef MatrixType::Index Index
Public Member Functions
CholmodDecomposition ()
CholmodDecomposition (const MatrixType &matrix)
~CholmodDecomposition ()
void setMode (CholmodMode mode)
Public Member Functions inherited from Eigen::CholmodBase< _MatrixType, _UpLo, CholmodDecomposition< _MatrixType, _UpLo > >
CholmodBase ()
CholmodBase (const MatrixType &matrix)
~CholmodBase ()
Index cols () const
Index rows () const
CholmodDecomposition
< _MatrixType, _UpLo > & derived ()
const CholmodDecomposition
< _MatrixType, _UpLo > & derived () const
ComputationInfo info () const
Reports whether previous computation was successful.
CholmodDecomposition
< _MatrixType, _UpLo > & compute (const MatrixType &matrix)
const internal::solve_retval
< CholmodBase, Rhs > solve (const MatrixBase< Rhs > &b) const
const
internal::sparse_solve_retval
< CholmodBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void analyzePattern (const MatrixType &matrix)
void factorize (const MatrixType &matrix)
cholmod_common & cholmod ()
void _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
void _solve (const SparseMatrix< RhsScalar, RhsOptions, RhsIndex > &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
void dumpMemory (Stream &s)
Protected Member Functions
void init ()
Private Types
typedef CholmodBase
< _MatrixType, _UpLo,
CholmodDecomposition > Base
Additional Inherited Members
Protected Attributes inherited from Eigen::CholmodBase< _MatrixType, _UpLo, CholmodDecomposition< _MatrixType, _UpLo > >
cholmod_common m_cholmod
cholmod_factor * m_cholmodFactor
ComputationInfo m_info
bool m_isInitialized
int m_factorizationIsOk
int m_analysisIsOk
Detailed Description
template<typename _MatrixType, int _UpLo = Lower>
class Eigen::CholmodDecomposition< _MatrixType, _UpLo >
A general Cholesky factorization and solver based on Cholmod.
This class allows to solve for A.X = B sparse linear problems via a LL^T or LDL^T Cholesky factorization using the Cholmod library. The sparse matrix A must be selfajoint and positive definite. The vectors or matrices X and B can be either dense or sparse.
This variant permits to change the underlying Cholesky method at runtime. On the other hand, it does not provide access to the result of the factorization. The default is to let Cholmod automatically choose between a simplicial and supernodal factorization.
Template Parameters
_MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
_UpLo the triangular part that will be used for the computations. It can be Lower or Upper. Default is Lower.
This class supports all kind of SparseMatrix<>: row or column major; upper, lower, or both; compressed or non compressed.
See Also
TutorialSparseDirectSolvers
Definition at line 495 of file CholmodSupport.h.
Member Typedef Documentation
template<typename _MatrixType , int _UpLo = Lower> typedef CholmodBase<_MatrixType, _UpLo, CholmodDecomposition> Eigen::CholmodDecomposition< _MatrixType, _UpLo >::Base private
Definition at line 497 of file CholmodSupport.h.
template<typename _MatrixType , int _UpLo = Lower> typedef _MatrixType Eigen::CholmodDecomposition< _MatrixType, _UpLo >::MatrixType
Definition at line 502 of file CholmodSupport.h.
Constructor & Destructor Documentation
template<typename _MatrixType , int _UpLo = Lower> Eigen::CholmodDecomposition< _MatrixType, _UpLo >::CholmodDecomposition () inline
Definition at line 504 of file CholmodSupport.h.
References Eigen::CholmodDecomposition< _MatrixType, _UpLo >::init().
template<typename _MatrixType , int _UpLo = Lower> Eigen::CholmodDecomposition< _MatrixType, _UpLo >::CholmodDecomposition (const MatrixType & matrix) inline
Definition at line 506 of file CholmodSupport.h.
References Eigen::CholmodBase< _MatrixType, _UpLo, CholmodDecomposition< _MatrixType, _UpLo > >::compute(), and Eigen::CholmodDecomposition< _MatrixType, _UpLo >::init().
template<typename _MatrixType , int _UpLo = Lower> Eigen::CholmodDecomposition< _MatrixType, _UpLo >::~CholmodDecomposition () inline
Definition at line 512 of file CholmodSupport.h.
Member Function Documentation
template<typename _MatrixType , int _UpLo = Lower> void Eigen::CholmodDecomposition< _MatrixType, _UpLo >::init () inline protected
Definition at line 540 of file CholmodSupport.h.
References Eigen::CholmodBase< _MatrixType, _UpLo, CholmodDecomposition< _MatrixType, _UpLo > >::m_cholmod.
Referenced by Eigen::CholmodDecomposition< _MatrixType, _UpLo >::CholmodDecomposition().
template<typename _MatrixType , int _UpLo = Lower> void Eigen::CholmodDecomposition< _MatrixType, _UpLo >::setMode (CholmodMode mode) inline
Definition at line 514 of file CholmodSupport.h.
References Eigen::CholmodAuto, Eigen::CholmodLDLt, Eigen::CholmodSimplicialLLt, Eigen::CholmodSupernodalLLt, and Eigen::CholmodBase< _MatrixType, _UpLo, CholmodDecomposition< _MatrixType, _UpLo > >::m_cholmod.
The documentation for this class was generated from the following file:
include/Eigen/src/CholmodSupport/CholmodSupport.h