LIA_RAL: PldaDev Class Reference
PldaDev Class Reference
#include <PldaTools.h>
Public Member Functions
PldaDev ()
Constructors, load vectors from ASCII file or XList.
PldaDev (String &, Config &)
PldaDev (XList &, Config &)
virtual ~PldaDev ()
virtual String getClassName () const
void load (String &ndxFilename, Config &config)
void computeAll ()
unsigned long getVectSize ()
unsigned long getSpeakerNumber ()
unsigned long getSessionNumber ()
unsigned long getSpeakerSessionNumber (unsigned long)
ULongVector & getSpeakerSessionNumber ()
Matrix< double > getData ()
double getData (unsigned long, unsigned long)
RealVector< double > & getMean ()
void getSpeakerMean (unsigned long spk, RealVector< double > &)
void lengthNorm ()
void center (RealVector< double > &mu)
void center (Eigen::VectorXd &mu)
void centerPerSpeaker ()
void rotateLeft (Matrix< double > &M)
void computeCovMat (DoubleSquareMatrix &Sigma, DoubleSquareMatrix &W, DoubleSquareMatrix &B, Config &config)
void computeCovMatUnThreaded (DoubleSquareMatrix &Sigma, DoubleSquareMatrix &W, DoubleSquareMatrix &B)
void computeInnerCovMat (Matrix< double > &W, Config &config)
void computeInnerCovMatUnThreaded (Matrix< double > &W)
void computeCovMatEigen (Eigen::MatrixXd &Sigma, Config &config)
void computeCovMatEigenUnThreaded (Eigen::MatrixXd &Sigma)
void computeWccnChol (DoubleSquareMatrix &WCCN, Config &config)
void computeWccnCholUnThreaded (DoubleSquareMatrix &WCCN)
void computeMahalanobis (DoubleSquareMatrix &M, Config &config)
void splitPerSpeaker (unsigned long nbThread, RealVector< unsigned long > &startIndex)
void splitPerSpeaker (unsigned long nbThread, RealVector< unsigned long > &startIndex, RealVector< unsigned long > &spkStartIndex)
void computeScatterMat (DoubleSquareMatrix &SW, DoubleSquareMatrix &SB, Config &config)
void computeScatterMatUnThreaded (DoubleSquareMatrix &W, DoubleSquareMatrix &B)
void sphericalNuisanceNormalization (Config &config)
void applySphericalNuisanceNormalization (Config &config)
void trainPLDA (Config &config)
void computeLDA (Matrix< double > &L, long ldaRank, Config &config)
void computeEigenProblem (Matrix< double > &EP, Matrix< double > &eigenVect, long rank, Config &config)
void computeEigenProblem (Matrix< double > &EP, Matrix< double > &eigenVect, Matrix< double > &eigenVal, long rank, Config &config)
unsigned long getClass (unsigned long)
ULongVector & getClass ()
Private Attributes
XList _fileList
unsigned long _vectSize
unsigned long _n_speakers
unsigned long _n_sessions
RealVector< double > _mean
Mean Vectors.
Matrix< double > _speaker_means
ULongVector _class
Class definitions.
ULongVector _style
ULongVector _session_per_speaker
Matrix< double > _data
Data Matrix.
Detailed Description
This class represents a accumulator of statistics. A TVAcc contains the accumulators needed for TotalVariability estimation
Author
Anthony Larcher alarc.nosp@m.her@.nosp@m.i2r.a.nosp@m.-sta.nosp@m.r.edu.nosp@m..sg
Version
1.0
Date
2012
Definition at line 80 of file PldaTools.h.
Constructor & Destructor Documentation
PldaDev::PldaDev ()
Constructors, load vectors from ASCII file or XList.
Definition at line 94 of file PldaTools.cpp.
PldaDev::PldaDev (String & ndxFilename, Config & config)
Definition at line 97 of file PldaTools.cpp.
References verboseLevel.
PldaDev::PldaDev (XList & fileList, Config & config)
Definition at line 190 of file PldaTools.cpp.
PldaDev::~PldaDev () virtual
Definition at line 268 of file PldaTools.cpp.
Member Function Documentation
void PldaDev::applySphericalNuisanceNormalization (Config & config)
Apply normalization if the parameters already exist
Parameters
config the configuration file
Definition at line 1931 of file PldaTools.cpp.
References verboseLevel.
Referenced by IvTest().
void PldaDev::center (RealVector< double > & mu)
Substrac a vector to all vectors in the PldaDev object
Parameters
mu mean vector to remove from all vectors
Global and speaker means are re-computed
Definition at line 466 of file PldaTools.cpp.
void PldaDev::center (Eigen::VectorXd & mu)
Substrac a vector to all vectors in the PldaDev object
Parameters
mu mean vector to remove from all vectors (Eigen::VectorXd)
Global and speaker means are re-computed
Definition at line 477 of file PldaTools.cpp.
void PldaDev::centerPerSpeaker ()
Subtrac the mean vector from a speaker to all vectors from this speaker
Definition at line 488 of file PldaTools.cpp.
void PldaDev::computeAll ()
Compute global mean and mean per speaker
Definition at line 353 of file PldaTools.cpp.
void PldaDev::computeCovMat (DoubleSquareMatrix & Sigma, DoubleSquareMatrix & W, DoubleSquareMatrix & B, Config & config)
Compute three co-variance matrices
Parameters
Sigma the total covariance matrix
W the within class covariance matrix
B the between class covariance matrix
config configuration object
Data are centered within this function before computation of co-variance matrix
Definition at line 516 of file PldaTools.cpp.
Referenced by IvTest().
void PldaDev::computeCovMatEigen (Eigen::MatrixXd & Sigma, Config & config)
Threaded fonction to compute the Choleski decomposition of Within Class Covariance matrixCompute the total co-variance matrices in Eigen format Beware, the matrix is not normalized by the number of sessions
Parameters
Sigma the total covariance matrix
config configuration object
Data are centered within this function before computation of co-variance matrix
Definition at line 920 of file PldaTools.cpp.
void PldaDev::computeCovMatEigenUnThreaded (Eigen::MatrixXd & Sigma)
UnThreaded fonction to compute the total co-variance matrix
Parameters
Sigma the total covariance matrix
Definition at line 931 of file PldaTools.cpp.
References verboseLevel.
void PldaDev::computeCovMatUnThreaded (DoubleSquareMatrix & Sigma, DoubleSquareMatrix & W, DoubleSquareMatrix & B)
UnThreaded fonction to compute the three co-variance matrices
Parameters
Sigma the total covariance matrix
W the within class covariance matrix
B the between class covariance matrix
Definition at line 527 of file PldaTools.cpp.
References verboseLevel.
void PldaDev::computeEigenProblem (Matrix< double > & EP, Matrix< double > & eigenVect, long rank, Config & config)
Compute Eigen Value decomposition
Parameters
EP matrix to decompose
eigenVect matrix of eigen vectors
rank number of eigen vectors to keep
config configuration object
Definition at line 1426 of file PldaTools.cpp.
void PldaDev::computeEigenProblem (Matrix< double > & EP, Matrix< double > & eigenVect, Matrix< double > & eigenVal, long rank, Config & config)
Compute Eigen Value decomposition
Parameters
EP matrix to decompose
eigenVect matrix of eigen vectors
eigenVal diagonal matrix of eigen values
rank number of eigen vectors to keep
config configuration object
Definition at line 1490 of file PldaTools.cpp.
References Eigen::EigenSolver< _MatrixType >::eigenvalues(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), imag(), real(), and verboseLevel.
void PldaDev::computeInnerCovMat (Matrix< double > & W, Config & config)
Threaded fonction to compute the Choleski decomposition of Within Class Covariance matrixCompute the inner within class co-variance matrix
Parameters
W the within class covariance matrix
config configuration object
Data are centered within this function before computation of co-variance matrix
Definition at line 756 of file PldaTools.cpp.
void PldaDev::computeInnerCovMatUnThreaded (Matrix< double > & W)
UnThreaded fonction to compute the inner within class co-variance matrix
Parameters
W the within class covariance matrix
Definition at line 767 of file PldaTools.cpp.
References verboseLevel.
void PldaDev::computeLDA (Matrix< double > & L, long ldaRank, Config & config)
Compute Linear Discriminant Analysis matrix
Parameters
L LDA matrix computed on the development set
ldaRank rank of the LDA matrix
config configuration object
Definition at line 1381 of file PldaTools.cpp.
References verboseLevel.
Referenced by IvNorm(), and IvTest().
void PldaDev::computeMahalanobis (DoubleSquareMatrix & M, Config & config)
Compute the Mahalanobis matrix for scoring (i.e. the inverse of the within-class co-variance matrix)
Parameters
M Mahalanobis matrix computed on the development set
config configuration object
Definition at line 1366 of file PldaTools.cpp.
Referenced by IvTest().
void PldaDev::computeScatterMat (DoubleSquareMatrix & SW, DoubleSquareMatrix & SB, Config & config)
Compute the scatter matrices
Parameters
SW the within class covariance matrix
SB the between class covariance matrix config configuration object
Data are centered within this function before computation of co-variance matrix
Definition at line 1599 of file PldaTools.cpp.
void PldaDev::computeScatterMatUnThreaded (DoubleSquareMatrix & W, DoubleSquareMatrix & B)
UnThreaded fonction to compute the scatter matrices
Parameters
SW the within class covariance matrix
SB the between class covariance matrix
threads number of threads to run
Definition at line 1610 of file PldaTools.cpp.
References verboseLevel.
void PldaDev::computeWccnChol (DoubleSquareMatrix & WCCN, Config & config)
Compute the Choleski decomposition of Within Class Covariance matrix
Parameters
WCCN Choleski decomposition of the WCCN matrix
Definition at line 1113 of file PldaTools.cpp.
Referenced by IvTest().
void PldaDev::computeWccnCholUnThreaded (DoubleSquareMatrix & WCCN)
Threaded fonction to compute the Choleski decomposition of Within Class Covariance matrixUnthreaded fonction to compute the Choleski decomposition of Within Class Covariance matrix
Parameters
config config filename
Definition at line 1124 of file PldaTools.cpp.
References verboseLevel.
unsigned long PldaDev::getClass (unsigned long s)
Definition at line 1546 of file PldaTools.cpp.
ULongVector & PldaDev::getClass ()
Definition at line 1551 of file PldaTools.cpp.
String PldaDev::getClassName () const virtual
Definition at line 271 of file PldaTools.cpp.
Matrix< double > PldaDev::getData ()
Get the matrix of vectors
Definition at line 414 of file PldaTools.cpp.
double PldaDev::getData (unsigned long i, unsigned long j)
Definition at line 419 of file PldaTools.cpp.
RealVector< double > & PldaDev::getMean ()
Return the global mean of development data
Definition at line 424 of file PldaTools.cpp.
unsigned long PldaDev::getSessionNumber ()
Get the total number of sessions
Definition at line 399 of file PldaTools.cpp.
void PldaDev::getSpeakerMean (unsigned long spk, RealVector< double > & spkMean)
Return the mean of a specific speaker
Parameters
spk the index of the speaker
Definition at line 429 of file PldaTools.cpp.
unsigned long PldaDev::getSpeakerNumber ()
Get the number of speakers
Definition at line 395 of file PldaTools.cpp.
unsigned long PldaDev::getSpeakerSessionNumber (unsigned long spkIdx)
Get the total number of sessions for a give speaker
Definition at line 404 of file PldaTools.cpp.
ULongVector & PldaDev::getSpeakerSessionNumber ()
Get the vector of the total number of sessions per speaker
Definition at line 409 of file PldaTools.cpp.
unsigned long PldaDev::getVectSize ()
Get the size of data vectors
Definition at line 390 of file PldaTools.cpp.
Referenced by PldaModel::initTrain().
void PldaDev::lengthNorm ()
Normalize the length of all vectors to one (Euclidian Norm)
Global and speaker means are re-computed
Definition at line 436 of file PldaTools.cpp.
References sqrt(), and verboseLevel.
void PldaDev::load (String & ndxFilename, Config & config)
Load data and compute all
Parameters
ndxFilename the index file to load
config the config
Definition at line 274 of file PldaTools.cpp.
void PldaDev::rotateLeft (Matrix< double > & M)
Rotate the development vectors by multiplying on the left by M
Parameters
M the matrix to multiply
Definition at line 498 of file PldaTools.cpp.
Referenced by IvTest().
void PldaDev::sphericalNuisanceNormalization (Config & config)
Threaded fonction to compute the Choleski decomposition of Within Class Covariance matrixEstimate normalization parameters or Spherical Nuisance Normalization
Parameters
config the configuration file
Definition at line 1822 of file PldaTools.cpp.
References sqrt(), and verboseLevel.
Referenced by IvNorm(), and IvTest().
void PldaDev::splitPerSpeaker (unsigned long nbThread, RealVector< unsigned long > & startIndex)
Split the list of speaker in a given number of sublists and return the index of the first session of each sub-list
Parameters
nbThread number of sub-list to split
startIndex index of the first session of each sub-list
Definition at line 1556 of file PldaTools.cpp.
void PldaDev::splitPerSpeaker (unsigned long nbThread, RealVector< unsigned long > & startIndex, RealVector< unsigned long > & spkStartIndex)
Split the list of speaker in a given number of sublists and return the index of the first session of each sub-list
Parameters
nbThread number of sub-list to split
startIndex index of the first session of each sub-list
spkStartIndex index of the first speaker of each sub-list
Definition at line 1576 of file PldaTools.cpp.
void PldaDev::trainPLDA (Config & config)
Estimate parameters for Probabilistic Linear Discriminant Analysis model
Parameters
config configuration object
Member Data Documentation
ULongVector PldaDev::_class private
Class definitions.
Definition at line 94 of file PldaTools.h.
Matrix<double> PldaDev::_data private
Data Matrix.
Definition at line 99 of file PldaTools.h.
XList PldaDev::_fileList private
Definition at line 84 of file PldaTools.h.
RealVector<double> PldaDev::_mean private
Mean Vectors.
Definition at line 90 of file PldaTools.h.
unsigned long PldaDev::_n_sessions private
Definition at line 87 of file PldaTools.h.
unsigned long PldaDev::_n_speakers private
Definition at line 86 of file PldaTools.h.
ULongVector PldaDev::_session_per_speaker private
Definition at line 96 of file PldaTools.h.
Matrix<double> PldaDev::_speaker_means private
Definition at line 91 of file PldaTools.h.
ULongVector PldaDev::_style private
Definition at line 95 of file PldaTools.h.
unsigned long PldaDev::_vectSize private
Definition at line 85 of file PldaTools.h.
The documentation for this class was generated from the following files:
LIA_SpkTools/include/PldaTools.h
LIA_SpkTools/src/PldaTools.cpp