LIA_RAL: Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType > Class Template Reference
Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType > Class Template Reference
Computes eigenvalues and eigenvectors of the generalized selfadjoint eigen problem.
#include <GeneralizedSelfAdjointEigenSolver.h>
Public Types
typedef Base::Index Index
typedef _MatrixType MatrixType
Public Types inherited from Eigen::SelfAdjointEigenSolver< _MatrixType >
enum { Size = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type _MatrixType.
typedef MatrixType::Index Index
typedef NumTraits< Scalar >::Real RealScalar
Real scalar type for _MatrixType.
typedef
internal::plain_col_type
< MatrixType, RealScalar >
::type RealVectorType
Type for vector of eigenvalues as returned by eigenvalues().
typedef Tridiagonalization
< MatrixType > TridiagonalizationType
Public Member Functions
GeneralizedSelfAdjointEigenSolver ()
Default constructor for fixed-size matrices.
GeneralizedSelfAdjointEigenSolver (Index size)
Constructor, pre-allocates memory for dynamic-size matrices.
GeneralizedSelfAdjointEigenSolver (const MatrixType &matA, const MatrixType &matB, int options=ComputeEigenvectors|Ax_lBx)
Constructor; computes generalized eigendecomposition of given matrix pencil.
GeneralizedSelfAdjointEigenSolver & compute (const MatrixType &matA, const MatrixType &matB, int options=ComputeEigenvectors|Ax_lBx)
Computes generalized eigendecomposition of given matrix pencil.
Public Member Functions inherited from Eigen::SelfAdjointEigenSolver< _MatrixType >
SelfAdjointEigenSolver ()
Default constructor for fixed-size matrices.
SelfAdjointEigenSolver (Index size)
Constructor, pre-allocates memory for dynamic-size matrices.
SelfAdjointEigenSolver (const MatrixType &matrix, int options=ComputeEigenvectors)
Constructor; computes eigendecomposition of given matrix.
SelfAdjointEigenSolver & compute (const MatrixType &matrix, int options=ComputeEigenvectors)
Computes eigendecomposition of given matrix.
SelfAdjointEigenSolver & computeDirect (const MatrixType &matrix, int options=ComputeEigenvectors)
Computes eigendecomposition of given matrix using a direct algorithm.
const MatrixType & eigenvectors () const
Returns the eigenvectors of given matrix.
const RealVectorType & eigenvalues () const
Returns the eigenvalues of given matrix.
MatrixType operatorSqrt () const
Computes the positive-definite square root of the matrix.
MatrixType operatorInverseSqrt () const
Computes the inverse square root of the matrix.
ComputationInfo info () const
Reports whether previous computation was successful.
Private Types
typedef SelfAdjointEigenSolver
< _MatrixType > Base
Additional Inherited Members
Static Public Attributes inherited from Eigen::SelfAdjointEigenSolver< _MatrixType >
static const int m_maxIterations = 30
Maximum number of iterations.
Protected Attributes inherited from Eigen::SelfAdjointEigenSolver< _MatrixType >
MatrixType m_eivec
RealVectorType m_eivalues
TridiagonalizationType::SubDiagonalType m_subdiag
ComputationInfo m_info
bool m_isInitialized
bool m_eigenvectorsOk
Detailed Description
template<typename _MatrixType>
class Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >
Computes eigenvalues and eigenvectors of the generalized selfadjoint eigen problem.
Template Parameters
_MatrixType the type of the matrix of which we are computing the eigendecomposition; this is expected to be an instantiation of the Matrix class template.
This class solves the generalized eigenvalue problem . In this case, the matrix should be selfadjoint and the matrix should be positive definite.
Only the lower triangular part of the input matrix is referenced.
Call the function compute() to compute the eigenvalues and eigenvectors of a given matrix. Alternatively, you can use the GeneralizedSelfAdjointEigenSolver(const MatrixType&, const MatrixType&, int) constructor which computes the eigenvalues and eigenvectors at construction time. Once the eigenvalue and eigenvectors are computed, they can be retrieved with the eigenvalues() and eigenvectors() functions.
The documentation for GeneralizedSelfAdjointEigenSolver(const MatrixType&, const MatrixType&, int) contains an example of the typical use of this class.
See Also
class SelfAdjointEigenSolver, class EigenSolver, class ComplexEigenSolver
Definition at line 48 of file GeneralizedSelfAdjointEigenSolver.h.
Member Typedef Documentation
template<typename _MatrixType > typedef SelfAdjointEigenSolver<_MatrixType> Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::Base private
Definition at line 50 of file GeneralizedSelfAdjointEigenSolver.h.
template<typename _MatrixType > typedef Base::Index Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::Index
Definition at line 53 of file GeneralizedSelfAdjointEigenSolver.h.
template<typename _MatrixType > typedef _MatrixType Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::MatrixType
Definition at line 54 of file GeneralizedSelfAdjointEigenSolver.h.
Constructor & Destructor Documentation
template<typename _MatrixType > Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver () inline
Default constructor for fixed-size matrices.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). This constructor can only be used if _MatrixType is a fixed-size matrix; use GeneralizedSelfAdjointEigenSolver(Index) for dynamic-size matrices.
Definition at line 63 of file GeneralizedSelfAdjointEigenSolver.h.
template<typename _MatrixType > Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver (Index size) inline
Constructor, pre-allocates memory for dynamic-size matrices.
Parameters
[in] size Positive integer, size of the matrix whose eigenvalues and eigenvectors will be computed.
This constructor is useful for dynamic-size matrices, when the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See Also
compute() for an example
Definition at line 77 of file GeneralizedSelfAdjointEigenSolver.h.
template<typename _MatrixType > Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver (const MatrixType & matA, const MatrixType & matB, int options = ComputeEigenvectors|Ax_lBx) inline
Constructor; computes generalized eigendecomposition of given matrix pencil.
Parameters
[in] matA Selfadjoint matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] matB Positive-definite matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] options A or-ed set of flags {ComputeEigenvectors,EigenvaluesOnly} | {Ax_lBx,ABx_lx,BAx_lx}. Default is ComputeEigenvectors|Ax_lBx.
This constructor calls compute(const MatrixType&, const MatrixType&, int) to compute the eigenvalues and (if requested) the eigenvectors of the generalized eigenproblem with matA the selfadjoint matrix and matB the positive definite matrix . Each eigenvector satisfies the property . The eigenvectors are computed if options contains ComputeEigenvectors.
In addition, the two following variants can be solved via options:
ABx_lx:
BAx_lx:
Example:
Output:
See Also
compute(const MatrixType&, const MatrixType&, int)
Definition at line 107 of file GeneralizedSelfAdjointEigenSolver.h.
References Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::compute().
Member Function Documentation
template<typename MatrixType > GeneralizedSelfAdjointEigenSolver< MatrixType > & Eigen::GeneralizedSelfAdjointEigenSolver< MatrixType >::compute (const MatrixType & matA, const MatrixType & matB, int options = ComputeEigenvectors|Ax_lBx)
Computes generalized eigendecomposition of given matrix pencil.
Parameters
[in] matA Selfadjoint matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] matB Positive-definite matrix in matrix pencil. Only the lower triangular part of the matrix is referenced.
[in] options A or-ed set of flags {ComputeEigenvectors,EigenvaluesOnly} | {Ax_lBx,ABx_lx,BAx_lx}. Default is ComputeEigenvectors|Ax_lBx.
Returns
Reference to *this
Accoring to options, this function computes eigenvalues and (if requested) the eigenvectors of one of the following three generalized eigenproblems:
Ax_lBx:
ABx_lx:
BAx_lx: with matA the selfadjoint matrix and matB the positive definite matrix . In addition, each eigenvector satisfies the property .
The eigenvalues() function can be used to retrieve the eigenvalues. If options contains ComputeEigenvectors, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The implementation uses LLT to compute the Cholesky decomposition and computes the classical eigendecomposition of the selfadjoint matrix if options contains Ax_lBx and of otherwise. This solves the generalized eigenproblem, because any solution of the generalized eigenproblem corresponds to a solution of the eigenproblem for . Similar statements can be made for the two other variants.
Example:
Output:
See Also
GeneralizedSelfAdjointEigenSolver(const MatrixType&, const MatrixType&, int)
Definition at line 164 of file GeneralizedSelfAdjointEigenSolver.h.
References Eigen::ABx_lx, Eigen::Ax_lBx, Eigen::BAx_lx, Eigen::ComputeEigenvectors, eigen_assert, Eigen::EigenvaluesOnly, Eigen::EigVecMask, Eigen::GenEigMask, Eigen::LLT< _MatrixType, _UpLo >::matrixL(), and Eigen::LLT< _MatrixType, _UpLo >::matrixU().
Referenced by Eigen::GeneralizedSelfAdjointEigenSolver< _MatrixType >::GeneralizedSelfAdjointEigenSolver().
The documentation for this class was generated from the following file:
include/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h