LIA_RAL: TVAcc Class Reference
TVAcc Class Reference
#include <AccumulateTVStat.h>
Public Member Functions
TVAcc (String &, Config &)
TVAcc (XList &, Config &)
TVAcc (Config &)
virtual ~TVAcc ()
virtual String getClassName () const
void computeAndAccumulateTVStat (Config &config)
void computeAndAccumulateTVStatUnThreaded (Config &config)
void computeAndAccumulateTVStat (FeatureServer &fs, Config &config)
void computeAndAccumulateTVStat (SegCluster &sc, FeatureServer &fs, Config &config)
void resetAcc ()
void resetTmpAcc ()
void loadT (const String &file, Config &config)
void loadT (Matrix< double > &mat, Config &config)
void loadMeanEstimate (DoubleVector &meanEstimate)
void loadN (Config &)
void loadF_X (Config &)
void initT (Config &)
void saveT (const String &file, Config &config)
void estimateTETt (Config &config)
void estimateTETtUnThreaded ()
void getTW (DoubleVector &vy, String &file)
void getTW (DoubleVector &file, unsigned long spk)
void getMplusTW (DoubleVector &MplusVY, String &file)
void getMplusTW (DoubleVector &MplusVY, unsigned long spk)
void estimateAandC (Config &config)
void estimateAandCUnthreaded (Config &config)
void estimateW (Config &)
void estimateWUnThreaded (Config &)
void estimateWUbmWeight (DoubleSquareMatrix &W, Config &)
void estimateWUbmWeightUnThreaded (DoubleSquareMatrix &W, Config &)
void estimateWEigenDecomposition (Matrix< double > D, Matrix< double > Q, Config &config)
void estimateWEigenDecompositionUnThreaded (Matrix< double > D, Matrix< double > Q, Config &config)
void updateTestimate ()
XList & getXList ()
unsigned long getNSpeakers ()
unsigned long getNDistrib ()
unsigned long getVectSize ()
unsigned long getSvSize ()
unsigned long getRankT ()
DoubleVector & getUbmMeans ()
DoubleVector & getUbmInvVar ()
Matrix< double > getT ()
Matrix< double > getW ()
void saveW (String yFilename, Config &)
void storeAccs ()
void restoreAccs ()
void substractM (Config &config)
void substractMUnThreaded ()
void normStatistics (Config &config)
void normStatisticsUnThreaded ()
void substractMplusTW (Config &)
void substractMplusTWUnThreaded ()
void getSpeakerModel (MixtureGD &mixture, String &file)
void orthonormalizeT ()
void normTMatrix ()
void saveAccs (Config &config)
Save Accumulators on disk.
double getLLK (SegCluster &selectedSegments, MixtureGD &model, FeatureServer &fs, Config &config)
void verifyEMLK (Config &config)
Matrix< double > & getN ()
Matrix< double > & getF ()
DoubleSquareMatrix & getTETt (unsigned long idx)
void minDivergence ()
void saveWbyFile (Config &config)
void getWeightedCov (DoubleSquareMatrix &W, DoubleVector &weight, Config &config)
void getWeightedCovUnThreaded (DoubleSquareMatrix &W, DoubleVector &weight)
void computeEigenProblem (Matrix< double > &EP, Matrix< double > &eigenVect, long rank, Config &config)
void computeEigenProblem (Matrix< double > &EP, Matrix< double > &eigenVect, Matrix< double > &eigenVal, long rank, Config &config)
void approximateTcTc (Matrix< double > &D, Matrix< double > &Q, Config &config)
void approximateTcTcUnThreaded (Matrix< double > &D, Matrix< double > &Q)
Public Attributes
TVTranslate _ndxTable
Association between filename and indexes of speaker and sessions.
Private Member Functions
void _init (XList &list, Config &config)
void _init (Config &config)
Private Attributes
MixtureServer _ms
StatServer _ss
XList _fileList
unsigned long _vectSize
unsigned long _n_distrib
unsigned long _svSize
unsigned long _rankT
unsigned long _n_speakers
unsigned long _n_sessions
RealVector< double > _ubm_means
UBM SVs.
RealVector< double > _ubm_invvar
RealVector< double > _meanW
Matrix< double > _statN
Accumulators.
Matrix< double > _statF
Matrix< double > _T
TotalVariability Objects.
Matrix< double > _W
RefVector< DoubleSquareMatrix > _TETt
Accumulators for VSigmaVT.
Matrix< double > _A
Accumulators.
Matrix< double > _Cmx
DoubleSquareMatrix _R
Minimum Divergence Accumulators.
DoubleVector _r
Detailed Description
This class represents a accumulator of statistics. A TVAcc contains the accumulators needed for TotalVariability estimation
Author
Anthony Larcher alarc.nosp@m.her@.nosp@m.i2r.a.nosp@m.-sta.nosp@m.r.edu.nosp@m..sg
Version
1.0
Date
2012
Definition at line 201 of file AccumulateTVStat.h.
Constructor & Destructor Documentation
TVAcc::TVAcc (String & featFilename, Config & config)
Definition at line 91 of file AccumulateTVStat.cpp.
References _init(), and verboseLevel.
TVAcc::TVAcc (XList & ndx, Config & config)
Definition at line 109 of file AccumulateTVStat.cpp.
References _init().
TVAcc::TVAcc (Config & config)
Definition at line 115 of file AccumulateTVStat.cpp.
References _init().
TVAcc::~TVAcc () virtual
Definition at line 121 of file AccumulateTVStat.cpp.
References _TETt.
Member Function Documentation
void TVAcc::_init (XList & list, Config & config) private
main function to initialise the accumulator
Parameters
list the XList containing speakers and sessions filenames
config config filename
Convert the NDX file
Load the UBM
Read NDX file
Create UBM supervectors
Create and initialise statistics acumulators
Create the accumulators for vEvT computation
Create accumulators to compute the TotalVariability matrix
Definition at line 129 of file AccumulateTVStat.cpp.
References _A, _Cmx, _fileList, _meanW, _ms, _n_distrib, _n_sessions, _n_speakers, _ndxTable, _R, _r, _rankT, _statF, _statN, _svSize, _T, _TETt, _ubm_invvar, _ubm_means, _vectSize, and _W.
Referenced by TVAcc().
void TVAcc::_init (Config & config) private
function to initialise the accumulator without loading data
Parameters
list the XList containing speakers and sessions filenames
config config filename
Load the UBM
Read NDX file
Create UBM supervectors
Create and initialise statistics acumulators
Create the accumulators for vEvT computation
Create accumulators to compute the TotalVariability matrix
Definition at line 201 of file AccumulateTVStat.cpp.
References _A, _Cmx, _meanW, _ms, _n_distrib, _n_sessions, _n_speakers, _R, _r, _rankT, _statF, _statN, _svSize, _T, _TETt, _ubm_invvar, _ubm_means, _vectSize, and _W.
void TVAcc::approximateTcTc (Matrix< double > & D, Matrix< double > & Q, Config & config)
Definition at line 3106 of file AccumulateTVStat.cpp.
References approximateTcTcUnThreaded().
Referenced by IvExtractorEigenDecomposition(), and TotalVariability().
void TVAcc::approximateTcTcUnThreaded (Matrix< double > & D, Matrix< double > & Q)
Definition at line 3116 of file AccumulateTVStat.cpp.
References _n_distrib, _rankT, _T, and _vectSize.
Referenced by approximateTcTc().
void TVAcc::computeAndAccumulateTVStat (Config & config)
main fonction to accumulate statistics
Parameters
config config filename
Definition at line 268 of file AccumulateTVStat.cpp.
References computeAndAccumulateTVStatUnThreaded().
Referenced by computeAndAccumulateTVStat(), ComputeTVStats(), IvExtractor(), IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::computeAndAccumulateTVStat (FeatureServer & fs, Config & config)
Threaded fonction to accumulate statistics
Parameters
config config filenameFonction to accumulate statistics
fs featureserver containing the required data
config config filename
Definition at line 553 of file AccumulateTVStat.cpp.
References _fileList, computeAndAccumulateTVStat(), initializeClusters(), and verifyClusterFile().
void TVAcc::computeAndAccumulateTVStat (SegCluster & sc, FeatureServer & fs, Config & config)
Fonction to accumulate statistics
Parameters
sc SegCluster containing the selected segments
fs featureserver containing the required data
config config filename
Fast access to vector and matrices array
Compute Occupations and Statistics
Idx of the first frame of the current file in the feature server
Definition at line 564 of file AccumulateTVStat.cpp.
References _fileList, _ms, _n_distrib, _ss, _statF, _statN, _svSize, _vectSize, TVTranslate::locNb(), TVTranslate::sessionNb(), and verboseLevel.
void TVAcc::computeAndAccumulateTVStatUnThreaded (Config & config)
Unthreaded fonction to accumulate statistics
Parameters
config config filename
Create and initialise the feature server
Create and initialise feature clusters
Fast access to vector and matrices array
Idx of the first frame of the current file in the feature server
Definition at line 281 of file AccumulateTVStat.cpp.
References _fileList, _ms, _n_distrib, _ss, _statF, _statN, _svSize, _vectSize, initializeClusters(), TVTranslate::locIndices(), TVTranslate::locNb(), TVTranslate::sessIndices(), TVTranslate::sessionNb(), verboseLevel, and verifyClusterFile().
Referenced by computeAndAccumulateTVStat().
void TVAcc::computeEigenProblem (Matrix< double > & EP, Matrix< double > & eigenVect, long rank, Config & config)
Definition at line 2988 of file AccumulateTVStat.cpp.
Referenced by IvExtractorEigenDecomposition(), and TotalVariability().
void TVAcc::computeEigenProblem (Matrix< double > & EP, Matrix< double > & eigenVect, Matrix< double > & eigenVal, long rank, Config & config)
Definition at line 3056 of file AccumulateTVStat.cpp.
References Eigen::EigenSolver< _MatrixType >::eigenvalues(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), imag(), real(), and verboseLevel.
void TVAcc::estimateAandC (Config & config)
Compute the inverse of L matrices for TotalVariability estimation, estimate TotalVariability matrix and Y components
Parameters
config config filename
Definition at line 1691 of file AccumulateTVStat.cpp.
References estimateAandCUnthreaded().
Referenced by TotalVariability().
void TVAcc::estimateAandCUnthreaded (Config & config)
Compute the inverse of L matrices for TotalVariability estimation, estimate TotalVariability matrix and Y components without threads
Parameters
config config filename
Definition at line 1702 of file AccumulateTVStat.cpp.
References _A, _Cmx, _meanW, _n_distrib, _n_speakers, _R, _r, _rankT, _statF, _statN, _svSize, _T, _TETt, _ubm_invvar, _W, verboseLevel, and Eigen::internal::y.
Referenced by estimateAandC().
void TVAcc::estimateTETt (Config & config)
Compute the VEVt matrices
Parameters
config config filename
Definition at line 766 of file AccumulateTVStat.cpp.
References estimateTETtUnThreaded().
Referenced by IvExtractor(), and TotalVariability().
void TVAcc::estimateTETtUnThreaded ()
Compute the VEVt matrices without threads
Compute _TETt matrices
Definition at line 777 of file AccumulateTVStat.cpp.
References _n_distrib, _rankT, _T, _TETt, _ubm_invvar, _vectSize, and verboseLevel.
Referenced by estimateTETt().
void TVAcc::estimateW (Config & config)
Estimate W components
Parameters
config config filename
Definition at line 2103 of file AccumulateTVStat.cpp.
References estimateWUnThreaded().
Referenced by IvExtractor().
void TVAcc::estimateWEigenDecomposition (Matrix< double > D, Matrix< double > Q, Config & config)
Definition at line 2556 of file AccumulateTVStat.cpp.
References estimateWEigenDecompositionUnThreaded().
Referenced by IvExtractorEigenDecomposition().
void TVAcc::estimateWEigenDecompositionUnThreaded (Matrix< double > D, Matrix< double > Q, Config & config)
Definition at line 2566 of file AccumulateTVStat.cpp.
References _n_distrib, _n_speakers, _rankT, _statF, _statN, _svSize, _T, _ubm_invvar, _W, and verboseLevel.
Referenced by estimateWEigenDecomposition().
void TVAcc::estimateWUbmWeight (DoubleSquareMatrix & W, Config & config)
Approximate W components by using UBM weight
Parameters
config config filename
Definition at line 2337 of file AccumulateTVStat.cpp.
References estimateWUbmWeightUnThreaded().
Referenced by IvExtractorUbmWeigth().
void TVAcc::estimateWUbmWeightUnThreaded (DoubleSquareMatrix & W, Config & config)
Approximate W components without threads
Definition at line 2348 of file AccumulateTVStat.cpp.
References _n_distrib, _n_speakers, _rankT, _statF, _statN, _svSize, _T, _W, verboseLevel, and Eigen::internal::y.
Referenced by estimateWUbmWeight().
void TVAcc::estimateWUnThreaded (Config & config)
Estimate W components without threads
Definition at line 2114 of file AccumulateTVStat.cpp.
References _n_distrib, _n_speakers, _rankT, _statF, _statN, _svSize, _T, _TETt, _ubm_invvar, _W, verboseLevel, and Eigen::internal::y.
Referenced by estimateW().
String TVAcc::getClassName () const virtual
Definition at line 126 of file AccumulateTVStat.cpp.
Matrix< double > & TVAcc::getF ()
Return the First order speaker statistic Matrix
Definition at line 1068 of file AccumulateTVStat.cpp.
References _statF.
double TVAcc::getLLK (SegCluster & selectedSegments, MixtureGD & model, FeatureServer & fs, Config & config)
Compute LLK
Parameters
selectedSegments segment cluster to process
model GMM model
config config filename
Definition at line 1627 of file AccumulateTVStat.cpp.
References _ss, and verboseLevel.
Referenced by verifyEMLK().
void TVAcc::getMplusTW (DoubleVector & MplusVY, String & file)
Get the MplusVY supervector for a given featurefile
Parameters
MplusVY DoubleVector to fill with the supervector
file name of the feature file
Definition at line 953 of file AccumulateTVStat.cpp.
References _svSize, _ubm_means, and getTW().
Referenced by getSpeakerModel(), and substractMplusTWUnThreaded().
void TVAcc::getMplusTW (DoubleVector & MplusVY, unsigned long spk)
Get the MplusVY supervector for a given speaker
Parameters
MplusVY DoubleVector to fill with the supervector
spk index of the speaker
Definition at line 964 of file AccumulateTVStat.cpp.
References _svSize, _ubm_means, and getTW().
Matrix< double > & TVAcc::getN ()
Return the Null order speaker statistic Matrix
Definition at line 1063 of file AccumulateTVStat.cpp.
References _statN.
unsigned long TVAcc::getNDistrib ()
Return the number of distribution of the Universal Backgroud Model
Definition at line 1018 of file AccumulateTVStat.cpp.
References _n_distrib.
Referenced by IvExtractorEigenDecomposition(), and TotalVariability().
unsigned long TVAcc::getNSpeakers ()
Return the number of speakers of the TVAcc
Definition at line 1013 of file AccumulateTVStat.cpp.
References _n_speakers.
unsigned long TVAcc::getRankT ()
Return the rank of the Total Variability Matrix
Definition at line 1033 of file AccumulateTVStat.cpp.
Referenced by IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::getSpeakerModel (MixtureGD & mixture, String & file)
Return the speaker model (M + TW) for a given feature file
Parameters
mixture mixture to fill with the speaker model
file name of the feature file
Definition at line 1533 of file AccumulateTVStat.cpp.
References _svSize, getMplusTW(), and svToModel().
Referenced by verifyEMLK().
unsigned long TVAcc::getSvSize ()
Return the dimension of the supervectors
Definition at line 1028 of file AccumulateTVStat.cpp.
Matrix< double > TVAcc::getT ()
Return the Total Variability Matrix
Definition at line 1048 of file AccumulateTVStat.cpp.
References _T.
DoubleSquareMatrix & TVAcc::getTETt (unsigned long idx)
Return a temporary DoubleSquareMatrix TETt
Parameters
idx index of the matrix to return
Definition at line 1073 of file AccumulateTVStat.cpp.
References _TETt.
void TVAcc::getTW (DoubleVector & vy, String & file)
Get the VY supervector for a feature file
Parameters
vy DoubleVector to fill with the supervector
name of the feature file
Compute VY for the speaker corresponding to the given file given file
Definition at line 926 of file AccumulateTVStat.cpp.
References _ndxTable, _rankT, _svSize, _T, _W, TVTranslate::locNb(), and Eigen::internal::y.
Referenced by getMplusTW().
void TVAcc::getTW (DoubleVector & file, unsigned long spk)
Get the supervector for a given speaker
Parameters
vy DoubleVector to fill with the supervector
spk index of the speaker
Compute VY for speaker spk
Definition at line 940 of file AccumulateTVStat.cpp.
References _rankT, _svSize, _T, _W, and Eigen::internal::y.
DoubleVector & TVAcc::getUbmInvVar ()
Return the Supervector of variances of the UBM
Definition at line 1043 of file AccumulateTVStat.cpp.
References _ubm_invvar.
DoubleVector & TVAcc::getUbmMeans ()
Return the Supervector of means of the UBM
Definition at line 1038 of file AccumulateTVStat.cpp.
References _ubm_means.
Referenced by IvExtractor(), IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
unsigned long TVAcc::getVectSize ()
Return the dimension of feature vectors
Definition at line 1023 of file AccumulateTVStat.cpp.
Matrix< double > TVAcc::getW ()
Return the W matrix
Definition at line 1053 of file AccumulateTVStat.cpp.
References _W.
void TVAcc::getWeightedCov (DoubleSquareMatrix & W, DoubleVector & weight, Config & config)
Compute Weighted covariance matrix from the TotalVariability matrix
Parameters
W the output weighted covariance matrix
Definition at line 2826 of file AccumulateTVStat.cpp.
References getWeightedCovUnThreaded().
Referenced by IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::getWeightedCovUnThreaded (DoubleSquareMatrix & W, DoubleVector & weight)
Compute Weighted covariance matrix from the TotalVariability matrix without multi-threading
Parameters
W the output weighted covariance matrix
Definition at line 2837 of file AccumulateTVStat.cpp.
References _n_distrib, _rankT, _T, _vectSize, and verboseLevel.
Referenced by getWeightedCov().
XList & TVAcc::getXList ()
Return the XList
Definition at line 1008 of file AccumulateTVStat.cpp.
References _fileList.
void TVAcc::initT (Config & config)
Initialise the Total Variability matrix by a Box-Muller random process
random initialisation of the TotalVariability Matrix
Definition at line 701 of file AccumulateTVStat.cpp.
References _rankT, _svSize, _T, _ubm_invvar, boxMullerGenerator(), boxMullerGeneratorInit(), and verboseLevel.
Referenced by TotalVariability().
void TVAcc::loadF_X (Config & config)
Load the first order statistics matrix of speakers
Parameters
config config filename
Definition at line 690 of file AccumulateTVStat.cpp.
References _fileList, _statF, and _svSize.
Referenced by IvExtractor(), IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::loadMeanEstimate (DoubleVector & meanEstimate)
Load the Mean Estimate from Minimum Divergence
Parameters
meanEstimate DoubleVector object
Definition at line 671 of file AccumulateTVStat.cpp.
References _svSize, and _ubm_means.
Referenced by IvExtractor(), IvExtractorEigenDecomposition(), and IvExtractorUbmWeigth().
void TVAcc::loadN (Config & config)
Load the null order statistics matrix of speakers
Parameters
config config filename
Definition at line 679 of file AccumulateTVStat.cpp.
References _fileList, _n_distrib, and _statN.
Referenced by IvExtractor(), IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::loadT (const String & file, Config & config)
Load the Total Variability Matrix from a file
Parameters
file name of the matrix file
config config filename
load an TotalVariability Matrix
Definition at line 632 of file AccumulateTVStat.cpp.
References _rankT, and _T.
Referenced by IvExtractor(), IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::loadT (Matrix< double > & mat, Config & config)
Load the Total Variability Matrix from an existing matrix
Parameters
mat matrix object
Definition at line 651 of file AccumulateTVStat.cpp.
References _rankT, and _T.
void TVAcc::minDivergence ()
Update the Matrix according to the Minimum Divergence Criteria
Definition at line 2056 of file AccumulateTVStat.cpp.
References _meanW, _n_sessions, _R, _r, _rankT, _svSize, _T, _ubm_means, and verboseLevel.
Referenced by TotalVariability().
void TVAcc::normStatistics (Config & config)
Subtract the mean component M from the statistics and whiten
Parameters
config config filename
Definition at line 1215 of file AccumulateTVStat.cpp.
References normStatisticsUnThreaded().
Referenced by IvExtractorEigenDecomposition(), and IvExtractorUbmWeigth().
void TVAcc::normStatisticsUnThreaded ()
Subtract the mean component M from the statistics and whiten without threads
Definition at line 1225 of file AccumulateTVStat.cpp.
References _n_distrib, _n_speakers, _statF, _statN, _ubm_invvar, _ubm_means, _vectSize, sqrt(), and verboseLevel.
Referenced by normStatistics().
void TVAcc::normTMatrix ()
Definition at line 1600 of file AccumulateTVStat.cpp.
References _rankT, _svSize, _T, _ubm_invvar, sqrt(), and verboseLevel.
Referenced by IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::orthonormalizeT ()
Orthonormalize the Total Variability matrix
Definition at line 1548 of file AccumulateTVStat.cpp.
References _rankT, _svSize, _T, and sqrt().
Referenced by TotalVariability().
void TVAcc::resetAcc ()
Function to reset the sufficient statistics accumulators
Definition at line 613 of file AccumulateTVStat.cpp.
References _statF, _statN, and verboseLevel.
void TVAcc::resetTmpAcc ()
Reset the tempporary variables used for matrix estimations
Reinitialise accumulators for L matrices computation
Definition at line 620 of file AccumulateTVStat.cpp.
References _A, _Cmx, _n_distrib, and _TETt.
Referenced by TotalVariability().
void TVAcc::restoreAccs ()
Restore the sufficient statistics accumulators
void TVAcc::saveAccs (Config & config)
Save Accumulators on disk.
Save Accumulators on disk
Parameters
config config filename
Definition at line 1614 of file AccumulateTVStat.cpp.
References _statF, _statN, and verboseLevel.
Referenced by ComputeTVStats(), IvExtractor(), IvExtractorEigenDecomposition(), IvExtractorUbmWeigth(), and TotalVariability().
void TVAcc::saveT (const String & file, Config & config)
Save the Total Variability matrix
Parameters
file name of the matrix file to save
Definition at line 760 of file AccumulateTVStat.cpp.
References _T.
Referenced by TotalVariability().
void TVAcc::saveW (String yFilename, Config & config)
Save matrix W
Parameters
yFilename filename to save the matrix
Definition at line 1058 of file AccumulateTVStat.cpp.
References _W.
void TVAcc::saveWbyFile (Config & config)
Save i-vector to a file
Parameters
config config filename
Definition at line 2799 of file AccumulateTVStat.cpp.
References _rankT, and _W.
Referenced by IvExtractor(), IvExtractorEigenDecomposition(), and IvExtractorUbmWeigth().
void TVAcc::storeAccs ()
Store the sufficient statistics accumulators for backup
void TVAcc::substractM (Config & config)
Subtract the mean component M from the statistics
Parameters
config config filename
Definition at line 1078 of file AccumulateTVStat.cpp.
References substractMUnThreaded().
Referenced by IvExtractor(), and TotalVariability().
void TVAcc::substractMplusTW (Config & config)
Substract the mean component M from the speaker statistics
Parameters
config config filename
Definition at line 1369 of file AccumulateTVStat.cpp.
References substractMplusTWUnThreaded().
void TVAcc::substractMplusTWUnThreaded ()
Substract the mean component M from the speaker statistics without threads
Definition at line 1379 of file AccumulateTVStat.cpp.
References _n_distrib, _n_speakers, _statF, _statN, _vectSize, getMplusTW(), and verboseLevel.
Referenced by substractMplusTW().
void TVAcc::substractMUnThreaded ()
Subtract the mean component M from the statistics without threads
Definition at line 1088 of file AccumulateTVStat.cpp.
References _n_distrib, _n_speakers, _statF, _statN, _ubm_means, _vectSize, and verboseLevel.
Referenced by substractM().
void TVAcc::updateTestimate ()
Update the Total Variability Matrix
Definition at line 974 of file AccumulateTVStat.cpp.
References _A, _Cmx, _n_distrib, _rankT, _T, _vectSize, and verboseLevel.
Referenced by TotalVariability().
void TVAcc::verifyEMLK (Config & config)
Compute LLK
Parameters
selectedSegments segment cluster to process
model GMM model
config config filename
Compute TV model
Get LLK
Definition at line 1655 of file AccumulateTVStat.cpp.
References _fileList, getLLK(), getSpeakerModel(), initializeClusters(), verboseLevel, and verifyClusterFile().
Referenced by TotalVariability().
Member Data Documentation
Matrix<double> TVAcc::_A private
Accumulators.
Definition at line 234 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), resetTmpAcc(), and updateTestimate().
Matrix<double> TVAcc::_Cmx private
Definition at line 235 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), resetTmpAcc(), and updateTestimate().
XList TVAcc::_fileList private
Definition at line 208 of file AccumulateTVStat.h.
Referenced by _init(), computeAndAccumulateTVStat(), computeAndAccumulateTVStatUnThreaded(), getXList(), loadF_X(), loadN(), and verifyEMLK().
RealVector<double> TVAcc::_meanW private
Definition at line 220 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), and minDivergence().
MixtureServer TVAcc::_ms private
Definition at line 205 of file AccumulateTVStat.h.
Referenced by _init(), computeAndAccumulateTVStat(), and computeAndAccumulateTVStatUnThreaded().
unsigned long TVAcc::_n_distrib private
Definition at line 210 of file AccumulateTVStat.h.
Referenced by _init(), approximateTcTcUnThreaded(), computeAndAccumulateTVStat(), computeAndAccumulateTVStatUnThreaded(), estimateAandCUnthreaded(), estimateTETtUnThreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getNDistrib(), getWeightedCovUnThreaded(), loadN(), normStatisticsUnThreaded(), resetTmpAcc(), substractMplusTWUnThreaded(), substractMUnThreaded(), and updateTestimate().
unsigned long TVAcc::_n_sessions private
Definition at line 214 of file AccumulateTVStat.h.
Referenced by _init(), and minDivergence().
unsigned long TVAcc::_n_speakers private
Definition at line 213 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getNSpeakers(), normStatisticsUnThreaded(), substractMplusTWUnThreaded(), and substractMUnThreaded().
TVTranslate TVAcc::_ndxTable
Association between filename and indexes of speaker and sessions.
Definition at line 257 of file AccumulateTVStat.h.
Referenced by _init(), and getTW().
DoubleSquareMatrix TVAcc::_R private
Minimum Divergence Accumulators.
Definition at line 238 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), and minDivergence().
DoubleVector TVAcc::_r private
Definition at line 239 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), and minDivergence().
unsigned long TVAcc::_rankT private
Definition at line 212 of file AccumulateTVStat.h.
Referenced by _init(), approximateTcTcUnThreaded(), estimateAandCUnthreaded(), estimateTETtUnThreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getTW(), getWeightedCovUnThreaded(), initT(), loadT(), minDivergence(), normTMatrix(), orthonormalizeT(), saveWbyFile(), and updateTestimate().
StatServer TVAcc::_ss private
Definition at line 206 of file AccumulateTVStat.h.
Referenced by computeAndAccumulateTVStat(), computeAndAccumulateTVStatUnThreaded(), and getLLK().
Matrix<double> TVAcc::_statF private
Definition at line 224 of file AccumulateTVStat.h.
Referenced by _init(), computeAndAccumulateTVStat(), computeAndAccumulateTVStatUnThreaded(), estimateAandCUnthreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getF(), loadF_X(), normStatisticsUnThreaded(), resetAcc(), saveAccs(), substractMplusTWUnThreaded(), and substractMUnThreaded().
Matrix<double> TVAcc::_statN private
Accumulators.
Definition at line 223 of file AccumulateTVStat.h.
Referenced by _init(), computeAndAccumulateTVStat(), computeAndAccumulateTVStatUnThreaded(), estimateAandCUnthreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getN(), loadN(), normStatisticsUnThreaded(), resetAcc(), saveAccs(), substractMplusTWUnThreaded(), and substractMUnThreaded().
unsigned long TVAcc::_svSize private
Definition at line 211 of file AccumulateTVStat.h.
Referenced by _init(), computeAndAccumulateTVStat(), computeAndAccumulateTVStatUnThreaded(), estimateAandCUnthreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getMplusTW(), getSpeakerModel(), getTW(), initT(), loadF_X(), loadMeanEstimate(), minDivergence(), normTMatrix(), and orthonormalizeT().
Matrix<double> TVAcc::_T private
TotalVariability Objects.
Definition at line 227 of file AccumulateTVStat.h.
Referenced by _init(), approximateTcTcUnThreaded(), estimateAandCUnthreaded(), estimateTETtUnThreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getT(), getTW(), getWeightedCovUnThreaded(), initT(), loadT(), minDivergence(), normTMatrix(), orthonormalizeT(), saveT(), and updateTestimate().
RefVector<DoubleSquareMatrix> TVAcc::_TETt private
Accumulators for VSigmaVT.
Definition at line 231 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), estimateTETtUnThreaded(), estimateWUnThreaded(), getTETt(), resetTmpAcc(), and ~TVAcc().
RealVector<double> TVAcc::_ubm_invvar private
Definition at line 218 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), estimateTETtUnThreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUnThreaded(), getUbmInvVar(), initT(), normStatisticsUnThreaded(), and normTMatrix().
RealVector<double> TVAcc::_ubm_means private
UBM SVs.
Definition at line 217 of file AccumulateTVStat.h.
Referenced by _init(), getMplusTW(), getUbmMeans(), loadMeanEstimate(), minDivergence(), normStatisticsUnThreaded(), and substractMUnThreaded().
unsigned long TVAcc::_vectSize private
Definition at line 209 of file AccumulateTVStat.h.
Referenced by _init(), approximateTcTcUnThreaded(), computeAndAccumulateTVStat(), computeAndAccumulateTVStatUnThreaded(), estimateTETtUnThreaded(), getWeightedCovUnThreaded(), normStatisticsUnThreaded(), substractMplusTWUnThreaded(), substractMUnThreaded(), and updateTestimate().
Matrix<double> TVAcc::_W private
Definition at line 228 of file AccumulateTVStat.h.
Referenced by _init(), estimateAandCUnthreaded(), estimateWEigenDecompositionUnThreaded(), estimateWUbmWeightUnThreaded(), estimateWUnThreaded(), getTW(), getW(), saveW(), and saveWbyFile().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/AccumulateTVStat.h
LIA_SpkTools/src/AccumulateTVStat.cpp