LIA_RAL: hmm Class Reference
hmm Class Reference
#include <Hmm.h>
Public Member Functions
unsigned long getNbState ()
unsigned long getStateIndex (String)
unsigned long LoadState (String)
unsigned long LoadState (String, String)
unsigned long LoadState (Mixture &, String)
unsigned long LoadState (MixtureGD &, String)
unsigned long LoadState (Mixture &, String, unsigned long)
unsigned long LoadState (Mixture &, String, unsigned long, unsigned long)
unsigned long LoadState (MixtureGD &, String, unsigned long)
unsigned long LoadState (MixtureGD &, String, unsigned long, unsigned long)
unsigned long addState (String)
unsigned long deleteState (unsigned long indice)
double getTransition (int i, int j)
void getTransition (DoubleVector &)
void setTransition (double, int, int)
void reset ()
const hmm & operator= (const hmm &hmmc)
Mixture & getDensity (unsigned long)
void setDensity (Mixture &m, unsigned long nModel)
void setDensity (MixtureGD &m, unsigned long nModel)
void setDensity (String, unsigned long)
const String & getStateName (unsigned long)
void setStateName (unsigned long, String)
void setLength (unsigned long, unsigned long)
void setReplacement (unsigned long, unsigned long)
unsigned long getLength (unsigned long)
unsigned long getLength (String)
unsigned long getReplacement (unsigned long)
unsigned long getReplacement (String)
hmm (MixtureServer &, Config &)
hmm (const hmm &)
~hmm ()
Private Member Functions
void assign (const hmm &hmmc)
void save ()
void load ()
Private Attributes
MixtureServer * ms
Config * conf
ObjectRefVector tabState
XLine tabStateName
DoubleVector transitions
ULongVector length
ULongVector replacement
Detailed Description
Definition at line 74 of file Hmm.h.
Constructor & Destructor Documentation
hmm::hmm (MixtureServer & m, Config & config)
Definition at line 303 of file Hmm.cpp.
hmm::hmm (const hmm & h)
Definition at line 330 of file Hmm.cpp.
References assign().
hmm::~hmm ()
Definition at line 327 of file Hmm.cpp.
Member Function Documentation
unsigned long hmm::addState (String nameState)
Definition at line 209 of file Hmm.cpp.
Referenced by addSpeaker(), and segmentationProcess().
void hmm::assign (const hmm & hmmc) private
Definition at line 314 of file Hmm.cpp.
References conf, ms, reset(), tabState, tabStateName, and transitions.
Referenced by hmm(), and operator=().
unsigned long hmm::deleteState (unsigned long indice)
Definition at line 288 of file Hmm.cpp.
Referenced by isStopReSeg(), and NoDataSpeakerVerification().
Mixture & hmm::getDensity (unsigned long nModel)
Definition at line 83 of file Hmm.cpp.
Referenced by bestFittingCluster(), cohortMaxLikelihood(), computeLLKMeanOnOneCluster(), ComputePath(), createAndInitializeViterbiAccum(), CreateInitHMM(), interCluster(), intraCluster(), segAdaptation(), and segAdaptationClass().
unsigned long hmm::getLength (unsigned long i)
Definition at line 238 of file Hmm.cpp.
Referenced by applyLengthRules().
unsigned long hmm::getLength (String name)
Definition at line 244 of file Hmm.cpp.
unsigned long hmm::getNbState ()
Definition at line 68 of file Hmm.cpp.
Referenced by AcousticSegmentationProcess(), addSpeaker(), applyLengthRules(), cohortMaxLikelihood(), ComputePath(), computeTransitions(), createAndInitializeViterbiAccum(), InitHMM(), InitHMMOverlap(), initializeCluster(), ReSegmentationProcess(), and viterbiDecoding().
unsigned long hmm::getReplacement (unsigned long i)
Definition at line 256 of file Hmm.cpp.
unsigned long hmm::getReplacement (String name)
Definition at line 250 of file Hmm.cpp.
unsigned long hmm::getStateIndex (String name)
Definition at line 72 of file Hmm.cpp.
const String & hmm::getStateName (unsigned long nModel)
Definition at line 112 of file Hmm.cpp.
Referenced by applyLengthRules(), ComputePath(), copyPathInCluster(), and initializeCluster().
double hmm::getTransition (int i, int j)
Definition at line 218 of file Hmm.cpp.
Referenced by createAndInitializeViterbiAccum().
void hmm::getTransition (DoubleVector & tmpTrans)
Definition at line 223 of file Hmm.cpp.
void hmm::load () private
Definition at line 334 of file Hmm.cpp.
unsigned long hmm::LoadState (String fileName)
Definition at line 122 of file Hmm.cpp.
Referenced by AcousticSegmentationProcess(), CreateInitHMM(), InitHMM(), and InitHMMOverlap().
unsigned long hmm::LoadState (String fileName, String name)
Definition at line 131 of file Hmm.cpp.
unsigned long hmm::LoadState (Mixture & m, String name)
Definition at line 142 of file Hmm.cpp.
unsigned long hmm::LoadState (MixtureGD & m, String name)
Definition at line 152 of file Hmm.cpp.
unsigned long hmm::LoadState (Mixture & m, String name, unsigned long l)
Definition at line 162 of file Hmm.cpp.
unsigned long hmm::LoadState (Mixture & m, String name, unsigned long l, unsigned long r)
Definition at line 185 of file Hmm.cpp.
unsigned long hmm::LoadState (MixtureGD & m, String name, unsigned long l)
Definition at line 173 of file Hmm.cpp.
unsigned long hmm::LoadState (MixtureGD & m, String name, unsigned long l, unsigned long r)
Definition at line 197 of file Hmm.cpp.
const hmm & hmm::operator= (const hmm & hmmc)
Definition at line 308 of file Hmm.cpp.
References assign().
void hmm::reset (void)
Definition at line 276 of file Hmm.cpp.
Referenced by assign(), CreateInitHMM(), InitHMM(), and InitHMMOverlap().
void hmm::save () private
Definition at line 340 of file Hmm.cpp.
void hmm::setDensity (Mixture & m, unsigned long nModel)
Definition at line 89 of file Hmm.cpp.
Referenced by CreateInitHMM(), segAdaptation(), segAdaptationClass(), and segEM().
void hmm::setDensity (MixtureGD & m, unsigned long nModel)
Definition at line 101 of file Hmm.cpp.
void hmm::setDensity (String fileName, unsigned long nModel)
Definition at line 77 of file Hmm.cpp.
void hmm::setLength (unsigned long i, unsigned long l)
Definition at line 264 of file Hmm.cpp.
void hmm::setReplacement (unsigned long i, unsigned long r)
Definition at line 270 of file Hmm.cpp.
void hmm::setStateName (unsigned long nModel, String s)
Definition at line 117 of file Hmm.cpp.
void hmm::setTransition (double a, int i, int j)
Definition at line 233 of file Hmm.cpp.
Referenced by computeTransitions().
Member Data Documentation
Config* hmm::conf private
Definition at line 76 of file Hmm.h.
Referenced by assign().
ULongVector hmm::length private
Definition at line 80 of file Hmm.h.
Referenced by bestFittingSegment().
MixtureServer* hmm::ms private
Definition at line 75 of file Hmm.h.
Referenced by assign().
ULongVector hmm::replacement private
Definition at line 81 of file Hmm.h.
ObjectRefVector hmm::tabState private
Definition at line 77 of file Hmm.h.
Referenced by assign().
XLine hmm::tabStateName private
Definition at line 78 of file Hmm.h.
Referenced by assign().
DoubleVector hmm::transitions private
Definition at line 79 of file Hmm.h.
Referenced by assign().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/Hmm.h
LIA_SpkTools/src/Hmm.cpp