LIA_RAL: CritInfo Class Reference
CritInfo Class Reference
#include <TurnDetection.h>
Public Member Functions
double getValue ()
bool getDec ()
unsigned long getFrame ()
void setValue (double v)
void setDec (bool d)
void setFrame (unsigned long f)
CritInfo (double v, bool d, unsigned long f)
Private Attributes
double value
bool dec
unsigned long frame
Detailed Description
Definition at line 77 of file TurnDetection.h.
Constructor & Destructor Documentation
CritInfo::CritInfo (double v, bool d, unsigned long f) inline
Definition at line 89 of file TurnDetection.h.
Member Function Documentation
bool CritInfo::getDec () inline
Definition at line 84 of file TurnDetection.h.
unsigned long CritInfo::getFrame () inline
Definition at line 85 of file TurnDetection.h.
double CritInfo::getValue () inline
Definition at line 83 of file TurnDetection.h.
Referenced by TurnDetection().
void CritInfo::setDec (bool d) inline
Definition at line 87 of file TurnDetection.h.
Referenced by TurnDetection().
void CritInfo::setFrame (unsigned long f) inline
Definition at line 88 of file TurnDetection.h.
void CritInfo::setValue (double v) inline
Definition at line 86 of file TurnDetection.h.
Referenced by TurnDetection().
Member Data Documentation
bool CritInfo::dec private
Definition at line 79 of file TurnDetection.h.
unsigned long CritInfo::frame private
Definition at line 80 of file TurnDetection.h.
double CritInfo::value private
Definition at line 78 of file TurnDetection.h.
The documentation for this class was generated from the following file:
LIA_SpkSeg/TurnDetection/include/TurnDetection.h