LIA_RAL: Eigen::TriangularBase< Derived > Class Template Reference
Eigen::TriangularBase< Derived > Class Template Reference
#include <TriangularMatrix.h>
Public Types
enum {
Mode = internal::traits<Derived>::Mode, CoeffReadCost = internal::traits<Derived>::CoeffReadCost, RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime, ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime, MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime
}
typedef internal::traits
< Derived >::Scalar Scalar
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
typedef internal::traits
< Derived >::DenseMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
TriangularBase ()
Index rows () const
Index cols () const
Index outerStride () const
Index innerStride () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
template<typename Other >
EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
Scalar operator() (Index row, Index col) const
Scalar & operator() (Index row, Index col)
const Derived & derived () const
Derived & derived ()
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
void evalToLazy (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Protected Member Functions
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Detailed Description
template<typename Derived>
class Eigen::TriangularBase< Derived >
Definition at line 29 of file TriangularMatrix.h.
Member Typedef Documentation
template<typename Derived> typedef internal::traits<Derived>::DenseMatrixType Eigen::TriangularBase< Derived >::DenseMatrixType
Definition at line 44 of file TriangularMatrix.h.
template<typename Derived> typedef DenseMatrixType Eigen::TriangularBase< Derived >::DenseType
Definition at line 45 of file TriangularMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::Index Eigen::TriangularBase< Derived >::Index
Definition at line 43 of file TriangularMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::TriangularBase< Derived >::Scalar
Definition at line 41 of file TriangularMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::TriangularBase< Derived >::StorageKind
Definition at line 42 of file TriangularMatrix.h.
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
Mode
CoeffReadCost
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 33 of file TriangularMatrix.h.
Constructor & Destructor Documentation
template<typename Derived> Eigen::TriangularBase< Derived >::TriangularBase () inline
Definition at line 47 of file TriangularMatrix.h.
Member Function Documentation
template<typename Derived> void Eigen::TriangularBase< Derived >::check_coordinates (Index row, Index col) const inline protected
Definition at line 95 of file TriangularMatrix.h.
Referenced by Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::operator()().
template<typename Derived> void Eigen::TriangularBase< Derived >::check_coordinates_internal (Index , Index) const inline protected
Definition at line 114 of file TriangularMatrix.h.
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::coeff(), and Eigen::TriangularView< _MatrixType, _Mode >::coeffRef().
template<typename Derived> Scalar Eigen::TriangularBase< Derived >::coeff (Index row, Index col) const inline
Definition at line 54 of file TriangularMatrix.h.
Referenced by Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::operator()().
template<typename Derived> Scalar& Eigen::TriangularBase< Derived >::coeffRef (Index row, Index col) inline
Definition at line 55 of file TriangularMatrix.h.
Referenced by Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::operator()().
template<typename Derived> Index Eigen::TriangularBase< Derived >::cols (void) const inline
Definition at line 50 of file TriangularMatrix.h.
Referenced by Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::check_coordinates(), Eigen::TriangularView< _MatrixType, _Mode >::lazyAssign(), Eigen::TriangularView< _MatrixType, _Mode >::operator=(), and Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::toDenseMatrix().
template<typename Derived> template<typename Other > EIGEN_STRONG_INLINE void Eigen::TriangularBase< Derived >::copyCoeff (Index row, Index col, Other & other) inline
See Also
MatrixBase::copyCoeff(row,col)
Definition at line 60 of file TriangularMatrix.h.
template<typename Derived> const Derived& Eigen::TriangularBase< Derived >::derived () const inline
Definition at line 77 of file TriangularMatrix.h.
Referenced by Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::coeff(), Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::coeffRef(), Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::cols(), Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::copyCoeff(), Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::innerStride(), Eigen::TriangularView< _MatrixType, _Mode >::lazyAssign(), Eigen::TriangularView< _MatrixType, _Mode >::operator=(), Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::outerStride(), Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::rows(), and Eigen::TriangularView< _MatrixType, _Mode >::swap().
template<typename Derived> Derived& Eigen::TriangularBase< Derived >::derived () inline
Definition at line 78 of file TriangularMatrix.h.
template<typename Derived > template<typename DenseDerived > void Eigen::TriangularBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
Definition at line 672 of file TriangularMatrix.h.
References Eigen::EvalBeforeAssigningBit, and Eigen::DenseBase< Derived >::swap().
template<typename Derived > template<typename DenseDerived > void Eigen::TriangularBase< Derived >::evalToLazy (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
Definition at line 688 of file TriangularMatrix.h.
References Eigen::Dynamic, EIGEN_UNROLLING_LIMIT, and Eigen::DenseBase< Derived >::resize().
Referenced by Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::toDenseMatrix().
template<typename Derived> Index Eigen::TriangularBase< Derived >::innerStride () const inline
Definition at line 52 of file TriangularMatrix.h.
template<typename Derived> Scalar Eigen::TriangularBase< Derived >::operator() (Index row, Index col) const inline
Definition at line 65 of file TriangularMatrix.h.
template<typename Derived> Scalar& Eigen::TriangularBase< Derived >::operator() (Index row, Index col) inline
Definition at line 70 of file TriangularMatrix.h.
template<typename Derived> Index Eigen::TriangularBase< Derived >::outerStride () const inline
Definition at line 51 of file TriangularMatrix.h.
template<typename Derived> Index Eigen::TriangularBase< Derived >::rows (void) const inline
Definition at line 49 of file TriangularMatrix.h.
Referenced by Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::check_coordinates(), Eigen::TriangularView< _MatrixType, _Mode >::lazyAssign(), Eigen::TriangularView< _MatrixType, _Mode >::operator=(), and Eigen::TriangularBase< SelfAdjointView< MatrixType, UpLo > >::toDenseMatrix().
template<typename Derived> DenseMatrixType Eigen::TriangularBase< Derived >::toDenseMatrix () const inline
Definition at line 86 of file TriangularMatrix.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/TriangularMatrix.h