LIA_RAL: Eigen::PardisoLU< _MatrixType > Class Template Reference
Eigen::PardisoLU< _MatrixType > Class Template Reference
A sparse direct LU factorization and solver based on the PARDISO library.
#include <PardisoSupport.h>
Public Member Functions
PardisoLU ()
PardisoLU (const MatrixType &matrix)
Public Member Functions inherited from Eigen::PardisoImpl< Derived >
PardisoImpl ()
~PardisoImpl ()
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
ParameterType & pardisoParameterArray ()
Derived & analyzePattern (const MatrixType &matrix)
Derived & factorize (const MatrixType &matrix)
Derived & compute (const MatrixType &matrix)
template<typename Rhs >
const internal::solve_retval
< PardisoImpl, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const
internal::sparse_solve_retval
< PardisoImpl, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
Derived & derived ()
const Derived & derived () const
template<typename BDerived , typename XDerived >
bool _solve (const MatrixBase< BDerived > &b, MatrixBase< XDerived > &x) const
template<typename Rhs , typename DestScalar , int DestOptions, typename DestIndex >
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Protected Types
typedef PardisoImpl< PardisoLU
< MatrixType > > Base
typedef Base::Scalar Scalar
typedef Base::RealScalar RealScalar
Protected Member Functions
void getMatrix (const MatrixType &matrix)
Protected Member Functions inherited from Eigen::PardisoImpl< Derived >
void pardisoRelease ()
void pardisoInit (int type)
void manageErrorCode (Index error)
Private Member Functions
PardisoLU (PardisoLU &)
Friends
class PardisoImpl< PardisoLU< MatrixType > >
Additional Inherited Members
Public Types inherited from Eigen::PardisoImpl< Derived >
enum { ScalarIsComplex = NumTraits<Scalar>::IsComplex }
typedef Traits::MatrixType MatrixType
typedef Traits::Scalar Scalar
typedef Traits::RealScalar RealScalar
typedef Traits::Index Index
typedef SparseMatrix< Scalar,
RowMajor, Index > SparseMatrixType
typedef Matrix< Scalar,
Dynamic, 1 > VectorType
typedef Matrix< Index,
1, MatrixType::ColsAtCompileTime > IntRowVectorType
typedef Matrix< Index,
MatrixType::RowsAtCompileTime, 1 > IntColVectorType
typedef Array< Index,
64, 1, DontAlign > ParameterType
Protected Attributes inherited from Eigen::PardisoImpl< Derived >
SparseMatrixType m_matrix
ComputationInfo m_info
bool m_initialized
bool m_analysisIsOk
bool m_factorizationIsOk
Index m_type
Index m_msglvl
void * m_pt [64]
ParameterType m_iparm
IntColVectorType m_perm
Index m_size
Detailed Description
template<typename _MatrixType>
class Eigen::PardisoLU< _MatrixType >
A sparse direct LU factorization and solver based on the PARDISO library.
This class allows to solve for A.X = B sparse linear problems via a direct LU factorization using the Intel MKL PARDISO library. The sparse matrix A must be squared and invertible. The vectors or matrices X and B can be either dense or sparse.
Template Parameters
_MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
See Also
TutorialSparseDirectSolvers
Definition at line 37 of file PardisoSupport.h.
Member Typedef Documentation
template<typename _MatrixType > typedef PardisoImpl< PardisoLU<MatrixType> > Eigen::PardisoLU< _MatrixType >::Base protected
Definition at line 431 of file PardisoSupport.h.
template<typename _MatrixType > typedef Base::RealScalar Eigen::PardisoLU< _MatrixType >::RealScalar protected
Definition at line 433 of file PardisoSupport.h.
template<typename _MatrixType > typedef Base::Scalar Eigen::PardisoLU< _MatrixType >::Scalar protected
Definition at line 432 of file PardisoSupport.h.
Constructor & Destructor Documentation
template<typename _MatrixType > Eigen::PardisoLU< _MatrixType >::PardisoLU () inline
Definition at line 443 of file PardisoSupport.h.
References Eigen::PardisoImpl< Derived >::pardisoInit(), and Eigen::PardisoImpl< PardisoLU< MatrixType > >::ScalarIsComplex.
template<typename _MatrixType > Eigen::PardisoLU< _MatrixType >::PardisoLU (const MatrixType & matrix) inline
Definition at line 449 of file PardisoSupport.h.
References Eigen::PardisoImpl< Derived >::compute(), Eigen::PardisoImpl< Derived >::pardisoInit(), and Eigen::PardisoImpl< PardisoLU< MatrixType > >::ScalarIsComplex.
template<typename _MatrixType > Eigen::PardisoLU< _MatrixType >::PardisoLU (PardisoLU< _MatrixType > &) inline private
Definition at line 462 of file PardisoSupport.h.
Member Function Documentation
template<typename _MatrixType > void Eigen::PardisoLU< _MatrixType >::getMatrix (const MatrixType & matrix) inline protected
Definition at line 456 of file PardisoSupport.h.
References Eigen::PardisoImpl< Derived >::m_matrix.
Friends And Related Function Documentation
template<typename _MatrixType > friend class PardisoImpl< PardisoLU< MatrixType > > friend
Definition at line 436 of file PardisoSupport.h.
The documentation for this class was generated from the following file:
include/Eigen/src/PardisoSupport/PardisoSupport.h