LIA_RAL: Eigen::PastixBase< Derived > Class Template Reference
Eigen::PastixBase< Derived > Class Template Reference
#include <PaStiXSupport.h>
Public Types
typedef
internal::pastix_traits
< Derived >::MatrixType _MatrixType
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
Dynamic, 1 > Vector
typedef SparseMatrix< Scalar,
ColMajor > ColSpMatrix
Public Member Functions
PastixBase ()
~PastixBase ()
template<typename Rhs >
const internal::solve_retval
< PastixBase, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
bool _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &x) const
template<typename Rhs , typename DestScalar , int DestOptions, typename DestIndex >
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Derived & derived ()
const Derived & derived () const
Array< Index, IPARM_SIZE, 1 > & iparm ()
int & iparm (int idxparam)
Array< RealScalar, IPARM_SIZE, 1 > & dparm ()
double & dparm (int idxparam)
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
template<typename Rhs >
const
internal::sparse_solve_retval
< PastixBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
Protected Member Functions
void init ()
void analyzePattern (ColSpMatrix &mat)
void factorize (ColSpMatrix &mat)
void clean ()
void compute (ColSpMatrix &mat)
Protected Attributes
int m_initisOk
int m_analysisIsOk
int m_factorizationIsOk
bool m_isInitialized
ComputationInfo m_info
pastix_data_t * m_pastixdata
int m_comm
Matrix< int, IPARM_SIZE, 1 > m_iparm
Matrix< double, DPARM_SIZE, 1 > m_dparm
Matrix< Index, Dynamic, 1 > m_perm
Matrix< Index, Dynamic, 1 > m_invp
int m_size
Additional Inherited Members
Private Member Functions inherited from Eigen::internal::noncopyable
noncopyable ()
~noncopyable ()
Detailed Description
template<class Derived>
class Eigen::PastixBase< Derived >
Definition at line 120 of file PaStiXSupport.h.
Member Typedef Documentation
template<class Derived> typedef internal::pastix_traits<Derived>::MatrixType Eigen::PastixBase< Derived >::_MatrixType
Definition at line 123 of file PaStiXSupport.h.
template<class Derived> typedef SparseMatrix<Scalar, ColMajor> Eigen::PastixBase< Derived >::ColSpMatrix
Definition at line 129 of file PaStiXSupport.h.
template<class Derived> typedef MatrixType::Index Eigen::PastixBase< Derived >::Index
Definition at line 127 of file PaStiXSupport.h.
template<class Derived> typedef _MatrixType Eigen::PastixBase< Derived >::MatrixType
Definition at line 124 of file PaStiXSupport.h.
template<class Derived> typedef MatrixType::RealScalar Eigen::PastixBase< Derived >::RealScalar
Definition at line 126 of file PaStiXSupport.h.
template<class Derived> typedef MatrixType::Scalar Eigen::PastixBase< Derived >::Scalar
Definition at line 125 of file PaStiXSupport.h.
template<class Derived> typedef Matrix<Scalar,Dynamic,1> Eigen::PastixBase< Derived >::Vector
Definition at line 128 of file PaStiXSupport.h.
Constructor & Destructor Documentation
template<class Derived> Eigen::PastixBase< Derived >::PastixBase () inline
Definition at line 133 of file PaStiXSupport.h.
template<class Derived> Eigen::PastixBase< Derived >::~PastixBase () inline
Definition at line 138 of file PaStiXSupport.h.
Member Function Documentation
template<typename Base > template<typename Rhs , typename Dest > bool Eigen::PastixBase< Base >::_solve (const MatrixBase< Rhs > & b, MatrixBase< Dest > & x) const
Definition at line 409 of file PaStiXSupport.h.
References eigen_assert, Eigen::internal::eigen_pastix(), EIGEN_STATIC_ASSERT, Eigen::NumericalIssue, Eigen::RowMajorBit, and Eigen::Success.
template<class Derived> template<typename Rhs , typename DestScalar , int DestOptions, typename DestIndex > void Eigen::PastixBase< Derived >::_solve_sparse (const Rhs & b, SparseMatrix< DestScalar, DestOptions, DestIndex > & dest) const inline
Definition at line 162 of file PaStiXSupport.h.
template<class Derived > void Eigen::PastixBase< Derived >::analyzePattern (ColSpMatrix & mat) protected
Definition at line 349 of file PaStiXSupport.h.
References eigen_assert, Eigen::internal::eigen_pastix(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr(), Eigen::NumericalIssue, Eigen::SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::rows(), Eigen::Success, and Eigen::SparseMatrix< _Scalar, _Options, _Index >::valuePtr().
Referenced by Eigen::PastixLU< _MatrixType, IsStrSym >::analyzePattern(), Eigen::PastixLLT< _MatrixType, Options >::analyzePattern(), and Eigen::PastixLDLT< _MatrixType, Options >::analyzePattern().
template<class Derived> void Eigen::PastixBase< Derived >::clean () inline protected
Definition at line 270 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::~PastixBase().
template<class Derived> Index Eigen::PastixBase< Derived >::cols (void) const inline
Definition at line 227 of file PaStiXSupport.h.
template<class Derived > void Eigen::PastixBase< Derived >::compute (ColSpMatrix & mat) protected
Definition at line 336 of file PaStiXSupport.h.
References Eigen::SparseMatrix< _Scalar, _Options, _Index >::cols(), eigen_assert, and Eigen::SparseMatrix< _Scalar, _Options, _Index >::rows().
Referenced by Eigen::PastixLU< _MatrixType, IsStrSym >::compute(), Eigen::PastixLLT< _MatrixType, Options >::compute(), and Eigen::PastixLDLT< _MatrixType, Options >::compute().
template<class Derived> Derived& Eigen::PastixBase< Derived >::derived () inline
Definition at line 181 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::_solve_sparse().
template<class Derived> const Derived& Eigen::PastixBase< Derived >::derived () const inline
Definition at line 185 of file PaStiXSupport.h.
template<class Derived> Array<RealScalar,IPARM_SIZE,1>& Eigen::PastixBase< Derived >::dparm () inline
Returns a reference to the double vector DPARM of PaStiX parameters The statistics related to the different phases of factorization and solve are saved here as well
See Also
analyzePattern() factorize()
Definition at line 213 of file PaStiXSupport.h.
template<class Derived> double& Eigen::PastixBase< Derived >::dparm (int idxparam) inline
Return a reference to a particular index parameter of the DPARM vector
See Also
dparm()
Definition at line 222 of file PaStiXSupport.h.
template<class Derived > void Eigen::PastixBase< Derived >::factorize (ColSpMatrix & mat) protected
Definition at line 380 of file PaStiXSupport.h.
References eigen_assert, Eigen::internal::eigen_pastix(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr(), Eigen::NumericalIssue, Eigen::SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::rows(), Eigen::Success, and Eigen::SparseMatrix< _Scalar, _Options, _Index >::valuePtr().
Referenced by Eigen::PastixLU< _MatrixType, IsStrSym >::factorize(), Eigen::PastixLLT< _MatrixType, Options >::factorize(), and Eigen::PastixLDLT< _MatrixType, Options >::factorize().
template<class Derived> ComputationInfo Eigen::PastixBase< Derived >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the PaStiX reports a problem InvalidInput if the input matrix is invalid
See Also
iparm()
Definition at line 238 of file PaStiXSupport.h.
template<class Derived > void Eigen::PastixBase< Derived >::init () protected
Initialize the PaStiX data structure. A first call to this function fills iparm and dparm with the default PaStiX parameters
See Also
iparm() dparm()
Definition at line 300 of file PaStiXSupport.h.
References Eigen::internal::eigen_pastix(), Eigen::InvalidInput, and Eigen::Success.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::PastixBase().
template<class Derived> Array<Index,IPARM_SIZE,1>& Eigen::PastixBase< Derived >::iparm () inline
Returns a reference to the integer vector IPARM of PaStiX parameters to modify the default parameters. The statistics related to the different phases of factorization and solve are saved here as well
See Also
analyzePattern() factorize()
Definition at line 195 of file PaStiXSupport.h.
template<class Derived> int& Eigen::PastixBase< Derived >::iparm (int idxparam) inline
Return a reference to a particular index parameter of the IPARM vector
See Also
iparm()
Definition at line 204 of file PaStiXSupport.h.
template<class Derived> Index Eigen::PastixBase< Derived >::rows (void) const inline
Definition at line 228 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::_solve_sparse(), and Eigen::PastixBase< PastixLU< _MatrixType > >::solve().
template<class Derived> template<typename Rhs > const internal::solve_retval<PastixBase, Rhs> Eigen::PastixBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline
Returns
the solution x of using the current decomposition of A.
See Also
compute()
Definition at line 149 of file PaStiXSupport.h.
template<class Derived> template<typename Rhs > const internal::sparse_solve_retval<PastixBase, Rhs> Eigen::PastixBase< Derived >::solve (const SparseMatrixBase< Rhs > & b) const inline
Returns
the solution x of using the current decomposition of A.
See Also
compute()
Definition at line 250 of file PaStiXSupport.h.
Member Data Documentation
template<class Derived> int Eigen::PastixBase< Derived >::m_analysisIsOk protected
Definition at line 282 of file PaStiXSupport.h.
template<class Derived> int Eigen::PastixBase< Derived >::m_comm mutable protected
Definition at line 287 of file PaStiXSupport.h.
template<class Derived> Matrix<double,DPARM_SIZE,1> Eigen::PastixBase< Derived >::m_dparm mutable protected
Definition at line 289 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::clean(), and Eigen::PastixBase< PastixLU< _MatrixType > >::dparm().
template<class Derived> int Eigen::PastixBase< Derived >::m_factorizationIsOk protected
Definition at line 283 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::_solve_sparse().
template<class Derived> ComputationInfo Eigen::PastixBase< Derived >::m_info mutable protected
Definition at line 285 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::info().
template<class Derived> int Eigen::PastixBase< Derived >::m_initisOk protected
Definition at line 281 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::clean().
template<class Derived> Matrix<Index,Dynamic,1> Eigen::PastixBase< Derived >::m_invp mutable protected
Definition at line 291 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::clean().
template<class Derived> Matrix<int,IPARM_SIZE,1> Eigen::PastixBase< Derived >::m_iparm mutable protected
Definition at line 288 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::clean(), and Eigen::PastixBase< PastixLU< _MatrixType > >::iparm().
template<class Derived> bool Eigen::PastixBase< Derived >::m_isInitialized protected
Definition at line 284 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::info(), and Eigen::PastixBase< PastixLU< _MatrixType > >::solve().
template<class Derived> pastix_data_t* Eigen::PastixBase< Derived >::m_pastixdata mutable protected
Definition at line 286 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::clean().
template<class Derived> Matrix<Index,Dynamic,1> Eigen::PastixBase< Derived >::m_perm mutable protected
Definition at line 290 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::clean().
template<class Derived> int Eigen::PastixBase< Derived >::m_size mutable protected
Definition at line 292 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< PastixLU< _MatrixType > >::cols(), and Eigen::PastixBase< PastixLU< _MatrixType > >::rows().
The documentation for this class was generated from the following file:
include/Eigen/src/PaStiXSupport/PaStiXSupport.h