LIA_RAL: Eigen::QR< MatrixType > Class Template Reference
Eigen::QR< MatrixType > Class Template Reference
#include <QR.h>
Public Types
typedef HouseholderQR< MatrixType > Base
typedef Block< const
MatrixType,
MatrixType::ColsAtCompileTime,
MatrixType::ColsAtCompileTime > MatrixRBlockType
Public Types inherited from Eigen::HouseholderQR< MatrixType >
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
RowsAtCompileTime,(MatrixType::Flags
&RowMajorBit)?RowMajor:ColMajor,
MaxRowsAtCompileTime,
MaxRowsAtCompileTime > MatrixQType
typedef
internal::plain_diag_type
< MatrixType >::type HCoeffsType
typedef
internal::plain_row_type
< MatrixType >::type RowVectorType
typedef HouseholderSequence
< MatrixType, HCoeffsType >
::ConjugateReturnType HouseholderSequenceType
Public Member Functions
QR ()
template<typename T >
QR (const T &t)
template<typename OtherDerived , typename ResultType >
bool solve (const MatrixBase< OtherDerived > &b, ResultType *result) const
MatrixType matrixQ (void) const
bool isFullRank () const
const TriangularView
< MatrixRBlockType,
UpperTriangular > matrixR (void) const
Public Member Functions inherited from Eigen::HouseholderQR< MatrixType >
HouseholderQR ()
Default Constructor.
HouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
HouseholderQR (const MatrixType &matrix)
template<typename Rhs >
const internal::solve_retval
< HouseholderQR, Rhs > solve (const MatrixBase< Rhs > &b) const
HouseholderSequenceType householderQ () const
const MatrixType & matrixQR () const
HouseholderQR & compute (const MatrixType &matrix)
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
Additional Inherited Members
Protected Attributes inherited from Eigen::HouseholderQR< MatrixType >
MatrixType m_qr
HCoeffsType m_hCoeffs
RowVectorType m_temp
bool m_isInitialized
Detailed Description
template<typename MatrixType>
class Eigen::QR< MatrixType >
Definition at line 17 of file QR.h.
Member Typedef Documentation
template<typename MatrixType > typedef HouseholderQR<MatrixType> Eigen::QR< MatrixType >::Base
Definition at line 21 of file QR.h.
template<typename MatrixType > typedef Block<const MatrixType, MatrixType::ColsAtCompileTime, MatrixType::ColsAtCompileTime> Eigen::QR< MatrixType >::MatrixRBlockType
Definition at line 22 of file QR.h.
Constructor & Destructor Documentation
template<typename MatrixType > Eigen::QR< MatrixType >::QR () inline
Definition at line 24 of file QR.h.
template<typename MatrixType > template<typename T > Eigen::QR< MatrixType >::QR (const T & t) inline explicit
Definition at line 27 of file QR.h.
Member Function Documentation
template<typename MatrixType > bool Eigen::QR< MatrixType >::isFullRank () const inline
Definition at line 42 of file QR.h.
template<typename MatrixType > MatrixType Eigen::QR< MatrixType >::matrixQ (void) const inline
Definition at line 36 of file QR.h.
References Eigen::HouseholderQR< MatrixType >::cols(), Eigen::HouseholderQR< MatrixType >::householderQ(), and Eigen::HouseholderQR< MatrixType >::rows().
template<typename MatrixType > const TriangularView<MatrixRBlockType, UpperTriangular> Eigen::QR< MatrixType >::matrixR (void) const inline
Definition at line 47 of file QR.h.
References Eigen::HouseholderQR< MatrixType >::cols(), and Eigen::HouseholderQR< MatrixType >::matrixQR().
template<typename MatrixType > template<typename OtherDerived , typename ResultType > bool Eigen::QR< MatrixType >::solve (const MatrixBase< OtherDerived > & b, ResultType * result) const inline
Definition at line 30 of file QR.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Eigen2Support/QR.h