LIA_RAL: Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options > Class Template Reference
Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options > Class Template Reference
#include <DenseStorage.h>
Public Member Functions
DenseStorage ()
DenseStorage (internal::constructor_without_unaligned_array_assert)
DenseStorage (DenseIndex, DenseIndex, DenseIndex)
void swap (DenseStorage &other)
void conservativeResize (DenseIndex, DenseIndex, DenseIndex)
void resize (DenseIndex, DenseIndex, DenseIndex)
const T * data () const
T * data ()
Static Public Member Functions
static DenseIndex rows (void)
static DenseIndex cols (void)
Private Attributes
internal::plain_array< T, Size,
_Options > m_data
Detailed Description
template<typename T, int Size, int _Rows, int _Cols, int _Options>
class Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >
Definition at line 82 of file DenseStorage.h.
Constructor & Destructor Documentation
template<typename T, int Size, int _Rows, int _Cols, int _Options> Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::DenseStorage () inline explicit
Definition at line 89 of file DenseStorage.h.
template<typename T, int Size, int _Rows, int _Cols, int _Options> Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::DenseStorage (internal::constructor_without_unaligned_array_assert) inline
Definition at line 90 of file DenseStorage.h.
template<typename T, int Size, int _Rows, int _Cols, int _Options> Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::DenseStorage (DenseIndex , DenseIndex , DenseIndex) inline
Definition at line 92 of file DenseStorage.h.
Member Function Documentation
template<typename T, int Size, int _Rows, int _Cols, int _Options> static DenseIndex Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::cols (void) inline static
Definition at line 95 of file DenseStorage.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::cols(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket().
template<typename T, int Size, int _Rows, int _Cols, int _Options> void Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::conservativeResize (DenseIndex , DenseIndex , DenseIndex) inline
Definition at line 96 of file DenseStorage.h.
template<typename T, int Size, int _Rows, int _Cols, int _Options> const T* Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data () const inline
Definition at line 98 of file DenseStorage.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2(), Eigen::Array< Index, 64, 1, DontAlign >::Array(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::data(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket().
template<typename T, int Size, int _Rows, int _Cols, int _Options> T* Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::data () inline
Definition at line 99 of file DenseStorage.h.
template<typename T, int Size, int _Rows, int _Cols, int _Options> void Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::resize (DenseIndex , DenseIndex , DenseIndex) inline
Definition at line 97 of file DenseStorage.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize().
template<typename T, int Size, int _Rows, int _Cols, int _Options> static DenseIndex Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::rows (void) inline static
Definition at line 94 of file DenseStorage.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::packet(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::rows(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::writePacket().
template<typename T, int Size, int _Rows, int _Cols, int _Options> void Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::swap (DenseStorage< T, Size, _Rows, _Cols, _Options > & other) inline
Definition at line 93 of file DenseStorage.h.
Referenced by Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >::run().
Member Data Documentation
template<typename T, int Size, int _Rows, int _Cols, int _Options> internal::plain_array<T,Size,_Options> Eigen::DenseStorage< T, Size, _Rows, _Cols, _Options >::m_data private
Definition at line 87 of file DenseStorage.h.
Referenced by Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::swap(), Eigen::DenseStorage< T, Size, Dynamic, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Size, Dynamic, _Cols, _Options >::swap(), Eigen::DenseStorage< T, Size, _Rows, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::swap(), and Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::swap().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/DenseStorage.h