LIA_RAL: Eigen::ReturnByValue< Derived > Class Template Reference
Eigen::ReturnByValue< Derived > Class Template Reference
#include <ReturnByValue.h>
Classes
class Unusable
Public Types
typedef internal::traits
< Derived >::ReturnType ReturnType
typedef
internal::dense_xpr_base
< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
void evalTo (Dest &dst) const
Index rows () const
Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Detailed Description
template<typename Derived>
class Eigen::ReturnByValue< Derived >
Definition at line 50 of file ReturnByValue.h.
Member Typedef Documentation
template<typename Derived> typedef internal::dense_xpr_base<ReturnByValue>::type Eigen::ReturnByValue< Derived >::Base
Definition at line 56 of file ReturnByValue.h.
template<typename Derived> typedef internal::traits<Derived>::ReturnType Eigen::ReturnByValue< Derived >::ReturnType
Definition at line 54 of file ReturnByValue.h.
Member Function Documentation
template<typename Derived> const Unusable& Eigen::ReturnByValue< Derived >::coeff (Index) const inline
Definition at line 71 of file ReturnByValue.h.
template<typename Derived> const Unusable& Eigen::ReturnByValue< Derived >::coeff (Index , Index) const inline
Definition at line 72 of file ReturnByValue.h.
template<typename Derived> Unusable& Eigen::ReturnByValue< Derived >::coeffRef (Index) inline
Definition at line 73 of file ReturnByValue.h.
template<typename Derived> Unusable& Eigen::ReturnByValue< Derived >::coeffRef (Index , Index) inline
Definition at line 74 of file ReturnByValue.h.
template<typename Derived> Index Eigen::ReturnByValue< Derived >::cols (void) const inline
Definition at line 63 of file ReturnByValue.h.
Referenced by Eigen::Array< Index, 64, 1, DontAlign >::Array(), Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::cols(), Eigen::Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=().
template<typename Derived> template<typename Dest > void Eigen::ReturnByValue< Derived >::evalTo (Dest & dst) const inline
Definition at line 60 of file ReturnByValue.h.
Referenced by Eigen::Array< Index, 64, 1, DontAlign >::Array(), Eigen::Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator=(), Eigen::DenseBase< Derived >::operator=(), Eigen::Transform< _Scalar, _Dim >::operator=(), Eigen::MatrixBase< Derived >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor >::SparseMatrix(), and Eigen::Transform< _Scalar, _Dim >::Transform().
template<typename Derived> Index Eigen::ReturnByValue< Derived >::rows (void) const inline
Definition at line 62 of file ReturnByValue.h.
Referenced by Eigen::Array< Index, 64, 1, DontAlign >::Array(), Eigen::Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), and Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::rows().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/ReturnByValue.h