LIA_RAL: Eigen::UmfPackLU< _MatrixType > Class Template Reference
Eigen::UmfPackLU< _MatrixType > Class Template Reference
A sparse LU factorization and solver based on UmfPack.
#include <UmfPackSupport.h>
Public Types
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
Dynamic, 1 > Vector
typedef Matrix< int,
1, MatrixType::ColsAtCompileTime > IntRowVectorType
typedef Matrix< int,
MatrixType::RowsAtCompileTime, 1 > IntColVectorType
typedef SparseMatrix< Scalar > LUMatrixType
typedef SparseMatrix< Scalar,
ColMajor, int > UmfpackMatrixType
Public Member Functions
UmfPackLU ()
UmfPackLU (const MatrixType &matrix)
~UmfPackLU ()
Index rows () const
Index cols () const
ComputationInfo info () const
Reports whether previous computation was successful.
const LUMatrixType & matrixL () const
const LUMatrixType & matrixU () const
const IntColVectorType & permutationP () const
const IntRowVectorType & permutationQ () const
void compute (const MatrixType &matrix)
template<typename Rhs >
const internal::solve_retval
< UmfPackLU, Rhs > solve (const MatrixBase< Rhs > &b) const
void analyzePattern (const MatrixType &matrix)
void factorize (const MatrixType &matrix)
template<typename BDerived , typename XDerived >
bool _solve (const MatrixBase< BDerived > &b, MatrixBase< XDerived > &x) const
Scalar determinant () const
void extractData () const
Protected Member Functions
void init ()
void grapInput (const MatrixType &mat)
Protected Attributes
LUMatrixType m_l
LUMatrixType m_u
IntColVectorType m_p
IntRowVectorType m_q
UmfpackMatrixType m_copyMatrix
const Scalar * m_valuePtr
const int * m_outerIndexPtr
const int * m_innerIndexPtr
void * m_numeric
void * m_symbolic
ComputationInfo m_info
bool m_isInitialized
int m_factorizationIsOk
int m_analysisIsOk
bool m_extractedDataAreDirty
Private Member Functions
UmfPackLU (UmfPackLU &)
Private Member Functions inherited from Eigen::internal::noncopyable
noncopyable ()
~noncopyable ()
Detailed Description
template<typename _MatrixType>
class Eigen::UmfPackLU< _MatrixType >
A sparse LU factorization and solver based on UmfPack.
This class allows to solve for A.X = B sparse linear problems via a LU factorization using the UmfPack library. The sparse matrix A must be squared and full rank. The vectors or matrices X and B can be either dense or sparse.
The input matrix A should be in a compressed and column-major form. Otherwise an expensive copy will be made. You can call the inexpensive makeCompressed() to get a compressed matrix.
Template Parameters
_MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
See Also
TutorialSparseDirectSolvers
Definition at line 124 of file UmfPackSupport.h.
Member Typedef Documentation
template<typename _MatrixType> typedef MatrixType::Index Eigen::UmfPackLU< _MatrixType >::Index
Definition at line 130 of file UmfPackSupport.h.
template<typename _MatrixType> typedef Matrix<int, MatrixType::RowsAtCompileTime, 1> Eigen::UmfPackLU< _MatrixType >::IntColVectorType
Definition at line 133 of file UmfPackSupport.h.
template<typename _MatrixType> typedef Matrix<int, 1, MatrixType::ColsAtCompileTime> Eigen::UmfPackLU< _MatrixType >::IntRowVectorType
Definition at line 132 of file UmfPackSupport.h.
template<typename _MatrixType> typedef SparseMatrix<Scalar> Eigen::UmfPackLU< _MatrixType >::LUMatrixType
Definition at line 134 of file UmfPackSupport.h.
template<typename _MatrixType> typedef _MatrixType Eigen::UmfPackLU< _MatrixType >::MatrixType
Definition at line 127 of file UmfPackSupport.h.
template<typename _MatrixType> typedef MatrixType::RealScalar Eigen::UmfPackLU< _MatrixType >::RealScalar
Definition at line 129 of file UmfPackSupport.h.
template<typename _MatrixType> typedef MatrixType::Scalar Eigen::UmfPackLU< _MatrixType >::Scalar
Definition at line 128 of file UmfPackSupport.h.
template<typename _MatrixType> typedef SparseMatrix<Scalar,ColMajor,int> Eigen::UmfPackLU< _MatrixType >::UmfpackMatrixType
Definition at line 135 of file UmfPackSupport.h.
template<typename _MatrixType> typedef Matrix<Scalar,Dynamic,1> Eigen::UmfPackLU< _MatrixType >::Vector
Definition at line 131 of file UmfPackSupport.h.
Constructor & Destructor Documentation
template<typename _MatrixType> Eigen::UmfPackLU< _MatrixType >::UmfPackLU () inline
Definition at line 139 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::init().
template<typename _MatrixType> Eigen::UmfPackLU< _MatrixType >::UmfPackLU (const MatrixType & matrix) inline
Definition at line 141 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::compute(), and Eigen::UmfPackLU< _MatrixType >::init().
template<typename _MatrixType> Eigen::UmfPackLU< _MatrixType >::~UmfPackLU () inline
Definition at line 147 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::m_numeric, Eigen::UmfPackLU< _MatrixType >::m_symbolic, Eigen::umfpack_free_numeric(), and Eigen::umfpack_free_symbolic().
template<typename _MatrixType> Eigen::UmfPackLU< _MatrixType >::UmfPackLU (UmfPackLU< _MatrixType > &) inline private
Definition at line 337 of file UmfPackSupport.h.
Member Function Documentation
template<typename MatrixType > template<typename BDerived , typename XDerived > bool Eigen::UmfPackLU< MatrixType >::_solve (const MatrixBase< BDerived > & b, MatrixBase< XDerived > & x) const
Definition at line 379 of file UmfPackSupport.h.
References Eigen::DenseBase< Derived >::col(), eigen_assert, Eigen::RowMajorBit, and Eigen::umfpack_solve().
template<typename _MatrixType> void Eigen::UmfPackLU< _MatrixType >::analyzePattern (const MatrixType & matrix) inline
Returns
the solution x of using the current decomposition of A.
See Also
compute()Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See Also
factorize(), compute()
Definition at line 233 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::grapInput(), Eigen::InvalidInput, Eigen::UmfPackLU< _MatrixType >::m_analysisIsOk, Eigen::UmfPackLU< _MatrixType >::m_factorizationIsOk, Eigen::UmfPackLU< _MatrixType >::m_info, Eigen::UmfPackLU< _MatrixType >::m_innerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_isInitialized, Eigen::UmfPackLU< _MatrixType >::m_numeric, Eigen::UmfPackLU< _MatrixType >::m_outerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_symbolic, Eigen::UmfPackLU< _MatrixType >::m_valuePtr, Eigen::Success, Eigen::umfpack_free_numeric(), Eigen::umfpack_free_symbolic(), and Eigen::umfpack_symbolic().
Referenced by Eigen::UmfPackLU< _MatrixType >::compute().
template<typename _MatrixType> Index Eigen::UmfPackLU< _MatrixType >::cols (void) const inline
Definition at line 154 of file UmfPackSupport.h.
References Eigen::SparseMatrix< _Scalar, _Options, _Index >::cols(), and Eigen::UmfPackLU< _MatrixType >::m_copyMatrix.
template<typename _MatrixType> void Eigen::UmfPackLU< _MatrixType >::compute (const MatrixType & matrix) inline
Computes the sparse Cholesky decomposition of matrix Note that the matrix should be column-major, and in compressed format for best performance.
See Also
SparseMatrix::makeCompressed().
Definition at line 195 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::analyzePattern(), and Eigen::UmfPackLU< _MatrixType >::factorize().
Referenced by Eigen::UmfPackLU< _MatrixType >::UmfPackLU().
template<typename MatrixType > UmfPackLU< MatrixType >::Scalar Eigen::UmfPackLU< MatrixType >::determinant () const
Definition at line 370 of file UmfPackSupport.h.
References Eigen::umfpack_get_determinant().
template<typename MatrixType > void Eigen::UmfPackLU< MatrixType >::extractData () const
Definition at line 342 of file UmfPackSupport.h.
References min(), Eigen::umfpack_get_lunz(), and Eigen::umfpack_get_numeric().
Referenced by Eigen::UmfPackLU< _MatrixType >::matrixL(), Eigen::UmfPackLU< _MatrixType >::matrixU(), Eigen::UmfPackLU< _MatrixType >::permutationP(), and Eigen::UmfPackLU< _MatrixType >::permutationQ().
template<typename _MatrixType> void Eigen::UmfPackLU< _MatrixType >::factorize (const MatrixType & matrix) inline
Performs a numeric decomposition of matrix
The given matrix must has the same sparcity than the matrix on which the pattern anylysis has been performed.
See Also
analyzePattern(), compute()
Definition at line 258 of file UmfPackSupport.h.
References eigen_assert, Eigen::UmfPackLU< _MatrixType >::grapInput(), Eigen::UmfPackLU< _MatrixType >::m_analysisIsOk, Eigen::UmfPackLU< _MatrixType >::m_factorizationIsOk, Eigen::UmfPackLU< _MatrixType >::m_info, Eigen::UmfPackLU< _MatrixType >::m_innerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_numeric, Eigen::UmfPackLU< _MatrixType >::m_outerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_symbolic, Eigen::UmfPackLU< _MatrixType >::m_valuePtr, Eigen::NumericalIssue, Eigen::Success, Eigen::umfpack_free_numeric(), and Eigen::umfpack_numeric().
Referenced by Eigen::UmfPackLU< _MatrixType >::compute().
template<typename _MatrixType> void Eigen::UmfPackLU< _MatrixType >::grapInput (const MatrixType & mat) inline protected
Definition at line 298 of file UmfPackSupport.h.
References Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr(), Eigen::UmfPackLU< _MatrixType >::m_copyMatrix, Eigen::UmfPackLU< _MatrixType >::m_innerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_outerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_valuePtr, Eigen::SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::resize(), Eigen::RowMajorBit, and Eigen::SparseMatrix< _Scalar, _Options, _Index >::valuePtr().
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), and Eigen::UmfPackLU< _MatrixType >::factorize().
template<typename _MatrixType> ComputationInfo Eigen::UmfPackLU< _MatrixType >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the matrix.appears to be negative.
Definition at line 161 of file UmfPackSupport.h.
References eigen_assert, Eigen::UmfPackLU< _MatrixType >::m_info, and Eigen::UmfPackLU< _MatrixType >::m_isInitialized.
template<typename _MatrixType> void Eigen::UmfPackLU< _MatrixType >::init () inline protected
Definition at line 287 of file UmfPackSupport.h.
References Eigen::InvalidInput, Eigen::UmfPackLU< _MatrixType >::m_info, Eigen::UmfPackLU< _MatrixType >::m_innerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_isInitialized, Eigen::UmfPackLU< _MatrixType >::m_numeric, Eigen::UmfPackLU< _MatrixType >::m_outerIndexPtr, Eigen::UmfPackLU< _MatrixType >::m_symbolic, and Eigen::UmfPackLU< _MatrixType >::m_valuePtr.
Referenced by Eigen::UmfPackLU< _MatrixType >::UmfPackLU().
template<typename _MatrixType> const LUMatrixType& Eigen::UmfPackLU< _MatrixType >::matrixL () const inline
Definition at line 167 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::UmfPackLU< _MatrixType >::m_extractedDataAreDirty, and Eigen::UmfPackLU< _MatrixType >::m_l.
template<typename _MatrixType> const LUMatrixType& Eigen::UmfPackLU< _MatrixType >::matrixU () const inline
Definition at line 173 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::UmfPackLU< _MatrixType >::m_extractedDataAreDirty, and Eigen::UmfPackLU< _MatrixType >::m_u.
template<typename _MatrixType> const IntColVectorType& Eigen::UmfPackLU< _MatrixType >::permutationP () const inline
Definition at line 179 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::UmfPackLU< _MatrixType >::m_extractedDataAreDirty, and Eigen::UmfPackLU< _MatrixType >::m_p.
template<typename _MatrixType> const IntRowVectorType& Eigen::UmfPackLU< _MatrixType >::permutationQ () const inline
Definition at line 185 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::UmfPackLU< _MatrixType >::m_extractedDataAreDirty, and Eigen::UmfPackLU< _MatrixType >::m_q.
template<typename _MatrixType> Index Eigen::UmfPackLU< _MatrixType >::rows (void) const inline
Definition at line 153 of file UmfPackSupport.h.
References Eigen::UmfPackLU< _MatrixType >::m_copyMatrix, and Eigen::SparseMatrix< _Scalar, _Options, _Index >::rows().
Referenced by Eigen::UmfPackLU< _MatrixType >::solve().
template<typename _MatrixType> template<typename Rhs > const internal::solve_retval<UmfPackLU, Rhs> Eigen::UmfPackLU< _MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
Returns
the solution x of using the current decomposition of A.
See Also
compute()
Definition at line 206 of file UmfPackSupport.h.
References eigen_assert, Eigen::UmfPackLU< _MatrixType >::m_isInitialized, and Eigen::UmfPackLU< _MatrixType >::rows().
Member Data Documentation
template<typename _MatrixType> int Eigen::UmfPackLU< _MatrixType >::m_analysisIsOk protected
Definition at line 333 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), and Eigen::UmfPackLU< _MatrixType >::factorize().
template<typename _MatrixType> UmfpackMatrixType Eigen::UmfPackLU< _MatrixType >::m_copyMatrix protected
Definition at line 323 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::cols(), Eigen::UmfPackLU< _MatrixType >::grapInput(), and Eigen::UmfPackLU< _MatrixType >::rows().
template<typename _MatrixType> bool Eigen::UmfPackLU< _MatrixType >::m_extractedDataAreDirty mutable protected
Definition at line 334 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::matrixL(), Eigen::UmfPackLU< _MatrixType >::matrixU(), Eigen::UmfPackLU< _MatrixType >::permutationP(), and Eigen::UmfPackLU< _MatrixType >::permutationQ().
template<typename _MatrixType> int Eigen::UmfPackLU< _MatrixType >::m_factorizationIsOk protected
Definition at line 332 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), and Eigen::UmfPackLU< _MatrixType >::factorize().
template<typename _MatrixType> ComputationInfo Eigen::UmfPackLU< _MatrixType >::m_info mutable protected
Definition at line 330 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::factorize(), Eigen::UmfPackLU< _MatrixType >::info(), and Eigen::UmfPackLU< _MatrixType >::init().
template<typename _MatrixType> const int* Eigen::UmfPackLU< _MatrixType >::m_innerIndexPtr protected
Definition at line 326 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::factorize(), Eigen::UmfPackLU< _MatrixType >::grapInput(), and Eigen::UmfPackLU< _MatrixType >::init().
template<typename _MatrixType> bool Eigen::UmfPackLU< _MatrixType >::m_isInitialized protected
Definition at line 331 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::info(), Eigen::UmfPackLU< _MatrixType >::init(), and Eigen::UmfPackLU< _MatrixType >::solve().
template<typename _MatrixType> LUMatrixType Eigen::UmfPackLU< _MatrixType >::m_l mutable protected
Definition at line 318 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::matrixL().
template<typename _MatrixType> void* Eigen::UmfPackLU< _MatrixType >::m_numeric protected
Definition at line 327 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::factorize(), Eigen::UmfPackLU< _MatrixType >::init(), and Eigen::UmfPackLU< _MatrixType >::~UmfPackLU().
template<typename _MatrixType> const int* Eigen::UmfPackLU< _MatrixType >::m_outerIndexPtr protected
Definition at line 325 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::factorize(), Eigen::UmfPackLU< _MatrixType >::grapInput(), and Eigen::UmfPackLU< _MatrixType >::init().
template<typename _MatrixType> IntColVectorType Eigen::UmfPackLU< _MatrixType >::m_p mutable protected
Definition at line 320 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::permutationP().
template<typename _MatrixType> IntRowVectorType Eigen::UmfPackLU< _MatrixType >::m_q mutable protected
Definition at line 321 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::permutationQ().
template<typename _MatrixType> void* Eigen::UmfPackLU< _MatrixType >::m_symbolic protected
Definition at line 328 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::factorize(), Eigen::UmfPackLU< _MatrixType >::init(), and Eigen::UmfPackLU< _MatrixType >::~UmfPackLU().
template<typename _MatrixType> LUMatrixType Eigen::UmfPackLU< _MatrixType >::m_u mutable protected
Definition at line 319 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::matrixU().
template<typename _MatrixType> const Scalar* Eigen::UmfPackLU< _MatrixType >::m_valuePtr protected
Definition at line 324 of file UmfPackSupport.h.
Referenced by Eigen::UmfPackLU< _MatrixType >::analyzePattern(), Eigen::UmfPackLU< _MatrixType >::factorize(), Eigen::UmfPackLU< _MatrixType >::grapInput(), and Eigen::UmfPackLU< _MatrixType >::init().
The documentation for this class was generated from the following file:
include/Eigen/src/UmfPackSupport/UmfPackSupport.h