LIA_RAL: Eigen::SparseSelfAdjointView< MatrixType, UpLo > Class Template Reference
Eigen::SparseSelfAdjointView< MatrixType, UpLo > Class Template Reference
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
#include <SparseSelfAdjointView.h>
Public Types
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef Matrix< Index, Dynamic, 1 > VectorI
typedef MatrixType::Nested MatrixTypeNested
typedef internal::remove_all
< MatrixTypeNested >::type _MatrixTypeNested
Public Types inherited from Eigen::EigenBase< SparseSelfAdjointView< MatrixType, UpLo > >
typedef internal::traits
< SparseSelfAdjointView
< MatrixType, UpLo >
>::StorageKind StorageKind
typedef internal::traits
< SparseSelfAdjointView
< MatrixType, UpLo > >::Index Index
Public Member Functions
SparseSelfAdjointView (const MatrixType &matrix)
Index rows () const
Index cols () const
const _MatrixTypeNested & matrix () const
_MatrixTypeNested & matrix ()
template<typename OtherDerived >
SparseSelfAdjointTimeDenseProduct
< MatrixType, OtherDerived,
UpLo > operator* (const MatrixBase< OtherDerived > &rhs) const
template<typename DerivedU >
SparseSelfAdjointView & rankUpdate (const SparseMatrixBase< DerivedU > &u, Scalar alpha=Scalar(1))
template<typename DestScalar , int StorageOrder>
void evalTo (SparseMatrix< DestScalar, StorageOrder, Index > &_dest) const
template<typename DestScalar >
void evalTo (DynamicSparseMatrix< DestScalar, ColMajor, Index > &_dest) const
SparseSymmetricPermutationProduct
< _MatrixTypeNested, UpLo > twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > &perm) const
template<typename SrcMatrixType , int SrcUpLo>
SparseSelfAdjointView & operator= (const SparseSymmetricPermutationProduct< SrcMatrixType, SrcUpLo > &permutedMatrix)
SparseSelfAdjointView & operator= (const SparseSelfAdjointView &src)
template<typename SrcMatrixType , unsigned int SrcUpLo>
SparseSelfAdjointView & operator= (const SparseSelfAdjointView< SrcMatrixType, SrcUpLo > &src)
template<typename DerivedU >
SparseSelfAdjointView
< MatrixType, UpLo > & rankUpdate (const SparseMatrixBase< DerivedU > &u, Scalar alpha)
Public Member Functions inherited from Eigen::EigenBase< SparseSelfAdjointView< MatrixType, UpLo > >
SparseSelfAdjointView
< MatrixType, UpLo > & derived ()
const SparseSelfAdjointView
< MatrixType, UpLo > & derived () const
SparseSelfAdjointView
< MatrixType, UpLo > & const_cast_derived () const
const SparseSelfAdjointView
< MatrixType, UpLo > & const_derived () const
Index rows () const
Index cols () const
Index size () const
void evalTo (Dest &dst) const
void addTo (Dest &dst) const
void subTo (Dest &dst) const
void applyThisOnTheRight (Dest &dst) const
void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
MatrixType::Nested m_matrix
VectorI m_countPerRow
VectorI m_countPerCol
Friends
template<typename OtherDerived >
DenseTimeSparseSelfAdjointProduct
< OtherDerived, MatrixType,
UpLo > operator* (const MatrixBase< OtherDerived > &lhs, const SparseSelfAdjointView &rhs)
Detailed Description
template<typename MatrixType, unsigned int UpLo>
class Eigen::SparseSelfAdjointView< MatrixType, UpLo >
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
Parameters
MatrixType the type of the dense matrix storing the coefficients
UpLo can be either Lower or Upper
This class is an expression of a sefladjoint matrix from a triangular part of a matrix with given dense storage of the coefficients. It is the return type of MatrixBase::selfadjointView() and most of the time this is the only way that it is used.
See Also
SparseMatrixBase::selfadjointView()
Definition at line 49 of file SparseSelfAdjointView.h.
Member Typedef Documentation
template<typename MatrixType, unsigned int UpLo> typedef internal::remove_all<MatrixTypeNested>::type Eigen::SparseSelfAdjointView< MatrixType, UpLo >::_MatrixTypeNested
Definition at line 58 of file SparseSelfAdjointView.h.
template<typename MatrixType, unsigned int UpLo> typedef MatrixType::Index Eigen::SparseSelfAdjointView< MatrixType, UpLo >::Index
Definition at line 55 of file SparseSelfAdjointView.h.
template<typename MatrixType, unsigned int UpLo> typedef MatrixType::Nested Eigen::SparseSelfAdjointView< MatrixType, UpLo >::MatrixTypeNested
Definition at line 57 of file SparseSelfAdjointView.h.
template<typename MatrixType, unsigned int UpLo> typedef MatrixType::Scalar Eigen::SparseSelfAdjointView< MatrixType, UpLo >::Scalar
Definition at line 54 of file SparseSelfAdjointView.h.
template<typename MatrixType, unsigned int UpLo> typedef Matrix<Index,Dynamic,1> Eigen::SparseSelfAdjointView< MatrixType, UpLo >::VectorI
Definition at line 56 of file SparseSelfAdjointView.h.
Constructor & Destructor Documentation
template<typename MatrixType, unsigned int UpLo> Eigen::SparseSelfAdjointView< MatrixType, UpLo >::SparseSelfAdjointView (const MatrixType & matrix) inline
Definition at line 60 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::cols(), eigen_assert, and Eigen::SparseSelfAdjointView< MatrixType, UpLo >::rows().
Member Function Documentation
template<typename MatrixType, unsigned int UpLo> Index Eigen::SparseSelfAdjointView< MatrixType, UpLo >::cols (void) const inline
Definition at line 66 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, UpLo >::SparseSelfAdjointView().
template<typename MatrixType, unsigned int UpLo> template<typename DestScalar , int StorageOrder> void Eigen::SparseSelfAdjointView< MatrixType, UpLo >::evalTo (SparseMatrix< DestScalar, StorageOrder, Index > & _dest) const inline
Definition at line 100 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
template<typename MatrixType, unsigned int UpLo> template<typename DestScalar > void Eigen::SparseSelfAdjointView< MatrixType, UpLo >::evalTo (DynamicSparseMatrix< DestScalar, ColMajor, Index > & _dest) const inline
Definition at line 105 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
template<typename MatrixType, unsigned int UpLo> const _MatrixTypeNested& Eigen::SparseSelfAdjointView< MatrixType, UpLo >::matrix () const inline
Definition at line 69 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
Referenced by Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo().
template<typename MatrixType, unsigned int UpLo> _MatrixTypeNested& Eigen::SparseSelfAdjointView< MatrixType, UpLo >::matrix () inline
Definition at line 70 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
template<typename MatrixType, unsigned int UpLo> template<typename OtherDerived > SparseSelfAdjointTimeDenseProduct<MatrixType,OtherDerived,UpLo> Eigen::SparseSelfAdjointView< MatrixType, UpLo >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient sparse self-adjoint matrix times dense vector/matrix product
Definition at line 75 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
template<typename MatrixType, unsigned int UpLo> template<typename SrcMatrixType , int SrcUpLo> SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, UpLo >::operator= (const SparseSymmetricPermutationProduct< SrcMatrixType, SrcUpLo > & permutedMatrix) inline
Definition at line 120 of file SparseSelfAdjointView.h.
References Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo().
template<typename MatrixType, unsigned int UpLo> SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, UpLo >::operator= (const SparseSelfAdjointView< MatrixType, UpLo > & src) inline
Definition at line 127 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::twistedBy().
template<typename MatrixType, unsigned int UpLo> template<typename SrcMatrixType , unsigned int SrcUpLo> SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, UpLo >::operator= (const SparseSelfAdjointView< SrcMatrixType, SrcUpLo > & src) inline
Definition at line 134 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::twistedBy().
template<typename MatrixType, unsigned int UpLo> template<typename DerivedU > SparseSelfAdjointView& Eigen::SparseSelfAdjointView< MatrixType, UpLo >::rankUpdate (const SparseMatrixBase< DerivedU > & u, Scalar alpha = Scalar(1))
Perform a symmetric rank K update of the selfadjoint matrix *this: where u is a vector or matrix.
Returns
a reference to *this
To perform you can simply call this function with u.adjoint().
template<typename MatrixType, unsigned int UpLo> template<typename DerivedU > SparseSelfAdjointView<MatrixType,UpLo>& Eigen::SparseSelfAdjointView< MatrixType, UpLo >::rankUpdate (const SparseMatrixBase< DerivedU > & u, Scalar alpha)
Definition at line 176 of file SparseSelfAdjointView.h.
References Eigen::SparseMatrixBase< Derived >::adjoint(), and Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >::const_cast_derived().
template<typename MatrixType, unsigned int UpLo> Index Eigen::SparseSelfAdjointView< MatrixType, UpLo >::rows (void) const inline
Definition at line 65 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, UpLo >::SparseSelfAdjointView().
template<typename MatrixType, unsigned int UpLo> SparseSymmetricPermutationProduct<_MatrixTypeNested,UpLo> Eigen::SparseSelfAdjointView< MatrixType, UpLo >::twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > & perm) const inline
Returns
an expression of P H P^-1
Definition at line 114 of file SparseSelfAdjointView.h.
References Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, UpLo >::operator=().
Friends And Related Function Documentation
template<typename MatrixType, unsigned int UpLo> template<typename OtherDerived > DenseTimeSparseSelfAdjointProduct<OtherDerived,MatrixType,UpLo> operator* (const MatrixBase< OtherDerived > & lhs, const SparseSelfAdjointView< MatrixType, UpLo > & rhs) friend
Efficient dense vector/matrix times sparse self-adjoint matrix product
Definition at line 83 of file SparseSelfAdjointView.h.
Member Data Documentation
template<typename MatrixType, unsigned int UpLo> VectorI Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_countPerCol mutable protected
Definition at line 148 of file SparseSelfAdjointView.h.
template<typename MatrixType, unsigned int UpLo> VectorI Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_countPerRow mutable protected
Definition at line 147 of file SparseSelfAdjointView.h.
template<typename MatrixType, unsigned int UpLo> MatrixType::Nested Eigen::SparseSelfAdjointView< MatrixType, UpLo >::m_matrix protected
Definition at line 146 of file SparseSelfAdjointView.h.
Referenced by Eigen::SparseSelfAdjointView< MatrixType, UpLo >::cols(), Eigen::SparseSelfAdjointView< MatrixType, UpLo >::evalTo(), Eigen::SparseSelfAdjointView< MatrixType, UpLo >::matrix(), Eigen::SparseSelfAdjointView< MatrixType, UpLo >::operator*(), Eigen::SparseSelfAdjointView< MatrixType, UpLo >::rows(), and Eigen::SparseSelfAdjointView< MatrixType, UpLo >::twistedBy().
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCore/SparseSelfAdjointView.h