LIA_RAL: Eigen::BiCGSTAB< _MatrixType, _Preconditioner > Class Template Reference
Eigen::BiCGSTAB< _MatrixType, _Preconditioner > Class Template Reference
A bi conjugate gradient stabilized solver for sparse square problems.
#include <BiCGSTAB.h>
Public Types
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef MatrixType::RealScalar RealScalar
typedef _Preconditioner Preconditioner
Public Types inherited from Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >
typedef internal::traits
< BiCGSTAB< _MatrixType,
_Preconditioner >
>::MatrixType MatrixType
typedef internal::traits
< BiCGSTAB< _MatrixType,
_Preconditioner >
>::Preconditioner Preconditioner
typedef MatrixType::Scalar Scalar
typedef MatrixType::Index Index
typedef MatrixType::RealScalar RealScalar
Public Member Functions
BiCGSTAB ()
BiCGSTAB (const MatrixType &A)
~BiCGSTAB ()
template<typename Rhs , typename Guess >
const
internal::solve_retval_with_guess
< BiCGSTAB, Rhs, Guess > solveWithGuess (const MatrixBase< Rhs > &b, const Guess &x0) const
template<typename Rhs , typename Dest >
void _solveWithGuess (const Rhs &b, Dest &x) const
template<typename Rhs , typename Dest >
void _solve (const Rhs &b, Dest &x) const
Public Member Functions inherited from Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >
BiCGSTAB< _MatrixType,
_Preconditioner > & derived ()
const BiCGSTAB< _MatrixType,
_Preconditioner > & derived () const
IterativeSolverBase ()
IterativeSolverBase (const MatrixType &A)
~IterativeSolverBase ()
BiCGSTAB< _MatrixType,
_Preconditioner > & analyzePattern (const MatrixType &A)
BiCGSTAB< _MatrixType,
_Preconditioner > & factorize (const MatrixType &A)
BiCGSTAB< _MatrixType,
_Preconditioner > & compute (const MatrixType &A)
Index rows () const
Index cols () const
RealScalar tolerance () const
BiCGSTAB< _MatrixType,
_Preconditioner > & setTolerance (RealScalar tolerance)
Preconditioner & preconditioner ()
const Preconditioner & preconditioner () const
int maxIterations () const
BiCGSTAB< _MatrixType,
_Preconditioner > & setMaxIterations (int maxIters)
int iterations () const
RealScalar error () const
const internal::solve_retval
< BiCGSTAB< _MatrixType,
_Preconditioner >, Rhs > solve (const MatrixBase< Rhs > &b) const
const
internal::sparse_solve_retval
< IterativeSolverBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
ComputationInfo info () const
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Private Types
typedef IterativeSolverBase
< BiCGSTAB > Base
Additional Inherited Members
Protected Member Functions inherited from Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >
void init ()
Protected Attributes inherited from Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >
const MatrixType * mp_matrix
Preconditioner m_preconditioner
int m_maxIterations
RealScalar m_tolerance
RealScalar m_error
int m_iterations
ComputationInfo m_info
bool m_isInitialized
bool m_analysisIsOk
bool m_factorizationIsOk
Detailed Description
template<typename _MatrixType, typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>>
class Eigen::BiCGSTAB< _MatrixType, _Preconditioner >
A bi conjugate gradient stabilized solver for sparse square problems.
This class allows to solve for A.x = b sparse linear problems using a bi conjugate gradient stabilized algorithm. The vectors x and b can be either dense or sparse.
Template Parameters
_MatrixType the type of the sparse matrix A, can be a dense or a sparse matrix.
_Preconditioner the type of the preconditioner. Default is DiagonalPreconditioner
The maximal number of iterations and tolerance value can be controlled via the setMaxIterations() and setTolerance() methods. The defaults are the size of the problem for the maximal number of iterations and NumTraits<Scalar>::epsilon() for the tolerance.
This class can be used as the direct solver classes. Here is a typical usage example:
int n = 10000;
VectorXd x(n), b(n);
SparseMatrix<double> A(n,n);
// fill A and b
BiCGSTAB<SparseMatrix<double> > solver;
solver(A);
x = solver.solve(b);
std::cout << "#iterations:     " << solver.iterations() << std::endl;
std::cout << "estimated error: " << solver.error()      << std::endl;
// update b, and solve again
x = solver.solve(b);
By default the iterations start with x=0 as an initial guess of the solution. One can control the start using the solveWithGuess() method. Here is a step by step execution example starting with a random guess and printing the evolution of the estimated error:
x = VectorXd::Random(n);
solver.setMaxIterations(1);
int i = 0;
do {
  x = solver.solveWithGuess(b,x);
  std::cout << i << " : " << solver.error() << std::endl;
  ++i;
} while (solver.info()!=Success && i<100);
Note that such a step by step excution is slightly slower.
See Also
class SimplicialCholesky, DiagonalPreconditioner, IdentityPreconditioner
Definition at line 92 of file BiCGSTAB.h.
Member Typedef Documentation
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef IterativeSolverBase<BiCGSTAB> Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::Base private
Definition at line 154 of file BiCGSTAB.h.
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef MatrixType::Index Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::Index
Definition at line 163 of file BiCGSTAB.h.
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef _MatrixType Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::MatrixType
Definition at line 161 of file BiCGSTAB.h.
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef _Preconditioner Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::Preconditioner
Definition at line 165 of file BiCGSTAB.h.
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef MatrixType::RealScalar Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::RealScalar
Definition at line 164 of file BiCGSTAB.h.
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> typedef MatrixType::Scalar Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::Scalar
Definition at line 162 of file BiCGSTAB.h.
Constructor & Destructor Documentation
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::BiCGSTAB () inline
Default constructor.
Definition at line 170 of file BiCGSTAB.h.
Referenced by Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::solveWithGuess().
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::BiCGSTAB (const MatrixType & A) inline
Initialize the solver with matrix A for further Ax=b solving.
This constructor is a shortcut for the default constructor followed by a call to compute().
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
Definition at line 182 of file BiCGSTAB.h.
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::~BiCGSTAB () inline
Definition at line 184 of file BiCGSTAB.h.
Member Function Documentation
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> template<typename Rhs , typename Dest > void Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::_solve (const Rhs & b, Dest & x) const inline
Definition at line 224 of file BiCGSTAB.h.
References Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::_solveWithGuess().
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> template<typename Rhs , typename Dest > void Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::_solveWithGuess (const Rhs & b, Dest & x) const inline
Definition at line 204 of file BiCGSTAB.h.
References Eigen::internal::bicgstab(), Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >::m_error, Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >::m_info, Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >::m_isInitialized, Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >::m_iterations, Eigen::IterativeSolverBase< Derived >::m_preconditioner, Eigen::IterativeSolverBase< Derived >::m_tolerance, Eigen::IterativeSolverBase< Derived >::maxIterations(), Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >::mp_matrix, Eigen::NoConvergence, Eigen::NumericalIssue, and Eigen::Success.
Referenced by Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::_solve().
template<typename _MatrixType , typename _Preconditioner = DiagonalPreconditioner<typename _MatrixType::Scalar>> template<typename Rhs , typename Guess > const internal::solve_retval_with_guess<BiCGSTAB, Rhs, Guess> Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::solveWithGuess (const MatrixBase< Rhs > & b, const Guess & x0) const inline
Returns
the solution x of using the current decomposition of A x0 as an initial solution.
See Also
compute()
Definition at line 193 of file BiCGSTAB.h.
References Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::BiCGSTAB(), eigen_assert, Eigen::IterativeSolverBase< BiCGSTAB< _MatrixType, _Preconditioner > >::m_isInitialized, and Eigen::IterativeSolverBase< Derived >::rows().
The documentation for this class was generated from the following file:
include/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h