LIA_RAL: Eigen::QuaternionBase< Derived > Class Template Reference
Eigen::QuaternionBase< Derived > Class Template Reference
Geometry_Module
Base class for quaternion expressions.
#include <ForwardDeclarations.h>
Public Types
enum { Flags = Eigen::internal::traits<Derived>::Flags }
typedef internal::traits
< Derived >::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::traits
< Derived >::Coefficients Coefficients
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef AngleAxis< Scalar > AngleAxisType
Public Types inherited from Eigen::RotationBase< Derived, 3 >
enum
enum
typedef ei_traits< Derived >
::Scalar Scalar
typedef internal::traits
< Derived >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
Scalar x () const
Scalar y () const
Scalar z () const
Scalar w () const
Scalar & x ()
Scalar & y ()
Scalar & z ()
Scalar & w ()
const VectorBlock< const
Coefficients, 3 > vec () const
VectorBlock< Coefficients, 3 > vec ()
const internal::traits
< Derived >::Coefficients & coeffs () const
internal::traits< Derived >
::Coefficients & coeffs ()
EIGEN_STRONG_INLINE
QuaternionBase< Derived > & operator= (const QuaternionBase< Derived > &other)
template<class OtherDerived >
EIGEN_STRONG_INLINE Derived & operator= (const QuaternionBase< OtherDerived > &other)
Derived & operator= (const AngleAxisType &aa)
template<class OtherDerived >
Derived & operator= (const MatrixBase< OtherDerived > &m)
QuaternionBase & setIdentity ()
Scalar squaredNorm () const
Scalar norm () const
void normalize ()
Quaternion< Scalar > normalized () const
template<class OtherDerived >
Scalar dot (const QuaternionBase< OtherDerived > &other) const
template<class OtherDerived >
Scalar angularDistance (const QuaternionBase< OtherDerived > &other) const
Matrix3 toRotationMatrix () const
template<typename Derived1 , typename Derived2 >
Derived & setFromTwoVectors (const MatrixBase< Derived1 > &a, const MatrixBase< Derived2 > &b)
template<class OtherDerived >
EIGEN_STRONG_INLINE Quaternion
< Scalar > operator* (const QuaternionBase< OtherDerived > &q) const
template<class OtherDerived >
EIGEN_STRONG_INLINE Derived & operator*= (const QuaternionBase< OtherDerived > &q)
Quaternion< Scalar > inverse () const
Quaternion< Scalar > conjugate () const
template<class OtherDerived >
Quaternion< Scalar > slerp (Scalar t, const QuaternionBase< OtherDerived > &other) const
template<class OtherDerived >
bool isApprox (const QuaternionBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_STRONG_INLINE Vector3 _transformVector (Vector3 v) const
template<typename NewScalarType >
internal::cast_return_type
< Derived, Quaternion
< NewScalarType > >::type cast () const
template<class OtherDerived >
EIGEN_STRONG_INLINE Quaternion
< typename internal::traits
< Derived >::Scalar > operator* (const QuaternionBase< OtherDerived > &other) const
template<class MatrixDerived >
Derived & operator= (const MatrixBase< MatrixDerived > &xpr)
template<class OtherDerived >
internal::traits< Derived >::Scalar angularDistance (const QuaternionBase< OtherDerived > &other) const
template<class OtherDerived >
Quaternion< typename
internal::traits< Derived >
::Scalar > slerp (Scalar t, const QuaternionBase< OtherDerived > &other) const
Public Member Functions inherited from Eigen::RotationBase< Derived, 3 >
const Derived & derived () const
Derived & derived ()
const Derived & derived () const
Derived & derived ()
RotationMatrixType toRotationMatrix () const
RotationMatrixType toRotationMatrix () const
Derived inverse () const
Derived inverse () const
Transform< Scalar, Dim > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const Scaling< Scalar, Dim > &s) const
Transform< Scalar, Dim > operator* (const Transform< Scalar, Dim > &t) const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_STRONG_INLINE
internal::rotation_base_generic_product_selector
< Derived, OtherDerived,
OtherDerived::IsVectorAtCompileTime >
::ReturnType operator* (const EigenBase< OtherDerived > &e) const
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
RotationMatrixType matrix () const
VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static Quaternion< Scalar > Identity ()
Private Types
typedef RotationBase< Derived, 3 > Base
Detailed Description
template<typename Derived>
class Eigen::QuaternionBase< Derived >
Base class for quaternion expressions.
Template Parameters
Derived derived type (CRTP)
See Also
class Quaternion
Definition at line 234 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename Derived> typedef AngleAxis<Scalar> Eigen::QuaternionBase< Derived >::AngleAxisType
the equivalent angle-axis type
Definition at line 55 of file Quaternion.h.
template<typename Derived> typedef RotationBase<Derived, 3> Eigen::QuaternionBase< Derived >::Base private
Definition at line 37 of file Quaternion.h.
template<typename Derived> typedef internal::traits<Derived>::Coefficients Eigen::QuaternionBase< Derived >::Coefficients
Definition at line 44 of file Quaternion.h.
template<typename Derived> typedef Matrix<Scalar,3,3> Eigen::QuaternionBase< Derived >::Matrix3
the equivalent rotation matrix type
Definition at line 53 of file Quaternion.h.
template<typename Derived> typedef NumTraits<Scalar>::Real Eigen::QuaternionBase< Derived >::RealScalar
Definition at line 43 of file Quaternion.h.
template<typename Derived> typedef internal::traits<Derived>::Scalar Eigen::QuaternionBase< Derived >::Scalar
Definition at line 42 of file Quaternion.h.
template<typename Derived> typedef Matrix<Scalar,3,1> Eigen::QuaternionBase< Derived >::Vector3
the type of a 3D vector
Definition at line 51 of file Quaternion.h.
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
Flags
Definition at line 45 of file Quaternion.h.
Member Function Documentation
template<class Derived > EIGEN_STRONG_INLINE QuaternionBase< Derived >::Vector3 Eigen::QuaternionBase< Derived >::_transformVector (Vector3 v) const
return the result vector of v through the rotation
Rotation of a vector by a quaternion.
Remarks
If the quaternion is used to rotate several points (>1) then it is much more efficient to first convert it to a 3x3 Matrix. Comparison of the operation cost for n transformations:
Quaternion2: 30n
Via a Matrix3: 24 + 15n
Definition at line 476 of file Quaternion.h.
template<typename Derived> template<class OtherDerived > Scalar Eigen::QuaternionBase< Derived >::angularDistance (const QuaternionBase< OtherDerived > & other) const
template<typename Derived> template<class OtherDerived > internal::traits<Derived>::Scalar Eigen::QuaternionBase< Derived >::angularDistance (const QuaternionBase< OtherDerived > & other) const inline
Returns
the angle (in radian) between two rotations
See Also
dot()
Definition at line 677 of file Quaternion.h.
References abs(), and acos().
template<typename Derived> template<typename NewScalarType > internal::cast_return_type<Derived,Quaternion<NewScalarType> >::type Eigen::QuaternionBase< Derived >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 176 of file Quaternion.h.
template<typename Derived> const internal::traits<Derived>::Coefficients& Eigen::QuaternionBase< Derived >::coeffs () const inline
Returns
a read-only vector expression of the coefficients (x,y,z,w)
Definition at line 84 of file Quaternion.h.
Referenced by Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::isApprox(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::norm(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::normalize(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::normalized(), Eigen::QuaternionBase< Derived >::operator=(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, float, Aligned >::run(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run(), Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run(), Eigen::internal::quaternionbase_assign_impl< Other, 4, 1 >::run(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::setIdentity(), Eigen::QuaternionBase< Derived >::slerp(), Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::squaredNorm(), and Eigen::QuaternionBase< Quaternion< _Scalar, _Options > >::vec().
template<typename Derived> internal::traits<Derived>::Coefficients& Eigen::QuaternionBase< Derived >::coeffs () inline
Returns
a vector expression of the coefficients (x,y,z,w)
Definition at line 87 of file Quaternion.h.
template<class Derived > Quaternion< typename internal::traits< Derived >::Scalar > Eigen::QuaternionBase< Derived >::conjugate (void) const inline
Returns
the conjugated quaternion
the conjugate of the *this which is equal to the multiplicative inverse if the quaternion is normalized. The conjugate of a quaternion represents the opposite rotation.
See Also
Quaternion2::inverse()
Definition at line 666 of file Quaternion.h.
References Eigen::internal::y.
template<typename Derived> template<class OtherDerived > Scalar Eigen::QuaternionBase< Derived >::dot (const QuaternionBase< OtherDerived > & other) const inline
Returns
the dot product of *this and other Geometrically speaking, the dot product of two unit quaternions corresponds to the cosine of half the angle between the two rotations.
See Also
angularDistance()
Definition at line 133 of file Quaternion.h.
template<typename Derived> static Quaternion<Scalar> Eigen::QuaternionBase< Derived >::Identity () inline static
Returns
a quaternion representing an identity rotation
See Also
MatrixBase::Identity()
Definition at line 105 of file Quaternion.h.
template<class Derived > Quaternion< typename internal::traits< Derived >::Scalar > Eigen::QuaternionBase< Derived >::inverse (void) const inline
Returns
the quaternion describing the inverse rotation
the multiplicative inverse of *this Note that in most cases, i.e., if you simply want the opposite rotation, and/or the quaternion is normalized, then it is enough to use the conjugate.
See Also
QuaternionBase::conjugate()
Definition at line 645 of file Quaternion.h.
References conjugate().
template<typename Derived> template<class OtherDerived > bool Eigen::QuaternionBase< Derived >::isApprox (const QuaternionBase< OtherDerived > & other, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 164 of file Quaternion.h.
template<typename Derived> Scalar Eigen::QuaternionBase< Derived >::norm () const inline
Returns
the norm of the quaternion's coefficients
See Also
QuaternionBase::squaredNorm(), MatrixBase::norm()
Definition at line 119 of file Quaternion.h.
template<typename Derived> void Eigen::QuaternionBase< Derived >::normalize (void) inline
Normalizes the quaternion *this
See Also
normalized(), MatrixBase::normalize()
Definition at line 123 of file Quaternion.h.
template<typename Derived> Quaternion<Scalar> Eigen::QuaternionBase< Derived >::normalized () const inline
Returns
a normalized copy of *this
See Also
normalize(), MatrixBase::normalized()
Definition at line 126 of file Quaternion.h.
template<typename Derived> template<class OtherDerived > EIGEN_STRONG_INLINE Quaternion<Scalar> Eigen::QuaternionBase< Derived >::operator* (const QuaternionBase< OtherDerived > & q) const
template<typename Derived> template<class OtherDerived > EIGEN_STRONG_INLINE Quaternion<typename internal::traits<Derived>::Scalar> Eigen::QuaternionBase< Derived >::operator* (const QuaternionBase< OtherDerived > & other) const
Returns
the concatenation of two rotations as a quaternion-quaternion product
Definition at line 449 of file Quaternion.h.
References EIGEN_STATIC_ASSERT, and Eigen::Architecture::Target.
template<class Derived > template<class OtherDerived > EIGEN_STRONG_INLINE Derived & Eigen::QuaternionBase< Derived >::operator*= (const QuaternionBase< OtherDerived > & other)
See Also
operator*(Quaternion)
Definition at line 461 of file Quaternion.h.
References Eigen::RotationBase< Derived, 3 >::derived().
template<class Derived> EIGEN_STRONG_INLINE QuaternionBase< Derived > & Eigen::QuaternionBase< Derived >::operator= (const QuaternionBase< Derived > & other)
Definition at line 489 of file Quaternion.h.
References Eigen::QuaternionBase< Derived >::coeffs().
template<class Derived > template<class OtherDerived > EIGEN_STRONG_INLINE Derived & Eigen::QuaternionBase< Derived >::operator= (const QuaternionBase< OtherDerived > & other)
Definition at line 497 of file Quaternion.h.
References Eigen::QuaternionBase< Derived >::coeffs().
template<class Derived> EIGEN_STRONG_INLINE Derived & Eigen::QuaternionBase< Derived >::operator= (const AngleAxisType & aa)
Set *this from an angle-axis aa and returns a reference to *this
Definition at line 506 of file Quaternion.h.
References Eigen::AngleAxis< Scalar >::angle(), Eigen::AngleAxis< Scalar >::axis(), cos(), and sin().
template<typename Derived> template<class OtherDerived > Derived& Eigen::QuaternionBase< Derived >::operator= (const MatrixBase< OtherDerived > & m)
template<typename Derived> template<class MatrixDerived > Derived& Eigen::QuaternionBase< Derived >::operator= (const MatrixBase< MatrixDerived > & xpr) inline
Set *this from the expression xpr:
if xpr is a 4x1 vector, then xpr is assumed to be a quaternion
if xpr is a 3x3 matrix, then xpr is assumed to be rotation matrix and xpr is converted to a quaternion
Definition at line 522 of file Quaternion.h.
References EIGEN_STATIC_ASSERT.
template<class Derived > template<typename Derived1 , typename Derived2 > Derived & Eigen::QuaternionBase< Derived >::setFromTwoVectors (const MatrixBase< Derived1 > & a, const MatrixBase< Derived2 > & b) inline
Returns
the quaternion which transform a into b through a rotation
Sets *this to be a quaternion representing a rotation between the two arbitrary vectors a and b. In other words, the built rotation represent a rotation sending the line of direction a to the line of direction b, both lines passing through the origin.
Returns
a reference to *this.
Note that the two input vectors do not have to be normalized, and do not need to have the same norm.
Definition at line 581 of file Quaternion.h.
References Eigen::ComputeFullV, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::matrixV(), max(), Eigen::MatrixBase< Derived >::normalized(), and sqrt().
template<typename Derived> QuaternionBase& Eigen::QuaternionBase< Derived >::setIdentity () inline
See Also
QuaternionBase::Identity(), MatrixBase::setIdentity()
Definition at line 109 of file Quaternion.h.
template<typename Derived> template<class OtherDerived > Quaternion<Scalar> Eigen::QuaternionBase< Derived >::slerp (Scalar t, const QuaternionBase< OtherDerived > & other) const
Returns
an interpolation for a constant motion between other and *this t in [0;1] see http://en.wikipedia.org/wiki/Slerp
template<typename Derived> template<class OtherDerived > Quaternion<typename internal::traits<Derived>::Scalar> Eigen::QuaternionBase< Derived >::slerp (Scalar t, const QuaternionBase< OtherDerived > & other) const
Returns
the spherical linear interpolation between the two quaternions *this and other at the parameter t
Definition at line 692 of file Quaternion.h.
References abs(), acos(), Eigen::QuaternionBase< Derived >::coeffs(), and sin().
template<typename Derived> Scalar Eigen::QuaternionBase< Derived >::squaredNorm () const inline
Returns
the squared norm of the quaternion's coefficients
See Also
QuaternionBase::norm(), MatrixBase::squaredNorm()
Definition at line 114 of file Quaternion.h.
template<class Derived > QuaternionBase< Derived >::Matrix3 Eigen::QuaternionBase< Derived >::toRotationMatrix (void) const inline
Returns
an equivalent 3x3 rotation matrix
Convert the quaternion to a 3x3 rotation matrix. The quaternion is required to be normalized, otherwise the result is undefined.
Definition at line 535 of file Quaternion.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::internal::y.
template<typename Derived> const VectorBlock<const Coefficients,3> Eigen::QuaternionBase< Derived >::vec () const inline
Returns
a read-only vector expression of the imaginary part (x,y,z)
Definition at line 78 of file Quaternion.h.
Referenced by Eigen::AngleAxis< Scalar >::operator=().
template<typename Derived> VectorBlock<Coefficients,3> Eigen::QuaternionBase< Derived >::vec () inline
Returns
a vector expression of the imaginary part (x,y,z)
Definition at line 81 of file Quaternion.h.
template<typename Derived> Scalar Eigen::QuaternionBase< Derived >::w () const inline
Returns
the w coefficient
Definition at line 66 of file Quaternion.h.
Referenced by Eigen::AngleAxis< Scalar >::operator=(), Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar, _Options >::run(), and Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run().
template<typename Derived> Scalar& Eigen::QuaternionBase< Derived >::w () inline
Returns
a reference to the w coefficient
Definition at line 75 of file Quaternion.h.
template<typename Derived> Scalar Eigen::QuaternionBase< Derived >::x () const inline
Returns
the x coefficient
Definition at line 60 of file Quaternion.h.
Referenced by Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar, _Options >::run(), and Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run().
template<typename Derived> Scalar& Eigen::QuaternionBase< Derived >::x () inline
Returns
a reference to the x coefficient
Definition at line 69 of file Quaternion.h.
template<typename Derived> Scalar Eigen::QuaternionBase< Derived >::y () const inline
Returns
the y coefficient
Definition at line 62 of file Quaternion.h.
Referenced by Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar, _Options >::run(), and Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run().
template<typename Derived> Scalar& Eigen::QuaternionBase< Derived >::y () inline
Returns
a reference to the y coefficient
Definition at line 71 of file Quaternion.h.
template<typename Derived> Scalar Eigen::QuaternionBase< Derived >::z () const inline
Returns
the z coefficient
Definition at line 64 of file Quaternion.h.
Referenced by Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar, _Options >::run(), and Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >::run().
template<typename Derived> Scalar& Eigen::QuaternionBase< Derived >::z () inline
Returns
a reference to the z coefficient
Definition at line 73 of file Quaternion.h.
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Geometry/Quaternion.h