LIA_RAL: Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true > Class Template Reference
#include <JacobiSVD.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime }
typedef MatrixType::Index Index
typedef MatrixType::Scalar Scalar
typedef Matrix< Scalar,
1, RowsAtCompileTime, RowMajor,
1, MaxRowsAtCompileTime > WorkspaceType
Public Member Functions
void allocate (const JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Attributes
FullPivHouseholderQR< MatrixType > m_qr
WorkspaceType m_workspace
Detailed Description
template<typename MatrixType>
class Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
Definition at line 65 of file JacobiSVD.h.
Member Typedef Documentation
template<typename MatrixType > typedef MatrixType::Index Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::Index
Definition at line 68 of file JacobiSVD.h.
template<typename MatrixType > typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::Scalar
Definition at line 69 of file JacobiSVD.h.
template<typename MatrixType > typedef Matrix<Scalar, 1, RowsAtCompileTime, RowMajor, 1, MaxRowsAtCompileTime> Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::WorkspaceType
Definition at line 75 of file JacobiSVD.h.
Member Enumeration Documentation
template<typename MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
MaxRowsAtCompileTime
Definition at line 70 of file JacobiSVD.h.
Member Function Documentation
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate (const JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > & svd) inline
Definition at line 77 of file JacobiSVD.h.
References Eigen::JacobiSVD< MatrixType, QRPreconditioner >::cols(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullU, and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::rows().
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run (JacobiSVD< MatrixType, FullPivHouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
Definition at line 86 of file JacobiSVD.h.
References Eigen::JacobiSVD< MatrixType, QRPreconditioner >::computeV(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixV, and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
template<typename MatrixType > FullPivHouseholderQR<MatrixType> Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_qr private
Definition at line 99 of file JacobiSVD.h.
template<typename MatrixType > WorkspaceType Eigen::internal::qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::m_workspace private
Definition at line 100 of file JacobiSVD.h.
The documentation for this class was generated from the following file:
include/Eigen/src/SVD/JacobiSVD.h