LIA_RAL: NGram Class Reference
NGram Class Reference
#include <LabelNGram.h>
Public Member Functions
NGram (unsigned long order, unsigned long nb)
NGram (const NGram &ng)
~NGram ()
const NGram & operator= (const NGram &ng)
unsigned long getOrder ()
unsigned long getSize ()
void setSize (const unsigned size)
short int getSymbol (const unsigned idx, const unsigned long o)
unsigned long getCount (const unsigned idx)
void setCount (const unsigned idx, const unsigned long &count)
unsigned long getTotalCount ()
void setTotalCount (const unsigned long &count)
void setSymbol (const unsigned, const unsigned long, const short int, unsigned long)
void showTable (ostream &out=cout)
void load (const String filename, Config &config)
Private Attributes
unsigned long _order
unsigned long _nb
short int * _sym
unsigned long * _count
unsigned long _totalCount
Detailed Description
Definition at line 67 of file LabelNGram.h.
Constructor & Destructor Documentation
NGram::NGram (unsigned long order, unsigned long nb)
Definition at line 66 of file LabelNGram.cpp.
NGram::NGram (const NGram & ng)
Definition at line 80 of file LabelNGram.cpp.
References _count, _nb, _order, _sym, and _totalCount.
NGram::~NGram ()
Definition at line 73 of file LabelNGram.cpp.
Member Function Documentation
unsigned long NGram::getCount (const unsigned idx)
Definition at line 126 of file LabelNGram.cpp.
Referenced by CommonPartTree::addNGram().
unsigned long NGram::getOrder () inline
Definition at line 80 of file LabelNGram.h.
Referenced by CommonPartTree::addNGram(), computeLabelNGram(), and isNGram().
unsigned long NGram::getSize () inline
Definition at line 81 of file LabelNGram.h.
Referenced by CommonPartTree::addNGram(), and isNGram().
short int NGram::getSymbol (const unsigned idx, const unsigned long o)
Definition at line 120 of file LabelNGram.cpp.
Referenced by CommonPartTree::addNGram(), and isNGram().
unsigned long NGram::getTotalCount ()
Definition at line 138 of file LabelNGram.cpp.
void NGram::load (const String filename, Config & config)
Definition at line 162 of file LabelNGram.cpp.
References verboseLevel.
Referenced by labelNGram(), and sequenceExtractor().
const NGram & NGram::operator= (const NGram & ng)
Definition at line 89 of file LabelNGram.cpp.
References _count, _nb, _order, _sym, and _totalCount.
void NGram::setCount (const unsigned idx, const unsigned long & count)
Definition at line 132 of file LabelNGram.cpp.
void NGram::setSize (const unsigned size)
Definition at line 106 of file LabelNGram.cpp.
void NGram::setSymbol (const unsigned idx, const unsigned long o, const short int sym, unsigned long count = 0)
Definition at line 144 of file LabelNGram.cpp.
void NGram::setTotalCount (const unsigned long & count)
Definition at line 141 of file LabelNGram.cpp.
void NGram::showTable (ostream & out = cout)
Definition at line 150 of file LabelNGram.cpp.
Referenced by sequenceExtractor().
Member Data Documentation
unsigned long* NGram::_count private
Definition at line 71 of file LabelNGram.h.
Referenced by NGram(), and operator=().
unsigned long NGram::_nb private
Definition at line 69 of file LabelNGram.h.
Referenced by NGram(), and operator=().
unsigned long NGram::_order private
Definition at line 68 of file LabelNGram.h.
Referenced by NGram(), and operator=().
short int* NGram::_sym private
Definition at line 70 of file LabelNGram.h.
Referenced by NGram(), and operator=().
unsigned long NGram::_totalCount private
Definition at line 72 of file LabelNGram.h.
Referenced by NGram(), and operator=().
The documentation for this class was generated from the following files:
LIA_Utils/LabelNGram/include/LabelNGram.h
LIA_Utils/LabelNGram/src/LabelNGram.cpp