LIA_RAL: alize::FileInfo Class Reference
alize::FileInfo Class Reference
#include <FileInfo.h>
Public Member Functions
FileInfo (const FileName &)
virtual ~FileInfo ()
virtual void close ()
virtual String getClassName () const
virtual String toString () const
void open (int mode)
bool isClosed () const
bool isOpen () const
void writeTopInfo (const LKVector &value, Config &c)
void writeTopInfo (RealVector< real_t > &value, Config &c)
void loadTopInfo (StatServer &ss, unsigned long &numLigne, Config &c)
Public Attributes
FILE * _pFileStruct
FileName _fileName
bool _swap
Detailed Description
Definition at line 78 of file FileInfo.h.
Constructor & Destructor Documentation
FileInfo::FileInfo (const FileName & f) explicit
Definition at line 68 of file FileInfo.cpp.
FileInfo::~FileInfo () virtual
Definition at line 202 of file FileInfo.cpp.
References close().
Member Function Documentation
void FileInfo::close () virtual
Closes the file
Exceptions
IOException if an I/O error occurs
Definition at line 102 of file FileInfo.cpp.
References _fileName, _pFileStruct, and isOpen().
Referenced by computeFastLLR(), computeLLR(), open(), and ~FileInfo().
String FileInfo::getClassName () const virtual
Definition at line 196 of file FileInfo.cpp.
bool FileInfo::isClosed () const
Tests whether the file is closed
Definition at line 74 of file FileInfo.cpp.
References _pFileStruct.
Referenced by loadTopInfo(), and writeTopInfo().
bool FileInfo::isOpen () const
Tests whether the file is opened
Definition at line 80 of file FileInfo.cpp.
References _pFileStruct.
Referenced by close(), and open().
void FileInfo::loadTopInfo (StatServer & ss, unsigned long & numLigne, Config & c)
Definition at line 155 of file FileInfo.cpp.
References _fileName, _pFileStruct, isClosed(), and open().
Referenced by adaptModelEMweightedFrames(), and computeFastLLR().
void FileInfo::open (int mode)
Exceptions
IOException if an I/O error occurs
Definition at line 86 of file FileInfo.cpp.
References _fileName, _pFileStruct, close(), and isOpen().
Referenced by loadTopInfo(), and writeTopInfo().
String FileInfo::toString () const virtual
Definition at line 190 of file FileInfo.cpp.
References _fileName.
void FileInfo::writeTopInfo (const LKVector & value, Config & c)
Definition at line 111 of file FileInfo.cpp.
References _fileName, _pFileStruct, isClosed(), and open().
Referenced by adaptModelEMweightedFrames(), and computeLLR().
void FileInfo::writeTopInfo (RealVector< real_t > & value, Config & c)
Definition at line 133 of file FileInfo.cpp.
References _fileName, _pFileStruct, isClosed(), and open().
Member Data Documentation
FileName alize::FileInfo::_fileName
Definition at line 93 of file FileInfo.h.
Referenced by close(), loadTopInfo(), open(), toString(), and writeTopInfo().
FILE* alize::FileInfo::_pFileStruct
Definition at line 92 of file FileInfo.h.
Referenced by close(), isClosed(), isOpen(), loadTopInfo(), open(), and writeTopInfo().
bool alize::FileInfo::_swap
Definition at line 94 of file FileInfo.h.
The documentation for this class was generated from the following files:
LIA_SpkTools/include/FileInfo.h
LIA_SpkTools/src/FileInfo.cpp