LIA_RAL: Eigen::AngleAxis< Scalar > Class Template Reference
Eigen::AngleAxis< Scalar > Class Template Reference
Geometry_Module
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
#include <ForwardDeclarations.h>
Public Types
enum { Dim = 3 }
enum { Dim = 3 }
typedef _Scalar Scalar
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Quaternion< Scalar > QuaternionType
typedef _Scalar Scalar
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Quaternion< Scalar > QuaternionType
Public Types inherited from Eigen::RotationBase< AngleAxis< _Scalar >, 3 >
enum
enum
typedef ei_traits< AngleAxis
< _Scalar > >::Scalar Scalar
typedef internal::traits
< AngleAxis< _Scalar >
>::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
AngleAxis ()
template<typename Derived >
AngleAxis (Scalar angle, const MatrixBase< Derived > &axis)
AngleAxis (const QuaternionType &q)
template<typename Derived >
AngleAxis (const MatrixBase< Derived > &m)
Scalar angle () const
Scalar & angle ()
const Vector3 & axis () const
Vector3 & axis ()
QuaternionType operator* (const AngleAxis &other) const
QuaternionType operator* (const QuaternionType &other) const
Matrix3 operator* (const Matrix3 &other) const
Vector3 operator* (const Vector3 &other) const
AngleAxis inverse () const
AngleAxis & operator= (const QuaternionType &q)
template<typename Derived >
AngleAxis & operator= (const MatrixBase< Derived > &m)
template<typename Derived >
AngleAxis & fromRotationMatrix (const MatrixBase< Derived > &m)
Matrix3 toRotationMatrix (void) const
template<typename NewScalarType >
internal::cast_return_type
< AngleAxis, AngleAxis
< NewScalarType > >::type cast () const
template<typename OtherScalarType >
AngleAxis (const AngleAxis< OtherScalarType > &other)
bool isApprox (const AngleAxis &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
AngleAxis ()
template<typename Derived >
AngleAxis (Scalar angle, const MatrixBase< Derived > &axis)
template<typename QuatDerived >
AngleAxis (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
AngleAxis (const MatrixBase< Derived > &m)
Scalar angle () const
Scalar & angle ()
const Vector3 & axis () const
Vector3 & axis ()
QuaternionType operator* (const AngleAxis &other) const
QuaternionType operator* (const QuaternionType &other) const
AngleAxis inverse () const
template<class QuatDerived >
AngleAxis & operator= (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
AngleAxis & operator= (const MatrixBase< Derived > &m)
template<typename Derived >
AngleAxis & fromRotationMatrix (const MatrixBase< Derived > &m)
Matrix3 toRotationMatrix (void) const
template<typename NewScalarType >
internal::cast_return_type
< AngleAxis, AngleAxis
< NewScalarType > >::type cast () const
template<typename OtherScalarType >
AngleAxis (const AngleAxis< OtherScalarType > &other)
bool isApprox (const AngleAxis &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
AngleAxis< Scalar > & operator= (const MatrixBase< Derived > &mat)
template<typename QuatDerived >
AngleAxis< Scalar > & operator= (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
AngleAxis< Scalar > & fromRotationMatrix (const MatrixBase< Derived > &mat)
Sets *this from a 3x3 rotation matrix.
Public Member Functions inherited from Eigen::RotationBase< AngleAxis< _Scalar >, 3 >
const AngleAxis< _Scalar > & derived () const
AngleAxis< _Scalar > & derived ()
const AngleAxis< _Scalar > & derived () const
AngleAxis< _Scalar > & derived ()
RotationMatrixType toRotationMatrix () const
RotationMatrixType toRotationMatrix () const
AngleAxis< _Scalar > inverse () const
AngleAxis< _Scalar > inverse () const
Transform< Scalar, Dim > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const Scaling< Scalar, Dim > &s) const
Transform< Scalar, Dim > operator* (const Transform< Scalar, Dim > &t) const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_STRONG_INLINE
internal::rotation_base_generic_product_selector
< AngleAxis< _Scalar >
, OtherDerived,
OtherDerived::IsVectorAtCompileTime >
::ReturnType operator* (const EigenBase< OtherDerived > &e) const
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
RotationMatrixType matrix () const
VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static const AngleAxis Identity ()
Protected Attributes
Vector3 m_axis
Scalar m_angle
Private Types
typedef RotationBase
< AngleAxis< _Scalar >, 3 > Base
typedef RotationBase
< AngleAxis< _Scalar >, 3 > Base
Friends
QuaternionType operator* (const QuaternionType &a, const AngleAxis &b)
Matrix3 operator* (const Matrix3 &a, const AngleAxis &b)
QuaternionType operator* (const QuaternionType &a, const AngleAxis &b)
Detailed Description
template<typename Scalar>
class Eigen::AngleAxis< Scalar >
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
Parameters
_Scalar the scalar type, i.e., the type of the coefficients.
The following two typedefs are provided for convenience:
AngleAxisf for float
AngleAxisd for double
AngleAxisForEuler How to define a rotation from Euler-angles
Combined with MatrixBase::Unit{X,Y,Z}, AngleAxis can be used to easily mimic Euler-angles. Here is an example:
Output:
Note
This class is not aimed to be used to store a rotation transformation, but rather to make easier the creation of other rotation (Quaternion, rotation Matrix) and transformation objects.
See Also
class Quaternion, class Transform, MatrixBase::UnitX()
Parameters
_Scalar the scalar type, i.e., the type of the coefficients.
Warning
When setting up an AngleAxis object, the axis vector must be normalized.
The following two typedefs are provided for convenience:
AngleAxisf for float
AngleAxisd for double
Combined with MatrixBase::Unit{X,Y,Z}, AngleAxis can be used to easily mimic Euler-angles. Here is an example:
Output:
Note
This class is not aimed to be used to store a rotation transformation, but rather to make easier the creation of other rotation (Quaternion, rotation Matrix) and transformation objects.
See Also
class Quaternion, class Transform, MatrixBase::UnitX()
Definition at line 236 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename Scalar> typedef RotationBase<AngleAxis<_Scalar>,3> Eigen::AngleAxis< Scalar >::Base private
Definition at line 48 of file AngleAxis.h.
template<typename Scalar> typedef RotationBase<AngleAxis<_Scalar>,3> Eigen::AngleAxis< Scalar >::Base private
Definition at line 51 of file AngleAxis.h.
template<typename Scalar> typedef Matrix<Scalar,3,3> Eigen::AngleAxis< Scalar >::Matrix3
Definition at line 57 of file AngleAxis.h.
template<typename Scalar> typedef Matrix<Scalar,3,3> Eigen::AngleAxis< Scalar >::Matrix3
Definition at line 60 of file AngleAxis.h.
template<typename Scalar> typedef Quaternion<Scalar> Eigen::AngleAxis< Scalar >::QuaternionType
Definition at line 59 of file AngleAxis.h.
template<typename Scalar> typedef Quaternion<Scalar> Eigen::AngleAxis< Scalar >::QuaternionType
Definition at line 62 of file AngleAxis.h.
template<typename Scalar> typedef _Scalar Eigen::AngleAxis< Scalar >::Scalar
the scalar type of the coefficients
Definition at line 56 of file AngleAxis.h.
template<typename Scalar> typedef _Scalar Eigen::AngleAxis< Scalar >::Scalar
the scalar type of the coefficients
Definition at line 59 of file AngleAxis.h.
template<typename Scalar> typedef Matrix<Scalar,3,1> Eigen::AngleAxis< Scalar >::Vector3
Definition at line 58 of file AngleAxis.h.
template<typename Scalar> typedef Matrix<Scalar,3,1> Eigen::AngleAxis< Scalar >::Vector3
Definition at line 61 of file AngleAxis.h.
Member Enumeration Documentation
template<typename Scalar> anonymous enum
Enumerator
Dim
Definition at line 54 of file AngleAxis.h.
template<typename Scalar> anonymous enum
Enumerator
Dim
Definition at line 57 of file AngleAxis.h.
Constructor & Destructor Documentation
template<typename Scalar> Eigen::AngleAxis< Scalar >::AngleAxis () inline
Default constructor without initialization.
Definition at line 69 of file AngleAxis.h.
Referenced by Eigen::AngleAxis< Scalar >::Identity(), and Eigen::AngleAxis< Scalar >::inverse().
template<typename Scalar> template<typename Derived > Eigen::AngleAxis< Scalar >::AngleAxis (Scalar angle, const MatrixBase< Derived > & axis) inline
Constructs and initialize the angle-axis rotation from an angle in radian and an axis which must be normalized.
Definition at line 73 of file AngleAxis.h.
template<typename Scalar> Eigen::AngleAxis< Scalar >::AngleAxis (const QuaternionType & q) inline
Constructs and initialize the angle-axis rotation from a quaternion q.
Definition at line 75 of file AngleAxis.h.
template<typename Scalar> template<typename Derived > Eigen::AngleAxis< Scalar >::AngleAxis (const MatrixBase< Derived > & m) inline explicit
Constructs and initialize the angle-axis rotation from a 3x3 rotation matrix.
Definition at line 78 of file AngleAxis.h.
template<typename Scalar> template<typename OtherScalarType > Eigen::AngleAxis< Scalar >::AngleAxis (const AngleAxis< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 133 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::angle(), Eigen::AngleAxis< Scalar >::axis(), Eigen::AngleAxis< Scalar >::m_angle, and Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> Eigen::AngleAxis< Scalar >::AngleAxis () inline
Default constructor without initialization.
Definition at line 72 of file AngleAxis.h.
template<typename Scalar> template<typename Derived > Eigen::AngleAxis< Scalar >::AngleAxis (Scalar angle, const MatrixBase< Derived > & axis) inline
Constructs and initialize the angle-axis rotation from an angle in radian and an axis which must be normalized.
Warning
If the axis vector is not normalized, then the angle-axis object represents an invalid rotation.
Definition at line 79 of file AngleAxis.h.
template<typename Scalar> template<typename QuatDerived > Eigen::AngleAxis< Scalar >::AngleAxis (const QuaternionBase< QuatDerived > & q) inline explicit
Constructs and initialize the angle-axis rotation from a quaternion q.
Definition at line 81 of file AngleAxis.h.
template<typename Scalar> template<typename Derived > Eigen::AngleAxis< Scalar >::AngleAxis (const MatrixBase< Derived > & m) inline explicit
Constructs and initialize the angle-axis rotation from a 3x3 rotation matrix.
Definition at line 84 of file AngleAxis.h.
template<typename Scalar> template<typename OtherScalarType > Eigen::AngleAxis< Scalar >::AngleAxis (const AngleAxis< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 128 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::angle(), Eigen::AngleAxis< Scalar >::axis(), Eigen::AngleAxis< Scalar >::m_angle, and Eigen::AngleAxis< Scalar >::m_axis.
Member Function Documentation
template<typename Scalar> Scalar Eigen::AngleAxis< Scalar >::angle () const inline
Definition at line 80 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_angle.
Referenced by Eigen::AngleAxis< Scalar >::AngleAxis(), Eigen::QuaternionBase< Derived >::operator=(), and Eigen::Quaternion< _Scalar >::operator=().
template<typename Scalar> Scalar& Eigen::AngleAxis< Scalar >::angle () inline
Definition at line 81 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_angle.
template<typename Scalar> Scalar Eigen::AngleAxis< Scalar >::angle () const inline
Definition at line 86 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_angle.
template<typename Scalar> Scalar& Eigen::AngleAxis< Scalar >::angle () inline
Definition at line 87 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_angle.
template<typename Scalar> const Vector3& Eigen::AngleAxis< Scalar >::axis () const inline
Definition at line 83 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_axis.
Referenced by Eigen::AngleAxis< Scalar >::AngleAxis(), Eigen::QuaternionBase< Derived >::operator=(), and Eigen::Quaternion< _Scalar >::operator=().
template<typename Scalar> Vector3& Eigen::AngleAxis< Scalar >::axis () inline
Definition at line 84 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> const Vector3& Eigen::AngleAxis< Scalar >::axis () const inline
Definition at line 89 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> Vector3& Eigen::AngleAxis< Scalar >::axis () inline
Definition at line 90 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> template<typename NewScalarType > internal::cast_return_type<AngleAxis,AngleAxis<NewScalarType> >::type Eigen::AngleAxis< Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 123 of file AngleAxis.h.
template<typename Scalar> template<typename NewScalarType > internal::cast_return_type<AngleAxis,AngleAxis<NewScalarType> >::type Eigen::AngleAxis< Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 128 of file AngleAxis.h.
template<typename Scalar> template<typename Derived > AngleAxis& Eigen::AngleAxis< Scalar >::fromRotationMatrix (const MatrixBase< Derived > & m)
template<typename Scalar> template<typename Derived > AngleAxis& Eigen::AngleAxis< Scalar >::fromRotationMatrix (const MatrixBase< Derived > & m)
template<typename Scalar> template<typename Derived > AngleAxis<Scalar>& Eigen::AngleAxis< Scalar >::fromRotationMatrix (const MatrixBase< Derived > & mat)
Sets *this from a 3x3 rotation matrix.
Definition at line 194 of file AngleAxis.h.
template<typename Scalar> static const AngleAxis Eigen::AngleAxis< Scalar >::Identity () inline static
Definition at line 134 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::AngleAxis().
template<typename Scalar> AngleAxis Eigen::AngleAxis< Scalar >::inverse (void) const inline
Returns
the inverse rotation, i.e., an angle-axis with opposite rotation angle
Definition at line 105 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::AngleAxis(), Eigen::AngleAxis< Scalar >::m_angle, and Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> AngleAxis Eigen::AngleAxis< Scalar >::inverse () const inline
Returns
the inverse rotation, i.e., an angle-axis with opposite rotation angle
Definition at line 111 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::AngleAxis(), Eigen::AngleAxis< Scalar >::m_angle, and Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> bool Eigen::AngleAxis< Scalar >::isApprox (const AngleAxis< Scalar > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 140 of file AngleAxis.h.
References Eigen::internal::isApprox(), Eigen::AngleAxis< Scalar >::m_angle, and Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> bool Eigen::AngleAxis< Scalar >::isApprox (const AngleAxis< Scalar > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 143 of file AngleAxis.h.
References Eigen::ei_isApprox(), Eigen::AngleAxis< Scalar >::m_angle, and Eigen::AngleAxis< Scalar >::m_axis.
template<typename Scalar> QuaternionType Eigen::AngleAxis< Scalar >::operator* (const AngleAxis< Scalar > & other) const inline
Concatenates two rotations
Definition at line 87 of file AngleAxis.h.
template<typename Scalar> QuaternionType Eigen::AngleAxis< Scalar >::operator* (const QuaternionType & other) const inline
Concatenates two rotations
Definition at line 91 of file AngleAxis.h.
template<typename Scalar> QuaternionType Eigen::AngleAxis< Scalar >::operator* (const AngleAxis< Scalar > & other) const inline
Concatenates two rotations
Definition at line 93 of file AngleAxis.h.
template<typename Scalar> QuaternionType Eigen::AngleAxis< Scalar >::operator* (const QuaternionType & other) const inline
Concatenates two rotations
Definition at line 97 of file AngleAxis.h.
template<typename Scalar> Matrix3 Eigen::AngleAxis< Scalar >::operator* (const Matrix3 & other) const inline
Concatenates two rotations
Definition at line 99 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::toRotationMatrix().
template<typename Scalar> Vector3 Eigen::AngleAxis< Scalar >::operator* (const Vector3 & other) const inline
Applies rotation to vector
Definition at line 107 of file AngleAxis.h.
References Eigen::AngleAxis< Scalar >::toRotationMatrix().
template<typename Scalar> template<class QuatDerived > AngleAxis& Eigen::AngleAxis< Scalar >::operator= (const QuaternionBase< QuatDerived > & q)
template<typename Scalar> template<typename Derived > AngleAxis& Eigen::AngleAxis< Scalar >::operator= (const MatrixBase< Derived > & m)
template<typename Scalar > AngleAxis< Scalar > & Eigen::AngleAxis< Scalar >::operator= (const QuaternionType & q)
Set *this from a quaternion. The axis is normalized.
Definition at line 158 of file AngleAxis.h.
References acos(), Eigen::ei_sqrt(), Eigen::Quaternion< _Scalar >::vec(), and Eigen::Quaternion< _Scalar >::w().
template<typename Scalar> template<typename Derived > AngleAxis& Eigen::AngleAxis< Scalar >::operator= (const MatrixBase< Derived > & m)
template<typename Scalar> template<typename QuatDerived > AngleAxis<Scalar>& Eigen::AngleAxis< Scalar >::operator= (const QuaternionBase< QuatDerived > & q)
Set *this from a unit quaternion. The axis is normalized.
Warning
As any other method dealing with quaternion, if the input quaternion is not normalized then the result is undefined.
Definition at line 159 of file AngleAxis.h.
References acos(), max(), min(), sqrt(), Eigen::QuaternionBase< Derived >::vec(), and Eigen::QuaternionBase< Derived >::w().
template<typename Scalar > template<typename Derived > AngleAxis< Scalar > & Eigen::AngleAxis< Scalar >::operator= (const MatrixBase< Derived > & mat)
Set *this from a 3x3 rotation matrix mat.
Definition at line 178 of file AngleAxis.h.
template<typename Scalar> Matrix3 Eigen::AngleAxis< Scalar >::toRotationMatrix (void) const
template<typename Scalar > AngleAxis< Scalar >::Matrix3 Eigen::AngleAxis< Scalar >::toRotationMatrix (void) const
Constructs and
Returns
an equivalent 3x3 rotation matrix.
Definition at line 189 of file AngleAxis.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::ei_cos(), and Eigen::ei_sin().
Referenced by Eigen::AngleAxis< Scalar >::operator*().
Friends And Related Function Documentation
template<typename Scalar> QuaternionType operator* (const QuaternionType & a, const AngleAxis< Scalar > & b) friend
Concatenates two rotations
Definition at line 95 of file AngleAxis.h.
template<typename Scalar> QuaternionType operator* (const QuaternionType & a, const AngleAxis< Scalar > & b) friend
Concatenates two rotations
Definition at line 101 of file AngleAxis.h.
template<typename Scalar> Matrix3 operator* (const Matrix3 & a, const AngleAxis< Scalar > & b) friend
Concatenates two rotations
Definition at line 103 of file AngleAxis.h.
Member Data Documentation
template<typename Scalar> Scalar Eigen::AngleAxis< Scalar >::m_angle protected
Definition at line 64 of file AngleAxis.h.
Referenced by Eigen::AngleAxis< Scalar >::angle(), Eigen::AngleAxis< Scalar >::AngleAxis(), Eigen::AngleAxis< Scalar >::inverse(), and Eigen::AngleAxis< Scalar >::isApprox().
template<typename Scalar> Vector3 Eigen::AngleAxis< Scalar >::m_axis protected
Definition at line 63 of file AngleAxis.h.
Referenced by Eigen::AngleAxis< Scalar >::AngleAxis(), Eigen::AngleAxis< Scalar >::axis(), Eigen::AngleAxis< Scalar >::inverse(), and Eigen::AngleAxis< Scalar >::isApprox().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Eigen2Support/Geometry/AngleAxis.h