LIA_RAL: Eigen::FullPivLU< MatrixType > Class Template Reference
Eigen::FullPivLU< MatrixType > Class Template Reference
LU decomposition of a matrix with complete pivoting, and related features.
#include <ForwardDeclarations.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, Options = MatrixType::Options, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename
MatrixType::Scalar >::Real RealScalar
typedef internal::traits
< MatrixType >::StorageKind StorageKind
typedef MatrixType::Index Index
typedef
internal::plain_row_type
< MatrixType, Index >::type IntRowVectorType
typedef
internal::plain_col_type
< MatrixType, Index >::type IntColVectorType
typedef PermutationMatrix
< ColsAtCompileTime,
MaxColsAtCompileTime > PermutationQType
typedef PermutationMatrix
< RowsAtCompileTime,
MaxRowsAtCompileTime > PermutationPType
Public Member Functions
FullPivLU ()
Default Constructor.
FullPivLU (Index rows, Index cols)
Default Constructor with memory preallocation.
FullPivLU (const MatrixType &matrix)
FullPivLU & compute (const MatrixType &matrix)
const MatrixType & matrixLU () const
Index nonzeroPivots () const
RealScalar maxPivot () const
const PermutationPType & permutationP () const
const PermutationQType & permutationQ () const
const internal::kernel_retval
< FullPivLU > kernel () const
const internal::image_retval
< FullPivLU > image (const MatrixType &originalMatrix) const
template<typename Rhs >
const internal::solve_retval
< FullPivLU, Rhs > solve (const MatrixBase< Rhs > &b) const
internal::traits< MatrixType >
::Scalar determinant () const
FullPivLU & setThreshold (const RealScalar &threshold)
FullPivLU & setThreshold (Default_t)
RealScalar threshold () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const internal::solve_retval
< FullPivLU, typename
MatrixType::IdentityReturnType > inverse () const
MatrixType reconstructedMatrix () const
Index rows () const
Index cols () const
Protected Attributes
MatrixType m_lu
PermutationPType m_p
PermutationQType m_q
IntColVectorType m_rowsTranspositions
IntRowVectorType m_colsTranspositions
Index m_det_pq
Index m_nonzero_pivots
RealScalar m_maxpivot
RealScalar m_prescribedThreshold
bool m_isInitialized
bool m_usePrescribedThreshold
Detailed Description
template<typename MatrixType>
class Eigen::FullPivLU< MatrixType >
LU decomposition of a matrix with complete pivoting, and related features.
Parameters
MatrixType the type of the matrix of which we are computing the LU decomposition
This class represents a LU decomposition of any matrix, with complete pivoting: the matrix A is decomposed as A = PLUQ where L is unit-lower-triangular, U is upper-triangular, and P and Q are permutation matrices. This is a rank-revealing LU decomposition. The eigenvalues (diagonal coefficients) of U are sorted in such a way that any zeros are at the end.
This decomposition provides the generic approach to solving systems of linear equations, computing the rank, invertibility, inverse, kernel, and determinant.
This LU decomposition is very stable and well tested with large matrices. However there are use cases where the SVD decomposition is inherently more stable and/or flexible. For example, when computing the kernel of a matrix, working with the SVD allows to select the smallest singular values of the matrix, something that the LU decomposition doesn't see.
The data of the LU decomposition can be directly accessed through the methods matrixLU(), permutationP(), permutationQ().
As an exemple, here is how the original matrix can be retrieved:
Output:
See Also
MatrixBase::fullPivLu(), MatrixBase::determinant(), MatrixBase::inverse()
Definition at line 217 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename MatrixType> typedef MatrixType::Index Eigen::FullPivLU< MatrixType >::Index
Definition at line 59 of file FullPivLU.h.
template<typename MatrixType> typedef internal::plain_col_type<MatrixType, Index>::type Eigen::FullPivLU< MatrixType >::IntColVectorType
Definition at line 61 of file FullPivLU.h.
template<typename MatrixType> typedef internal::plain_row_type<MatrixType, Index>::type Eigen::FullPivLU< MatrixType >::IntRowVectorType
Definition at line 60 of file FullPivLU.h.
template<typename MatrixType> typedef _MatrixType Eigen::FullPivLU< MatrixType >::MatrixType
Definition at line 48 of file FullPivLU.h.
template<typename MatrixType> typedef PermutationMatrix<RowsAtCompileTime, MaxRowsAtCompileTime> Eigen::FullPivLU< MatrixType >::PermutationPType
Definition at line 63 of file FullPivLU.h.
template<typename MatrixType> typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime> Eigen::FullPivLU< MatrixType >::PermutationQType
Definition at line 62 of file FullPivLU.h.
template<typename MatrixType> typedef NumTraits<typename MatrixType::Scalar>::Real Eigen::FullPivLU< MatrixType >::RealScalar
Definition at line 57 of file FullPivLU.h.
template<typename MatrixType> typedef MatrixType::Scalar Eigen::FullPivLU< MatrixType >::Scalar
Definition at line 56 of file FullPivLU.h.
template<typename MatrixType> typedef internal::traits<MatrixType>::StorageKind Eigen::FullPivLU< MatrixType >::StorageKind
Definition at line 58 of file FullPivLU.h.
Member Enumeration Documentation
template<typename MatrixType> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
Definition at line 49 of file FullPivLU.h.
Constructor & Destructor Documentation
template<typename MatrixType > Eigen::FullPivLU< MatrixType >::FullPivLU ()
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via LU::compute(const MatrixType&).
Definition at line 386 of file FullPivLU.h.
template<typename MatrixType > Eigen::FullPivLU< MatrixType >::FullPivLU (Index rows, Index cols)
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See Also
FullPivLU()
Definition at line 392 of file FullPivLU.h.
template<typename MatrixType> Eigen::FullPivLU< MatrixType >::FullPivLU (const MatrixType & matrix)
Constructor.
Parameters
matrix the matrix of which to compute the LU decomposition. It is required to be nonzero.
Definition at line 404 of file FullPivLU.h.
References Eigen::FullPivLU< MatrixType >::compute().
Member Function Documentation
template<typename MatrixType> Index Eigen::FullPivLU< MatrixType >::cols (void) const inline
Definition at line 372 of file FullPivLU.h.
Referenced by Eigen::LU< MatrixType >::computeInverse(), Eigen::FullPivLU< _MatrixType >::dimensionOfKernel(), and Eigen::FullPivLU< _MatrixType >::isInjective().
template<typename MatrixType> FullPivLU< MatrixType > & Eigen::FullPivLU< MatrixType >::compute (const MatrixType & matrix)
Computes the LU decomposition of the given matrix.
Parameters
matrix the matrix of which to compute the LU decomposition. It is required to be nonzero.
Returns
a reference to *this
Definition at line 417 of file FullPivLU.h.
References Eigen::FullPivLU< MatrixType >::rows().
Referenced by Eigen::FullPivLU< MatrixType >::FullPivLU().
template<typename MatrixType > internal::traits< MatrixType >::Scalar Eigen::FullPivLU< MatrixType >::determinant () const
Returns
the determinant of the matrix of which *this is the LU decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the LU decomposition has already been computed.
Note
This is only for square matrices.
For fixed-size matrices of size up to 4, MatrixBase::determinant() offers optimized paths.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow.
See Also
MatrixBase::determinant()
Definition at line 502 of file FullPivLU.h.
References eigen_assert.
template<typename MatrixType> Index Eigen::FullPivLU< MatrixType >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the LU decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 310 of file FullPivLU.h.
template<typename MatrixType> const internal::image_retval<FullPivLU> Eigen::FullPivLU< MatrixType >::image (const MatrixType & originalMatrix) const inline
Returns
the image of the matrix, also called its column-space. The columns of the returned matrix will form a basis of the kernel.
Parameters
originalMatrix the original matrix, of which *this is the LU decomposition. The reason why it is needed to pass it here, is that this allows a large optimization, as otherwise this method would need to reconstruct it from the LU decomposition.
Note
If the image has dimension zero, then the returned matrix is a column-vector filled with zeros.
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Example:
Output:
See Also
kernel()
Definition at line 187 of file FullPivLU.h.
template<typename MatrixType> const internal::solve_retval<FullPivLU,typename MatrixType::IdentityReturnType> Eigen::FullPivLU< MatrixType >::inverse (void) const inline
Returns
the inverse of the matrix of which *this is the LU decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
See Also
MatrixBase::inverse()
Definition at line 361 of file FullPivLU.h.
template<typename MatrixType> bool Eigen::FullPivLU< MatrixType >::isInjective () const inline
Returns
true if the matrix of which *this is the LU decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 323 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::isInvertible().
template<typename MatrixType> bool Eigen::FullPivLU< MatrixType >::isInvertible () const inline
Returns
true if the matrix of which *this is the LU decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 348 of file FullPivLU.h.
template<typename MatrixType> bool Eigen::FullPivLU< MatrixType >::isSurjective () const inline
Returns
true if the matrix of which *this is the LU decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 336 of file FullPivLU.h.
template<typename MatrixType> const internal::kernel_retval<FullPivLU> Eigen::FullPivLU< MatrixType >::kernel () const inline
Returns
the kernel of the matrix, also called its null-space. The columns of the returned matrix will form a basis of the kernel.
Note
If the kernel has dimension zero, then the returned matrix is a column-vector filled with zeros.
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Example:
Output:
See Also
image()
Definition at line 161 of file FullPivLU.h.
Referenced by Eigen::LU< MatrixType >::computeKernel().
template<typename MatrixType> const MatrixType& Eigen::FullPivLU< MatrixType >::matrixLU () const inline
Returns
the LU decomposition matrix: the upper-triangular part is U, the unit-lower-triangular part is L (at least for square matrices; in the non-square case, special care is needed, see the documentation of class FullPivLU).
See Also
matrixL(), matrixU()
Definition at line 103 of file FullPivLU.h.
template<typename MatrixType> RealScalar Eigen::FullPivLU< MatrixType >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
Definition at line 125 of file FullPivLU.h.
template<typename MatrixType> Index Eigen::FullPivLU< MatrixType >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the LU decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See Also
rank()
Definition at line 116 of file FullPivLU.h.
template<typename MatrixType> const PermutationPType& Eigen::FullPivLU< MatrixType >::permutationP () const inline
Returns
the permutation matrix P
See Also
permutationQ()
Definition at line 131 of file FullPivLU.h.
template<typename MatrixType> const PermutationQType& Eigen::FullPivLU< MatrixType >::permutationQ () const inline
Returns
the permutation matrix Q
See Also
permutationP()
Definition at line 141 of file FullPivLU.h.
template<typename MatrixType> Index Eigen::FullPivLU< MatrixType >::rank () const inline
Returns
the rank of the matrix of which *this is the LU decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Definition at line 294 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::dimensionOfKernel(), Eigen::FullPivLU< _MatrixType >::isInjective(), and Eigen::FullPivLU< _MatrixType >::isSurjective().
template<typename MatrixType > MatrixType Eigen::FullPivLU< MatrixType >::reconstructedMatrix () const
Returns
the matrix represented by the decomposition, i.e., it returns the product: P^{-1} L U Q^{-1}. This function is provided for debug purpose.
Definition at line 513 of file FullPivLU.h.
References eigen_assert, and min().
template<typename MatrixType> Index Eigen::FullPivLU< MatrixType >::rows (void) const inline
Definition at line 371 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< MatrixType >::compute(), Eigen::LU< MatrixType >::computeInverse(), and Eigen::FullPivLU< _MatrixType >::isSurjective().
template<typename MatrixType> FullPivLU& Eigen::FullPivLU< MatrixType >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the LU decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
Definition at line 254 of file FullPivLU.h.
template<typename MatrixType> FullPivLU& Eigen::FullPivLU< MatrixType >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
lu.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
Definition at line 269 of file FullPivLU.h.
template<typename MatrixType> template<typename Rhs > const internal::solve_retval<FullPivLU, Rhs> Eigen::FullPivLU< MatrixType >::solve (const MatrixBase< Rhs > & b) const inline
Returns
a solution x to the equation Ax=b, where A is the matrix of which *this is the LU decomposition.
Parameters
b the right-hand-side of the equation to solve. Can be a vector or a matrix, the only requirement in order for the equation to make sense is that b.rows()==A.rows(), where A is the matrix of which *this is the LU decomposition.
Returns
a solution.
Example:
Output:
See Also
TriangularView::solve(), kernel(), inverse()
Definition at line 214 of file FullPivLU.h.
template<typename MatrixType> RealScalar Eigen::FullPivLU< MatrixType >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
Definition at line 279 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::rank(), and Eigen::FullPivLU< _MatrixType >::setThreshold().
Member Data Documentation
template<typename MatrixType> IntRowVectorType Eigen::FullPivLU< MatrixType >::m_colsTranspositions protected
Definition at line 379 of file FullPivLU.h.
template<typename MatrixType> Index Eigen::FullPivLU< MatrixType >::m_det_pq protected
Definition at line 380 of file FullPivLU.h.
template<typename MatrixType> bool Eigen::FullPivLU< MatrixType >::m_isInitialized protected
Definition at line 382 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::dimensionOfKernel(), Eigen::FullPivLU< _MatrixType >::image(), Eigen::FullPivLU< _MatrixType >::inverse(), Eigen::FullPivLU< _MatrixType >::isInjective(), Eigen::FullPivLU< _MatrixType >::isInvertible(), Eigen::FullPivLU< _MatrixType >::isSurjective(), Eigen::FullPivLU< _MatrixType >::kernel(), Eigen::FullPivLU< _MatrixType >::matrixLU(), Eigen::FullPivLU< _MatrixType >::nonzeroPivots(), Eigen::FullPivLU< _MatrixType >::permutationP(), Eigen::FullPivLU< _MatrixType >::permutationQ(), Eigen::FullPivLU< _MatrixType >::rank(), Eigen::FullPivLU< _MatrixType >::solve(), and Eigen::FullPivLU< _MatrixType >::threshold().
template<typename MatrixType> MatrixType Eigen::FullPivLU< MatrixType >::m_lu protected
Definition at line 375 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::cols(), Eigen::FullPivLU< _MatrixType >::inverse(), Eigen::FullPivLU< _MatrixType >::isInvertible(), Eigen::FullPivLU< _MatrixType >::matrixLU(), Eigen::FullPivLU< _MatrixType >::rank(), Eigen::FullPivLU< _MatrixType >::rows(), and Eigen::FullPivLU< _MatrixType >::threshold().
template<typename MatrixType> RealScalar Eigen::FullPivLU< MatrixType >::m_maxpivot protected
Definition at line 381 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::maxPivot(), and Eigen::FullPivLU< _MatrixType >::rank().
template<typename MatrixType> Index Eigen::FullPivLU< MatrixType >::m_nonzero_pivots protected
Definition at line 380 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::nonzeroPivots(), and Eigen::FullPivLU< _MatrixType >::rank().
template<typename MatrixType> PermutationPType Eigen::FullPivLU< MatrixType >::m_p protected
Definition at line 376 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::permutationP().
template<typename MatrixType> RealScalar Eigen::FullPivLU< MatrixType >::m_prescribedThreshold protected
Definition at line 381 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::setThreshold(), and Eigen::FullPivLU< _MatrixType >::threshold().
template<typename MatrixType> PermutationQType Eigen::FullPivLU< MatrixType >::m_q protected
Definition at line 377 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::permutationQ().
template<typename MatrixType> IntColVectorType Eigen::FullPivLU< MatrixType >::m_rowsTranspositions protected
Definition at line 378 of file FullPivLU.h.
template<typename MatrixType> bool Eigen::FullPivLU< MatrixType >::m_usePrescribedThreshold protected
Definition at line 382 of file FullPivLU.h.
Referenced by Eigen::FullPivLU< _MatrixType >::setThreshold(), and Eigen::FullPivLU< _MatrixType >::threshold().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/LU/FullPivLU.h