LIA_RAL: Eigen::RotationBase< Derived, _Dim > Class Template Reference
Eigen::RotationBase< Derived, _Dim > Class Template Reference
Common base class for compact rotation representations.
#include <ForwardDeclarations.h>
Public Types
enum { Dim = _Dim }
enum { Dim = _Dim }
typedef ei_traits< Derived >
::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef internal::traits
< Derived >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
const Derived & derived () const
Derived & derived ()
RotationMatrixType toRotationMatrix () const
Derived inverse () const
Transform< Scalar, Dim > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const Scaling< Scalar, Dim > &s) const
Transform< Scalar, Dim > operator* (const Transform< Scalar, Dim > &t) const
const Derived & derived () const
Derived & derived ()
RotationMatrixType toRotationMatrix () const
RotationMatrixType matrix () const
Derived inverse () const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE
internal::rotation_base_generic_product_selector
< Derived, OtherDerived,
OtherDerived::IsVectorAtCompileTime >
::ReturnType operator* (const EigenBase< OtherDerived > &e) const
template<int Mode, int Options>
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<typename OtherVectorType >
VectorType _transformVector (const OtherVectorType &v) const
Friends
template<typename OtherDerived >
RotationMatrixType operator* (const EigenBase< OtherDerived > &l, const Derived &r)
Transform< Scalar, Dim, Affine > operator* (const DiagonalMatrix< Scalar, Dim > &l, const Derived &r)
Detailed Description
template<typename Derived, int _Dim>
class Eigen::RotationBase< Derived, _Dim >
Common base class for compact rotation representations.
Parameters
Derived is the derived type, i.e., a rotation type
_Dim the dimension of the space
Definition at line 232 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename Derived, int _Dim> typedef Matrix<Scalar,Dim,Dim> Eigen::RotationBase< Derived, _Dim >::RotationMatrixType
corresponding linear transformation matrix type
Definition at line 33 of file RotationBase.h.
template<typename Derived, int _Dim> typedef Matrix<Scalar,Dim,Dim> Eigen::RotationBase< Derived, _Dim >::RotationMatrixType
corresponding linear transformation matrix type
Definition at line 37 of file RotationBase.h.
template<typename Derived, int _Dim> typedef ei_traits<Derived>::Scalar Eigen::RotationBase< Derived, _Dim >::Scalar
the scalar type of the coefficients
Definition at line 30 of file RotationBase.h.
template<typename Derived, int _Dim> typedef internal::traits<Derived>::Scalar Eigen::RotationBase< Derived, _Dim >::Scalar
the scalar type of the coefficients
Definition at line 34 of file RotationBase.h.
template<typename Derived, int _Dim> typedef Matrix<Scalar,Dim,1> Eigen::RotationBase< Derived, _Dim >::VectorType
Definition at line 38 of file RotationBase.h.
Member Enumeration Documentation
template<typename Derived, int _Dim> anonymous enum
Enumerator
Dim
Definition at line 28 of file RotationBase.h.
template<typename Derived, int _Dim> anonymous enum
Enumerator
Dim
Definition at line 32 of file RotationBase.h.
Member Function Documentation
template<typename Derived, int _Dim> template<typename OtherVectorType > VectorType Eigen::RotationBase< Derived, _Dim >::_transformVector (const OtherVectorType & v) const inline
Definition at line 93 of file RotationBase.h.
template<typename Derived, int _Dim> const Derived& Eigen::RotationBase< Derived, _Dim >::derived () const inline
Definition at line 35 of file RotationBase.h.
Referenced by Eigen::RotationBase< Derived, 3 >::inverse(), Eigen::RotationBase< Derived, 3 >::matrix(), Eigen::RotationBase< Derived, 3 >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator*(), and Eigen::RotationBase< Derived, 3 >::toRotationMatrix().
template<typename Derived, int _Dim> Derived& Eigen::RotationBase< Derived, _Dim >::derived () inline
Definition at line 36 of file RotationBase.h.
template<typename Derived, int _Dim> const Derived& Eigen::RotationBase< Derived, _Dim >::derived () const inline
Definition at line 41 of file RotationBase.h.
template<typename Derived, int _Dim> Derived& Eigen::RotationBase< Derived, _Dim >::derived () inline
Definition at line 42 of file RotationBase.h.
template<typename Derived, int _Dim> Derived Eigen::RotationBase< Derived, _Dim >::inverse (void) const inline
Returns
the inverse rotation
Definition at line 42 of file RotationBase.h.
template<typename Derived, int _Dim> Derived Eigen::RotationBase< Derived, _Dim >::inverse (void) const inline
Returns
the inverse rotation
Definition at line 53 of file RotationBase.h.
template<typename Derived, int _Dim> RotationMatrixType Eigen::RotationBase< Derived, _Dim >::matrix () const inline
Returns
an equivalent rotation matrix This function is added to be conform with the Transform class' naming scheme.
Definition at line 50 of file RotationBase.h.
template<typename Derived, int _Dim> Transform<Scalar,Dim> Eigen::RotationBase< Derived, _Dim >::operator* (const Translation< Scalar, Dim > & t) const inline
Returns
the concatenation of the rotation *this with a translation t
Definition at line 45 of file RotationBase.h.
template<typename Derived, int _Dim> RotationMatrixType Eigen::RotationBase< Derived, _Dim >::operator* (const Scaling< Scalar, Dim > & s) const inline
Returns
the concatenation of the rotation *this with a scaling s
Definition at line 49 of file RotationBase.h.
template<typename Derived, int _Dim> Transform<Scalar,Dim> Eigen::RotationBase< Derived, _Dim >::operator* (const Transform< Scalar, Dim > & t) const inline
Returns
the concatenation of the rotation *this with an affine transformation t
Definition at line 53 of file RotationBase.h.
template<typename Derived, int _Dim> Transform<Scalar,Dim,Isometry> Eigen::RotationBase< Derived, _Dim >::operator* (const Translation< Scalar, Dim > & t) const inline
Returns
the concatenation of the rotation *this with a translation t
Definition at line 56 of file RotationBase.h.
template<typename Derived, int _Dim> RotationMatrixType Eigen::RotationBase< Derived, _Dim >::operator* (const UniformScaling< Scalar > & s) const inline
Returns
the concatenation of the rotation *this with a uniform scaling s
Definition at line 60 of file RotationBase.h.
template<typename Derived, int _Dim> template<typename OtherDerived > EIGEN_STRONG_INLINE internal::rotation_base_generic_product_selector<Derived,OtherDerived,OtherDerived::IsVectorAtCompileTime>::ReturnType Eigen::RotationBase< Derived, _Dim >::operator* (const EigenBase< OtherDerived > & e) const inline
Returns
the concatenation of the rotation *this with a generic expression e e can be:
a DimxDim linear transformation matrix
a DimxDim diagonal matrix (axis aligned scaling)
a vector of size Dim
Definition at line 71 of file RotationBase.h.
template<typename Derived, int _Dim> template<int Mode, int Options> Transform<Scalar,Dim,Mode> Eigen::RotationBase< Derived, _Dim >::operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline
Returns
the concatenation of the rotation *this with a transformation t
Definition at line 89 of file RotationBase.h.
template<typename Derived, int _Dim> RotationMatrixType Eigen::RotationBase< Derived, _Dim >::toRotationMatrix (void) const inline
Returns
an equivalent rotation matrix
Definition at line 39 of file RotationBase.h.
Referenced by Eigen::RotationBase< Derived, 3 >::_transformVector(), Eigen::RotationBase< Derived, 3 >::operator*(), Eigen::UniformScaling< _Scalar >::operator*(), Eigen::Translation< Scalar, Dim >::operator*(), Eigen::Scaling< _Scalar, _Dim >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator*=(), and Eigen::internal::toRotationMatrix().
template<typename Derived, int _Dim> RotationMatrixType Eigen::RotationBase< Derived, _Dim >::toRotationMatrix (void) const inline
Returns
an equivalent rotation matrix
Definition at line 45 of file RotationBase.h.
Friends And Related Function Documentation
template<typename Derived, int _Dim> template<typename OtherDerived > RotationMatrixType operator* (const EigenBase< OtherDerived > & l, const Derived & r) friend
Returns
the concatenation of a linear transformation l with the rotation r
Definition at line 76 of file RotationBase.h.
template<typename Derived, int _Dim> Transform<Scalar,Dim,Affine> operator* (const DiagonalMatrix< Scalar, Dim > & l, const Derived & r) friend
Returns
the concatenation of a scaling l with the rotation r
Definition at line 80 of file RotationBase.h.
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Eigen2Support/Geometry/RotationBase.h