LIA_RAL: Eigen::Rotation2D< Scalar > Class Template Reference
Eigen::Rotation2D< Scalar > Class Template Reference
Geometry_Module
Represents a rotation/orientation in a 2 dimensional space.
#include <ForwardDeclarations.h>
Public Types
enum { Dim = 2 }
enum { Dim = 2 }
typedef _Scalar Scalar
typedef Matrix< Scalar, 2, 1 > Vector2
typedef Matrix< Scalar, 2, 2 > Matrix2
typedef _Scalar Scalar
typedef Matrix< Scalar, 2, 1 > Vector2
typedef Matrix< Scalar, 2, 2 > Matrix2
Public Types inherited from Eigen::RotationBase< Rotation2D< _Scalar >, 2 >
enum
enum
typedef ei_traits< Rotation2D
< _Scalar > >::Scalar Scalar
typedef internal::traits
< Rotation2D< _Scalar >
>::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
Rotation2D (Scalar a)
Scalar angle () const
Scalar & angle ()
Rotation2D inverse () const
Rotation2D operator* (const Rotation2D &other) const
Rotation2D & operator*= (const Rotation2D &other)
Vector2 operator* (const Vector2 &vec) const
template<typename Derived >
Rotation2D & fromRotationMatrix (const MatrixBase< Derived > &m)
Matrix2 toRotationMatrix (void) const
Rotation2D slerp (Scalar t, const Rotation2D &other) const
template<typename NewScalarType >
internal::cast_return_type
< Rotation2D, Rotation2D
< NewScalarType > >::type cast () const
template<typename OtherScalarType >
Rotation2D (const Rotation2D< OtherScalarType > &other)
bool isApprox (const Rotation2D &other, typename NumTraits< Scalar >::Real prec=precision< Scalar >()) const
Rotation2D (Scalar a)
Scalar angle () const
Scalar & angle ()
Rotation2D inverse () const
Rotation2D operator* (const Rotation2D &other) const
Rotation2D & operator*= (const Rotation2D &other)
Vector2 operator* (const Vector2 &vec) const
template<typename Derived >
Rotation2D & fromRotationMatrix (const MatrixBase< Derived > &m)
Matrix2 toRotationMatrix (void) const
Rotation2D slerp (Scalar t, const Rotation2D &other) const
template<typename NewScalarType >
internal::cast_return_type
< Rotation2D, Rotation2D
< NewScalarType > >::type cast () const
template<typename OtherScalarType >
Rotation2D (const Rotation2D< OtherScalarType > &other)
bool isApprox (const Rotation2D &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
Rotation2D< Scalar > & fromRotationMatrix (const MatrixBase< Derived > &mat)
Public Member Functions inherited from Eigen::RotationBase< Rotation2D< _Scalar >, 2 >
const Rotation2D< _Scalar > & derived () const
Rotation2D< _Scalar > & derived ()
const Rotation2D< _Scalar > & derived () const
Rotation2D< _Scalar > & derived ()
RotationMatrixType toRotationMatrix () const
RotationMatrixType toRotationMatrix () const
Rotation2D< _Scalar > inverse () const
Rotation2D< _Scalar > inverse () const
Transform< Scalar, Dim > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const Scaling< Scalar, Dim > &s) const
Transform< Scalar, Dim > operator* (const Transform< Scalar, Dim > &t) const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
EIGEN_STRONG_INLINE
internal::rotation_base_generic_product_selector
< Rotation2D< _Scalar >
, OtherDerived,
OtherDerived::IsVectorAtCompileTime >
::ReturnType operator* (const EigenBase< OtherDerived > &e) const
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
RotationMatrixType matrix () const
VectorType _transformVector (const OtherVectorType &v) const
Static Public Member Functions
static Rotation2D Identity ()
Protected Attributes
Scalar m_angle
Private Types
typedef RotationBase
< Rotation2D< _Scalar >, 2 > Base
typedef RotationBase
< Rotation2D< _Scalar >, 2 > Base
Detailed Description
template<typename Scalar>
class Eigen::Rotation2D< Scalar >
Represents a rotation/orientation in a 2 dimensional space.
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
This class is equivalent to a single scalar representing a counter clock wise rotation as a single angle in radian. It provides some additional features such as the automatic conversion from/to a 2x2 rotation matrix. Moreover this class aims to provide a similar interface to Quaternion in order to facilitate the writing of generic algorithms dealing with rotations.
See Also
class Quaternion, class Transform
Definition at line 235 of file ForwardDeclarations.h.
Member Typedef Documentation
template<typename Scalar> typedef RotationBase<Rotation2D<_Scalar>,2> Eigen::Rotation2D< Scalar >::Base private
Definition at line 38 of file Rotation2D.h.
template<typename Scalar> typedef RotationBase<Rotation2D<_Scalar>,2> Eigen::Rotation2D< Scalar >::Base private
Definition at line 43 of file Rotation2D.h.
template<typename Scalar> typedef Matrix<Scalar,2,2> Eigen::Rotation2D< Scalar >::Matrix2
Definition at line 48 of file Rotation2D.h.
template<typename Scalar> typedef Matrix<Scalar,2,2> Eigen::Rotation2D< Scalar >::Matrix2
Definition at line 53 of file Rotation2D.h.
template<typename Scalar> typedef _Scalar Eigen::Rotation2D< Scalar >::Scalar
the scalar type of the coefficients
Definition at line 46 of file Rotation2D.h.
template<typename Scalar> typedef _Scalar Eigen::Rotation2D< Scalar >::Scalar
the scalar type of the coefficients
Definition at line 51 of file Rotation2D.h.
template<typename Scalar> typedef Matrix<Scalar,2,1> Eigen::Rotation2D< Scalar >::Vector2
Definition at line 47 of file Rotation2D.h.
template<typename Scalar> typedef Matrix<Scalar,2,1> Eigen::Rotation2D< Scalar >::Vector2
Definition at line 52 of file Rotation2D.h.
Member Enumeration Documentation
template<typename Scalar> anonymous enum
Enumerator
Dim
Definition at line 44 of file Rotation2D.h.
template<typename Scalar> anonymous enum
Enumerator
Dim
Definition at line 49 of file Rotation2D.h.
Constructor & Destructor Documentation
template<typename Scalar> Eigen::Rotation2D< Scalar >::Rotation2D (Scalar a) inline
Construct a 2D counter clock wise rotation from the angle a in radian.
Definition at line 57 of file Rotation2D.h.
Referenced by Eigen::Rotation2D< Scalar >::Identity().
template<typename Scalar> template<typename OtherScalarType > Eigen::Rotation2D< Scalar >::Rotation2D (const Rotation2D< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 101 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::angle(), and Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Eigen::Rotation2D< Scalar >::Rotation2D (Scalar a) inline
Construct a 2D counter clock wise rotation from the angle a in radian.
Definition at line 62 of file Rotation2D.h.
template<typename Scalar> template<typename OtherScalarType > Eigen::Rotation2D< Scalar >::Rotation2D (const Rotation2D< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
Definition at line 106 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::angle(), and Eigen::Rotation2D< Scalar >::m_angle.
Member Function Documentation
template<typename Scalar> Scalar Eigen::Rotation2D< Scalar >::angle () const inline
Returns
the rotation angle
Definition at line 60 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
Referenced by Eigen::Rotation2D< Scalar >::Rotation2D(), and Eigen::Rotation2D< Scalar >::slerp().
template<typename Scalar> Scalar& Eigen::Rotation2D< Scalar >::angle () inline
Returns
a read-write reference to the rotation angle
Definition at line 63 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Scalar Eigen::Rotation2D< Scalar >::angle () const inline
Returns
the rotation angle
Definition at line 65 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Scalar& Eigen::Rotation2D< Scalar >::angle () inline
Returns
a read-write reference to the rotation angle
Definition at line 68 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> template<typename NewScalarType > internal::cast_return_type<Rotation2D,Rotation2D<NewScalarType> >::type Eigen::Rotation2D< Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 96 of file Rotation2D.h.
template<typename Scalar> template<typename NewScalarType > internal::cast_return_type<Rotation2D,Rotation2D<NewScalarType> >::type Eigen::Rotation2D< Scalar >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
Definition at line 101 of file Rotation2D.h.
template<typename Scalar> template<typename Derived > Rotation2D& Eigen::Rotation2D< Scalar >::fromRotationMatrix (const MatrixBase< Derived > & m)
template<typename Scalar> template<typename Derived > Rotation2D& Eigen::Rotation2D< Scalar >::fromRotationMatrix (const MatrixBase< Derived > & m)
template<typename Scalar > template<typename Derived > Rotation2D< Scalar > & Eigen::Rotation2D< Scalar >::fromRotationMatrix (const MatrixBase< Derived > & mat)
Set *this from a 2x2 rotation matrix mat. In other words, this function extract the rotation angle from the rotation matrix.
Definition at line 127 of file Rotation2D.h.
References Eigen::ei_atan2(), and EIGEN_STATIC_ASSERT.
template<typename Scalar> static Rotation2D Eigen::Rotation2D< Scalar >::Identity () inline static
Definition at line 111 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::Rotation2D().
template<typename Scalar> Rotation2D Eigen::Rotation2D< Scalar >::inverse (void) const inline
Returns
the inverse rotation
Definition at line 66 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Rotation2D Eigen::Rotation2D< Scalar >::inverse (void) const inline
Returns
the inverse rotation
Definition at line 71 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> bool Eigen::Rotation2D< Scalar >::isApprox (const Rotation2D< Scalar > & other, typename NumTraits< Scalar >::Real prec = precision<Scalar>()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 110 of file Rotation2D.h.
References Eigen::ei_isApprox(), and Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> bool Eigen::Rotation2D< Scalar >::isApprox (const Rotation2D< Scalar > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
Definition at line 117 of file Rotation2D.h.
References Eigen::internal::isApprox(), and Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Rotation2D Eigen::Rotation2D< Scalar >::operator* (const Rotation2D< Scalar > & other) const inline
Concatenates two rotations
Definition at line 69 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Rotation2D Eigen::Rotation2D< Scalar >::operator* (const Rotation2D< Scalar > & other) const inline
Concatenates two rotations
Definition at line 74 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Vector2 Eigen::Rotation2D< Scalar >::operator* (const Vector2 & vec) const inline
Applies the rotation to a 2D vector
Definition at line 77 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::toRotationMatrix().
template<typename Scalar> Vector2 Eigen::Rotation2D< Scalar >::operator* (const Vector2 & vec) const inline
Applies the rotation to a 2D vector
Definition at line 82 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::toRotationMatrix().
template<typename Scalar> Rotation2D& Eigen::Rotation2D< Scalar >::operator*= (const Rotation2D< Scalar > & other) inline
Concatenates two rotations
Definition at line 73 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Rotation2D& Eigen::Rotation2D< Scalar >::operator*= (const Rotation2D< Scalar > & other) inline
Concatenates two rotations
Definition at line 78 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Rotation2D Eigen::Rotation2D< Scalar >::slerp (Scalar t, const Rotation2D< Scalar > & other) const inline
Returns
the spherical interpolation between *this and other using parameter t. It is in fact equivalent to a linear interpolation.
Definition at line 87 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::angle(), and Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar> Rotation2D Eigen::Rotation2D< Scalar >::slerp (Scalar t, const Rotation2D< Scalar > & other) const inline
Returns
the spherical interpolation between *this and other using parameter t. It is in fact equivalent to a linear interpolation.
Definition at line 92 of file Rotation2D.h.
References Eigen::Rotation2D< Scalar >::angle(), and Eigen::Rotation2D< Scalar >::m_angle.
template<typename Scalar > Rotation2D< Scalar >::Matrix2 Eigen::Rotation2D< Scalar >::toRotationMatrix (void) const
Constructs and
Returns
an equivalent 2x2 rotation matrix.
Definition at line 138 of file Rotation2D.h.
References Eigen::ei_cos(), and Eigen::ei_sin().
Referenced by Eigen::Rotation2D< Scalar >::operator*().
template<typename Scalar> Matrix2 Eigen::Rotation2D< Scalar >::toRotationMatrix (void) const
Member Data Documentation
template<typename Scalar> Scalar Eigen::Rotation2D< Scalar >::m_angle protected
Definition at line 52 of file Rotation2D.h.
Referenced by Eigen::Rotation2D< Scalar >::angle(), Eigen::Rotation2D< Scalar >::inverse(), Eigen::Rotation2D< Scalar >::isApprox(), Eigen::Rotation2D< Scalar >::operator*(), Eigen::Rotation2D< Scalar >::operator*=(), Eigen::Rotation2D< Scalar >::Rotation2D(), and Eigen::Rotation2D< Scalar >::slerp().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/util/ForwardDeclarations.h
include/Eigen/src/Eigen2Support/Geometry/Rotation2D.h