LIA_RAL: Eigen::DenseCoeffsBase< Derived, WriteAccessors > Class Template Reference
Eigen::DenseCoeffsBase< Derived, WriteAccessors > Class Template Reference
Base class providing read/write coefficient access to matrices and arrays.
#include <DenseCoeffsBase.h>
Public Types
typedef DenseCoeffsBase
< Derived, ReadOnlyAccessors > Base
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
typedef internal::traits
< Derived >::Scalar Scalar
typedef
internal::packet_traits
< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
Public Types inherited from Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
typedef internal::traits
< Derived >::Scalar Scalar
typedef
internal::packet_traits
< Scalar >::type PacketScalar
typedef internal::conditional
< bool(internal::traits
< Derived >::Flags &LvalueBit),
const Scalar &, typename
internal::conditional
< internal::is_arithmetic
< Scalar >::value, Scalar,
const Scalar >::type >::type CoeffReturnType
typedef
internal::add_const_on_value_type_if_arithmetic
< typename
internal::packet_traits
< Scalar >::type >::type PacketReturnType
typedef EigenBase< Derived > Base
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_STRONG_INLINE Scalar & coeffRefByOuterInner (Index outer, Index inner)
EIGEN_STRONG_INLINE Scalar & operator() (Index row, Index col)
EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_STRONG_INLINE Scalar & operator[] (Index index)
EIGEN_STRONG_INLINE Scalar & operator() (Index index)
EIGEN_STRONG_INLINE Scalar & x ()
EIGEN_STRONG_INLINE Scalar & y ()
EIGEN_STRONG_INLINE Scalar & z ()
EIGEN_STRONG_INLINE Scalar & w ()
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const typename internal::packet_traits< Scalar >::type &x)
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacketByOuterInner (Index outer, Index inner, const typename internal::packet_traits< Scalar >::type &x)
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacket (Index index, const typename internal::packet_traits< Scalar >::type &x)
template<typename OtherDerived >
EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE void copyCoeff (Index index, const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE void copyCoeffByOuterInner (Index outer, Index inner, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
EIGEN_STRONG_INLINE void copyPacket (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
EIGEN_STRONG_INLINE void copyPacket (Index index, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
EIGEN_STRONG_INLINE void copyPacketByOuterInner (Index outer, Index inner, const DenseBase< OtherDerived > &other)
Public Member Functions inherited from Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >
EIGEN_STRONG_INLINE Index rowIndexByOuterInner (Index outer, Index inner) const
EIGEN_STRONG_INLINE Index colIndexByOuterInner (Index outer, Index inner) const
EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_STRONG_INLINE CoeffReturnType coeffByOuterInner (Index outer, Index inner) const
EIGEN_STRONG_INLINE CoeffReturnType operator() (Index row, Index col) const
EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_STRONG_INLINE CoeffReturnType operator[] (Index index) const
EIGEN_STRONG_INLINE CoeffReturnType operator() (Index index) const
EIGEN_STRONG_INLINE CoeffReturnType x () const
EIGEN_STRONG_INLINE CoeffReturnType y () const
EIGEN_STRONG_INLINE CoeffReturnType z () const
EIGEN_STRONG_INLINE CoeffReturnType w () const
template<int LoadMode>
EIGEN_STRONG_INLINE
PacketReturnType packet (Index row, Index col) const
template<int LoadMode>
EIGEN_STRONG_INLINE
PacketReturnType packetByOuterInner (Index outer, Index inner) const
template<int LoadMode>
EIGEN_STRONG_INLINE
PacketReturnType packet (Index index) const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Additional Inherited Members
Protected Member Functions inherited from Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >
void coeffRef ()
void coeffRefByOuterInner ()
void writePacket ()
void writePacketByOuterInner ()
void copyCoeff ()
void copyCoeffByOuterInner ()
void copyPacket ()
void copyPacketByOuterInner ()
void stride ()
void innerStride ()
void outerStride ()
void rowStride ()
void colStride ()
Detailed Description
template<typename Derived>
class Eigen::DenseCoeffsBase< Derived, WriteAccessors >
Base class providing read/write coefficient access to matrices and arrays.
Template Parameters
Derived Type of the derived class
WriteAccessors Constant indicating read/write access
This class defines the non-const operator() function and friends, which can be used to write specific entries of a matrix or array. This class inherits DenseCoeffsBase<Derived, ReadOnlyAccessors> which defines the const variant for reading specific entries.
See Also
DenseCoeffsBase<Derived, DirectAccessors>, TopicClassHierarchy
Definition at line 274 of file DenseCoeffsBase.h.
Member Typedef Documentation
template<typename Derived > typedef DenseCoeffsBase<Derived, ReadOnlyAccessors> Eigen::DenseCoeffsBase< Derived, WriteAccessors >::Base
Definition at line 278 of file DenseCoeffsBase.h.
template<typename Derived > typedef internal::traits<Derived>::Index Eigen::DenseCoeffsBase< Derived, WriteAccessors >::Index
Definition at line 281 of file DenseCoeffsBase.h.
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::DenseCoeffsBase< Derived, WriteAccessors >::PacketScalar
Definition at line 283 of file DenseCoeffsBase.h.
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::DenseCoeffsBase< Derived, WriteAccessors >::RealScalar
Definition at line 284 of file DenseCoeffsBase.h.
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::DenseCoeffsBase< Derived, WriteAccessors >::Scalar
Definition at line 282 of file DenseCoeffsBase.h.
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::DenseCoeffsBase< Derived, WriteAccessors >::StorageKind
Definition at line 280 of file DenseCoeffsBase.h.
Member Function Documentation
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRef (Index row, Index col) inline
Short version: don't use this function, use operator()(Index,Index) instead.
Long version: this function is similar to operator()(Index,Index), but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameters row and col are in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator()(Index,Index).
See Also
operator()(Index,Index), coeff(Index, Index) const, coeffRef(Index)
Definition at line 314 of file DenseCoeffsBase.h.
References eigen_internal_assert.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRef (Index index) inline
Short version: don't use this function, use operator[](Index) instead.
Long version: this function is similar to operator[](Index), but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameters row and col are in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator[](Index).
See Also
operator[](Index), coeff(Index) const, coeffRef(Index,Index)
Definition at line 358 of file DenseCoeffsBase.h.
References eigen_internal_assert.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRefByOuterInner (Index outer, Index inner) inline
Definition at line 322 of file DenseCoeffsBase.h.
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyCoeff (Index row, Index col, const DenseBase< OtherDerived > & other) inline
Definition at line 476 of file DenseCoeffsBase.h.
References eigen_internal_assert.
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyCoeff (Index index, const DenseBase< OtherDerived > & other) inline
Definition at line 492 of file DenseCoeffsBase.h.
References eigen_internal_assert.
template<typename Derived > template<typename OtherDerived > EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyCoeffByOuterInner (Index outer, Index inner, const DenseBase< OtherDerived > & other) inline
Definition at line 500 of file DenseCoeffsBase.h.
template<typename Derived > template<typename OtherDerived , int StoreMode, int LoadMode> EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyPacket (Index row, Index col, const DenseBase< OtherDerived > & other) inline
Definition at line 517 of file DenseCoeffsBase.h.
References col(), eigen_internal_assert, and row().
template<typename Derived > template<typename OtherDerived , int StoreMode, int LoadMode> EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyPacket (Index index, const DenseBase< OtherDerived > & other) inline
Definition at line 534 of file DenseCoeffsBase.h.
References eigen_internal_assert.
template<typename Derived > template<typename OtherDerived , int StoreMode, int LoadMode> EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::copyPacketByOuterInner (Index outer, Index inner, const DenseBase< OtherDerived > & other) inline
Definition at line 543 of file DenseCoeffsBase.h.
References col(), and row().
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator() (Index row, Index col) inline
Returns
a reference to the coefficient at given the given row and column.
See Also
operator[](Index)
Definition at line 334 of file DenseCoeffsBase.h.
References eigen_assert.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator() (Index index) inline
Returns
a reference to the coefficient at given index.
This is synonymous to operator[](Index).
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See Also
operator[](Index) const, operator()(Index,Index), x(), y(), z(), w()
Definition at line 392 of file DenseCoeffsBase.h.
References eigen_assert.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator[] (Index index) inline
Returns
a reference to the coefficient at given index.
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See Also
operator[](Index) const, operator()(Index,Index), x(), y(), z(), w()
Definition at line 372 of file DenseCoeffsBase.h.
References eigen_assert, and EIGEN_STATIC_ASSERT.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::w () inline
equivalent to operator[](3).
Definition at line 416 of file DenseCoeffsBase.h.
template<typename Derived > template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::writePacket (Index row, Index col, const typename internal::packet_traits< Scalar >::type & x) inline
Definition at line 430 of file DenseCoeffsBase.h.
References col(), eigen_internal_assert, and row().
template<typename Derived > template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::writePacket (Index index, const typename internal::packet_traits< Scalar >::type & x) inline
Definition at line 459 of file DenseCoeffsBase.h.
References eigen_internal_assert.
template<typename Derived > template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::DenseCoeffsBase< Derived, WriteAccessors >::writePacketByOuterInner (Index outer, Index inner, const typename internal::packet_traits< Scalar >::type & x) inline
Definition at line 441 of file DenseCoeffsBase.h.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::x () inline
equivalent to operator[](0).
Definition at line 401 of file DenseCoeffsBase.h.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::y () inline
equivalent to operator[](1).
Definition at line 406 of file DenseCoeffsBase.h.
template<typename Derived > EIGEN_STRONG_INLINE Scalar& Eigen::DenseCoeffsBase< Derived, WriteAccessors >::z () inline
equivalent to operator[](2).
Definition at line 411 of file DenseCoeffsBase.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/DenseCoeffsBase.h