LIA_RAL: Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs > Class Template Reference
Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs > Class Template Reference
#include <SelfCwiseBinaryOp.h>
Public Types
typedef
internal::dense_xpr_base
< SelfCwiseBinaryOp >::type Base
typedef
internal::packet_traits
< Scalar >::type Packet
Public Member Functions
SelfCwiseBinaryOp (Lhs &xpr, const BinaryOp &func=BinaryOp())
Index rows () const
Index cols () const
Index outerStride () const
Index innerStride () const
const Scalar * data () const
Scalar & coeffRef (Index row, Index col)
const Scalar & coeffRef (Index row, Index col) const
Scalar & coeffRef (Index index)
const Scalar & coeffRef (Index index) const
template<typename OtherDerived >
void copyCoeff (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
void copyCoeff (Index index, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index index, const DenseBase< OtherDerived > &other)
template<typename RhsDerived >
EIGEN_STRONG_INLINE
SelfCwiseBinaryOp & lazyAssign (const DenseBase< RhsDerived > &rhs)
SelfCwiseBinaryOp & operator= (const Rhs &_rhs)
Lhs & expression () const
const BinaryOp & functor () const
Protected Attributes
Lhs & m_matrix
const BinaryOp & m_functor
Private Member Functions
SelfCwiseBinaryOp & operator= (const SelfCwiseBinaryOp &)
Detailed Description
template<typename BinaryOp, typename Lhs, typename Rhs>
class Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >
Definition at line 45 of file SelfCwiseBinaryOp.h.
Member Typedef Documentation
template<typename BinaryOp, typename Lhs, typename Rhs> typedef internal::dense_xpr_base<SelfCwiseBinaryOp>::type Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::Base
Definition at line 50 of file SelfCwiseBinaryOp.h.
template<typename BinaryOp, typename Lhs, typename Rhs> typedef internal::packet_traits<Scalar>::type Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::Packet
Definition at line 53 of file SelfCwiseBinaryOp.h.
Constructor & Destructor Documentation
template<typename BinaryOp, typename Lhs, typename Rhs> Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::SelfCwiseBinaryOp (Lhs & xpr, const BinaryOp & func = BinaryOp()) inline
Definition at line 55 of file SelfCwiseBinaryOp.h.
Member Function Documentation
template<typename BinaryOp, typename Lhs, typename Rhs> Scalar& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::coeffRef (Index row, Index col) inline
Definition at line 65 of file SelfCwiseBinaryOp.h.
References EIGEN_STATIC_ASSERT_LVALUE, and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> const Scalar& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::coeffRef (Index row, Index col) const inline
Definition at line 70 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> Scalar& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::coeffRef (Index index) inline
Definition at line 77 of file SelfCwiseBinaryOp.h.
References EIGEN_STATIC_ASSERT_LVALUE, and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> const Scalar& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::coeffRef (Index index) const inline
Definition at line 82 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> Index Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols (void) const inline
Definition at line 58 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Referenced by Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::lazyAssign().
template<typename BinaryOp, typename Lhs, typename Rhs> template<typename OtherDerived > void Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff (Index row, Index col, const DenseBase< OtherDerived > & other) inline
Definition at line 88 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), eigen_internal_assert, Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix, and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
template<typename BinaryOp, typename Lhs, typename Rhs> template<typename OtherDerived > void Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff (Index index, const DenseBase< OtherDerived > & other) inline
Definition at line 98 of file SelfCwiseBinaryOp.h.
References eigen_internal_assert, Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> template<typename OtherDerived , int StoreMode, int LoadMode> void Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket (Index row, Index col, const DenseBase< OtherDerived > & other) inline
Definition at line 107 of file SelfCwiseBinaryOp.h.
References col(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), eigen_internal_assert, Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix, row(), and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
template<typename BinaryOp, typename Lhs, typename Rhs> template<typename OtherDerived , int StoreMode, int LoadMode> void Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket (Index index, const DenseBase< OtherDerived > & other) inline
Definition at line 117 of file SelfCwiseBinaryOp.h.
References eigen_internal_assert, Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> const Scalar* Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::data () const inline
Definition at line 61 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> Lhs& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::expression () const inline
Definition at line 153 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> const BinaryOp& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::functor () const inline
Definition at line 158 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor.
template<typename BinaryOp, typename Lhs, typename Rhs> Index Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::innerStride () const inline
Definition at line 60 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> template<typename RhsDerived > EIGEN_STRONG_INLINE SelfCwiseBinaryOp& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::lazyAssign (const DenseBase< RhsDerived > & rhs) inline
Definition at line 128 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), debug, eigen_assert, EIGEN_CHECK_BINARY_COMPATIBILIY, EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE, and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
template<typename BinaryOp, typename Lhs, typename Rhs> SelfCwiseBinaryOp& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::operator= (const Rhs & _rhs) inline
Definition at line 147 of file SelfCwiseBinaryOp.h.
template<typename BinaryOp, typename Lhs, typename Rhs> SelfCwiseBinaryOp& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::operator= (const SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs > &) private
template<typename BinaryOp, typename Lhs, typename Rhs> Index Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::outerStride () const inline
Definition at line 59 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
template<typename BinaryOp, typename Lhs, typename Rhs> Index Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows (void) const inline
Definition at line 57 of file SelfCwiseBinaryOp.h.
References Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Referenced by Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::lazyAssign().
Member Data Documentation
template<typename BinaryOp, typename Lhs, typename Rhs> const BinaryOp& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor protected
Definition at line 165 of file SelfCwiseBinaryOp.h.
Referenced by Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::functor().
template<typename BinaryOp, typename Lhs, typename Rhs> Lhs& Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix protected
Definition at line 164 of file SelfCwiseBinaryOp.h.
Referenced by Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::coeffRef(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::data(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::expression(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::innerStride(), Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::outerStride(), and Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/SelfCwiseBinaryOp.h