LIA_RAL: Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator Class Reference
Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator Class Reference
#include <SparseVector.h>
Public Member Functions
InnerIterator (const SparseVector &vec, Index outer=0)
InnerIterator (const internal::CompressedStorage< Scalar, Index > &data)
InnerIterator & operator++ ()
Scalar value () const
Scalar & valueRef ()
Index index () const
Index row () const
Index col () const
operator bool () const
Protected Attributes
const
internal::CompressedStorage
< Scalar, Index > & m_data
Index m_id
const Index m_end
Detailed Description
template<typename _Scalar, int _Flags = 0, typename _Index = int>
class Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator
Definition at line 333 of file SparseVector.h.
Constructor & Destructor Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::InnerIterator (const SparseVector & vec, Index outer = 0) inline
Definition at line 336 of file SparseVector.h.
References eigen_assert, and EIGEN_UNUSED_VARIABLE.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::InnerIterator (const internal::CompressedStorage< Scalar, Index > & data) inline
Definition at line 343 of file SparseVector.h.
Member Function Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::col () const inline
Definition at line 354 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::index () const inline
Definition at line 352 of file SparseVector.h.
References Eigen::internal::CompressedStorage< _Scalar, _Index >::index(), and Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::operator bool () const inline
Definition at line 356 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> InnerIterator& Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::operator++ () inline
Definition at line 347 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::row () const inline
Definition at line 353 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::IsColVector.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::value () const inline
Definition at line 349 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
template<typename _Scalar , int _Flags = 0, typename _Index = int> Scalar& Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::valueRef () inline
Definition at line 350 of file SparseVector.h.
References Eigen::SparseVector< _Scalar, _Flags, _Index >::m_data, and Eigen::internal::CompressedStorage< _Scalar, _Index >::value().
Member Data Documentation
template<typename _Scalar , int _Flags = 0, typename _Index = int> const internal::CompressedStorage<Scalar,Index>& Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::m_data protected
Definition at line 359 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> const Index Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::m_end protected
Definition at line 361 of file SparseVector.h.
template<typename _Scalar , int _Flags = 0, typename _Index = int> Index Eigen::SparseVector< _Scalar, _Flags, _Index >::InnerIterator::m_id protected
Definition at line 360 of file SparseVector.h.
The documentation for this class was generated from the following file:
include/Eigen/src/SparseCore/SparseVector.h