LIA_RAL: Eigen::internal::UpperBidiagonalization< _MatrixType > Class Template Reference
Eigen::internal::UpperBidiagonalization< _MatrixType > Class Template Reference
#include <UpperBidiagonalization.h>
Public Types
enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, ColsAtCompileTimeMinusOne = internal::decrement_size<ColsAtCompileTime>::ret }
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
1, ColsAtCompileTime > RowVectorType
typedef Matrix< Scalar,
RowsAtCompileTime, 1 > ColVectorType
typedef BandMatrix< RealScalar,
ColsAtCompileTime,
ColsAtCompileTime, 1, 0 > BidiagonalType
typedef Matrix< Scalar,
ColsAtCompileTime, 1 > DiagVectorType
typedef Matrix< Scalar,
ColsAtCompileTimeMinusOne, 1 > SuperDiagVectorType
typedef HouseholderSequence
< const MatrixType,
CwiseUnaryOp
< internal::scalar_conjugate_op
< Scalar >, const Diagonal
< const MatrixType, 0 > > > HouseholderUSequenceType
typedef HouseholderSequence
< const MatrixType, Diagonal
< const MatrixType, 1 >
, OnTheRight > HouseholderVSequenceType
Public Member Functions
UpperBidiagonalization ()
Default Constructor.
UpperBidiagonalization (const MatrixType &matrix)
UpperBidiagonalization & compute (const MatrixType &matrix)
const MatrixType & householder () const
const BidiagonalType & bidiagonal () const
const HouseholderUSequenceType householderU () const
const HouseholderVSequenceType householderV ()
Protected Attributes
MatrixType m_householder
BidiagonalType m_bidiagonal
bool m_isInitialized
Detailed Description
template<typename _MatrixType>
class Eigen::internal::UpperBidiagonalization< _MatrixType >
Definition at line 19 of file UpperBidiagonalization.h.
Member Typedef Documentation
template<typename _MatrixType > typedef BandMatrix<RealScalar, ColsAtCompileTime, ColsAtCompileTime, 1, 0> Eigen::internal::UpperBidiagonalization< _MatrixType >::BidiagonalType
Definition at line 34 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef Matrix<Scalar, RowsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::ColVectorType
Definition at line 33 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef Matrix<Scalar, ColsAtCompileTime, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::DiagVectorType
Definition at line 35 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef HouseholderSequence< const MatrixType, CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Diagonal<const MatrixType,0> > > Eigen::internal::UpperBidiagonalization< _MatrixType >::HouseholderUSequenceType
Definition at line 40 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef HouseholderSequence< const MatrixType, Diagonal<const MatrixType,1>, OnTheRight > Eigen::internal::UpperBidiagonalization< _MatrixType >::HouseholderVSequenceType
Definition at line 45 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef MatrixType::Index Eigen::internal::UpperBidiagonalization< _MatrixType >::Index
Definition at line 31 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef _MatrixType Eigen::internal::UpperBidiagonalization< _MatrixType >::MatrixType
Definition at line 23 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef MatrixType::RealScalar Eigen::internal::UpperBidiagonalization< _MatrixType >::RealScalar
Definition at line 30 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef Matrix<Scalar, 1, ColsAtCompileTime> Eigen::internal::UpperBidiagonalization< _MatrixType >::RowVectorType
Definition at line 32 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef MatrixType::Scalar Eigen::internal::UpperBidiagonalization< _MatrixType >::Scalar
Definition at line 29 of file UpperBidiagonalization.h.
template<typename _MatrixType > typedef Matrix<Scalar, ColsAtCompileTimeMinusOne, 1> Eigen::internal::UpperBidiagonalization< _MatrixType >::SuperDiagVectorType
Definition at line 36 of file UpperBidiagonalization.h.
Member Enumeration Documentation
template<typename _MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
ColsAtCompileTimeMinusOne
Definition at line 24 of file UpperBidiagonalization.h.
Constructor & Destructor Documentation
template<typename _MatrixType > Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via Bidiagonalization::compute(const MatrixType&).
Definition at line 53 of file UpperBidiagonalization.h.
template<typename _MatrixType > Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization (const MatrixType & matrix) inline
Definition at line 55 of file UpperBidiagonalization.h.
References Eigen::internal::UpperBidiagonalization< _MatrixType >::compute().
Member Function Documentation
template<typename _MatrixType > const BidiagonalType& Eigen::internal::UpperBidiagonalization< _MatrixType >::bidiagonal () const inline
Definition at line 66 of file UpperBidiagonalization.h.
References Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal.
template<typename _MatrixType > UpperBidiagonalization< _MatrixType > & Eigen::internal::UpperBidiagonalization< _MatrixType >::compute (const MatrixType & matrix)
Definition at line 89 of file UpperBidiagonalization.h.
References Eigen::PlainObjectBase< Derived >::data(), and eigen_assert.
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::UpperBidiagonalization().
template<typename _MatrixType > const MatrixType& Eigen::internal::UpperBidiagonalization< _MatrixType >::householder () const inline
Definition at line 65 of file UpperBidiagonalization.h.
References Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder.
template<typename _MatrixType > const HouseholderUSequenceType Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU () const inline
Definition at line 68 of file UpperBidiagonalization.h.
References eigen_assert, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, and Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized.
template<typename _MatrixType > const HouseholderVSequenceType Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV () inline
Definition at line 74 of file UpperBidiagonalization.h.
References eigen_assert, Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder, and Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized.
Member Data Documentation
template<typename _MatrixType > BidiagonalType Eigen::internal::UpperBidiagonalization< _MatrixType >::m_bidiagonal protected
Definition at line 84 of file UpperBidiagonalization.h.
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::bidiagonal().
template<typename _MatrixType > MatrixType Eigen::internal::UpperBidiagonalization< _MatrixType >::m_householder protected
Definition at line 83 of file UpperBidiagonalization.h.
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::householder(), Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV().
template<typename _MatrixType > bool Eigen::internal::UpperBidiagonalization< _MatrixType >::m_isInitialized protected
Definition at line 85 of file UpperBidiagonalization.h.
Referenced by Eigen::internal::UpperBidiagonalization< _MatrixType >::householderU(), and Eigen::internal::UpperBidiagonalization< _MatrixType >::householderV().
The documentation for this class was generated from the following file:
include/Eigen/src/SVD/UpperBidiagonalization.h