LIA_RAL: Eigen::SparseMatrix< _Scalar, _Options, _Index > Class Template Reference
Eigen::SparseMatrix< _Scalar, _Options, _Index > Class Template Reference
A versatible sparse matrix representation.
#include <SparseMatrix.h>
Classes
struct default_prunning_func
class InnerIterator
class ReverseInnerIterator
class SingletonVector
Public Types
enum { Options = _Options }
typedef MappedSparseMatrix
< Scalar, Flags > Map
typedef
internal::CompressedStorage
< Scalar, Index > Storage
Public Types inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >
enum
typedef internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Scalar Scalar
typedef
internal::packet_traits
< Scalar >::type PacketScalar
typedef internal::traits
< SparseMatrix< _Scalar,
_Options, _Index >
>::StorageKind StorageKind
typedef internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Index Index
typedef
internal::add_const_on_value_type_if_arithmetic
< typename
internal::packet_traits
< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef EigenBase
< SparseMatrix< _Scalar,
_Options, _Index > > Base
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, CwiseUnaryOp
< internal::scalar_conjugate_op
< Scalar >, Eigen::Transpose
< const SparseMatrix< _Scalar,
_Options, _Index >
> >, Transpose< const
SparseMatrix< _Scalar,
_Options, _Index > > >::type AdjointReturnType
typedef SparseMatrix< Scalar,
Flags &RowMajorBit?RowMajor:ColMajor > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef internal::conditional
< _HasDirectAccess, const
Scalar &, Scalar >::type CoeffReturnType
typedef CwiseNullaryOp
< internal::scalar_constant_op
< Scalar >, Matrix< Scalar,
Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar,
EIGEN_SIZE_MAX(RowsAtCompileTime,
ColsAtCompileTime),
EIGEN_SIZE_MAX(RowsAtCompileTime,
ColsAtCompileTime)> SquareMatrixType
typedef CwiseUnaryOp
< internal::scalar_multiple_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > ScalarMultipleReturnType
typedef CwiseUnaryOp
< internal::scalar_quotient1_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > ScalarQuotient1ReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, const
CwiseUnaryOp
< internal::scalar_conjugate_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
>, const SparseMatrix
< _Scalar, _Options, _Index >
& >::type ConjugateReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, const
CwiseUnaryOp
< internal::scalar_real_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
>, const SparseMatrix
< _Scalar, _Options, _Index >
& >::type RealReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, CwiseUnaryView
< internal::scalar_real_ref_op
< Scalar >, SparseMatrix
< _Scalar, _Options, _Index >
>, SparseMatrix< _Scalar,
_Options, _Index > & >::type NonConstRealReturnType
typedef CwiseUnaryOp
< internal::scalar_imag_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > ImagReturnType
typedef CwiseUnaryView
< internal::scalar_imag_ref_op
< Scalar >, SparseMatrix
< _Scalar, _Options, _Index > > NonConstImagReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
bool isCompressed () const
Index rows () const
Index cols () const
Index innerSize () const
Index outerSize () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const Index * innerIndexPtr () const
Index * innerIndexPtr ()
const Index * outerIndexPtr () const
Index * outerIndexPtr ()
const Index * innerNonZeroPtr () const
Index * innerNonZeroPtr ()
Storage & data ()
const Storage & data () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
EIGEN_DONT_INLINE Scalar & insert (Index row, Index col)
void setZero ()
Index nonZeros () const
void reserve (Index reserveSize)
template<class SizesType >
void reserve (const SizesType &reserveSizes, const typename SizesType::value_type &enableif=typename SizesType::value_type())
template<class SizesType >
void reserve (const SizesType &reserveSizes, const typename SizesType::Scalar &enableif=typename SizesType::Scalar())
Scalar & insertBack (Index row, Index col)
Scalar & insertBackByOuterInner (Index outer, Index inner)
Scalar & insertBackByOuterInnerUnordered (Index outer, Index inner)
void startVec (Index outer)
void finalize ()
template<typename InputIterators >
void setFromTriplets (const InputIterators &begin, const InputIterators &end)
void sumupDuplicates ()
EIGEN_DONT_INLINE Scalar & insertByOuterInner (Index j, Index i)
void makeCompressed ()
void prune (Scalar reference, RealScalar epsilon=NumTraits< RealScalar >::dummy_precision())
template<typename KeepFunc >
void prune (const KeepFunc &keep=KeepFunc())
void resize (Index rows, Index cols)
void resizeNonZeros (Index size)
const Diagonal< const
SparseMatrix > diagonal () const
SparseMatrix ()
SparseMatrix (Index rows, Index cols)
template<typename OtherDerived >
SparseMatrix (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix (const SparseMatrix &other)
template<typename OtherDerived >
SparseMatrix (const ReturnByValue< OtherDerived > &other)
Copy constructor with in-place evaluation.
void swap (SparseMatrix &other)
SparseMatrix & operator= (const SparseMatrix &other)
template<typename Lhs , typename Rhs >
SparseMatrix & operator= (const SparseSparseProduct< Lhs, Rhs > &product)
template<typename OtherDerived >
SparseMatrix & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
SparseMatrix & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DONT_INLINE SparseMatrix & operator= (const SparseMatrixBase< OtherDerived > &other)
~SparseMatrix ()
Scalar sum () const
Scalar & insertBackUncompressed (Index row, Index col)
Public Member Functions inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >
SparseMatrix< _Scalar,
_Options, _Index > & operator= (const EigenBase< OtherDerived > &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator= (const ReturnByValue< OtherDerived > &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator= (const SparseMatrix< _Scalar, _Options, _Index > &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator= (const SparseSparseProduct< Lhs, Rhs > &product)
const SparseMatrix< _Scalar,
_Options, _Index > & derived () const
SparseMatrix< _Scalar,
_Options, _Index > & derived ()
SparseMatrix< _Scalar,
_Options, _Index > & const_cast_derived () const
const CwiseUnaryOp
< internal::scalar_opposite_op
< typename internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index > > operator- () const
const ScalarMultipleReturnType operator* (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const SparseMatrix
< _Scalar, _Options, _Index > > operator* (const std::complex< Scalar > &scalar) const
const
SparseSparseProductReturnType
< SparseMatrix< _Scalar,
_Options, _Index >
, OtherDerived >::Type operator* (const SparseMatrixBase< OtherDerived > &other) const
const SparseDiagonalProduct
< SparseMatrix< _Scalar,
_Options, _Index >
, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const
SparseDenseProductReturnType
< SparseMatrix< _Scalar,
_Options, _Index >
, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_quotient1_op
< typename internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index > > operator/ (const Scalar &scalar) const
internal::cast_return_type
< SparseMatrix< _Scalar,
_Options, _Index >, const
CwiseUnaryOp
< internal::scalar_cast_op
< typename internal::traits
< SparseMatrix< _Scalar,
_Options, _Index > >::Scalar,
NewType >, const SparseMatrix
< _Scalar, _Options, _Index >
> >::type cast () const
ConjugateReturnType conjugate () const
RealReturnType real () const
NonConstRealReturnType real ()
const ImagReturnType imag () const
NonConstImagReturnType imag ()
const CwiseUnaryOp
< CustomUnaryOp, const
SparseMatrix< _Scalar,
_Options, _Index > > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
const CwiseUnaryView
< CustomViewOp, const
SparseMatrix< _Scalar,
_Options, _Index > > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp< CustomBinaryOp,
const SparseMatrix< _Scalar,
_Options, _Index >, const
OtherDerived > binaryExpr (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
EIGEN_STRONG_INLINE const
CwiseUnaryOp
< internal::scalar_abs_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseAbs () const
EIGEN_STRONG_INLINE const
CwiseUnaryOp
< internal::scalar_abs2_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseAbs2 () const
const CwiseUnaryOp
< internal::scalar_sqrt_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseSqrt () const
const CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseInverse () const
const CwiseUnaryOp
< std::binder1st
< std::equal_to< Scalar >
>, const SparseMatrix
< _Scalar, _Options, _Index > > cwiseEqual (const Scalar &s) const
const CwiseBinaryOp
< std::equal_to< Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const EIGEN_CWISE_PRODUCT_RETURN_TYPE (SparseMatrix< _Scalar, _Options, _Index >, OtherDerived) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
const CwiseBinaryOp
< std::not_equal_to< Scalar >
, const SparseMatrix< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMin (const Scalar &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMax (const Scalar &other) const
EIGEN_STRONG_INLINE const
CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const SparseMatrix
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
Index rows () const
Index cols () const
Index size () const
Index nonZeros () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
SparseMatrix< _Scalar,
_Options, _Index > & markAsRValue ()
SparseMatrixBase ()
SparseMatrix< _Scalar,
_Options, _Index > & operator+= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator-= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator*= (const Scalar &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator*= (const SparseMatrixBase< OtherDerived > &other)
SparseMatrix< _Scalar,
_Options, _Index > & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const
EIGEN_SPARSE_CWISE_PRODUCT_RETURN_TYPE cwiseProduct (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct
< SparseMatrix< _Scalar,
_Options, _Index >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > &perm) const
const SparseTriangularView
< SparseMatrix< _Scalar,
_Options, _Index >, Mode > triangularView () const
const SparseSelfAdjointView
< SparseMatrix< _Scalar,
_Options, _Index >, UpLo > selfadjointView () const
SparseSelfAdjointView
< SparseMatrix< _Scalar,
_Options, _Index >, UpLo > selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
Transpose< SparseMatrix
< _Scalar, _Options, _Index > > transpose ()
const Transpose< const
SparseMatrix< _Scalar,
_Options, _Index > > transpose () const
const AdjointReturnType adjoint () const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, 1 > row (Index i)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, 1 > row (Index i) const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, 1 > col (Index j)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, 1 > col (Index j) const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, 1 > innerVector (Index outer)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, 1 > innerVector (Index outer) const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > subrows (Index start, Index size)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > subrows (Index start, Index size) const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > subcols (Index start, Index size)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > subcols (Index start, Index size) const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > middleRows (Index start, Index size)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > middleRows (Index start, Index size) const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > middleCols (Index start, Index size)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > middleCols (Index start, Index size) const
SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > innerVectors (Index outerStart, Index outerSize)
const SparseInnerVectorSet
< SparseMatrix< _Scalar,
_Options, _Index >, Dynamic > innerVectors (Index outerStart, Index outerSize) const
void evalTo (MatrixBase< DenseDerived > &dst) const
Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime > toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval
< SparseMatrix< _Scalar,
_Options, _Index > >::type eval () const
Scalar sum () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef SparseMatrix< Scalar,(Flags
&~RowMajorBit)|(IsRowMajor?RowMajorBit:0)> TransposedSparseMatrix
Protected Member Functions
Eigen::Map< Matrix< Index,
Dynamic, 1 > > innerNonZeros ()
const Eigen::Map< const Matrix
< Index, Dynamic, 1 > > innerNonZeros () const
template<class SizesType >
void reserveInnerVectors (const SizesType &reserveSizes)
template<typename Other >
void initAssignment (const Other &other)
EIGEN_DONT_INLINE Scalar & insertCompressed (Index row, Index col)
EIGEN_DONT_INLINE Scalar & insertUncompressed (Index row, Index col)
Protected Member Functions inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >
SparseMatrix< _Scalar,
_Options, _Index > & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Protected Attributes
Index m_outerSize
Index m_innerSize
Index * m_outerIndex
Index * m_innerNonZeros
Storage m_data
Protected Attributes inherited from Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >
bool m_isRValue
Static Private Member Functions
static void check_template_parameters ()
Friends
std::ostream & operator<< (std::ostream &s, const SparseMatrix &m)
Detailed Description
template<typename _Scalar, int _Options, typename _Index>
class Eigen::SparseMatrix< _Scalar, _Options, _Index >
A versatible sparse matrix representation.
This class implements a more versatile variants of the common compressed row/column storage format. Each colmun's (resp. row) non zeros are stored as a pair of value with associated row (resp. colmiun) index. All the non zeros are stored in a single large buffer. Unlike the compressed format, there might be extra space inbetween the nonzeros of two successive colmuns (resp. rows) such that insertion of new non-zero can be done with limited memory reallocation and copies.
A call to the function makeCompressed() turns the matrix into the standard compressed format compatible with many library.
More details on this storage sceheme are given in the manual pages.
Template Parameters
_Scalar the scalar type, i.e. the type of the coefficients
_Options Union of bit flags controlling the storage scheme. Currently the only possibility is RowMajor. The default is 0 which means column-major.
_Index the type of the indices. It has to be a signed type (e.g., short, int, std::ptrdiff_t). Default is int.
This class can be extended with the help of the plugin mechanism described on the page TopicCustomizingEigen by defining the preprocessor symbol EIGEN_SPARSEMATRIX_PLUGIN.
Definition at line 85 of file SparseMatrix.h.
Member Typedef Documentation
template<typename _Scalar, int _Options, typename _Index> typedef MappedSparseMatrix<Scalar,Flags> Eigen::SparseMatrix< _Scalar, _Options, _Index >::Map
Definition at line 93 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> typedef internal::CompressedStorage<Scalar,Index> Eigen::SparseMatrix< _Scalar, _Options, _Index >::Storage
Definition at line 95 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> typedef SparseMatrix<Scalar,(Flags&~RowMajorBit)|(IsRowMajor?RowMajorBit:0)> Eigen::SparseMatrix< _Scalar, _Options, _Index >::TransposedSparseMatrix protected
Definition at line 102 of file SparseMatrix.h.
Member Enumeration Documentation
template<typename _Scalar, int _Options, typename _Index> anonymous enum
Enumerator
Options
Definition at line 96 of file SparseMatrix.h.
Constructor & Destructor Documentation
template<typename _Scalar, int _Options, typename _Index> Eigen::SparseMatrix< _Scalar, _Options, _Index >::SparseMatrix () inline
Default constructor yielding an empty 0 x 0 matrix
Definition at line 543 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Eigen::SparseMatrix< _Scalar, _Options, _Index >::SparseMatrix (Index rows, Index cols) inline
Constructs a rows x cols empty matrix
Definition at line 551 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _Index >::SparseMatrix (const SparseMatrixBase< OtherDerived > & other) inline
Constructs a sparse matrix from the sparse expression other
Definition at line 560 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Eigen::SparseMatrix< _Scalar, _Options, _Index >::SparseMatrix (const SparseMatrix< _Scalar, _Options, _Index > & other) inline
Copy constructor (it performs a deep copy)
Definition at line 568 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<typename OtherDerived > Eigen::SparseMatrix< _Scalar, _Options, _Index >::SparseMatrix (const ReturnByValue< OtherDerived > & other) inline
Copy constructor with in-place evaluation.
Definition at line 577 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Eigen::SparseMatrix< _Scalar, _Options, _Index >::~SparseMatrix () inline
Destructor
Definition at line 732 of file SparseMatrix.h.
Member Function Documentation
template<typename _Scalar, int _Options, typename _Index> static void Eigen::SparseMatrix< _Scalar, _Options, _Index >::check_template_parameters () inline static private
Definition at line 934 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::SparseMatrix().
template<typename _Scalar, int _Options, typename _Index> Scalar Eigen::SparseMatrix< _Scalar, _Options, _Index >::coeff (Index row, Index col) const inline
Returns
the value of the matrix at position i, j This function returns Scalar(0) if the element is an explicit zero
Definition at line 171 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::coeffRef (Index row, Index col) inline
Returns
a non-const reference to the value of the matrix at position i, j
If the element does not exist then it is inserted via the insert(Index,Index) function which itself turns the matrix into a non compressed form if that was not the case.
This is a O(log(nnz_j)) operation (binary search) plus the cost of insert(Index,Index) function if the element does not already exist.
Definition at line 187 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Index Eigen::SparseMatrix< _Scalar, _Options, _Index >::cols (void) const inline
Returns
the number of columns of the matrix
Definition at line 121 of file SparseMatrix.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::cols(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::cols(), Eigen::UmfPackLU< _MatrixType >::cols(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::cols(), Eigen::PastixBase< Derived >::compute(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::dumpMemory(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::internal::minimum_degree_ordering(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), and Eigen::viewAsCholmod().
template<typename _Scalar, int _Options, typename _Index> Storage& Eigen::SparseMatrix< _Scalar, _Options, _Index >::data () inline
Definition at line 165 of file SparseMatrix.h.
Referenced by Eigen::SparseInnerVectorSet< SparseMatrix< _Scalar, _Options, _Index >, Size >::operator=().
template<typename _Scalar, int _Options, typename _Index> const Storage& Eigen::SparseMatrix< _Scalar, _Options, _Index >::data () const inline
Definition at line 167 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> const Diagonal<const SparseMatrix> Eigen::SparseMatrix< _Scalar, _Options, _Index >::diagonal () const inline
Returns
a const expression of the diagonal coefficients
Definition at line 540 of file SparseMatrix.h.
Referenced by Eigen::SimplicialLLT< _MatrixType, _UpLo >::determinant().
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::finalize () inline
Definition at line 405 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<typename Other > void Eigen::SparseMatrix< _Scalar, _Options, _Index >::initAssignment (const Other & other) inline protected
Definition at line 750 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::operator=(), and Eigen::SparseMatrix< Scalar, RowMajor >::SparseMatrix().
template<typename _Scalar, int _Options, typename _Index> const Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr () const inline
Returns
a const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), outerIndexPtr()
Definition at line 140 of file SparseMatrix.h.
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), Eigen::PastixBase< Derived >::factorize(), Eigen::UmfPackLU< _MatrixType >::grapInput(), Eigen::internal::minimum_degree_ordering(), and Eigen::viewAsCholmod().
template<typename _Scalar, int _Options, typename _Index> Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr () inline
Returns
a non-const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), outerIndexPtr()
Definition at line 144 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> const Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerNonZeroPtr () const inline
Returns
a const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
Definition at line 158 of file SparseMatrix.h.
Referenced by Eigen::viewAsCholmod().
template<typename _Scalar, int _Options, typename _Index> Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerNonZeroPtr () inline
Returns
a non-const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
Definition at line 162 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Eigen::Map<Matrix<Index,Dynamic,1> > Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerNonZeros () inline protected
Definition at line 110 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::nonZeros().
template<typename _Scalar, int _Options, typename _Index> const Eigen::Map<const Matrix<Index,Dynamic,1> > Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerNonZeros () const inline protected
Definition at line 111 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Index Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerSize () const inline
Returns
the number of rows (resp. columns) of the matrix if the storage order column major (resp. row major)
Definition at line 124 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> EIGEN_DONT_INLINE Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insert (Index row, Index col) inline
Returns
a reference to a novel non zero coefficient with coordinates row x col. The non zero coefficient must not already exist.
If the matrix *this is in compressed mode, then *this is turned into uncompressed mode while reserving room for 2 non zeros per inner vector. It is strongly recommended to first call reserve(const SizesType &) to reserve a more appropriate number of elements per inner vector that better match your scenario.
This function performs a sorted insertion in O(1) if the elements of each inner vector are inserted in increasing inner index order, and in O(nnz_j) for a random insertion.
Definition at line 216 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::coeffRef(), and Eigen::SparseMatrix< Scalar, RowMajor >::insertByOuterInner().
template<typename _Scalar, int _Options, typename _Index> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insertBack (Index row, Index col) inline
Definition at line 366 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insertBackByOuterInner (Index outer, Index inner) inline
Definition at line 373 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::insertBack().
template<typename _Scalar, int _Options, typename _Index> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insertBackByOuterInnerUnordered (Index outer, Index inner) inline
Definition at line 385 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insertBackUncompressed (Index row, Index col) inline
Definition at line 919 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> EIGEN_DONT_INLINE Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insertByOuterInner (Index j, Index i) inline
Definition at line 434 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> EIGEN_DONT_INLINE Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insertCompressed (Index row, Index col) inline protected
Definition at line 762 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> EIGEN_DONT_INLINE Scalar& Eigen::SparseMatrix< _Scalar, _Options, _Index >::insertUncompressed (Index row, Index col) inline protected
Definition at line 885 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::insert().
template<typename _Scalar, int _Options, typename _Index> bool Eigen::SparseMatrix< _Scalar, _Options, _Index >::isCompressed () const inline
Returns
whether *this is in compressed form.
Definition at line 116 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::InnerIterator::InnerIterator(), Eigen::SparseMatrix< Scalar, RowMajor >::insert(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor >::reserve(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::ReverseInnerIterator::ReverseInnerIterator(), and Eigen::viewAsCholmod().
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::makeCompressed () inline
Turns the matrix into the compressed format.
Definition at line 441 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::prune().
template<typename _Scalar, int _Options, typename _Index> Index Eigen::SparseMatrix< _Scalar, _Options, _Index >::nonZeros () const inline
Returns
the number of non zero coefficients
Definition at line 240 of file SparseMatrix.h.
Referenced by Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::_solve(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::dumpMemory(), Eigen::internal::minimum_degree_ordering(), Eigen::SparseInnerVectorSet< SparseMatrix< _Scalar, _Options, _Index >, Size >::operator=(), and Eigen::viewAsCholmod().
template<typename _Scalar, int _Options, typename _Index> SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _Index >::operator= (const SparseMatrix< _Scalar, _Options, _Index > & other) inline
Definition at line 597 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<typename Lhs , typename Rhs > SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _Index >::operator= (const SparseSparseProduct< Lhs, Rhs > & product) inline
Definition at line 621 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<typename OtherDerived > SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _Index >::operator= (const ReturnByValue< OtherDerived > & other) inline
Definition at line 625 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<typename OtherDerived > SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _Index >::operator= (const EigenBase< OtherDerived > & other) inline
Definition at line 632 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<typename OtherDerived > EIGEN_DONT_INLINE SparseMatrix& Eigen::SparseMatrix< _Scalar, _Options, _Index >::operator= (const SparseMatrixBase< OtherDerived > & other) inline
Definition at line 637 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> const Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr () const inline
Returns
a const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), innerIndexPtr()
Definition at line 149 of file SparseMatrix.h.
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), Eigen::PastixBase< Derived >::factorize(), Eigen::UmfPackLU< _MatrixType >::grapInput(), Eigen::internal::minimum_degree_ordering(), and Eigen::viewAsCholmod().
template<typename _Scalar, int _Options, typename _Index> Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr () inline
Returns
a non-const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See Also
valuePtr(), innerIndexPtr()
Definition at line 153 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> Index Eigen::SparseMatrix< _Scalar, _Options, _Index >::outerSize () const inline
Returns
the number of columns (resp. rows) of the matrix if the storage order column major (resp. row major)
Definition at line 126 of file SparseMatrix.h.
Referenced by Eigen::PastixLU< _MatrixType, IsStrSym >::grabMatrix(), Eigen::SparseMatrix< Scalar, RowMajor >::insert(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), and Eigen::SparseInnerVectorSet< SparseMatrix< _Scalar, _Options, _Index >, Size >::SparseInnerVectorSet().
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::prune (Scalar reference, RealScalar epsilon = NumTraits<RealScalar>::dummy_precision()) inline
Suppresses all nonzeros which are much smaller than reference under the tolerence epsilon
Definition at line 470 of file SparseMatrix.h.
Referenced by Eigen::IncompleteLUT< _Scalar >::analyzePattern(), and Eigen::SparseMatrix< Scalar, RowMajor >::prune().
template<typename _Scalar, int _Options, typename _Index> template<typename KeepFunc > void Eigen::SparseMatrix< _Scalar, _Options, _Index >::prune (const KeepFunc & keep = KeepFunc()) inline
Turns the matrix into compressed format, and suppresses all nonzeros which do not satisfy the predicate keep. The functor type KeepFunc must implement the following function:
bool operator() (const Index& row, const Index& col, const Scalar& value) const;
See Also
prune(Scalar,RealScalar)
Definition at line 483 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::reserve (Index reserveSize) inline
Preallocates reserveSize non zeros.
Precondition: the matrix must be in compressed mode.
Definition at line 250 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::insert(), and Eigen::SparseMatrix< Scalar, RowMajor >::insertUncompressed().
template<typename _Scalar, int _Options, typename _Index> template<class SizesType > void Eigen::SparseMatrix< _Scalar, _Options, _Index >::reserve (const SizesType & reserveSizes, const typename SizesType::value_type & enableif = typename SizesType::value_type()) inline
Definition at line 264 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<class SizesType > void Eigen::SparseMatrix< _Scalar, _Options, _Index >::reserve (const SizesType & reserveSizes, const typename SizesType::Scalar & enableif = typename SizesType::Scalar()) inline
Definition at line 270 of file SparseMatrix.h.
template<typename _Scalar, int _Options, typename _Index> template<class SizesType > void Eigen::SparseMatrix< _Scalar, _Options, _Index >::reserveInnerVectors (const SizesType & reserveSizes) inline protected
Definition at line 282 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::reserve().
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::resize (Index rows, Index cols) inline
Resizes the matrix to a rows x cols matrix and initializes it to zero.
See Also
resizeNonZeros(Index), reserve(), setZero()
Definition at line 512 of file SparseMatrix.h.
Referenced by Eigen::PardisoLLT< _MatrixType, Options >::getMatrix(), Eigen::PardisoLDLT< _MatrixType, Options >::getMatrix(), Eigen::UmfPackLU< _MatrixType >::grapInput(), Eigen::SparseMatrix< Scalar, RowMajor >::initAssignment(), Eigen::SimplicialCholeskyBase< Derived >::ordering(), and Eigen::SparseMatrix< Scalar, RowMajor >::SparseMatrix().
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::resizeNonZeros (Index size) inline
Definition at line 533 of file SparseMatrix.h.
Referenced by Eigen::internal::minimum_degree_ordering().
template<typename _Scalar, int _Options, typename _Index> Index Eigen::SparseMatrix< _Scalar, _Options, _Index >::rows (void) const inline
Returns
the number of rows of the matrix
Definition at line 119 of file SparseMatrix.h.
Referenced by Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::_solve(), Eigen::CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::_solve(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::_solve_sparse(), Eigen::PastixBase< Derived >::analyzePattern(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered(), Eigen::PastixBase< Derived >::compute(), Eigen::PastixBase< Derived >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), Eigen::IncompleteLUT< _MatrixType >::rows(), Eigen::SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::rows(), Eigen::UmfPackLU< _MatrixType >::rows(), Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::rows(), and Eigen::viewAsCholmod().
template<typename Scalar , int _Options, typename _Index > template<typename InputIterators > void Eigen::SparseMatrix< Scalar, _Options, _Index >::setFromTriplets (const InputIterators & begin, const InputIterators & end)
Fill the matrix *this with the list of triplets defined by the iterator range begin - .
A triplet is a tuple (i,j,value) defining a non-zero element. The input list of triplets does not have to be sorted, and can contains duplicated elements. In any case, the result is a sorted and compressed sparse matrix where the duplicates have been summed up. This is a O(n) operation, with n the number of triplet elements. The initial contents of *this is destroyed. The matrix *this must be properly resized beforehand using the SparseMatrix(Index,Index) constructor, or the resize(Index,Index) method. The sizes are not extracted from the triplet list.
The InputIterators value_type must provide the following interface:
Scalar value() const; // the value
Scalar row() const;   // the row index i
Scalar col() const;   // the column index j
See for instance the Eigen::Triplet template class.
Here is a typical usage example:
typedef Triplet<double> T;
std::vector<T> tripletList;
triplets.reserve(estimation_of_entries);
for(...)
{
  // ...
  tripletList.push_back(T(i,j,v_ij));
}
SparseMatrixType m(rows,cols);
m.setFromTriplets(tripletList.begin(), tripletList.end());
// m is ready to go!
Warning
The list of triplets is read multiple times (at least twice). Therefore, it is not recommended to define an abstract iterator over a complex data-structure that would be expensive to evaluate. The triplets should rather be explicitely stored into a std::vector for instance.
Definition at line 1087 of file SparseMatrix.h.
References Eigen::internal::set_from_triplets().
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::setZero () inline
Removes all non zeros but keep allocated memory
Definition at line 231 of file SparseMatrix.h.
Referenced by Eigen::internal::permut_sparsematrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo(), Eigen::SparseMatrix< Scalar, RowMajor >::operator=(), and Eigen::internal::set_from_triplets().
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::startVec (Index outer) inline
Definition at line 395 of file SparseMatrix.h.
template<typename _Scalar , int _Options, typename _Index > internal::traits< SparseMatrix< _Scalar, _Options, _Index > >::Scalar Eigen::SparseMatrix< _Scalar, _Options, _Index >::sum () const
Overloaded for performance
Definition at line 29 of file SparseRedux.h.
References eigen_assert, and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::Map().
template<typename Scalar , int _Options, typename _Index > void Eigen::SparseMatrix< Scalar, _Options, _Index >::sumupDuplicates ()
Definition at line 1094 of file SparseMatrix.h.
References eigen_assert.
template<typename _Scalar, int _Options, typename _Index> void Eigen::SparseMatrix< _Scalar, _Options, _Index >::swap (SparseMatrix< _Scalar, _Options, _Index > & other) inline
Swaps the content of two sparse matrices of the same type. This is a fast operation that simply swaps the underlying pointers and parameters.
Definition at line 587 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::operator=().
template<typename _Scalar, int _Options, typename _Index> const Scalar* Eigen::SparseMatrix< _Scalar, _Options, _Index >::valuePtr () const inline
Returns
a const pointer to the array of values. This function is aimed at interoperability with other libraries.
See Also
innerIndexPtr(), outerIndexPtr()
Definition at line 131 of file SparseMatrix.h.
Referenced by Eigen::PastixBase< Derived >::analyzePattern(), Eigen::PastixBase< Derived >::factorize(), Eigen::UmfPackLU< _MatrixType >::grapInput(), and Eigen::viewAsCholmod().
template<typename _Scalar, int _Options, typename _Index> Scalar* Eigen::SparseMatrix< _Scalar, _Options, _Index >::valuePtr () inline
Returns
a non-const pointer to the array of values. This function is aimed at interoperability with other libraries.
See Also
innerIndexPtr(), outerIndexPtr()
Definition at line 135 of file SparseMatrix.h.
Friends And Related Function Documentation
template<typename _Scalar, int _Options, typename _Index> std::ostream& operator<< (std::ostream & s, const SparseMatrix< _Scalar, _Options, _Index > & m) friend
Definition at line 694 of file SparseMatrix.h.
Member Data Documentation
template<typename _Scalar, int _Options, typename _Index> Storage Eigen::SparseMatrix< _Scalar, _Options, _Index >::m_data protected
Definition at line 108 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::coeff(), Eigen::SparseMatrix< Scalar, RowMajor >::coeffRef(), Eigen::SparseMatrix< Scalar, RowMajor >::data(), Eigen::SparseMatrix< Scalar, RowMajor >::finalize(), Eigen::SparseMatrix< Scalar, RowMajor >::innerIndexPtr(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::nonZeros(), Eigen::SparseMatrix< Scalar, RowMajor >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::reserve(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), Eigen::SparseMatrix< Scalar, RowMajor >::resizeNonZeros(), Eigen::SparseMatrix< Scalar, RowMajor >::setZero(), Eigen::SparseMatrix< Scalar, RowMajor >::startVec(), Eigen::SparseMatrix< Scalar, RowMajor >::swap(), and Eigen::SparseMatrix< Scalar, RowMajor >::valuePtr().
template<typename _Scalar, int _Options, typename _Index> Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::m_innerNonZeros protected
Definition at line 107 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::coeff(), Eigen::SparseMatrix< Scalar, RowMajor >::coeffRef(), Eigen::SparseMatrix< Scalar, RowMajor >::initAssignment(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::InnerIterator::InnerIterator(), Eigen::SparseMatrix< Scalar, RowMajor >::innerNonZeroPtr(), Eigen::SparseMatrix< Scalar, RowMajor >::innerNonZeros(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::isCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::nonZeros(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::ReverseInnerIterator::ReverseInnerIterator(), Eigen::SparseMatrix< Scalar, RowMajor >::setZero(), Eigen::SparseMatrix< Scalar, RowMajor >::swap(), and Eigen::SparseMatrix< Scalar, RowMajor >::~SparseMatrix().
template<typename _Scalar, int _Options, typename _Index> Index Eigen::SparseMatrix< _Scalar, _Options, _Index >::m_innerSize protected
Definition at line 105 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::cols(), Eigen::SparseMatrix< Scalar, RowMajor >::innerSize(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), Eigen::SparseMatrix< Scalar, RowMajor >::rows(), and Eigen::SparseMatrix< Scalar, RowMajor >::swap().
template<typename _Scalar, int _Options, typename _Index> Index* Eigen::SparseMatrix< _Scalar, _Options, _Index >::m_outerIndex protected
Definition at line 106 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::coeff(), Eigen::SparseMatrix< Scalar, RowMajor >::coeffRef(), Eigen::SparseMatrix< Scalar, RowMajor >::finalize(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::InnerIterator::InnerIterator(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInner(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackByOuterInnerUnordered(), Eigen::SparseMatrix< Scalar, RowMajor >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::insertUncompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor >::outerIndexPtr(), Eigen::SparseMatrix< Scalar, RowMajor >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::ReverseInnerIterator::ReverseInnerIterator(), Eigen::SparseMatrix< Scalar, RowMajor >::setZero(), Eigen::SparseMatrix< Scalar, RowMajor >::startVec(), Eigen::SparseMatrix< Scalar, RowMajor >::swap(), and Eigen::SparseMatrix< Scalar, RowMajor >::~SparseMatrix().
template<typename _Scalar, int _Options, typename _Index> Index Eigen::SparseMatrix< _Scalar, _Options, _Index >::m_outerSize protected
Definition at line 104 of file SparseMatrix.h.
Referenced by Eigen::SparseMatrix< Scalar, RowMajor >::cols(), Eigen::SparseMatrix< Scalar, RowMajor >::finalize(), Eigen::SparseMatrix< Scalar, RowMajor >::innerNonZeros(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::makeCompressed(), Eigen::SparseMatrix< Scalar, RowMajor >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor >::outerSize(), Eigen::SparseMatrix< Scalar, RowMajor >::prune(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::SparseMatrix< Scalar, RowMajor >::resize(), Eigen::SparseMatrix< Scalar, RowMajor >::rows(), Eigen::SparseMatrix< Scalar, RowMajor >::setZero(), and Eigen::SparseMatrix< Scalar, RowMajor >::swap().
The documentation for this class was generated from the following files:
include/Eigen/src/SparseCore/SparseMatrix.h
include/Eigen/src/SparseCore/SparseRedux.h