LIA_RAL: Seq Class Reference
Seq Class Reference
#include <SequenceExtractor.h>
Public Member Functions
Seq (short int, short int)
Seq (const Seq &)
~Seq ()
Seq & operator= (const Seq &)
SymbTab & operator[] (short int)
void setLength (short int order)
short int getLength ()
void init (short int)
void show ()
void add (SymbTab *ptr)
Private Member Functions
void _reserveMem ()
Private Attributes
short int _maxLength
short int _length
short int _nbInputSymb
SymbTab * _array
Detailed Description
Definition at line 103 of file SequenceExtractor.h.
Constructor & Destructor Documentation
Seq::Seq (short int maxLength, short int nbInputSymb)
Definition at line 400 of file SequenceExtractor.cpp.
References _length, _maxLength, _nbInputSymb, and _reserveMem().
Seq::Seq (const Seq & obj)
Definition at line 393 of file SequenceExtractor.cpp.
References _array, _length, _maxLength, _nbInputSymb, and _reserveMem().
Seq::~Seq ()
Definition at line 406 of file SequenceExtractor.cpp.
References _array.
Member Function Documentation
void Seq::_reserveMem () private
Definition at line 386 of file SequenceExtractor.cpp.
References _array, _maxLength, _nbInputSymb, SymbTab::reserveMem(), and SymbTab::setNbSymb().
Referenced by operator=(), and Seq().
void Seq::add (SymbTab * ptr)
Definition at line 444 of file SequenceExtractor.cpp.
References _array, _length, and _maxLength.
Referenced by SequenceDecoder::_toFile().
short int Seq::getLength ()
Definition at line 429 of file SequenceExtractor.cpp.
References _length.
Referenced by CommonPartTree::_findPartSeq(), CommonPartTree::_suppressSeq(), SequenceDecoder::_toFile(), SequenceDecoder::addSequence(), CommonPartTree::findMaxEndSeq(), sequenceExtractor(), and CommonPartTree::suppressSeq().
void Seq::init (short int length = 0)
Definition at line 432 of file SequenceExtractor.cpp.
References _array, _length, and _maxLength.
Referenced by SequenceDecoder::_toFile(), sequenceExtractor(), and SequenceDecoder::toFile().
Seq & Seq::operator= (const Seq & obj)
Definition at line 409 of file SequenceExtractor.cpp.
References _array, _length, _maxLength, _nbInputSymb, and _reserveMem().
SymbTab & Seq::operator[] (short int idx)
Definition at line 420 of file SequenceExtractor.cpp.
References _array, and _maxLength.
void Seq::setLength (short int order)
Definition at line 425 of file SequenceExtractor.cpp.
References _length, and _maxLength.
Referenced by CommonPartTree::_findMaxSeq().
void Seq::show ()
Definition at line 438 of file SequenceExtractor.cpp.
References _array, _length, and SymbTab::show().
Referenced by sequenceExtractor().
Member Data Documentation
SymbTab* Seq::_array private
Definition at line 107 of file SequenceExtractor.h.
Referenced by _reserveMem(), add(), init(), operator=(), operator[](), Seq(), show(), and ~Seq().
short int Seq::_length private
Definition at line 105 of file SequenceExtractor.h.
Referenced by add(), getLength(), init(), operator=(), Seq(), setLength(), and show().
short int Seq::_maxLength private
Definition at line 104 of file SequenceExtractor.h.
Referenced by _reserveMem(), add(), init(), operator=(), operator[](), Seq(), and setLength().
short int Seq::_nbInputSymb private
Definition at line 106 of file SequenceExtractor.h.
Referenced by _reserveMem(), operator=(), and Seq().
The documentation for this class was generated from the following files:
LIA_Utils/SequenceExtractor/include/SequenceExtractor.h
LIA_Utils/SequenceExtractor/src/SequenceExtractor.cpp