LIA_RAL: Eigen::DiagonalBase< Derived > Class Template Reference
Eigen::DiagonalBase< Derived > Class Template Reference
#include <DiagonalMatrix.h>
Public Types
enum {
RowsAtCompileTime = DiagonalVectorType::SizeAtCompileTime, ColsAtCompileTime = DiagonalVectorType::SizeAtCompileTime, MaxRowsAtCompileTime = DiagonalVectorType::MaxSizeAtCompileTime, MaxColsAtCompileTime = DiagonalVectorType::MaxSizeAtCompileTime,
IsVectorAtCompileTime = 0, Flags = 0
}
typedef internal::traits
< Derived >
::DiagonalVectorType DiagonalVectorType
typedef DiagonalVectorType::Scalar Scalar
typedef
DiagonalVectorType::RealScalar RealScalar
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime,
0, MaxRowsAtCompileTime,
MaxColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType DenseType
typedef DiagonalMatrix< Scalar,
DiagonalVectorType::SizeAtCompileTime,
DiagonalVectorType::MaxSizeAtCompileTime > PlainObject
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
const Derived & derived () const
Derived & derived ()
DenseMatrixType toDenseMatrix () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
void addTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
void subTo (MatrixBase< DenseDerived > &other) const
const DiagonalVectorType & diagonal () const
DiagonalVectorType & diagonal ()
Index rows () const
Index cols () const
template<typename MatrixDerived >
const DiagonalProduct
< MatrixDerived, Derived,
OnTheLeft > operator* (const MatrixBase< MatrixDerived > &matrix) const
const DiagonalWrapper< const
CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const
DiagonalVectorType > > inverse () const
const DiagonalWrapper< const
CwiseUnaryOp
< internal::scalar_multiple_op
< Scalar >, const
DiagonalVectorType > > operator* (const Scalar &scalar) const
template<typename MatrixDerived >
const DiagonalProduct
< MatrixDerived,
DiagonalDerived, OnTheLeft > operator* (const MatrixBase< MatrixDerived > &matrix) const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Friends
const DiagonalWrapper< const
CwiseUnaryOp
< internal::scalar_multiple_op
< Scalar >, const
DiagonalVectorType > > operator* (const Scalar &scalar, const DiagonalBase &other)
Detailed Description
template<typename Derived>
class Eigen::DiagonalBase< Derived >
Definition at line 18 of file DiagonalMatrix.h.
Member Typedef Documentation
template<typename Derived> typedef Matrix<Scalar, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::DiagonalBase< Derived >::DenseMatrixType
Definition at line 36 of file DiagonalMatrix.h.
template<typename Derived> typedef DenseMatrixType Eigen::DiagonalBase< Derived >::DenseType
Definition at line 37 of file DiagonalMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::DiagonalVectorType Eigen::DiagonalBase< Derived >::DiagonalVectorType
Definition at line 21 of file DiagonalMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::Index Eigen::DiagonalBase< Derived >::Index
Definition at line 25 of file DiagonalMatrix.h.
template<typename Derived> typedef DiagonalMatrix<Scalar,DiagonalVectorType::SizeAtCompileTime,DiagonalVectorType::MaxSizeAtCompileTime> Eigen::DiagonalBase< Derived >::PlainObject
Definition at line 38 of file DiagonalMatrix.h.
template<typename Derived> typedef DiagonalVectorType::RealScalar Eigen::DiagonalBase< Derived >::RealScalar
Definition at line 23 of file DiagonalMatrix.h.
template<typename Derived> typedef DiagonalVectorType::Scalar Eigen::DiagonalBase< Derived >::Scalar
Definition at line 22 of file DiagonalMatrix.h.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::DiagonalBase< Derived >::StorageKind
Definition at line 24 of file DiagonalMatrix.h.
Member Enumeration Documentation
template<typename Derived> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
IsVectorAtCompileTime
Flags
Definition at line 27 of file DiagonalMatrix.h.
Member Function Documentation
template<typename Derived> template<typename DenseDerived > void Eigen::DiagonalBase< Derived >::addTo (MatrixBase< DenseDerived > & other) const inline
Definition at line 47 of file DiagonalMatrix.h.
template<typename Derived> Index Eigen::DiagonalBase< Derived >::cols (void) const inline
Definition at line 57 of file DiagonalMatrix.h.
template<typename Derived> const Derived& Eigen::DiagonalBase< Derived >::derived () const inline
Definition at line 40 of file DiagonalMatrix.h.
Referenced by Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::diagonal(), Eigen::MatrixBase< Derived >::operator*(), Eigen::SparseMatrixBase< Derived >::operator*(), and Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::toDenseMatrix().
template<typename Derived> Derived& Eigen::DiagonalBase< Derived >::derived () inline
Definition at line 41 of file DiagonalMatrix.h.
template<typename Derived> const DiagonalVectorType& Eigen::DiagonalBase< Derived >::diagonal () const inline
Definition at line 53 of file DiagonalMatrix.h.
Referenced by Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::addTo(), Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::cols(), Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::inverse(), Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::operator*(), Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=(), Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::rows(), and Eigen::DiagonalBase< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >::subTo().
template<typename Derived> DiagonalVectorType& Eigen::DiagonalBase< Derived >::diagonal () inline
Definition at line 54 of file DiagonalMatrix.h.
template<typename Derived > template<typename DenseDerived > void Eigen::DiagonalBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const
Definition at line 96 of file DiagonalMatrix.h.
References Eigen::MatrixBase< Derived >::diagonal(), and Eigen::DenseBase< Derived >::setZero().
template<typename Derived> const DiagonalWrapper<const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const DiagonalVectorType> > Eigen::DiagonalBase< Derived >::inverse () const inline
Definition at line 64 of file DiagonalMatrix.h.
template<typename Derived> template<typename MatrixDerived > const DiagonalProduct<MatrixDerived, Derived, OnTheLeft> Eigen::DiagonalBase< Derived >::operator* (const MatrixBase< MatrixDerived > & matrix) const
template<typename Derived> const DiagonalWrapper<const CwiseUnaryOp<internal::scalar_multiple_op<Scalar>, const DiagonalVectorType> > Eigen::DiagonalBase< Derived >::operator* (const Scalar & scalar) const inline
Definition at line 70 of file DiagonalMatrix.h.
template<typename Derived> template<typename MatrixDerived > const DiagonalProduct<MatrixDerived, DiagonalDerived, OnTheLeft> Eigen::DiagonalBase< Derived >::operator* (const MatrixBase< MatrixDerived > & matrix) const inline
Returns
the diagonal matrix product of *this by the matrix matrix.
Definition at line 116 of file DiagonalProduct.h.
template<typename Derived> Index Eigen::DiagonalBase< Derived >::rows (void) const inline
Definition at line 56 of file DiagonalMatrix.h.
template<typename Derived> template<typename DenseDerived > void Eigen::DiagonalBase< Derived >::subTo (MatrixBase< DenseDerived > & other) const inline
Definition at line 50 of file DiagonalMatrix.h.
template<typename Derived> DenseMatrixType Eigen::DiagonalBase< Derived >::toDenseMatrix () const inline
Definition at line 43 of file DiagonalMatrix.h.
Friends And Related Function Documentation
template<typename Derived> const DiagonalWrapper<const CwiseUnaryOp<internal::scalar_multiple_op<Scalar>, const DiagonalVectorType> > operator* (const Scalar & scalar, const DiagonalBase< Derived > & other) friend
Definition at line 75 of file DiagonalMatrix.h.
The documentation for this class was generated from the following files:
include/Eigen/src/Core/DiagonalMatrix.h
include/Eigen/src/Core/DiagonalProduct.h