LIA_RAL: Eigen::TransposeImpl< MatrixType, Dense > Class Template Reference
Eigen::TransposeImpl< MatrixType, Dense > Class Template Reference
#include <Transpose.h>
Public Types
typedef
internal::TransposeImpl_base
< MatrixType >::type Base
typedef internal::conditional
< internal::is_lvalue
< MatrixType >::value, Scalar,
const Scalar >::type ScalarWithConstIfNotLvalue
Public Member Functions
Index innerStride () const
Index outerStride () const
ScalarWithConstIfNotLvalue * data ()
const Scalar * data () const
ScalarWithConstIfNotLvalue & coeffRef (Index row, Index col)
ScalarWithConstIfNotLvalue & coeffRef (Index index)
const Scalar & coeffRef (Index row, Index col) const
const Scalar & coeffRef (Index index) const
CoeffReturnType coeff (Index row, Index col) const
CoeffReturnType coeff (Index index) const
template<int LoadMode>
const PacketScalar packet (Index row, Index col) const
template<int LoadMode>
void writePacket (Index row, Index col, const PacketScalar &x)
template<int LoadMode>
const PacketScalar packet (Index index) const
template<int LoadMode>
void writePacket (Index index, const PacketScalar &x)
Detailed Description
template<typename MatrixType>
class Eigen::TransposeImpl< MatrixType, Dense >
Definition at line 100 of file Transpose.h.
Member Typedef Documentation
template<typename MatrixType > typedef internal::TransposeImpl_base<MatrixType>::type Eigen::TransposeImpl< MatrixType, Dense >::Base
Definition at line 105 of file Transpose.h.
template<typename MatrixType > typedef internal::conditional< internal::is_lvalue<MatrixType>::value, Scalar, const Scalar >::type Eigen::TransposeImpl< MatrixType, Dense >::ScalarWithConstIfNotLvalue
Definition at line 115 of file Transpose.h.
Member Function Documentation
template<typename MatrixType > CoeffReturnType Eigen::TransposeImpl< MatrixType, Dense >::coeff (Index row, Index col) const inline
Definition at line 142 of file Transpose.h.
template<typename MatrixType > CoeffReturnType Eigen::TransposeImpl< MatrixType, Dense >::coeff (Index index) const inline
Definition at line 147 of file Transpose.h.
template<typename MatrixType > ScalarWithConstIfNotLvalue& Eigen::TransposeImpl< MatrixType, Dense >::coeffRef (Index row, Index col) inline
Definition at line 120 of file Transpose.h.
References EIGEN_STATIC_ASSERT_LVALUE.
template<typename MatrixType > ScalarWithConstIfNotLvalue& Eigen::TransposeImpl< MatrixType, Dense >::coeffRef (Index index) inline
Definition at line 126 of file Transpose.h.
References EIGEN_STATIC_ASSERT_LVALUE.
template<typename MatrixType > const Scalar& Eigen::TransposeImpl< MatrixType, Dense >::coeffRef (Index row, Index col) const inline
Definition at line 132 of file Transpose.h.
template<typename MatrixType > const Scalar& Eigen::TransposeImpl< MatrixType, Dense >::coeffRef (Index index) const inline
Definition at line 137 of file Transpose.h.
template<typename MatrixType > ScalarWithConstIfNotLvalue* Eigen::TransposeImpl< MatrixType, Dense >::data () inline
Definition at line 117 of file Transpose.h.
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression().
template<typename MatrixType > const Scalar* Eigen::TransposeImpl< MatrixType, Dense >::data () const inline
Definition at line 118 of file Transpose.h.
template<typename MatrixType > Index Eigen::TransposeImpl< MatrixType, Dense >::innerStride () const inline
Definition at line 108 of file Transpose.h.
template<typename MatrixType > Index Eigen::TransposeImpl< MatrixType, Dense >::outerStride () const inline
Definition at line 109 of file Transpose.h.
template<typename MatrixType > template<int LoadMode> const PacketScalar Eigen::TransposeImpl< MatrixType, Dense >::packet (Index row, Index col) const inline
Definition at line 153 of file Transpose.h.
References col(), and row().
template<typename MatrixType > template<int LoadMode> const PacketScalar Eigen::TransposeImpl< MatrixType, Dense >::packet (Index index) const inline
Definition at line 165 of file Transpose.h.
template<typename MatrixType > template<int LoadMode> void Eigen::TransposeImpl< MatrixType, Dense >::writePacket (Index row, Index col, const PacketScalar & x) inline
Definition at line 159 of file Transpose.h.
References col(), and row().
template<typename MatrixType > template<int LoadMode> void Eigen::TransposeImpl< MatrixType, Dense >::writePacket (Index index, const PacketScalar & x) inline
Definition at line 171 of file Transpose.h.
The documentation for this class was generated from the following file:
include/Eigen/src/Core/Transpose.h