LIA_RAL: TabWeight Class Reference
TabWeight Class Reference
#include <GeneralTools.h>
Public Member Functions
TabWeight ()
TabWeight (const MixtureGD &)
TabWeight (const MixtureGD &, unsigned long)
TabWeight (const MixtureGD &, double)
void init (const MixtureGD &, unsigned long)
void init (const MixtureGD &, double)
unsigned long getNbTop ()
unsigned long getDistrib (unsigned long id)
double getWeight (unsigned long id)
void setDistrib (unsigned long id, unsigned long distrib, double weight)
TabWeightElem * getArray ()
~TabWeight ()
Private Member Functions
void _sortByWeight (const MixtureGD &data)
void _nbTopDyn (double threshold)
Private Attributes
unsigned long _size
TabWeightElem * _tab
unsigned long _nbTop
Detailed Description
Definition at line 153 of file GeneralTools.h.
Constructor & Destructor Documentation
TabWeight::TabWeight () inline
Definition at line 171 of file GeneralTools.h.
TabWeight::TabWeight (const MixtureGD & model)
Definition at line 293 of file GeneralTools.cpp.
References init().
TabWeight::TabWeight (const MixtureGD & model, unsigned long topDistribs)
Definition at line 296 of file GeneralTools.cpp.
References init().
TabWeight::TabWeight (const MixtureGD & model, double threshold)
Definition at line 299 of file GeneralTools.cpp.
References init().
TabWeight::~TabWeight () inline
Definition at line 182 of file GeneralTools.h.
Member Function Documentation
void TabWeight::_nbTopDyn (double threshold) inline private
Definition at line 165 of file GeneralTools.h.
References verbose.
Referenced by init().
void TabWeight::_sortByWeight (const MixtureGD & data) inline private
Definition at line 157 of file GeneralTools.h.
References _compF().
Referenced by init().
TabWeightElem* TabWeight::getArray () inline
Definition at line 181 of file GeneralTools.h.
Referenced by likelihoodGD().
unsigned long TabWeight::getDistrib (unsigned long id) inline
Definition at line 178 of file GeneralTools.h.
Referenced by likelihoodGD(), and selectComponent().
unsigned long TabWeight::getNbTop () inline
Definition at line 177 of file GeneralTools.h.
Referenced by likelihoodGD().
double TabWeight::getWeight (unsigned long id) inline
Definition at line 179 of file GeneralTools.h.
Referenced by likelihoodGD().
void TabWeight::init (const MixtureGD & model, unsigned long topDistribs)
Definition at line 281 of file GeneralTools.cpp.
References _nbTop, _size, _sortByWeight(), and _tab.
Referenced by TabWeight().
void TabWeight::init (const MixtureGD & model, double threshold)
Definition at line 287 of file GeneralTools.cpp.
References _nbTopDyn(), _size, _sortByWeight(), and _tab.
void TabWeight::setDistrib (unsigned long id, unsigned long distrib, double weight) inline
Definition at line 180 of file GeneralTools.h.
Member Data Documentation
unsigned long TabWeight::_nbTop private
Definition at line 156 of file GeneralTools.h.
Referenced by init().
unsigned long TabWeight::_size private
Definition at line 154 of file GeneralTools.h.
Referenced by init().
TabWeightElem* TabWeight::_tab private
Definition at line 155 of file GeneralTools.h.
Referenced by init().
The documentation for this class was generated from the following files:
LIA_SpkTools/include/GeneralTools.h
LIA_SpkTools/src/GeneralTools.cpp