LIA_RAL: Eigen::PastixLLT< _MatrixType, Options > Class Template Reference
Eigen::PastixLLT< _MatrixType, Options > Class Template Reference
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
#include <PaStiXSupport.h>
Public Types
enum { UpLo = _UpLo }
typedef _MatrixType MatrixType
typedef PastixBase< PastixLLT
< MatrixType, _UpLo > > Base
typedef Base::ColSpMatrix ColSpMatrix
Public Types inherited from Eigen::PastixBase< PastixLLT< _MatrixType, _UpLo > >
typedef
internal::pastix_traits
< PastixLLT< _MatrixType,
_UpLo > >::MatrixType _MatrixType
typedef _MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
typedef Matrix< Scalar,
Dynamic, 1 > Vector
typedef SparseMatrix< Scalar,
ColMajor > ColSpMatrix
Public Member Functions
PastixLLT ()
PastixLLT (const MatrixType &matrix)
void compute (const MatrixType &matrix)
void analyzePattern (const MatrixType &matrix)
void factorize (const MatrixType &matrix)
Public Member Functions inherited from Eigen::PastixBase< PastixLLT< _MatrixType, _UpLo > >
PastixBase ()
~PastixBase ()
const internal::solve_retval
< PastixBase, Rhs > solve (const MatrixBase< Rhs > &b) const
const
internal::sparse_solve_retval
< PastixBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
bool _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &x) const
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
PastixLLT< _MatrixType, _UpLo > & derived ()
const PastixLLT< _MatrixType,
_UpLo > & derived () const
Array< Index, IPARM_SIZE, 1 > & iparm ()
int & iparm (int idxparam)
Array< RealScalar, IPARM_SIZE, 1 > & dparm ()
double & dparm (int idxparam)
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
Protected Member Functions
void init ()
void grabMatrix (const MatrixType &matrix, ColSpMatrix &out)
Protected Member Functions inherited from Eigen::PastixBase< PastixLLT< _MatrixType, _UpLo > >
void init ()
void analyzePattern (ColSpMatrix &mat)
void factorize (ColSpMatrix &mat)
void clean ()
void compute (ColSpMatrix &mat)
Additional Inherited Members
Protected Attributes inherited from Eigen::PastixBase< PastixLLT< _MatrixType, _UpLo > >
int m_initisOk
int m_analysisIsOk
int m_factorizationIsOk
bool m_isInitialized
ComputationInfo m_info
pastix_data_t * m_pastixdata
int m_comm
Matrix< int, IPARM_SIZE, 1 > m_iparm
Matrix< double, DPARM_SIZE, 1 > m_dparm
Matrix< Index, Dynamic, 1 > m_perm
Matrix< Index, Dynamic, 1 > m_invp
int m_size
Detailed Description
template<typename _MatrixType, int Options>
class Eigen::PastixLLT< _MatrixType, Options >
A sparse direct supernodal Cholesky (LLT) factorization and solver based on the PaStiX library.
This class is used to solve the linear systems A.X = B via a LL^T supernodal Cholesky factorization available in the PaStiX library. The matrix A should be symmetric and positive definite WARNING Selfadjoint complex matrices are not supported in the current version of PaStiX The vectors or matrices X and B can be either dense or sparse
Template Parameters
MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
UpLo The part of the matrix to use : Lower or Upper. The default is Lower as required by PaStiX
See Also
TutorialSparseDirectSolvers
Definition at line 24 of file PaStiXSupport.h.
Member Typedef Documentation
template<typename _MatrixType , int Options> typedef PastixBase<PastixLLT<MatrixType, _UpLo> > Eigen::PastixLLT< _MatrixType, Options >::Base
Definition at line 566 of file PaStiXSupport.h.
template<typename _MatrixType , int Options> typedef Base::ColSpMatrix Eigen::PastixLLT< _MatrixType, Options >::ColSpMatrix
Definition at line 567 of file PaStiXSupport.h.
template<typename _MatrixType , int Options> typedef _MatrixType Eigen::PastixLLT< _MatrixType, Options >::MatrixType
Definition at line 565 of file PaStiXSupport.h.
Member Enumeration Documentation
template<typename _MatrixType , int Options> anonymous enum
Enumerator
UpLo
Definition at line 570 of file PaStiXSupport.h.
Constructor & Destructor Documentation
template<typename _MatrixType , int Options> Eigen::PastixLLT< _MatrixType, Options >::PastixLLT () inline
Definition at line 571 of file PaStiXSupport.h.
References Eigen::PastixLLT< _MatrixType, Options >::init().
template<typename _MatrixType , int Options> Eigen::PastixLLT< _MatrixType, Options >::PastixLLT (const MatrixType & matrix) inline
Definition at line 576 of file PaStiXSupport.h.
References Eigen::PastixLLT< _MatrixType, Options >::compute(), and Eigen::PastixLLT< _MatrixType, Options >::init().
Member Function Documentation
template<typename _MatrixType , int Options> void Eigen::PastixLLT< _MatrixType, Options >::analyzePattern (const MatrixType & matrix) inline
Compute the LL^T symbolic factorization of matrix using its sparsity pattern The result of this operation can be used with successive matrices having the same pattern as matrix
See Also
factorize()
Definition at line 596 of file PaStiXSupport.h.
References Eigen::PastixBase< Derived >::analyzePattern(), and Eigen::PastixLLT< _MatrixType, Options >::grabMatrix().
template<typename _MatrixType , int Options> void Eigen::PastixLLT< _MatrixType, Options >::compute (const MatrixType & matrix) inline
Compute the L factor of the LL^T supernodal factorization of matrix
See Also
analyzePattern() factorize()
Definition at line 585 of file PaStiXSupport.h.
References Eigen::PastixBase< Derived >::compute(), and Eigen::PastixLLT< _MatrixType, Options >::grabMatrix().
Referenced by Eigen::PastixLLT< _MatrixType, Options >::PastixLLT().
template<typename _MatrixType , int Options> void Eigen::PastixLLT< _MatrixType, Options >::factorize (const MatrixType & matrix) inline
Compute the LL^T supernodal numerical factorization of matrix
See Also
analyzePattern()
Definition at line 605 of file PaStiXSupport.h.
References Eigen::PastixBase< Derived >::factorize(), and Eigen::PastixLLT< _MatrixType, Options >::grabMatrix().
template<typename _MatrixType , int Options> void Eigen::PastixLLT< _MatrixType, Options >::grabMatrix (const MatrixType & matrix, ColSpMatrix & out) inline protected
Definition at line 620 of file PaStiXSupport.h.
References Eigen::internal::c_to_fortran_numbering().
Referenced by Eigen::PastixLLT< _MatrixType, Options >::analyzePattern(), Eigen::PastixLLT< _MatrixType, Options >::compute(), and Eigen::PastixLLT< _MatrixType, Options >::factorize().
template<typename _MatrixType , int Options> void Eigen::PastixLLT< _MatrixType, Options >::init () inline protected
Definition at line 614 of file PaStiXSupport.h.
References Eigen::PastixBase< PastixLLT< _MatrixType, _UpLo > >::m_iparm.
Referenced by Eigen::PastixLLT< _MatrixType, Options >::PastixLLT().
The documentation for this class was generated from the following file:
include/Eigen/src/PaStiXSupport/PaStiXSupport.h