LIA_RAL: Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
#include <JacobiSVD.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
Options = MatrixType::Options
}
typedef MatrixType::Index Index
typedef MatrixType::Scalar Scalar
typedef Matrix< Scalar,
ColsAtCompileTime,
RowsAtCompileTime, Options,
MaxColsAtCompileTime,
MaxRowsAtCompileTime > TransposeTypeWithSameStorageOrder
Public Member Functions
void allocate (const JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > &svd)
bool run (JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > &svd, const MatrixType &matrix)
Private Attributes
ColPivHouseholderQR
< TransposeTypeWithSameStorageOrder > m_qr
TransposeTypeWithSameStorageOrder m_adjoint
internal::plain_row_type
< MatrixType >::type m_workspace
Detailed Description
template<typename MatrixType>
class Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
Definition at line 191 of file JacobiSVD.h.
Member Typedef Documentation
template<typename MatrixType > typedef MatrixType::Index Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::Index
Definition at line 194 of file JacobiSVD.h.
template<typename MatrixType > typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::Scalar
Definition at line 195 of file JacobiSVD.h.
template<typename MatrixType > typedef Matrix<Scalar, ColsAtCompileTime, RowsAtCompileTime, Options, MaxColsAtCompileTime, MaxRowsAtCompileTime> Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::TransposeTypeWithSameStorageOrder
Definition at line 206 of file JacobiSVD.h.
Member Enumeration Documentation
template<typename MatrixType > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Options
Definition at line 196 of file JacobiSVD.h.
Member Function Documentation
template<typename MatrixType > void Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate (const JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > & svd) inline
Definition at line 208 of file JacobiSVD.h.
References Eigen::JacobiSVD< MatrixType, QRPreconditioner >::cols(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullV, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeThinV, and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::rows().
template<typename MatrixType > bool Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run (JacobiSVD< MatrixType, ColPivHouseholderQRPreconditioner > & svd, const MatrixType & matrix) inline
Definition at line 219 of file JacobiSVD.h.
References Eigen::JacobiSVD< MatrixType, QRPreconditioner >::computeU(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeFullV, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_computeThinV, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixV, and Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_workMatrix.
Member Data Documentation
template<typename MatrixType > TransposeTypeWithSameStorageOrder Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_adjoint private
Definition at line 241 of file JacobiSVD.h.
template<typename MatrixType > ColPivHouseholderQR<TransposeTypeWithSameStorageOrder> Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_qr private
Definition at line 240 of file JacobiSVD.h.
template<typename MatrixType > internal::plain_row_type<MatrixType>::type Eigen::internal::qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_workspace private
Definition at line 242 of file JacobiSVD.h.
The documentation for this class was generated from the following file:
include/Eigen/src/SVD/JacobiSVD.h