LIA_RAL: ReadMemory Class Reference
ReadMemory Class Reference
#include <SequenceExtractor.h>
Public Member Functions
ReadMemory (String, int, unsigned long, unsigned long)
~ReadMemory ()
bool notEof ()
bool eof ()
bool lecture (bool)
unsigned long getIdx ()
short int getCurrentSymb ()
void setIdx (unsigned long idx)
Private Member Functions
bool readSymb (short int &, string &)
Private Attributes
ifstream _inputFile
unsigned long _idx
unsigned long _realIdx
short int * _buf
int _bufSize
unsigned long _begin
unsigned long _length
bool _segmental
Detailed Description
Definition at line 82 of file SequenceExtractor.h.
Constructor & Destructor Documentation
ReadMemory::ReadMemory (String inputFilename, int bufSize = 100, unsigned long begin = 0, unsigned long length = 0)
Definition at line 310 of file SequenceExtractor.cpp.
References _begin, _buf, _bufSize, _idx, _inputFile, _length, _realIdx, and _segmental.
ReadMemory::~ReadMemory ()
Definition at line 320 of file SequenceExtractor.cpp.
References _buf, and _inputFile.
Member Function Documentation
bool ReadMemory::eof ()
Definition at line 328 of file SequenceExtractor.cpp.
References notEof().
Referenced by SequenceDecoder::_decode().
short int ReadMemory::getCurrentSymb ()
Definition at line 379 of file SequenceExtractor.cpp.
References _buf, _bufSize, and _idx.
Referenced by SequenceDecoder::_decode(), and SequenceDecoder::decode().
unsigned long ReadMemory::getIdx ()
Definition at line 376 of file SequenceExtractor.cpp.
References _idx.
Referenced by SequenceDecoder::_decode(), and SequenceDecoder::decode().
bool ReadMemory::lecture (bool init = false)
Definition at line 350 of file SequenceExtractor.cpp.
References _begin, _buf, _bufSize, _idx, _realIdx, _segmental, notEof(), and readSymb().
Referenced by SequenceDecoder::_decode(), and SequenceDecoder::decode().
bool ReadMemory::notEof ()
Definition at line 324 of file SequenceExtractor.cpp.
References _begin, _idx, _inputFile, _length, and _segmental.
Referenced by SequenceDecoder::decode(), eof(), lecture(), and readSymb().
bool ReadMemory::readSymb (short int & symb, string & oov) private
Definition at line 331 of file SequenceExtractor.cpp.
References _idx, _inputFile, debug, and notEof().
Referenced by lecture().
void ReadMemory::setIdx (unsigned long idx)
Definition at line 382 of file SequenceExtractor.cpp.
References _idx.
Referenced by SequenceDecoder::_decode(), and SequenceDecoder::decode().
Member Data Documentation
unsigned long ReadMemory::_begin private
Definition at line 88 of file SequenceExtractor.h.
Referenced by lecture(), notEof(), and ReadMemory().
short int* ReadMemory::_buf private
Definition at line 86 of file SequenceExtractor.h.
Referenced by getCurrentSymb(), lecture(), ReadMemory(), and ~ReadMemory().
int ReadMemory::_bufSize private
Definition at line 87 of file SequenceExtractor.h.
Referenced by getCurrentSymb(), lecture(), and ReadMemory().
unsigned long ReadMemory::_idx private
Definition at line 84 of file SequenceExtractor.h.
Referenced by getCurrentSymb(), getIdx(), lecture(), notEof(), ReadMemory(), readSymb(), and setIdx().
ifstream ReadMemory::_inputFile private
Definition at line 83 of file SequenceExtractor.h.
Referenced by notEof(), ReadMemory(), readSymb(), and ~ReadMemory().
unsigned long ReadMemory::_length private
Definition at line 89 of file SequenceExtractor.h.
Referenced by notEof(), and ReadMemory().
unsigned long ReadMemory::_realIdx private
Definition at line 85 of file SequenceExtractor.h.
Referenced by lecture(), and ReadMemory().
bool ReadMemory::_segmental private
Definition at line 90 of file SequenceExtractor.h.
Referenced by lecture(), notEof(), and ReadMemory().
The documentation for this class was generated from the following files:
LIA_Utils/SequenceExtractor/include/SequenceExtractor.h
LIA_Utils/SequenceExtractor/src/SequenceExtractor.cpp