LIA_RAL: Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > Class Template Reference
Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > Class Template Reference
Permutation matrix.
#include <PermutationMatrix.h>
Public Types
typedef Traits::IndicesType IndicesType
Public Types inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >
enum
typedef Traits::IndicesType IndicesType
typedef Traits::Scalar Scalar
typedef Traits::Index Index
typedef Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime,
0, MaxRowsAtCompileTime,
MaxColsAtCompileTime > DenseMatrixType
typedef PermutationMatrix
< IndicesType::SizeAtCompileTime,
IndicesType::MaxSizeAtCompileTime,
Index > PlainPermutationType
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
PermutationMatrix ()
PermutationMatrix (int size)
template<typename OtherDerived >
PermutationMatrix (const PermutationBase< OtherDerived > &other)
PermutationMatrix (const PermutationMatrix &other)
template<typename Other >
PermutationMatrix (const MatrixBase< Other > &indices)
template<typename Other >
PermutationMatrix (const TranspositionsBase< Other > &tr)
template<typename Other >
PermutationMatrix & operator= (const PermutationBase< Other > &other)
template<typename Other >
PermutationMatrix & operator= (const TranspositionsBase< Other > &tr)
PermutationMatrix & operator= (const PermutationMatrix &other)
const IndicesType & indices () const
IndicesType & indices ()
template<typename Other >
PermutationMatrix (const Transpose< PermutationBase< Other > > &other)
template<typename Lhs , typename Rhs >
PermutationMatrix (internal::PermPermProduct_t, const Lhs &lhs, const Rhs &rhs)
Public Member Functions inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >
PermutationMatrix
< SizeAtCompileTime,
MaxSizeAtCompileTime,
IndexType > & operator= (const PermutationBase< OtherDerived > &other)
PermutationMatrix
< SizeAtCompileTime,
MaxSizeAtCompileTime,
IndexType > & operator= (const TranspositionsBase< OtherDerived > &tr)
PermutationMatrix
< SizeAtCompileTime,
MaxSizeAtCompileTime,
IndexType > & operator= (const PermutationBase &other)
Index rows () const
Index cols () const
Index size () const
void evalTo (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
const IndicesType & indices () const
IndicesType & indices ()
void resize (Index size)
void setIdentity ()
void setIdentity (Index size)
PermutationMatrix
< SizeAtCompileTime,
MaxSizeAtCompileTime,
IndexType > & applyTranspositionOnTheLeft (Index i, Index j)
PermutationMatrix
< SizeAtCompileTime,
MaxSizeAtCompileTime,
IndexType > & applyTranspositionOnTheRight (Index i, Index j)
Transpose< PermutationBase > inverse () const
Transpose< PermutationBase > transpose () const
PlainPermutationType operator* (const PermutationBase< Other > &other) const
PlainPermutationType operator* (const Transpose< PermutationBase< Other > > &other) const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Protected Attributes
IndicesType m_indices
Private Types
typedef PermutationBase
< PermutationMatrix > Base
typedef internal::traits
< PermutationMatrix > Traits
Additional Inherited Members
Protected Member Functions inherited from Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >
void assignTranspose (const PermutationBase< OtherDerived > &other)
void assignProduct (const Lhs &lhs, const Rhs &rhs)
Detailed Description
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType>
class Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >
Permutation matrix.
Parameters
SizeAtCompileTime the number of rows/cols, or Dynamic
MaxSizeAtCompileTime the maximum number of rows/cols, or Dynamic. This optional parameter defaults to SizeAtCompileTime. Most of the time, you should not have to specify it.
IndexType the interger type of the indices
This class represents a permutation matrix, internally stored as a vector of integers.
See Also
class PermutationBase, class PermutationWrapper, class DiagonalMatrix
Definition at line 283 of file PermutationMatrix.h.
Member Typedef Documentation
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> typedef PermutationBase<PermutationMatrix> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::Base private
Definition at line 285 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> typedef Traits::IndicesType Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::IndicesType
Definition at line 290 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> typedef internal::traits<PermutationMatrix> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::Traits private
Definition at line 286 of file PermutationMatrix.h.
Constructor & Destructor Documentation
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix () inline
Definition at line 293 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix (int size) inline
Constructs an uninitialized permutation matrix of given size.
Definition at line 298 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> template<typename OtherDerived > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix (const PermutationBase< OtherDerived > & other) inline
Copy constructor.
Definition at line 303 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix (const PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & other) inline
Standard copy constructor. Defined only to prevent a default copy constructor from hiding the other templated constructor
Definition at line 309 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix (const MatrixBase< Other > & indices) inline explicit
Generic constructor from expression of the indices. The indices array has the meaning that the permutations sends each integer i to indices[i].
Warning
It is your responsibility to check that the indices array that you passes actually describes a permutation, i.e., each value between 0 and n-1 occurs exactly once, where n is the array's size.
Definition at line 320 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix (const TranspositionsBase< Other > & tr) inline explicit
Convert the Transpositions tr to a permutation matrix
Definition at line 325 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> template<typename Other > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix (const Transpose< PermutationBase< Other > > & other) inline
Definition at line 367 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> template<typename Lhs , typename Rhs > Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::PermutationMatrix (internal::PermPermProduct_t , const Lhs & lhs, const Rhs & rhs) inline
Definition at line 373 of file PermutationMatrix.h.
Member Function Documentation
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> const IndicesType& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices () const inline
const version of indices().
Definition at line 358 of file PermutationMatrix.h.
Referenced by Eigen::internal::permut_sparsematrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo(), Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo(), and Eigen::internal::minimum_degree_ordering().
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> IndicesType& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices () inline
Returns
a reference to the stored array representing the permutation.
Definition at line 360 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> template<typename Other > PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::operator= (const PermutationBase< Other > & other) inline
Copies the other permutation into *this
Definition at line 333 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> template<typename Other > PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::operator= (const TranspositionsBase< Other > & tr) inline
Assignment from the Transpositions tr
Definition at line 341 of file PermutationMatrix.h.
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> PermutationMatrix& Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::operator= (const PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
Definition at line 350 of file PermutationMatrix.h.
Member Data Documentation
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType> IndicesType Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::m_indices protected
Definition at line 382 of file PermutationMatrix.h.
Referenced by Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::indices(), Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=(), and Eigen::PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::PermutationMatrix().
The documentation for this class was generated from the following file:
include/Eigen/src/Core/PermutationMatrix.h