LIA_RAL: Eigen::TriangularView< _MatrixType, _Mode > Class Template Reference
Eigen::TriangularView< _MatrixType, _Mode > Class Template Reference
Base class for triangular part in a matrix.
#include <TriangularMatrix.h>
Public Types
enum { Mode = _Mode, TransposeMode }
typedef TriangularBase
< TriangularView > Base
typedef internal::traits
< TriangularView >::Scalar Scalar
typedef _MatrixType MatrixType
typedef internal::traits
< TriangularView >
::DenseMatrixType DenseMatrixType
typedef DenseMatrixType PlainObject
typedef internal::traits
< TriangularView >
::StorageKind StorageKind
typedef internal::traits
< TriangularView >::Index Index
Public Types inherited from Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >
enum
typedef internal::traits
< TriangularView< _MatrixType,
_Mode > >::Scalar Scalar
typedef internal::traits
< TriangularView< _MatrixType,
_Mode > >::StorageKind StorageKind
typedef internal::traits
< TriangularView< _MatrixType,
_Mode > >::Index Index
typedef internal::traits
< TriangularView< _MatrixType,
_Mode > >::DenseMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
Public Types inherited from Eigen::EigenBase< Derived >
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
TriangularView (const MatrixType &matrix)
Index rows () const
Index cols () const
Index outerStride () const
Index innerStride () const
template<typename Other >
TriangularView & operator+= (const DenseBase< Other > &other)
template<typename Other >
TriangularView & operator-= (const DenseBase< Other > &other)
TriangularView & operator*= (const typename internal::traits< MatrixType >::Scalar &other)
TriangularView & operator/= (const typename internal::traits< MatrixType >::Scalar &other)
void fill (const Scalar &value)
TriangularView & setConstant (const Scalar &value)
TriangularView & setZero ()
TriangularView & setOnes ()
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
const MatrixTypeNestedCleaned & nestedExpression () const
MatrixTypeNestedCleaned & nestedExpression ()
template<typename OtherDerived >
TriangularView & operator= (const TriangularBase< OtherDerived > &other)
template<typename OtherDerived >
TriangularView & operator= (const MatrixBase< OtherDerived > &other)
TriangularView & operator= (const TriangularView &other)
template<typename OtherDerived >
void lazyAssign (const TriangularBase< OtherDerived > &other)
template<typename OtherDerived >
void lazyAssign (const MatrixBase< OtherDerived > &other)
TriangularView
< MatrixConjugateReturnType,
Mode > conjugate ()
const TriangularView
< MatrixConjugateReturnType,
Mode > conjugate () const
const TriangularView< const
typename
MatrixType::AdjointReturnType,
TransposeMode > adjoint () const
TriangularView< Transpose
< MatrixType >, TransposeMode > transpose ()
const TriangularView
< Transpose< MatrixType >
, TransposeMode > transpose () const
template<typename OtherDerived >
TriangularProduct< Mode, true,
MatrixType, false,
OtherDerived,
OtherDerived::IsVectorAtCompileTime > operator* (const MatrixBase< OtherDerived > &rhs) const
template<int Side, typename Other >
const
internal::triangular_solve_retval
< Side, TriangularView, Other > solve (const MatrixBase< Other > &other) const
template<int Side, typename OtherDerived >
void solveInPlace (const MatrixBase< OtherDerived > &other) const
template<typename Other >
const
internal::triangular_solve_retval
< OnTheLeft, TriangularView,
Other > solve (const MatrixBase< Other > &other) const
template<typename OtherDerived >
void solveInPlace (const MatrixBase< OtherDerived > &other) const
const SelfAdjointView
< MatrixTypeNestedNonRef, Mode > selfadjointView () const
SelfAdjointView
< MatrixTypeNestedNonRef, Mode > selfadjointView ()
template<typename OtherDerived >
void swap (TriangularBase< OtherDerived > const &other)
template<typename OtherDerived >
void swap (MatrixBase< OtherDerived > const &other)
Scalar determinant () const
template<typename ProductDerived , typename Lhs , typename Rhs >
EIGEN_STRONG_INLINE
TriangularView & operator= (const ProductBase< ProductDerived, Lhs, Rhs > &other)
template<typename ProductDerived , typename Lhs , typename Rhs >
EIGEN_STRONG_INLINE
TriangularView & operator+= (const ProductBase< ProductDerived, Lhs, Rhs > &other)
template<typename ProductDerived , typename Lhs , typename Rhs >
EIGEN_STRONG_INLINE
TriangularView & operator-= (const ProductBase< ProductDerived, Lhs, Rhs > &other)
template<typename ProductDerived >
EIGEN_STRONG_INLINE
TriangularView & operator= (const ScaledProduct< ProductDerived > &other)
template<typename ProductDerived >
EIGEN_STRONG_INLINE
TriangularView & operator+= (const ScaledProduct< ProductDerived > &other)
template<typename ProductDerived >
EIGEN_STRONG_INLINE
TriangularView & operator-= (const ScaledProduct< ProductDerived > &other)
template<typename ProductDerived , typename _Lhs , typename _Rhs >
TriangularView< MatrixType,
UpLo > & assignProduct (const ProductBase< ProductDerived, _Lhs, _Rhs > &prod, const Scalar &alpha)
template<int Side, typename Other >
const
internal::triangular_solve_retval
< Side, TriangularView
< Derived, Mode >, Other > solve (const MatrixBase< Other > &other) const
template<typename OtherDerived >
TriangularView< MatrixType,
Mode > & operator= (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
TriangularView< MatrixType,
Mode > & operator= (const TriangularBase< OtherDerived > &other)
Public Member Functions inherited from Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >
TriangularBase ()
Index rows () const
Index cols () const
Index outerStride () const
Index innerStride () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
Scalar operator() (Index row, Index col) const
Scalar & operator() (Index row, Index col)
const TriangularView
< _MatrixType, _Mode > & derived () const
TriangularView< _MatrixType,
_Mode > & derived ()
void evalTo (MatrixBase< DenseDerived > &other) const
void evalToLazy (MatrixBase< DenseDerived > &other) const
DenseMatrixType toDenseMatrix () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Protected Types
typedef internal::traits
< TriangularView >
::MatrixTypeNested MatrixTypeNested
typedef internal::traits
< TriangularView >
::MatrixTypeNestedNonRef MatrixTypeNestedNonRef
typedef internal::traits
< TriangularView >
::MatrixTypeNestedCleaned MatrixTypeNestedCleaned
typedef internal::remove_all
< typename
MatrixType::ConjugateReturnType >
::type MatrixConjugateReturnType
Protected Member Functions
template<typename ProductDerived , typename Lhs , typename Rhs >
EIGEN_STRONG_INLINE
TriangularView & assignProduct (const ProductBase< ProductDerived, Lhs, Rhs > &prod, const Scalar &alpha)
Protected Member Functions inherited from Eigen::TriangularBase< TriangularView< _MatrixType, _Mode > >
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Protected Attributes
MatrixTypeNested m_matrix
Friends
template<typename OtherDerived >
TriangularProduct< Mode, false,
OtherDerived,
OtherDerived::IsVectorAtCompileTime,
MatrixType, false > operator* (const MatrixBase< OtherDerived > &lhs, const TriangularView &rhs)
Detailed Description
template<typename _MatrixType, unsigned int _Mode>
class Eigen::TriangularView< _MatrixType, _Mode >
Base class for triangular part in a matrix.
Parameters
MatrixType the type of the object in which we are taking the triangular part
Mode the kind of triangular matrix expression to construct. Can be Upper, Lower, UnitUpper, UnitLower, StrictlyUpper, or StrictlyLower. This is in fact a bit field; it must have either Upper or Lower, and additionnaly it may have UnitDiag or ZeroDiag or neither.
This class represents a triangular part of a matrix, not necessarily square. Strictly speaking, for rectangular matrices one should speak of "trapezoid" parts. This class is the return type of MatrixBase::triangularView() and most of the time this is the only way it is used.
See Also
MatrixBase::triangularView()
Definition at line 158 of file TriangularMatrix.h.
Member Typedef Documentation
template<typename _MatrixType, unsigned int _Mode> typedef TriangularBase<TriangularView> Eigen::TriangularView< _MatrixType, _Mode >::Base
Definition at line 163 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::traits<TriangularView>::DenseMatrixType Eigen::TriangularView< _MatrixType, _Mode >::DenseMatrixType
Definition at line 167 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::traits<TriangularView>::Index Eigen::TriangularView< _MatrixType, _Mode >::Index
Definition at line 182 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::remove_all<typename MatrixType::ConjugateReturnType>::type Eigen::TriangularView< _MatrixType, _Mode >::MatrixConjugateReturnType protected
Definition at line 175 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef _MatrixType Eigen::TriangularView< _MatrixType, _Mode >::MatrixType
Definition at line 166 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::traits<TriangularView>::MatrixTypeNested Eigen::TriangularView< _MatrixType, _Mode >::MatrixTypeNested protected
Definition at line 171 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::traits<TriangularView>::MatrixTypeNestedCleaned Eigen::TriangularView< _MatrixType, _Mode >::MatrixTypeNestedCleaned protected
Definition at line 173 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::traits<TriangularView>::MatrixTypeNestedNonRef Eigen::TriangularView< _MatrixType, _Mode >::MatrixTypeNestedNonRef protected
Definition at line 172 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef DenseMatrixType Eigen::TriangularView< _MatrixType, _Mode >::PlainObject
Definition at line 168 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::traits<TriangularView>::Scalar Eigen::TriangularView< _MatrixType, _Mode >::Scalar
Definition at line 164 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> typedef internal::traits<TriangularView>::StorageKind Eigen::TriangularView< _MatrixType, _Mode >::StorageKind
Definition at line 181 of file TriangularMatrix.h.
Member Enumeration Documentation
template<typename _MatrixType, unsigned int _Mode> anonymous enum
Enumerator
Mode
TransposeMode
Definition at line 184 of file TriangularMatrix.h.
Constructor & Destructor Documentation
template<typename _MatrixType, unsigned int _Mode> Eigen::TriangularView< _MatrixType, _Mode >::TriangularView (const MatrixType & matrix) inline
Definition at line 192 of file TriangularMatrix.h.
Member Function Documentation
template<typename _MatrixType, unsigned int _Mode> const TriangularView<const typename MatrixType::AdjointReturnType,TransposeMode> Eigen::TriangularView< _MatrixType, _Mode >::adjoint () const inline
See Also
MatrixBase::adjoint() const
Definition at line 264 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
Referenced by Eigen::internal::apply_block_householder_on_the_left(), Eigen::internal::LLT_Traits< MatrixType, Upper >::getL(), Eigen::internal::LDLT_Traits< MatrixType, Upper >::getL(), Eigen::internal::LLT_Traits< MatrixType, Lower >::getU(), and Eigen::internal::LDLT_Traits< MatrixType, Lower >::getU().
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived , typename _Lhs , typename _Rhs > TriangularView<MatrixType,UpLo>& Eigen::TriangularView< _MatrixType, _Mode >::assignProduct (const ProductBase< ProductDerived, _Lhs, _Rhs > & prod, const Scalar & alpha)
Definition at line 185 of file GeneralMatrixMatrixTriangular.h.
References Eigen::ColMajor, Eigen::ProductBase< Derived, Lhs, Rhs >::lhs(), Eigen::ProductBase< Derived, Lhs, Rhs >::rhs(), Eigen::RowMajor, and Eigen::RowMajorBit.
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived , typename Lhs , typename Rhs > EIGEN_STRONG_INLINE TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::assignProduct (const ProductBase< ProductDerived, Lhs, Rhs > & prod, const Scalar & alpha) protected
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::operator+=(), Eigen::TriangularView< _MatrixType, _Mode >::operator-=(), and Eigen::TriangularView< _MatrixType, _Mode >::operator=().
template<typename _MatrixType, unsigned int _Mode> Scalar Eigen::TriangularView< _MatrixType, _Mode >::coeff (Index row, Index col) const inline
See Also
MatrixBase::coeff()
Warning
the coordinates must fit into the referenced triangular part
Definition at line 222 of file TriangularMatrix.h.
References Eigen::TriangularBase< Derived >::check_coordinates_internal(), and Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> Scalar& Eigen::TriangularView< _MatrixType, _Mode >::coeffRef (Index row, Index col) inline
See Also
MatrixBase::coeffRef()
Warning
the coordinates must fit into the referenced triangular part
Definition at line 231 of file TriangularMatrix.h.
References Eigen::TriangularBase< Derived >::check_coordinates_internal(), and Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> Index Eigen::TriangularView< _MatrixType, _Mode >::cols (void) const inline
Definition at line 196 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::setConstant().
template<typename _MatrixType, unsigned int _Mode> TriangularView<MatrixConjugateReturnType,Mode> Eigen::TriangularView< _MatrixType, _Mode >::conjugate () inline
See Also
MatrixBase::conjugate()
Definition at line 257 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> const TriangularView<MatrixConjugateReturnType,Mode> Eigen::TriangularView< _MatrixType, _Mode >::conjugate () const inline
See Also
MatrixBase::conjugate() const
Definition at line 260 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> Scalar Eigen::TriangularView< _MatrixType, _Mode >::determinant () const inline
Definition at line 368 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix, Eigen::TriangularView< _MatrixType, _Mode >::Mode, Eigen::UnitDiag, and Eigen::ZeroDiag.
template<typename _MatrixType, unsigned int _Mode> void Eigen::TriangularView< _MatrixType, _Mode >::fill (const Scalar & value) inline
See Also
MatrixBase::fill()
Definition at line 210 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::setConstant().
template<typename _MatrixType, unsigned int _Mode> Index Eigen::TriangularView< _MatrixType, _Mode >::innerStride () const inline
Definition at line 198 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename MatrixType , unsigned int Mode> template<typename OtherDerived > void Eigen::TriangularView< MatrixType, Mode >::lazyAssign (const TriangularBase< OtherDerived > & other)
Definition at line 647 of file TriangularMatrix.h.
References Eigen::TriangularBase< Derived >::cols(), Eigen::TriangularBase< Derived >::derived(), Eigen::Dynamic, eigen_assert, EIGEN_UNROLLING_LIMIT, and Eigen::TriangularBase< Derived >::rows().
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::swap().
template<typename MatrixType , unsigned int Mode> template<typename OtherDerived > void Eigen::TriangularView< MatrixType, Mode >::lazyAssign (const MatrixBase< OtherDerived > & other)
Definition at line 610 of file TriangularMatrix.h.
References Eigen::Dynamic, eigen_assert, and EIGEN_UNROLLING_LIMIT.
template<typename _MatrixType, unsigned int _Mode> const MatrixTypeNestedCleaned& Eigen::TriangularView< _MatrixType, _Mode >::nestedExpression () const inline
Definition at line 237 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::operator=().
template<typename _MatrixType, unsigned int _Mode> MatrixTypeNestedCleaned& Eigen::TriangularView< _MatrixType, _Mode >::nestedExpression () inline
Definition at line 238 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > TriangularProduct<Mode,true,MatrixType,false,OtherDerived, OtherDerived::IsVectorAtCompileTime> Eigen::TriangularView< _MatrixType, _Mode >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient triangular matrix times vector/matrix product
Definition at line 282 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix, and Eigen::TriangularView< _MatrixType, _Mode >::Mode.
template<typename _MatrixType, unsigned int _Mode> TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator*= (const typename internal::traits< MatrixType >::Scalar & other) inline
See Also
MatrixBase::operator*=()
Definition at line 205 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> template<typename Other > TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator+= (const DenseBase< Other > & other) inline
See Also
MatrixBase::operator+=()
Definition at line 201 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived , typename Lhs , typename Rhs > EIGEN_STRONG_INLINE TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator+= (const ProductBase< ProductDerived, Lhs, Rhs > & other) inline
Definition at line 387 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::assignProduct().
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived > EIGEN_STRONG_INLINE TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator+= (const ScaledProduct< ProductDerived > & other) inline
Definition at line 407 of file TriangularMatrix.h.
References Eigen::ScaledProduct< NestedProduct >::alpha(), and Eigen::TriangularView< _MatrixType, _Mode >::assignProduct().
template<typename _MatrixType, unsigned int _Mode> template<typename Other > TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator-= (const DenseBase< Other > & other) inline
See Also
MatrixBase::operator-=()
Definition at line 203 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived , typename Lhs , typename Rhs > EIGEN_STRONG_INLINE TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator-= (const ProductBase< ProductDerived, Lhs, Rhs > & other) inline
Definition at line 393 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::assignProduct().
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived > EIGEN_STRONG_INLINE TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator-= (const ScaledProduct< ProductDerived > & other) inline
Definition at line 413 of file TriangularMatrix.h.
References Eigen::ScaledProduct< NestedProduct >::alpha(), and Eigen::TriangularView< _MatrixType, _Mode >::assignProduct().
template<typename _MatrixType, unsigned int _Mode> TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator/= (const typename internal::traits< MatrixType >::Scalar & other) inline
See Also
MatrixBase::operator/=()
Definition at line 207 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator= (const TriangularBase< OtherDerived > & other)
Assigns a triangular matrix to a triangular part of a dense matrix
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator= (const MatrixBase< OtherDerived > & other)
template<typename _MatrixType, unsigned int _Mode> TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator= (const TriangularView< _MatrixType, _Mode > & other) inline
Definition at line 247 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::nestedExpression().
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived , typename Lhs , typename Rhs > EIGEN_STRONG_INLINE TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator= (const ProductBase< ProductDerived, Lhs, Rhs > & other) inline
Definition at line 380 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::assignProduct(), and Eigen::TriangularView< _MatrixType, _Mode >::setZero().
template<typename _MatrixType, unsigned int _Mode> template<typename ProductDerived > EIGEN_STRONG_INLINE TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::operator= (const ScaledProduct< ProductDerived > & other) inline
Definition at line 400 of file TriangularMatrix.h.
References Eigen::ScaledProduct< NestedProduct >::alpha(), Eigen::TriangularView< _MatrixType, _Mode >::assignProduct(), and Eigen::TriangularView< _MatrixType, _Mode >::setZero().
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > TriangularView<MatrixType, Mode>& Eigen::TriangularView< _MatrixType, _Mode >::operator= (const MatrixBase< OtherDerived > & other) inline
Definition at line 594 of file TriangularMatrix.h.
References Eigen::EvalBeforeAssigningBit.
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > TriangularView<MatrixType, Mode>& Eigen::TriangularView< _MatrixType, _Mode >::operator= (const TriangularBase< OtherDerived > & other) inline
Definition at line 631 of file TriangularMatrix.h.
References Eigen::TriangularBase< Derived >::cols(), Eigen::TriangularBase< Derived >::derived(), eigen_assert, Eigen::EvalBeforeAssigningBit, and Eigen::TriangularBase< Derived >::rows().
template<typename _MatrixType, unsigned int _Mode> Index Eigen::TriangularView< _MatrixType, _Mode >::outerStride () const inline
Definition at line 197 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> Index Eigen::TriangularView< _MatrixType, _Mode >::rows (void) const inline
Definition at line 195 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::setConstant().
template<typename _MatrixType, unsigned int _Mode> const SelfAdjointView<MatrixTypeNestedNonRef,Mode> Eigen::TriangularView< _MatrixType, _Mode >::selfadjointView () const inline
Definition at line 344 of file TriangularMatrix.h.
References EIGEN_STATIC_ASSERT, Eigen::TriangularView< _MatrixType, _Mode >::m_matrix, Eigen::TriangularView< _MatrixType, _Mode >::Mode, and Eigen::UnitDiag.
template<typename _MatrixType, unsigned int _Mode> SelfAdjointView<MatrixTypeNestedNonRef,Mode> Eigen::TriangularView< _MatrixType, _Mode >::selfadjointView () inline
Definition at line 349 of file TriangularMatrix.h.
References EIGEN_STATIC_ASSERT, Eigen::TriangularView< _MatrixType, _Mode >::m_matrix, Eigen::TriangularView< _MatrixType, _Mode >::Mode, and Eigen::UnitDiag.
template<typename _MatrixType, unsigned int _Mode> TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::setConstant (const Scalar & value) inline
See Also
MatrixBase::setConstant()
Definition at line 212 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::cols(), and Eigen::TriangularView< _MatrixType, _Mode >::rows().
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::fill(), Eigen::TriangularView< _MatrixType, _Mode >::setOnes(), and Eigen::TriangularView< _MatrixType, _Mode >::setZero().
template<typename _MatrixType, unsigned int _Mode> TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::setOnes () inline
See Also
MatrixBase::setOnes()
Definition at line 217 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::setConstant().
template<typename _MatrixType, unsigned int _Mode> TriangularView& Eigen::TriangularView< _MatrixType, _Mode >::setZero () inline
See Also
MatrixBase::setZero()
Definition at line 215 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::setConstant().
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::operator=().
template<typename _MatrixType, unsigned int _Mode> template<int Side, typename Other > const internal::triangular_solve_retval<Side,TriangularView<Derived,Mode>,Other> Eigen::TriangularView< _MatrixType, _Mode >::solve (const MatrixBase< Other > & other) const
Returns
the product of the inverse of *this with other, *this being triangular.
This function computes the inverse-matrix matrix product inverse(*this) * other if Side==OnTheLeft (the default), or the right-inverse-multiply other * inverse(*this) if Side==OnTheRight.
The matrix *this must be triangular and invertible (i.e., all the coefficients of the diagonal must be non zero). It works as a forward (resp. backward) substitution if *this is an upper (resp. lower) triangular matrix.
Example:
Output:
This function returns an expression of the inverse-multiply and can works in-place if it is assigned to the same matrix or vector other.
For users coming from BLAS, this function (and more specifically solveInPlace()) offer all the operations supported by the *TRSV and *TRSM BLAS routines.
See Also
TriangularView::solveInPlace()
Definition at line 216 of file SolveTriangular.h.
template<typename _MatrixType, unsigned int _Mode> template<int Side, typename Other > const internal::triangular_solve_retval<Side,TriangularView, Other> Eigen::TriangularView< _MatrixType, _Mode >::solve (const MatrixBase< Other > & other) const inline
template<typename _MatrixType, unsigned int _Mode> template<typename Other > const internal::triangular_solve_retval<OnTheLeft,TriangularView, Other> Eigen::TriangularView< _MatrixType, _Mode >::solve (const MatrixBase< Other > & other) const inline
Definition at line 337 of file TriangularMatrix.h.
template<typename MatrixType , unsigned int Mode> template<int Side, typename OtherDerived > void Eigen::TriangularView< MatrixType, Mode >::solveInPlace (const MatrixBase< OtherDerived > & _other) const
"in-place" version of TriangularView::solve() where the result is written in other
Warning
The parameter is only marked 'const' to make the C++ compiler accept a temporary expression here. This function will const_cast it, so constness isn't honored here.
See TriangularView:solve() for the details.
Definition at line 174 of file SolveTriangular.h.
References copy(), eigen_assert, Eigen::Lower, Eigen::OnTheLeft, Eigen::OnTheRight, Eigen::RowMajorBit, Eigen::Upper, and Eigen::ZeroDiag.
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > void Eigen::TriangularView< _MatrixType, _Mode >::solveInPlace (const MatrixBase< OtherDerived > & other) const inline
Definition at line 341 of file TriangularMatrix.h.
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > void Eigen::TriangularView< _MatrixType, _Mode >::swap (TriangularBase< OtherDerived > const & other) inline
Definition at line 356 of file TriangularMatrix.h.
References Eigen::TriangularBase< Derived >::derived(), Eigen::TriangularView< _MatrixType, _Mode >::m_matrix, and Eigen::TriangularView< _MatrixType, _Mode >::Mode.
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > void Eigen::TriangularView< _MatrixType, _Mode >::swap (MatrixBase< OtherDerived > const & other) inline
Definition at line 362 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::lazyAssign(), Eigen::TriangularView< _MatrixType, _Mode >::m_matrix, and Eigen::TriangularView< _MatrixType, _Mode >::Mode.
template<typename _MatrixType, unsigned int _Mode> TriangularView<Transpose<MatrixType>,TransposeMode> Eigen::TriangularView< _MatrixType, _Mode >::transpose () inline
See Also
MatrixBase::transpose()
Definition at line 268 of file TriangularMatrix.h.
References EIGEN_STATIC_ASSERT_LVALUE, and Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
template<typename _MatrixType, unsigned int _Mode> const TriangularView<Transpose<MatrixType>,TransposeMode> Eigen::TriangularView< _MatrixType, _Mode >::transpose () const inline
See Also
MatrixBase::transpose() const
Definition at line 274 of file TriangularMatrix.h.
References Eigen::TriangularView< _MatrixType, _Mode >::m_matrix.
Friends And Related Function Documentation
template<typename _MatrixType, unsigned int _Mode> template<typename OtherDerived > TriangularProduct<Mode,false,OtherDerived,OtherDerived::IsVectorAtCompileTime,MatrixType,false> operator* (const MatrixBase< OtherDerived > & lhs, const TriangularView< _MatrixType, _Mode > & rhs) friend
Efficient vector/matrix times triangular matrix product
Definition at line 292 of file TriangularMatrix.h.
Member Data Documentation
template<typename _MatrixType, unsigned int _Mode> MatrixTypeNested Eigen::TriangularView< _MatrixType, _Mode >::m_matrix protected
Definition at line 423 of file TriangularMatrix.h.
Referenced by Eigen::TriangularView< _MatrixType, _Mode >::adjoint(), Eigen::TriangularView< _MatrixType, _Mode >::coeff(), Eigen::TriangularView< _MatrixType, _Mode >::coeffRef(), Eigen::TriangularView< _MatrixType, _Mode >::cols(), Eigen::TriangularView< _MatrixType, _Mode >::conjugate(), Eigen::TriangularView< _MatrixType, _Mode >::determinant(), Eigen::TriangularView< _MatrixType, _Mode >::innerStride(), Eigen::TriangularView< _MatrixType, _Mode >::nestedExpression(), Eigen::TriangularView< _MatrixType, _Mode >::operator*(), Eigen::TriangularView< _MatrixType, _Mode >::operator*=(), Eigen::TriangularView< _MatrixType, _Mode >::operator+=(), Eigen::TriangularView< _MatrixType, _Mode >::operator-=(), Eigen::TriangularView< _MatrixType, _Mode >::operator/=(), Eigen::TriangularView< _MatrixType, _Mode >::outerStride(), Eigen::TriangularView< _MatrixType, _Mode >::rows(), Eigen::TriangularView< _MatrixType, _Mode >::selfadjointView(), Eigen::TriangularView< _MatrixType, _Mode >::swap(), and Eigen::TriangularView< _MatrixType, _Mode >::transpose().
The documentation for this class was generated from the following files:
include/Eigen/src/Core/TriangularMatrix.h
include/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h
include/Eigen/src/Core/SolveTriangular.h