LIA_RAL: Eigen::IncompleteLUT< _Scalar > Class Template Reference
Eigen::IncompleteLUT< _Scalar > Class Template Reference
Incomplete LU factorization with dual-threshold strategy During the numerical factorization, two dropping rules are used : 1) any element whose magnitude is less than some tolerance is dropped. This tolerance is obtained by multiplying the input tolerance droptol by the average magnitude of all the original elements in the current row. 2) After the elimination of the row, only the fill largest elements in the L part and the fill largest elements in the U part are kept (in addition to the diagonal element). Note that fill is computed from the input parameter fillfactor which is used the ratio to control the fill_in relatively to the initial number of nonzero elements.
#include <IncompleteLUT.h>
Classes
struct keep_diag
Public Types
typedef Matrix< Scalar,
Dynamic, Dynamic > MatrixType
Public Member Functions
IncompleteLUT ()
template<typename MatrixType >
IncompleteLUT (const MatrixType &mat, RealScalar droptol=NumTraits< Scalar >::dummy_precision(), int fillfactor=10)
Index rows () const
Index cols () const
ComputationInfo info () const
Reports whether previous computation was successful.
template<typename MatrixType >
void analyzePattern (const MatrixType &amat)
template<typename MatrixType >
void factorize (const MatrixType &amat)
template<typename MatrixType >
IncompleteLUT< Scalar > & compute (const MatrixType &amat)
void setDroptol (RealScalar droptol)
void setFillfactor (int fillfactor)
template<typename Rhs , typename Dest >
void _solve (const Rhs &b, Dest &x) const
template<typename Rhs >
const internal::solve_retval
< IncompleteLUT, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename _MatrixType >
void analyzePattern (const _MatrixType &amat)
template<typename _MatrixType >
void factorize (const _MatrixType &amat)
Protected Member Functions
template<typename VectorV , typename VectorI >
int QuickSplit (VectorV &row, VectorI &ind, int ncut)
Protected Attributes
FactorType m_lu
RealScalar m_droptol
int m_fillfactor
bool m_analysisIsOk
bool m_factorizationIsOk
bool m_isInitialized
ComputationInfo m_info
PermutationMatrix< Dynamic,
Dynamic, Index > m_P
PermutationMatrix< Dynamic,
Dynamic, Index > m_Pinv
Private Types
typedef _Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< Scalar,
Dynamic, 1 > Vector
typedef SparseMatrix< Scalar,
RowMajor > FactorType
typedef SparseMatrix< Scalar,
ColMajor > PermutType
typedef FactorType::Index Index
Additional Inherited Members
Private Member Functions inherited from Eigen::internal::noncopyable
noncopyable ()
~noncopyable ()
Detailed Description
template<typename _Scalar>
class Eigen::IncompleteLUT< _Scalar >
Incomplete LU factorization with dual-threshold strategy During the numerical factorization, two dropping rules are used : 1) any element whose magnitude is less than some tolerance is dropped. This tolerance is obtained by multiplying the input tolerance droptol by the average magnitude of all the original elements in the current row. 2) After the elimination of the row, only the fill largest elements in the L part and the fill largest elements in the U part are kept (in addition to the diagonal element). Note that fill is computed from the input parameter fillfactor which is used the ratio to control the fill_in relatively to the initial number of nonzero elements.
The two extreme cases are when droptol=0 (to keep all the fill*2 largest elements) and when fill=n/2 with droptol being different to zero.
References : Yousef Saad, ILUT: A dual threshold incomplete LU factorization, Numerical Linear Algebra with Applications, 1(4), pp 387-402, 1994.
NOTE : The following implementation is derived from the ILUT implementation in the SPARSKIT package, Copyright (C) 2005, the Regents of the University of Minnesota released under the terms of the GNU LGPL: http://www-users.cs.umn.edu/~saad/software/SPARSKIT/README However, Yousef Saad gave us permission to relicense his ILUT code to MPL2. See the Eigen mailing list archive, thread: ILUT, date: July 8, 2012: http://listengine.tuxfamily.org/lists.tuxfamily.org/eigen/2012/07/msg00064.html alternatively, on GMANE: http://comments.gmane.org/gmane.comp.lib.eigen/3302
Definition at line 44 of file IncompleteLUT.h.
Member Typedef Documentation
template<typename _Scalar> typedef SparseMatrix<Scalar,RowMajor> Eigen::IncompleteLUT< _Scalar >::FactorType private
Definition at line 49 of file IncompleteLUT.h.
template<typename _Scalar> typedef FactorType::Index Eigen::IncompleteLUT< _Scalar >::Index private
Definition at line 51 of file IncompleteLUT.h.
template<typename _Scalar> typedef Matrix<Scalar,Dynamic,Dynamic> Eigen::IncompleteLUT< _Scalar >::MatrixType
Definition at line 54 of file IncompleteLUT.h.
template<typename _Scalar> typedef SparseMatrix<Scalar,ColMajor> Eigen::IncompleteLUT< _Scalar >::PermutType private
Definition at line 50 of file IncompleteLUT.h.
template<typename _Scalar> typedef NumTraits<Scalar>::Real Eigen::IncompleteLUT< _Scalar >::RealScalar private
Definition at line 47 of file IncompleteLUT.h.
template<typename _Scalar> typedef _Scalar Eigen::IncompleteLUT< _Scalar >::Scalar private
Definition at line 46 of file IncompleteLUT.h.
template<typename _Scalar> typedef Matrix<Scalar,Dynamic,1> Eigen::IncompleteLUT< _Scalar >::Vector private
Definition at line 48 of file IncompleteLUT.h.
Constructor & Destructor Documentation
template<typename _Scalar> Eigen::IncompleteLUT< _Scalar >::IncompleteLUT () inline
Definition at line 56 of file IncompleteLUT.h.
template<typename _Scalar> template<typename MatrixType > Eigen::IncompleteLUT< _Scalar >::IncompleteLUT (const MatrixType & mat, RealScalar droptol = NumTraits<Scalar>::dummy_precision(), int fillfactor = 10) inline
Definition at line 62 of file IncompleteLUT.h.
Member Function Documentation
template<typename _Scalar> template<typename Rhs , typename Dest > void Eigen::IncompleteLUT< _Scalar >::_solve (const Rhs & b, Dest & x) const inline
Definition at line 110 of file IncompleteLUT.h.
template<typename _Scalar> template<typename MatrixType > void Eigen::IncompleteLUT< _Scalar >::analyzePattern (const MatrixType & amat)
Referenced by Eigen::IncompleteLUT< _MatrixType >::compute().
template<typename _Scalar> template<typename _MatrixType > void Eigen::IncompleteLUT< _Scalar >::analyzePattern (const _MatrixType & amat)
Definition at line 221 of file IncompleteLUT.h.
References Eigen::SparseMatrix< _Scalar, _Options, _Index >::prune(), and Eigen::SparseMatrixBase< Derived >::transpose().
template<typename _Scalar> Index Eigen::IncompleteLUT< _Scalar >::cols (void) const inline
Definition at line 72 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::solve().
template<typename _Scalar> template<typename MatrixType > IncompleteLUT<Scalar>& Eigen::IncompleteLUT< _Scalar >::compute (const MatrixType & amat) inline
Compute an incomplete LU factorization with dual threshold on the matrix mat No pivoting is done in this version
Definition at line 97 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::IncompleteLUT().
template<typename _Scalar> template<typename MatrixType > void Eigen::IncompleteLUT< _Scalar >::factorize (const MatrixType & amat)
Referenced by Eigen::IncompleteLUT< _MatrixType >::compute().
template<typename _Scalar> template<typename _MatrixType > void Eigen::IncompleteLUT< _Scalar >::factorize (const _MatrixType & amat)
Definition at line 240 of file IncompleteLUT.h.
References abs(), abs2(), eigen_assert, eigen_internal_assert, min(), Eigen::NumericalIssue, sqrt(), Eigen::Success, swap(), and Eigen::SparseMatrixBase< Derived >::twistedBy().
template<typename _Scalar> ComputationInfo Eigen::IncompleteLUT< _Scalar >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the matrix.appears to be negative.
Definition at line 79 of file IncompleteLUT.h.
template<typename Scalar > template<typename VectorV , typename VectorI > int Eigen::IncompleteLUT< Scalar >::QuickSplit (VectorV & row, VectorI & ind, int ncut) protected
Compute a quick-sort split of a vector On output, the vector row is permuted such that its elements satisfy abs(row(i)) >= abs(row(ncut)) if i<ncut abs(row(i)) <= abs(row(ncut)) if i>ncut
Parameters
row The vector of values
ind The array of index for the elements in row
ncut The number of largest elements to keep
Definition at line 186 of file IncompleteLUT.h.
References abs(), row(), and swap().
template<typename _Scalar> Index Eigen::IncompleteLUT< _Scalar >::rows (void) const inline
Definition at line 70 of file IncompleteLUT.h.
template<typename Scalar > void Eigen::IncompleteLUT< Scalar >::setDroptol (RealScalar droptol)
Set control parameter droptol
Parameters
droptol Drop any element whose magnitude is less than this tolerance
Definition at line 159 of file IncompleteLUT.h.
template<typename Scalar > void Eigen::IncompleteLUT< Scalar >::setFillfactor (int fillfactor)
Set control parameter fillfactor
Parameters
fillfactor This is used to compute the number fill_in of largest elements to keep on each row.
Definition at line 169 of file IncompleteLUT.h.
template<typename _Scalar> template<typename Rhs > const internal::solve_retval<IncompleteLUT, Rhs> Eigen::IncompleteLUT< _Scalar >::solve (const MatrixBase< Rhs > & b) const inline
Definition at line 119 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::_solve().
Member Data Documentation
template<typename _Scalar> bool Eigen::IncompleteLUT< _Scalar >::m_analysisIsOk protected
Definition at line 146 of file IncompleteLUT.h.
template<typename _Scalar> RealScalar Eigen::IncompleteLUT< _Scalar >::m_droptol protected
Definition at line 144 of file IncompleteLUT.h.
template<typename _Scalar> bool Eigen::IncompleteLUT< _Scalar >::m_factorizationIsOk protected
Definition at line 147 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::compute().
template<typename _Scalar> int Eigen::IncompleteLUT< _Scalar >::m_fillfactor protected
Definition at line 145 of file IncompleteLUT.h.
template<typename _Scalar> ComputationInfo Eigen::IncompleteLUT< _Scalar >::m_info protected
Definition at line 149 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::info().
template<typename _Scalar> bool Eigen::IncompleteLUT< _Scalar >::m_isInitialized protected
Definition at line 148 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::compute(), Eigen::IncompleteLUT< _MatrixType >::info(), and Eigen::IncompleteLUT< _MatrixType >::solve().
template<typename _Scalar> FactorType Eigen::IncompleteLUT< _Scalar >::m_lu protected
Definition at line 143 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::_solve(), Eigen::IncompleteLUT< _MatrixType >::cols(), and Eigen::IncompleteLUT< _MatrixType >::rows().
template<typename _Scalar> PermutationMatrix<Dynamic,Dynamic,Index> Eigen::IncompleteLUT< _Scalar >::m_P protected
Definition at line 150 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::_solve().
template<typename _Scalar> PermutationMatrix<Dynamic,Dynamic,Index> Eigen::IncompleteLUT< _Scalar >::m_Pinv protected
Definition at line 151 of file IncompleteLUT.h.
Referenced by Eigen::IncompleteLUT< _MatrixType >::_solve().
The documentation for this class was generated from the following file:
include/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h