LIA_RAL: LIA_SpkTools/src/ClusteringCriterion.cpp File Reference
ClusteringCriterion.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include "TrainTools.h"
#include "SegTools.h"
Functions
double clrCrit (Config &config, SegCluster &c1, SegCluster &c2, StatServer &ss, FeatureServer &fs, MixtureGD &m1, MixtureGD &m2, MixtureGD &world)
double gllrCrit (Config &config, SegCluster &c1, SegCluster &c2, SegCluster &c12, StatServer &ss, FeatureServer &fs, MixtureGD &m1, MixtureGD &m2, MixtureGD &m12)
double bicCrit (Config &config, SegCluster &c1, SegCluster &c2, SegCluster &c12, StatServer &ss, FeatureServer &fs, MixtureGD &m1, MixtureGD &m2, MixtureGD &m12)
double deltabicCrit (Config &config, SegCluster &c1, SegCluster &c2, SegCluster &c12, StatServer &ss, FeatureServer &fs, MixtureGD &m1, MixtureGD &m2, MixtureGD &m12)
double clusteringCriterionByAdapt (Config &config, Seg *segment1, Seg *segment2, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
double clusteringCriterion (Config &config, Seg *segment1, Seg *segment2, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
SegCluster & mergeCluster (SegCluster &c1, SegCluster &c2, SegServer &segTemp, String merge="NULL")
double clusteringCriterionWithoutWorldInit (Config &config, SegCluster &c1, SegCluster &c2, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
double clusteringCriterionWithoutWorldInit (Config &config, SegCluster &c1, MixtureGD &m1, SegCluster &c2, MixtureGD &m2, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
double clusteringCriterionWithoutWorldInit (Config &config, Seg *segment1, Seg *segment2, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
bool isSimilarSegment (Config &config, Seg *segment1, Seg *segment2, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
double cohortMaxLikelihood (StatServer &ss, FeatureServer &fs, hmm &actualHMM, unsigned long except, unsigned long begin, unsigned long longSelection, Config &config)
Seg * bestFittingSegment (Config &config, SegCluster &cluster, MixtureGD &m, StatServer &ss, FeatureServer &fs)
Seg * bestFittingSegment (Config &config, SegCluster &cluster, MixtureGD &m, StatServer &ss, FeatureServer &fs, MixtureGD &world)
Seg * bestFittingSegment (Config &config, SegCluster &cluster, MixtureGD &m, StatServer &ss, FeatureServer &fs, hmm &actualHMM, unsigned long except)
unsigned long bestFittingCluster (Config &config, hmm &actualHMM, SegServer &actualSeg, Seg *segment, StatServer &ss, FeatureServer &fs, unsigned long exceptInd=200)
void intraCluster (Config &config, hmm &actualHMM, SegServer &actualSeg, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
void interCluster (Config &config, hmm &actualHMM, SegServer &actualSeg, StatServer &ss, FeatureServer &fs, MixtureGD &world, String crit)
MixtureGD & InitOneGausMixture (Config &config, SegCluster &c, FeatureServer &fs, MixtureServer &ms)
double clusteringCriterionWithoutWorldInitOneGaus (Config &config, SegCluster &c1, SegCluster &c2, StatServer &ss, FeatureServer &fs, String crit)
Function Documentation
unsigned long bestFittingCluster (Config & config, hmm & actualHMM, SegServer & actualSeg, Seg * segment, StatServer & ss, FeatureServer & fs, unsigned long exceptInd = 200)
Definition at line 739 of file ClusteringCriterion.cpp.
References hmm::getDensity(), meanLikelihood(), and verbose.
Seg* bestFittingSegment (Config & config, SegCluster & cluster, MixtureGD & m, StatServer & ss, FeatureServer & fs)
Definition at line 609 of file ClusteringCriterion.cpp.
References endSeg(), meanLikelihood(), verbose, and verboseLevel.
Referenced by interCluster(), and intraCluster().
Seg* bestFittingSegment (Config & config, SegCluster & cluster, MixtureGD & m, StatServer & ss, FeatureServer & fs, MixtureGD & world)
Definition at line 650 of file ClusteringCriterion.cpp.
References endSeg(), meanLikelihood(), verbose, and verboseLevel.
Seg* bestFittingSegment (Config & config, SegCluster & cluster, MixtureGD & m, StatServer & ss, FeatureServer & fs, hmm & actualHMM, unsigned long except)
Definition at line 694 of file ClusteringCriterion.cpp.
References cohortMaxLikelihood(), endSeg(), hmm::length, meanLikelihood(), verbose, and verboseLevel.
double bicCrit (Config & config, SegCluster & c1, SegCluster & c2, SegCluster & c12, StatServer & ss, FeatureServer & fs, MixtureGD & m1, MixtureGD & m2, MixtureGD & m12)
Definition at line 130 of file ClusteringCriterion.cpp.
References gllrCrit(), log(), totalFrame(), and verbose.
Referenced by clusteringCriterion(), clusteringCriterionByAdapt(), clusteringCriterionWithoutWorldInit(), and clusteringCriterionWithoutWorldInitOneGaus().
double clrCrit (Config & config, SegCluster & c1, SegCluster & c2, StatServer & ss, FeatureServer & fs, MixtureGD & m1, MixtureGD & m2, MixtureGD & world)
Definition at line 71 of file ClusteringCriterion.cpp.
References accumulateStatLLK(), totalFrame(), verbose, and verboseLevel.
Referenced by clusteringCriterion(), clusteringCriterionByAdapt(), and clusteringCriterionWithoutWorldInit().
double clusteringCriterion (Config & config, Seg * segment1, Seg * segment2, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 212 of file ClusteringCriterion.cpp.
References bicCrit(), clrCrit(), endSeg(), gllrCrit(), globalMeanCov(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setNbTrainIt(), trainModel(), and verbose.
double clusteringCriterionByAdapt (Config & config, Seg * segment1, Seg * segment2, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 155 of file ClusteringCriterion.cpp.
References adaptModel(), bicCrit(), clrCrit(), endSeg(), gllrCrit(), MAPCfg::setBaggedFrameProbability(), MAPCfg::setMeanReg(), MAPCfg::setMethod(), and verbose.
double clusteringCriterionWithoutWorldInit (Config & config, SegCluster & c1, SegCluster & c2, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 303 of file ClusteringCriterion.cpp.
References bicCrit(), clrCrit(), deltabicCrit(), gllrCrit(), globalMeanCov(), mergeCluster(), mixtureInit(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setBaggedFrameProbabilityInit(), TrainCfg::setFinalVarFlooring(), TrainCfg::setInitVarFlooring(), TrainCfg::setNbTrainIt(), trainModel(), and verbose.
Referenced by clusteringCriterionWithoutWorldInit(), and isSimilarSegment().
double clusteringCriterionWithoutWorldInit (Config & config, SegCluster & c1, MixtureGD & m1, SegCluster & c2, MixtureGD & m2, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 458 of file ClusteringCriterion.cpp.
References bicCrit(), clrCrit(), deltabicCrit(), gllrCrit(), globalMeanCov(), mergeCluster(), mixtureInit(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setBaggedFrameProbabilityInit(), TrainCfg::setFinalVarFlooring(), TrainCfg::setInitVarFlooring(), TrainCfg::setNbTrainIt(), totalFrame(), trainModel(), and verbose.
double clusteringCriterionWithoutWorldInit (Config & config, Seg * segment1, Seg * segment2, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 543 of file ClusteringCriterion.cpp.
References clusteringCriterionWithoutWorldInit(), endSeg(), and verbose.
double clusteringCriterionWithoutWorldInitOneGaus (Config & config, SegCluster & c1, SegCluster & c2, StatServer & ss, FeatureServer & fs, String crit)
Definition at line 831 of file ClusteringCriterion.cpp.
References accumulateStatEM(), bicCrit(), deltabicCrit(), TrainCfg::getNbTrainIt(), gllrCrit(), InitOneGausMixture(), mergeCluster(), TrainCfg::setNbTrainIt(), and sqrt().
Referenced by TurnDetection().
double cohortMaxLikelihood (StatServer & ss, FeatureServer & fs, hmm & actualHMM, unsigned long except, unsigned long begin, unsigned long longSelection, Config & config)
Definition at line 587 of file ClusteringCriterion.cpp.
References hmm::getDensity(), hmm::getNbState(), max(), meanLikelihood(), verbose, and verboseLevel.
Referenced by bestFittingSegment().
double deltabicCrit (Config & config, SegCluster & c1, SegCluster & c2, SegCluster & c12, StatServer & ss, FeatureServer & fs, MixtureGD & m1, MixtureGD & m2, MixtureGD & m12)
Definition at line 144 of file ClusteringCriterion.cpp.
References gllrCrit(), totalFrame(), and verbose.
Referenced by clusteringCriterionWithoutWorldInit(), and clusteringCriterionWithoutWorldInitOneGaus().
double gllrCrit (Config & config, SegCluster & c1, SegCluster & c2, SegCluster & c12, StatServer & ss, FeatureServer & fs, MixtureGD & m1, MixtureGD & m2, MixtureGD & m12)
Definition at line 104 of file ClusteringCriterion.cpp.
References accumulateStatLLK(), totalFrame(), verbose, and verboseLevel.
Referenced by bicCrit(), clusteringCriterion(), clusteringCriterionByAdapt(), clusteringCriterionWithoutWorldInit(), clusteringCriterionWithoutWorldInitOneGaus(), and deltabicCrit().
MixtureGD& InitOneGausMixture (Config & config, SegCluster & c, FeatureServer & fs, MixtureServer & ms)
Definition at line 807 of file ClusteringCriterion.cpp.
References globalMeanCov().
Referenced by clusteringCriterionWithoutWorldInitOneGaus().
void interCluster (Config & config, hmm & actualHMM, SegServer & actualSeg, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 778 of file ClusteringCriterion.cpp.
References bestFittingSegment(), endSeg(), hmm::getDensity(), isSimilarSegment(), verbose, and verboseLevel.
void intraCluster (Config & config, hmm & actualHMM, SegServer & actualSeg, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 761 of file ClusteringCriterion.cpp.
References bestFittingSegment(), endSeg(), hmm::getDensity(), isSimilarSegment(), verbose, and verboseLevel.
bool isSimilarSegment (Config & config, Seg * segment1, Seg * segment2, StatServer & ss, FeatureServer & fs, MixtureGD & world, String crit)
Definition at line 564 of file ClusteringCriterion.cpp.
References clusteringCriterionWithoutWorldInit().
Referenced by interCluster(), and intraCluster().
SegCluster& mergeCluster (SegCluster & c1, SegCluster & c2, SegServer & segTemp, String merge = "NULL")
Definition at line 284 of file ClusteringCriterion.cpp.
Referenced by clusteringCriterionWithoutWorldInit(), and clusteringCriterionWithoutWorldInitOneGaus().