LIA_RAL: include/Eigen/src/plugins/CommonCwiseUnaryOps.h File Reference
CommonCwiseUnaryOps.h File Reference
Typedefs
typedef CwiseUnaryOp
< internal::scalar_multiple_op
< Scalar >, const Derived > ScalarMultipleReturnType
typedef CwiseUnaryOp
< internal::scalar_quotient1_op
< Scalar >, const Derived > ScalarQuotient1ReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, const
CwiseUnaryOp
< internal::scalar_conjugate_op
< Scalar >, const Derived >
, const Derived & >::type ConjugateReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, const
CwiseUnaryOp
< internal::scalar_real_op
< Scalar >, const Derived >
, const Derived & >::type RealReturnType
typedef internal::conditional
< NumTraits< Scalar >
::IsComplex, CwiseUnaryView
< internal::scalar_real_ref_op
< Scalar >, Derived >, Derived & >
::type NonConstRealReturnType
typedef CwiseUnaryOp
< internal::scalar_imag_op
< Scalar >, const Derived > ImagReturnType
typedef CwiseUnaryView
< internal::scalar_imag_ref_op
< Scalar >, Derived > NonConstImagReturnType
Functions
const CwiseUnaryOp
< internal::scalar_opposite_op
< typename internal::traits
< Derived >::Scalar >, const
Derived > operator- () const
const ScalarMultipleReturnType operator* (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_quotient1_op
< typename internal::traits
< Derived >::Scalar >, const
Derived > operator/ (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const Derived > operator* (const std::complex< Scalar > &scalar) const
const ScalarMultipleReturnType operator* (const Scalar &scalar, const StorageBaseType &matrix)
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const Derived > operator* (const std::complex< Scalar > &scalar, const StorageBaseType &matrix)
template<typename NewType >
internal::cast_return_type
< Derived, const CwiseUnaryOp
< internal::scalar_cast_op
< typename internal::traits
< Derived >::Scalar, NewType >
, const Derived > >::type cast () const
ConjugateReturnType conjugate () const
RealReturnType real () const
const ImagReturnType imag () const
template<typename CustomUnaryOp >
const CwiseUnaryOp
< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
const CwiseUnaryView
< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
Typedef Documentation
typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, const Derived& >::type ConjugateReturnType
Definition at line 23 of file CommonCwiseUnaryOps.h.
typedef CwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> ImagReturnType
Definition at line 35 of file CommonCwiseUnaryOps.h.
typedef CwiseUnaryView<internal::scalar_imag_ref_op<Scalar>, Derived> NonConstImagReturnType
Definition at line 37 of file CommonCwiseUnaryOps.h.
typedef internal::conditional<NumTraits<Scalar>::IsComplex, CwiseUnaryView<internal::scalar_real_ref_op<Scalar>, Derived>, Derived& >::type NonConstRealReturnType
Definition at line 33 of file CommonCwiseUnaryOps.h.
typedef internal::conditional<NumTraits<Scalar>::IsComplex, const CwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived>, const Derived& >::type RealReturnType
Definition at line 28 of file CommonCwiseUnaryOps.h.
typedef CwiseUnaryOp<internal::scalar_multiple_op<Scalar>, const Derived> ScalarMultipleReturnType
Definition at line 16 of file CommonCwiseUnaryOps.h.
typedef CwiseUnaryOp<internal::scalar_quotient1_op<Scalar>, const Derived> ScalarQuotient1ReturnType
Definition at line 18 of file CommonCwiseUnaryOps.h.
Function Documentation
template<typename NewType > internal::cast_return_type<Derived,const CwiseUnaryOp<internal::scalar_cast_op<typename internal::traits<Derived>::Scalar, NewType>, const Derived> >::type cast () const
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See Also
class CwiseUnaryOp
Definition at line 92 of file CommonCwiseUnaryOps.h.
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::operator*(), and Eigen::operator*().
ConjugateReturnType conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See Also
adjoint()
Definition at line 101 of file CommonCwiseUnaryOps.h.
Referenced by Eigen::VectorwiseOp< ExpressionType, Direction >::cross(), Eigen::QuaternionBase< Derived >::inverse(), and Eigen::Quaternion< _Scalar >::inverse().
NonConstImagReturnType imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See Also
real()
Returns
a non const expression of the imaginary part of *this.
See Also
real()
Definition at line 116 of file CommonCwiseUnaryOps.h.
Referenced by PldaDev::computeEigenProblem(), TVAcc::computeEigenProblem(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::ei_imag(), Eigen::internal::EIGEN_MATHFUNC_RETVAL(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::internal::scalar_imag_op< Scalar >::operator()(), Eigen::internal::pcplxflip(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmul(), Eigen::internal::pmul(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvalueMatrix(), Eigen::internal::imag_impl< std::complex< RealScalar > >::run(), Eigen::internal::trmv_selector< ColMajor >::run(), Eigen::internal::abs2_impl< std::complex< RealScalar > >::run(), Eigen::internal::norm1_default_impl< Scalar, NumTraits< Scalar >::IsComplex >::run(), Eigen::internal::gemv_selector< OnTheRight, ColMajor, true >::run(), Eigen::internal::random_default_impl< Scalar, true, false >::run(), and Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::unpackRhs().
const ScalarMultipleReturnType operator* (const Scalar & scalar) const inline
Returns
an expression of *this scaled by the scalar factor scalar
Definition at line 49 of file CommonCwiseUnaryOps.h.
const CwiseUnaryOp<internal::scalar_multiple2_op<Scalar,std::complex<Scalar> >, const Derived> operator* (const std::complex< Scalar > & scalar) const inline
Overloaded for efficient real matrix times complex scalar value
Definition at line 69 of file CommonCwiseUnaryOps.h.
friend const ScalarMultipleReturnType operator* (const Scalar & scalar, const StorageBaseType & matrix) inline
Definition at line 76 of file CommonCwiseUnaryOps.h.
friend const CwiseUnaryOp<internal::scalar_multiple2_op<Scalar,std::complex<Scalar> >, const Derived> operator* (const std::complex< Scalar > & scalar, const StorageBaseType & matrix) inline
Definition at line 80 of file CommonCwiseUnaryOps.h.
const CwiseUnaryOp<internal::scalar_opposite_op<typename internal::traits<Derived>::Scalar>, const Derived> operator- () const inline
Returns
an expression of the opposite of *this
Definition at line 44 of file CommonCwiseUnaryOps.h.
const CwiseUnaryOp<internal::scalar_quotient1_op<typename internal::traits<Derived>::Scalar>, const Derived> operator/ (const Scalar & scalar) const inline
Returns
an expression of *this divided by the scalar value scalar
Definition at line 61 of file CommonCwiseUnaryOps.h.
NonConstRealReturnType real () const inline
Returns
a read-only expression of the real part of *this.
See Also
imag()
Returns
a non const expression of the real part of *this.
See Also
imag()
Definition at line 110 of file CommonCwiseUnaryOps.h.
Referenced by Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), PldaDev::computeEigenProblem(), TVAcc::computeEigenProblem(), Eigen::ComplexSchur< _MatrixType >::computeShift(), Eigen::internal::conjugate_gradient(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::ei_real(), Eigen::internal::EIGEN_MATHFUNC_RETVAL(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), Eigen::internal::llt_rank_update_lower(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::JacobiRotation< Scalar >::makeJacobi(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2, StorageOrder >::operator()(), Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder >::operator()(), Eigen::internal::scalar_real_op< Scalar >::operator()(), Eigen::internal::symm_pack_lhs< Scalar, Index, Pack1, Pack2, StorageOrder >::pack(), Eigen::internal::pcplxflip(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmul(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmul(), Eigen::internal::pmul(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvalueMatrix(), Eigen::internal::real_2x2_jacobi_svd(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn >::run(), Eigen::internal::real_impl< std::complex< RealScalar > >::run(), Eigen::internal::get_factor< Scalar, typename NumTraits< Scalar >::Real >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Upper), UnrollCount, ClearOpposite >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite >::run(), Eigen::internal::abs2_impl< std::complex< RealScalar > >::run(), Eigen::internal::norm1_default_impl< Scalar, NumTraits< Scalar >::IsComplex >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 1, IsComplex >::run(), Eigen::internal::random_default_impl< Scalar, true, false >::run(), Eigen::MatrixBase< Derived >::squaredNorm(), Eigen::SparseMatrixBase< Derived >::squaredNorm(), Eigen::internal::ldlt_inplace< Lower >::unblocked(), Eigen::internal::llt_inplace< Scalar, Lower >::unblocked(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::unpackRhs(), and Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
template<typename CustomUnaryOp > const CwiseUnaryOp<CustomUnaryOp, const Derived> unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
Output:
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
Output:
See Also
class CwiseUnaryOp, class CwiseBinaryOp
Definition at line 139 of file CommonCwiseUnaryOps.h.
template<typename CustomViewOp > const CwiseUnaryView<CustomViewOp, const Derived> unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
Output:
See Also
class CwiseUnaryOp, class CwiseBinaryOp
Definition at line 157 of file CommonCwiseUnaryOps.h.