LIA_RAL: LIA_SpkDet/ComputeJFAStats/src/ComputeJFAStats.cpp File Reference
ComputeJFAStats.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <cstdlib>
#include "liatools.h"
#include "ComputeJFAStats.h"
Macros
#define ALIZE_ComputeJFAStats_cpp
Functions
int ComputeJFAStats (Config &config)
int ComputeTVStats (Config &config)
Macro Definition Documentation
#define ALIZE_ComputeJFAStats_cpp
Definition at line 56 of file ComputeJFAStats.cpp.
Function Documentation
int ComputeJFAStats (Config & config)
Definition at line 71 of file ComputeJFAStats.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), and JFAAcc::saveAccs().
Referenced by main().
int ComputeTVStats (Config & config)
Definition at line 89 of file ComputeJFAStats.cpp.
References TVAcc::computeAndAccumulateTVStat(), and TVAcc::saveAccs().
Referenced by main().