LIA_RAL: LIA_SpkDet/ComputeTest/src/ComputeTest.cpp File Reference
ComputeTest.cpp File Reference
#include <iostream>
#include <fstream>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "ComputeTest.h"
#include <sys/stat.h>
Classes
class WindowLLR
Macros
#define ALIZE_ComputeTest_cpp
Functions
int fexist (char *filename)
int ComputeTest (Config &config)
int ComputeTestDotProduct (Config &config)
int ComputeTestJFA (Config &config)
int ComputeTestLFA (Config &config)
int ComputeTestNAP (Config &config)
int ComputeTestByLabel (Config &config)
int ComputeTestHisto (Config &config)
Macro Definition Documentation
#define ALIZE_ComputeTest_cpp
Definition at line 56 of file ComputeTest.cpp.
Function Documentation
int ComputeTest (Config & config)
Definition at line 218 of file ComputeTest.cpp.
References WindowLLR::accLLR(), CST_MAX_CLIENT_LINE, WindowLLR::dec(), frameIdxToTime(), TabClientLine::getClientModel(), TabClientLine::getClientName(), WindowLLR::getIdxBegin(), WindowLLR::getIdxEnd(), WindowLLR::getLLR(), initializeClusters(), WindowLLR::isEnd(), WindowLLR::isSet(), TabClientLine::loadLine(), TabClientLine::nbClientLine(), outputResultLine(), setDecision(), WindowLLR::setNbClient(), WindowLLR::showConfig(), verbose, verboseLevel, and verifyClusterFile().
int ComputeTestByLabel (Config & config)
Definition at line 1044 of file ComputeTest.cpp.
References ScoreAccum::addAndAccumulate(), CST_MAX_CLIENT_LINE, TabClientLine::getClientModel(), TabClientLine::getClientName(), ScoreAccum::getId(), ScoreAccum::getScore(), ScoreAccum::getSize(), initializeClusters(), TabClientLine::loadLine(), TabClientLine::nbClientLine(), outputResultLine(), setDecision(), verbose, and verifyClusterFile().
int ComputeTestDotProduct (Config & config)
Definition at line 356 of file ComputeTest.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), CST_MAX_CLIENT_LINE, debug, JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateUEUT(), JFAAcc::estimateX(), JFAAcc::getF_X(), JFAAcc::getN(), JFAAcc::getNDistrib(), JFAAcc::getSvSize(), JFAAcc::loadD(), JFAAcc::loadEC(), JFAAcc::loadEV(), outputResultLine(), setDecision(), JFAAcc::substractMplusUX(), and JFAAcc::substractMplusVYplusDZ().
int ComputeTestHisto (Config & config)
Definition at line 1159 of file ComputeTest.cpp.
References TabHisto::accumulateValueInTab(), ScoreAccum::addAndAccumulate(), computeEntropy(), TabHisto::computeHistoInTab(), computeMean(), CST_MAX_CLIENT_LINE, debug, TabClientLine::getClientModel(), TabClientLine::getClientName(), TabHisto::getHisto(), ScoreAccum::getScore(), initializeClusters(), TabClientLine::loadLine(), TabClientLine::nbClientLine(), outputResultLine(), setDecision(), verbose, and verifyClusterFile().
int ComputeTestJFA (Config & config)
Load existing JFA matrices
Compute JFA stats
Estimate uEuT for the test
Estimate and inverse L matrices
Substract the UBM mean vector from the test segment (Y and X are null at this time)
Estimate X for the test segment
Estimate XYZ on the test segment and normalise the features by substracting Ux
Definition at line 504 of file ComputeTest.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), CST_MAX_CLIENT_LINE, debug, JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateUEUT(), JFAAcc::estimateX(), TabClientLine::getClientModel(), TabClientLine::getClientName(), initializeClusters(), JFAAcc::loadD(), JFAAcc::loadEC(), JFAAcc::loadEV(), TabClientLine::loadLine(), TabClientLine::nbClientLine(), outputResultLine(), setDecision(), JFAAcc::substractMplusVYplusDZ(), JFAAcc::substractUXfromFeatures(), verbose, verboseLevel, and verifyClusterFile().
int ComputeTestLFA (Config & config)
Load existing JFA matrices
Compute JFA stats
Estimate uEuT for the test
Estimate and inverse L matrices
Estimate X for the test segment
Estimate XYZ on the test segment and normalise the features by substracting Ux
Definition at line 702 of file ComputeTest.cpp.
References cms(), JFAAcc::computeAndAccumulateJFAStat(), CST_MAX_CLIENT_LINE, debug, JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateUEUT(), JFAAcc::estimateX(), JFAAcc::estimateZMAP(), TabClientLine::getClientModel(), TabClientLine::getClientName(), initializeClusters(), JFAAcc::loadD(), JFAAcc::loadEC(), JFAAcc::loadEV(), TabClientLine::loadLine(), TabClientLine::nbClientLine(), outputResultLine(), setDecision(), sqrt(), JFAAcc::substractMplusDZByChannel(), JFAAcc::substractMplusUX(), JFAAcc::substractUXfromFeatures(), verbose, verboseLevel, and verifyClusterFile().
int ComputeTestNAP (Config & config)
Definition at line 895 of file ComputeTest.cpp.
References computeNAPChannelEffect(), CST_MAX_CLIENT_LINE, debug, frameIdxToTime(), TabClientLine::getClientModel(), TabClientLine::getClientName(), initializeClusters(), TabClientLine::loadLine(), TabClientLine::nbClientLine(), outputResultLine(), setDecision(), verbose, verboseLevel, and verifyClusterFile().
int fexist (char * filename)
Definition at line 81 of file ComputeTest.cpp.