LIA_RAL: LIA_SpkDet/ComputeJFAStats/include/ComputeJFAStats.h File Reference
ComputeJFAStats.h File Reference
#include "alize.h"
#include "liatools.h"
Functions
int ComputeJFAStats (Config &)
int ComputeTVStats (Config &)
Function Documentation
int ComputeJFAStats (Config &)
Definition at line 71 of file ComputeJFAStats.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), and JFAAcc::saveAccs().
Referenced by main().
int ComputeTVStats (Config &)
Definition at line 89 of file ComputeJFAStats.cpp.
References TVAcc::computeAndAccumulateTVStat(), and TVAcc::saveAccs().
Referenced by main().