LIA_RAL: LIA_SpkDet/ComputeNorm/src/ComputeNorm.cpp File Reference
ComputeNorm.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <cstdlib>
#include "liatools.h"
#include "ComputeNorm.h"
Classes
class DistribNorm
class NormSeg
class Norm
Macros
#define ALIZE_ComputeNorm_cpp
Functions
bool selectImp (String &fieldOne, String &fieldTwo, XList &impList, char selectMode)
void getAllScores (XList &list, unsigned long indFieldOne, unsigned long indFieldTwo, unsigned long indScore, Norm &norm, XList &impList, char selectMode, Config &config)
void getAllScoresFirstNormed (XList &list, unsigned long indFieldOne, unsigned long indFieldTwo, unsigned long indScore, Norm &firstNorm, Norm &outNorm, XList &impList, char selectMode, Config &config)
int ComputeNorm (Config &config)
Macro Definition Documentation
#define ALIZE_ComputeNorm_cpp
Definition at line 56 of file ComputeNorm.cpp.
Function Documentation
int ComputeNorm (Config & config)
Definition at line 491 of file ComputeNorm.cpp.
References debug, Norm::findEntityInNorm(), getAllScores(), getAllScoresFirstNormed(), Norm::getMean(), Norm::getStd(), outputResultLine(), Norm::print(), Norm::setNormAndFreeDistrib(), verbose, verboseLevel, and znorm().
void getAllScores (XList & list, unsigned long indFieldOne, unsigned long indFieldTwo, unsigned long indScore, Norm & norm, XList & impList, char selectMode, Config & config)
Definition at line 446 of file ComputeNorm.cpp.
References Norm::addScore(), Norm::findAddSeg(), and selectImp().
Referenced by ComputeNorm().
void getAllScoresFirstNormed (XList & list, unsigned long indFieldOne, unsigned long indFieldTwo, unsigned long indScore, Norm & firstNorm, Norm & outNorm, XList & impList, char selectMode, Config & config)
Definition at line 466 of file ComputeNorm.cpp.
References Norm::addScore(), Norm::findAddSeg(), Norm::findEntityInNorm(), Norm::getMean(), Norm::getStd(), and selectImp().
Referenced by ComputeNorm().
bool selectImp (String & fieldOne, String & fieldTwo, XList & impList, char selectMode)
Definition at line 436 of file ComputeNorm.cpp.
Referenced by getAllScores(), and getAllScoresFirstNormed().