LIA_RAL: LIA_SpkDet/ComputeTest/src/ComputeTestMain.cpp File Reference
ComputeTestMain.cpp File Reference
#include <iostream>
#include <alize.h>
#include "liatools.h"
#include "ComputeTest.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 63 of file ComputeTestMain.cpp.
References ComputeTest(), ComputeTestByLabel(), ComputeTestDotProduct(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), debug, verbose, and verboseLevel.