LIA_RAL: LIA_SpkDet/CovIntra/src/CovIntra.cpp File Reference
CovIntra.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "CovIntra.h"
#include "svdlib.h"
Classes
class RealVectorStat< T >
Macros
#define ALIZE_CovIntra_cpp
#define myTINY 1e-11
Functions
void dividesSvByInteger (RealVector< double > &v, unsigned long nb)
void dividesSvByInteger (Matrix< double > &v, unsigned long nb)
bool badSv (Matrix< double > &v)
void loadMeanSv (String id, Matrix< double > &v, Config &config)
int CovIntra (Config &config)
Macro Definition Documentation
#define ALIZE_CovIntra_cpp
Definition at line 56 of file CovIntra.cpp.
#define myTINY 1e-11
Definition at line 81 of file CovIntra.cpp.
Referenced by badSv(), and CovIntra().
Function Documentation
bool badSv (Matrix< double > & v)
Definition at line 99 of file CovIntra.cpp.
References abs(), and myTINY.
Referenced by CovIntra().
int CovIntra (Config & config)
Definition at line 160 of file CovIntra.cpp.
References abs(), RealVectorStat< T >::acc(), badSv(), dmat::cols, svdrec::d, debug, dividesSvByInteger(), loadMeanSv(), RealVectorStat< T >::mean(), myTINY, dmat::rows, svdrec::S, SVD_F_DB, svdConvertDtoS(), svdFreeDMat(), svdFreeSMat(), svdFreeSVDRec(), svdLAS2(), svdNewDMat(), SVDVerbosity, svdWriteDenseMatrix(), svdrec::Ut, smat::vals, smat::value, dmat::value, verbose, and verboseLevel.
Referenced by main().
void dividesSvByInteger (RealVector< double > & v, unsigned long nb)
Definition at line 86 of file CovIntra.cpp.
Referenced by CovIntra().
void dividesSvByInteger (Matrix< double > & v, unsigned long nb)
Definition at line 93 of file CovIntra.cpp.
void loadMeanSv (String id, Matrix< double > & v, Config & config)
Definition at line 107 of file CovIntra.cpp.
References getKLVector(), and modelToSv().
Referenced by CovIntra().