LIA_RAL: LIA_SpkDet/CovIntra/include/CovIntra.h File Reference
CovIntra.h File Reference
#include "alize.h"
Macros
#define ALIZE_ CovIntra_h
Functions
int CovIntra (Config &config)
int CovIntraBin (Config &config)
Macro Definition Documentation
#define ALIZE_ CovIntra_h
Definition at line 56 of file CovIntra.h.
Function Documentation
int CovIntra (Config & config)
Definition at line 160 of file CovIntra.cpp.
References abs(), RealVectorStat< T >::acc(), badSv(), dmat::cols, svdrec::d, debug, dividesSvByInteger(), loadMeanSv(), RealVectorStat< T >::mean(), myTINY, dmat::rows, svdrec::S, SVD_F_DB, svdConvertDtoS(), svdFreeDMat(), svdFreeSMat(), svdFreeSVDRec(), svdLAS2(), svdNewDMat(), SVDVerbosity, svdWriteDenseMatrix(), svdrec::Ut, smat::vals, smat::value, dmat::value, verbose, and verboseLevel.
Referenced by main().
int CovIntraBin (Config & config)