LIA_RAL: LIA_SpkDet/EigenVoice/src/EigenVoice.cpp File Reference
EigenVoice.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "EigenVoice.h"
Macros
#define ALIZE_EigenVoice_cpp
Functions
int EigenVoice (Config &config)
Macro Definition Documentation
#define ALIZE_EigenVoice_cpp
Definition at line 57 of file EigenVoice.cpp.
Function Documentation
int EigenVoice (Config & config)
Definition at line 71 of file EigenVoice.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_EV(), JFAAcc::estimateVEVT(), JFAAcc::estimateYandV(), JFAAcc::initEV(), JFAAcc::loadEV(), JFAAcc::loadF_X(), JFAAcc::loadF_X_h(), JFAAcc::loadN(), JFAAcc::loadN_h(), JFAAcc::orthonormalizeV(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::saveAccs(), JFAAcc::saveV(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractUX(), JFAAcc::updateVestimate(), verboseLevel, and JFAAcc::verifyEMLK().
Referenced by main().