LIA_RAL: LIA_SpkDet/EigenVoice/include/EigenVoice.h File Reference
EigenVoice.h File Reference
#include "alize.h"
#include "liatools.h"
Functions
int EigenVoice (Config &)
Function Documentation
int EigenVoice (Config &)
Definition at line 71 of file EigenVoice.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_EV(), JFAAcc::estimateVEVT(), JFAAcc::estimateYandV(), JFAAcc::initEV(), JFAAcc::loadEV(), JFAAcc::loadF_X(), JFAAcc::loadF_X_h(), JFAAcc::loadN(), JFAAcc::loadN_h(), JFAAcc::orthonormalizeV(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::saveAccs(), JFAAcc::saveV(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractUX(), JFAAcc::updateVestimate(), verboseLevel, and JFAAcc::verifyEMLK().
Referenced by main().