LIA_RAL: LIA_SpkDet/EigenChannel/include/EigenChannel.h File Reference
EigenChannel.h File Reference
#include <alize.h>
#include "liatools.h"
Functions
int EigenChannelJFA (Config &)
int EigenChannelLFA (Config &)
Function Documentation
int EigenChannelJFA (Config &)
Definition at line 70 of file EigenChannel.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateAndInverseL_EV(), JFAAcc::estimateUEUT(), JFAAcc::estimateVEVT(), JFAAcc::estimateXandU(), JFAAcc::estimateY(), JFAAcc::getV(), JFAAcc::initEC(), JFAAcc::loadEC(), JFAAcc::loadEV(), JFAAcc::loadF_X(), JFAAcc::loadF_X_h(), JFAAcc::loadN(), JFAAcc::loadN_h(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::saveAccs(), JFAAcc::saveU(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractMplusVYplusDZ(), JFAAcc::substractUX(), JFAAcc::updateUestimate(), and JFAAcc::verifyEMLK().
Referenced by main().
int EigenChannelLFA (Config &)
Definition at line 178 of file EigenChannel.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateAndInverseL_EV(), JFAAcc::estimateU(), JFAAcc::estimateUEUT(), JFAAcc::estimateVEVT(), JFAAcc::estimateX(), JFAAcc::estimateY(), JFAAcc::estimateZMAP(), JFAAcc::getV(), JFAAcc::initD(), JFAAcc::initEC(), JFAAcc::loadEC(), JFAAcc::loadEV(), JFAAcc::loadF_X(), JFAAcc::loadF_X_h(), JFAAcc::loadN(), JFAAcc::loadN_h(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::saveAccs(), JFAAcc::saveU(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractMplusUX(), JFAAcc::substractMplusVYplusDZ(), JFAAcc::substractUX(), JFAAcc::updateUestimate(), verbose, and JFAAcc::verifyEMLK().
Referenced by main().