LIA_RAL: LIA_SpkDet/EigenChannel/src/EigenChannel.cpp File Reference
EigenChannel.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include "liatools.h"
#include "EigenChannel.h"
Macros
#define ALIZE_EigenChannel_cpp
Functions
int EigenChannelJFA (Config &config)
int EigenChannelLFA (Config &config)
Macro Definition Documentation
#define ALIZE_EigenChannel_cpp
Definition at line 56 of file EigenChannel.cpp.
Function Documentation
int EigenChannelJFA (Config & config)
Definition at line 70 of file EigenChannel.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateAndInverseL_EV(), JFAAcc::estimateUEUT(), JFAAcc::estimateVEVT(), JFAAcc::estimateXandU(), JFAAcc::estimateY(), JFAAcc::getV(), JFAAcc::initEC(), JFAAcc::loadEC(), JFAAcc::loadEV(), JFAAcc::loadF_X(), JFAAcc::loadF_X_h(), JFAAcc::loadN(), JFAAcc::loadN_h(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::saveAccs(), JFAAcc::saveU(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractMplusVYplusDZ(), JFAAcc::substractUX(), JFAAcc::updateUestimate(), and JFAAcc::verifyEMLK().
Referenced by main().
int EigenChannelLFA (Config & config)
Definition at line 178 of file EigenChannel.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateAndInverseL_EV(), JFAAcc::estimateU(), JFAAcc::estimateUEUT(), JFAAcc::estimateVEVT(), JFAAcc::estimateX(), JFAAcc::estimateY(), JFAAcc::estimateZMAP(), JFAAcc::getV(), JFAAcc::initD(), JFAAcc::initEC(), JFAAcc::loadEC(), JFAAcc::loadEV(), JFAAcc::loadF_X(), JFAAcc::loadF_X_h(), JFAAcc::loadN(), JFAAcc::loadN_h(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::saveAccs(), JFAAcc::saveU(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractMplusUX(), JFAAcc::substractMplusVYplusDZ(), JFAAcc::substractUX(), JFAAcc::updateUestimate(), verbose, and JFAAcc::verifyEMLK().
Referenced by main().