LIA_RAL: LIA_SpkDet/EnergyDetector/src/EnergyDetector.cpp File Reference
EnergyDetector.cpp File Reference
#include <iostream>
#include <fstream>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "SegTools.h"
#include "EnergyDetector.h"
Macros
#define ALIZE_EnergyDetector_cpp
#define DirectInterpolation 1
Functions
void plotEnergyDistrib (MixtureGD &mixt)
unsigned long findMaxEnergyDistrib (MixtureGD &mixt)
unsigned long findMinEnergyDistrib (MixtureGD &mixt)
double computeEnergyThreshold (FeatureServer &fs, double pSelect, unsigned long nbBins=100)
unsigned long selectFrames (FeatureServer &fs, SegServer &segServer, double threshold, SegCluster &selectedSeg, SegCluster &outputSeg, String labelOutput, String fileName)
MixtureGD & energyMixtureInit (MixtureServer &ms, StatServer &ss, FeatureServer &fs, MixtureGD &world, SegCluster &selectedSegments, const DoubleVector &globalCov, Config &config)
SegCluster & energyDetector (Config &config, SegServer &segServer, String &featureFileName)
Macro Definition Documentation
#define ALIZE_EnergyDetector_cpp
Definition at line 56 of file EnergyDetector.cpp.
#define DirectInterpolation 1
Definition at line 66 of file EnergyDetector.cpp.
Function Documentation
double computeEnergyThreshold (FeatureServer & fs, double pSelect, unsigned long nbBins = 100)
Definition at line 106 of file EnergyDetector.cpp.
References verbose.
Referenced by energyDetector().
SegCluster& energyDetector (Config & config, SegServer & segServer, String & featureFileName)
Definition at line 200 of file EnergyDetector.cpp.
References accumulateStatEM(), computeEnergyThreshold(), energyMixtureInit(), findMaxEnergyDistrib(), findMinEnergyDistrib(), globalMeanCov(), initializeClusters(), likelihoodLoss(), plotEnergyDistrib(), selectFrames(), sqrt(), varianceControl(), verbose, and verboseLevel.
Referenced by main().
MixtureGD& energyMixtureInit (MixtureServer & ms, StatServer & ss, FeatureServer & fs, MixtureGD & world, SegCluster & selectedSegments, const DoubleVector & globalCov, Config & config)
Definition at line 173 of file EnergyDetector.cpp.
Referenced by energyDetector().
unsigned long findMaxEnergyDistrib (MixtureGD & mixt)
Definition at line 82 of file EnergyDetector.cpp.
References verbose.
Referenced by energyDetector().
unsigned long findMinEnergyDistrib (MixtureGD & mixt)
Definition at line 94 of file EnergyDetector.cpp.
References verbose.
Referenced by energyDetector().
void plotEnergyDistrib (MixtureGD & mixt)
Definition at line 72 of file EnergyDetector.cpp.
Referenced by energyDetector().
unsigned long selectFrames (FeatureServer & fs, SegServer & segServer, double threshold, SegCluster & selectedSeg, SegCluster & outputSeg, String labelOutput, String fileName)
Definition at line 128 of file EnergyDetector.cpp.
Referenced by energyDetector().