LIA_RAL: LIA_SpkDet/EnergyDetector/include/EnergyDetector.h File Reference
EnergyDetector.h File Reference
#include "alize.h"
Functions
SegCluster & energyDetector (Config &config, SegServer &segServer, String &featureFileName)
SegCluster & turnDetector (Config &config, SegServer &segServer, const String &featureFileName)
Function Documentation
SegCluster& energyDetector (Config & config, SegServer & segServer, String & featureFileName)
Definition at line 200 of file EnergyDetector.cpp.
References accumulateStatEM(), computeEnergyThreshold(), energyMixtureInit(), findMaxEnergyDistrib(), findMinEnergyDistrib(), globalMeanCov(), initializeClusters(), likelihoodLoss(), plotEnergyDistrib(), selectFrames(), sqrt(), varianceControl(), verbose, and verboseLevel.
Referenced by main().
SegCluster& turnDetector (Config & config, SegServer & segServer, const String & featureFileName)