LIA_RAL: LIA_Utils/FusionScore/src/FusionScore.cpp File Reference
FusionScore.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include "FusionScore.h"
#include <liatools.h>
Macros
#define ALIZE_FusionScore_cpp
Functions
void computeFusion (XLine &lineTab, XLine &finalScore, XList &weights, Histo &destH, Config &config)
void findNbest (XLine &tabScoreLine, int Nbest, int comp_double(const void *a, const void *b))
int comp_double (const void *a, const void *b)
String extractModel (String &classModel)
int FusionScore (Config &config)
int FusionClassScore (Config &config)
Macro Definition Documentation
#define ALIZE_FusionScore_cpp
Definition at line 56 of file FusionScore.cpp.
Function Documentation
int comp_double (const void * a, const void * b)
Definition at line 137 of file FusionScore.cpp.
Referenced by findNbest(), and FusionScore().
void computeFusion (XLine & lineTab, XLine & finalScore, XList & weights, Histo & destH, Config & config)
Definition at line 70 of file FusionScore.cpp.
References debug, and pow().
Referenced by FusionClassScore(), and FusionScore().
String extractModel (String & classModel)
Definition at line 143 of file FusionScore.cpp.
Referenced by FusionClassScore().
void findNbest (XLine & tabScoreLine, int Nbest, int comp_doubleconst void *a, const void *b)
Definition at line 120 of file FusionScore.cpp.
References comp_double().
Referenced by FusionScore().
int FusionClassScore (Config & config)
Definition at line 258 of file FusionScore.cpp.
References computeFusion(), debug, extractModel(), outputResultLine(), outputResultNIST04Line(), setLIAInfoFields(), and setNIST04InfoFields().
int FusionScore (Config & config)
Definition at line 154 of file FusionScore.cpp.
References comp_double(), computeFusion(), debug, findNbest(), outputResultLine(), outputResultNIST04Line(), setLIAInfoFields(), and setNIST04InfoFields().