LIA_RAL: LIA_SpkTools/include/GeneralTools.h File Reference
GeneralTools.h File Reference
#include "alize.h"
#include "liatools.h"
Classes
class TabClientLine
class TabHisto
class ScoreAccum
struct TabWeightElem
class TabWeight
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API double computeEntropy (Histo &hist)
LIA_SPKTOOLS_API double computeMean (Histo &hist)
LIA_SPKTOOLS_API long setDecision (double LLRClient, double decisionThreshold)
LIA_SPKTOOLS_API int _compF (const void *op1, const void *op2)
LIA_SPKTOOLS_API bool baggedFrame (double baggedFrameProbability)
LIA_SPKTOOLS_API void baggedSegments (SegCluster &, SegCluster &, double, unsigned long=3, unsigned long=7)
LIA_SPKTOOLS_API void baggedSegmentsConstraint (SegCluster &, SegCluster &, double, unsigned long=3, unsigned long=7)
LIA_SPKTOOLS_API void baggedSegments (SegCluster &selectedSegments, SegCluster &baggedSeg, unsigned long nbBagged, double &baggedProbability, unsigned long minimumLength, unsigned long maximumLength)
LIA_SPKTOOLS_API void baggedSegments (SegCluster &selectedSegments, SegCluster &baggedSelected, SegCluster &baggedUnselected, double baggedProbability, unsigned long minimumLength, unsigned long maximumLength)
LIA_SPKTOOLS_API double meanLikelihood (StatServer &ss, FeatureServer &fs, MixtureGD &model, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
LIA_SPKTOOLS_API double meanLikelihood (StatServer &ss, FeatureServer &fs, MixtureGD &model, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API double meanLikelihood (StatServer &ss, FeatureServer **fsTab, SegCluster **segTab, unsigned long nbStream, MixtureGD &model, Config &config)
LIA_SPKTOOLS_API double meanLikelihood (StatServer &ss, ObjectRefVector &FeatServ, ObjectRefVector &ClusterSeg, MixtureGD &model, DoubleVector &decision, Config &config)
LIA_SPKTOOLS_API void globalMeanCov (FeatureServer &fs, SegCluster &selectedSegments, FrameAcc &globalFrameAcc, Config &config)
LIA_SPKTOOLS_API void globalMeanCov (FeatureServer &fs, FrameAcc &globalFrameAcc, Config &config)
LIA_SPKTOOLS_API double areaHisto (const Histo &histo, unsigned long bin)
LIA_SPKTOOLS_API double areaHisto (const Histo &histo, unsigned long bin, double nonObserved)
LIA_SPKTOOLS_API double linearInterpolation (double val, double lower, double higher)
LIA_SPKTOOLS_API void freezeHistoTab (Histo *&histoT)
LIA_SPKTOOLS_API void initHistoTab (Histo *&histoT, unsigned long size, unsigned long nbBins)
LIA_SPKTOOLS_API void computeHistoTab (Histo *histoT, unsigned long size)
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, Seg *seg, Config &config)
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo *histoT, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API void computeWarp (Histo *histoT, Histo &destH, FeatureServer &fs, unsigned long begin, unsigned long length, Config &config)
LIA_SPKTOOLS_API void computeWarp (Histo *histoT, Histo &destH, FeatureServer &fs, Seg *seg, Config &config)
LIA_SPKTOOLS_API void computeWarp (Histo *histoT, Histo &destH, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API void cms (String &, FeatureServer &, Config &)
LIA_SPKTOOLS_API void computeZeroOne (FrameAccGD &frameAccu, FeatureServer &fs, unsigned long begin, unsigned long length, Config &config)
LIA_SPKTOOLS_API void computeZeroOne (FrameAccGD &frameAccu, FeatureServer &fs, Seg *seg, Config &config)
LIA_SPKTOOLS_API void computeZeroOne (FrameAccGD &frameAccu, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API void computeZeroOne (const DoubleVector &mean, const DoubleVector &cov, FeatureServer &fs, unsigned long begin, unsigned long length, Config &config)
LIA_SPKTOOLS_API void computeZeroOne (const DoubleVector &mean, const DoubleVector &cov, FeatureServer &fs, Seg *seg, Config &config)
LIA_SPKTOOLS_API void computeZeroOne (const DoubleVector &mean, const DoubleVector &cov, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API void outputFeatureFile (Config &config, FeatureServer &fs, Feature &f, FeatureFileWriter &w)
LIA_SPKTOOLS_API void outputFeatureFile (Config &config, FeatureServer &fs, Seg *seg, FeatureFileWriter &w)
LIA_SPKTOOLS_API void outputFeatureFile (Config &config, FeatureServer &fs, SegCluster &selectedSegments, FeatureFileWriter &w)
LIA_SPKTOOLS_API void outputFeatureFile (Config &config, FeatureServer &fs, unsigned long begin, unsigned long length, FeatureFileWriter &w)
LIA_SPKTOOLS_API unsigned long getBestGaussian (Mixture &M, Feature &f)
LIA_SPKTOOLS_API void mapDataToDistrib (double &data, const double meanData, const double covData, const double meanMap, const double covMap)
LIA_SPKTOOLS_API void featureMapping (MixtureServer &ms, FeatureServer &fs, unsigned long begin, unsigned long length, Config &config)
LIA_SPKTOOLS_API void featureMapping (MixtureServer &ms, FeatureServer &fs, Seg *seg, Config &config)
LIA_SPKTOOLS_API void featureMapping (MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API double likelihoodGD (const DistribGD &, const DistribGD &)
LIA_SPKTOOLS_API double likelihoodGD (const MixtureGD &, const MixtureGD &)
LIA_SPKTOOLS_API double likelihoodGD (const MixtureGD &, const MixtureGD &, TabWeight &)
LIA_SPKTOOLS_API double likelihoodGD (const MixtureGD &, const MixtureGD &, TabWeight &, TabWeight &)
Variables
const unsigned long CST_MAX_CLIENT_LINE =500
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file GeneralTools.h.
Function Documentation
LIA_SPKTOOLS_API int _compF (const void * op1, const void * op2)
Definition at line 277 of file GeneralTools.cpp.
Referenced by TabWeight::_sortByWeight().
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 453 of file AccumulateStat.cpp.
Referenced by accumulateHistoFrame().
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 465 of file AccumulateStat.cpp.
References accumulateHistoFrame().
LIA_SPKTOOLS_API void accumulateHistoFrame (Histo * histoT, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 471 of file AccumulateStat.cpp.
References accumulateHistoFrame().
LIA_SPKTOOLS_API double areaHisto (const Histo & histo, unsigned long bin)
Definition at line 424 of file AccumulateStat.cpp.
Referenced by areaHisto().
LIA_SPKTOOLS_API double areaHisto (const Histo & histo, unsigned long bin, double nonObserved)
Definition at line 428 of file AccumulateStat.cpp.
References areaHisto().
LIA_SPKTOOLS_API bool baggedFrame (double baggedFrameProbability)
Definition at line 309 of file GeneralTools.cpp.
Referenced by baggedSegments().
LIA_SPKTOOLS_API void baggedSegments (SegCluster & , SegCluster & , double , unsigned long = 3, unsigned long = 7)
Definition at line 455 of file GeneralTools.cpp.
References baggedFrame(), correctedLength(), debug, showCluster(), totalFrame(), verbose, and verboseLevel.
Referenced by adaptModel(), adaptModelEM(), crossValid(), mixtureInit(), modelBasedadaptModel(), modelBasedadaptModelEM(), trainModel(), and trainModelStream().
LIA_SPKTOOLS_API void baggedSegments (SegCluster & selectedSegments, SegCluster & baggedSeg, unsigned long nbBagged, double & baggedProbability, unsigned long minimumLength, unsigned long maximumLength)
Definition at line 330 of file GeneralTools.cpp.
References baggedFrame(), correctedLength(), debug, showCluster(), totalFrame(), verbose, and verboseLevel.
Referenced by baggedSegmentsConstraint().
LIA_SPKTOOLS_API void baggedSegments (SegCluster & selectedSegments, SegCluster & baggedSelected, SegCluster & baggedUnselected, double baggedProbability, unsigned long minimumLength, unsigned long maximumLength)
Definition at line 513 of file GeneralTools.cpp.
References baggedFrame(), correctedLength(), debug, showCluster(), totalFrame(), and verboseLevel.
LIA_SPKTOOLS_API void baggedSegmentsConstraint (SegCluster & , SegCluster & , double , unsigned long = 3, unsigned long = 7)
Definition at line 322 of file GeneralTools.cpp.
References baggedSegments(), and totalFrame().
LIA_SPKTOOLS_API void cms (String & , FeatureServer & , Config &)
Definition at line 713 of file GeneralTools.cpp.
References accumulateStatFrame(), computeZeroOne(), initializeClusters(), and verifyClusterFile().
Referenced by ComputeTestLFA(), normFeat(), normFeatFA(), and normFeatLFA().
LIA_SPKTOOLS_API double computeEntropy (Histo & hist)
Definition at line 194 of file GeneralTools.cpp.
References log().
Referenced by ComputeTestHisto().
LIA_SPKTOOLS_API void computeHistoTab (Histo * histoT, unsigned long size)
Definition at line 448 of file AccumulateStat.cpp.
LIA_SPKTOOLS_API double computeMean (Histo & hist)
Definition at line 213 of file GeneralTools.cpp.
Referenced by ComputeTestHisto().
LIA_SPKTOOLS_API void computeWarp (Histo * histoT, Histo & destH, FeatureServer & fs, unsigned long begin, unsigned long length, Config & config)
Definition at line 642 of file GeneralTools.cpp.
References warping().
Referenced by computeWarp(), and normFeat().
LIA_SPKTOOLS_API void computeWarp (Histo * histoT, Histo & destH, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 656 of file GeneralTools.cpp.
References computeWarp().
LIA_SPKTOOLS_API void computeWarp (Histo * histoT, Histo & destH, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 661 of file GeneralTools.cpp.
References computeWarp().
LIA_SPKTOOLS_API void computeZeroOne (FrameAccGD & frameAccu, FeatureServer & fs, unsigned long begin, unsigned long length, Config & config)
Definition at line 683 of file GeneralTools.cpp.
References computeZeroOne().
Referenced by normFeat().
LIA_SPKTOOLS_API void computeZeroOne (FrameAccGD & frameAccu, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 689 of file GeneralTools.cpp.
References computeZeroOne().
LIA_SPKTOOLS_API void computeZeroOne (FrameAccGD & frameAccu, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 700 of file GeneralTools.cpp.
References computeZeroOne().
LIA_SPKTOOLS_API void computeZeroOne (const DoubleVector & mean, const DoubleVector & cov, FeatureServer & fs, unsigned long begin, unsigned long length, Config & config)
Definition at line 670 of file GeneralTools.cpp.
Referenced by cms(), and computeZeroOne().
LIA_SPKTOOLS_API void computeZeroOne (const DoubleVector & mean, const DoubleVector & cov, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 695 of file GeneralTools.cpp.
References computeZeroOne().
LIA_SPKTOOLS_API void computeZeroOne (const DoubleVector & mean, const DoubleVector & cov, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 705 of file GeneralTools.cpp.
References computeZeroOne(), and verbose.
LIA_SPKTOOLS_API void featureMapping (MixtureServer & ms, FeatureServer & fs, unsigned long begin, unsigned long length, Config & config)
Referenced by featMap().
LIA_SPKTOOLS_API void featureMapping (MixtureServer & ms, FeatureServer & fs, Seg * seg, Config & config)
Definition at line 793 of file GeneralTools.cpp.
References featureMapping().
LIA_SPKTOOLS_API void featureMapping (MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 805 of file GeneralTools.cpp.
References featureMapping().
LIA_SPKTOOLS_API void freezeHistoTab (Histo *& histoT)
Definition at line 438 of file AccumulateStat.cpp.
LIA_SPKTOOLS_API unsigned long getBestGaussian (Mixture & M, Feature & f)
Definition at line 762 of file GeneralTools.cpp.
Referenced by featureMapping().
LIA_SPKTOOLS_API void globalMeanCov (FeatureServer & fs, SegCluster & selectedSegments, FrameAcc & globalFrameAcc, Config & config)
Definition at line 629 of file GeneralTools.cpp.
References accumulateStatFrame().
Referenced by clusteringCriterion(), clusteringCriterionWithoutWorldInit(), energyDetector(), infoFeat(), InitOneGausMixture(), learnModel(), learnModelFromBaggedFrame(), and learnModelFromSplit().
LIA_SPKTOOLS_API void globalMeanCov (FeatureServer & fs, FrameAcc & globalFrameAcc, Config & config)
Definition at line 634 of file GeneralTools.cpp.
References accumulateStatFrame().
LIA_SPKTOOLS_API void initHistoTab (Histo *& histoT, unsigned long size, unsigned long nbBins)
Definition at line 442 of file AccumulateStat.cpp.
LIA_SPKTOOLS_API double likelihoodGD (const DistribGD & , const DistribGD &)
Definition at line 816 of file GeneralTools.cpp.
References exp().
Referenced by computeLLRGD(), likelihoodGD(), modelBasedadaptModel(), and modelBasedadaptModelEM().
LIA_SPKTOOLS_API double likelihoodGD (const MixtureGD & , const MixtureGD &)
Definition at line 852 of file GeneralTools.cpp.
References likelihoodGD().
LIA_SPKTOOLS_API double likelihoodGD (const MixtureGD & , const MixtureGD & , TabWeight &)
Definition at line 848 of file GeneralTools.cpp.
References likelihoodGD().
LIA_SPKTOOLS_API double likelihoodGD (const MixtureGD & , const MixtureGD & , TabWeight & , TabWeight &)
Definition at line 828 of file GeneralTools.cpp.
References debug, TabWeightElem::distribP, TabWeight::getArray(), TabWeight::getDistrib(), TabWeight::getNbTop(), TabWeight::getWeight(), likelihoodGD(), log(), and TabWeightElem::weight.
LIA_SPKTOOLS_API double linearInterpolation (double val, double lower, double higher)
Definition at line 432 of file AccumulateStat.cpp.
LIA_SPKTOOLS_API void mapDataToDistrib (double & data, const double meanData, const double covData, const double meanMap, const double covMap)
Definition at line 777 of file GeneralTools.cpp.
References sqrt().
Referenced by featureMapping().
LIA_SPKTOOLS_API double meanLikelihood (StatServer & ss, FeatureServer & fs, MixtureGD & model, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 580 of file GeneralTools.cpp.
References accumulateStatLLK().
Referenced by adaptModel(), adaptModelEM(), bestFittingCluster(), bestFittingSegment(), cohortMaxLikelihood(), computeLLKMeanOnOneCluster(), crossValid(), mixtureInitBySplit(), modelBasedadaptModel(), modelBasedadaptModelEM(), trainModel(), and trainModelStream().
LIA_SPKTOOLS_API double meanLikelihood (StatServer & ss, FeatureServer & fs, MixtureGD & model, SegCluster & selectedSegments, Config & config)
Definition at line 589 of file GeneralTools.cpp.
References accumulateStatLLK().
LIA_SPKTOOLS_API double meanLikelihood (StatServer & ss, FeatureServer ** fsTab, SegCluster ** segTab, unsigned long nbStream, MixtureGD & model, Config & config)
Definition at line 599 of file GeneralTools.cpp.
References accumulateStatLLK().
LIA_SPKTOOLS_API double meanLikelihood (StatServer & ss, ObjectRefVector & FeatServ, ObjectRefVector & ClusterSeg, MixtureGD & model, DoubleVector & decision, Config & config)
Definition at line 610 of file GeneralTools.cpp.
References accumulateStatLLK().
LIA_SPKTOOLS_API void outputFeatureFile (Config & config, FeatureServer & fs, Feature & f, FeatureFileWriter & w)
Definition at line 733 of file GeneralTools.cpp.
Referenced by featMap(), featWarp(), normFeat(), normFeatFA(), normFeatLFA(), normFeatNAP(), and outputFeatureFile().
LIA_SPKTOOLS_API void outputFeatureFile (Config & config, FeatureServer & fs, Seg * seg, FeatureFileWriter & w)
Definition at line 746 of file GeneralTools.cpp.
References outputFeatureFile(), and verbose.
LIA_SPKTOOLS_API void outputFeatureFile (Config & config, FeatureServer & fs, SegCluster & selectedSegments, FeatureFileWriter & w)
Definition at line 753 of file GeneralTools.cpp.
References outputFeatureFile().
LIA_SPKTOOLS_API void outputFeatureFile (Config & config, FeatureServer & fs, unsigned long begin, unsigned long length, FeatureFileWriter & w)
Definition at line 738 of file GeneralTools.cpp.
References outputFeatureFile().
LIA_SPKTOOLS_API long setDecision (double LLRClient, double decisionThreshold)
Definition at line 232 of file GeneralTools.cpp.
Referenced by ComputeTest(), ComputeTestByLabel(), ComputeTestDotProduct(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), and IvTest().
Variable Documentation
const unsigned long CST_MAX_CLIENT_LINE =500
Definition at line 76 of file GeneralTools.h.
Referenced by ComputeTest(), ComputeTestByLabel(), ComputeTestDotProduct(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), and IvTest().