LIA_RAL: LIA_Utils/GmmTokenizer/src/GmmTokenizer.cpp File Reference
GmmTokenizer.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include "GmmTokenizer.h"
#include "liatools.h"
Macros
#define ALIZE_GMMTokenizer_cpp
Functions
void computeConfusionMatrix (Feature &f, StatServer &ss, MixtureGDStat &acc, unsigned long &nBest, Matrix< unsigned long > &mce_matrix)
void computeConfusionMatrix (Seg *seg, FeatureServer &fs, StatServer &ss, MixtureGDStat &acc, unsigned long &nBest, Matrix< unsigned long > &mce_matrix)
void computeConfusionMatrix (SegCluster &selectedSegments, FeatureServer &fs, StatServer &ss, MixtureGD &world, unsigned long &nBest, Matrix< unsigned long > &mce_matrix)
void computeSymbols (Feature &f, MixtureGD &world, StatServer &ss, ULongVector &stream, Config &config)
void computeSymbols (Seg *seg, FeatureServer &fs, MixtureGD &world, StatServer &ss, ULongVector &stream, Config &config)
void computeSymbols (SegCluster &selectedSegments, FeatureServer &fs, MixtureGD &world, StatServer &ss, ULongVector &stream, Config &config)
int GaussianConfusionMatrix (Config &config)
int GMMTokenizer (Config &config)
Macro Definition Documentation
#define ALIZE_GMMTokenizer_cpp
Definition at line 56 of file GmmTokenizer.cpp.
Function Documentation
void computeConfusionMatrix (Feature & f, StatServer & ss, MixtureGDStat & acc, unsigned long & nBest, Matrix< unsigned long > & mce_matrix)
Definition at line 69 of file GmmTokenizer.cpp.
Referenced by computeConfusionMatrix(), and GaussianConfusionMatrix().
void computeConfusionMatrix (Seg * seg, FeatureServer & fs, StatServer & ss, MixtureGDStat & acc, unsigned long & nBest, Matrix< unsigned long > & mce_matrix)
Definition at line 79 of file GmmTokenizer.cpp.
References computeConfusionMatrix().
void computeConfusionMatrix (SegCluster & selectedSegments, FeatureServer & fs, StatServer & ss, MixtureGD & world, unsigned long & nBest, Matrix< unsigned long > & mce_matrix)
Definition at line 89 of file GmmTokenizer.cpp.
References computeConfusionMatrix().
void computeSymbols (Feature & f, MixtureGD & world, StatServer & ss, ULongVector & stream, Config & config)
Definition at line 99 of file GmmTokenizer.cpp.
Referenced by computeSymbols(), and GMMTokenizer().
void computeSymbols (Seg * seg, FeatureServer & fs, MixtureGD & world, StatServer & ss, ULongVector & stream, Config & config)
Definition at line 107 of file GmmTokenizer.cpp.
References computeSymbols().
void computeSymbols (SegCluster & selectedSegments, FeatureServer & fs, MixtureGD & world, StatServer & ss, ULongVector & stream, Config & config)
Definition at line 117 of file GmmTokenizer.cpp.
References computeSymbols().
int GaussianConfusionMatrix (Config & config)
Definition at line 125 of file GmmTokenizer.cpp.
References computeConfusionMatrix(), initializeClusters(), verbose, and verifyClusterFile().
int GMMTokenizer (Config & config)
Definition at line 170 of file GmmTokenizer.cpp.
References computeSymbols(), initializeClusters(), verbose, and verifyClusterFile().