LIA_RAL: LIA_Utils/Svm/include/libsvm.h File Reference
libsvm.h File Reference
Classes
struct svm_node
struct svm_problem
struct svm_parameter
Enumerations
enum {
C_SVC, NU_SVC, ONE_CLASS, EPSILON_SVR,
NU_SVR
}
enum {
LINEAR, POLY, RBF, SIGMOID,
PRECOMPUTED
}
Functions
struct svm_model * svm_train (const struct svm_problem *prob, const struct svm_parameter *param)
void svm_cross_validation (const struct svm_problem *prob, const struct svm_parameter *param, int nr_fold, double *target)
int svm_save_model (const char *model_file_name, const struct svm_model *model)
struct svm_model * svm_load_model (const char *model_file_name)
int svm_get_svm_type (const struct svm_model *model)
int svm_get_nr_class (const struct svm_model *model)
void svm_get_labels (const struct svm_model *model, int *label)
double svm_get_svr_probability (const struct svm_model *model)
void svm_predict_values (const struct svm_model *model, const struct svm_node *x, double *dec_values)
double svm_predict (const struct svm_model *model, const struct svm_node *x)
double svm_predict_probability (const struct svm_model *model, const struct svm_node *x, double *prob_estimates)
void svm_destroy_model (struct svm_model *model)
void svm_destroy_param (struct svm_parameter *param)
const char * svm_check_parameter (const struct svm_problem *prob, const struct svm_parameter *param)
int svm_check_probability_model (const struct svm_model *model)
Enumeration Type Documentation
anonymous enum
Enumerator
C_SVC
NU_SVC
ONE_CLASS
EPSILON_SVR
NU_SVR
Definition at line 21 of file libsvm.h.
anonymous enum
Enumerator
LINEAR
POLY
RBF
SIGMOID
PRECOMPUTED
Definition at line 22 of file libsvm.h.
Function Documentation
const char* svm_check_parameter (const struct svm_problem * prob, const struct svm_parameter * param)
Referenced by svmTrain().
int svm_check_probability_model (const struct svm_model * model)
void svm_cross_validation (const struct svm_problem * prob, const struct svm_parameter * param, int nr_fold, double * target)
void svm_destroy_model (struct svm_model * model)
Definition at line 2915 of file libsvm.cpp.
Referenced by svmTrain().
void svm_destroy_param (struct svm_parameter * param)
Definition at line 2921 of file libsvm.cpp.
Referenced by svmTrain().
void svm_get_labels (const struct svm_model * model, int * label)
int svm_get_nr_class (const struct svm_model * model)
int svm_get_svm_type (const struct svm_model * model)
double svm_get_svr_probability (const struct svm_model * model)
struct svm_model* svm_load_model (const char * model_file_name)
Definition at line 2690 of file libsvm.cpp.
double svm_predict (const struct svm_model * model, const struct svm_node * x)
double svm_predict_probability (const struct svm_model * model, const struct svm_node * x, double * prob_estimates)
void svm_predict_values (const struct svm_model * model, const struct svm_node * x, double * dec_values)
int svm_save_model (const char * model_file_name, const struct svm_model * model)
struct svm_model* svm_train (const struct svm_problem * prob, const struct svm_parameter * param)
Referenced by svmTrain().