LIA_RAL: LIA_SpkTools/src/IOFormat.cpp File Reference
IOFormat.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "IOFormat.h"
Macros
#define ALIZE_IOFormat_cpp
Functions
void outputWeightVector (MixtureGD &world, MixtureGD &clientMixture, double frameCount, Config &config)
void outputSVMLightVector (RealVector< double > &v, const String &id, Config &config)
void outputDSM (DoubleSquareMatrix &W, MixtureGD &clientMixture, Config &config)
void outputResultLine (double LLR, const String &clientName, const String &seg, const String &gender, int decision, ostream &strm)
void outputResultLine (double LLR, const String &clientName, const String &seg, real_t begin, real_t end, const String &gender, int decision, ostream &strm)
void outputResultLIARALLine (const String &gender, const String &clientName, const String &channel, const String &seg, const String &start, const String &duration, double LLR, ostream &strm)
void outputResultNIST04Line (const String &trainTypeTest, const String &adaptationMode, const String &segTypeTest, const String &gender, const String &clientName, const String &seg, const String &decision, double LLR, ostream &strm)
void outputResultETFLine (const String &source, const String &channel, const String &start, double duration, const String &type, const String &sub, const String &event, double score, const String &decision, ostream &strm)
void outputResultMDTMLine (const String &source, const String &channel, const String &start, double duration, const String &type, double conf, const String &sub, ostream &strm)
void setLIAInfoFields (unsigned long &genderField, unsigned long &nameField, unsigned long &decisionField, unsigned long &segField, unsigned long &scoreField)
void setNIST04InfoFields (unsigned long &genderField, unsigned long &nameField, unsigned long &decisionField, unsigned long &segField, unsigned long &scoreField)
Macro Definition Documentation
#define ALIZE_IOFormat_cpp
Definition at line 56 of file IOFormat.cpp.
Function Documentation
void outputDSM (DoubleSquareMatrix & W, MixtureGD & clientMixture, Config & config)
Definition at line 99 of file IOFormat.cpp.
References verbose.
void outputResultETFLine (const String & source, const String & channel, const String & start, double duration, const String & type, const String & sub, const String & event, double score, const String & decision, ostream & strm)
Definition at line 138 of file IOFormat.cpp.
Referenced by Scoring().
void outputResultLIARALLine (const String & gender, const String & clientName, const String & channel, const String & seg, const String & start, const String & duration, double LLR, ostream & strm)
Definition at line 124 of file IOFormat.cpp.
Referenced by Scoring().
void outputResultLine (double LLR, const String & clientName, const String & seg, const String & gender, int decision, ostream & strm)
Definition at line 112 of file IOFormat.cpp.
Referenced by ComputeNorm(), ComputeTest(), ComputeTestByLabel(), ComputeTestDotProduct(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), FusionClassScore(), FusionScore(), IvTest(), svmPredict(), and svmPredictTnorm().
void outputResultLine (double LLR, const String & clientName, const String & seg, real_t begin, real_t end, const String & gender, int decision, ostream & strm)
Definition at line 117 of file IOFormat.cpp.
void outputResultMDTMLine (const String & source, const String & channel, const String & start, double duration, const String & type, double conf, const String & sub, ostream & strm)
Definition at line 145 of file IOFormat.cpp.
Referenced by Scoring().
void outputResultNIST04Line (const String & trainTypeTest, const String & adaptationMode, const String & segTypeTest, const String & gender, const String & clientName, const String & seg, const String & decision, double LLR, ostream & strm)
Definition at line 131 of file IOFormat.cpp.
Referenced by FusionClassScore(), FusionScore(), Scoring(), and WarpScores().
void outputSVMLightVector (RealVector< double > & v, const String & id, Config & config)
Definition at line 87 of file IOFormat.cpp.
void outputWeightVector (MixtureGD & world, MixtureGD & clientMixture, double frameCount, Config & config)
Definition at line 71 of file IOFormat.cpp.
References sqrt(), and verbose.
Referenced by main().
void setLIAInfoFields (unsigned long & genderField, unsigned long & nameField, unsigned long & decisionField, unsigned long & segField, unsigned long & scoreField)
Definition at line 155 of file IOFormat.cpp.
Referenced by FusionClassScore(), FusionScore(), and Scoring().
void setNIST04InfoFields (unsigned long & genderField, unsigned long & nameField, unsigned long & decisionField, unsigned long & segField, unsigned long & scoreField)
Definition at line 165 of file IOFormat.cpp.
Referenced by FusionClassScore(), and FusionScore().