LIA_RAL: LIA_SpkTools/include/IOFormat.h File Reference
IOFormat.h File Reference
#include <alize.h>
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API void outputWeightVector (MixtureGD &world, MixtureGD &clientMixture, double frameCount, Config &config)
LIA_SPKTOOLS_API void outputSVMLightVector (RealVector< double > &, const String &, Config &)
LIA_SPKTOOLS_API void outputDSM (DoubleSquareMatrix &, MixtureGD &, Config &)
LIA_SPKTOOLS_API void outputResultLine (double LLR, const String &clientName, const String &seg, const String &gender, int decision, ostream &strm)
LIA_SPKTOOLS_API void outputResultLine (double LLR, const String &clientName, const String &seg, real_t begin, real_t end, const String &gender, int decision, ostream &strm)
LIA_SPKTOOLS_API void outputResultLIARALLine (const String &gender, const String &clientName, const String &channel, const String &seg, const String &start, const String &duration, double LLR, ostream &strm)
LIA_SPKTOOLS_API void outputResultNIST04Line (const String &trainTypeTest, const String &adaptationMode, const String &segTypeTest, const String &gender, const String &clientName, const String &seg, const String &decision, double LLR, ostream &strm)
LIA_SPKTOOLS_API void outputResultETFLine (const String &source, const String &channel, const String &start, double duration, const String &type, const String &sub, const String &event, double score, const String &decision, ostream &strm)
LIA_SPKTOOLS_API void outputResultMDTMLine (const String &source, const String &channel, const String &start, double duration, const String &type, double conf, const String &sub, ostream &strm)
LIA_SPKTOOLS_API void setLIAInfoFields (unsigned long &genderField, unsigned long &nameField, unsigned long &decisionField, unsigned long &segField, unsigned long &scoreField)
LIA_SPKTOOLS_API void setNIST04InfoFields (unsigned long &genderField, unsigned long &nameField, unsigned long &decisionField, unsigned long &segField, unsigned long &scoreField)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file IOFormat.h.
Function Documentation
LIA_SPKTOOLS_API void outputDSM (DoubleSquareMatrix & , MixtureGD & , Config &)
Definition at line 99 of file IOFormat.cpp.
References verbose.
LIA_SPKTOOLS_API void outputResultETFLine (const String & source, const String & channel, const String & start, double duration, const String & type, const String & sub, const String & event, double score, const String & decision, ostream & strm)
Definition at line 138 of file IOFormat.cpp.
Referenced by Scoring().
LIA_SPKTOOLS_API void outputResultLIARALLine (const String & gender, const String & clientName, const String & channel, const String & seg, const String & start, const String & duration, double LLR, ostream & strm)
Definition at line 124 of file IOFormat.cpp.
Referenced by Scoring().
LIA_SPKTOOLS_API void outputResultLine (double LLR, const String & clientName, const String & seg, const String & gender, int decision, ostream & strm)
Definition at line 112 of file IOFormat.cpp.
Referenced by ComputeNorm(), ComputeTest(), ComputeTestByLabel(), ComputeTestDotProduct(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), FusionClassScore(), FusionScore(), IvTest(), svmPredict(), and svmPredictTnorm().
LIA_SPKTOOLS_API void outputResultLine (double LLR, const String & clientName, const String & seg, real_t begin, real_t end, const String & gender, int decision, ostream & strm)
Definition at line 117 of file IOFormat.cpp.
LIA_SPKTOOLS_API void outputResultMDTMLine (const String & source, const String & channel, const String & start, double duration, const String & type, double conf, const String & sub, ostream & strm)
Definition at line 145 of file IOFormat.cpp.
Referenced by Scoring().
LIA_SPKTOOLS_API void outputResultNIST04Line (const String & trainTypeTest, const String & adaptationMode, const String & segTypeTest, const String & gender, const String & clientName, const String & seg, const String & decision, double LLR, ostream & strm)
Definition at line 131 of file IOFormat.cpp.
Referenced by FusionClassScore(), FusionScore(), Scoring(), and WarpScores().
LIA_SPKTOOLS_API void outputSVMLightVector (RealVector< double > & , const String & , Config &)
Definition at line 87 of file IOFormat.cpp.
LIA_SPKTOOLS_API void outputWeightVector (MixtureGD & world, MixtureGD & clientMixture, double frameCount, Config & config)
Definition at line 71 of file IOFormat.cpp.
References sqrt(), and verbose.
Referenced by main().
LIA_SPKTOOLS_API void setLIAInfoFields (unsigned long & genderField, unsigned long & nameField, unsigned long & decisionField, unsigned long & segField, unsigned long & scoreField)
Definition at line 155 of file IOFormat.cpp.
Referenced by FusionClassScore(), FusionScore(), and Scoring().
LIA_SPKTOOLS_API void setNIST04InfoFields (unsigned long & genderField, unsigned long & nameField, unsigned long & decisionField, unsigned long & segField, unsigned long & scoreField)
Definition at line 165 of file IOFormat.cpp.
Referenced by FusionClassScore(), and FusionScore().