LIA_RAL: LIA_SpkDet/IvExtractor/include/IvExtractor.h File Reference
IvExtractor.h File Reference
#include "alize.h"
Functions
int InfoTarget (Config &config)
int IvExtractor (Config &config)
int IvExtractorUbmWeigth (Config &config)
int IvExtractorEigenDecomposition (Config &config)
Function Documentation
int InfoTarget (Config & config)
Definition at line 72 of file IvExtractor.cpp.
Referenced by main().
int IvExtractor (Config & config)
Definition at line 134 of file IvExtractor.cpp.
References TVAcc::computeAndAccumulateTVStat(), TVAcc::estimateTETt(), TVAcc::estimateW(), TVAcc::getUbmMeans(), TVAcc::loadF_X(), TVAcc::loadMeanEstimate(), TVAcc::loadN(), TVAcc::loadT(), TVAcc::saveAccs(), TVAcc::saveWbyFile(), TVAcc::substractM(), and verbose.
Referenced by main().
int IvExtractorEigenDecomposition (Config & config)
Definition at line 317 of file IvExtractor.cpp.
References TVAcc::approximateTcTc(), TVAcc::computeAndAccumulateTVStat(), TVAcc::computeEigenProblem(), TVAcc::estimateWEigenDecomposition(), TVAcc::getNDistrib(), TVAcc::getRankT(), TVAcc::getUbmMeans(), TVAcc::getWeightedCov(), TVAcc::loadF_X(), TVAcc::loadMeanEstimate(), TVAcc::loadN(), TVAcc::loadT(), TVAcc::normStatistics(), TVAcc::normTMatrix(), TVAcc::saveAccs(), TVAcc::saveWbyFile(), and verbose.
Referenced by main().
int IvExtractorUbmWeigth (Config & config)
Definition at line 215 of file IvExtractor.cpp.
References TVAcc::computeAndAccumulateTVStat(), TVAcc::estimateWUbmWeight(), TVAcc::getRankT(), TVAcc::getUbmMeans(), TVAcc::getWeightedCov(), TVAcc::loadF_X(), TVAcc::loadMeanEstimate(), TVAcc::loadN(), TVAcc::loadT(), TVAcc::normStatistics(), TVAcc::normTMatrix(), TVAcc::saveAccs(), TVAcc::saveWbyFile(), and verbose.
Referenced by main().