LIA_RAL: LIA_SpkDet/IvNorm/src/IvNorm.cpp File Reference
IvNorm.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "IvNorm.h"
Macros
#define ALIZE_IvNorm_cpp
Functions
int IvNorm (Config &config)
Macro Definition Documentation
#define ALIZE_IvNorm_cpp
Definition at line 57 of file IvNorm.cpp.
Function Documentation
int IvNorm (Config & config)
Definition at line 72 of file IvNorm.cpp.
References PldaDev::computeLDA(), PldaTest::rotateLeft(), PldaTest::saveSegments(), PldaTest::saveVectors(), PldaDev::sphericalNuisanceNormalization(), PldaTest::sphericalNuisanceNormalization(), and verboseLevel.
Referenced by main().