LIA_RAL: LIA_SpkDet/IvNorm/include/IvNorm.h File Reference
IvNorm.h File Reference
#include "alize.h"
#include "liatools.h"
Functions
int IvNorm (Config &)
Function Documentation
int IvNorm (Config &)
Definition at line 72 of file IvNorm.cpp.
References PldaDev::computeLDA(), PldaTest::rotateLeft(), PldaTest::saveSegments(), PldaTest::saveVectors(), PldaDev::sphericalNuisanceNormalization(), PldaTest::sphericalNuisanceNormalization(), and verboseLevel.
Referenced by main().