LIA_RAL: LIA_SpkDet/IvTest/src/IvTest.cpp File Reference
IvTest.cpp File Reference
#include <iostream>
#include <fstream>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "IvTest.h"
#include <sys/stat.h>
Macros
#define ALIZE_IvTest_cpp
Functions
int IvTest (Config &config)
Macro Definition Documentation
#define ALIZE_IvTest_cpp
Definition at line 56 of file IvTest.cpp.
Function Documentation
int IvTest (Config & config)
Definition at line 73 of file IvTest.cpp.
References PldaDev::applySphericalNuisanceNormalization(), PldaModel::centerData(), PldaDev::computeCovMat(), PldaDev::computeLDA(), PldaDev::computeMahalanobis(), PldaDev::computeWccnChol(), PldaTest::cosineDistance(), CST_MAX_CLIENT_LINE, debug, PldaModel::em_iteration(), PldaModel::getDev(), PldaTest::getMaxEnrollmentSession(), PldaTest::getModelName(), PldaTest::getModelsNumber(), PldaTest::getScores(), PldaTest::getSegmentName(), PldaTest::getSegmentsNumber(), PldaTest::getTrials(), PldaTest::mahalanobisDistance(), outputResultLine(), PldaTest::pldaMeanScoring(), PldaTest::pldaNativeScoring(), PldaDev::rotateLeft(), PldaTest::rotateLeft(), PldaModel::saveModel(), setDecision(), PldaDev::sphericalNuisanceNormalization(), PldaTest::sphericalNuisanceNormalization(), PldaTest::twoCovScoring(), PldaModel::updateModel(), and verboseLevel.