LIA_RAL: LIA_Utils/LabelFusion/src/LabelFusion.cpp File Reference
LabelFusion.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "LabelFusion.h"
Macros
#define ALIZE_LabelFusion_cpp
Functions
void interSeg (SegCluster &clusterOne, SegCluster &clusterTwo, SegCluster &clusterOutput)
bool selFrame (double frm, double length, double threshold)
void morphologicalFilter (SegCluster &clusterIn, SegCluster &clusterOut, unsigned long winLength, double selectThreshold)
void morphologicalFilter (SegCluster &clusterIn, SegCluster &clusterOut, Config &config)
int labelFusion (Config &config)
int labelMorphing (Config &config)
Macro Definition Documentation
#define ALIZE_LabelFusion_cpp
Definition at line 56 of file LabelFusion.cpp.
Function Documentation
void interSeg (SegCluster & clusterOne, SegCluster & clusterTwo, SegCluster & clusterOutput)
Definition at line 73 of file LabelFusion.cpp.
References debug, endSeg(), and verbose.
Referenced by labelFusion().
int labelFusion (Config & config)
Definition at line 181 of file LabelFusion.cpp.
References debug, interSeg(), loadClusterFile(), morphologicalFilter(), outputLabelFile(), totalFrame(), and verbose.
int labelMorphing (Config & config)
Definition at line 248 of file LabelFusion.cpp.
References debug, loadClusterFile(), morphologicalFilter(), outputLabelFile(), totalFrame(), and verbose.
void morphologicalFilter (SegCluster & clusterIn, SegCluster & clusterOut, unsigned long winLength, double selectThreshold)
Definition at line 132 of file LabelFusion.cpp.
References debug, endSeg(), selFrame(), and verbose.
Referenced by labelFusion(), labelMorphing(), and morphologicalFilter().
void morphologicalFilter (SegCluster & clusterIn, SegCluster & clusterOut, Config & config)
Definition at line 174 of file LabelFusion.cpp.
References morphologicalFilter().
bool selFrame (double frm, double length, double threshold)
Definition at line 125 of file LabelFusion.cpp.
Referenced by morphologicalFilter().