LIA_RAL: LIA_Utils/LabelNGram/src/LabelNGram.cpp File Reference
LabelNGram.cpp File Reference
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "LabelNGram.h"
Macros
#define ALIZE_LabelNGram_cpp
Functions
bool isNGram (short int *sym, NGram &tabS, unsigned long &tag)
short int recognizeSymbol (unsigned long &idxFrame, unsigned long end, ULongVector &tabS)
void moveTab (unsigned long *begin, short int *sym, unsigned long *end, unsigned long order)
void computeLabelNGram (NGram &NG, SegCluster &cluster, SegCluster &clusterOut, ULongVector &tabS, unsigned long nbSym)
unsigned long loadSymbol (const String &filename, const String &type, ULongVector &ret, Config &config)
int labelNGram (Config &config)
Macro Definition Documentation
#define ALIZE_LabelNGram_cpp
Definition at line 56 of file LabelNGram.cpp.
Function Documentation
void computeLabelNGram (NGram & NG, SegCluster & cluster, SegCluster & clusterOut, ULongVector & tabS, unsigned long nbSym)
Definition at line 218 of file LabelNGram.cpp.
References debug, endSeg(), NGram::getOrder(), isNGram(), moveTab(), and recognizeSymbol().
Referenced by labelNGram().
bool isNGram (short int * sym, NGram & tabS, unsigned long & tag)
Definition at line 188 of file LabelNGram.cpp.
References NGram::getOrder(), NGram::getSize(), and NGram::getSymbol().
Referenced by computeLabelNGram().
int labelNGram (Config & config)
Definition at line 294 of file LabelNGram.cpp.
References computeLabelNGram(), debug, NGram::load(), loadClusterFile(), loadSymbol(), outputLabelFile(), and verbose.
unsigned long loadSymbol (const String & filename, const String & type, ULongVector & ret, Config & config)
Definition at line 272 of file LabelNGram.cpp.
References debug, and OOV.
Referenced by labelNGram().
void moveTab (unsigned long * begin, short int * sym, unsigned long * end, unsigned long order)
Definition at line 210 of file LabelNGram.cpp.
Referenced by computeLabelNGram().
short int recognizeSymbol (unsigned long & idxFrame, unsigned long end, ULongVector & tabS)
Definition at line 203 of file LabelNGram.cpp.
Referenced by computeLabelNGram().