LIA_RAL: LIA_Utils/Svm/src/libsvm.cpp File Reference
libsvm.cpp File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <float.h>
#include <string.h>
#include <stdarg.h>
#include "libsvm.h"
Classes
class Cache
struct Cache::head_t
class QMatrix
class Kernel
class Solver
struct Solver::SolutionInfo
class Solver_NU
class SVC_Q
class ONE_CLASS_Q
class SVR_Q
struct decision_function
Macros
#define INF HUGE_VAL
#define TAU 1e-12
#define Malloc(type, n) (type *)malloc((n)*sizeof(type))
Typedefs
typedef float Qfloat
typedef signed char schar
Functions
template<class T >
static T min (T x, T y)
template<class T >
static T max (T x, T y)
template<class T >
static void swap (T &x, T &y)
template<class S , class T >
static void clone (T *&dst, S *src, int n)
static double powi (double base, int times)
static void print_string_stdout (const char *s)
static void info (const char *fmt,...)
static void solve_c_svc (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si, double Cp, double Cn)
static void solve_nu_svc (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si)
static void solve_one_class (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si)
static void solve_epsilon_svr (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si)
static void solve_nu_svr (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si)
static decision_function svm_train_one (const svm_problem *prob, const svm_parameter *param, double Cp, double Cn)
static void sigmoid_train (int l, const double *dec_values, const double *labels, double &A, double &B)
static double sigmoid_predict (double decision_value, double A, double B)
static void multiclass_probability (int k, double **r, double *p)
static void svm_binary_svc_probability (const svm_problem *prob, const svm_parameter *param, double Cp, double Cn, double &probA, double &probB)
static double svm_svr_probability (const svm_problem *prob, const svm_parameter *param)
static void svm_group_classes (const svm_problem *prob, int *nr_class_ret, int **label_ret, int **start_ret, int **count_ret, int *perm)
svm_model * svm_train (const svm_problem *prob, const svm_parameter *param)
void svm_cross_validation (const svm_problem *prob, const svm_parameter *param, int nr_fold, double *target)
int svm_get_svm_type (const svm_model *model)
int svm_get_nr_class (const svm_model *model)
void svm_get_labels (const svm_model *model, int *label)
double svm_get_svr_probability (const svm_model *model)
double svm_predict_values (const svm_model *model, const svm_node *x, double *dec_values)
double svm_predict (const svm_model *model, const svm_node *x)
double svm_predict_probability (const svm_model *model, const svm_node *x, double *prob_estimates)
int svm_save_model (const char *model_file_name, const svm_model *model)
static char * readline (FILE *input)
svm_model * svm_load_model (const char *model_file_name)
void svm_free_model_content (svm_model *model_ptr)
void svm_free_and_destroy_model (svm_model **model_ptr_ptr)
void svm_destroy_model (svm_model *model_ptr)
void svm_destroy_param (svm_parameter *param)
const char * svm_check_parameter (const svm_problem *prob, const svm_parameter *param)
int svm_check_probability_model (const svm_model *model)
void svm_set_print_string_function (void(*print_func)(const char *))
Variables
int libsvm_version = LIBSVM_VERSION
static void(* svm_print_string)(const char *) = &print_string_stdout
static const char * svm_type_table []
static const char * kernel_type_table []
static char * line = NULL
static int max_line_len
Macro Definition Documentation
#define INF HUGE_VAL
Definition at line 37 of file libsvm.cpp.
Referenced by Solver::calculate_rho(), Solver_NU::calculate_rho(), Solver::do_shrinking(), Solver_NU::do_shrinking(), Solver::select_working_set(), and Solver_NU::select_working_set().
#define Malloc (type, n) (type *)malloc((n)*sizeof(type))
Definition at line 39 of file libsvm.cpp.
Referenced by multiclass_probability(), sigmoid_train(), svm_binary_svc_probability(), svm_check_parameter(), svm_cross_validation(), svm_group_classes(), svm_load_model(), svm_predict(), svm_predict_probability(), svm_predict_values(), svm_svr_probability(), svm_train(), and svm_train_one().
#define TAU 1e-12
Definition at line 38 of file libsvm.cpp.
Referenced by Solver::select_working_set(), Solver_NU::select_working_set(), and Solver::Solve().
Typedef Documentation
typedef float Qfloat
Definition at line 12 of file libsvm.cpp.
typedef signed char schar
Definition at line 13 of file libsvm.cpp.
Function Documentation
template<class S , class T > static void clone (T *& dst, S * src, int n) inline static
Definition at line 21 of file libsvm.cpp.
Referenced by Kernel::Kernel(), Solver::Solve(), and SVC_Q::SVC_Q().
static void info (const char * fmt, ...) static
Definition at line 48 of file libsvm.cpp.
Referenced by Eigen::SuperLU< _MatrixType >::_solve(), Solver::do_shrinking(), Eigen::SuperLU< _MatrixType >::factorize(), multiclass_probability(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::internal::parallelize_gemm(), Solver::reconstruct_gradient(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), sigmoid_train(), Solver::Solve(), solve_c_svc(), solve_epsilon_svr(), solve_nu_svc(), solve_nu_svr(), svm_svr_probability(), svm_train(), and svm_train_one().
template<class T > static T max (T x, T y) inline static
Definition at line 18 of file libsvm.cpp.
References Eigen::internal::y.
Referenced by Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::assign(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::assignGeneric(), Eigen::internal::llt_inplace< Scalar, Lower >::blocked(), Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::blocked_lu(), Eigen::MatrixBase< Derived >::blueNorm(), Cache::Cache(), Solver::calculate_rho(), Solver_NU::calculate_rho(), cohortMaxLikelihood(), Eigen::SVD< MatrixType >::compute(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute(), computeNAPChannelEffect(), Eigen::RealSchur< _MatrixType >::computeNormOfT(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Solver_NU::do_shrinking(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), Eigen::internal::solve_retval< LDLT< _MatrixType, _UpLo >, Rhs >::evalTo(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), main(), Eigen::aligned_allocator< T >::max_size(), multiclass_probability(), Eigen::internal::scalar_max_op< Scalar >::operator()(), Eigen::internal::scalar_hypot_op< Scalar >::operator()(), Eigen::AngleAxis< Scalar >::operator=(), Eigen::internal::permute_symm_to_symm(), Eigen::internal::pmax(), Eigen::internal::queryTopLevelCacheSize(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run(), Eigen::internal::hypot_impl< Scalar >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Solver_NU::select_working_set(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), Eigen::AlignedBox< _Scalar, _AmbientDim >::setNull(), Eigen::internal::stable_norm_kernel(), and svm_predict_probability().
template<class T > static T min (T x, T y) inline static
Definition at line 15 of file libsvm.cpp.
References Eigen::internal::y.
Referenced by Eigen::JacobiSVD< MatrixType, QRPreconditioner >::allocate(), Eigen::internal::llt_inplace< Scalar, Lower >::blocked(), Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::blocked_lu(), Eigen::MatrixBase< Derived >::blueNorm(), Solver::calculate_rho(), Solver_NU::calculate_rho(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::col(), Eigen::SVD< MatrixType >::compute(), Eigen::HouseholderQR< MatrixType >::compute(), Eigen::FullPivHouseholderQR< MatrixType >::compute(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonalLength(), Eigen::MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::diagonalSize(), Eigen::internal::solve_retval< HouseholderQR< _MatrixType >, Rhs >::evalTo(), Eigen::internal::solve_retval< FullPivHouseholderQR< _MatrixType >, Rhs >::evalTo(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType >::evalTo(), Eigen::internal::solve_retval< FullPivLU< _MatrixType >, Rhs >::evalTo(), Eigen::internal::solve_retval< JacobiSVD< _MatrixType, QRPreconditioner >, Rhs >::evalTo(), Eigen::UmfPackLU< _MatrixType >::extractData(), Eigen::IncompleteLUT< _Scalar >::factorize(), Eigen::internal::generic_aligned_realloc(), Eigen::internal::householder_qr_inplace_blocked(), Eigen::internal::householder_qr_inplace_unblocked(), Eigen::SparseMatrix< Scalar, RowMajor >::insertCompressed(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::isApprox(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, true, false >::isApprox(), Eigen::MatrixBase< Derived >::isLowerTriangular(), Eigen::MatrixBase< Derived >::isUpperTriangular(), main(), Eigen::internal::symm_pack_rhs< Scalar, Index, nr, StorageOrder >::operator()(), Eigen::internal::scalar_min_op< Scalar >::operator()(), Eigen::internal::scalar_hypot_op< Scalar >::operator()(), Eigen::AngleAxis< Scalar >::operator=(), Eigen::RealSchur< _MatrixType >::performFrancisQRStep(), Eigen::internal::permute_symm_to_symm(), Eigen::internal::pmin(), Eigen::internal::CompressedStorage< Scalar, Index >::reallocate(), Eigen::internal::AmbiVector< _Scalar, _Index >::reallocateSparse(), Eigen::FullPivLU< MatrixType >::reconstructedMatrix(), Eigen::ComplexSchur< _MatrixType >::reduceToTriangularForm(), Eigen::Diagonal< MatrixType, DiagIndex >::rows(), Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, ColMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, ColMajor >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >::run(), Eigen::internal::hypot_impl< Scalar >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2, Upper, Dynamic, ClearOpposite >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2, Lower, Dynamic, ClearOpposite >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2, StrictlyUpper, Dynamic, ClearOpposite >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2, StrictlyLower, Dynamic, ClearOpposite >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2, UnitUpper, Dynamic, ClearOpposite >::run(), Eigen::internal::triangular_assignment_selector< Derived1, Derived2, UnitLower, Dynamic, ClearOpposite >::run(), Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run(), Eigen::internal::setIdentity_impl< Derived, true >::run(), Eigen::TriangularProduct< Mode, LhsIsTriangular, Lhs, false, Rhs, false >::scaleAndAddTo(), Solver::Solve(), solve_nu_svc(), solve_nu_svr(), Eigen::MatrixBase< Derived >::stableNorm(), svm_check_parameter(), svm_predict_probability(), and Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::unblocked_lu().
static void multiclass_probability (int k, double ** r, double * p) static
Definition at line 1815 of file libsvm.cpp.
References eps, info(), Malloc, and max().
Referenced by svm_predict_probability().
static double powi (double base, int times) inline static
Definition at line 26 of file libsvm.cpp.
Referenced by Kernel::k_function(), and Kernel::kernel_poly().
static void print_string_stdout (const char * s) static
Definition at line 41 of file libsvm.cpp.
Referenced by svm_set_print_string_function().
static char* readline (FILE * input) static
Definition at line 2672 of file libsvm.cpp.
References line, and max_line_len.
Referenced by svm_load_model().
static double sigmoid_predict (double decision_value, double A, double B) static
Definition at line 1805 of file libsvm.cpp.
References exp().
Referenced by svm_predict_probability().
static void sigmoid_train (int l, const double * dec_values, const double * labels, double & A, double & B) static
Definition at line 1692 of file libsvm.cpp.
References eps, exp(), info(), log(), and Malloc.
Referenced by svm_binary_svc_probability().
static void solve_c_svc (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si, double Cp, double Cn) static
Definition at line 1427 of file libsvm.cpp.
References svm_parameter::eps, info(), svm_problem::l, svm_parameter::shrinking, Solver::Solve(), svm_problem::y, and Eigen::internal::y.
Referenced by svm_train_one().
static void solve_epsilon_svr (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si) static
Definition at line 1549 of file libsvm.cpp.
References svm_parameter::C, svm_parameter::eps, info(), svm_problem::l, svm_parameter::p, svm_parameter::shrinking, Solver::Solve(), svm_problem::y, and Eigen::internal::y.
Referenced by svm_train_one().
static void solve_nu_svc (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si) static
Definition at line 1462 of file libsvm.cpp.
References svm_parameter::eps, info(), svm_problem::l, min(), svm_parameter::nu, Solver::SolutionInfo::obj, Solver::SolutionInfo::r, Solver::SolutionInfo::rho, svm_parameter::shrinking, Solver_NU::Solve(), Solver::SolutionInfo::upper_bound_n, Solver::SolutionInfo::upper_bound_p, svm_problem::y, and Eigen::internal::y.
Referenced by svm_train_one().
static void solve_nu_svr (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si) static
Definition at line 1587 of file libsvm.cpp.
References svm_parameter::C, svm_parameter::eps, info(), svm_problem::l, min(), svm_parameter::nu, Solver::SolutionInfo::r, svm_parameter::shrinking, Solver_NU::Solve(), svm_problem::y, and Eigen::internal::y.
Referenced by svm_train_one().
static void solve_one_class (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si) static
Definition at line 1517 of file libsvm.cpp.
References svm_parameter::eps, svm_problem::l, svm_parameter::nu, svm_parameter::shrinking, and Solver::Solve().
Referenced by svm_train_one().
static void svm_binary_svc_probability (const svm_problem * prob, const svm_parameter * param, double Cp, double Cn, double & probA, double & probB) static
Definition at line 1879 of file libsvm.cpp.
References svm_parameter::C, svm_problem::l, svm_model::label, Malloc, svm_parameter::nr_weight, svm_parameter::probability, sigmoid_train(), svm_destroy_param(), svm_free_and_destroy_model(), svm_predict_values(), svm_train(), swap(), svm_parameter::weight, svm_parameter::weight_label, svm_problem::x, and svm_problem::y.
Referenced by svm_train().
const char* svm_check_parameter (const svm_problem * prob, const svm_parameter * param)
Definition at line 2927 of file libsvm.cpp.
References svm_parameter::C, C_SVC, svm_parameter::cache_size, svm_parameter::degree, svm_parameter::eps, EPSILON_SVR, svm_parameter::gamma, svm_parameter::kernel_type, svm_problem::l, svm_model::l, svm_model::label, LINEAR, Malloc, min(), svm_model::nr_class, svm_parameter::nu, NU_SVC, NU_SVR, ONE_CLASS, svm_parameter::p, POLY, PRECOMPUTED, svm_parameter::probability, RBF, svm_parameter::shrinking, SIGMOID, svm_parameter::svm_type, and svm_problem::y.
int svm_check_probability_model (const svm_model * model)
Definition at line 3048 of file libsvm.cpp.
References C_SVC, EPSILON_SVR, NU_SVC, NU_SVR, svm_model::param, svm_model::probA, svm_model::probB, and svm_parameter::svm_type.
void svm_cross_validation (const svm_problem * prob, const svm_parameter * param, int nr_fold, double * target)
Definition at line 2297 of file libsvm.cpp.
References C_SVC, svm_problem::l, svm_model::l, svm_model::label, Malloc, svm_model::nr_class, NU_SVC, svm_parameter::probability, svm_free_and_destroy_model(), svm_get_nr_class(), svm_group_classes(), svm_predict(), svm_predict_probability(), svm_train(), svm_parameter::svm_type, swap(), svm_problem::x, and svm_problem::y.
Referenced by svm_svr_probability().
void svm_destroy_model (svm_model * model_ptr)
Definition at line 2915 of file libsvm.cpp.
References svm_free_and_destroy_model().
Referenced by svmTrain().
void svm_destroy_param (svm_parameter * param)
Definition at line 2921 of file libsvm.cpp.
References svm_parameter::weight, and svm_parameter::weight_label.
Referenced by svm_binary_svc_probability(), and svmTrain().
void svm_free_and_destroy_model (svm_model ** model_ptr_ptr)
Definition at line 2905 of file libsvm.cpp.
References svm_free_model_content().
Referenced by svm_binary_svc_probability(), svm_cross_validation(), and svm_destroy_model().
void svm_free_model_content (svm_model * model_ptr)
Definition at line 2890 of file libsvm.cpp.
References svm_model::free_sv, svm_model::l, svm_model::label, svm_model::nr_class, svm_model::nSV, svm_model::probA, svm_model::probB, svm_model::rho, svm_model::SV, and svm_model::sv_coef.
Referenced by svm_free_and_destroy_model().
void svm_get_labels (const svm_model * model, int * label)
Definition at line 2423 of file libsvm.cpp.
References svm_model::label, and svm_model::nr_class.
int svm_get_nr_class (const svm_model * model)
Definition at line 2418 of file libsvm.cpp.
References svm_model::nr_class.
Referenced by svm_cross_validation().
int svm_get_svm_type (const svm_model * model)
Definition at line 2413 of file libsvm.cpp.
References svm_model::param, and svm_parameter::svm_type.
double svm_get_svr_probability (const svm_model * model)
Definition at line 2430 of file libsvm.cpp.
References EPSILON_SVR, NU_SVR, svm_model::param, svm_model::probA, and svm_parameter::svm_type.
static void svm_group_classes (const svm_problem * prob, int * nr_class_ret, int ** label_ret, int ** start_ret, int ** count_ret, int * perm) static
Definition at line 2000 of file libsvm.cpp.
References svm_problem::l, svm_model::l, svm_model::label, Malloc, svm_model::nr_class, and svm_problem::y.
Referenced by svm_cross_validation(), and svm_train().
svm_model* svm_load_model (const char * model_file_name)
Definition at line 2690 of file libsvm.cpp.
References svm_parameter::coef0, svm_parameter::degree, svm_model::free_sv, svm_parameter::gamma, svm_node::index, svm_parameter::kernel_type, kernel_type_table, svm_model::l, svm_model::label, line, Malloc, max_line_len, svm_model::nr_class, svm_model::nSV, svm_model::param, svm_model::probA, svm_model::probB, readline(), svm_model::rho, svm_model::SV, svm_model::sv_coef, svm_parameter::svm_type, svm_type_table, and svm_node::value.
double svm_predict (const svm_model * model, const svm_node * x)
Definition at line 2518 of file libsvm.cpp.
References EPSILON_SVR, Malloc, svm_model::nr_class, NU_SVR, ONE_CLASS, svm_model::param, svm_predict_values(), and svm_parameter::svm_type.
Referenced by svm_cross_validation(), and svm_predict_probability().
double svm_predict_probability (const svm_model * model, const svm_node * x, double * prob_estimates)
Definition at line 2533 of file libsvm.cpp.
References C_SVC, svm_model::label, Malloc, max(), min(), multiclass_probability(), svm_model::nr_class, NU_SVC, svm_model::param, svm_model::probA, svm_model::probB, sigmoid_predict(), svm_predict(), svm_predict_values(), and svm_parameter::svm_type.
Referenced by svm_cross_validation().
double svm_predict_values (const svm_model * model, const svm_node * x, double * dec_values)
Definition at line 2442 of file libsvm.cpp.
References EPSILON_SVR, Kernel::k_function(), svm_model::l, svm_model::label, Malloc, svm_model::nr_class, svm_model::nSV, NU_SVR, ONE_CLASS, svm_model::param, svm_model::rho, svm_model::SV, svm_model::sv_coef, and svm_parameter::svm_type.
Referenced by svm_binary_svc_probability(), svm_predict(), and svm_predict_probability().
int svm_save_model (const char * model_file_name, const svm_model * model)
Definition at line 2582 of file libsvm.cpp.
References svm_parameter::coef0, svm_parameter::degree, svm_parameter::gamma, svm_node::index, svm_parameter::kernel_type, kernel_type_table, svm_model::l, svm_model::label, svm_model::nr_class, svm_model::nSV, svm_model::param, POLY, PRECOMPUTED, svm_model::probA, svm_model::probB, RBF, svm_model::rho, SIGMOID, svm_model::SV, svm_model::sv_coef, svm_parameter::svm_type, svm_type_table, and svm_node::value.
void svm_set_print_string_function (void(*)(const char *) print_func)
Definition at line 3056 of file libsvm.cpp.
References print_string_stdout(), and svm_print_string.
static double svm_svr_probability (const svm_problem * prob, const svm_parameter * param) static
Definition at line 1966 of file libsvm.cpp.
References info(), svm_problem::l, Malloc, svm_model::param, svm_parameter::probability, sqrt(), svm_cross_validation(), and svm_problem::y.
Referenced by svm_train().
svm_model* svm_train (const svm_problem * prob, const svm_parameter * param)
Definition at line 2060 of file libsvm.cpp.
References decision_function::alpha, svm_parameter::C, EPSILON_SVR, svm_model::free_sv, info(), svm_problem::l, svm_model::l, svm_model::label, Malloc, svm_model::nr_class, svm_model::nSV, NU_SVR, ONE_CLASS, svm_model::param, svm_model::probA, svm_parameter::probability, svm_model::probB, svm_model::rho, decision_function::rho, svm_model::SV, svm_model::sv_coef, svm_binary_svc_probability(), svm_group_classes(), svm_svr_probability(), svm_train_one(), svm_parameter::svm_type, svm_parameter::weight, svm_parameter::weight_label, svm_problem::x, and svm_problem::y.
Referenced by svm_binary_svc_probability(), and svm_cross_validation().
static decision_function svm_train_one (const svm_problem * prob, const svm_parameter * param, double Cp, double Cn) static
Definition at line 1634 of file libsvm.cpp.
References decision_function::alpha, C_SVC, EPSILON_SVR, info(), svm_problem::l, Malloc, NU_SVC, NU_SVR, Solver::SolutionInfo::obj, ONE_CLASS, Solver::SolutionInfo::rho, decision_function::rho, solve_c_svc(), solve_epsilon_svr(), solve_nu_svc(), solve_nu_svr(), solve_one_class(), svm_parameter::svm_type, Solver::SolutionInfo::upper_bound_n, Solver::SolutionInfo::upper_bound_p, and svm_problem::y.
Referenced by svm_train().
template<class T > static void swap (T & x, T & y) inline static
Definition at line 20 of file libsvm.cpp.
References Eigen::internal::y.
Referenced by Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), Eigen::ColPivHouseholderQR< MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots(), Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo(), Eigen::IncompleteLUT< _Scalar >::factorize(), Cache::get_data(), Eigen::internal::parallelize_gemm(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), Eigen::IncompleteLUT< _Scalar >::QuickSplit(), Eigen::SparseMatrix< Scalar, RowMajor >::reserveInnerVectors(), Eigen::internal::inplace_transpose_selector< MatrixType, true >::run(), Eigen::SVD< MatrixType >::sort(), Eigen::ComplexEigenSolver< _MatrixType >::sortEigenvalues(), svm_binary_svc_probability(), svm_cross_validation(), Eigen::internal::CompressedStorage< Scalar, Index >::swap(), Eigen::DenseStorage< Scalar, Base::MaxSizeAtCompileTime, Base::RowsAtCompileTime, Base::ColsAtCompileTime, Options >::swap(), Eigen::DenseStorage< T, Size, Dynamic, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Size, Dynamic, _Cols, _Options >::swap(), Eigen::DenseStorage< T, Size, _Rows, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, Dynamic, _Options >::swap(), Eigen::SparseVector< _Scalar, _Flags, _Index >::swap(), Eigen::DenseStorage< T, Dynamic, _Rows, Dynamic, _Options >::swap(), Eigen::DenseStorage< T, Dynamic, Dynamic, _Cols, _Options >::swap(), Eigen::SparseMatrix< Scalar, RowMajor >::swap(), Cache::swap_index(), Kernel::swap_index(), Solver::swap_index(), SVC_Q::swap_index(), ONE_CLASS_Q::swap_index(), SVR_Q::swap_index(), and Eigen::internal::ldlt_inplace< Lower >::unblocked().
Variable Documentation
const char* kernel_type_table[] static
Initial value:
=
{
        "linear","polynomial","rbf","sigmoid","precomputed",NULL
}
Definition at line 2577 of file libsvm.cpp.
Referenced by svm_load_model(), and svm_save_model().
int libsvm_version = LIBSVM_VERSION
Definition at line 11 of file libsvm.cpp.
char* line = NULL static
Definition at line 2669 of file libsvm.cpp.
Referenced by computeAdaptedTnorm(), computeAndStoreZnormParam(), computeLLRmatrix(), learnEMimpostorModels(), learnMAPimpostorModels(), loadTnormParam(), Oracle(), readline(), searchLLRFromResFile(), selectNearestTarModel(), svdLoadSparseTextHBFile(), and svm_load_model().
int max_line_len static
Definition at line 2670 of file libsvm.cpp.
Referenced by readline(), and svm_load_model().
void(* svm_print_string)(const char *) = &print_string_stdout static
Definition at line 46 of file libsvm.cpp.
Referenced by svm_set_print_string_function().
const char* svm_type_table[] static
Initial value:
=
{
        "c_svc","nu_svc","one_class","epsilon_svr","nu_svr",NULL
}
Definition at line 2572 of file libsvm.cpp.
Referenced by svm_load_model(), and svm_save_model().