LIA_RAL: LIA_SpkDet/CovIntra/src/SVDLIBC/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <strings.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/resource.h>
#include "svdlib.h"
Enumerations
enum algorithms { LAS2 }
Functions
float timer (void)
static long imin (long a, long b)
static void debug (char *fmt,...)
static void fatalError (char *fmt,...)
void printUsage (char *progname)
int main (int argc, char *argv[])
Enumeration Type Documentation
enum algorithms
Enumerator
LAS2
Definition at line 10 of file main.c.
Function Documentation
static void debug (char * fmt, ...) static
Definition at line 33 of file main.c.
Referenced by printUsage().
static void fatalError (char * fmt, ...) static
Definition at line 40 of file main.c.
Referenced by main().
static long imin (long a, long b) static
Definition at line 31 of file main.c.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 77 of file main.c.
References smat::cols, svdrec::d, FALSE, fatalError(), imin(), LAS2, printUsage(), smat::rows, svdrec::S, SVD_F_DB, SVD_F_DT, SVD_F_SB, SVD_F_ST, SVD_F_STH, SVD_IS_SPARSE, SVD_MXV, SVDCount, svdFreeSMat(), svdLAS2(), svdLoadDenseMatrix(), svdLoadSparseMatrix(), svdTransposeD(), svdTransposeS(), SVDVerbosity, svdWriteDenseArray(), svdWriteDenseMatrix(), svdWriteSparseMatrix(), timer(), TRUE, svdrec::Ut, and svdrec::Vt.
void printUsage (char * progname)
Definition at line 50 of file main.c.
References debug(), and SVDVersion.
Referenced by main().
float timer (void)
Definition at line 18 of file main.c.
Referenced by main().