LIA_RAL: Eigen::internal Namespace Reference
Eigen::internal Namespace Reference
Classes
struct LDLT_Traits
struct ldlt_inplace
struct ldlt_inplace< Lower >
struct ldlt_inplace< Upper >
struct LDLT_Traits< MatrixType, Lower >
struct LDLT_Traits< MatrixType, Upper >
struct solve_retval< LDLT< _MatrixType, _UpLo >, Rhs >
struct LLT_Traits
struct llt_inplace
struct llt_inplace< Scalar, Lower >
struct llt_inplace< Scalar, Upper >
struct LLT_Traits< MatrixType, Lower >
struct LLT_Traits< MatrixType, Upper >
struct solve_retval< LLT< _MatrixType, UpLo >, Rhs >
struct mkl_llt
struct solve_retval< CholmodBase< _MatrixType, _UpLo, Derived >, Rhs >
struct sparse_solve_retval< CholmodBase< _MatrixType, _UpLo, Derived >, Rhs >
struct Packet2cf
struct packet_traits< std::complex< float > >
struct unpacket_traits< Packet2cf >
struct palign_impl< Offset, Packet2cf >
struct conj_helper< Packet2cf, Packet2cf, false, true >
struct conj_helper< Packet2cf, Packet2cf, true, false >
struct conj_helper< Packet2cf, Packet2cf, true, true >
struct packet_traits< float >
struct packet_traits< int >
struct unpacket_traits< Packet4f >
struct unpacket_traits< Packet4i >
struct palign_impl< Offset, Packet4f >
struct palign_impl< Offset, Packet4i >
struct conj_helper< Packet4f, Packet2cf, false, false >
struct conj_helper< Packet2cf, Packet4f, false, false >
struct Packet1cd
struct packet_traits< std::complex< double > >
struct unpacket_traits< Packet1cd >
struct palign_impl< Offset, Packet1cd >
struct conj_helper< Packet1cd, Packet1cd, false, true >
struct conj_helper< Packet1cd, Packet1cd, true, false >
struct conj_helper< Packet1cd, Packet1cd, true, true >
struct conj_helper< Packet2d, Packet1cd, false, false >
struct conj_helper< Packet1cd, Packet2d, false, false >
struct is_arithmetic< __m128 >
struct is_arithmetic< __m128i >
struct is_arithmetic< __m128d >
struct packet_traits< double >
struct unpacket_traits< Packet2d >
struct palign_impl< Offset, Packet2d >
struct traits< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >
struct traits< ArrayWrapper< ExpressionType > >
struct traits< MatrixWrapper< ExpressionType > >
struct assign_traits
struct assign_DefaultTraversal_CompleteUnrolling
struct assign_DefaultTraversal_CompleteUnrolling< Derived1, Derived2, Stop, Stop >
struct assign_DefaultTraversal_InnerUnrolling
struct assign_DefaultTraversal_InnerUnrolling< Derived1, Derived2, Stop, Stop >
struct assign_LinearTraversal_CompleteUnrolling
struct assign_LinearTraversal_CompleteUnrolling< Derived1, Derived2, Stop, Stop >
struct assign_innervec_CompleteUnrolling
struct assign_innervec_CompleteUnrolling< Derived1, Derived2, Stop, Stop >
struct assign_innervec_InnerUnrolling
struct assign_innervec_InnerUnrolling< Derived1, Derived2, Stop, Stop >
struct assign_impl
struct assign_impl< Derived1, Derived2, InvalidTraversal, Unrolling, Version >
struct assign_impl< Derived1, Derived2, DefaultTraversal, NoUnrolling, Version >
struct assign_impl< Derived1, Derived2, DefaultTraversal, CompleteUnrolling, Version >
struct assign_impl< Derived1, Derived2, DefaultTraversal, InnerUnrolling, Version >
struct assign_impl< Derived1, Derived2, LinearTraversal, NoUnrolling, Version >
struct assign_impl< Derived1, Derived2, LinearTraversal, CompleteUnrolling, Version >
struct assign_impl< Derived1, Derived2, InnerVectorizedTraversal, NoUnrolling, Version >
struct assign_impl< Derived1, Derived2, InnerVectorizedTraversal, CompleteUnrolling, Version >
struct assign_impl< Derived1, Derived2, InnerVectorizedTraversal, InnerUnrolling, Version >
struct unaligned_assign_impl
struct unaligned_assign_impl< false >
struct assign_impl< Derived1, Derived2, LinearVectorizedTraversal, NoUnrolling, Version >
struct assign_impl< Derived1, Derived2, LinearVectorizedTraversal, CompleteUnrolling, Version >
struct assign_impl< Derived1, Derived2, SliceVectorizedTraversal, NoUnrolling, Version >
struct assign_selector
struct assign_selector< Derived, OtherDerived, false, false >
struct assign_selector< Derived, OtherDerived, true, false >
struct assign_selector< Derived, OtherDerived, false, true >
struct assign_selector< Derived, OtherDerived, true, true >
struct vml_call
class vml_assign_traits
struct vml_assign_impl
struct vml_assign_impl< Derived1, Derived2, UnaryOp, Traversal, Unrolling, InnerVectorizedTraversal >
struct vml_assign_impl< Derived1, Derived2, UnaryOp, Traversal, Unrolling, LinearVectorizedTraversal >
class BandMatrixBase
struct traits< BandMatrix< _Scalar, _Rows, _Cols, _Supers, _Subs, _Options > >
class BandMatrix
Represents a rectangular matrix with a banded storage.
class BandMatrixWrapper
struct traits< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >
class TridiagonalMatrix
Represents a tridiagonal matrix with a compact banded storage.
struct traits< Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess > >
struct all_unroller
struct all_unroller< Derived, 1 >
struct all_unroller< Derived, Dynamic >
struct any_unroller
struct any_unroller< Derived, 1 >
struct any_unroller< Derived, Dynamic >
struct traits< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >
struct traits< CwiseNullaryOp< NullaryOp, PlainObjectType > >
struct setIdentity_impl
struct setIdentity_impl< Derived, true >
struct traits< CwiseUnaryOp< UnaryOp, XprType > >
struct traits< CwiseUnaryView< ViewOp, MatrixType > >
struct add_const_on_value_type_if_arithmetic
struct first_aligned_impl
struct first_aligned_impl< Derived, false >
struct inner_stride_at_compile_time
struct inner_stride_at_compile_time< Derived, false >
struct outer_stride_at_compile_time
struct outer_stride_at_compile_time< Derived, false >
struct constructor_without_unaligned_array_assert
struct plain_array
struct plain_array< T, Size, MatrixOrArrayOptions, 16 >
struct plain_array< T, 0, MatrixOrArrayOptions, Alignment >
struct traits< Diagonal< MatrixType, DiagIndex > >
struct traits< DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > >
struct traits< DiagonalWrapper< _DiagonalVectorType > >
struct traits< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >
struct dot_nocheck
struct dot_nocheck< T, U, true >
struct lpNorm_selector
struct lpNorm_selector< Derived, 1 >
struct lpNorm_selector< Derived, 2 >
struct lpNorm_selector< Derived, Infinity >
struct traits< Flagged< ExpressionType, Added, Removed > >
struct traits< ForceAlignedAccess< ExpressionType > >
struct scalar_sum_op
struct functor_traits< scalar_sum_op< Scalar > >
struct scalar_product_op
struct functor_traits< scalar_product_op< LhsScalar, RhsScalar > >
struct scalar_conj_product_op
struct functor_traits< scalar_conj_product_op< LhsScalar, RhsScalar > >
struct scalar_min_op
struct functor_traits< scalar_min_op< Scalar > >
struct scalar_max_op
struct functor_traits< scalar_max_op< Scalar > >
struct scalar_hypot_op
struct functor_traits< scalar_hypot_op< Scalar > >
struct scalar_binary_pow_op
struct functor_traits< scalar_binary_pow_op< Scalar, OtherScalar > >
struct scalar_difference_op
struct functor_traits< scalar_difference_op< Scalar > >
struct scalar_quotient_op
struct functor_traits< scalar_quotient_op< Scalar > >
struct scalar_boolean_and_op
struct functor_traits< scalar_boolean_and_op >
struct scalar_boolean_or_op
struct functor_traits< scalar_boolean_or_op >
struct scalar_opposite_op
struct functor_traits< scalar_opposite_op< Scalar > >
struct scalar_abs_op
struct functor_traits< scalar_abs_op< Scalar > >
struct scalar_abs2_op
struct functor_traits< scalar_abs2_op< Scalar > >
struct scalar_conjugate_op
struct functor_traits< scalar_conjugate_op< Scalar > >
struct scalar_cast_op
struct functor_traits< scalar_cast_op< Scalar, NewType > >
struct scalar_real_op
struct functor_traits< scalar_real_op< Scalar > >
struct scalar_imag_op
struct functor_traits< scalar_imag_op< Scalar > >
struct scalar_real_ref_op
struct functor_traits< scalar_real_ref_op< Scalar > >
struct scalar_imag_ref_op
struct functor_traits< scalar_imag_ref_op< Scalar > >
struct scalar_exp_op
struct functor_traits< scalar_exp_op< Scalar > >
struct scalar_log_op
struct functor_traits< scalar_log_op< Scalar > >
struct scalar_multiple_op
struct functor_traits< scalar_multiple_op< Scalar > >
struct scalar_multiple2_op
struct functor_traits< scalar_multiple2_op< Scalar1, Scalar2 > >
struct scalar_quotient1_op
struct functor_traits< scalar_quotient1_op< Scalar > >
struct scalar_constant_op
struct functor_traits< scalar_constant_op< Scalar > >
struct scalar_identity_op
struct functor_traits< scalar_identity_op< Scalar > >
struct linspaced_op_impl
struct linspaced_op_impl< Scalar, false >
struct linspaced_op_impl< Scalar, true >
struct linspaced_op
struct functor_traits< linspaced_op< Scalar, RandomAccess > >
struct functor_has_linear_access
struct functor_has_linear_access< scalar_identity_op< Scalar > >
struct functor_allows_mixing_real_and_complex
struct functor_allows_mixing_real_and_complex< scalar_product_op< LhsScalar, RhsScalar > >
struct functor_allows_mixing_real_and_complex< scalar_conj_product_op< LhsScalar, RhsScalar > >
struct scalar_add_op
struct functor_traits< scalar_add_op< Scalar > >
struct scalar_sqrt_op
struct functor_traits< scalar_sqrt_op< Scalar > >
struct scalar_cos_op
struct functor_traits< scalar_cos_op< Scalar > >
struct scalar_sin_op
struct functor_traits< scalar_sin_op< Scalar > >
struct scalar_tan_op
struct functor_traits< scalar_tan_op< Scalar > >
struct scalar_acos_op
struct functor_traits< scalar_acos_op< Scalar > >
struct scalar_asin_op
struct functor_traits< scalar_asin_op< Scalar > >
struct scalar_pow_op
struct functor_traits< scalar_pow_op< Scalar > >
struct scalar_inverse_mult_op
struct scalar_inverse_op
struct functor_traits< scalar_inverse_op< Scalar > >
struct scalar_square_op
struct functor_traits< scalar_square_op< Scalar > >
struct scalar_cube_op
struct functor_traits< scalar_cube_op< Scalar > >
struct functor_traits< std::multiplies< T > >
struct functor_traits< std::divides< T > >
struct functor_traits< std::plus< T > >
struct functor_traits< std::minus< T > >
struct functor_traits< std::negate< T > >
struct functor_traits< std::logical_or< T > >
struct functor_traits< std::logical_and< T > >
struct functor_traits< std::logical_not< T > >
struct functor_traits< std::greater< T > >
struct functor_traits< std::less< T > >
struct functor_traits< std::greater_equal< T > >
struct functor_traits< std::less_equal< T > >
struct functor_traits< std::equal_to< T > >
struct functor_traits< std::not_equal_to< T > >
struct functor_traits< std::binder2nd< T > >
struct functor_traits< std::binder1st< T > >
struct functor_traits< std::unary_negate< T > >
struct functor_traits< std::binary_negate< T > >
struct isApprox_selector
struct isApprox_selector< Derived, OtherDerived, true >
struct isMuchSmallerThan_object_selector
struct isMuchSmallerThan_object_selector< Derived, OtherDerived, true >
struct isMuchSmallerThan_scalar_selector
struct isMuchSmallerThan_scalar_selector< Derived, true >
struct product_type_selector
struct product_size_category
struct product_type
struct product_type_selector< M, N, 1 >
struct product_type_selector< 1, 1, Depth >
struct product_type_selector< 1, 1, 1 >
struct product_type_selector< Small, 1, Small >
struct product_type_selector< 1, Small, Small >
struct product_type_selector< Small, Small, Small >
struct product_type_selector< Small, Small, 1 >
struct product_type_selector< Small, Large, 1 >
struct product_type_selector< Large, Small, 1 >
struct product_type_selector< 1, Large, Small >
struct product_type_selector< 1, Large, Large >
struct product_type_selector< 1, Small, Large >
struct product_type_selector< Large, 1, Small >
struct product_type_selector< Large, 1, Large >
struct product_type_selector< Small, 1, Large >
struct product_type_selector< Small, Small, Large >
struct product_type_selector< Large, Small, Large >
struct product_type_selector< Small, Large, Large >
struct product_type_selector< Large, Large, Large >
struct product_type_selector< Large, Small, Small >
struct product_type_selector< Small, Large, Small >
struct product_type_selector< Large, Large, Small >
struct traits< GeneralProduct< Lhs, Rhs, InnerProduct > >
struct outer_product_selector
struct traits< GeneralProduct< Lhs, Rhs, OuterProduct > >
struct outer_product_selector< ColMajor >
struct outer_product_selector< RowMajor >
struct traits< GeneralProduct< Lhs, Rhs, GemvProduct > >
struct gemv_selector
struct gemv_selector< OnTheLeft, StorageOrder, BlasCompatible >
struct gemv_static_vector_if
struct gemv_static_vector_if< Scalar, Size, MaxSize, false >
struct gemv_static_vector_if< Scalar, Size, Dynamic, true >
struct gemv_static_vector_if< Scalar, Size, MaxSize, true >
struct gemv_selector< OnTheRight, ColMajor, true >
struct gemv_selector< OnTheRight, RowMajor, true >
struct gemv_selector< OnTheRight, ColMajor, false >
struct gemv_selector< OnTheRight, RowMajor, false >
struct default_packet_traits
struct packet_traits
struct palign_impl
struct significant_decimals_default_impl
struct significant_decimals_default_impl< Scalar, true >
struct significant_decimals_impl
struct traits< Map< PlainObjectType, MapOptions, StrideType > >
struct global_math_functions_filtering_base
struct always_void
struct global_math_functions_filtering_base< T, typename always_void< typename T::Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl >::type >
struct real_impl
struct real_impl< std::complex< RealScalar > >
struct real_retval
struct imag_impl
struct imag_impl< std::complex< RealScalar > >
struct imag_retval
struct real_ref_impl
struct real_ref_retval
struct imag_ref_default_impl
struct imag_ref_default_impl< Scalar, false >
struct imag_ref_impl
struct imag_ref_retval
struct conj_impl
struct conj_impl< std::complex< RealScalar > >
struct conj_retval
struct abs_impl
struct abs_retval
struct abs2_impl
struct abs2_impl< std::complex< RealScalar > >
struct abs2_retval
struct norm1_default_impl
struct norm1_default_impl< Scalar, false >
struct norm1_impl
struct norm1_retval
struct hypot_impl
struct hypot_retval
struct cast_impl
struct sqrt_default_impl
struct sqrt_default_impl< Scalar, true >
struct sqrt_impl
struct sqrt_retval
struct atan2_default_impl
struct atan2_default_impl< Scalar, true >
struct atan2_impl
struct atan2_retval
struct pow_default_impl
struct pow_default_impl< Scalar, true >
struct pow_impl
struct pow_retval
struct random_default_impl
struct random_impl
struct random_retval
struct random_default_impl< Scalar, false, false >
struct floor_log2_selector
struct floor_log2
struct floor_log2< n, lower, upper, floor_log2_move_down >
struct floor_log2< n, lower, upper, floor_log2_move_up >
struct floor_log2< n, lower, upper, floor_log2_terminate >
struct floor_log2< n, lower, upper, floor_log2_bogus >
struct random_default_impl< Scalar, false, true >
struct random_default_impl< Scalar, true, false >
struct scalar_fuzzy_default_impl
struct scalar_fuzzy_default_impl< Scalar, false, false >
struct scalar_fuzzy_default_impl< Scalar, false, true >
struct scalar_fuzzy_default_impl< Scalar, true, false >
struct scalar_fuzzy_impl
struct random_impl< bool >
struct scalar_fuzzy_impl< bool >
struct traits< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >
struct traits< NestByValue< ExpressionType > >
struct permut_matrix_product_retval
struct permut_sparsematrix_product_retval
struct traits< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >
struct traits< Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, _PacketAccess > >
struct traits< PermutationWrapper< _IndicesType > >
struct traits< permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed > >
struct traits< Transpose< PermutationBase< Derived > > >
struct conservative_resize_like_impl
struct matrix_swap_impl
struct conservative_resize_like_impl< Derived, OtherDerived, true >
struct matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >
struct traits< ProductBase< Derived, _Lhs, _Rhs > >
struct nested< GeneralProduct< Lhs, Rhs, Mode >, N, PlainObject >
struct traits< ScaledProduct< NestedProduct > >
struct product_coeff_impl
struct product_packet_impl
struct traits< CoeffBasedProduct< LhsNested, RhsNested, NestingFlags > >
struct nested< CoeffBasedProduct< Lhs, Rhs, EvalBeforeNestingBit|EvalBeforeAssigningBit >, N, PlainObject >
struct product_coeff_impl< DefaultTraversal, UnrollingIndex, Lhs, Rhs, RetScalar >
struct product_coeff_impl< DefaultTraversal, 0, Lhs, Rhs, RetScalar >
struct product_coeff_impl< DefaultTraversal, Dynamic, Lhs, Rhs, RetScalar >
struct product_coeff_vectorized_unroller
struct product_coeff_vectorized_unroller< 0, Lhs, Rhs, Packet >
struct product_coeff_impl< InnerVectorizedTraversal, UnrollingIndex, Lhs, Rhs, RetScalar >
struct product_coeff_vectorized_dyn_selector
struct product_coeff_vectorized_dyn_selector< Lhs, Rhs, 1, RhsCols >
struct product_coeff_vectorized_dyn_selector< Lhs, Rhs, LhsRows, 1 >
struct product_coeff_vectorized_dyn_selector< Lhs, Rhs, 1, 1 >
struct product_coeff_impl< InnerVectorizedTraversal, Dynamic, Lhs, Rhs, RetScalar >
struct product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >
struct product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >
struct product_packet_impl< RowMajor, 0, Lhs, Rhs, Packet, LoadMode >
struct product_packet_impl< ColMajor, 0, Lhs, Rhs, Packet, LoadMode >
struct product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >
struct product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >
class gebp_traits
struct gebp_madd_selector
struct gebp_madd_selector< CJ, T, T, T, T >
class gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >
class gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >
class gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >
struct gebp_kernel
struct gemm_pack_lhs
struct gemm_pack_rhs< Scalar, Index, nr, ColMajor, Conjugate, PanelMode >
struct gemm_pack_rhs< Scalar, Index, nr, RowMajor, Conjugate, PanelMode >
class level3_blocking
struct general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor >
struct general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >
struct traits< GeneralProduct< Lhs, Rhs, GemmProduct > >
struct gemm_functor
class gemm_blocking_space
class gemm_blocking_space< StorageOrder, _LhsScalar, _RhsScalar, MaxRows, MaxCols, MaxDepth, KcFactor, true >
class gemm_blocking_space< StorageOrder, _LhsScalar, _RhsScalar, MaxRows, MaxCols, MaxDepth, KcFactor, false >
struct tribb_kernel
struct general_matrix_matrix_triangular_product
struct general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor, UpLo, Version >
struct general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, UpLo, Version >
struct general_matrix_matrix_rankupdate
struct general_matrix_vector_product< Index, LhsScalar, ColMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >
struct general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >
struct general_matrix_vector_product_gemv
struct GemmParallelInfo
struct symm_pack_lhs
struct symm_pack_rhs
struct product_selfadjoint_matrix
struct product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, LhsSelfAdjoint, ConjugateLhs, RhsStorageOrder, RhsSelfAdjoint, ConjugateRhs, RowMajor >
struct product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor >
struct product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor >
struct traits< SelfadjointProductMatrix< Lhs, LhsMode, false, Rhs, RhsMode, false > >
struct selfadjoint_matrix_vector_product
struct traits< SelfadjointProductMatrix< Lhs, LhsMode, false, Rhs, 0, true > >
struct traits< SelfadjointProductMatrix< Lhs, 0, true, Rhs, RhsMode, false > >
struct selfadjoint_matrix_vector_product_symv
struct selfadjoint_rank2_update_selector
struct selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Lower >
struct selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Upper >
struct conj_expr_if
struct product_triangular_matrix_matrix
struct product_triangular_matrix_matrix< Scalar, Index, Mode, LhsIsTriangular, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, RowMajor, Version >
struct product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >
struct product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >
struct traits< TriangularProduct< Mode, LhsIsTriangular, Lhs, false, Rhs, false > >
struct product_triangular_matrix_matrix_trmm
struct triangular_matrix_vector_product
struct triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >
struct triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor, Version >
struct traits< TriangularProduct< Mode, LhsIsTriangular, Lhs, false, Rhs, true > >
struct traits< TriangularProduct< Mode, LhsIsTriangular, Lhs, true, Rhs, false > >
struct trmv_selector
struct trmv_selector< ColMajor >
struct trmv_selector< RowMajor >
struct triangular_matrix_vector_product_trmv
struct triangular_solve_matrix< Scalar, Index, Side, Mode, Conjugate, TriStorageOrder, RowMajor >
struct triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >
struct triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor >
struct triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheRight, Mode, Conjugate, StorageOrder >
struct triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >
struct triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, ColMajor >
struct scalar_random_op
struct functor_traits< scalar_random_op< Scalar > >
struct redux_traits
struct redux_novec_unroller
struct redux_novec_unroller< Func, Derived, Start, 1 >
struct redux_novec_unroller< Func, Derived, Start, 0 >
struct redux_vec_unroller
struct redux_vec_unroller< Func, Derived, Start, 1 >
struct redux_impl
struct redux_impl< Func, Derived, DefaultTraversal, NoUnrolling >
struct redux_impl< Func, Derived, DefaultTraversal, CompleteUnrolling >
struct redux_impl< Func, Derived, LinearVectorizedTraversal, NoUnrolling >
struct redux_impl< Func, Derived, SliceVectorizedTraversal, NoUnrolling >
struct redux_impl< Func, Derived, LinearVectorizedTraversal, CompleteUnrolling >
struct traits< Replicate< MatrixType, RowFactor, ColFactor > >
struct traits< ReturnByValue< Derived > >
struct nested< ReturnByValue< Derived >, n, PlainObject >
struct traits< Reverse< MatrixType, Direction > >
struct reverse_packet_cond
struct reverse_packet_cond< PacketScalar, false >
struct traits< Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > >
struct traits< SelfAdjointView< MatrixType, UpLo > >
struct triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Upper), UnrollCount, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, SelfAdjoint|Upper, 0, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, SelfAdjoint|Lower, 0, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, SelfAdjoint|Upper, Dynamic, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, SelfAdjoint|Lower, Dynamic, ClearOpposite >
struct traits< SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs > >
struct triangular_solve_vector
struct triangular_solve_matrix
class trsolve_traits
struct triangular_solver_selector
struct triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >
struct triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, Dynamic >
struct triangular_solver_unroller
struct triangular_solver_unroller< Lhs, Rhs, Mode, Index, Size, false >
struct triangular_solver_unroller< Lhs, Rhs, Mode, Index, Size, true >
struct triangular_solver_selector< Lhs, Rhs, OnTheLeft, Mode, CompleteUnrolling, 1 >
struct triangular_solver_selector< Lhs, Rhs, OnTheRight, Mode, CompleteUnrolling, 1 >
struct traits< triangular_solve_retval< Side, TriangularType, Rhs > >
struct triangular_solve_retval
struct traits< SwapWrapper< ExpressionType > >
struct traits< Transpose< MatrixType > >
struct TransposeImpl_base
struct TransposeImpl_base< MatrixType, false >
struct inplace_transpose_selector
struct inplace_transpose_selector< MatrixType, true >
struct inplace_transpose_selector< MatrixType, false >
struct blas_traits< SelfCwiseBinaryOp< BinOp, NestedXpr, Rhs > >
struct check_transpose_aliasing_compile_time_selector
struct check_transpose_aliasing_compile_time_selector< DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >
struct check_transpose_aliasing_run_time_selector
struct check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >
struct checkTransposeAliasing_impl
struct checkTransposeAliasing_impl< Derived, OtherDerived, false >
struct transposition_matrix_product_retval
struct traits< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >
struct traits< Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, _PacketAccess > >
struct traits< TranspositionsWrapper< _IndicesType > >
struct traits< transposition_matrix_product_retval< TranspositionType, MatrixType, Side, Transposed > >
struct traits< TriangularView< MatrixType, _Mode > >
struct triangular_assignment_selector
struct triangular_assignment_selector< Derived1, Derived2, Mode, 0, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, Upper, Dynamic, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, Lower, Dynamic, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, StrictlyUpper, Dynamic, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, StrictlyLower, Dynamic, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, UnitUpper, Dynamic, ClearOpposite >
struct triangular_assignment_selector< Derived1, Derived2, UnitLower, Dynamic, ClearOpposite >
struct gemm_pack_rhs
struct general_matrix_matrix_product
struct general_matrix_vector_product
struct conj_if
struct conj_if< true >
struct conj_if< false >
struct conj_helper< Scalar, Scalar, false, false >
struct conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >
struct conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >
struct conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >
struct conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >
struct conj_helper< RealScalar, std::complex< RealScalar >, false, Conj >
struct get_factor
struct get_factor< Scalar, typename NumTraits< Scalar >::Real >
class blas_data_mapper
class const_blas_data_mapper
struct blas_traits
struct blas_traits< CwiseUnaryOp< scalar_conjugate_op< Scalar >, NestedXpr > >
struct blas_traits< CwiseUnaryOp< scalar_multiple_op< Scalar >, NestedXpr > >
struct blas_traits< CwiseUnaryOp< scalar_opposite_op< Scalar >, NestedXpr > >
struct blas_traits< Transpose< NestedXpr > >
struct blas_traits< const T >
struct extract_data_selector
struct extract_data_selector< T, false >
struct traits
struct traits< const T >
struct has_direct_access
struct accessors_level
class solve_retval_base
struct solve_retval
class kernel_retval_base
struct kernel_retval
class image_retval_base
struct image_retval
struct conj_helper
struct inverse_impl
struct stem_function
struct smart_copy_helper
struct smart_copy_helper< T, true >
struct smart_copy_helper< T, false >
class aligned_stack_memory_handler
struct true_type
struct false_type
struct conditional
struct conditional< false, Then, Else >
struct is_same
struct is_same< T, T >
struct remove_reference
struct remove_reference< T & >
struct remove_pointer
struct remove_pointer< T * >
struct remove_pointer< T *const >
struct remove_const
struct remove_const< const T >
struct remove_const< const T[]>
struct remove_const< const T[Size]>
struct remove_all
struct remove_all< const T >
struct remove_all< T const & >
struct remove_all< T & >
struct remove_all< T const * >
struct remove_all< T * >
struct is_arithmetic
struct is_arithmetic< float >
struct is_arithmetic< double >
struct is_arithmetic< long double >
struct is_arithmetic< bool >
struct is_arithmetic< char >
struct is_arithmetic< signed char >
struct is_arithmetic< unsigned char >
struct is_arithmetic< signed short >
struct is_arithmetic< unsigned short >
struct is_arithmetic< signed int >
struct is_arithmetic< unsigned int >
struct is_arithmetic< signed long >
struct is_arithmetic< unsigned long >
struct add_const
struct add_const< T & >
struct is_const
struct is_const< T const >
struct add_const_on_value_type
struct add_const_on_value_type< T & >
struct add_const_on_value_type< T * >
struct add_const_on_value_type< T *const >
struct add_const_on_value_type< T const *const >
struct enable_if
struct enable_if< true, T >
class noncopyable
struct result_of
struct has_none
struct has_std_result_type
struct has_tr1_result
struct unary_result_of_select
struct unary_result_of_select< Func, ArgType, sizeof(has_std_result_type)>
struct unary_result_of_select< Func, ArgType, sizeof(has_tr1_result)>
struct result_of< Func(ArgType)>
struct binary_result_of_select
struct binary_result_of_select< Func, ArgType0, ArgType1, sizeof(has_std_result_type)>
struct binary_result_of_select< Func, ArgType0, ArgType1, sizeof(has_tr1_result)>
struct result_of< Func(ArgType0, ArgType1)>
class meta_sqrt
class meta_sqrt< Y, InfX, SupX, true >
struct scalar_product_traits
struct scalar_product_traits< T, T >
struct scalar_product_traits< T, std::complex< T > >
struct scalar_product_traits< std::complex< T >, T >
struct is_diagonal
struct is_diagonal< DiagonalBase< T > >
struct is_diagonal< DiagonalWrapper< T > >
struct is_diagonal< DiagonalMatrix< T, S > >
struct static_assertion
struct static_assertion< true >
class no_assignment_operator
struct promote_index_type
class variable_if_dynamic
class variable_if_dynamic< T, Dynamic >
struct functor_traits
struct unpacket_traits
class make_proper_matrix_type
class compute_matrix_flags
struct size_at_compile_time
struct plain_matrix_type
struct plain_matrix_type_dense
struct plain_matrix_type< T, Dense >
struct plain_matrix_type_dense< T, MatrixXpr >
struct plain_matrix_type_dense< T, ArrayXpr >
struct eval
struct eval< T, Dense >
struct eval< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, Dense >
struct eval< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >, Dense >
struct plain_matrix_type_column_major
struct plain_matrix_type_row_major
struct must_nest_by_value
struct ref_selector
struct transfer_constness
struct nested
struct dense_xpr_base
struct dense_xpr_base< Derived, MatrixXpr >
struct dense_xpr_base< Derived, ArrayXpr >
struct special_scalar_op_base
struct special_scalar_op_base< Derived, Scalar, OtherScalar, true >
struct cast_return_type
struct promote_storage_type
struct promote_storage_type< A, A >
struct plain_row_type
struct plain_col_type
struct plain_diag_type
struct is_lvalue
struct traits< VectorBlock< VectorType, Size > >
struct traits< PartialReduxExpr< MatrixType, MemberOp, Direction > >
struct member_redux
struct visitor_impl
struct visitor_impl< Visitor, Derived, 1 >
struct visitor_impl< Visitor, Derived, Dynamic >
struct coeff_visitor
struct min_coeff_visitor
struct functor_traits< min_coeff_visitor< Scalar > >
struct max_coeff_visitor
struct functor_traits< max_coeff_visitor< Scalar > >
struct traits< Minor< MatrixType > >
struct complex_schur_reduce_to_hessenberg
struct complex_schur_reduce_to_hessenberg< MatrixType, false >
struct HessenbergDecompositionMatrixHReturnType
Expression type for return value of HessenbergDecomposition::matrixH()
struct traits< HessenbergDecompositionMatrixHReturnType< MatrixType > >
struct eigenvalues_selector
struct eigenvalues_selector< Derived, false >
struct direct_selfadjoint_eigenvalues
struct direct_selfadjoint_eigenvalues< SolverType, 3, false >
struct direct_selfadjoint_eigenvalues< SolverType, 2, false >
struct TridiagonalizationMatrixTReturnType
struct traits< TridiagonalizationMatrixTReturnType< MatrixType > >
struct tridiagonalization_inplace_selector
struct tridiagonalization_inplace_selector< MatrixType, 3, false >
struct tridiagonalization_inplace_selector< MatrixType, 1, IsComplex >
struct traits< AngleAxis< _Scalar > >
struct quat_product< Architecture::SSE, Derived, OtherDerived, float, Aligned >
struct cross3_impl< Architecture::SSE, VectorLhs, VectorRhs, float, true >
struct quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >
struct traits< Homogeneous< MatrixType, Direction > >
struct homogeneous_left_product_impl
struct homogeneous_right_product_impl
struct take_matrix_for_product
struct take_matrix_for_product< Transform< Scalar, Dim, Mode, Options > >
struct take_matrix_for_product< Transform< Scalar, Dim, Projective, Options > >
struct traits< homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs > >
struct homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >
struct traits< homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs > >
struct homogeneous_right_product_impl< Homogeneous< MatrixType, Horizontal >, Rhs >
struct cross3_impl
struct unitOrthogonal_selector
struct unitOrthogonal_selector< Derived, 3 >
struct unitOrthogonal_selector< Derived, 2 >
struct quaternionbase_assign_impl
struct traits< Quaternion< _Scalar, _Options > >
struct traits< Map< Quaternion< _Scalar >, _Options > >
struct traits< Map< const Quaternion< _Scalar >, _Options > >
struct quat_product
struct quaternionbase_assign_impl< Other, 3, 3 >
struct quaternionbase_assign_impl< Other, 4, 1 >
struct traits< Rotation2D< _Scalar > >
struct rotation_base_generic_product_selector
struct rotation_base_generic_product_selector< RotationDerived, MatrixType, false >
struct rotation_base_generic_product_selector< RotationDerived, DiagonalMatrix< Scalar, Dim, MaxDim >, false >
struct rotation_base_generic_product_selector< RotationDerived, OtherVectorType, true >
struct transform_traits
struct transform_right_product_impl
struct transform_left_product_impl
struct transform_transform_product_impl
struct transform_construct_from_matrix
struct transform_take_affine_part
struct projective_transform_inverse
struct projective_transform_inverse< TransformType, Projective >
struct transform_take_affine_part< Transform< Scalar, Dim, AffineCompact, Options > >
struct transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, Dim >
struct transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, Dim, HDim >
struct transform_construct_from_matrix< Other, Mode, Options, Dim, HDim, HDim, HDim >
struct transform_construct_from_matrix< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >
struct transform_product_result
struct transform_right_product_impl< TransformType, MatrixType, 0 >
struct transform_right_product_impl< TransformType, MatrixType, 1 >
struct transform_right_product_impl< TransformType, MatrixType, 2 >
struct transform_left_product_impl< Other, Mode, Options, Dim, HDim, HDim, HDim >
struct transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, HDim, HDim >
struct transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, HDim >
struct transform_left_product_impl< Other, AffineCompact, Options, Dim, HDim, Dim, HDim >
struct transform_left_product_impl< Other, Mode, Options, Dim, HDim, Dim, Dim >
struct transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, false >
struct transform_transform_product_impl< Transform< Scalar, Dim, LhsMode, LhsOptions >, Transform< Scalar, Dim, RhsMode, RhsOptions >, true >
struct transform_transform_product_impl< Transform< Scalar, Dim, AffineCompact, LhsOptions >, Transform< Scalar, Dim, Projective, RhsOptions >, true >
struct transform_transform_product_impl< Transform< Scalar, Dim, Projective, LhsOptions >, Transform< Scalar, Dim, AffineCompact, RhsOptions >, true >
struct umeyama_transform_matrix_type
struct decrement_size
struct traits< HouseholderSequence< VectorsType, CoeffsType, Side > >
struct hseq_side_dependent_impl
struct hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >
struct matrix_type_times_scalar_type
struct solve_retval< DiagonalPreconditioner< _MatrixType >, Rhs >
struct traits< BiCGSTAB< _MatrixType, _Preconditioner > >
struct solve_retval< BiCGSTAB< _MatrixType, _Preconditioner >, Rhs >
struct traits< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >
struct solve_retval< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >, Rhs >
struct solve_retval< IncompleteLUT< _MatrixType >, Rhs >
struct sparse_solve_retval< IterativeSolverBase< Derived >, Rhs >
struct compute_inverse_size4< Architecture::SSE, float, MatrixType, ResultType >
struct compute_inverse_size4< Architecture::SSE, double, MatrixType, ResultType >
struct determinant_impl
struct determinant_impl< Derived, 1 >
struct determinant_impl< Derived, 2 >
struct determinant_impl< Derived, 3 >
struct determinant_impl< Derived, 4 >
struct kernel_retval< FullPivLU< _MatrixType > >
struct image_retval< FullPivLU< _MatrixType > >
struct solve_retval< FullPivLU< _MatrixType >, Rhs >
struct compute_inverse
struct compute_inverse_and_det_with_check
struct compute_inverse< MatrixType, ResultType, 1 >
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 1 >
struct compute_inverse< MatrixType, ResultType, 2 >
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >
struct compute_inverse< MatrixType, ResultType, 3 >
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >
struct compute_inverse_size4
struct compute_inverse< MatrixType, ResultType, 4 >
struct compute_inverse_and_det_with_check< MatrixType, ResultType, 4 >
struct traits< inverse_impl< MatrixType > >
struct partial_lu_impl
struct solve_retval< PartialPivLU< _MatrixType >, Rhs >
struct traits< image_retval_base< DecompositionType > >
struct traits< kernel_retval_base< DecompositionType > >
struct traits< solve_retval_base< DecompositionType, Rhs > >
struct sparse_solve_retval_base
struct sparse_solve_retval
struct traits< sparse_solve_retval_base< DecompositionType, Rhs > >
struct solve_retval_with_guess
struct traits< solve_retval_with_guess< DecompositionType, Rhs, Guess > >
struct pardiso_run_selector
struct pardiso_run_selector< long long int >
struct pardiso_traits
struct pardiso_traits< PardisoLU< _MatrixType > >
struct pardiso_traits< PardisoLLT< _MatrixType, Options > >
struct pardiso_traits< PardisoLDLT< _MatrixType, Options > >
struct solve_retval< PardisoImpl< _Derived >, Rhs >
struct sparse_solve_retval< PardisoImpl< Derived >, Rhs >
struct pastix_traits
struct pastix_traits< PastixLU< _MatrixType > >
struct pastix_traits< PastixLLT< _MatrixType, Options > >
struct pastix_traits< PastixLDLT< _MatrixType, Options > >
struct solve_retval< PastixBase< _MatrixType >, Rhs >
struct sparse_solve_retval< PastixBase< _MatrixType >, Rhs >
struct solve_retval< ColPivHouseholderQR< _MatrixType >, Rhs >
struct FullPivHouseholderQRMatrixQReturnType
Expression type for return value of FullPivHouseholderQR::matrixQ()
struct traits< FullPivHouseholderQRMatrixQReturnType< MatrixType > >
struct solve_retval< FullPivHouseholderQR< _MatrixType >, Rhs >
struct solve_retval< HouseholderQR< _MatrixType >, Rhs >
struct traits< SimplicialLLT< _MatrixType, _UpLo > >
struct traits< SimplicialLDLT< _MatrixType, _UpLo > >
struct traits< SimplicialCholesky< _MatrixType, _UpLo > >
struct solve_retval< SimplicialCholeskyBase< Derived >, Rhs >
struct sparse_solve_retval< SimplicialCholeskyBase< Derived >, Rhs >
class AmbiVector
class CompressedStorage
struct conservative_sparse_sparse_product_selector
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, ColMajor, RowMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, ColMajor, RowMajor, RowMajor >
struct conservative_sparse_sparse_product_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor >
struct traits< MappedSparseMatrix< _Scalar, _Flags, _Index > >
struct traits< SparseInnerVectorSet< MatrixType, Size > >
struct promote_storage_type< Dense, Sparse >
struct promote_storage_type< Sparse, Dense >
class sparse_cwise_binary_op_inner_iterator_selector
class sparse_cwise_binary_op_inner_iterator_selector< BinaryOp, Lhs, Rhs, Derived, Sparse, Sparse >
class sparse_cwise_binary_op_inner_iterator_selector< scalar_product_op< T >, Lhs, Rhs, Derived, Sparse, Sparse >
class sparse_cwise_binary_op_inner_iterator_selector< scalar_product_op< T >, Lhs, Rhs, Derived, Sparse, Dense >
class sparse_cwise_binary_op_inner_iterator_selector< scalar_product_op< T >, Lhs, Rhs, Derived, Dense, Sparse >
struct traits< SparseDenseOuterProduct< Lhs, Rhs, Tr > >
struct traits< SparseTimeDenseProduct< Lhs, Rhs > >
struct sparse_time_dense_product_impl
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, RowMajor, true >
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, ColMajor, true >
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, RowMajor, false >
struct sparse_time_dense_product_impl< SparseLhsType, DenseRhsType, DenseResType, ColMajor, false >
struct traits< DenseTimeSparseProduct< Lhs, Rhs > >
struct traits< SparseDiagonalProduct< Lhs, Rhs > >
class sparse_diagonal_product_inner_iterator_selector
class sparse_diagonal_product_inner_iterator_selector< Lhs, Rhs, SparseDiagonalProductType, SDP_IsDiagonal, SDP_IsSparseRowMajor >
class sparse_diagonal_product_inner_iterator_selector< Lhs, Rhs, SparseDiagonalProductType, SDP_IsDiagonal, SDP_IsSparseColMajor >
class sparse_diagonal_product_inner_iterator_selector< Lhs, Rhs, SparseDiagonalProductType, SDP_IsSparseColMajor, SDP_IsDiagonal >
class sparse_diagonal_product_inner_iterator_selector< Lhs, Rhs, SparseDiagonalProductType, SDP_IsSparseRowMajor, SDP_IsDiagonal >
struct traits< SparseMatrix< _Scalar, _Options, _Index > >
struct traits< Diagonal< const SparseMatrix< _Scalar, _Options, _Index >, DiagIndex > >
struct traits< permut_sparsematrix_product_retval< PermutationType, MatrixType, Side, Transposed > >
struct traits< SparseSparseProduct< LhsNested, RhsNested > >
struct traits< SparseSelfAdjointView< MatrixType, UpLo > >
struct traits< SparseSelfAdjointTimeDenseProduct< Lhs, Rhs, UpLo > >
struct traits< DenseTimeSparseSelfAdjointProduct< Lhs, Rhs, UpLo > >
struct traits< SparseSymmetricPermutationProduct< MatrixType, UpLo > >
struct sparse_sparse_product_with_pruning_selector
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor >
struct sparse_sparse_product_with_pruning_selector< Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor >
struct traits< SparseTriangularView< MatrixType, Mode > >
struct sparse_eval
struct eval< T, Sparse >
struct sparse_eval< T, 1, Cols >
struct sparse_eval< T, Rows, 1 >
struct sparse_eval< T, 1, 1 >
struct plain_matrix_type< T, Sparse >
struct traits< SparseVector< _Scalar, _Options, _Index > >
struct traits< SparseView< MatrixType > >
struct sparse_solve_triangular_selector
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, RowMajor >
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, RowMajor >
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Lower, ColMajor >
struct sparse_solve_triangular_selector< Lhs, Rhs, Mode, Upper, ColMajor >
struct sparse_solve_triangular_sparse_selector
struct sparse_solve_triangular_sparse_selector< Lhs, Rhs, Mode, UpLo, ColMajor >
struct solve_retval< SuperLUBase< _MatrixType, Derived >, Rhs >
struct sparse_solve_retval< SuperLUBase< _MatrixType, Derived >, Rhs >
struct svd_precondition_2x2_block_to_be_real
struct qr_preconditioner_should_do_anything
struct qr_preconditioner_impl
class qr_preconditioner_impl< MatrixType, QRPreconditioner, Case, false >
class qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
class qr_preconditioner_impl< MatrixType, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
class qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
class qr_preconditioner_impl< MatrixType, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
class qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >
class qr_preconditioner_impl< MatrixType, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >
struct svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, false >
struct svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >
struct solve_retval< JacobiSVD< _MatrixType, QRPreconditioner >, Rhs >
class UpperBidiagonalization
struct solve_retval< UmfPackLU< _MatrixType >, Rhs >
struct sparse_solve_retval< UmfPackLU< _MatrixType >, Rhs >
Typedefs
typedef __vector float Packet4f
typedef __vector int Packet4i
typedef __vector unsigned int Packet4ui
typedef __vector __bool int Packet4bi
typedef __vector short int Packet8i
typedef __vector unsigned char Packet16uc
typedef __m128d Packet2d
Enumerations
enum { floor_log2_terminate, floor_log2_move_up, floor_log2_move_down, floor_log2_bogus }
enum PermPermProduct_t { PermPermProduct }
enum { SDP_IsDiagonal, SDP_IsSparseRowMajor, SDP_IsSparseColMajor }
enum { PreconditionIfMoreColsThanRows, PreconditionIfMoreRowsThanCols }
Functions
template<typename MatrixType , typename VectorType >
static MatrixType::Index llt_rank_update_lower (MatrixType &mat, const VectorType &vec, const typename MatrixType::RealScalar &sigma)
template<typename Scalar , typename CholmodType >
void cholmod_configure_matrix (CholmodType &mat)
template<>
EIGEN_STRONG_INLINE Packet2cf pset1< Packet2cf > (const std::complex< float > &from)
template<>
EIGEN_STRONG_INLINE Packet2cf padd< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf psub< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pnegate (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf pconj (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf pmul< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pand< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf por< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pxor< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pandnot< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pload< Packet2cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE Packet2cf ploadu< Packet2cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE Packet2cf ploaddup< Packet2cf > (const std::complex< float > *from)
template<>
EIGEN_STRONG_INLINE void pstore< std::complex< float > > (std::complex< float > *to, const Packet2cf &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< std::complex< float > > (std::complex< float > *to, const Packet2cf &from)
template<>
EIGEN_STRONG_INLINE void prefetch< std::complex< float > > (const std::complex< float > *addr)
template<>
EIGEN_STRONG_INLINE
std::complex< float > pfirst< Packet2cf > (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf preverse (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE
std::complex< float > predux< Packet2cf > (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf preduxp< Packet2cf > (const Packet2cf *vecs)
template<>
EIGEN_STRONG_INLINE
std::complex< float > predux_mul< Packet2cf > (const Packet2cf &a)
template<>
EIGEN_STRONG_INLINE Packet2cf pdiv< Packet2cf > (const Packet2cf &a, const Packet2cf &b)
template<>
EIGEN_STRONG_INLINE Packet2cf pcplxflip< Packet2cf > (const Packet2cf &x)
static _EIGEN_DECLARE_CONST_FAST_Packet4f (ZERO, 0)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (ZERO, 0)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (ONE, 1)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS16,-16)
static _EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS1,-1)
template<>
EIGEN_STRONG_INLINE Packet4f pset1< Packet4f > (const float &from)
template<>
EIGEN_STRONG_INLINE Packet4i pset1< Packet4i > (const int &from)
template<>
EIGEN_STRONG_INLINE Packet4f plset< float > (const float &a)
template<>
EIGEN_STRONG_INLINE Packet4i plset< int > (const int &a)
template<>
EIGEN_STRONG_INLINE Packet4f padd< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i padd< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f psub< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i psub< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pnegate (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i pnegate (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f pmul< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4f pdiv< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pdiv< Packet4i > (const Packet4i &, const Packet4i &)
template<>
EIGEN_STRONG_INLINE Packet4f pmadd (const Packet4f &a, const Packet4f &b, const Packet4f &c)
template<>
EIGEN_STRONG_INLINE Packet4i pmadd (const Packet4i &a, const Packet4i &b, const Packet4i &c)
template<>
EIGEN_STRONG_INLINE Packet4f pmin< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pmin< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pmax< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pmax< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pand< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pand< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f por< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i por< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pxor< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pxor< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pandnot< Packet4f > (const Packet4f &a, const Packet4f &b)
template<>
EIGEN_STRONG_INLINE Packet4i pandnot< Packet4i > (const Packet4i &a, const Packet4i &b)
template<>
EIGEN_STRONG_INLINE Packet4f pload< Packet4f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4i pload< Packet4i > (const int *from)
template<>
EIGEN_STRONG_INLINE Packet4f ploadu< Packet4f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4i ploadu< Packet4i > (const int *from)
template<>
EIGEN_STRONG_INLINE Packet4f ploaddup< Packet4f > (const float *from)
template<>
EIGEN_STRONG_INLINE Packet4i ploaddup< Packet4i > (const int *from)
template<>
EIGEN_STRONG_INLINE void pstore< float > (float *to, const Packet4f &from)
template<>
EIGEN_STRONG_INLINE void pstore< int > (int *to, const Packet4i &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< float > (float *to, const Packet4f &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< int > (int *to, const Packet4i &from)
template<>
EIGEN_STRONG_INLINE void prefetch< float > (const float *addr)
template<>
EIGEN_STRONG_INLINE void prefetch< int > (const int *addr)
template<>
EIGEN_STRONG_INLINE float pfirst< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int pfirst< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f preverse (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i preverse (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4f pabs (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4i pabs (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE float predux< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE Packet4f preduxp< Packet4f > (const Packet4f *vecs)
template<>
EIGEN_STRONG_INLINE int predux< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4i preduxp< Packet4i > (const Packet4i *vecs)
template<>
EIGEN_STRONG_INLINE float predux_mul< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int predux_mul< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE float predux_min< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int predux_min< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE float predux_max< Packet4f > (const Packet4f &a)
template<>
EIGEN_STRONG_INLINE int predux_max< Packet4i > (const Packet4i &a)
template<>
EIGEN_STRONG_INLINE Packet4i pmul< Packet4i > (const Packet4i &a, const Packet4i &b)
EIGEN_STRONG_INLINE Packet2cf pcplxflip (const Packet2cf &x)
template<>
EIGEN_STRONG_INLINE Packet1cd padd< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd psub< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pnegate (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd pconj (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd pmul< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pand< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd por< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pxor< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pandnot< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
template<>
EIGEN_STRONG_INLINE Packet1cd pload< Packet1cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE Packet1cd ploadu< Packet1cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE Packet1cd pset1< Packet1cd > (const std::complex< double > &from)
template<>
EIGEN_STRONG_INLINE Packet1cd ploaddup< Packet1cd > (const std::complex< double > *from)
template<>
EIGEN_STRONG_INLINE void pstore< std::complex< double > > (std::complex< double > *to, const Packet1cd &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< std::complex< double > > (std::complex< double > *to, const Packet1cd &from)
template<>
EIGEN_STRONG_INLINE void prefetch< std::complex< double > > (const std::complex< double > *addr)
template<>
EIGEN_STRONG_INLINE
std::complex< double > pfirst< Packet1cd > (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd preverse (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE
std::complex< double > predux< Packet1cd > (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd preduxp< Packet1cd > (const Packet1cd *vecs)
template<>
EIGEN_STRONG_INLINE
std::complex< double > predux_mul< Packet1cd > (const Packet1cd &a)
template<>
EIGEN_STRONG_INLINE Packet1cd pdiv< Packet1cd > (const Packet1cd &a, const Packet1cd &b)
EIGEN_STRONG_INLINE Packet1cd pcplxflip (const Packet1cd &x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
EIGEN_UNUSED Packet4f plog< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
EIGEN_UNUSED Packet4f pexp< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
EIGEN_UNUSED Packet4f psin< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
EIGEN_UNUSED Packet4f pcos< Packet4f > (const Packet4f &_x)
template<>
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
EIGEN_UNUSED Packet4f psqrt< Packet4f > (const Packet4f &_x)
template<>
EIGEN_STRONG_INLINE Packet2d pset1< Packet2d > (const double &from)
template<>
EIGEN_STRONG_INLINE Packet2d plset< double > (const double &a)
template<>
EIGEN_STRONG_INLINE Packet2d padd< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d psub< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pnegate (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d pmul< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pdiv< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pmin< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pmax< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pand< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d por< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pxor< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pandnot< Packet2d > (const Packet2d &a, const Packet2d &b)
template<>
EIGEN_STRONG_INLINE Packet2d pload< Packet2d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet2d ploadu< Packet2d > (const double *from)
template<>
EIGEN_STRONG_INLINE Packet2d ploaddup< Packet2d > (const double *from)
template<>
EIGEN_STRONG_INLINE void pstore< double > (double *to, const Packet2d &from)
template<>
EIGEN_STRONG_INLINE void pstoreu< double > (double *to, const Packet2d &from)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet4f > (float *to, const float &a)
template<>
EIGEN_STRONG_INLINE void pstore1< Packet2d > (double *to, const double &a)
template<>
EIGEN_STRONG_INLINE void prefetch< double > (const double *addr)
template<>
EIGEN_STRONG_INLINE double pfirst< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d preverse (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d pabs (const Packet2d &a)
EIGEN_STRONG_INLINE void punpackp (Packet4f *vecs)
template<>
EIGEN_STRONG_INLINE double predux< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE Packet2d preduxp< Packet2d > (const Packet2d *vecs)
template<>
EIGEN_STRONG_INLINE double predux_mul< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE double predux_min< Packet2d > (const Packet2d &a)
template<>
EIGEN_STRONG_INLINE double predux_max< Packet2d > (const Packet2d &a)
template<typename Derived >
static Derived::Index first_aligned (const Derived &m)
template<typename Packet >
Packet padd (const Packet &a, const Packet &b)
template<typename Packet >
Packet psub (const Packet &a, const Packet &b)
template<typename Packet >
Packet pnegate (const Packet &a)
template<typename Packet >
Packet pconj (const Packet &a)
template<typename Packet >
Packet pmul (const Packet &a, const Packet &b)
template<typename Packet >
Packet pdiv (const Packet &a, const Packet &b)
template<typename Packet >
Packet pmin (const Packet &a, const Packet &b)
template<typename Packet >
Packet pmax (const Packet &a, const Packet &b)
template<typename Packet >
Packet pabs (const Packet &a)
template<typename Packet >
Packet pand (const Packet &a, const Packet &b)
template<typename Packet >
Packet por (const Packet &a, const Packet &b)
template<typename Packet >
Packet pxor (const Packet &a, const Packet &b)
template<typename Packet >
Packet pandnot (const Packet &a, const Packet &b)
template<typename Packet >
Packet pload (const typename unpacket_traits< Packet >::type *from)
template<typename Packet >
Packet ploadu (const typename unpacket_traits< Packet >::type *from)
template<typename Packet >
Packet ploaddup (const typename unpacket_traits< Packet >::type *from)
template<typename Packet >
Packet pset1 (const typename unpacket_traits< Packet >::type &a)
template<typename Scalar >
packet_traits< Scalar >::type plset (const Scalar &a)
template<typename Scalar , typename Packet >
void pstore (Scalar *to, const Packet &from)
template<typename Scalar , typename Packet >
void pstoreu (Scalar *to, const Packet &from)
template<typename Scalar >
void prefetch (const Scalar *addr)
template<typename Packet >
unpacket_traits< Packet >::type pfirst (const Packet &a)
template<typename Packet >
Packet preduxp (const Packet *vecs)
template<typename Packet >
unpacket_traits< Packet >::type predux (const Packet &a)
template<typename Packet >
unpacket_traits< Packet >::type predux_mul (const Packet &a)
template<typename Packet >
unpacket_traits< Packet >::type predux_min (const Packet &a)
template<typename Packet >
unpacket_traits< Packet >::type predux_max (const Packet &a)
template<typename Packet >
Packet preverse (const Packet &a)
template<typename Packet >
Packet pcplxflip (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet psin (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet pcos (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet ptan (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet pasin (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet pacos (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet pexp (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet plog (const Packet &a)
template<typename Packet >
EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS
Packet psqrt (const Packet &a)
template<typename Packet >
void pstore1 (typename unpacket_traits< Packet >::type *to, const typename unpacket_traits< Packet >::type &a)
template<typename Packet >
Packet pmadd (const Packet &a, const Packet &b, const Packet &c)
template<typename Packet , int LoadMode>
Packet ploadt (const typename unpacket_traits< Packet >::type *from)
template<typename Scalar , typename Packet , int LoadMode>
void pstoret (Scalar *to, const Packet &from)
template<int Offset, typename PacketType >
void palign (PacketType &first, const PacketType &second)
template<>
std::complex< float > pmul (const std::complex< float > &a, const std::complex< float > &b)
template<>
std::complex< double > pmul (const std::complex< double > &a, const std::complex< double > &b)
template<typename Derived >
std::ostream & print_matrix (std::ostream &s, const Derived &_m, const IOFormat &fmt)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (real, Scalar) real(const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (imag, Scalar) imag(const Scalar &x)
template<typename Scalar >
add_const_on_value_type
< EIGEN_MATHFUNC_RETVAL(real_ref,
Scalar) >::type real_ref (const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (real_ref, Scalar) real_ref(Scalar &x)
template<typename Scalar >
add_const_on_value_type
< EIGEN_MATHFUNC_RETVAL(imag_ref,
Scalar) >::type imag_ref (const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (imag_ref, Scalar) imag_ref(Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (conj, Scalar) conj(const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (abs, Scalar) abs(const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (abs2, Scalar) abs2(const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (norm1, Scalar) norm1(const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (hypot, Scalar) hypot(const Scalar &x
template<typename OldType , typename NewType >
NewType cast (const OldType &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (sqrt, Scalar) sqrt(const Scalar &x)
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (atan2, Scalar) atan2(const Scalar &x
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (pow, Scalar) pow(const Scalar &x
template<typename Scalar >
EIGEN_MATHFUNC_RETVAL (random, Scalar) random(const Scalar &x
template<typename Scalar , typename OtherScalar >
bool isMuchSmallerThan (const Scalar &x, const OtherScalar &y, typename NumTraits< Scalar >::Real precision=NumTraits< Scalar >::dummy_precision())
template<typename Scalar >
bool isApprox (const Scalar &x, const Scalar &y, typename NumTraits< Scalar >::Real precision=NumTraits< Scalar >::dummy_precision())
template<typename Scalar >
bool isApproxOrLessThan (const Scalar &x, const Scalar &y, typename NumTraits< Scalar >::Real precision=NumTraits< Scalar >::dummy_precision())
template<typename T >
bool() isfinite (const T &x)
template<typename Index >
EIGEN_ALWAYS_INLINE void check_rows_cols_for_overflow (Index rows, Index cols)
std::ptrdiff_t manage_caching_sizes_helper (std::ptrdiff_t a, std::ptrdiff_t b)
void manage_caching_sizes (Action action, std::ptrdiff_t *l1=0, std::ptrdiff_t *l2=0)
template<typename LhsScalar , typename RhsScalar , int KcFactor>
void computeProductBlockingSizes (std::ptrdiff_t &k, std::ptrdiff_t &m, std::ptrdiff_t &n)
Computes the blocking parameters for a m x k times k x n matrix product.
template<typename LhsScalar , typename RhsScalar >
void computeProductBlockingSizes (std::ptrdiff_t &k, std::ptrdiff_t &m, std::ptrdiff_t &n)
template<typename CJ , typename A , typename B , typename C , typename T >
EIGEN_STRONG_INLINE void gebp_madd (const CJ &cj, A &a, B &b, C &c, T &t)
void manage_multi_threading (Action action, int *v)
template<bool Condition, typename Functor , typename Index >
void parallelize_gemm (const Functor &func, Index rows, Index cols, bool transpose)
template<typename ExpressionType , typename Scalar >
void stable_norm_kernel (const ExpressionType &bl, Scalar &ssq, Scalar &scale, Scalar &invScale)
template<typename T >
const T::Scalar * extract_data (const T &m)
bool copy_bool (bool b)
void throw_std_bad_alloc ()
void * handmade_aligned_malloc (size_t size)
void handmade_aligned_free (void *ptr)
void * handmade_aligned_realloc (void *ptr, size_t size, size_t=0)
void * aligned_malloc (size_t size)
void aligned_free (void *ptr)
void * generic_aligned_realloc (void *ptr, size_t size, size_t old_size)
void check_that_malloc_is_allowed ()
void * aligned_realloc (void *ptr, size_t new_size, size_t old_size)
template<bool Align>
void * conditional_aligned_malloc (size_t size)
template<>
void * conditional_aligned_malloc< false > (size_t size)
template<bool Align>
void conditional_aligned_free (void *ptr)
template<>
void conditional_aligned_free< false > (void *ptr)
template<bool Align>
void * conditional_aligned_realloc (void *ptr, size_t new_size, size_t old_size)
template<>
void * conditional_aligned_realloc< false > (void *ptr, size_t new_size, size_t)
template<typename T >
T * construct_elements_of_array (T *ptr, size_t size)
template<typename T >
void destruct_elements_of_array (T *ptr, size_t size)
template<typename T >
EIGEN_ALWAYS_INLINE void check_size_for_overflow (size_t size)
template<typename T >
T * aligned_new (size_t size)
template<typename T , bool Align>
T * conditional_aligned_new (size_t size)
template<typename T >
void aligned_delete (T *ptr, size_t size)
template<typename T , bool Align>
void conditional_aligned_delete (T *ptr, size_t size)
template<typename T , bool Align>
T * conditional_aligned_realloc_new (T *pts, size_t new_size, size_t old_size)
template<typename T , bool Align>
T * conditional_aligned_new_auto (size_t size)
template<typename T , bool Align>
T * conditional_aligned_realloc_new_auto (T *pts, size_t new_size, size_t old_size)
template<typename T , bool Align>
void conditional_aligned_delete_auto (T *ptr, size_t size)
template<typename Scalar , typename Index >
static Index first_aligned (const Scalar *array, Index size)
template<typename T >
void smart_copy (const T *start, const T *end, T *target)
void queryCacheSizes (int &l1, int &l2, int &l3)
int queryL1CacheSize ()
int queryTopLevelCacheSize ()
template<typename T >
T * const_cast_ptr (const T *ptr)
EIGEN_MEMBER_FUNCTOR (squaredNorm, Size *NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (norm,(Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (stableNorm,(Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (blueNorm,(Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (hypotNorm,(Size-1)*functor_traits< scalar_hypot_op< Scalar > >::Cost)
EIGEN_MEMBER_FUNCTOR (sum,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (mean,(Size-1)*NumTraits< Scalar >::AddCost+NumTraits< Scalar >::MulCost)
EIGEN_MEMBER_FUNCTOR (minCoeff,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (maxCoeff,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (all,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (any,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (count,(Size-1)*NumTraits< Scalar >::AddCost)
EIGEN_MEMBER_FUNCTOR (prod,(Size-1)*NumTraits< Scalar >::MulCost)
template<int StorageOrder, typename RealScalar , typename Scalar , typename Index >
static void tridiagonal_qr_step (RealScalar *diag, RealScalar *subdiag, Index start, Index end, Scalar *matrixQ, Index n)
template<typename MatrixType , typename CoeffVectorType >
void tridiagonalization_inplace (MatrixType &matA, CoeffVectorType &hCoeffs)
template<typename MatrixType , typename DiagonalType , typename SubDiagonalType >
void tridiagonalization_inplace (MatrixType &mat, DiagonalType &diag, SubDiagonalType &subdiag, bool extractQ)
Performs a full tridiagonalization in place.
template<typename Scalar , int Dim>
static Matrix< Scalar, 2, 2 > toRotationMatrix (const Scalar &s)
template<typename Scalar , int Dim, typename OtherDerived >
static Matrix< Scalar, Dim, Dim > toRotationMatrix (const RotationBase< OtherDerived, Dim > &r)
template<typename Scalar , int Dim, typename OtherDerived >
static const MatrixBase
< OtherDerived > & toRotationMatrix (const MatrixBase< OtherDerived > &mat)
template<typename TriangularFactorType , typename VectorsType , typename CoeffsType >
void make_block_householder_triangular_factor (TriangularFactorType &triFactor, const VectorsType &vectors, const CoeffsType &hCoeffs)
template<typename MatrixType , typename VectorsType , typename CoeffsType >
void apply_block_householder_on_the_left (MatrixType &mat, const VectorsType &vectors, const CoeffsType &hCoeffs)
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner >
bool bicgstab (const MatrixType &mat, const Rhs &rhs, Dest &x, const Preconditioner &precond, int &iters, typename Dest::RealScalar &tol_error)
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner >
EIGEN_DONT_INLINE void conjugate_gradient (const MatrixType &mat, const Rhs &rhs, Dest &x, const Preconditioner &precond, int &iters, typename Dest::RealScalar &tol_error)
template<typename VectorX , typename VectorY , typename OtherScalar >
void apply_rotation_in_the_plane (VectorX &_x, VectorY &_y, const JacobiRotation< OtherScalar > &j)
template<typename Derived >
const Derived::Scalar bruteforce_det3_helper (const MatrixBase< Derived > &matrix, int a, int b, int c)
template<typename Derived >
const Derived::Scalar bruteforce_det4_helper (const MatrixBase< Derived > &matrix, int j, int k, int m, int n)
template<typename MatrixType , typename ResultType >
void compute_inverse_size2_helper (const MatrixType &matrix, const typename ResultType::Scalar &invdet, ResultType &result)
template<typename MatrixType , int i, int j>
MatrixType::Scalar cofactor_3x3 (const MatrixType &m)
template<typename MatrixType , typename ResultType >
void compute_inverse_size3_helper (const MatrixType &matrix, const typename ResultType::Scalar &invdet, const Matrix< typename ResultType::Scalar, 3, 1 > &cofactors_col0, ResultType &result)
template<typename Derived >
const Derived::Scalar general_det3_helper (const MatrixBase< Derived > &matrix, int i1, int i2, int i3, int j1, int j2, int j3)
template<typename MatrixType , int i, int j>
MatrixType::Scalar cofactor_4x4 (const MatrixType &matrix)
template<typename MatrixType , typename TranspositionType >
void partial_lu_inplace (MatrixType &lu, TranspositionType &row_transpositions, typename TranspositionType::Index &nb_transpositions)
template<typename T >
T amd_flip (const T &i)
template<typename T >
T amd_unflip (const T &i)
template<typename T0 , typename T1 >
bool amd_marked (const T0 *w, const T1 &j)
template<typename T0 , typename T1 >
void amd_mark (const T0 *w, const T1 &j)
template<typename Index >
static int cs_wclear (Index mark, Index lemax, Index *w, Index n)
template<typename Index >
Index cs_tdfs (Index j, Index k, Index *head, const Index *next, Index *post, Index *stack)
template<typename Scalar , typename Index >
void minimum_degree_ordering (SparseMatrix< Scalar, ColMajor, Index > &C, PermutationMatrix< Dynamic, Dynamic, Index > &perm)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, float *vals, int *perm, int *invp, float *x, int nbrhs, int *iparm, double *dparm)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, double *vals, int *perm, int *invp, double *x, int nbrhs, int *iparm, double *dparm)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, std::complex< float > *vals, int *perm, int *invp, std::complex< float > *x, int nbrhs, int *iparm, double *dparm)
void eigen_pastix (pastix_data_t **pastix_data, int pastix_comm, int n, int *ptr, int *idx, std::complex< double > *vals, int *perm, int *invp, std::complex< double > *x, int nbrhs, int *iparm, double *dparm)
template<typename MatrixType >
void c_to_fortran_numbering (MatrixType &mat)
template<typename MatrixType >
void fortran_to_c_numbering (MatrixType &mat)
template<typename MatrixQR , typename HCoeffs >
void householder_qr_inplace_unblocked (MatrixQR &mat, HCoeffs &hCoeffs, typename MatrixQR::Scalar *tempData=0)
template<typename MatrixQR , typename HCoeffs >
void householder_qr_inplace_blocked (MatrixQR &mat, HCoeffs &hCoeffs, typename MatrixQR::Index maxBlockSize=32, typename MatrixQR::Scalar *tempData=0)
template<typename Lhs , typename Rhs , typename ResultType >
static void conservative_sparse_sparse_product_impl (const Lhs &lhs, const Rhs &rhs, ResultType &res)
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType , typename AlphaType >
void sparse_time_dense_product (const SparseLhsType &lhs, const DenseRhsType &rhs, DenseResType &res, const AlphaType &alpha)
template<typename InputIterator , typename SparseMatrixType >
void set_from_triplets (const InputIterator &begin, const InputIterator &end, SparseMatrixType &mat, int Options=0)
template<int SrcUpLo, int DstUpLo, typename MatrixType , int DestOrder>
void permute_symm_to_symm (const MatrixType &mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::Index > &_dest, const typename MatrixType::Index *perm=0)
template<int UpLo, typename MatrixType , int DestOrder>
void permute_symm_to_fullsymm (const MatrixType &mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::Index > &_dest, const typename MatrixType::Index *perm=0)
template<int _SrcUpLo, int _DstUpLo, typename MatrixType , int DstOrder>
void permute_symm_to_symm (const MatrixType &mat, SparseMatrix< typename MatrixType::Scalar, DstOrder, typename MatrixType::Index > &_dest, const typename MatrixType::Index *perm)
template<typename Lhs , typename Rhs , typename ResultType >
static void sparse_sparse_product_with_pruning_impl (const Lhs &lhs, const Rhs &rhs, ResultType &res, typename ResultType::RealScalar tolerance)
template<typename MatrixType >
SluMatrix asSluMatrix (MatrixType &mat)
template<typename Scalar , int Flags, typename Index >
MappedSparseMatrix< Scalar,
Flags, Index > map_superlu (SluMatrix &sluMat)
template<typename MatrixType , typename RealScalar , typename Index >
void real_2x2_jacobi_svd (const MatrixType &matrix, Index p, Index q, JacobiRotation< RealScalar > *j_left, JacobiRotation< RealScalar > *j_right)
Variables
static Packet4ui p4ui_CONJ_XOR = vec_mergeh((Packet4ui)p4i_ZERO, (Packet4ui)p4f_ZERO_)
static Packet16uc p16uc_COMPLEX_RE = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 2), 8)
static Packet16uc p16uc_COMPLEX_IM = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 1), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 3), 8)
static Packet16uc p16uc_COMPLEX_REV = vec_sld(p16uc_REVERSE, p16uc_REVERSE, 8)
static Packet16uc p16uc_COMPLEX_REV2 = vec_sld(p16uc_FORWARD, p16uc_FORWARD, 8)
static Packet16uc p16uc_PSET_HI = (Packet16uc) vec_mergeh((Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 1))
static Packet16uc p16uc_PSET_LO = (Packet16uc) vec_mergeh((Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 2), (Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 3))
static Packet4f p4f_COUNTDOWN = { 3.0, 2.0, 1.0, 0.0 }
static Packet4i p4i_COUNTDOWN = { 3, 2, 1, 0 }
static Packet16uc p16uc_REVERSE = {12,13,14,15, 8,9,10,11, 4,5,6,7, 0,1,2,3}
static Packet16uc p16uc_FORWARD = vec_lvsl(0, (float*)0)
static Packet16uc p16uc_DUPLICATE = {0,1,2,3, 0,1,2,3, 4,5,6,7, 4,5,6,7}
static Packet4f p4f_ONE = vec_ctf(p4i_ONE, 0)
static Packet4f p4f_ZERO_ = (Packet4f) vec_sl((Packet4ui)p4i_MINUS1, (Packet4ui)p4i_MINUS1)
static uint32x4_t p4ui_CONJ_XOR = EIGEN_INIT_NEON_PACKET4(0x00000000, 0x80000000, 0x00000000, 0x80000000)
static uint32x2_t p2ui_CONJ_XOR = EIGEN_INIT_NEON_PACKET2(0x00000000, 0x80000000)
const Scalar & y
Detailed Description
Applies the clock wise 2D rotation j to the set of 2D vectors of cordinates x and y:
See Also
MatrixBase::applyOnTheLeft(), MatrixBase::applyOnTheRight()
Typedef Documentation
typedef __vector unsigned char Eigen::internal::Packet16uc
Definition at line 35 of file PacketMath.h.
typedef __m128d Eigen::internal::Packet2d
Definition at line 27 of file PacketMath.h.
typedef __vector __bool int Eigen::internal::Packet4bi
Definition at line 33 of file PacketMath.h.
typedef __m128 Eigen::internal::Packet4f
Definition at line 30 of file PacketMath.h.
typedef __m128i Eigen::internal::Packet4i
Definition at line 31 of file PacketMath.h.
typedef uint32x4_t Eigen::internal::Packet4ui
Definition at line 32 of file PacketMath.h.
typedef __vector short int Eigen::internal::Packet8i
Definition at line 34 of file PacketMath.h.
Enumeration Type Documentation
anonymous enum
Enumerator
floor_log2_terminate
floor_log2_move_up
floor_log2_move_down
floor_log2_bogus
Definition at line 605 of file MathFunctions.h.
anonymous enum
Enumerator
SDP_IsDiagonal
SDP_IsSparseRowMajor
SDP_IsSparseColMajor
Definition at line 52 of file SparseDiagonalProduct.h.
anonymous enum
Enumerator
PreconditionIfMoreColsThanRows
PreconditionIfMoreRowsThanCols
Definition at line 29 of file JacobiSVD.h.
enum Eigen::internal::PermPermProduct_t
Enumerator
PermPermProduct
Definition at line 48 of file PermutationMatrix.h.
Function Documentation
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4f (ZERO , 0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (ZERO , 0) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (ONE , 1) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS16 , - 16) static
static Eigen::internal::_EIGEN_DECLARE_CONST_FAST_Packet4i (MINUS1 , - 1) static
template<typename T > void Eigen::internal::aligned_delete (T * ptr, size_t size) inline
Definition at line 372 of file Memory.h.
References aligned_free().
Referenced by Eigen::ei_aligned_delete(), and Eigen::internal::gemm_blocking_space< StorageOrder, _LhsScalar, _RhsScalar, MaxRows, MaxCols, MaxDepth, KcFactor, false >::~gemm_blocking_space().
void Eigen::internal::aligned_free (void * ptr) inline
Definition at line 220 of file Memory.h.
References handmade_aligned_free().
Referenced by aligned_delete(), conditional_aligned_free(), Eigen::aligned_allocator< T >::deallocate(), Eigen::ei_aligned_free(), generic_aligned_realloc(), and Eigen::internal::aligned_stack_memory_handler< T >::~aligned_stack_memory_handler().
void * Eigen::internal::aligned_malloc (size_t size) inline
Definition at line 194 of file Memory.h.
References check_that_malloc_is_allowed(), handmade_aligned_malloc(), and throw_std_bad_alloc().
Referenced by aligned_new(), Eigen::aligned_allocator< T >::allocate(), conditional_aligned_malloc(), Eigen::ei_aligned_malloc(), and generic_aligned_realloc().
template<typename T > T* Eigen::internal::aligned_new (size_t size) inline
Definition at line 355 of file Memory.h.
References aligned_malloc(), and construct_elements_of_array().
void* Eigen::internal::aligned_realloc (void * ptr, size_t new_size, size_t old_size) inline
Definition at line 242 of file Memory.h.
References EIGEN_UNUSED_VARIABLE, generic_aligned_realloc(), handmade_aligned_realloc(), and throw_std_bad_alloc().
Referenced by conditional_aligned_realloc(), and Eigen::ei_aligned_realloc().
template<typename T > T Eigen::internal::amd_flip (const T & i) inline
Definition at line 42 of file Amd.h.
Referenced by amd_mark(), amd_unflip(), and minimum_degree_ordering().
template<typename T0 , typename T1 > void Eigen::internal::amd_mark (const T0 * w, const T1 & j) inline
Definition at line 45 of file Amd.h.
References amd_flip().
template<typename T0 , typename T1 > bool Eigen::internal::amd_marked (const T0 * w, const T1 & j) inline
Definition at line 44 of file Amd.h.
template<typename T > T Eigen::internal::amd_unflip (const T & i) inline
Definition at line 43 of file Amd.h.
References amd_flip().
template<typename MatrixType , typename VectorsType , typename CoeffsType > void Eigen::internal::apply_block_householder_on_the_left (MatrixType & mat, const VectorsType & vectors, const CoeffsType & hCoeffs)
Definition at line 46 of file BlockHouseholder.h.
References Eigen::TriangularView< _MatrixType, _Mode >::adjoint(), and make_block_householder_triangular_factor().
Referenced by householder_qr_inplace_blocked().
template<typename VectorX , typename VectorY , typename OtherScalar > void Eigen::internal::apply_rotation_in_the_plane (VectorX & _x, VectorY & _y, const JacobiRotation< OtherScalar > & j)
Definition at line 293 of file Jacobi.h.
References Eigen::AlignedBit, Eigen::Dynamic, eigen_assert, EIGEN_RESTRICT, first_aligned(), Eigen::PacketAccessBit, padd(), pmul(), pstore(), pstoreu(), psub(), and y.
Referenced by Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheRight(), and llt_rank_update_lower().
template<typename MatrixType > SluMatrix Eigen::internal::asSluMatrix (MatrixType & mat)
Definition at line 265 of file SuperLUSupport.h.
References Eigen::SluMatrix::Map().
Referenced by Eigen::SuperLUBase< _MatrixType, SuperLU< _MatrixType > >::initFactorization().
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner > bool Eigen::internal::bicgstab (const MatrixType & mat, const Rhs & rhs, Dest & x, const Preconditioner & precond, int & iters, typename Dest::RealScalar & tol_error)
Definition at line 29 of file BiCGSTAB.h.
References abs(), Eigen::PlainObjectBase< Derived >::cols(), sqrt(), and y.
Referenced by Eigen::BiCGSTAB< _MatrixType, _Preconditioner >::_solveWithGuess().
template<typename Derived > const Derived::Scalar Eigen::internal::bruteforce_det3_helper (const MatrixBase< Derived > & matrix, int a, int b, int c) inline
Definition at line 19 of file Determinant.h.
Referenced by Eigen::internal::determinant_impl< Derived, 3 >::run().
template<typename Derived > const Derived::Scalar Eigen::internal::bruteforce_det4_helper (const MatrixBase< Derived > & matrix, int j, int k, int m, int n)
Definition at line 27 of file Determinant.h.
Referenced by Eigen::internal::determinant_impl< Derived, 4 >::run().
template<typename MatrixType > void Eigen::internal::c_to_fortran_numbering (MatrixType & mat)
Definition at line 89 of file PaStiXSupport.h.
Referenced by Eigen::PastixLU< _MatrixType, IsStrSym >::grabMatrix(), Eigen::PastixLLT< _MatrixType, Options >::grabMatrix(), and Eigen::PastixLDLT< _MatrixType, Options >::grabMatrix().
template<typename OldType , typename NewType > NewType Eigen::internal::cast (const OldType & x) inline
Definition at line 402 of file MathFunctions.h.
References Eigen::internal::cast_impl< OldType, NewType >::run().
template<typename Index > EIGEN_ALWAYS_INLINE void Eigen::internal::check_rows_cols_for_overflow (Index rows, Index cols)
Definition at line 25 of file PlainObjectBase.h.
References throw_std_bad_alloc().
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resize(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), and Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
template<typename T > EIGEN_ALWAYS_INLINE void Eigen::internal::check_size_for_overflow (size_t size)
Definition at line 345 of file Memory.h.
References throw_std_bad_alloc().
void Eigen::internal::check_that_malloc_is_allowed () inline
Definition at line 187 of file Memory.h.
Referenced by aligned_malloc(), and conditional_aligned_malloc< false >().
template<typename Scalar , typename CholmodType > void Eigen::internal::cholmod_configure_matrix (CholmodType & mat)
Definition at line 18 of file CholmodSupport.h.
References eigen_assert.
template<typename MatrixType , int i, int j> MatrixType::Scalar Eigen::internal::cofactor_3x3 (const MatrixType & m) inline
Definition at line 115 of file Inverse.h.
template<typename MatrixType , int i, int j> MatrixType::Scalar Eigen::internal::cofactor_4x4 (const MatrixType & matrix) inline
Definition at line 196 of file Inverse.h.
References general_det3_helper().
template<typename MatrixType , typename ResultType > void Eigen::internal::compute_inverse_size2_helper (const MatrixType & matrix, const typename ResultType::Scalar & invdet, ResultType & result) inline
Definition at line 69 of file Inverse.h.
Referenced by Eigen::internal::compute_inverse< MatrixType, ResultType, 2 >::run(), and Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 2 >::run().
template<typename MatrixType , typename ResultType > void Eigen::internal::compute_inverse_size3_helper (const MatrixType & matrix, const typename ResultType::Scalar & invdet, const Matrix< typename ResultType::Scalar, 3, 1 > & cofactors_col0, ResultType & result) inline
Definition at line 128 of file Inverse.h.
References Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef().
Referenced by Eigen::internal::compute_inverse< MatrixType, ResultType, 3 >::run(), and Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run().
template<typename LhsScalar , typename RhsScalar , int KcFactor> void Eigen::internal::computeProductBlockingSizes (std::ptrdiff_t & k, std::ptrdiff_t & m, std::ptrdiff_t & n)
Computes the blocking parameters for a m x k times k x n matrix product.
Parameters
[in,out] k Input: the third dimension of the product. Output: the blocking size along the same dimension.
[in,out] m Input: the number of rows of the left hand side. Output: the blocking size along the same dimension.
[in,out] n Input: the number of columns of the right hand side. Output: the blocking size along the same dimension.
Given a m x k times k x n matrix product of scalar types LhsScalar and RhsScalar, this function computes the blocking size parameters along the respective dimensions for matrix products and related algorithms. The blocking sizes depends on various parameters:
the L1 and L2 cache sizes,
the register level blocking sizes defined by gebp_traits,
the number of scalars that fit into a packet (when vectorization is enabled).
See Also
setCpuCacheSizes
Definition at line 73 of file GeneralBlockPanelKernel.h.
References EIGEN_UNUSED_VARIABLE, Eigen::GetAction, and manage_caching_sizes().
template<typename LhsScalar , typename RhsScalar > void Eigen::internal::computeProductBlockingSizes (std::ptrdiff_t & k, std::ptrdiff_t & m, std::ptrdiff_t & n) inline
Definition at line 100 of file GeneralBlockPanelKernel.h.
template<typename T , bool Align> void Eigen::internal::conditional_aligned_delete (T * ptr, size_t size) inline
Definition at line 381 of file Memory.h.
template<typename T , bool Align> void Eigen::internal::conditional_aligned_delete_auto (T * ptr, size_t size) inline
Definition at line 421 of file Memory.h.
template<bool Align> void Eigen::internal::conditional_aligned_free (void * ptr) inline
Definition at line 297 of file Memory.h.
References aligned_free().
template<> void Eigen::internal::conditional_aligned_free< false > (void * ptr) inline
Definition at line 302 of file Memory.h.
template<bool Align> void* Eigen::internal::conditional_aligned_malloc (size_t size) inline
Definition at line 281 of file Memory.h.
References aligned_malloc().
template<> void* Eigen::internal::conditional_aligned_malloc< false > (size_t size) inline
Definition at line 286 of file Memory.h.
References check_that_malloc_is_allowed(), and throw_std_bad_alloc().
template<typename T , bool Align> T* Eigen::internal::conditional_aligned_new (size_t size) inline
Definition at line 362 of file Memory.h.
References construct_elements_of_array().
template<typename T , bool Align> T* Eigen::internal::conditional_aligned_new_auto (size_t size) inline
Definition at line 400 of file Memory.h.
References construct_elements_of_array().
template<bool Align> void* Eigen::internal::conditional_aligned_realloc (void * ptr, size_t new_size, size_t old_size) inline
Definition at line 307 of file Memory.h.
References aligned_realloc().
template<> void* Eigen::internal::conditional_aligned_realloc< false > (void * ptr, size_t new_size, size_t) inline
Definition at line 312 of file Memory.h.
template<typename T , bool Align> T* Eigen::internal::conditional_aligned_realloc_new (T * pts, size_t new_size, size_t old_size) inline
Definition at line 387 of file Memory.h.
References construct_elements_of_array(), and destruct_elements_of_array().
template<typename T , bool Align> T* Eigen::internal::conditional_aligned_realloc_new_auto (T * pts, size_t new_size, size_t old_size) inline
Definition at line 409 of file Memory.h.
References construct_elements_of_array(), and destruct_elements_of_array().
template<typename MatrixType , typename Rhs , typename Dest , typename Preconditioner > EIGEN_DONT_INLINE void Eigen::internal::conjugate_gradient (const MatrixType & mat, const Rhs & rhs, Dest & x, const Preconditioner & precond, int & iters, typename Dest::RealScalar & tol_error)
Definition at line 28 of file ConjugateGradient.h.
References abs(), Eigen::PlainObjectBase< Derived >::cols(), real(), and sqrt().
Referenced by Eigen::ConjugateGradient< _MatrixType, _UpLo, _Preconditioner >::_solveWithGuess().
template<typename Lhs , typename Rhs , typename ResultType > static void Eigen::internal::conservative_sparse_sparse_product_impl (const Lhs & lhs, const Rhs & rhs, ResultType & res) static
Definition at line 18 of file ConservativeSparseSparseProduct.h.
References Eigen::PlainObjectBase< Derived >::data(), eigen_assert, and y.
template<typename T > T* Eigen::internal::const_cast_ptr (const T * ptr)
Definition at line 322 of file XprHelper.h.
template<typename T > T* Eigen::internal::construct_elements_of_array (T * ptr, size_t size) inline
Definition at line 324 of file Memory.h.
Referenced by aligned_new(), Eigen::internal::aligned_stack_memory_handler< T >::aligned_stack_memory_handler(), conditional_aligned_new(), conditional_aligned_new_auto(), conditional_aligned_realloc_new(), and conditional_aligned_realloc_new_auto().
bool Eigen::internal::copy_bool (bool b) inline
Definition at line 174 of file Macros.h.
template<typename Index > Index Eigen::internal::cs_tdfs (Index j, Index k, Index * head, const Index * next, Index * post, Index * stack)
Definition at line 64 of file Amd.h.
template<typename Index > static int Eigen::internal::cs_wclear (Index mark, Index lemax, Index * w, Index n) static
Definition at line 49 of file Amd.h.
template<typename T > void Eigen::internal::destruct_elements_of_array (T * ptr, size_t size) inline
Definition at line 333 of file Memory.h.
Referenced by conditional_aligned_realloc_new(), and conditional_aligned_realloc_new_auto().
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (real , Scalar) const inline
Definition at line 89 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL, and real().
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (imag , Scalar) const inline
Definition at line 125 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL, and imag().
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (real_ref , Scalar) inline
Definition at line 161 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL, and real_ref().
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (imag_ref , Scalar) inline
Definition at line 213 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL, and imag_ref().
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (conj , Scalar) const inline
Definition at line 248 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL.
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (abs , Scalar) const inline
Definition at line 275 of file MathFunctions.h.
References abs(), and EIGEN_MATHFUNC_IMPL.
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (abs2 , Scalar) const inline
Definition at line 310 of file MathFunctions.h.
References abs2(), and EIGEN_MATHFUNC_IMPL.
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (norm1 , Scalar) const inline
Definition at line 348 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL.
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (hypot , Scalar) const inline
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (sqrt , Scalar) const inline
Definition at line 445 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL, and sqrt().
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (atan2 , Scalar) const inline
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (pow , Scalar) const inline
template<typename Scalar > Eigen::internal::EIGEN_MATHFUNC_RETVAL (random , Scalar) const inline
Definition at line 700 of file MathFunctions.h.
References EIGEN_MATHFUNC_IMPL.
Eigen::internal::EIGEN_MEMBER_FUNCTOR (squaredNorm , Size *NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (norm , (Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (stableNorm , (Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (blueNorm , (Size+5)*NumTraits< Scalar >::MulCost+(Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (hypotNorm , (Size-1)*functor_traits< scalar_hypot_op< Scalar > >::Cost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (sum , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (mean , (Size-1)*NumTraits< Scalar >::AddCost+NumTraits< Scalar >::MulCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (minCoeff , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (maxCoeff , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (all , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (any , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (count , (Size-1)*NumTraits< Scalar >::AddCost)
Eigen::internal::EIGEN_MEMBER_FUNCTOR (prod , (Size-1)*NumTraits< Scalar >::MulCost)
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, float * vals, int * perm, int * invp, float * x, int nbrhs, int * iparm, double * dparm)
Definition at line 59 of file PaStiXSupport.h.
Referenced by Eigen::PastixBase< Derived >::_solve(), Eigen::PastixBase< Derived >::analyzePattern(), Eigen::PastixBase< PastixLU< _MatrixType > >::clean(), Eigen::PastixBase< Derived >::factorize(), and Eigen::PastixBase< Derived >::init().
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, double * vals, int * perm, int * invp, double * x, int nbrhs, int * iparm, double * dparm)
Definition at line 66 of file PaStiXSupport.h.
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, std::complex< float > * vals, int * perm, int * invp, std::complex< float > * x, int nbrhs, int * iparm, double * dparm)
Definition at line 73 of file PaStiXSupport.h.
void Eigen::internal::eigen_pastix (pastix_data_t ** pastix_data, int pastix_comm, int n, int * ptr, int * idx, std::complex< double > * vals, int * perm, int * invp, std::complex< double > * x, int nbrhs, int * iparm, double * dparm)
Definition at line 80 of file PaStiXSupport.h.
template<typename T > const T::Scalar* Eigen::internal::extract_data (const T & m)
Definition at line 255 of file BlasUtil.h.
References Eigen::internal::extract_data_selector< T, HasUsableDirectAccess >::run().
Referenced by Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::evalTo(), Eigen::internal::triangular_solve_retval< Side, TriangularType, Rhs >::evalTo(), Eigen::internal::inverse_impl< MatrixType >::evalTo(), Eigen::internal::transposition_matrix_product_retval< TranspositionType, MatrixType, Side, Transposed >::evalTo(), Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo(), Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, OtherDerived >::run(), Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run(), and Eigen::internal::checkTransposeAliasing_impl< Derived, OtherDerived, MightHaveTransposeAliasing >::run().
template<typename Scalar , typename Index > static Index Eigen::internal::first_aligned (const Scalar * array, Index size) inline static
Definition at line 447 of file Memory.h.
template<typename Derived > static Derived::Index Eigen::internal::first_aligned (const Derived & m) inline static
Definition at line 719 of file DenseCoeffsBase.h.
References Eigen::AlignedBit, and Eigen::DirectAccessBit.
Referenced by apply_rotation_in_the_plane(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, ColMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run(), Eigen::internal::redux_impl< Func, Derived, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run(), Eigen::internal::assign_impl< Derived1, Derived2, LinearVectorizedTraversal, NoUnrolling, Version >::run(), Eigen::internal::assign_impl< Derived1, Derived2, SliceVectorizedTraversal, NoUnrolling, Version >::run(), Eigen::internal::first_aligned_impl< Derived, false >::run(), and Eigen::MatrixBase< Derived >::stableNorm().
template<typename MatrixType > void Eigen::internal::fortran_to_c_numbering (MatrixType & mat)
Definition at line 103 of file PaStiXSupport.h.
template<typename CJ , typename A , typename B , typename C , typename T > EIGEN_STRONG_INLINE void Eigen::internal::gebp_madd (const CJ & cj, A & a, B & b, C & c, T & t)
Definition at line 126 of file GeneralBlockPanelKernel.h.
References Eigen::internal::gebp_madd_selector< CJ, A, B, C, T >::run().
template<typename Derived > const Derived::Scalar Eigen::internal::general_det3_helper (const MatrixBase< Derived > & matrix, int i1, int i2, int i3, int j1, int j2, int j3) inline
Definition at line 189 of file Inverse.h.
Referenced by cofactor_4x4().
void* Eigen::internal::generic_aligned_realloc (void * ptr, size_t size, size_t old_size) inline
Definition at line 134 of file Memory.h.
References aligned_free(), aligned_malloc(), and min().
Referenced by aligned_realloc().
void Eigen::internal::handmade_aligned_free (void * ptr) inline
Definition at line 101 of file Memory.h.
Referenced by aligned_free(), and Eigen::ei_handmade_aligned_free().
void* Eigen::internal::handmade_aligned_malloc (size_t size) inline
Definition at line 91 of file Memory.h.
Referenced by aligned_malloc(), Eigen::ei_handmade_aligned_malloc(), and handmade_aligned_realloc().
void* Eigen::internal::handmade_aligned_realloc (void * ptr, size_t size, size_t = 0) inline
Definition at line 111 of file Memory.h.
References handmade_aligned_malloc().
Referenced by aligned_realloc().
template<typename MatrixQR , typename HCoeffs > void Eigen::internal::householder_qr_inplace_blocked (MatrixQR & mat, HCoeffs & hCoeffs, typename MatrixQR::Index maxBlockSize = 32, typename MatrixQR::Scalar * tempData = 0)
Definition at line 229 of file HouseholderQR.h.
References apply_block_householder_on_the_left(), householder_qr_inplace_unblocked(), min(), Eigen::PlainObjectBase< Derived >::resize(), and Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::rows().
Referenced by Eigen::HouseholderQR< MatrixType >::compute().
template<typename MatrixQR , typename HCoeffs > void Eigen::internal::householder_qr_inplace_unblocked (MatrixQR & mat, HCoeffs & hCoeffs, typename MatrixQR::Scalar * tempData = 0)
Definition at line 193 of file HouseholderQR.h.
References eigen_assert, min(), and Eigen::PlainObjectBase< Derived >::resize().
Referenced by householder_qr_inplace_blocked().
template<typename Scalar > add_const_on_value_type< EIGEN_MATHFUNC_RETVAL(imag_ref, Scalar) >::type Eigen::internal::imag_ref (const Scalar & x) inline
Definition at line 207 of file MathFunctions.h.
References Eigen::internal::imag_ref_default_impl< Scalar, NumTraits< Scalar >::IsComplex >::run().
Referenced by EIGEN_MATHFUNC_RETVAL(), and Eigen::internal::scalar_imag_ref_op< Scalar >::operator()().
template<typename Scalar > bool Eigen::internal::isApprox (const Scalar & x, const Scalar & y, typename NumTraits< Scalar >::Real precision = NumTraits<Scalar>::dummy_precision()) inline
Definition at line 780 of file MathFunctions.h.
References Eigen::precision().
Referenced by Eigen::ei_isApprox(), Eigen::UniformScaling< _Scalar >::isApprox(), Eigen::Rotation2D< Scalar >::isApprox(), Eigen::AngleAxis< Scalar >::isApprox(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, false >::isApproxOrLessThan(), Eigen::DenseBase< Derived >::isApproxToConstant(), Eigen::MatrixBase< Derived >::isIdentity(), and Eigen::MatrixBase< Derived >::isUnitary().
template<typename Scalar > bool Eigen::internal::isApproxOrLessThan (const Scalar & x, const Scalar & y, typename NumTraits< Scalar >::Real precision = NumTraits<Scalar>::dummy_precision()) inline
Definition at line 787 of file MathFunctions.h.
References Eigen::precision().
Referenced by Eigen::ei_isApproxOrLessThan().
template<typename T > bool() Eigen::internal::isfinite (const T & x)
Definition at line 833 of file MathFunctions.h.
Referenced by Eigen::internal::ldlt_inplace< Lower >::updateInPlace().
template<typename Scalar , typename OtherScalar > bool Eigen::internal::isMuchSmallerThan (const Scalar & x, const OtherScalar & y, typename NumTraits< Scalar >::Real precision = NumTraits<Scalar>::dummy_precision()) inline
Definition at line 773 of file MathFunctions.h.
References Eigen::precision(), and y.
Referenced by Eigen::FullPivHouseholderQR< MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::ei_isMuchSmallerThan(), Eigen::EigenSolver< _MatrixType >::eigenvectors(), Eigen::internal::solve_retval< FullPivHouseholderQR< _MatrixType >, Rhs >::evalTo(), Eigen::SparseView< MatrixType >::InnerIterator::incrementToNonZero(), Eigen::Hyperplane< _Scalar, _AmbientDim >::intersection(), Eigen::MatrixBase< Derived >::isDiagonal(), Eigen::MatrixBase< Derived >::isIdentity(), Eigen::MatrixBase< Derived >::isUnitary(), Eigen::DenseBase< Derived >::isZero(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::default_prunning_func::operator()(), Eigen::internal::CompressedStorage< Scalar, Index >::prune(), Eigen::EigenSolver< _MatrixType >::pseudoEigenvalueMatrix(), Eigen::internal::unitOrthogonal_selector< Derived, 3 >::run(), Eigen::ComplexSchur< _MatrixType >::subdiagonalEntryIsNeglegible(), and Eigen::umeyama().
template<typename MatrixType , typename VectorType > static MatrixType::Index Eigen::internal::llt_rank_update_lower (MatrixType & mat, const VectorType & vec, const typename MatrixType::RealScalar & sigma) static
Definition at line 191 of file LLT.h.
References abs2(), apply_rotation_in_the_plane(), Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, Eigen::JacobiRotation< Scalar >::makeGivens(), real(), sqrt(), and y.
Referenced by Eigen::internal::llt_inplace< Scalar, Lower >::rankUpdate().
template<typename TriangularFactorType , typename VectorsType , typename CoeffsType > void Eigen::internal::make_block_householder_triangular_factor (TriangularFactorType & triFactor, const VectorsType & vectors, const CoeffsType & hCoeffs)
Definition at line 22 of file BlockHouseholder.h.
References eigen_assert.
Referenced by apply_block_householder_on_the_left().
void Eigen::internal::manage_caching_sizes (Action action, std::ptrdiff_t * l1 = 0, std::ptrdiff_t * l2 = 0) inline
Definition at line 28 of file GeneralBlockPanelKernel.h.
References eigen_internal_assert, Eigen::GetAction, manage_caching_sizes_helper(), queryL1CacheSize(), queryTopLevelCacheSize(), and Eigen::SetAction.
Referenced by computeProductBlockingSizes(), Eigen::initParallel(), Eigen::l1CacheSize(), Eigen::l2CacheSize(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run(), and Eigen::setCpuCacheSizes().
std::ptrdiff_t Eigen::internal::manage_caching_sizes_helper (std::ptrdiff_t a, std::ptrdiff_t b) inline
Definition at line 22 of file GeneralBlockPanelKernel.h.
Referenced by manage_caching_sizes().
void Eigen::internal::manage_multi_threading (Action action, int * v) inline
Definition at line 18 of file Parallelizer.h.
References eigen_internal_assert, EIGEN_UNUSED, Eigen::GetAction, and Eigen::SetAction.
Referenced by Eigen::initParallel(), Eigen::nbThreads(), and Eigen::setNbThreads().
template<typename Scalar , int Flags, typename Index > MappedSparseMatrix<Scalar,Flags,Index> Eigen::internal::map_superlu (SluMatrix & sluMat)
View a Super LU matrix as an Eigen expression
Definition at line 272 of file SuperLUSupport.h.
References Eigen::ColMajor, eigen_assert, Eigen::SluMatrix::innerInd, Eigen::SluMatrix::outerInd, Eigen::RowMajor, Eigen::SluMatrix::storage, and Eigen::SluMatrix::values.
template<typename Scalar , typename Index > void Eigen::internal::minimum_degree_ordering (SparseMatrix< Scalar, ColMajor, Index > & C, PermutationMatrix< Dynamic, Dynamic, Index > & perm)
Definition at line 94 of file Amd.h.
References amd_flip(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::cols(), Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::nonZeros(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr(), Eigen::PermutationBase< Derived >::resize(), Eigen::SparseMatrix< _Scalar, _Options, _Index >::resizeNonZeros(), and sqrt().
Referenced by Eigen::SimplicialCholeskyBase< Derived >::ordering().
template<typename Packet > Packet Eigen::internal::pabs (const Packet & a) inline
Definition at line 133 of file GenericPacketMath.h.
References abs().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pabs (const Packet4f & a)
Definition at line 347 of file PacketMath.h.
Referenced by Eigen::internal::scalar_abs_op< Scalar >::packetOp(), pcos< Packet4f >(), and psin< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pabs (const Packet4i & a)
Definition at line 348 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pabs (const Packet2d & a)
Definition at line 351 of file PacketMath.h.
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pacos (const Packet & a)
Definition at line 242 of file GenericPacketMath.h.
References acos().
Referenced by Eigen::internal::scalar_acos_op< Scalar >::packetOp().
template<typename Packet > Packet Eigen::internal::padd (const Packet & a, const Packet & b) inline
Definition at line 95 of file GenericPacketMath.h.
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), apply_rotation_in_the_plane(), Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd_impl(), Eigen::internal::scalar_sum_op< Scalar >::packetOp(), Eigen::internal::linspaced_op_impl< Scalar, false >::packetOp(), Eigen::internal::linspaced_op_impl< Scalar, true >::packetOp(), Eigen::internal::scalar_add_op< Scalar >::packetOp(), pcos< Packet4f >(), pexp< Packet4f >(), plog< Packet4f >(), Eigen::internal::conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >::pmadd(), Eigen::internal::conj_helper< RealScalar, std::complex< RealScalar >, false, Conj >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd(), Eigen::internal::conj_helper< Packet4f, Packet2cf, false, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmadd(), pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2d, Packet1cd, false, false >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet2d, false, false >::pmadd(), predux< Packet2cf >(), preduxp< Packet2cf >(), psin< Packet4f >(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run(), Eigen::internal::gebp_madd_selector< CJ, T, T, T, T >::run(), and Eigen::internal::product_coeff_vectorized_unroller< UnrollingIndex, Lhs, Rhs, Packet >::run().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::padd< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 268 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::padd< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 68 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::padd< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 118 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::padd< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 167 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::padd< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 168 of file PacketMath.h.
template<int Offset, typename PacketType > void Eigen::internal::palign (PacketType & first, const PacketType & second) inline
Definition at line 308 of file GenericPacketMath.h.
References Eigen::internal::palign_impl< Offset, PacketType >::run().
template<typename Packet > Packet Eigen::internal::pand (const Packet & a, const Packet & b) inline
Definition at line 137 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pand< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 292 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pand< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 92 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pand< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 187 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pand< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 244 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pand< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 245 of file PacketMath.h.
template<typename Packet > Packet Eigen::internal::pandnot (const Packet & a, const Packet & b) inline
Definition at line 149 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pandnot< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 295 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pandnot< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 95 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pandnot< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 199 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pandnot< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 253 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pandnot< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 254 of file PacketMath.h.
template<bool Condition, typename Functor , typename Index > void Eigen::internal::parallelize_gemm (const Functor & func, Index rows, Index cols, bool transpose)
Definition at line 86 of file Parallelizer.h.
References EIGEN_UNUSED_VARIABLE, info(), Eigen::initParallel(), Eigen::nbThreads(), Eigen::internal::GemmParallelInfo< Index >::rhs_length, Eigen::internal::GemmParallelInfo< Index >::rhs_start, and swap().
template<typename MatrixType , typename TranspositionType > void Eigen::internal::partial_lu_inplace (MatrixType & lu, TranspositionType & row_transpositions, typename TranspositionType::Index & nb_transpositions)
Definition at line 374 of file PartialPivLU.h.
References Eigen::ColMajor, eigen_assert, Eigen::RowMajor, and Eigen::RowMajorBit.
Referenced by Eigen::PartialPivLU< MatrixType >::compute().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pasin (const Packet & a)
Definition at line 238 of file GenericPacketMath.h.
References asin().
Referenced by Eigen::internal::scalar_asin_op< Scalar >::packetOp().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pconj (const Packet2cf & a)
Definition at line 71 of file Complex.h.
References p4ui_CONJ_XOR, and Eigen::internal::Packet2cf::v.
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), Eigen::internal::scalar_conjugate_op< Scalar >::packetOp(), Eigen::internal::conj_if< true >::pconj(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul(), and Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmul().
template<typename Packet > Packet Eigen::internal::pconj (const Packet & a) inline
Definition at line 109 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pconj (const Packet1cd & a)
Definition at line 271 of file Complex.h.
References Eigen::internal::Packet1cd::v.
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pcos (const Packet & a)
Definition at line 230 of file GenericPacketMath.h.
References cos().
Referenced by Eigen::internal::scalar_cos_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::pcos< Packet4f > (const Packet4f & _x)
Definition at line 279 of file MathFunctions.h.
References _EIGEN_DECLARE_CONST_Packet4f, _EIGEN_DECLARE_CONST_Packet4i, pabs(), padd(), pmadd(), pmul(), psub(), and y.
template<typename Packet > Packet Eigen::internal::pcplxflip (const Packet & a) inline
Definition at line 217 of file GenericPacketMath.h.
References imag(), and real().
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pcplxflip (const Packet2cf & x)
Definition at line 231 of file Complex.h.
References vec4f_swizzle1.
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc().
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pcplxflip (const Packet1cd & x)
Definition at line 427 of file Complex.h.
References preverse().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pcplxflip< Packet2cf > (const Packet2cf & x)
Definition at line 208 of file Complex.h.
References p16uc_COMPLEX_REV.
template<typename Packet > Packet Eigen::internal::pdiv (const Packet & a, const Packet & b) inline
Definition at line 118 of file GenericPacketMath.h.
Referenced by Eigen::internal::scalar_quotient_op< Scalar >::packetOp(), Eigen::internal::scalar_quotient1_op< Scalar >::packetOp(), Eigen::internal::scalar_inverse_mult_op< Scalar >::packetOp(), Eigen::internal::scalar_inverse_op< Scalar >::packetOp(), and pdiv< Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pdiv< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 419 of file Complex.h.
References pmul(), Eigen::internal::Packet1cd::v, and x1.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pdiv< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 200 of file Complex.h.
References p16uc_COMPLEX_REV, pdiv(), pmul(), and Eigen::internal::Packet2cf::v.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pdiv< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 159 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pdiv< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 213 of file PacketMath.h.
References p4f_ONE.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pdiv< Packet4i > (const Packet4i & , const Packet4i &)
Definition at line 228 of file PacketMath.h.
References eigen_assert, and pset1< Packet4i >().
template<int UpLo, typename MatrixType , int DestOrder> void Eigen::internal::permute_symm_to_fullsymm (const MatrixType & mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::Index > & _dest, const typename MatrixType::Index * perm = 0)
Definition at line 290 of file SparseSelfAdjointView.h.
References Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >::derived(), Eigen::Lower, Eigen::PlainObjectBase< Derived >::rows(), swap(), and Eigen::Upper.
template<int SrcUpLo, int DstUpLo, typename MatrixType , int DestOrder> void Eigen::internal::permute_symm_to_symm (const MatrixType & mat, SparseMatrix< typename MatrixType::Scalar, DestOrder, typename MatrixType::Index > & _dest, const typename MatrixType::Index * perm = 0)
template<int _SrcUpLo, int _DstUpLo, typename MatrixType , int DstOrder> void Eigen::internal::permute_symm_to_symm (const MatrixType & mat, SparseMatrix< typename MatrixType::Scalar, DstOrder, typename MatrixType::Index > & _dest, const typename MatrixType::Index * perm)
Definition at line 377 of file SparseSelfAdjointView.h.
References Eigen::ColMajor, Eigen::SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >::derived(), Eigen::Lower, max(), min(), Eigen::RowMajor, swap(), and Eigen::Upper.
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::pexp (const Packet & a)
Definition at line 246 of file GenericPacketMath.h.
References exp().
Referenced by Eigen::internal::scalar_exp_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::pexp< Packet4f > (const Packet4f & _x)
Definition at line 103 of file MathFunctions.h.
References _EIGEN_DECLARE_CONST_Packet4f, _EIGEN_DECLARE_CONST_Packet4i, padd(), pmadd(), pmax(), pmin(), pmul(), psub(), and y.
template<typename Packet > unpacket_traits<Packet>::type Eigen::internal::pfirst (const Packet & a) inline
Definition at line 188 of file GenericPacketMath.h.
Referenced by predux< Packet1cd >(), predux< Packet2cf >(), predux< Packet2d >(), predux< Packet4f >(), predux< Packet4i >(), predux_max< Packet2d >(), predux_max< Packet4f >(), predux_max< Packet4i >(), predux_min< Packet2d >(), predux_min< Packet4f >(), predux_min< Packet4i >(), predux_mul< Packet1cd >(), predux_mul< Packet2cf >(), predux_mul< Packet2d >(), predux_mul< Packet4f >(), and Eigen::internal::general_matrix_vector_product< Index, LhsScalar, ColMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run().
template<> EIGEN_STRONG_INLINE std::complex<double> Eigen::internal::pfirst< Packet1cd > (const Packet1cd & a)
Definition at line 313 of file Complex.h.
References EIGEN_ALIGN16.
template<> EIGEN_STRONG_INLINE std::complex< float > Eigen::internal::pfirst< Packet2cf > (const Packet2cf & a)
Definition at line 110 of file Complex.h.
References EIGEN_ALIGN16, and pstore().
template<> EIGEN_STRONG_INLINE double Eigen::internal::pfirst< Packet2d > (const Packet2d & a)
Definition at line 334 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE float Eigen::internal::pfirst< Packet4f > (const Packet4f & a)
Definition at line 341 of file PacketMath.h.
References EIGEN_ALIGN16.
template<> EIGEN_STRONG_INLINE int Eigen::internal::pfirst< Packet4i > (const Packet4i & a)
Definition at line 342 of file PacketMath.h.
References EIGEN_ALIGN16.
template<typename Packet > Packet Eigen::internal::pload (const typename unpacket_traits< Packet >::type * from) inline
Definition at line 153 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pload< Packet1cd > (const std::complex< double > * from)
Definition at line 298 of file Complex.h.
References EIGEN_DEBUG_ALIGNED_LOAD, and pload< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pload< Packet2cf > (const std::complex< float > * from)
Definition at line 97 of file Complex.h.
References EIGEN_DEBUG_ALIGNED_LOAD, and pload< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pload< Packet2d > (const double * from)
Definition at line 203 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by pload< Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pload< Packet4f > (const float * from)
Definition at line 256 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by pload< Packet2cf >(), ploaddup< Packet4f >(), and pset1< Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pload< Packet4i > (const int * from)
Definition at line 257 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by ploaddup< Packet4i >().
template<typename Packet > Packet Eigen::internal::ploaddup (const typename unpacket_traits< Packet >::type * from) inline
Definition at line 161 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::ploaddup< Packet1cd > (const std::complex< double > * from)
Definition at line 305 of file Complex.h.
References pset1< Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::ploaddup< Packet2cf > (const std::complex< float > * from)
Definition at line 100 of file Complex.h.
References pset1< Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::ploaddup< Packet2d > (const double * from)
Definition at line 283 of file PacketMath.h.
References pset1< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::ploaddup< Packet4f > (const float * from)
Definition at line 283 of file PacketMath.h.
References p16uc_DUPLICATE, pload< Packet4f >(), and ploadu< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::ploaddup< Packet4i > (const int * from)
Definition at line 290 of file PacketMath.h.
References p16uc_DUPLICATE, pload< Packet4i >(), and ploadu< Packet4i >().
template<typename Packet , int LoadMode> Packet Eigen::internal::ploadt (const typename unpacket_traits< Packet >::type * from) inline
Definition at line 278 of file GenericPacketMath.h.
References Eigen::Aligned.
template<typename Packet > Packet Eigen::internal::ploadu (const typename unpacket_traits< Packet >::type * from) inline
Definition at line 157 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::ploadu< Packet1cd > (const std::complex< double > * from)
Definition at line 300 of file Complex.h.
References EIGEN_DEBUG_UNALIGNED_LOAD, and ploadu< Packet2d >().
Referenced by pset1< Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::ploadu< Packet2cf > (const std::complex< float > * from)
Definition at line 98 of file Complex.h.
References EIGEN_DEBUG_UNALIGNED_LOAD, and ploadu< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::ploadu< Packet2d > (const double * from)
Definition at line 253 of file PacketMath.h.
References EIGEN_DEBUG_UNALIGNED_LOAD.
Referenced by ploadu< Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::ploadu< Packet4f > (const float * from)
Definition at line 259 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by ploaddup< Packet4f >(), ploadu< Packet2cf >(), and pset1< Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::ploadu< Packet4i > (const int * from)
Definition at line 271 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_LOAD.
Referenced by ploaddup< Packet4i >().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::plog (const Packet & a)
Definition at line 250 of file GenericPacketMath.h.
References log().
Referenced by Eigen::internal::scalar_log_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::plog< Packet4f > (const Packet4f & _x)
Definition at line 23 of file MathFunctions.h.
References _EIGEN_DECLARE_CONST_Packet4f, _EIGEN_DECLARE_CONST_Packet4f_FROM_INT, _EIGEN_DECLARE_CONST_Packet4i, padd(), pmadd(), pmax(), pmul(), psub(), x2, and y.
template<typename Scalar > packet_traits<Scalar>::type Eigen::internal::plset (const Scalar & a) inline
Definition at line 169 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::plset< double > (const double & a)
Definition at line 114 of file PacketMath.h.
References pset1< Packet2d >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::plset< float > (const float & a)
Definition at line 164 of file PacketMath.h.
References p4f_COUNTDOWN, and pset1< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::plset< int > (const int & a)
Definition at line 165 of file PacketMath.h.
References p4i_COUNTDOWN, and pset1< Packet4i >().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmadd (const Packet4f & a, const Packet4f & b, const Packet4f & c)
Definition at line 234 of file PacketMath.h.
Referenced by Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::acc(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), pcos< Packet4f >(), pexp< Packet4f >(), plog< Packet4f >(), Eigen::internal::conj_helper< Scalar, Scalar, false, false >::pmadd(), psin< Packet4f >(), Eigen::internal::product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), and Eigen::internal::product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmadd (const Packet4i & a, const Packet4i & b, const Packet4i & c)
Definition at line 235 of file PacketMath.h.
References padd(), and pmul().
template<typename Packet > Packet Eigen::internal::pmadd (const Packet & a, const Packet & b, const Packet & c) inline
Definition at line 270 of file GenericPacketMath.h.
References padd(), and pmul().
template<typename Packet > Packet Eigen::internal::pmax (const Packet & a, const Packet & b) inline
Definition at line 128 of file GenericPacketMath.h.
References max().
Referenced by Eigen::internal::scalar_max_op< Scalar >::packetOp(), pexp< Packet4f >(), and plog< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pmax< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 178 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmax< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 240 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmax< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 241 of file PacketMath.h.
template<typename Packet > Packet Eigen::internal::pmin (const Packet & a, const Packet & b) inline
Definition at line 123 of file GenericPacketMath.h.
References min().
Referenced by Eigen::internal::scalar_min_op< Scalar >::packetOp(), and pexp< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pmin< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 169 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmin< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 237 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmin< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 238 of file PacketMath.h.
template<typename Packet > Packet Eigen::internal::pmul (const Packet & a, const Packet & b) inline
Definition at line 113 of file GenericPacketMath.h.
Referenced by apply_rotation_in_the_plane(), Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, _ConjLhs, false >::madd_impl(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, _ConjRhs >::madd_impl(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::operator()(), Eigen::DiagonalProduct< MatrixType, DiagonalType, ProductOrder >::packet_impl(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_abs2_op< Scalar >::packetOp(), Eigen::internal::scalar_multiple_op< Scalar >::packetOp(), Eigen::internal::linspaced_op_impl< Scalar, true >::packetOp(), Eigen::internal::scalar_square_op< Scalar >::packetOp(), Eigen::internal::scalar_cube_op< Scalar >::packetOp(), pcos< Packet4f >(), pdiv< Packet1cd >(), pdiv< Packet2cf >(), pexp< Packet4f >(), plog< Packet4f >(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, false, true >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, true >::pmadd(), Eigen::internal::conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >::pmadd(), Eigen::internal::conj_helper< RealScalar, std::complex< RealScalar >, false, Conj >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmadd(), Eigen::internal::conj_helper< Packet4f, Packet2cf, false, false >::pmadd(), Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmadd(), pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmadd(), Eigen::internal::conj_helper< Packet2d, Packet1cd, false, false >::pmadd(), Eigen::internal::conj_helper< Packet1cd, Packet2d, false, false >::pmadd(), Eigen::internal::conj_helper< Scalar, Scalar, false, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, false, true >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet2cf, true, true >::pmul(), Eigen::internal::conj_helper< Packet4f, Packet2cf, false, false >::pmul(), Eigen::internal::conj_helper< Packet2cf, Packet4f, false, false >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, false >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet1cd, true, true >::pmul(), Eigen::internal::conj_helper< Packet2d, Packet1cd, false, false >::pmul(), Eigen::internal::conj_helper< Packet1cd, Packet2d, false, false >::pmul(), predux_mul< Packet2cf >(), predux_mul< Packet4f >(), psin< Packet4f >(), psqrt< Packet4f >(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run(), Eigen::internal::product_coeff_vectorized_unroller< UnrollingIndex, Lhs, Rhs, Packet >::run(), Eigen::internal::product_coeff_vectorized_unroller< 0, Lhs, Rhs, Packet >::run(), Eigen::internal::product_packet_impl< RowMajor, 0, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::product_packet_impl< ColMajor, 0, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), and Eigen::internal::product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run().
template<> std::complex<float> Eigen::internal::pmul (const std::complex< float > & a, const std::complex< float > & b) inline
Definition at line 317 of file GenericPacketMath.h.
References imag(), and real().
template<> std::complex<double> Eigen::internal::pmul (const std::complex< double > & a, const std::complex< double > & b) inline
Definition at line 320 of file GenericPacketMath.h.
References imag(), and real().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pmul< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 277 of file Complex.h.
References vec2d_swizzle1.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pmul< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 73 of file Complex.h.
References p16uc_COMPLEX_IM, p16uc_COMPLEX_RE, p16uc_COMPLEX_REV, and p4ui_CONJ_XOR.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pmul< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 141 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pmul< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 176 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pmul< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 119 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pnegate (const Packet2cf & a)
Definition at line 70 of file Complex.h.
References Eigen::internal::Packet2cf::v.
Referenced by Eigen::internal::scalar_opposite_op< Scalar >::packetOp(), and pnegate().
template<typename Packet > Packet Eigen::internal::pnegate (const Packet & a) inline
Definition at line 105 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pnegate (const Packet2d & a)
Definition at line 130 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pnegate (const Packet4f & a)
Definition at line 173 of file PacketMath.h.
References psub< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pnegate (const Packet4i & a)
Definition at line 174 of file PacketMath.h.
References psub< Packet4i >().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pnegate (const Packet1cd & a)
Definition at line 270 of file Complex.h.
References pnegate(), and Eigen::internal::Packet1cd::v.
template<typename Packet > Packet Eigen::internal::por (const Packet & a, const Packet & b) inline
Definition at line 141 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::por< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 293 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::por< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 93 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::por< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 191 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::por< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 247 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::por< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 248 of file PacketMath.h.
template<typename Packet > unpacket_traits<Packet>::type Eigen::internal::predux (const Packet & a) inline
Definition at line 196 of file GenericPacketMath.h.
Referenced by Eigen::internal::scalar_sum_op< Scalar >::predux(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn >::run(), Eigen::internal::product_coeff_impl< InnerVectorizedTraversal, UnrollingIndex, Lhs, Rhs, RetScalar >::run(), and Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run().
template<> EIGEN_STRONG_INLINE std::complex<double> Eigen::internal::predux< Packet1cd > (const Packet1cd & a)
Definition at line 322 of file Complex.h.
References pfirst().
template<> EIGEN_STRONG_INLINE std::complex< float > Eigen::internal::predux< Packet2cf > (const Packet2cf & a)
Definition at line 125 of file Complex.h.
References padd(), and pfirst().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux< Packet2d > (const Packet2d & a)
Definition at line 411 of file PacketMath.h.
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux< Packet4f > (const Packet4f & a)
Definition at line 350 of file PacketMath.h.
References pfirst().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux< Packet4i > (const Packet4i & a)
Definition at line 388 of file PacketMath.h.
References pfirst().
template<typename Packet > unpacket_traits<Packet>::type Eigen::internal::predux_max (const Packet & a) inline
Definition at line 208 of file GenericPacketMath.h.
Referenced by Eigen::internal::scalar_max_op< Scalar >::predux().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_max< Packet2d > (const Packet2d & a)
Definition at line 505 of file PacketMath.h.
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_max< Packet4f > (const Packet4f & a)
Definition at line 458 of file PacketMath.h.
References pfirst().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux_max< Packet4i > (const Packet4i & a)
Definition at line 466 of file PacketMath.h.
References pfirst().
template<typename Packet > unpacket_traits<Packet>::type Eigen::internal::predux_min (const Packet & a) inline
Definition at line 204 of file GenericPacketMath.h.
Referenced by Eigen::internal::scalar_min_op< Scalar >::predux().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_min< Packet2d > (const Packet2d & a)
Definition at line 484 of file PacketMath.h.
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_min< Packet4f > (const Packet4f & a)
Definition at line 441 of file PacketMath.h.
References pfirst().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux_min< Packet4i > (const Packet4i & a)
Definition at line 449 of file PacketMath.h.
References pfirst().
template<typename Packet > unpacket_traits<Packet>::type Eigen::internal::predux_mul (const Packet & a) inline
Definition at line 200 of file GenericPacketMath.h.
Referenced by Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::predux().
template<> EIGEN_STRONG_INLINE std::complex<double> Eigen::internal::predux_mul< Packet1cd > (const Packet1cd & a)
Definition at line 332 of file Complex.h.
References pfirst().
template<> EIGEN_STRONG_INLINE std::complex< float > Eigen::internal::predux_mul< Packet2cf > (const Packet2cf & a)
Definition at line 145 of file Complex.h.
References pfirst(), and pmul().
template<> EIGEN_STRONG_INLINE double Eigen::internal::predux_mul< Packet2d > (const Packet2d & a)
Definition at line 464 of file PacketMath.h.
References pfirst().
template<> EIGEN_STRONG_INLINE float Eigen::internal::predux_mul< Packet4f > (const Packet4f & a)
Definition at line 426 of file PacketMath.h.
References pfirst(), and pmul().
template<> EIGEN_STRONG_INLINE int Eigen::internal::predux_mul< Packet4i > (const Packet4i & a)
Definition at line 433 of file PacketMath.h.
References EIGEN_ALIGN16, and pstore().
template<typename Packet > Packet Eigen::internal::preduxp (const Packet * vecs) inline
Definition at line 193 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::preduxp< Packet1cd > (const Packet1cd * vecs)
Definition at line 327 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::preduxp< Packet2cf > (const Packet2cf * vecs)
Definition at line 133 of file Complex.h.
References padd().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::preduxp< Packet2d > (const Packet2d * vecs)
Definition at line 430 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::preduxp< Packet4f > (const Packet4f * vecs)
Definition at line 360 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::preduxp< Packet4i > (const Packet4i * vecs)
Definition at line 396 of file PacketMath.h.
template<typename Scalar > void Eigen::internal::prefetch (const Scalar * addr) inline
Definition at line 180 of file GenericPacketMath.h.
Referenced by Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::operator()().
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< double > (const double * addr)
Definition at line 318 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< float > (const float * addr)
Definition at line 338 of file PacketMath.h.
References DST_CHAN, and DST_CTRL.
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< int > (const int * addr)
Definition at line 339 of file PacketMath.h.
References DST_CHAN, and DST_CTRL.
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< std::complex< double > > (const std::complex< double > * addr)
Definition at line 311 of file Complex.h.
template<> EIGEN_STRONG_INLINE void Eigen::internal::prefetch< std::complex< float > > (const std::complex< float > * addr)
Definition at line 108 of file Complex.h.
References DST_CHAN, and DST_CTRL.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::preverse (const Packet2cf & a)
Definition at line 118 of file Complex.h.
References p16uc_COMPLEX_REV2, and Eigen::internal::Packet2cf::v.
Referenced by Eigen::Reverse< MatrixType, Direction >::packet(), pcplxflip(), Eigen::internal::reverse_packet_cond< PacketScalar, ReversePacket >::run(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run(), and Eigen::Reverse< MatrixType, Direction >::writePacket().
template<typename Packet > Packet Eigen::internal::preverse (const Packet & a) inline
Definition at line 212 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::preverse (const Packet1cd & a)
Definition at line 320 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::preverse (const Packet2d & a)
Definition at line 340 of file PacketMath.h.
References x1.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::preverse (const Packet4f & a)
Definition at line 344 of file PacketMath.h.
References p16uc_REVERSE.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::preverse (const Packet4i & a)
Definition at line 345 of file PacketMath.h.
References p16uc_REVERSE.
template<typename Derived > std::ostream & Eigen::internal::print_matrix (std::ostream & s, const Derived & _m, const IOFormat & fmt)
Definition at line 153 of file IO.h.
References Eigen::IOFormat::coeffSeparator, Eigen::DontAlignCols, Eigen::IOFormat::flags, Eigen::FullPrecision, Eigen::IOFormat::matPrefix, Eigen::IOFormat::matSuffix, Eigen::IOFormat::precision, Eigen::IOFormat::rowPrefix, Eigen::IOFormat::rowSeparator, Eigen::IOFormat::rowSpacer, Eigen::IOFormat::rowSuffix, Eigen::internal::significant_decimals_default_impl< Scalar, NumTraits< Scalar >::IsInteger >::run(), and Eigen::StreamPrecision.
Referenced by Eigen::DenseBase< Derived >::operator<<().
template<typename Packet > Packet Eigen::internal::pset1 (const typename unpacket_traits< Packet >::type & a) inline
Definition at line 165 of file GenericPacketMath.h.
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pset1< Packet1cd > (const std::complex< double > & from)
Definition at line 302 of file Complex.h.
References ploadu< Packet1cd >().
Referenced by ploaddup< Packet1cd >().
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pset1< Packet2cf > (const std::complex< float > & from)
Definition at line 56 of file Complex.h.
References p16uc_PSET_HI, pload< Packet4f >(), ploadu< Packet4f >(), and Eigen::internal::Packet2cf::v.
Referenced by ploaddup< Packet2cf >().
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pset1< Packet2d > (const double & from)
Definition at line 109 of file PacketMath.h.
Referenced by ploaddup< Packet2d >(), plset< double >(), and Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run().
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pset1< Packet4f > (const float & from)
Definition at line 147 of file PacketMath.h.
References EIGEN_ALIGN16.
Referenced by plset< float >(), and psqrt< Packet4f >().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pset1< Packet4i > (const int & from)
Definition at line 156 of file PacketMath.h.
References EIGEN_ALIGN16.
Referenced by pdiv< Packet4i >(), and plset< int >().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::psin (const Packet & a)
Definition at line 226 of file GenericPacketMath.h.
References sin().
Referenced by Eigen::internal::scalar_sin_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::psin< Packet4f > (const Packet4f & _x)
Definition at line 178 of file MathFunctions.h.
References _EIGEN_DECLARE_CONST_Packet4f, _EIGEN_DECLARE_CONST_Packet4f_FROM_INT, _EIGEN_DECLARE_CONST_Packet4i, pabs(), padd(), pmadd(), pmul(), psub(), and y.
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::psqrt (const Packet & a)
Definition at line 254 of file GenericPacketMath.h.
References sqrt().
Referenced by Eigen::internal::scalar_sqrt_op< Scalar >::packetOp().
template<> EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS EIGEN_UNUSED Packet4f Eigen::internal::psqrt< Packet4f > (const Packet4f & _x)
Definition at line 368 of file MathFunctions.h.
References pmul(), pset1< Packet4f >(), and psub().
template<typename Scalar , typename Packet > void Eigen::internal::pstore (Scalar * to, const Packet & from) inline
Definition at line 172 of file GenericPacketMath.h.
Referenced by apply_rotation_in_the_plane(), Eigen::internal::gemm_pack_lhs< Scalar, Index, Pack1, Pack2, StorageOrder, Conjugate, PanelMode >::operator()(), pfirst< Packet2cf >(), predux_mul< Packet4i >(), pstore1(), pstore1< Packet2d >(), pstore1< Packet4f >(), pstore< std::complex< double > >(), pstore< std::complex< float > >(), pstoret(), Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, float, Aligned >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn >::run(), Eigen::internal::cross3_impl< Architecture::SSE, VectorLhs, VectorRhs, float, true >::run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, ColMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run(), and Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run().
template<typename Packet > void Eigen::internal::pstore1 (typename unpacket_traits< Packet >::type * to, const typename unpacket_traits< Packet >::type & a) inline
Definition at line 263 of file GenericPacketMath.h.
References pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet2d > (double * to, const double & a)
Definition at line 311 of file PacketMath.h.
References pstore(), and vec2d_swizzle1.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore1< Packet4f > (float * to, const float & a)
Definition at line 305 of file PacketMath.h.
References pstore(), and vec4f_swizzle1.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< double > (double * to, const Packet2d & from)
Definition at line 293 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< float > (float * to, const Packet4f & from)
Definition at line 298 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< int > (int * to, const Packet4i & from)
Definition at line 299 of file PacketMath.h.
References EIGEN_DEBUG_ALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< std::complex< double > > (std::complex< double > * to, const Packet1cd & from)
Definition at line 308 of file Complex.h.
References EIGEN_DEBUG_ALIGNED_STORE, and pstore().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstore< std::complex< float > > (std::complex< float > * to, const Packet2cf & from)
Definition at line 105 of file Complex.h.
References EIGEN_DEBUG_ALIGNED_STORE, and pstore().
template<typename Scalar , typename Packet , int LoadMode> void Eigen::internal::pstoret (Scalar * to, const Packet & from) inline
Definition at line 289 of file GenericPacketMath.h.
References Eigen::Aligned, pstore(), and pstoreu().
template<typename Scalar , typename Packet > void Eigen::internal::pstoreu (Scalar * to, const Packet & from) inline
Definition at line 176 of file GenericPacketMath.h.
Referenced by apply_rotation_in_the_plane(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), pstoret(), pstoreu< std::complex< double > >(), and pstoreu< std::complex< float > >().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< double > (double * to, const Packet2d & from)
Definition at line 296 of file PacketMath.h.
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< float > (float * to, const Packet4f & from)
Definition at line 301 of file PacketMath.h.
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< int > (int * to, const Packet4i & from)
Definition at line 319 of file PacketMath.h.
References EIGEN_DEBUG_UNALIGNED_STORE.
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< std::complex< double > > (std::complex< double > * to, const Packet1cd & from)
Definition at line 309 of file Complex.h.
References EIGEN_DEBUG_UNALIGNED_STORE, and pstoreu().
template<> EIGEN_STRONG_INLINE void Eigen::internal::pstoreu< std::complex< float > > (std::complex< float > * to, const Packet2cf & from)
Definition at line 106 of file Complex.h.
References EIGEN_DEBUG_UNALIGNED_STORE, and pstoreu().
template<typename Packet > Packet Eigen::internal::psub (const Packet & a, const Packet & b) inline
Definition at line 100 of file GenericPacketMath.h.
Referenced by Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, _ConjLhs, _ConjRhs >::acc(), apply_rotation_in_the_plane(), Eigen::internal::scalar_difference_op< Scalar >::packetOp(), pcos< Packet4f >(), pexp< Packet4f >(), plog< Packet4f >(), psin< Packet4f >(), psqrt< Packet4f >(), and Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::psub< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 269 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::psub< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 69 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::psub< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 122 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::psub< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 170 of file PacketMath.h.
Referenced by pnegate().
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::psub< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 171 of file PacketMath.h.
Referenced by pnegate().
template<typename Packet > EIGEN_DECLARE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::ptan (const Packet & a)
Definition at line 234 of file GenericPacketMath.h.
References tan().
Referenced by Eigen::internal::scalar_tan_op< Scalar >::packetOp().
EIGEN_STRONG_INLINE void Eigen::internal::punpackp (Packet4f * vecs)
Definition at line 366 of file PacketMath.h.
template<typename Packet > Packet Eigen::internal::pxor (const Packet & a, const Packet & b) inline
Definition at line 145 of file GenericPacketMath.h.
Referenced by Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run().
template<> EIGEN_STRONG_INLINE Packet1cd Eigen::internal::pxor< Packet1cd > (const Packet1cd & a, const Packet1cd & b)
Definition at line 294 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2cf Eigen::internal::pxor< Packet2cf > (const Packet2cf & a, const Packet2cf & b)
Definition at line 94 of file Complex.h.
template<> EIGEN_STRONG_INLINE Packet2d Eigen::internal::pxor< Packet2d > (const Packet2d & a, const Packet2d & b)
Definition at line 195 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4f Eigen::internal::pxor< Packet4f > (const Packet4f & a, const Packet4f & b)
Definition at line 250 of file PacketMath.h.
template<> EIGEN_STRONG_INLINE Packet4i Eigen::internal::pxor< Packet4i > (const Packet4i & a, const Packet4i & b)
Definition at line 251 of file PacketMath.h.
void Eigen::internal::queryCacheSizes (int & l1, int & l2, int & l3) inline
Definition at line 898 of file Memory.h.
Referenced by queryL1CacheSize(), and queryTopLevelCacheSize().
int Eigen::internal::queryL1CacheSize () inline
Definition at line 932 of file Memory.h.
References queryCacheSizes().
Referenced by manage_caching_sizes().
int Eigen::internal::queryTopLevelCacheSize () inline
Definition at line 941 of file Memory.h.
References max(), and queryCacheSizes().
Referenced by manage_caching_sizes().
template<typename MatrixType , typename RealScalar , typename Index > void Eigen::internal::real_2x2_jacobi_svd (const MatrixType & matrix, Index p, Index q, JacobiRotation< RealScalar > * j_left, JacobiRotation< RealScalar > * j_right)
Definition at line 397 of file JacobiSVD.h.
References abs2(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::JacobiRotation< Scalar >::makeJacobi(), real(), sqrt(), and Eigen::JacobiRotation< Scalar >::transpose().
Referenced by Eigen::JacobiSVD< MatrixType, QRPreconditioner >::compute().
template<typename Scalar > add_const_on_value_type< EIGEN_MATHFUNC_RETVAL(real_ref, Scalar) >::type Eigen::internal::real_ref (const Scalar & x) inline
Definition at line 155 of file MathFunctions.h.
References Eigen::internal::real_ref_impl< Scalar >::run().
Referenced by Eigen::ComplexEigenSolver< _MatrixType >::doComputeEigenvectors(), EIGEN_MATHFUNC_RETVAL(), Eigen::internal::scalar_real_ref_op< Scalar >::operator()(), Eigen::umfpack_get_determinant(), Eigen::umfpack_get_numeric(), Eigen::umfpack_numeric(), Eigen::umfpack_solve(), and Eigen::umfpack_symbolic().
template<typename InputIterator , typename SparseMatrixType > void Eigen::internal::set_from_triplets (const InputIterator & begin, const InputIterator & end, SparseMatrixType & mat, int Options = 0)
Definition at line 1019 of file SparseMatrix.h.
References EIGEN_UNUSED_VARIABLE, and Eigen::SparseMatrix< _Scalar, _Options, _Index >::setZero().
Referenced by Eigen::SparseMatrix< _Scalar, _Options, _Index >::setFromTriplets().
template<typename T > void Eigen::internal::smart_copy (const T * start, const T * end, T * target)
Definition at line 478 of file Memory.h.
Referenced by Eigen::internal::CompressedStorage< Scalar, Index >::reallocate().
template<typename Lhs , typename Rhs , typename ResultType > static void Eigen::internal::sparse_sparse_product_with_pruning_impl (const Lhs & lhs, const Rhs & rhs, ResultType & res, typename ResultType::RealScalar tolerance) static
Definition at line 20 of file SparseSparseProductWithPruning.h.
References eigen_assert.
template<typename SparseLhsType , typename DenseRhsType , typename DenseResType , typename AlphaType > void Eigen::internal::sparse_time_dense_product (const SparseLhsType & lhs, const DenseRhsType & rhs, DenseResType & res, const AlphaType & alpha) inline
Definition at line 230 of file SparseDenseProduct.h.
Referenced by Eigen::SparseTimeDenseProduct< Lhs, Rhs >::scaleAndAddTo(), and Eigen::DenseTimeSparseProduct< Lhs, Rhs >::scaleAndAddTo().
template<typename ExpressionType , typename Scalar > void Eigen::internal::stable_norm_kernel (const ExpressionType & bl, Scalar & ssq, Scalar & scale, Scalar & invScale) inline
Definition at line 17 of file StableNorm.h.
References abs2(), and max().
Referenced by Eigen::MatrixBase< Derived >::stableNorm().
void Eigen::internal::throw_std_bad_alloc () inline
Definition at line 72 of file Memory.h.
Referenced by aligned_malloc(), aligned_realloc(), check_rows_cols_for_overflow(), check_size_for_overflow(), and conditional_aligned_malloc< false >().
template<typename Scalar , int Dim> static Matrix<Scalar,2,2> Eigen::internal::toRotationMatrix (const Scalar & s) inline static
Definition at line 182 of file RotationBase.h.
References EIGEN_STATIC_ASSERT, and toRotationMatrix().
template<typename Scalar , int Dim, typename OtherDerived > static Matrix<Scalar,Dim,Dim> Eigen::internal::toRotationMatrix (const RotationBase< OtherDerived, Dim > & r) inline static
Definition at line 189 of file RotationBase.h.
References Eigen::RotationBase< Derived, _Dim >::toRotationMatrix().
template<typename Scalar , int Dim, typename OtherDerived > static const MatrixBase<OtherDerived>& Eigen::internal::toRotationMatrix (const MatrixBase< OtherDerived > & mat) inline static
Definition at line 195 of file RotationBase.h.
References EIGEN_STATIC_ASSERT.
Referenced by Eigen::ei_toRotationMatrix(), and toRotationMatrix().
template<int StorageOrder, typename RealScalar , typename Scalar , typename Index > static void Eigen::internal::tridiagonal_qr_step (RealScalar * diag, RealScalar * subdiag, Index start, Index end, Scalar * matrixQ, Index n) static
Definition at line 737 of file SelfAdjointEigenSolver.h.
References abs(), abs2(), Eigen::JacobiRotation< Scalar >::c(), Eigen::JacobiRotation< Scalar >::makeGivens(), and Eigen::JacobiRotation< Scalar >::s().
template<typename MatrixType , typename CoeffVectorType > void Eigen::internal::tridiagonalization_inplace (MatrixType & matA, CoeffVectorType & hCoeffs)
Definition at line 346 of file Tridiagonalization.h.
References eigen_assert.
Referenced by Eigen::Tridiagonalization< _MatrixType >::compute(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run(), and Eigen::Tridiagonalization< _MatrixType >::Tridiagonalization().
template<typename MatrixType , typename DiagonalType , typename SubDiagonalType > void Eigen::internal::tridiagonalization_inplace (MatrixType & mat, DiagonalType & diag, SubDiagonalType & subdiag, bool extractQ)
Performs a full tridiagonalization in place.
Parameters
[in,out] mat On input, the selfadjoint matrix whose tridiagonal decomposition is to be computed. Only the lower triangular part referenced. The rest is left unchanged. On output, the orthogonal matrix Q in the decomposition if extractQ is true.
[out] diag The diagonal of the tridiagonal matrix T in the decomposition.
[out] subdiag The subdiagonal of the tridiagonal matrix T in the decomposition.
[in] extractQ If true, the orthogonal matrix Q in the decomposition is computed and stored in mat.
Computes the tridiagonal decomposition of the selfadjoint matrix mat in place such that where is unitary and a real symmetric tridiagonal matrix.
The tridiagonal matrix T is passed to the output parameters diag and subdiag. If extractQ is true, then the orthogonal matrix Q is passed to mat. Otherwise the lower part of the matrix mat is destroyed.
The vectors diag and subdiag are not resized. The function assumes that they are already of the correct size. The length of the vector diag should equal the number of rows in mat, and the length of the vector subdiag should be one left.
This implementation contains an optimized path for 3-by-3 matrices which is especially useful for plane fitting.
Note
Currently, it requires two temporary vectors to hold the intermediate Householder coefficients, and to reconstruct the matrix Q from the Householder reflectors.
Example (this uses the same matrix as the example in Tridiagonalization::Tridiagonalization(const MatrixType&)):
Output:
See Also
class Tridiagonalization
Definition at line 426 of file Tridiagonalization.h.
References eigen_assert, and Eigen::internal::tridiagonalization_inplace_selector< MatrixType, Size, IsComplex >::run().
Variable Documentation
Packet16uc Eigen::internal::p16uc_COMPLEX_IM = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 1), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 3), 8) static
Definition at line 19 of file Complex.h.
Referenced by pmul< Packet2cf >().
Packet16uc Eigen::internal::p16uc_COMPLEX_RE = vec_sld((Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet16uc) vec_splat((Packet4ui)p16uc_FORWARD, 2), 8) static
Definition at line 18 of file Complex.h.
Referenced by pmul< Packet2cf >().
Packet16uc Eigen::internal::p16uc_COMPLEX_REV = vec_sld(p16uc_REVERSE, p16uc_REVERSE, 8) static
Definition at line 20 of file Complex.h.
Referenced by pcplxflip< Packet2cf >(), pdiv< Packet2cf >(), and pmul< Packet2cf >().
Packet16uc Eigen::internal::p16uc_COMPLEX_REV2 = vec_sld(p16uc_FORWARD, p16uc_FORWARD, 8) static
Definition at line 21 of file Complex.h.
Referenced by preverse().
Packet16uc Eigen::internal::p16uc_DUPLICATE = {0,1,2,3, 0,1,2,3, 4,5,6,7, 4,5,6,7} static
Definition at line 63 of file PacketMath.h.
Referenced by ploaddup< Packet4f >(), and ploaddup< Packet4i >().
Packet16uc Eigen::internal::p16uc_FORWARD = vec_lvsl(0, (float*)0) static
Definition at line 62 of file PacketMath.h.
Packet16uc Eigen::internal::p16uc_PSET_HI = (Packet16uc) vec_mergeh((Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 0), (Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 1)) static
Definition at line 22 of file Complex.h.
Referenced by pset1< Packet2cf >().
Packet16uc Eigen::internal::p16uc_PSET_LO = (Packet16uc) vec_mergeh((Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 2), (Packet4ui) vec_splat((Packet4ui)p16uc_FORWARD, 3)) static
Definition at line 23 of file Complex.h.
Packet16uc Eigen::internal::p16uc_REVERSE = {12,13,14,15, 8,9,10,11, 4,5,6,7, 0,1,2,3} static
Definition at line 61 of file PacketMath.h.
Referenced by preverse().
uint32x2_t Eigen::internal::p2ui_CONJ_XOR = EIGEN_INIT_NEON_PACKET2(0x00000000, 0x80000000) static
Definition at line 18 of file Complex.h.
Packet4f Eigen::internal::p4f_COUNTDOWN = { 3.0, 2.0, 1.0, 0.0 } static
Definition at line 59 of file PacketMath.h.
Referenced by plset< float >().
Packet4f Eigen::internal::p4f_ONE = vec_ctf(p4i_ONE, 0) static
Definition at line 70 of file PacketMath.h.
Referenced by pdiv< Packet4f >().
Packet4f Eigen::internal::p4f_ZERO_ = (Packet4f) vec_sl((Packet4ui)p4i_MINUS1, (Packet4ui)p4i_MINUS1) static
Definition at line 71 of file PacketMath.h.
Packet4i Eigen::internal::p4i_COUNTDOWN = { 3, 2, 1, 0 } static
Definition at line 60 of file PacketMath.h.
Referenced by plset< int >().
uint32x4_t Eigen::internal::p4ui_CONJ_XOR = EIGEN_INIT_NEON_PACKET4(0x00000000, 0x80000000, 0x00000000, 0x80000000) static
Definition at line 17 of file Complex.h.
Packet4ui Eigen::internal::p4ui_CONJ_XOR = vec_mergeh((Packet4ui)p4i_ZERO, (Packet4ui)p4f_ZERO_) static
Definition at line 17 of file Complex.h.
Referenced by pconj(), and pmul< Packet2cf >().
const Scalar & Eigen::internal::y
Initial value:
{
  return EIGEN_MATHFUNC_IMPL(hypot, Scalar)::run(x, y)
Definition at line 382 of file MathFunctions.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_init2(), apply_rotation_in_the_plane(), Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheRight(), Eigen::Array< Index, 64, 1, DontAlign >::Array(), bicgstab(), boxMullerGenerator(), Eigen::QuaternionBase< Derived >::conjugate(), Eigen::Quaternion< _Scalar >::conjugate(), conservative_sparse_sparse_product_impl(), Eigen::EigenSolver< _MatrixType >::doComputeEigenvectors(), TVAcc::estimateAandCUnthreaded(), TVAcc::estimateWUbmWeightUnThreaded(), TVAcc::estimateWUnThreaded(), JFAAcc::estimateYandVUnThreaded(), JFAAcc::estimateYUnThreaded(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), TVAcc::getTW(), JFAAcc::getVY(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, true >::isApprox(), Eigen::internal::scalar_fuzzy_impl< bool >::isApprox(), Eigen::internal::scalar_fuzzy_default_impl< Scalar, false, true >::isApproxOrLessThan(), Eigen::internal::scalar_fuzzy_impl< bool >::isApproxOrLessThan(), isMuchSmallerThan(), Kernel::k_function(), llt_rank_update_lower(), Eigen::Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), max(), min(), pcos< Packet4f >(), pexp< Packet4f >(), plog< Packet4f >(), Eigen::internal::conj_helper< std::complex< RealScalar >, RealScalar, Conj, false >::pmul(), psin< Packet4f >(), solve_c_svc(), solve_epsilon_svr(), solve_nu_svc(), solve_nu_svr(), svd_readBinFloat(), svd_writeBinFloat(), svd_writeBinInt(), swap(), Eigen::QuaternionBase< Derived >::toRotationMatrix(), and Eigen::Quaternion< _Scalar >::toRotationMatrix().