LIA_RAL: std Namespace Reference
std Namespace Reference
Classes
class deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >
class list< T, EIGEN_ALIGNED_ALLOCATOR< T > >
class vector< T, EIGEN_ALIGNED_ALLOCATOR< T > >
Functions
template<typename Derived >
const Eigen::CwiseUnaryOp
< Eigen::internal::scalar_pow_op
< typename Derived::Scalar >
, const Derived > pow (const Eigen::ArrayBase< Derived > &x, const typename Derived::Scalar &exponent)
template<typename Derived >
const Eigen::CwiseBinaryOp
< Eigen::internal::scalar_binary_pow_op
< typename Derived::Scalar,
typename Derived::Scalar >
, const Derived, const Derived > pow (const Eigen::ArrayBase< Derived > &x, const Eigen::ArrayBase< Derived > &exponents)
Function Documentation
template<typename Derived > const Eigen::CwiseUnaryOp<Eigen::internal::scalar_pow_op<typename Derived::Scalar>, const Derived> std::pow (const Eigen::ArrayBase< Derived > & x, const typename Derived::Scalar & exponent) inline
Definition at line 54 of file GlobalFunctions.h.
References Eigen::ArrayBase< Derived >::pow().
Referenced by Eigen::MatrixBase< Derived >::blueNorm(), and Eigen::internal::pow_default_impl< Scalar, NumTraits< Scalar >::IsInteger >::run().
template<typename Derived > const Eigen::CwiseBinaryOp<Eigen::internal::scalar_binary_pow_op<typename Derived::Scalar, typename Derived::Scalar>, const Derived, const Derived> std::pow (const Eigen::ArrayBase< Derived > & x, const Eigen::ArrayBase< Derived > & exponents) inline
Definition at line 60 of file GlobalFunctions.h.