LIA_RAL: LIA_SpkDet/NormFeat/src/NormFeat.cpp File Reference
NormFeat.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "NormFeat.h"
#include "AccumulateJFAStat.h"
Macros
#define ALIZE_NormFeat_cpp
Functions
void displayStats (FrameAccGD &frameAccu, FeatureServer &fs, ostream &out, Config &config)
void loadStatsFromFile (String filename, DoubleVector &extMean, DoubleVector &extCov)
bool emptyWindow (SegCluster &window)
Seg * firstSeg (SegCluster &window)
Seg * lastSeg (SegCluster &window)
double windowLength (SegCluster &window, double frameLength)
bool inWindow (Seg &seg, SegCluster &window, double windowDuration, double frameLength)
void suppressFirst (SegCluster &window)
void moveWindow (SegCluster &window, Seg &seg, Seg *&currentSeg, double duration, double frameLength)
void computeWindowParam (Config &config, const DoubleVector &gMean, const DoubleVector &gCov, FeatureServer &fs, SegCluster &window, double windowDuration, double windowComp, double frameLength, DoubleVector &mean, DoubleVector &cov)
bool inMiddle (Seg *&currentSeg, SegCluster &window, double windowDuration, double frameLength)
bool nextSeg (Seg *&currentSeg, SegCluster &window)
void getUbmOffset (RealVector< double > &ubm_offset, Matrix< double > &U, MixtureGD &world, Config &config)
void removeOffsetOnFrame (RealVector< double > &occ, Feature &f, RealVector< double > &ubm_offset, unsigned long nbDistrib)
void featureChannelCompNAP (RealVector< double > &ubm_offset, MixtureGD &world, FeatureServer &fs, StatServer &ss, SegCluster &selectedSegments, Config &config)
int normFeat (Config &config)
int infoFeat (Config &config)
int featMap (Config &config)
void featureWarping (Matrix< double > table, FeatureServer &fs, SegCluster &selectedSegments, Config &config)
int featWarp (Config &config)
int normFeatNAP (Config &config)
int normFeatFA (Config &config)
int normFeatLFA (Config &config)
Macro Definition Documentation
#define ALIZE_NormFeat_cpp
Definition at line 56 of file NormFeat.cpp.
Function Documentation
void computeWindowParam (Config & config, const DoubleVector & gMean, const DoubleVector & gCov, FeatureServer & fs, SegCluster & window, double windowDuration, double windowComp, double frameLength, DoubleVector & mean, DoubleVector & cov)
Definition at line 147 of file NormFeat.cpp.
References accumulateStatFrame(), debug, frameIdxToTime(), pow(), showCluster(), sqrt(), totalFrame(), verboseLevel, and windowLength().
Referenced by normFeat().
void displayStats (FrameAccGD & frameAccu, FeatureServer & fs, ostream & out, Config & config)
Definition at line 71 of file NormFeat.cpp.
Referenced by infoFeat().
bool emptyWindow (SegCluster & window)
Definition at line 89 of file NormFeat.cpp.
Referenced by inWindow(), and normFeat().
int featMap (Config & config)
Definition at line 583 of file NormFeat.cpp.
References debug, featureMapping(), initializeClusters(), outputFeatureFile(), verbose, and verifyClusterFile().
void featureChannelCompNAP (RealVector< double > & ubm_offset, MixtureGD & world, FeatureServer & fs, StatServer & ss, SegCluster & selectedSegments, Config & config)
Definition at line 213 of file NormFeat.cpp.
References removeOffsetOnFrame(), and verbose.
Referenced by normFeatNAP().
void featureWarping (Matrix< double > table, FeatureServer & fs, SegCluster & selectedSegments, Config & config)
Definition at line 646 of file NormFeat.cpp.
Referenced by featWarp().
int featWarp (Config & config)
Definition at line 661 of file NormFeat.cpp.
References debug, featureWarping(), initializeClusters(), outputFeatureFile(), verbose, and verifyClusterFile().
Seg* firstSeg (SegCluster & window)
Definition at line 94 of file NormFeat.cpp.
Referenced by inMiddle(), moveWindow(), and windowLength().
void getUbmOffset (RealVector< double > & ubm_offset, Matrix< double > & U, MixtureGD & world, Config & config)
Definition at line 189 of file NormFeat.cpp.
References modelToSv(), projectOnSubSpace(), and verbose.
Referenced by normFeatNAP().
int infoFeat (Config & config)
Definition at line 520 of file NormFeat.cpp.
References accumulateStatFrame(), displayStats(), globalMeanCov(), initializeClusters(), verbose, and verifyClusterFile().
bool inMiddle (Seg *& currentSeg, SegCluster & window, double windowDuration, double frameLength)
Definition at line 174 of file NormFeat.cpp.
References firstSeg(), and frameIdxToTime().
Referenced by normFeat().
bool inWindow (Seg & seg, SegCluster & window, double windowDuration, double frameLength)
Definition at line 119 of file NormFeat.cpp.
References emptyWindow(), and windowLength().
Referenced by normFeat().
Seg* lastSeg (SegCluster & window)
Definition at line 100 of file NormFeat.cpp.
Referenced by windowLength().
void loadStatsFromFile (String filename, DoubleVector & extMean, DoubleVector & extCov)
Definition at line 79 of file NormFeat.cpp.
Referenced by normFeat().
void moveWindow (SegCluster & window, Seg & seg, Seg *& currentSeg, double duration, double frameLength)
Definition at line 135 of file NormFeat.cpp.
References debug, firstSeg(), suppressFirst(), and windowLength().
Referenced by normFeat().
bool nextSeg (Seg *& currentSeg, SegCluster & window)
Definition at line 178 of file NormFeat.cpp.
Referenced by normFeat().
int normFeat (Config & config)
Definition at line 231 of file NormFeat.cpp.
References accumulateHistoFrame(), accumulateStatFrame(), cms(), computeHistoTab(), computeMeanCov(), computeWarp(), computeWindowParam(), computeZeroOne(), debug, emptyWindow(), freezeHistoTab(), initHistoTab(), initializeClusters(), inMiddle(), inWindow(), loadStatsFromFile(), makeGausHisto(), moveWindow(), nextSeg(), outputFeatureFile(), showCluster(), suppressFirst(), verbose, verboseLevel, and verifyClusterFile().
int normFeatFA (Config & config)
Definition at line 793 of file NormFeat.cpp.
References cms(), FactorAnalysisStat::estimateXYAndNorm(), initializeClusters(), outputFeatureFile(), verbose, and verifyClusterFile().
int normFeatLFA (Config & config)
Compute JFA stats
Estimate uEuT for the test
Estimate and inverse L matrices
Estimate X for the test segment
Estimate XYZ on the test segment and normalise the features by substracting Ux
Definition at line 856 of file NormFeat.cpp.
References cms(), JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_EC(), JFAAcc::estimateUEUT(), JFAAcc::estimateX(), JFAAcc::estimateZMAP(), initializeClusters(), JFAAcc::loadEC(), outputFeatureFile(), JFAAcc::substractMplusDZByChannel(), JFAAcc::substractMplusUX(), JFAAcc::substractUXfromFeatures(), verbose, and verifyClusterFile().
int normFeatNAP (Config & config)
Definition at line 724 of file NormFeat.cpp.
References debug, featureChannelCompNAP(), getUbmOffset(), initializeClusters(), outputFeatureFile(), verbose, and verifyClusterFile().
void removeOffsetOnFrame (RealVector< double > & occ, Feature & f, RealVector< double > & ubm_offset, unsigned long nbDistrib)
Definition at line 200 of file NormFeat.cpp.
References verboseLevel.
Referenced by featureChannelCompNAP().
void suppressFirst (SegCluster & window)
Definition at line 129 of file NormFeat.cpp.
Referenced by moveWindow(), and normFeat().
double windowLength (SegCluster & window, double frameLength)
Definition at line 109 of file NormFeat.cpp.
References firstSeg(), frameIdxToTime(), and lastSeg().
Referenced by computeWindowParam(), inWindow(), and moveWindow().