LIA_RAL: LIA_SpkDet/NormFeat/include/NormFeat.h File Reference
NormFeat.h File Reference
#include "alize.h"
Functions
int normFeat (alize::Config &)
int infoFeat (alize::Config &)
int featMap (alize::Config &)
int normFeatNAP (alize::Config &)
int normFeatFA (alize::Config &)
int normFeatLFA (alize::Config &)
Function Documentation
int featMap (alize::Config &)
Referenced by main().
int infoFeat (alize::Config &)
Referenced by main().
int normFeat (alize::Config &)
NormFeat is dedicated to the normalisation of features often used in Automatic Speech/Speaker Recognition. It can work in segmental mode to compute mean, cov and normalisation only on interesting segments.
Referenced by main().
int normFeatFA (alize::Config &)
Referenced by main().
int normFeatLFA (alize::Config &)
Referenced by main().
int normFeatNAP (alize::Config &)
Referenced by main().