LIA_RAL: LIA_SpkDet/NormFeatWindowMode/src/NormFeatWindowMode.cpp File Reference
NormFeatWindowMode.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "NormFeatWindowMode.h"
Macros
#define ALIZE_NormFeatWindowMode_cpp
Functions
void computeCMVnorm (Feature &f, DoubleVector &cMean, DoubleVector &cCov)
void loadMeanAndCovParam (RefVector< Feature > &windowFrameAcc, DoubleVector &cMean, DoubleVector &cCov, long &windowDuration)
void updateMeanAndCovParam (Feature &f, DoubleVector &cMean, DoubleVector &cCov, long &windowDuration, long &frameCount, long &lookHead)
void computeCMVparameters (Feature &f, long &windowDuration, RefVector< Feature > &windowFrameAcc, DoubleVector &cMean, DoubleVector &cCov, long &frameCount)
int normFeatOnlineMode (Config &config)
Macro Definition Documentation
#define ALIZE_NormFeatWindowMode_cpp
Definition at line 56 of file NormFeatWindowMode.cpp.
Function Documentation
void computeCMVnorm (Feature & f, DoubleVector & cMean, DoubleVector & cCov)
Definition at line 72 of file NormFeatWindowMode.cpp.
Referenced by normFeatOnlineMode().
void computeCMVparameters (Feature & f, long & windowDuration, RefVector< Feature > & windowFrameAcc, DoubleVector & cMean, DoubleVector & cCov, long & frameCount)
Definition at line 143 of file NormFeatWindowMode.cpp.
References loadMeanAndCovParam().
void loadMeanAndCovParam (RefVector< Feature > & windowFrameAcc, DoubleVector & cMean, DoubleVector & cCov, long & windowDuration)
Definition at line 85 of file NormFeatWindowMode.cpp.
Referenced by computeCMVparameters(), and normFeatOnlineMode().
int normFeatOnlineMode (Config & config)
Definition at line 165 of file NormFeatWindowMode.cpp.
References computeCMVnorm(), loadMeanAndCovParam(), updateMeanAndCovParam(), and verbose.
void updateMeanAndCovParam (Feature & f, DoubleVector & cMean, DoubleVector & cCov, long & windowDuration, long & frameCount, long & lookHead)
Definition at line 114 of file NormFeatWindowMode.cpp.
References sqrt().
Referenced by normFeatOnlineMode().