LIA_RAL: LIA_SpkDet/PLDA/src/PLDA.cpp File Reference
PLDA.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "PLDA.h"
Macros
#define ALIZE_PLDA_cpp
Functions
int PLDA (Config &config)
Macro Definition Documentation
#define ALIZE_PLDA_cpp
Definition at line 57 of file PLDA.cpp.
Function Documentation
int PLDA (Config & config)
Definition at line 74 of file PLDA.cpp.
References PldaModel::centerData(), PldaModel::em_iteration(), PldaModel::saveModel(), PldaModel::updateMean(), and verboseLevel.
Referenced by main().