LIA_RAL: LIA_SpkDet/PLDA/include/PLDA.h File Reference
PLDA.h File Reference
#include "alize.h"
#include "liatools.h"
Functions
int PLDA (Config &)
Function Documentation
int PLDA (Config &)
Definition at line 74 of file PLDA.cpp.
References PldaModel::centerData(), PldaModel::em_iteration(), PldaModel::saveModel(), PldaModel::updateMean(), and verboseLevel.
Referenced by main().