LIA_RAL: LIA_Utils/PolyExp/src/PolyExpand.cpp File Reference
PolyExpand.cpp File Reference
#include <iostream>
#include "alize.h"
#include "liatools.h"
#include <cmath>
Functions
void computeExpansion (Feature &f, Feature &expF)
void computeAndAccumulateExpansion (FeatureServer &fs, FrameAccGD &avgExp, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
void computeAndAccumulateExpansion (FeatureServer &fs, FrameAccGD &avgExp, Seg *seg, Config &config)
void computeAndAccumulateExpansion (FeatureServer &fs, FrameAccGD &avgExp, SegCluster &selectedSegments, Config &config)
void multiplyByR (DoubleVector &avgExp, XList &rMat)
void zNorm (DoubleVector &avgExp, XList &rMat)
void computeRSqrt (DoubleVector &R, unsigned long count)
void outputR (const DoubleVector &v1, const DoubleVector &v2, Config &config)
void outputInstanceSVMLight (const DoubleVector &v, String &filename, Config &config)
void outputInstance (const DoubleVector &v, String &filename, Config &config)
int PolyExpand (Config &config)
Function Documentation
void computeAndAccumulateExpansion (FeatureServer & fs, FrameAccGD & avgExp, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 85 of file PolyExpand.cpp.
References computeExpansion(), and debug.
Referenced by computeAndAccumulateExpansion(), and PolyExpand().
void computeAndAccumulateExpansion (FeatureServer & fs, FrameAccGD & avgExp, Seg * seg, Config & config)
Definition at line 102 of file PolyExpand.cpp.
References computeAndAccumulateExpansion().
void computeAndAccumulateExpansion (FeatureServer & fs, FrameAccGD & avgExp, SegCluster & selectedSegments, Config & config)
Definition at line 109 of file PolyExpand.cpp.
References computeAndAccumulateExpansion().
void computeExpansion (Feature & f, Feature & expF)
Definition at line 65 of file PolyExpand.cpp.
Referenced by computeAndAccumulateExpansion().
void computeRSqrt (DoubleVector & R, unsigned long count)
Definition at line 131 of file PolyExpand.cpp.
References sqrt().
Referenced by PolyExpand().
void multiplyByR (DoubleVector & avgExp, XList & rMat)
Definition at line 118 of file PolyExpand.cpp.
Referenced by PolyExpand().
void outputInstance (const DoubleVector & v, String & filename, Config & config)
Definition at line 157 of file PolyExpand.cpp.
References outputInstanceSVMLight().
Referenced by PolyExpand().
void outputInstanceSVMLight (const DoubleVector & v, String & filename, Config & config)
Definition at line 147 of file PolyExpand.cpp.
Referenced by outputInstance().
void outputR (const DoubleVector & v1, const DoubleVector & v2, Config & config)
Definition at line 138 of file PolyExpand.cpp.
Referenced by PolyExpand().
int PolyExpand (Config & config)
Definition at line 164 of file PolyExpand.cpp.
References computeAndAccumulateExpansion(), computeRSqrt(), initializeClusters(), multiplyByR(), outputInstance(), outputR(), verbose, and verifyClusterFile().
void zNorm (DoubleVector & avgExp, XList & rMat)
Definition at line 124 of file PolyExpand.cpp.