LIA_RAL: LIA_SpkSeg/ReSegmentation/src/ReSegmentation.cpp File Reference
ReSegmentation.cpp File Reference
Definition of speaker re-segmentation behavior.
#include "Tools.h"
#include "ReSegmentation.h"
Macros
#define ALIZE_ReSegmentation_cpp
Functions
bool isStopReSeg (Config &config, SegServer &previousSeg, SegServer &segmentServer, DoubleVector &actualViterbiProb, DoubleVector &previousViterbiProb, hmm &actualHMM)
Check :
void createClusterDecoding (Config &config, SegServer &decoding, SegServer &segmentServer, bool merge=true)
Build a new cluster and associated segments for the decoding step from an existing segment Server given as input.
void initClusterReSeg (Config &config, SegServer &segmentServer, LabelServer &labelServer, StatServer &ss, FeatureServer &fs)
This procedure initializes the clusters.
void ReSegmentationProcess (Config &config, SegServer &resegOutputServer, SegServer &segmentServer, StatServer &ss, MixtureServer &ms, FeatureServer &fs, LabelServer &labelServer)
The speaker re-segmentation process.
void launchReSegmentationProcess (Config &config)
Launching of the process speaker re-segmentation.
Detailed Description
Definition of speaker re-segmentation behavior.
Author
LIA
Version
2.0
Date
june 2011
The resegmentation step is normally applied in order to refine the segmentation outputs (issued from the segmentation step) and to remove irrelevant speakers.
A new HMM is generated from the segmentation output and an iterative speaker model training/Viterbi decoding loop is launched. In contrast to the segmentation stage, here the MAP adaptation (coupled with a generic speech/background model) replaces the EM/ML algorithm for speaker model estimation since the segmentation step provides an initial distribution of speech segments among the different speakers detected.
For the resegmentation process, all the boundaries (except speech/non-speech boundaries) and segment labels are re-examined.
Definition in file ReSegmentation.cpp.
Macro Definition Documentation
#define ALIZE_ReSegmentation_cpp
Definition at line 71 of file ReSegmentation.cpp.
Function Documentation
void createClusterDecoding (Config & config, SegServer & decoding, SegServer & segmentServer, bool merge = true)
Build a new cluster and associated segments for the decoding step from an existing segment Server given as input.
Remarks
In this function, :
Segments named "nonspeech" are removed
the set of the remaining segments is re-named 'ToDecode0' and grouped together in a same cluster for further decoding In this way, each decoding iteration being based on this cluster, labels and boundaries are re-examined at each of them
Definition at line 172 of file ReSegmentation.cpp.
References displayAllSegments(), verbose, and verboseLevel.
Referenced by ReSegmentationProcess().
void initClusterReSeg (Config & config, SegServer & segmentServer, LabelServer & labelServer, StatServer & ss, FeatureServer & fs)
This procedure initializes the clusters.
Definition at line 226 of file ReSegmentation.cpp.
References initializeClusters().
Referenced by ReSegmentationProcess().
bool isStopReSeg (Config & config, SegServer & previousSeg, SegServer & segmentServer, DoubleVector & actualViterbiProb, DoubleVector & previousViterbiProb, hmm & actualHMM)
Check :
whether some global speaker durations (over the segmentation) are under a limit value fixed in the configuration file. In this case, speakers are removed from the segmentation
whether the stop criteria (for adaptation/decoding step) are reached
Returns
True if Comparison between the last two segmentations (previous and current) are identical otherwise false
Remarks
The comparison between both segmentations is defined by :
the difference in the number of speakers
the difference in values of the Viterbi paths according to an epsilon value given in the configuration file
Attention
The parameter decodingEpsilon is required for step 2.
The value of the parameter decodingEpsilon defines the absolute margin of acceptable difference in values of Viterbi paths between both segmentations.
Definition at line 94 of file ReSegmentation.cpp.
References computeTransitions(), debug, hmm::deleteState(), isDifferentSegmentation(), isLessEpsilon(), totalFrame(), verbose, and verboseLevel.
Referenced by ReSegmentationProcess().
void launchReSegmentationProcess (Config & config)
Launching of the process speaker re-segmentation.
Definition at line 328 of file ReSegmentation.cpp.
References displayAllSegmentsFromRef(), initializeClusters(), ReSegmentationProcess(), saveSegmentation(), verbose, and verifyClusterFile().
Referenced by main().
void ReSegmentationProcess (Config & config, SegServer & resegOutputServer, SegServer & segmentServer, StatServer & ss, MixtureServer & ms, FeatureServer & fs, LabelServer & labelServer)
The speaker re-segmentation process.
Definition at line 245 of file ReSegmentation.cpp.
References createClusterDecoding(), createWorld(), displayAllSegments(), hmm::getNbState(), initClusterReSeg(), InitHMM(), isStopReSeg(), segAdaptation(), verbose, verboseLevel, and viterbiDecoding().
Referenced by launchReSegmentationProcess().