LIA_RAL: LIA_SpkSeg/ReSegmentation/include/ReSegmentation.h File Reference
ReSegmentation.h File Reference
Declaration of speaker re-segmentation functions.
#include <alize.h>
Functions
bool isStopReSeg (Config &, SegServer &, SegServer &, DoubleVector &, DoubleVector &, hmm &)
Check :
void createClusterDecoding (Config &, SegServer &, SegServer &, bool)
Build a new cluster and associated segments for the decoding step from an existing segment Server given as input.
void initClusterReSeg (Config &, SegServer &, LabelServer &, StatServer &, FeatureServer &)
This procedure initializes the clusters.
void analyzeSeg (Config &, SegServer &, LabelServer &)
void ReSegmentationProcess (Config &, SegServer &, SegServer &, StatServer &, MixtureServer &, FeatureServer &, LabelServer &)
The speaker re-segmentation process.
void launchReSegmentationProcess (Config &)
Launching of the process speaker re-segmentation.
Detailed Description
Declaration of speaker re-segmentation functions.
Author
LIA
Version
2.0
Date
june 2011
Definition in file ReSegmentation.h.
Function Documentation
void analyzeSeg (Config & , SegServer & , LabelServer &)
void createClusterDecoding (Config & config, SegServer & decoding, SegServer & segmentServer, bool merge = true)
Build a new cluster and associated segments for the decoding step from an existing segment Server given as input.
Remarks
In this function, :
Segments named "nonspeech" are removed
the set of the remaining segments is re-named 'ToDecode0' and grouped together in a same cluster for further decoding In this way, each decoding iteration being based on this cluster, labels and boundaries are re-examined at each of them
Definition at line 172 of file ReSegmentation.cpp.
References displayAllSegments(), verbose, and verboseLevel.
Referenced by ReSegmentationProcess().
void initClusterReSeg (Config & , SegServer & , LabelServer & , StatServer & , FeatureServer &)
This procedure initializes the clusters.
Definition at line 226 of file ReSegmentation.cpp.
References initializeClusters().
Referenced by ReSegmentationProcess().
bool isStopReSeg (Config & config, SegServer & previousSeg, SegServer & segmentServer, DoubleVector & actualViterbiProb, DoubleVector & previousViterbiProb, hmm & actualHMM)
Check :
whether some global speaker durations (over the segmentation) are under a limit value fixed in the configuration file. In this case, speakers are removed from the segmentation
whether the stop criteria (for adaptation/decoding step) are reached
Returns
True if Comparison between the last two segmentations (previous and current) are identical otherwise false
Remarks
The comparison between both segmentations is defined by :
the difference in the number of speakers
the difference in values of the Viterbi paths according to an epsilon value given in the configuration file
Attention
The parameter decodingEpsilon is required for step 2.
The value of the parameter decodingEpsilon defines the absolute margin of acceptable difference in values of Viterbi paths between both segmentations.
Definition at line 94 of file ReSegmentation.cpp.
References computeTransitions(), debug, hmm::deleteState(), isDifferentSegmentation(), isLessEpsilon(), totalFrame(), verbose, and verboseLevel.
Referenced by ReSegmentationProcess().
void launchReSegmentationProcess (Config &)
Launching of the process speaker re-segmentation.
Definition at line 328 of file ReSegmentation.cpp.
References displayAllSegmentsFromRef(), initializeClusters(), ReSegmentationProcess(), saveSegmentation(), verbose, and verifyClusterFile().
Referenced by main().
void ReSegmentationProcess (Config & , SegServer & , SegServer & , StatServer & , MixtureServer & , FeatureServer & , LabelServer &)
The speaker re-segmentation process.
Definition at line 245 of file ReSegmentation.cpp.
References createClusterDecoding(), createWorld(), displayAllSegments(), hmm::getNbState(), initClusterReSeg(), InitHMM(), isStopReSeg(), segAdaptation(), verbose, verboseLevel, and viterbiDecoding().
Referenced by launchReSegmentationProcess().