LIA_RAL: LIA_Utils/Scoring/src/Scoring.cpp File Reference
Scoring.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include "Scoring.h"
#include <liatools.h>
Macros
#define ALIZE_Scoring_cpp
Functions
String getDecision (double score, double threshold)
String getLongDecision (double score, double threshold)
void retrieveNISTSegmentInfo (XList &inputList, String &gender, String &clientName, String &seg, unsigned long genderField, unsigned long nameField, unsigned long segField, unsigned long &i)
unsigned long getIndexOfMaxScore (XList &inputList, unsigned long scoreField, unsigned long segField, unsigned long &i, unsigned long nbListLines)
void getSegmentalMeanCov (XList &inputList, unsigned long nbLoc, double *meanTab, double *covTab)
void getTarClientIdx (Config &config, XList &inputList, unsigned long nbLoc, unsigned long *tarTab)
void getSegmentalMeanCovWithoutMax (Config &config, XList &inputList, unsigned long nbLoc, unsigned long *tarTab, double *meanTab, double *covTab)
int Scoring (Config &config)
int WarpScores (Config &config)
Macro Definition Documentation
#define ALIZE_Scoring_cpp
Definition at line 56 of file Scoring.cpp.
Function Documentation
String getDecision (double score, double threshold)
Definition at line 72 of file Scoring.cpp.
Referenced by Scoring().
unsigned long getIndexOfMaxScore (XList & inputList, unsigned long scoreField, unsigned long segField, unsigned long & i, unsigned long nbListLines)
Definition at line 104 of file Scoring.cpp.
Referenced by Scoring().
String getLongDecision (double score, double threshold)
Definition at line 84 of file Scoring.cpp.
Referenced by Scoring().
void getSegmentalMeanCov (XList & inputList, unsigned long nbLoc, double * meanTab, double * covTab)
Definition at line 123 of file Scoring.cpp.
void getSegmentalMeanCovWithoutMax (Config & config, XList & inputList, unsigned long nbLoc, unsigned long * tarTab, double * meanTab, double * covTab)
Definition at line 182 of file Scoring.cpp.
References verbose.
Referenced by Scoring().
void getTarClientIdx (Config & config, XList & inputList, unsigned long nbLoc, unsigned long * tarTab)
Definition at line 150 of file Scoring.cpp.
References verbose.
Referenced by Scoring().
void retrieveNISTSegmentInfo (XList & inputList, String & gender, String & clientName, String & seg, unsigned long genderField, unsigned long nameField, unsigned long segField, unsigned long & i)
Definition at line 96 of file Scoring.cpp.
Referenced by Scoring(), and WarpScores().
int Scoring (Config & config)
Definition at line 223 of file Scoring.cpp.
References debug, getDecision(), getIndexOfMaxScore(), getLongDecision(), getSegmentalMeanCovWithoutMax(), getTarClientIdx(), outputResultETFLine(), outputResultLIARALLine(), outputResultMDTMLine(), outputResultNIST04Line(), retrieveNISTSegmentInfo(), setLIAInfoFields(), sqrt(), and verbose.
int WarpScores (Config & config)
Definition at line 422 of file Scoring.cpp.
References debug, outputResultNIST04Line(), retrieveNISTSegmentInfo(), scoreWarping(), and verbose.