LIA_RAL: LIA_SpkTools/include/ScoreWarp.h File Reference
ScoreWarp.h File Reference
#include "alize.h"
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API void boxMullerGeneratorInit ()
LIA_SPKTOOLS_API double boxMullerGenerator (double mean, double cov)
LIA_SPKTOOLS_API Histo makeGausHisto (unsigned long nbSample, double mean, double cov, unsigned long nbBins)
LIA_SPKTOOLS_API double scoreWarping (double, const Histo &, const Histo &, double=0.1, double=0.5)
LIA_SPKTOOLS_API double warping (double score, const Histo &warpH, const Histo &destH)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file ScoreWarp.h.
Function Documentation
LIA_SPKTOOLS_API double boxMullerGenerator (double mean, double cov)
Definition at line 71 of file ScoreWarp.cpp.
References cos(), debug, log(), PI2, sqrt(), x1, x2, and Eigen::internal::y.
Referenced by JFAAcc::initD(), JFAAcc::initEC(), JFAAcc::initEV(), PldaModel::initF(), PldaModel::initG(), TVAcc::initT(), main(), and makeGausHisto().
LIA_SPKTOOLS_API void boxMullerGeneratorInit ()
Definition at line 68 of file ScoreWarp.cpp.
References x1.
Referenced by JFAAcc::initD(), JFAAcc::initEC(), JFAAcc::initEV(), PldaModel::initF(), PldaModel::initG(), TVAcc::initT(), main(), and makeGausHisto().
LIA_SPKTOOLS_API Histo makeGausHisto (unsigned long nbSample, double mean, double cov, unsigned long nbBins)
Definition at line 83 of file ScoreWarp.cpp.
References boxMullerGenerator(), boxMullerGeneratorInit(), and verbose.
Referenced by main(), and normFeat().
LIA_SPKTOOLS_API double scoreWarping (double , const Histo & , const Histo & , double = 0.1, double = 0.5)
Definition at line 114 of file ScoreWarp.cpp.
References areaHisto(), centralSpace(), debug, and linearInterpolation().
Referenced by main(), and WarpScores().
LIA_SPKTOOLS_API double warping (double score, const Histo & warpH, const Histo & destH)
Definition at line 168 of file ScoreWarp.cpp.
References areaHisto(), debug, and linearInterpolation().
Referenced by computeWarp().