LIA_RAL: LIA_SpkTools/src/ScoreWarp.cpp File Reference
ScoreWarp.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include "TrainTools.h"
#include "ScoreWarp.h"
Macros
#define ALIZE_ScoreWarp_cpp
Functions
void boxMullerGeneratorInit ()
double boxMullerGenerator (double mean, double cov)
Histo makeGausHisto (unsigned long nbSample, double mean, double cov, unsigned long nbBins)
double centralSpace (const Histo &warpH, double a)
double scoreWarping (double score, const Histo &warpH, const Histo &destH, double nonObserved, double refArea)
double warping (double score, const Histo &warpH, const Histo &destH)
Variables
const double PI2 = 3.14159265358979323846*2
static double x1
static double x2
Macro Definition Documentation
#define ALIZE_ScoreWarp_cpp
Definition at line 56 of file ScoreWarp.cpp.
Function Documentation
double boxMullerGenerator (double mean, double cov)
Definition at line 71 of file ScoreWarp.cpp.
References cos(), debug, log(), PI2, sqrt(), x1, x2, and Eigen::internal::y.
Referenced by JFAAcc::initD(), JFAAcc::initEC(), JFAAcc::initEV(), PldaModel::initF(), PldaModel::initG(), TVAcc::initT(), main(), and makeGausHisto().
void boxMullerGeneratorInit ()
Definition at line 68 of file ScoreWarp.cpp.
References x1.
Referenced by JFAAcc::initD(), JFAAcc::initEC(), JFAAcc::initEV(), PldaModel::initF(), PldaModel::initG(), TVAcc::initT(), main(), and makeGausHisto().
double centralSpace (const Histo & warpH, double a)
Definition at line 100 of file ScoreWarp.cpp.
References areaHisto().
Referenced by scoreWarping().
Histo makeGausHisto (unsigned long nbSample, double mean, double cov, unsigned long nbBins)
Definition at line 83 of file ScoreWarp.cpp.
References boxMullerGenerator(), boxMullerGeneratorInit(), and verbose.
Referenced by main(), and normFeat().
double scoreWarping (double score, const Histo & warpH, const Histo & destH, double nonObserved, double refArea)
Definition at line 114 of file ScoreWarp.cpp.
References areaHisto(), centralSpace(), debug, and linearInterpolation().
Referenced by main(), and WarpScores().
double warping (double score, const Histo & warpH, const Histo & destH)
Definition at line 168 of file ScoreWarp.cpp.
References areaHisto(), debug, and linearInterpolation().
Referenced by computeWarp().
Variable Documentation
const double PI2 = 3.14159265358979323846*2
Definition at line 65 of file ScoreWarp.cpp.
Referenced by boxMullerGenerator().
double x1 static
Definition at line 66 of file ScoreWarp.cpp.
Referenced by boxMullerGenerator(), boxMullerGeneratorInit(), Eigen::internal::pdiv< Packet1cd >(), and Eigen::internal::preverse().
double x2 static
Definition at line 67 of file ScoreWarp.cpp.
Referenced by boxMullerGenerator(), and Eigen::internal::plog< Packet4f >().