LIA_RAL: LIA_SpkSeg/Segmentation/src/Segmentation.cpp File Reference
Segmentation.cpp File Reference
Description of speaker segmentation behavior.
#include "Tools.h"
#include "Segmentation.h"
Macros
#define ALIZE_Segmentation_cpp
Functions
bool segmentSelection (Config &config, SegCluster &clusterSeg0, SegCluster &clusterAlreadyUsedSeg, unsigned long &startSeg, unsigned long &stopSeg, String &fileLabel)
Selection of suitable segment for adding a new speaker.
int addSpeaker (Config &config, SegServer &actualSeg, SegServer &alreadyUsedSeg, LabelServer &labelServer, int &numSpeaker, hmm &actualHMM, String clusterName)
Add a new speaker after selecting a segment.
bool isValidSpeaker (Config &config, hmm &actualHMM, hmm &previousHMM, SegServer &previousSeg, SegServer &actualSeg, SegServer &alreadyUsedSeg, unsigned long initSpeakerTime)
Different tests done to verify the validity of the new speaker and the hmm.
bool isSegAvailable (Config &config, SegServer &alreadyUsedSeg, SegServer &actualSeg)
Verifies whether a pre-selected segment is not already used.
bool isStopCriterionReached (Config &config, hmm &actualHMM, hmm &previousHMM, SegServer &actualSeg, SegServer &previousSeg, SegServer &alreadyUsedSeg, StatServer &ss, FeatureServer &fs, unsigned long initSpeakerTime)
Verifies that the stop criterion of a segmentation for a speaker is reached or not.
void test_segmentation (Config &config, SegCluster &cluster)
Set the parameter selectionMethod to the value firstSegmentFound if the speaker has only one turn of speech.
void segmentationProcess (Config &config, SegCluster &cluster, SegServer &segOutputServer, StatServer &ss, FeatureServer &fs, MixtureServer &ms, LabelServer &labelServer)
The speaker segmentation process.
void launchSegmentationProcess (Config &config)
Launching of the process speaker segmentation.
Detailed Description
Description of speaker segmentation behavior.
Author
LIA
Version
2.0
Date
june 2011
The speaker segmentation and clustering stage works directly on the SAD output. The segmentation and clustering process relies on a one-step segmentation and clustering algorithm in the form of an evolutive hidden Markov model (E-HMM). Each E-HMM state aims to characterise a single speaker and the transitions represent the speaker turns. All possible changes between speakers are authorized. The process for each audio show is as follows:
Initialization:
The E-HMM has only one state L0
An iterative process is then started where a new speaker is added at each iteration.
A new speaker Lx is added to the E-HMM:
According to the selection strategy used (defined through the selectionMethod parameter in the config file), a segment is chosen among all of the segments currently assigned to L0.
The selected segment is attributed to Lx and is used to estimate a new GMM with EM training.
Adaptation/Decoding loop:
The objective is to detect all segments belonging to the new speaker Lx.
All speaker models are re-estimated through an adaptation process, according to the current segmentation (EM Algorithm) and a new segmentation is obtained via Viterbi decoding.
This adaptation/decoding loop is repeated while some significant changes are observed on the speaker segmentation between two successive iterations.
Speaker model validation and stop criterion:
The current segmentation is analyzed in order to decide if the new added speaker Lx is relevant, according to some heuristical rules on the total duration of speech assigned to speaker Lx.
The stop criterion is reached if there are no more segments available in L0 with which a new speaker can be added, otherwise the process goes back to step 2.
Definition in file Segmentation.cpp.
Macro Definition Documentation
#define ALIZE_Segmentation_cpp
Definition at line 85 of file Segmentation.cpp.
Function Documentation
int addSpeaker (Config & config, SegServer & actualSeg, SegServer & alreadyUsedSeg, LabelServer & labelServer, int & numSpeaker, hmm & actualHMM, String clusterName)
Add a new speaker after selecting a segment.
Returns
0 if suitable segment is found otherwise -1 if no more segment available
Remarks
This function performs :
the deletion of the speakers for which the length in speech time is zero
the research of an available segment
the creation of a new speaker if a segment is available
Definition at line 211 of file Segmentation.cpp.
References hmm::addState(), computeTransitions(), displayAllClusters(), displayOneCluster(), hmm::getNbState(), NoDataSpeakerVerification(), removePartOfSeg(), segmentSelection(), verbose, and verboseLevel.
Referenced by segmentationProcess().
bool isSegAvailable (Config & config, SegServer & alreadyUsedSeg, SegServer & actualSeg)
Verifies whether a pre-selected segment is not already used.
Returns
True if the pre-selected segment is not already used otherwise false
Definition at line 302 of file Segmentation.cpp.
References findAlreadyUsed(), and verbose.
Referenced by isStopCriterionReached(), and segmentationProcess().
bool isStopCriterionReached (Config & config, hmm & actualHMM, hmm & previousHMM, SegServer & actualSeg, SegServer & previousSeg, SegServer & alreadyUsedSeg, StatServer & ss, FeatureServer & fs, unsigned long initSpeakerTime)
Verifies that the stop criterion of a segmentation for a speaker is reached or not.
Returns
True if the stop criterion is reached otherwise false
Remarks
The stop criterion depend on the validity of the last speaker and the availability of new segments to be selected.
Definition at line 332 of file Segmentation.cpp.
References isSegAvailable(), isValidSpeaker(), and verbose.
Referenced by segmentationProcess().
bool isValidSpeaker (Config & config, hmm & actualHMM, hmm & previousHMM, SegServer & previousSeg, SegServer & actualSeg, SegServer & alreadyUsedSeg, unsigned long initSpeakerTime)
Different tests done to verify the validity of the new speaker and the hmm.
Returns
True if the speaker is valid otherwise false
Remarks
A speaker is declared valid if the time of speech allocated to the last speaker is superior to the value of the parameter minSpeakerTime.
Definition at line 275 of file Segmentation.cpp.
References totalFrame(), and verbose.
Referenced by isStopCriterionReached().
void launchSegmentationProcess (Config & config)
Launching of the process speaker segmentation.
Definition at line 484 of file Segmentation.cpp.
References displayAllSegmentsFromRef(), initializeClusters(), saveSegmentation(), segmentationProcess(), verbose, and verifyClusterFile().
Referenced by main().
void segmentationProcess (Config & config, SegCluster & cluster, SegServer & segOutputServer, StatServer & ss, FeatureServer & fs, MixtureServer & ms, LabelServer & labelServer)
The speaker segmentation process.
Definition at line 356 of file Segmentation.cpp.
References addSpeaker(), hmm::addState(), createWorld(), displayAllSegments(), isComparableAndVerifSpeaker(), isSegAvailable(), isStopCriterionReached(), segAdaptation(), segEM(), test_segmentation(), totalFrame(), verbose, verboseLevel, and viterbiDecoding().
Referenced by launchSegmentationProcess().
bool segmentSelection (Config & config, SegCluster & clusterSeg0, SegCluster & clusterAlreadyUsedSeg, unsigned long & startSeg, unsigned long & stopSeg, String & fileLabel)
Selection of suitable segment for adding a new speaker.
Returns
True if suitable segment is found otherwise false
Remarks
The method of selection depends on the selectionMethod parameter which the following values can be associated with:
'firstSegmentFound' => Select the first segment which duration is over the selectionLength parameter
'firstLimitedLengthSegmentFound' => Select the first segment which duration is over than the selectionLength parameter, but truncated to reflect the limitedLength parameter
'longerSegmentFound' => Select the longest segment which duration is over the selectionLength parameter
'longerLimitedLengthSegmentFound' => Select the longest segment which duration is over than the selectionLength parameter, but truncated to reflect the limitedLength parameter
A segment is considered as suitable if :
the length of segment is superior or equal to the value of the parameter selectionLength
the pre-selected segment is not already used
Definition at line 111 of file Segmentation.cpp.
References findAlreadyUsed(), and verbose.
Referenced by addSpeaker().
void test_segmentation (Config & config, SegCluster & cluster)
Set the parameter selectionMethod to the value firstSegmentFound if the speaker has only one turn of speech.
Definition at line 346 of file Segmentation.cpp.
Referenced by segmentationProcess().