LIA_RAL: LIA_SpkSeg/Segmentation/include/Segmentation.h File Reference
Segmentation.h File Reference
Declaration of speaker segmentation functions.
#include <alize.h>
#include "Tools.h"
Functions
bool segmentSelection (Config &, SegCluster &, SegCluster &, unsigned long &, unsigned long &, String &)
Selection of suitable segment for adding a new speaker.
int addSpeaker (Config &, SegServer &, SegServer &, LabelServer &, int &, hmm &, String)
Add a new speaker after selecting a segment.
bool isValidSpeaker (Config &, hmm &, hmm &, SegServer &, SegServer &, SegServer &, unsigned long)
Different tests done to verify the validity of the new speaker and the hmm.
bool isSegAvailable (Config &, SegServer &, SegServer &)
Verifies whether a pre-selected segment is not already used.
bool isStopCriterionReached (Config &, hmm &, hmm &, SegServer &, SegServer &, SegServer &, StatServer &, FeatureServer &, unsigned long)
Verifies that the stop criterion of a segmentation for a speaker is reached or not.
void segmentationProcess (Config &, SegCluster &, SegServer &, StatServer &, FeatureServer &, MixtureServer &, LabelServer &)
The speaker segmentation process.
void launchSegmentationProcess (Config &)
Launching of the process speaker segmentation.
Detailed Description
Declaration of speaker segmentation functions.
Author
LIA
Version
2.0
Date
june 2011
Definition in file Segmentation.h.
Function Documentation
int addSpeaker (Config & config, SegServer & actualSeg, SegServer & alreadyUsedSeg, LabelServer & labelServer, int & numSpeaker, hmm & actualHMM, String clusterName)
Add a new speaker after selecting a segment.
Returns
0 if suitable segment is found otherwise -1 if no more segment available
Remarks
This function performs :
the deletion of the speakers for which the length in speech time is zero
the research of an available segment
the creation of a new speaker if a segment is available
Definition at line 211 of file Segmentation.cpp.
References hmm::addState(), computeTransitions(), displayAllClusters(), displayOneCluster(), hmm::getNbState(), NoDataSpeakerVerification(), removePartOfSeg(), segmentSelection(), verbose, and verboseLevel.
Referenced by segmentationProcess().
bool isSegAvailable (Config & config, SegServer & alreadyUsedSeg, SegServer & actualSeg)
Verifies whether a pre-selected segment is not already used.
Returns
True if the pre-selected segment is not already used otherwise false
Definition at line 302 of file Segmentation.cpp.
References findAlreadyUsed(), and verbose.
Referenced by isStopCriterionReached(), and segmentationProcess().
bool isStopCriterionReached (Config & config, hmm & actualHMM, hmm & previousHMM, SegServer & actualSeg, SegServer & previousSeg, SegServer & alreadyUsedSeg, StatServer & ss, FeatureServer & fs, unsigned long initSpeakerTime)
Verifies that the stop criterion of a segmentation for a speaker is reached or not.
Returns
True if the stop criterion is reached otherwise false
Remarks
The stop criterion depend on the validity of the last speaker and the availability of new segments to be selected.
Definition at line 332 of file Segmentation.cpp.
References isSegAvailable(), isValidSpeaker(), and verbose.
Referenced by segmentationProcess().
bool isValidSpeaker (Config & config, hmm & actualHMM, hmm & previousHMM, SegServer & previousSeg, SegServer & actualSeg, SegServer & alreadyUsedSeg, unsigned long initSpeakerTime)
Different tests done to verify the validity of the new speaker and the hmm.
Returns
True if the speaker is valid otherwise false
Remarks
A speaker is declared valid if the time of speech allocated to the last speaker is superior to the value of the parameter minSpeakerTime.
Definition at line 275 of file Segmentation.cpp.
References totalFrame(), and verbose.
Referenced by isStopCriterionReached().
void launchSegmentationProcess (Config &)
Launching of the process speaker segmentation.
Definition at line 484 of file Segmentation.cpp.
References displayAllSegmentsFromRef(), initializeClusters(), saveSegmentation(), segmentationProcess(), verbose, and verifyClusterFile().
Referenced by main().
void segmentationProcess (Config & , SegCluster & , SegServer & , StatServer & , FeatureServer & , MixtureServer & , LabelServer &)
The speaker segmentation process.
Definition at line 356 of file Segmentation.cpp.
References addSpeaker(), hmm::addState(), createWorld(), displayAllSegments(), isComparableAndVerifSpeaker(), isSegAvailable(), isStopCriterionReached(), segAdaptation(), segEM(), test_segmentation(), totalFrame(), verbose, verboseLevel, and viterbiDecoding().
Referenced by launchSegmentationProcess().
bool segmentSelection (Config & config, SegCluster & clusterSeg0, SegCluster & clusterAlreadyUsedSeg, unsigned long & startSeg, unsigned long & stopSeg, String & fileLabel)
Selection of suitable segment for adding a new speaker.
Returns
True if suitable segment is found otherwise false
Remarks
The method of selection depends on the selectionMethod parameter which the following values can be associated with:
'firstSegmentFound' => Select the first segment which duration is over the selectionLength parameter
'firstLimitedLengthSegmentFound' => Select the first segment which duration is over than the selectionLength parameter, but truncated to reflect the limitedLength parameter
'longerSegmentFound' => Select the longest segment which duration is over the selectionLength parameter
'longerLimitedLengthSegmentFound' => Select the longest segment which duration is over than the selectionLength parameter, but truncated to reflect the limitedLength parameter
A segment is considered as suitable if :
the length of segment is superior or equal to the value of the parameter selectionLength
the pre-selected segment is not already used
Definition at line 111 of file Segmentation.cpp.
References findAlreadyUsed(), and verbose.
Referenced by addSpeaker().