LIA_RAL: LIA_SpkTools/include/SegTools.h File Reference
SegTools.h File Reference
#include <alize.h>
#include <liatools.h>
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API void showCluster (SegCluster &cluster)
LIA_SPKTOOLS_API unsigned long totalFrame (SegCluster &cluster)
LIA_SPKTOOLS_API unsigned long endSeg (Seg *seg)
LIA_SPKTOOLS_API void outputLabelFile (SegCluster &selectedSeg, String FileName, Config &config)
LIA_SPKTOOLS_API void analiseParSegments (Config &config, XList *listSeg, LabelServer *labelServer, int nbrModels, XLine *labelaAnaliser, SegServer &segmentsServer, void(*pfunc)(int, Feature &, Config &config, void *pv1, void *pv2), void *pv1, void *pv2)
LIA_SPKTOOLS_API void createDefSeg (SegServer &ss, FeatureServer &fs, Config &config)
LIA_SPKTOOLS_API void verifyClusterFile (SegServer &segmentsServer, FeatureServer &fs, Config &config)
LIA_SPKTOOLS_API unsigned long timeToFrameIdx (real_t time, real_t frameLength)
LIA_SPKTOOLS_API real_t frameIdxToTime (unsigned long idx, real_t frameLength)
LIA_SPKTOOLS_API void loadLabelFile (SegCluster &cluster, String fileName, String path, String extension, Config &config)
LIA_SPKTOOLS_API void loadClusterFile (String &fileName, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
LIA_SPKTOOLS_API void initializeClusters (const XLine &listFiles, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
LIA_SPKTOOLS_API void initializeClusters (const XList &listXFiles, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
LIA_SPKTOOLS_API void initializeClusters (String &file, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
LIA_SPKTOOLS_API void initializeClusters (String &file, SegServer &segmentsServer, LabelServer &labelServer, Config &config, bool nomComplet)
LIA_SPKTOOLS_API ViterbiAccum & createAndInitializeViterbiAccum (StatServer &ss, hmm &cHmm)
LIA_SPKTOOLS_API void accumulateStatViterbi (FeatureServer &fs, ViterbiAccum &va, unsigned long beginIdx, unsigned long length, Config &config)
LIA_SPKTOOLS_API void accumulateStatViterbi (FeatureServer &fs, ViterbiAccum &va, Seg *seg, Config &config)
LIA_SPKTOOLS_API void accumulateStatViterbi (FeatureServer &fs, ViterbiAccum &va, Seg *seg, Config &config, SegServer &TransitSegServer, DoubleVector &TransitionsFort, DoubleVector &TransitionsFaible, unsigned long NbState)
LIA_SPKTOOLS_API void removeAllSeg (SegServer &segServer, SegCluster &cluster)
LIA_SPKTOOLS_API void initializeCluster (SegServer &currentSeg, hmm &cHmm, LabelServer &labelServer)
LIA_SPKTOOLS_API bool removePartOfSeg (SegCluster &clusterSeg, SegServer &segServer, LabelServer &labelServer, String segSourceName, unsigned long segStart, unsigned long segLength)
LIA_SPKTOOLS_API void displayAllClusters (Config &config, SegServer &seg)
LIA_SPKTOOLS_API void displayOneCluster (Config &config, SegCluster &clusterT)
LIA_SPKTOOLS_API void displayAllSegments (Config &config, SegServer &seg)
LIA_SPKTOOLS_API void displayAllSegmentsFromRef (Config &config, String &fileInit, unsigned long fileSize)
LIA_SPKTOOLS_API unsigned long computeClusterTime (SegCluster &cluster)
LIA_SPKTOOLS_API long findLabel (XLine classToAnalyse, String labelToFind)
LIA_SPKTOOLS_API void moveSegmentFromOneClusterToAnother (LabelServer &labelServer, Seg *segment, SegCluster &currentCluster, SegCluster &newCluster)
LIA_SPKTOOLS_API Seg * longerSegment (Config &config, SegCluster &cluster)
LIA_SPKTOOLS_API unsigned long findClusterIndex (String name, SegServer &segTmp)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file SegTools.h.
Function Documentation
LIA_SPKTOOLS_API void accumulateStatViterbi (FeatureServer & fs, ViterbiAccum & va, unsigned long beginIdx, unsigned long length, Config & config)
Definition at line 336 of file SegTools.cpp.
Referenced by accumulateStatViterbi(), and viterbiDecoding().
LIA_SPKTOOLS_API void accumulateStatViterbi (FeatureServer & fs, ViterbiAccum & va, Seg * seg, Config & config)
Definition at line 347 of file SegTools.cpp.
References accumulateStatViterbi().
LIA_SPKTOOLS_API void accumulateStatViterbi (FeatureServer & fs, ViterbiAccum & va, Seg * seg, Config & config, SegServer & TransitSegServer, DoubleVector & TransitionsFort, DoubleVector & TransitionsFaible, unsigned long NbState)
Definition at line 355 of file SegTools.cpp.
References log().
LIA_SPKTOOLS_API void analiseParSegments (Config & config, XList * listSeg, LabelServer * labelServer, int nbrModels, XLine * labelaAnaliser, SegServer & segmentsServer, void(*)(int, Feature &, Config &config, void *pv1, void *pv2) pfunc, void * pv1, void * pv2)
LIA_SPKTOOLS_API unsigned long computeClusterTime (SegCluster & cluster)
LIA_SPKTOOLS_API ViterbiAccum& createAndInitializeViterbiAccum (StatServer & ss, hmm & cHmm)
Definition at line 323 of file SegTools.cpp.
References hmm::getDensity(), hmm::getNbState(), hmm::getTransition(), and log().
Referenced by viterbiDecoding().
LIA_SPKTOOLS_API void createDefSeg (SegServer & ss, FeatureServer & fs, Config & config)
Definition at line 124 of file SegTools.cpp.
LIA_SPKTOOLS_API void displayAllClusters (Config & config, SegServer & seg)
Definition at line 451 of file SegTools.cpp.
References displayOneCluster().
Referenced by addSpeaker(), and TurnDetection().
LIA_SPKTOOLS_API void displayAllSegments (Config & config, SegServer & seg)
Definition at line 484 of file SegTools.cpp.
References verboseLevel.
Referenced by AcousticSegmentationProcess(), ComputePath(), createClusterDecoding(), launchTurnDetectionProcess(), ReSegmentationProcess(), saveAcousticSegmentation(), saveSegmentation(), and segmentationProcess().
LIA_SPKTOOLS_API void displayAllSegmentsFromRef (Config & config, String & fileInit, unsigned long fileSize)
Definition at line 544 of file SegTools.cpp.
References initializeClusters(), verbose, and verboseLevel.
Referenced by launchAcousticSegmentationProcess(), launchReSegmentationProcess(), launchSegmentationProcess(), and launchTurnDetectionProcess().
LIA_SPKTOOLS_API void displayOneCluster (Config & config, SegCluster & clusterT)
Definition at line 464 of file SegTools.cpp.
Referenced by addSpeaker(), and displayAllClusters().
LIA_SPKTOOLS_API unsigned long endSeg (Seg * seg)
Definition at line 99 of file SegTools.cpp.
Referenced by aggregateSegment(), applyLengthRules(), bestFittingSegment(), clusteringCriterion(), clusteringCriterionByAdapt(), clusteringCriterionWithoutWorldInit(), computeLabelNGram(), interCluster(), interSeg(), intraCluster(), morphologicalFilter(), and TurnDetection().
LIA_SPKTOOLS_API unsigned long findClusterIndex (String name, SegServer & segTmp)
Definition at line 654 of file SegTools.cpp.
LIA_SPKTOOLS_API long findLabel (XLine classToAnalyse, String labelToFind)
Definition at line 605 of file SegTools.cpp.
LIA_SPKTOOLS_API real_t frameIdxToTime (unsigned long idx, real_t frameLength)
Definition at line 143 of file SegTools.cpp.
Referenced by ComputeTest(), ComputeTestNAP(), computeWindowParam(), inMiddle(), main(), outputLabelFile(), and windowLength().
LIA_SPKTOOLS_API void initializeCluster (SegServer & currentSeg, hmm & cHmm, LabelServer & labelServer)
Definition at line 399 of file SegTools.cpp.
References hmm::getNbState(), and hmm::getStateName().
Referenced by viterbiDecoding().
LIA_SPKTOOLS_API void initializeClusters (const XLine & listFiles, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 289 of file SegTools.cpp.
References loadClusterFile().
Referenced by adaptModelEMweightedFrames(), cms(), TopGauss::compute(), FactorAnalysisStat::computeAndAccumulateGeneralFAStats(), JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::computeAndAccumulateJFAStatUnThreaded(), TVAcc::computeAndAccumulateTVStat(), TVAcc::computeAndAccumulateTVStatUnThreaded(), computeAndStoreZnormParam(), computeLLRmatrix(), ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), displayAllSegmentsFromRef(), energyDetector(), featMap(), featureStream(), featWarp(), GaussianConfusionMatrix(), TopGauss::get(), GMMTokenizer(), infoFeat(), InfoTarget(), initClusterReSeg(), initializeClusters(), launchAcousticSegmentationProcess(), launchReSegmentationProcess(), launchSegmentationProcess(), launchTurnDetectionProcess(), learnEMimpostorModels(), learnMAPimpostorModels(), FactorAnalysisStat::normalizeFeatures(), normFeat(), normFeatFA(), normFeatLFA(), normFeatNAP(), PolyExpand(), JFAAcc::substractUXfromFeatures(), TrainTarget(), TrainTargetAdapt(), TrainTargetByLabel(), TrainTargetFA(), TrainTargetJFA(), TrainTargetLFA(), TVAcc::verifyEMLK(), and JFAAcc::verifyEMLK().
LIA_SPKTOOLS_API void initializeClusters (const XList & listXFiles, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 299 of file SegTools.cpp.
References initializeClusters().
LIA_SPKTOOLS_API void initializeClusters (String & file, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 305 of file SegTools.cpp.
References initializeClusters(), and loadClusterFile().
LIA_SPKTOOLS_API void initializeClusters (String & file, SegServer & segmentsServer, LabelServer & labelServer, Config & config, bool nomComplet)
LIA_SPKTOOLS_API void loadClusterFile (String & fileName, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 216 of file SegTools.cpp.
References addSegment(), debug, timeToFrameIdx(), verbose, and verboseLevel.
Referenced by initializeClusters(), labelFusion(), labelMorphing(), labelNGram(), main(), and sequenceDecoder().
LIA_SPKTOOLS_API void loadLabelFile (SegCluster & cluster, String fileName, String path, String extension, Config & config)
Definition at line 197 of file SegTools.cpp.
References timeToFrameIdx(), and verboseLevel.
LIA_SPKTOOLS_API Seg* longerSegment (Config & config, SegCluster & cluster)
Definition at line 628 of file SegTools.cpp.
LIA_SPKTOOLS_API void moveSegmentFromOneClusterToAnother (LabelServer & labelServer, Seg * segment, SegCluster & currentCluster, SegCluster & newCluster)
Definition at line 615 of file SegTools.cpp.
Referenced by CleanSpeaker().
LIA_SPKTOOLS_API void outputLabelFile (SegCluster & selectedSeg, String FileName, Config & config)
Definition at line 106 of file SegTools.cpp.
References debug, and frameIdxToTime().
Referenced by labelFusion(), labelMorphing(), labelNGram(), and main().
LIA_SPKTOOLS_API void removeAllSeg (SegServer & segServer, SegCluster & cluster)
Definition at line 390 of file SegTools.cpp.
LIA_SPKTOOLS_API bool removePartOfSeg (SegCluster & clusterSeg, SegServer & segServer, LabelServer & labelServer, String segSourceName, unsigned long segStart, unsigned long segLength)
Definition at line 414 of file SegTools.cpp.
Referenced by addSpeaker().
LIA_SPKTOOLS_API void showCluster (SegCluster & cluster)
Definition at line 70 of file SegTools.cpp.
Referenced by baggedSegments(), computeWindowParam(), and normFeat().
LIA_SPKTOOLS_API unsigned long timeToFrameIdx (real_t time, real_t frameLength)
Definition at line 135 of file SegTools.cpp.
Referenced by loadClusterFile(), and loadLabelFile().
LIA_SPKTOOLS_API unsigned long totalFrame (SegCluster & cluster)
Definition at line 77 of file SegTools.cpp.
Referenced by baggedSegments(), baggedSegmentsConstraint(), bicCrit(), clrCrit(), clusteringCriterionWithoutWorldInit(), TopGauss::compute(), computeTransitions(), computeWindowParam(), deltabicCrit(), gllrCrit(), isStopReSeg(), isValidLengthOfLastSpeaker(), isValidSpeaker(), labelFusion(), labelMorphing(), learnModelFromBaggedFrame(), main(), mixtureInit(), mixtureInitBySplit(), modelBasedadaptModel(), NoDataSpeakerVerification(), segmentationProcess(), totalFrame(), and trainModelStream().
LIA_SPKTOOLS_API void verifyClusterFile (SegServer & segmentsServer, FeatureServer & fs, Config & config)
Definition at line 151 of file SegTools.cpp.
References debug, and verbose.
Referenced by adaptModelEMweightedFrames(), cms(), TopGauss::compute(), FactorAnalysisStat::computeAndAccumulateGeneralFAStats(), JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::computeAndAccumulateJFAStatUnThreaded(), TVAcc::computeAndAccumulateTVStat(), TVAcc::computeAndAccumulateTVStatUnThreaded(), computeAndStoreZnormParam(), computeLLRmatrix(), ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), featMap(), featureStream(), featWarp(), GaussianConfusionMatrix(), TopGauss::get(), GMMTokenizer(), infoFeat(), launchAcousticSegmentationProcess(), launchReSegmentationProcess(), launchSegmentationProcess(), launchTurnDetectionProcess(), learnEMimpostorModels(), learnMAPimpostorModels(), FactorAnalysisStat::normalizeFeatures(), normFeat(), normFeatFA(), normFeatLFA(), normFeatNAP(), PolyExpand(), JFAAcc::substractUXfromFeatures(), TrainTarget(), TrainTargetAdapt(), TrainTargetByLabel(), TrainTargetFA(), TrainTargetJFA(), TrainTargetLFA(), TVAcc::verifyEMLK(), and JFAAcc::verifyEMLK().