LIA_RAL: LIA_SpkTools/src/SegTools.cpp File Reference
SegTools.cpp File Reference
#include "SegTools.h"
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
Macros
#define ALIZE_SegTools_cpp
Functions
void showCluster (SegCluster &cluster)
unsigned long totalFrame (SegCluster &cluster)
unsigned long totalFrame (SegServer &s)
unsigned long endSeg (Seg *seg)
void outputLabelFile (SegCluster &selectedSeg, String FileName, Config &config)
void createDefSeg (SegServer &segServer, FeatureServer &fs, Config &config)
unsigned long timeToFrameIdx (real_t time, real_t frameLength)
real_t frameIdxToTime (unsigned long idx, real_t frameLength)
void verifyClusterFile (SegServer &segmentsServer, FeatureServer &fs, Config &config)
void addSegment (const Config &config, const String &file, const String &name, unsigned long segFrameBegin, unsigned long segFrameLength, LabelServer &labelServer, SegServer &segmentsServer)
void loadLabelFile (SegCluster &cluster, String fileName, String path, String extension, Config &config)
void loadClusterFile (String &fileName, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
void initializeClusters (const XLine &listFiles, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
void initializeClusters (const XList &listXFiles, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
void initializeClusters (String &file, SegServer &segmentsServer, LabelServer &labelServer, Config &config)
ViterbiAccum & createAndInitializeViterbiAccum (StatServer &ss, hmm &cHmm)
void accumulateStatViterbi (FeatureServer &fs, ViterbiAccum &va, unsigned long beginIdx, unsigned long length, Config &config)
void accumulateStatViterbi (FeatureServer &fs, ViterbiAccum &va, Seg *seg, Config &config)
void accumulateStatViterbi (FeatureServer &fs, ViterbiAccum &va, Seg *seg, Config &config, SegServer &TransitSegServer, DoubleVector &TransitionsFort, DoubleVector &TransitionsFaible, unsigned long NbState)
void removeAllSeg (SegServer &segServer, SegCluster &cluster)
void initializeCluster (SegServer &currentSeg, hmm &cHmm, LabelServer &labelServer)
bool removePartOfSeg (SegCluster &clusterSeg, SegServer &segServer, LabelServer &labelServer, String segSourceName, unsigned long segStart, unsigned long segLength)
void displayAllClusters (Config &config, SegServer &seg)
void displayOneCluster (Config &config, SegCluster &clusterT)
void displayAllSegments (Config &config, SegServer &seg)
void displayAllSegmentsFromRef (Config &config, String &fileInit, unsigned long fileSize)
long findLabel (XLine classToAnalyse, String labelToFind)
void moveSegmentFromOneClusterToAnother (LabelServer &labelServer, Seg *segment, SegCluster &currentCluster, SegCluster &newCluster)
Seg * longerSegment (Config &config, SegCluster &cluster)
unsigned long findClusterIndex (String name, SegServer &segTmp)
Macro Definition Documentation
#define ALIZE_SegTools_cpp
Definition at line 56 of file SegTools.cpp.
Function Documentation
void accumulateStatViterbi (FeatureServer & fs, ViterbiAccum & va, unsigned long beginIdx, unsigned long length, Config & config)
Definition at line 336 of file SegTools.cpp.
Referenced by accumulateStatViterbi(), and viterbiDecoding().
void accumulateStatViterbi (FeatureServer & fs, ViterbiAccum & va, Seg * seg, Config & config)
Definition at line 347 of file SegTools.cpp.
References accumulateStatViterbi().
void accumulateStatViterbi (FeatureServer & fs, ViterbiAccum & va, Seg * seg, Config & config, SegServer & TransitSegServer, DoubleVector & TransitionsFort, DoubleVector & TransitionsFaible, unsigned long NbState)
Definition at line 355 of file SegTools.cpp.
References log().
void addSegment (const Config & config, const String & file, const String & name, unsigned long segFrameBegin, unsigned long segFrameLength, LabelServer & labelServer, SegServer & segmentsServer)
Definition at line 177 of file SegTools.cpp.
References debug, and verboseLevel.
Referenced by loadClusterFile().
ViterbiAccum& createAndInitializeViterbiAccum (StatServer & ss, hmm & cHmm)
Definition at line 323 of file SegTools.cpp.
References hmm::getDensity(), hmm::getNbState(), hmm::getTransition(), and log().
Referenced by viterbiDecoding().
void createDefSeg (SegServer & segServer, FeatureServer & fs, Config & config)
Definition at line 124 of file SegTools.cpp.
void displayAllClusters (Config & config, SegServer & seg)
Definition at line 451 of file SegTools.cpp.
References displayOneCluster().
Referenced by addSpeaker(), and TurnDetection().
void displayAllSegments (Config & config, SegServer & seg)
Definition at line 484 of file SegTools.cpp.
References verboseLevel.
Referenced by AcousticSegmentationProcess(), ComputePath(), createClusterDecoding(), launchTurnDetectionProcess(), ReSegmentationProcess(), saveAcousticSegmentation(), saveSegmentation(), and segmentationProcess().
void displayAllSegmentsFromRef (Config & config, String & fileInit, unsigned long fileSize)
Definition at line 544 of file SegTools.cpp.
References initializeClusters(), verbose, and verboseLevel.
Referenced by launchAcousticSegmentationProcess(), launchReSegmentationProcess(), launchSegmentationProcess(), and launchTurnDetectionProcess().
void displayOneCluster (Config & config, SegCluster & clusterT)
Definition at line 464 of file SegTools.cpp.
Referenced by addSpeaker(), and displayAllClusters().
unsigned long endSeg (Seg * seg)
Definition at line 99 of file SegTools.cpp.
Referenced by aggregateSegment(), applyLengthRules(), bestFittingSegment(), clusteringCriterion(), clusteringCriterionByAdapt(), clusteringCriterionWithoutWorldInit(), computeLabelNGram(), interCluster(), interSeg(), intraCluster(), morphologicalFilter(), and TurnDetection().
unsigned long findClusterIndex (String name, SegServer & segTmp)
Definition at line 654 of file SegTools.cpp.
long findLabel (XLine classToAnalyse, String labelToFind)
Definition at line 605 of file SegTools.cpp.
real_t frameIdxToTime (unsigned long idx, real_t frameLength)
Definition at line 143 of file SegTools.cpp.
Referenced by ComputeTest(), ComputeTestNAP(), computeWindowParam(), inMiddle(), main(), outputLabelFile(), and windowLength().
void initializeCluster (SegServer & currentSeg, hmm & cHmm, LabelServer & labelServer)
Definition at line 399 of file SegTools.cpp.
References hmm::getNbState(), and hmm::getStateName().
Referenced by viterbiDecoding().
void initializeClusters (const XLine & listFiles, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 289 of file SegTools.cpp.
References loadClusterFile().
Referenced by adaptModelEMweightedFrames(), cms(), TopGauss::compute(), FactorAnalysisStat::computeAndAccumulateGeneralFAStats(), JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::computeAndAccumulateJFAStatUnThreaded(), TVAcc::computeAndAccumulateTVStat(), TVAcc::computeAndAccumulateTVStatUnThreaded(), computeAndStoreZnormParam(), computeLLRmatrix(), ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), displayAllSegmentsFromRef(), energyDetector(), featMap(), featureStream(), featWarp(), GaussianConfusionMatrix(), TopGauss::get(), GMMTokenizer(), infoFeat(), InfoTarget(), initClusterReSeg(), initializeClusters(), launchAcousticSegmentationProcess(), launchReSegmentationProcess(), launchSegmentationProcess(), launchTurnDetectionProcess(), learnEMimpostorModels(), learnMAPimpostorModels(), FactorAnalysisStat::normalizeFeatures(), normFeat(), normFeatFA(), normFeatLFA(), normFeatNAP(), PolyExpand(), JFAAcc::substractUXfromFeatures(), TrainTarget(), TrainTargetAdapt(), TrainTargetByLabel(), TrainTargetFA(), TrainTargetJFA(), TrainTargetLFA(), TVAcc::verifyEMLK(), and JFAAcc::verifyEMLK().
void initializeClusters (const XList & listXFiles, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 299 of file SegTools.cpp.
References initializeClusters().
void initializeClusters (String & file, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 305 of file SegTools.cpp.
References initializeClusters(), and loadClusterFile().
void loadClusterFile (String & fileName, SegServer & segmentsServer, LabelServer & labelServer, Config & config)
Definition at line 216 of file SegTools.cpp.
References addSegment(), debug, timeToFrameIdx(), verbose, and verboseLevel.
Referenced by initializeClusters(), labelFusion(), labelMorphing(), labelNGram(), main(), and sequenceDecoder().
void loadLabelFile (SegCluster & cluster, String fileName, String path, String extension, Config & config)
Definition at line 197 of file SegTools.cpp.
References timeToFrameIdx(), and verboseLevel.
Seg* longerSegment (Config & config, SegCluster & cluster)
Definition at line 628 of file SegTools.cpp.
void moveSegmentFromOneClusterToAnother (LabelServer & labelServer, Seg * segment, SegCluster & currentCluster, SegCluster & newCluster)
Definition at line 615 of file SegTools.cpp.
Referenced by CleanSpeaker().
void outputLabelFile (SegCluster & selectedSeg, String FileName, Config & config)
Definition at line 106 of file SegTools.cpp.
References debug, and frameIdxToTime().
Referenced by labelFusion(), labelMorphing(), labelNGram(), and main().
void removeAllSeg (SegServer & segServer, SegCluster & cluster)
Definition at line 390 of file SegTools.cpp.
bool removePartOfSeg (SegCluster & clusterSeg, SegServer & segServer, LabelServer & labelServer, String segSourceName, unsigned long segStart, unsigned long segLength)
Definition at line 414 of file SegTools.cpp.
Referenced by addSpeaker().
void showCluster (SegCluster & cluster)
Definition at line 70 of file SegTools.cpp.
Referenced by baggedSegments(), computeWindowParam(), and normFeat().
unsigned long timeToFrameIdx (real_t time, real_t frameLength)
Definition at line 135 of file SegTools.cpp.
Referenced by loadClusterFile(), and loadLabelFile().
unsigned long totalFrame (SegCluster & cluster)
Definition at line 77 of file SegTools.cpp.
Referenced by baggedSegments(), baggedSegmentsConstraint(), bicCrit(), clrCrit(), clusteringCriterionWithoutWorldInit(), TopGauss::compute(), computeTransitions(), computeWindowParam(), deltabicCrit(), gllrCrit(), isStopReSeg(), isValidLengthOfLastSpeaker(), isValidSpeaker(), labelFusion(), labelMorphing(), learnModelFromBaggedFrame(), main(), mixtureInit(), mixtureInitBySplit(), modelBasedadaptModel(), NoDataSpeakerVerification(), segmentationProcess(), totalFrame(), and trainModelStream().
unsigned long totalFrame (SegServer & s)
Definition at line 88 of file SegTools.cpp.
References totalFrame().
void verifyClusterFile (SegServer & segmentsServer, FeatureServer & fs, Config & config)
Definition at line 151 of file SegTools.cpp.
References debug, and verbose.
Referenced by adaptModelEMweightedFrames(), cms(), TopGauss::compute(), FactorAnalysisStat::computeAndAccumulateGeneralFAStats(), JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::computeAndAccumulateJFAStatUnThreaded(), TVAcc::computeAndAccumulateTVStat(), TVAcc::computeAndAccumulateTVStatUnThreaded(), computeAndStoreZnormParam(), computeLLRmatrix(), ComputeTest(), ComputeTestByLabel(), ComputeTestHisto(), ComputeTestJFA(), ComputeTestLFA(), ComputeTestNAP(), featMap(), featureStream(), featWarp(), GaussianConfusionMatrix(), TopGauss::get(), GMMTokenizer(), infoFeat(), launchAcousticSegmentationProcess(), launchReSegmentationProcess(), launchSegmentationProcess(), launchTurnDetectionProcess(), learnEMimpostorModels(), learnMAPimpostorModels(), FactorAnalysisStat::normalizeFeatures(), normFeat(), normFeatFA(), normFeatLFA(), normFeatNAP(), PolyExpand(), JFAAcc::substractUXfromFeatures(), TrainTarget(), TrainTargetAdapt(), TrainTargetByLabel(), TrainTargetFA(), TrainTargetJFA(), TrainTargetLFA(), TVAcc::verifyEMLK(), and JFAAcc::verifyEMLK().