LIA_RAL: LIA_Utils/SequenceExtractor/src/SequenceExtractor.cpp File Reference
SequenceExtractor.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <string>
#include "liatools.h"
#include "BNGram.h"
#include "SequenceExtractor.h"
Macros
#define ALIZE_SequenceExtractor_cpp
Functions
int sequenceDecoder (Config &config)
int sequenceExtractor (Config &config)
Macro Definition Documentation
#define ALIZE_SequenceExtractor_cpp
Definition at line 56 of file SequenceExtractor.cpp.
Function Documentation
int sequenceDecoder (Config & config)
Definition at line 677 of file SequenceExtractor.cpp.
References SequenceDecoder::decode(), SequenceDecoder::load(), loadClusterFile(), and BNgram::show().
int sequenceExtractor (Config & config)
Definition at line 732 of file SequenceExtractor.cpp.
References SequenceDecoder::addSequence(), debug, Seq::getLength(), Seq::init(), NGram::load(), SequenceDecoder::save(), SequenceDecoder::setNbOutputSeq(), Seq::show(), SequenceDecoder::show(), NGram::showTable(), SequenceDecoder::toFile(), verbose, and verboseLevel.