LIA_RAL: LIA_SpkDet/SpkAdapt/src/SpkAdapt.cpp File Reference
SpkAdapt.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "SpkAdapt.h"
#include "FileInfo.h"
#include "UnsupervisedTools.h"
Macros
#define ALIZE_SpkAdapt_cpp
Functions
int TrainTargetAdapt (Config &config, Config &configTest)
Macro Definition Documentation
#define ALIZE_SpkAdapt_cpp
Definition at line 56 of file SpkAdapt.cpp.
Function Documentation
int TrainTargetAdapt (Config & config, Config & configTest)
Definition at line 90 of file SpkAdapt.cpp.
References adaptModel(), adaptModelEM(), assessAdaptation(), computeAndStoreZnormParam(), computeFastLLR(), computeLLR(), computeMAPmodelFromEMones(), copyCluster(), crossValid(), debug, expandLLR(), FileExists(), findNearestLLRInMatrix(), fuseMAP(), getFullFileName(), getFullMixtureName(), initializeClusters(), loadTnormParam(), normalizeScore(), Oracle(), searchLLRFromResFile(), SegClusterFrame(), selectNearestTarModel(), verbose, verboseLevel, verifyClusterFile(), WMAP(), WMAPGMM(), WMAPGMMFixedPriors(), and znorm().