LIA_RAL: LIA_SpkDet/CovIntra/src/SVDLIBC/svdlib.h File Reference
svdlib.h File Reference
Classes
struct smat
struct dmat
struct svdrec
Macros
#define FALSE 0
#define TRUE 1
#define SVD_IS_SPARSE(format) ((format >= SVD_F_STH) && (format <= SVD_F_SB))
Typedefs
typedef struct smat * SMat
typedef struct dmat * DMat
typedef struct svdrec * SVDRec
Enumerations
enum svdCounters {
SVD_MXV, SVD_COUNTERS, SVD_MXV, SVD_COUNTERS,
SVD_MXV, SVD_COUNTERS
}
enum svdFileFormats {
SVD_F_STH, SVD_F_ST, SVD_F_SB, SVD_F_DT,
SVD_F_DB, SVD_F_STH, SVD_F_ST, SVD_F_SB,
SVD_F_DT, SVD_F_DB, SVD_F_STH, SVD_F_ST,
SVD_F_SB, SVD_F_DT, SVD_F_DB
}
Functions
void svdResetCounters (void)
DMat svdNewDMat (int rows, int cols)
void svdFreeDMat (DMat D)
SMat svdNewSMat (int rows, int cols, int vals)
void svdFreeSMat (SMat S)
SVDRec svdNewSVDRec (void)
void svdFreeSVDRec (SVDRec R)
DMat svdConvertStoD (SMat S)
SMat svdConvertDtoS (DMat D)
DMat svdTransposeD (DMat D)
SMat svdTransposeS (SMat S)
void svdWriteDenseArray (double *a, int n, char *filename, char binary)
double * svdLoadDenseArray (char *filename, int *np, char binary)
SMat svdLoadSparseMatrix (char *filename, int format)
DMat svdLoadDenseMatrix (char *filename, int format)
void svdWriteDenseMatrix (DMat A, char *filename, int format)
void svdWriteSparseMatrix (SMat A, char *filename, int format)
SVDRec svdLAS2 (SMat A, long dimensions, long iterations, double end[2], double kappa)
SVDRec svdLAS2A (SMat A, long dimensions)
Variables
char * SVDVersion
long SVDVerbosity
long SVDCount [SVD_COUNTERS]
Macro Definition Documentation
#define FALSE 0
Definition at line 5 of file svdlib.h.
#define SVD_IS_SPARSE (format) ((format >= SVD_F_STH) && (format <= SVD_F_SB))
Definition at line 67 of file svdlib.h.
#define TRUE 1
Definition at line 8 of file svdlib.h.
Typedef Documentation
typedef struct dmat* DMat
Definition at line 13 of file svdlib.h.
typedef struct smat* SMat
Definition at line 12 of file svdlib.h.
typedef struct svdrec* SVDRec
Definition at line 14 of file svdlib.h.
Enumeration Type Documentation
enum svdCounters
Enumerator
SVD_MXV
SVD_COUNTERS
SVD_MXV
SVD_COUNTERS
SVD_MXV
SVD_COUNTERS
Definition at line 52 of file svdlib.h.
enum svdFileFormats
Enumerator
SVD_F_STH
SVD_F_ST
SVD_F_SB
SVD_F_DT
SVD_F_DB
SVD_F_STH
SVD_F_ST
SVD_F_SB
SVD_F_DT
SVD_F_DB
SVD_F_STH
SVD_F_ST
SVD_F_SB
SVD_F_DT
SVD_F_DB
Definition at line 56 of file svdlib.h.
Function Documentation
SMat svdConvertDtoS (DMat D)
Definition at line 104 of file svdlib.c.
References smat::cols, dmat::cols, smat::pointr, smat::rowind, dmat::rows, svd_error(), svdNewSMat(), smat::vals, smat::value, and dmat::value.
Referenced by svdLoadSparseMatrix(), and svdWriteDenseMatrix().
DMat svdConvertStoD (SMat S)
Definition at line 89 of file svdlib.c.
References smat::cols, smat::pointr, smat::rowind, smat::rows, svd_error(), svdNewDMat(), smat::vals, smat::value, and dmat::value.
Referenced by svdLoadDenseMatrix(), and svdWriteSparseMatrix().
void svdFreeDMat (DMat D)
Definition at line 37 of file svdlib.c.
References SAFE_FREE, and dmat::value.
Referenced by svdFreeSVDRec(), svdLoadSparseMatrix(), and svdWriteSparseMatrix().
void svdFreeSMat (SMat S)
Definition at line 60 of file svdlib.c.
References smat::pointr, smat::rowind, SAFE_FREE, and smat::value.
Referenced by svdLoadDenseMatrix(), svdNewSMat(), and svdWriteDenseMatrix().
void svdFreeSVDRec (SVDRec R)
Definition at line 77 of file svdlib.c.
References svdrec::S, SAFE_FREE, svdFreeDMat(), svdrec::Ut, and svdrec::Vt.
SVDRec svdLAS2 (SMat A, long dimensions, long iterations, double end[2], double kappa)
Definition at line 326 of file las2.c.
References check_parameters(), smat::cols, svdrec::d, eps, eps1, eps34, FALSE, lanso(), LanStore, machar(), MAXLL, OPBTemp, reps, ritvec(), smat::rows, svdrec::S, SAFE_FREE, sqrt(), svd_dmax(), svd_doubleArray(), svd_error(), SVD_F_DT, svd_imin(), svdFreeSMat(), svdNewDMat(), svdNewSVDRec(), svdResetCounters(), svdTransposeS(), SVDVerbosity, svdWriteDenseArray(), svdWriteDenseMatrix(), TRUE, svdrec::Ut, smat::vals, svdrec::Vt, and write_header().
Referenced by svdLAS2A().
SVDRec svdLAS2A (SMat A, long dimensions)
Definition at line 315 of file las2.c.
References svd_error(), and svdLAS2().
double* svdLoadDenseArray (char * filename, int * np, char binary)
Definition at line 183 of file svdlib.c.
References FALSE, svd_closeFile(), svd_doubleArray(), svd_error(), svd_readBinFloat(), svd_readBinInt(), and svd_readFile().
DMat svdLoadDenseMatrix (char * filename, int format)
Definition at line 478 of file svdlib.c.
References svd_closeFile(), svd_error(), SVD_F_DB, SVD_F_DT, SVD_F_SB, SVD_F_ST, SVD_F_STH, svd_fatalReadFile(), svdConvertStoD(), svdFreeSMat(), svdLoadDenseBinaryFile(), svdLoadDenseTextFile(), svdLoadSparseBinaryFile(), svdLoadSparseTextFile(), and svdLoadSparseTextHBFile().
SMat svdLoadSparseMatrix (char * filename, int format)
Definition at line 448 of file svdlib.c.
References svd_closeFile(), svd_error(), SVD_F_DB, SVD_F_DT, SVD_F_SB, SVD_F_ST, SVD_F_STH, svd_fatalReadFile(), svdConvertDtoS(), svdFreeDMat(), svdLoadDenseBinaryFile(), svdLoadDenseTextFile(), svdLoadSparseBinaryFile(), svdLoadSparseTextFile(), and svdLoadSparseTextHBFile().
DMat svdNewDMat (int rows, int cols)
Definition at line 20 of file svdlib.c.
References dmat::cols, dmat::rows, SAFE_FREE, and dmat::value.
Referenced by svdConvertStoD(), svdLoadDenseBinaryFile(), svdLoadDenseTextFile(), and svdTransposeD().
SMat svdNewSMat (int rows, int cols, int vals)
Definition at line 45 of file svdlib.c.
References smat::cols, FALSE, smat::pointr, smat::rowind, smat::rows, svd_doubleArray(), svd_longArray(), svdFreeSMat(), TRUE, smat::vals, and smat::value.
Referenced by svdConvertDtoS(), svdLoadSparseBinaryFile(), svdLoadSparseTextFile(), svdLoadSparseTextHBFile(), and svdTransposeS().
SVDRec svdNewSVDRec (void)
Definition at line 70 of file svdlib.c.
void svdResetCounters (void)
Definition at line 10 of file svdlib.c.
References SVD_COUNTERS, and SVDCount.
DMat svdTransposeD (DMat D)
Definition at line 130 of file svdlib.c.
References dmat::cols, dmat::rows, svdNewDMat(), and dmat::value.
SMat svdTransposeS (SMat S)
Definition at line 140 of file svdlib.c.
References smat::cols, smat::pointr, smat::rowind, smat::rows, svdNewSMat(), smat::vals, and smat::value.
void svdWriteDenseArray (double * a, int n, char * filename, char binary)
Definition at line 166 of file svdlib.c.
References FALSE, svd_closeFile(), svd_error(), svd_writeBinFloat(), svd_writeBinInt(), and svd_writeFile().
void svdWriteDenseMatrix (DMat A, char * filename, int format)
Definition at line 539 of file svdlib.c.
References FALSE, svd_closeFile(), svd_error(), SVD_F_DB, SVD_F_DT, SVD_F_SB, SVD_F_ST, SVD_F_STH, svd_writeFile(), svdConvertDtoS(), svdFreeSMat(), svdWriteDenseBinaryFile(), svdWriteDenseTextFile(), svdWriteSparseBinaryFile(), svdWriteSparseTextFile(), and svdWriteSparseTextHBFile().
void svdWriteSparseMatrix (SMat A, char * filename, int format)
Definition at line 508 of file svdlib.c.
References FALSE, svd_closeFile(), svd_error(), SVD_F_DB, SVD_F_DT, SVD_F_SB, SVD_F_ST, SVD_F_STH, svd_writeFile(), svdConvertStoD(), svdFreeDMat(), svdWriteDenseBinaryFile(), svdWriteDenseTextFile(), svdWriteSparseBinaryFile(), svdWriteSparseTextFile(), and svdWriteSparseTextHBFile().
Variable Documentation
long SVDCount[SVD_COUNTERS]
Definition at line 8 of file svdlib.c.
Referenced by svdResetCounters().
long SVDVerbosity
Definition at line 7 of file svdlib.c.
char* SVDVersion
Definition at line 6 of file svdlib.c.
Referenced by svdWriteSparseTextHBFile().