LIA_RAL: LIA_Utils/Svm/src/libsvm.h File Reference
libsvm.h File Reference
Classes
struct svm_node
struct svm_problem
struct svm_parameter
struct svm_model
Macros
#define LIBSVM_VERSION 300
Enumerations
enum {
C_SVC, NU_SVC, ONE_CLASS, EPSILON_SVR,
NU_SVR
}
enum {
LINEAR, POLY, RBF, SIGMOID,
PRECOMPUTED
}
Functions
struct svm_model * svm_train (const struct svm_problem *prob, const struct svm_parameter *param)
void svm_cross_validation (const struct svm_problem *prob, const struct svm_parameter *param, int nr_fold, double *target)
int svm_save_model (const char *model_file_name, const struct svm_model *model)
struct svm_model * svm_load_model (const char *model_file_name)
int svm_get_svm_type (const struct svm_model *model)
int svm_get_nr_class (const struct svm_model *model)
void svm_get_labels (const struct svm_model *model, int *label)
double svm_get_svr_probability (const struct svm_model *model)
double svm_predict_values (const struct svm_model *model, const struct svm_node *x, double *dec_values)
double svm_predict (const struct svm_model *model, const struct svm_node *x)
double svm_predict_probability (const struct svm_model *model, const struct svm_node *x, double *prob_estimates)
void svm_free_model_content (struct svm_model *model_ptr)
void svm_free_and_destroy_model (struct svm_model **model_ptr_ptr)
void svm_destroy_param (struct svm_parameter *param)
const char * svm_check_parameter (const struct svm_problem *prob, const struct svm_parameter *param)
int svm_check_probability_model (const struct svm_model *model)
void svm_set_print_string_function (void(*print_func)(const char *))
void svm_destroy_model (struct svm_model *model_ptr)
Variables
int libsvm_version
Macro Definition Documentation
#define LIBSVM_VERSION 300
Definition at line 4 of file libsvm.h.
Enumeration Type Documentation
anonymous enum
Enumerator
C_SVC
NU_SVC
ONE_CLASS
EPSILON_SVR
NU_SVR
Definition at line 25 of file libsvm.h.
anonymous enum
Enumerator
LINEAR
POLY
RBF
SIGMOID
PRECOMPUTED
Definition at line 26 of file libsvm.h.
Function Documentation
const char* svm_check_parameter (const struct svm_problem * prob, const struct svm_parameter * param)
int svm_check_probability_model (const struct svm_model * model)
void svm_cross_validation (const struct svm_problem * prob, const struct svm_parameter * param, int nr_fold, double * target)
void svm_destroy_model (struct svm_model * model_ptr)
Definition at line 2915 of file libsvm.cpp.
References svm_free_and_destroy_model().
void svm_destroy_param (struct svm_parameter * param)
Definition at line 2921 of file libsvm.cpp.
References svm_parameter::weight, and svm_parameter::weight_label.
Referenced by svm_binary_svc_probability().
void svm_free_and_destroy_model (struct svm_model ** model_ptr_ptr)
Definition at line 2905 of file libsvm.cpp.
References svm_free_model_content().
Referenced by svm_binary_svc_probability(), svm_cross_validation(), and svm_destroy_model().
void svm_free_model_content (struct svm_model * model_ptr)
Definition at line 2890 of file libsvm.cpp.
References svm_model::free_sv, svm_model::l, svm_model::label, svm_model::nr_class, svm_model::nSV, svm_model::probA, svm_model::probB, svm_model::rho, svm_model::SV, and svm_model::sv_coef.
Referenced by svm_free_and_destroy_model().
void svm_get_labels (const struct svm_model * model, int * label)
int svm_get_nr_class (const struct svm_model * model)
int svm_get_svm_type (const struct svm_model * model)
double svm_get_svr_probability (const struct svm_model * model)
struct svm_model* svm_load_model (const char * model_file_name)
Definition at line 2690 of file libsvm.cpp.
References svm_parameter::coef0, svm_parameter::degree, svm_model::free_sv, svm_parameter::gamma, svm_node::index, svm_parameter::kernel_type, kernel_type_table, svm_model::l, svm_model::label, line, Malloc, max_line_len, svm_model::nr_class, svm_model::nSV, svm_model::param, svm_model::probA, svm_model::probB, readline(), svm_model::rho, svm_model::SV, svm_model::sv_coef, svm_parameter::svm_type, svm_type_table, and svm_node::value.
double svm_predict (const struct svm_model * model, const struct svm_node * x)
double svm_predict_probability (const struct svm_model * model, const struct svm_node * x, double * prob_estimates)
double svm_predict_values (const struct svm_model * model, const struct svm_node * x, double * dec_values)
int svm_save_model (const char * model_file_name, const struct svm_model * model)
void svm_set_print_string_function (void(*)(const char *) print_func)
Definition at line 3056 of file libsvm.cpp.
References print_string_stdout(), and svm_print_string.
struct svm_model* svm_train (const struct svm_problem * prob, const struct svm_parameter * param)
Variable Documentation
int libsvm_version
Definition at line 11 of file libsvm.cpp.