LIA_RAL: Eigen::ei_quaternion_assign_impl< Other, 3, 3 > Struct Template Reference
Eigen::ei_quaternion_assign_impl< Other, 3, 3 > Struct Template Reference
#include <Quaternion.h>
Public Types
typedef Other::Scalar Scalar
Static Public Member Functions
static void run (Quaternion< Scalar > &q, const Other &mat)
Detailed Description
template<typename Other>
struct Eigen::ei_quaternion_assign_impl< Other, 3, 3 >
Definition at line 447 of file Quaternion.h.
Member Typedef Documentation
template<typename Other > typedef Other::Scalar Eigen::ei_quaternion_assign_impl< Other, 3, 3 >::Scalar
Definition at line 449 of file Quaternion.h.
Member Function Documentation
template<typename Other > static void Eigen::ei_quaternion_assign_impl< Other, 3, 3 >::run (Quaternion< Scalar > & q, const Other & mat) inline static
Definition at line 450 of file Quaternion.h.
References Eigen::Quaternion< _Scalar >::coeffs(), Eigen::ei_sqrt(), Eigen::Quaternion< _Scalar >::w(), Eigen::Quaternion< _Scalar >::x(), Eigen::Quaternion< _Scalar >::y(), and Eigen::Quaternion< _Scalar >::z().
The documentation for this struct was generated from the following file:
include/Eigen/src/Eigen2Support/Geometry/Quaternion.h