LIA_RAL: Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true > Struct Template Reference
Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true > Struct Template Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet1cd pmadd (const Packet1cd &x, const Packet1cd &y, const Packet1cd &c) const
EIGEN_STRONG_INLINE Packet1cd pmul (const Packet1cd &a, const Packet1cd &b) const
Detailed Description
template<>
struct Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >
Definition at line 347 of file Complex.h.
Member Function Documentation
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmadd (const Packet1cd & x, const Packet1cd & y, const Packet1cd & c) const inline
Definition at line 349 of file Complex.h.
References Eigen::internal::padd(), and Eigen::internal::pmul().
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::conj_helper< Packet1cd, Packet1cd, false, true >::pmul (const Packet1cd & a, const Packet1cd & b) const inline
Definition at line 352 of file Complex.h.
References Eigen::internal::pconj(), Eigen::internal::pmul(), Eigen::internal::Packet1cd::v, and vec2d_swizzle1.
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/arch/SSE/Complex.h