LIA_RAL: Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version > Struct Template Reference
Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version > Struct Template Reference
#include <TriangularMatrixMatrix.h>
Public Types
enum { SmallPanelWidth = EIGEN_PLAIN_ENUM_MAX(Traits::mr,Traits::nr), IsLower = (Mode&Lower) == Lower, SetDiag = (Mode&(ZeroDiag|UnitDiag)) ? 0 : 1 }
typedef gebp_traits< Scalar,
Scalar > Traits
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index _rows, Index _cols, Index _depth, const Scalar *_lhs, Index lhsStride, const Scalar *_rhs, Index rhsStride, Scalar *res, Index resStride, Scalar alpha, level3_blocking< Scalar, Scalar > &blocking)
Detailed Description
template<typename Scalar, typename Index, int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version>
struct Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >
Definition at line 212 of file TriangularMatrixMatrix.h.
Member Typedef Documentation
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> typedef gebp_traits<Scalar,Scalar> Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::Traits
Definition at line 216 of file TriangularMatrixMatrix.h.
Member Enumeration Documentation
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> anonymous enum
Enumerator
SmallPanelWidth
IsLower
SetDiag
Definition at line 217 of file TriangularMatrixMatrix.h.
Member Function Documentation
template<typename Scalar , typename Index , int Mode, int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int Version> static EIGEN_DONT_INLINE void Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >::run (Index _rows, Index _cols, Index _depth, const Scalar * _lhs, Index lhsStride, const Scalar * _rhs, Index rhsStride, Scalar * res, Index resStride, Scalar alpha, level3_blocking< Scalar, Scalar > & blocking) inline static
Definition at line 223 of file TriangularMatrixMatrix.h.
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockW(), ei_declare_aligned_stack_constructed_variable, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc(), min(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::ZeroDiag.
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/products/TriangularMatrixMatrix.h