LIA_RAL: Eigen::internal::trmv_selector< ColMajor > Struct Template Reference
Eigen::internal::trmv_selector< ColMajor > Struct Template Reference
#include <TriangularMatrixVector.h>
Static Public Member Functions
template<int Mode, typename Lhs , typename Rhs , typename Dest >
static void run (const TriangularProduct< Mode, true, Lhs, false, Rhs, true > &prod, Dest &dest, typename TriangularProduct< Mode, true, Lhs, false, Rhs, true >::Scalar alpha)
Detailed Description
template<>
struct Eigen::internal::trmv_selector< ColMajor >
Definition at line 205 of file TriangularMatrixVector.h.
Member Function Documentation
template<int Mode, typename Lhs , typename Rhs , typename Dest > static void Eigen::internal::trmv_selector< ColMajor >::run (const TriangularProduct< Mode, true, Lhs, false, Rhs, true > & prod, Dest & dest, typename TriangularProduct< Mode, true, Lhs, false, Rhs, true >::Scalar alpha) inline static
Definition at line 208 of file TriangularMatrixVector.h.
References Eigen::Aligned, Eigen::ColMajor, ei_declare_aligned_stack_constructed_variable, imag(), Eigen::ProductBase< Derived, Lhs, Rhs >::lhs(), Eigen::ProductBase< Derived, Lhs, Rhs >::rhs(), and Eigen::internal::get_factor< From, To >::run().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/products/TriangularMatrixVector.h