LIA_RAL: Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 > Struct Template Reference
Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 > Struct Template Reference
#include <Transform.h>
Public Types
typedef Other::Scalar Scalar
typedef Transform< Scalar, Dim > TransformType
typedef Matrix< Scalar, Dim, 1 > ResultType
Static Public Member Functions
static ResultType run (const TransformType &tr, const Other &other)
Detailed Description
template<typename Other, int Dim, int HDim>
struct Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >
Definition at line 776 of file Transform.h.
Member Typedef Documentation
template<typename Other , int Dim, int HDim> typedef Matrix<Scalar,Dim,1> Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::ResultType
Definition at line 780 of file Transform.h.
template<typename Other , int Dim, int HDim> typedef Other::Scalar Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::Scalar
Definition at line 778 of file Transform.h.
template<typename Other , int Dim, int HDim> typedef Transform<Scalar,Dim> Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::TransformType
Definition at line 779 of file Transform.h.
Member Function Documentation
template<typename Other , int Dim, int HDim> static ResultType Eigen::ei_transform_product_impl< Other, Dim, HDim, Dim, 1 >::run (const TransformType & tr, const Other & other) inline static
Definition at line 781 of file Transform.h.
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Transform< _Scalar, _Dim >::linear(), Eigen::Transform< _Scalar, _Dim >::matrix(), and Eigen::Transform< _Scalar, _Dim >::translation().
The documentation for this struct was generated from the following file:
include/Eigen/src/Eigen2Support/Geometry/Transform.h