LIA_RAL: Eigen::internal::image_retval< FullPivLU< _MatrixType > > Struct Template Reference
Eigen::internal::image_retval< FullPivLU< _MatrixType > > Struct Template Reference
#include <FullPivLU.h>
Public Types
enum { MaxSmallDimAtCompileTime }
Public Types inherited from Eigen::internal::image_retval_base< FullPivLU< _MatrixType > >
typedef _DecompositionType DecompositionType
typedef FullPivLU< _MatrixType >
::MatrixType MatrixType
typedef ReturnByValue
< image_retval_base > Base
typedef Base::Index Index
Public Types inherited from Eigen::ReturnByValue< image_retval_base< _DecompositionType > >
typedef internal::traits
< image_retval_base
< _DecompositionType >
>::ReturnType ReturnType
typedef
internal::dense_xpr_base
< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::internal::image_retval_base< FullPivLU< _MatrixType > >
image_retval_base (const FullPivLU< _MatrixType > &dec, const MatrixType &originalMatrix)
Index rows () const
Index cols () const
Index rank () const
const FullPivLU< _MatrixType > & dec () const
const MatrixType & originalMatrix () const
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< image_retval_base< _DecompositionType > >
void evalTo (Dest &dst) const
Index rows () const
Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Additional Inherited Members
Protected Attributes inherited from Eigen::internal::image_retval_base< FullPivLU< _MatrixType > >
const FullPivLU< _MatrixType > & m_dec
Index m_rank
Index m_cols
const MatrixType & m_originalMatrix
Detailed Description
template<typename _MatrixType>
struct Eigen::internal::image_retval< FullPivLU< _MatrixType > >
Definition at line 623 of file FullPivLU.h.
Member Enumeration Documentation
template<typename _MatrixType > anonymous enum
Enumerator
MaxSmallDimAtCompileTime
Definition at line 628 of file FullPivLU.h.
Member Function Documentation
template<typename _MatrixType > template<typename Dest > void Eigen::internal::image_retval< FullPivLU< _MatrixType > >::evalTo (Dest & dst) const inline
Definition at line 633 of file FullPivLU.h.
References abs(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeff(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::coeffRef(), and eigen_internal_assert.
The documentation for this struct was generated from the following file:
include/Eigen/src/LU/FullPivLU.h