LIA_RAL: Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false > Struct Template Reference
Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false > Struct Template Reference
#include <BlasUtil.h>
Public Types
typedef std::complex< RealScalar > Scalar
Public Member Functions
EIGEN_STRONG_INLINE Scalar pmadd (const Scalar &x, const Scalar &y, const Scalar &c) const
EIGEN_STRONG_INLINE Scalar pmul (const Scalar &x, const Scalar &y) const
Detailed Description
template<typename RealScalar>
struct Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >
Definition at line 73 of file BlasUtil.h.
Member Typedef Documentation
template<typename RealScalar > typedef std::complex<RealScalar> Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::Scalar
Definition at line 75 of file BlasUtil.h.
Member Function Documentation
template<typename RealScalar > EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmadd (const Scalar & x, const Scalar & y, const Scalar & c) const inline
Definition at line 76 of file BlasUtil.h.
References Eigen::internal::pmul().
template<typename RealScalar > EIGEN_STRONG_INLINE Scalar Eigen::internal::conj_helper< std::complex< RealScalar >, std::complex< RealScalar >, true, false >::pmul (const Scalar & x, const Scalar & y) const inline
Definition at line 79 of file BlasUtil.h.
References imag(), and real().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/util/BlasUtil.h