LIA_RAL: Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 > Struct Template Reference
Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 > Struct Template Reference
#include <Inverse.h>
Static Public Member Functions
static void run (const MatrixType &matrix, const typename MatrixType::RealScalar &absDeterminantThreshold, ResultType &inverse, typename ResultType::Scalar &determinant, bool &invertible)
Detailed Description
template<typename MatrixType, typename ResultType>
struct Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >
Definition at line 160 of file Inverse.h.
Member Function Documentation
template<typename MatrixType , typename ResultType > static void Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 3 >::run (const MatrixType & matrix, const typename MatrixType::RealScalar & absDeterminantThreshold, ResultType & inverse, typename ResultType::Scalar & determinant, bool & invertible) inline static
Definition at line 162 of file Inverse.h.
References abs(), Eigen::PlainObjectBase< Derived >::coeffRef(), and Eigen::internal::compute_inverse_size3_helper().
The documentation for this struct was generated from the following file:
include/Eigen/src/LU/Inverse.h