LIA_RAL: Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned > Struct Template Reference
Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned > Struct Template Reference
#include <Geometry_SSE.h>
Static Public Member Functions
static Quaternion< double > run (const QuaternionBase< Derived > &_a, const QuaternionBase< OtherDerived > &_b)
Detailed Description
template<class Derived, class OtherDerived>
struct Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >
Definition at line 60 of file Geometry_SSE.h.
Member Function Documentation
template<class Derived , class OtherDerived > static Quaternion<double> Eigen::internal::quat_product< Architecture::SSE, Derived, OtherDerived, double, Aligned >::run (const QuaternionBase< Derived > & _a, const QuaternionBase< OtherDerived > & _b) inline static
Definition at line 62 of file Geometry_SSE.h.
References Eigen::QuaternionBase< Derived >::coeffs(), EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmul(), Eigen::internal::preverse(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::pstore(), Eigen::internal::psub(), Eigen::internal::pxor(), Eigen::Quaternion< _Scalar >::x(), and Eigen::Quaternion< _Scalar >::z().
The documentation for this struct was generated from the following file:
include/Eigen/src/Geometry/arch/Geometry_SSE.h