LIA_RAL: Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version > Struct Template Reference
Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version > Struct Template Reference
#include <GeneralMatrixVector.h>
Public Types
enum { Vectorizable, LhsPacketSize = Vectorizable ? packet_traits<LhsScalar>::size : 1, RhsPacketSize = Vectorizable ? packet_traits<RhsScalar>::size : 1, ResPacketSize = Vectorizable ? packet_traits<ResScalar>::size : 1 }
typedef scalar_product_traits
< LhsScalar, RhsScalar >
::ReturnType ResScalar
typedef packet_traits
< LhsScalar >::type _LhsPacket
typedef packet_traits
< RhsScalar >::type _RhsPacket
typedef packet_traits
< ResScalar >::type _ResPacket
typedef conditional
< Vectorizable, _LhsPacket,
LhsScalar >::type LhsPacket
typedef conditional
< Vectorizable, _RhsPacket,
RhsScalar >::type RhsPacket
typedef conditional
< Vectorizable, _ResPacket,
ResScalar >::type ResPacket
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index rows, Index cols, const LhsScalar *lhs, Index lhsStride, const RhsScalar *rhs, Index rhsIncr, ResScalar *res, Index resIncr, ResScalar alpha)
Detailed Description
template<typename Index, typename LhsScalar, bool ConjugateLhs, typename RhsScalar, bool ConjugateRhs, int Version>
struct Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >
Definition at line 289 of file GeneralMatrixVector.h.
Member Typedef Documentation
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> typedef packet_traits<LhsScalar>::type Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::_LhsPacket
Definition at line 301 of file GeneralMatrixVector.h.
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> typedef packet_traits<ResScalar>::type Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::_ResPacket
Definition at line 303 of file GeneralMatrixVector.h.
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> typedef packet_traits<RhsScalar>::type Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::_RhsPacket
Definition at line 302 of file GeneralMatrixVector.h.
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> typedef conditional<Vectorizable,_LhsPacket,LhsScalar>::type Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::LhsPacket
Definition at line 305 of file GeneralMatrixVector.h.
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> typedef conditional<Vectorizable,_ResPacket,ResScalar>::type Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::ResPacket
Definition at line 307 of file GeneralMatrixVector.h.
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> typedef scalar_product_traits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::ResScalar
Definition at line 291 of file GeneralMatrixVector.h.
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> typedef conditional<Vectorizable,_RhsPacket,RhsScalar>::type Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::RhsPacket
Definition at line 306 of file GeneralMatrixVector.h.
Member Enumeration Documentation
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> anonymous enum
Enumerator
Vectorizable
LhsPacketSize
RhsPacketSize
ResPacketSize
Definition at line 293 of file GeneralMatrixVector.h.
Member Function Documentation
template<typename Index , typename LhsScalar , bool ConjugateLhs, typename RhsScalar , bool ConjugateRhs, int Version> static EIGEN_DONT_INLINE void Eigen::internal::general_matrix_vector_product< Index, LhsScalar, RowMajor, ConjugateLhs, RhsScalar, ConjugateRhs, Version >::run (Index rows, Index cols, const LhsScalar * lhs, Index lhsStride, const RhsScalar * rhs, Index rhsIncr, ResScalar * res, Index resIncr, ResScalar alpha) inline static
Definition at line 309 of file GeneralMatrixVector.h.
References _EIGEN_ACCUMULATE_PACKETS, EIGEN_ALIGN16, eigen_internal_assert, EIGEN_UNUSED_VARIABLE, Eigen::internal::first_aligned(), min(), and Eigen::internal::predux().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/products/GeneralMatrixVector.h