LIA_RAL: Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed > Struct Template Reference
Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed > Struct Template Reference
#include <PermutationMatrix.h>
Public Types
typedef remove_all< typename
MatrixType::Nested >::type MatrixTypeNestedCleaned
Public Types inherited from Eigen::ReturnByValue< permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed > >
typedef internal::traits
< permut_matrix_product_retval
< PermutationType, MatrixType,
Side, Transposed >
>::ReturnType ReturnType
typedef
internal::dense_xpr_base
< ReturnByValue >::type Base
Public Member Functions
permut_matrix_product_retval (const PermutationType &perm, const MatrixType &matrix)
int rows () const
int cols () const
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed > >
void evalTo (Dest &dst) const
Index rows () const
Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
const PermutationType & m_permutation
MatrixType::Nested m_matrix
Detailed Description
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false>
struct Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >
Definition at line 45 of file PermutationMatrix.h.
Member Typedef Documentation
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false> typedef remove_all<typename MatrixType::Nested>::type Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::MatrixTypeNestedCleaned
Definition at line 543 of file PermutationMatrix.h.
Constructor & Destructor Documentation
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false> Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::permut_matrix_product_retval (const PermutationType & perm, const MatrixType & matrix) inline
Definition at line 545 of file PermutationMatrix.h.
Member Function Documentation
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false> int Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::cols (void) const inline
Definition at line 550 of file PermutationMatrix.h.
References Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::m_matrix.
Referenced by Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo().
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false> template<typename Dest > void Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo (Dest & dst) const inline
Definition at line 552 of file PermutationMatrix.h.
References Eigen::PlainObjectBase< Derived >::coeffRef(), Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::cols(), Eigen::internal::extract_data(), Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::m_matrix, Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::m_permutation, Eigen::OnTheLeft, Eigen::OnTheRight, Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::rows(), and swap().
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false> int Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::rows (void) const inline
Definition at line 549 of file PermutationMatrix.h.
References Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::m_matrix.
Referenced by Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo().
Member Data Documentation
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false> MatrixType::Nested Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::m_matrix protected
Definition at line 600 of file PermutationMatrix.h.
Referenced by Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::cols(), Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo(), and Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::rows().
template<typename PermutationType, typename MatrixType, int Side, bool Transposed = false> const PermutationType& Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::m_permutation protected
Definition at line 599 of file PermutationMatrix.h.
Referenced by Eigen::internal::permut_matrix_product_retval< PermutationType, MatrixType, Side, Transposed >::evalTo().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/PermutationMatrix.h