LIA_RAL: Eigen::internal::solve_retval< HouseholderQR< _MatrixType >, Rhs > Struct Template Reference
Eigen::internal::solve_retval< HouseholderQR< _MatrixType >, Rhs > Struct Template Reference
#include <HouseholderQR.h>
Public Member Functions
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::internal::solve_retval_base< HouseholderQR< _MatrixType >, Rhs >
solve_retval_base (const HouseholderQR< _MatrixType > &dec, const Rhs &rhs)
Index rows () const
Index cols () const
const HouseholderQR
< _MatrixType > & dec () const
const RhsNestedCleaned & rhs () const
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< solve_retval_base< _DecompositionType, Rhs > >
void evalTo (Dest &dst) const
Index rows () const
Index cols () const
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Additional Inherited Members
Public Types inherited from Eigen::internal::solve_retval_base< HouseholderQR< _MatrixType >, Rhs >
typedef remove_all< typename
Rhs::Nested >::type RhsNestedCleaned
typedef _DecompositionType DecompositionType
typedef ReturnByValue
< solve_retval_base > Base
typedef Base::Index Index
Public Types inherited from Eigen::ReturnByValue< solve_retval_base< _DecompositionType, Rhs > >
typedef internal::traits
< solve_retval_base
< _DecompositionType, Rhs >
>::ReturnType ReturnType
typedef
internal::dense_xpr_base
< ReturnByValue >::type Base
Protected Attributes inherited from Eigen::internal::solve_retval_base< HouseholderQR< _MatrixType >, Rhs >
const HouseholderQR
< _MatrixType > & m_dec
Rhs::Nested m_rhs
Detailed Description
template<typename _MatrixType, typename Rhs>
struct Eigen::internal::solve_retval< HouseholderQR< _MatrixType >, Rhs >
Definition at line 281 of file HouseholderQR.h.
Member Function Documentation
template<typename _MatrixType , typename Rhs > template<typename Dest > void Eigen::internal::solve_retval< HouseholderQR< _MatrixType >, Rhs >::evalTo (Dest & dst) const inline
Definition at line 286 of file HouseholderQR.h.
References eigen_assert, Eigen::householderSequence(), leftCols(), and min().
The documentation for this struct was generated from the following file:
include/Eigen/src/QR/HouseholderQR.h