LIA_RAL: Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true > Struct Template Reference
Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true > Struct Template Reference
#include <JacobiSVD.h>
Public Types
typedef JacobiSVD< MatrixType,
QRPreconditioner > SVD
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef SVD::Index Index
Static Public Member Functions
static void run (typename SVD::WorkMatrixType &work_matrix, SVD &svd, Index p, Index q)
Detailed Description
template<typename MatrixType, int QRPreconditioner>
struct Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >
Definition at line 354 of file JacobiSVD.h.
Member Typedef Documentation
template<typename MatrixType , int QRPreconditioner> typedef SVD::Index Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::Index
Definition at line 359 of file JacobiSVD.h.
template<typename MatrixType , int QRPreconditioner> typedef MatrixType::RealScalar Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::RealScalar
Definition at line 358 of file JacobiSVD.h.
template<typename MatrixType , int QRPreconditioner> typedef MatrixType::Scalar Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::Scalar
Definition at line 357 of file JacobiSVD.h.
template<typename MatrixType , int QRPreconditioner> typedef JacobiSVD<MatrixType, QRPreconditioner> Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::SVD
Definition at line 356 of file JacobiSVD.h.
Member Function Documentation
template<typename MatrixType , int QRPreconditioner> static void Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, QRPreconditioner, true >::run (typename SVD::WorkMatrixType & work_matrix, SVD & svd, Index p, Index q) inline static
Definition at line 360 of file JacobiSVD.h.
References abs(), abs2(), Eigen::JacobiRotation< Scalar >::adjoint(), Eigen::JacobiRotation< Scalar >::c(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::computeU(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::computeV(), Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixU, Eigen::JacobiSVD< MatrixType, QRPreconditioner >::m_matrixV, Eigen::JacobiRotation< Scalar >::s(), and sqrt().
The documentation for this struct was generated from the following file:
include/Eigen/src/SVD/JacobiSVD.h