LIA_RAL: Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite > Struct Template Reference
Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite > Struct Template Reference
#include <SelfAdjointView.h>
Public Types
enum { col = (UnrollCount-1) / Derived1::RowsAtCompileTime, row = (UnrollCount-1) % Derived1::RowsAtCompileTime }
Static Public Member Functions
static void run (Derived1 &dst, const Derived2 &src)
Detailed Description
template<typename Derived1, typename Derived2, int UnrollCount, bool ClearOpposite>
struct Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite >
Definition at line 230 of file SelfAdjointView.h.
Member Enumeration Documentation
template<typename Derived1 , typename Derived2 , int UnrollCount, bool ClearOpposite> anonymous enum
Enumerator
col
row
Definition at line 232 of file SelfAdjointView.h.
Member Function Documentation
template<typename Derived1 , typename Derived2 , int UnrollCount, bool ClearOpposite> static void Eigen::internal::triangular_assignment_selector< Derived1, Derived2,(SelfAdjoint|Lower), UnrollCount, ClearOpposite >::run (Derived1 & dst, const Derived2 & src) inline static
Definition at line 237 of file SelfAdjointView.h.
References col(), Eigen::Lower, real(), row(), and Eigen::SelfAdjoint.
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/SelfAdjointView.h