LIA_RAL: Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex > Struct Template Reference
Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex > Struct Template Reference
#include <PartialPivLU.h>
Public Types
typedef Map< Matrix< Scalar,
Dynamic, Dynamic, StorageOrder > > MapLU
typedef Block< MapLU, Dynamic,
Dynamic > MatrixType
typedef Block< MatrixType,
Dynamic, Dynamic > BlockType
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Index Index
Static Public Member Functions
static Index unblocked_lu (MatrixType &lu, PivIndex *row_transpositions, PivIndex &nb_transpositions)
static Index blocked_lu (Index rows, Index cols, Scalar *lu_data, Index luStride, PivIndex *row_transpositions, PivIndex &nb_transpositions, Index maxBlockSize=256)
Detailed Description
template<typename Scalar, int StorageOrder, typename PivIndex>
struct Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >
Definition at line 216 of file PartialPivLU.h.
Member Typedef Documentation
template<typename Scalar , int StorageOrder, typename PivIndex > typedef Block<MatrixType,Dynamic,Dynamic> Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::BlockType
Definition at line 225 of file PartialPivLU.h.
template<typename Scalar , int StorageOrder, typename PivIndex > typedef MatrixType::Index Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::Index
Definition at line 227 of file PartialPivLU.h.
template<typename Scalar , int StorageOrder, typename PivIndex > typedef Map<Matrix<Scalar, Dynamic, Dynamic, StorageOrder> > Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::MapLU
Definition at line 223 of file PartialPivLU.h.
template<typename Scalar , int StorageOrder, typename PivIndex > typedef Block<MapLU, Dynamic, Dynamic> Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::MatrixType
Definition at line 224 of file PartialPivLU.h.
template<typename Scalar , int StorageOrder, typename PivIndex > typedef MatrixType::RealScalar Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::RealScalar
Definition at line 226 of file PartialPivLU.h.
Member Function Documentation
template<typename Scalar , int StorageOrder, typename PivIndex > static Index Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::blocked_lu (Index rows, Index cols, Scalar * lu_data, Index luStride, PivIndex * row_transpositions, PivIndex & nb_transpositions, Index maxBlockSize = 256) inline static
Definition at line 298 of file PartialPivLU.h.
References Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeffRef(), max(), min(), Eigen::RowMajor, and Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::unblocked_lu().
template<typename Scalar , int StorageOrder, typename PivIndex > static Index Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::unblocked_lu (MatrixType & lu, PivIndex * row_transpositions, PivIndex & nb_transpositions) inline static
Definition at line 239 of file PartialPivLU.h.
References Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeff(), Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::cols(), min(), and Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::rows().
Referenced by Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex >::blocked_lu().
The documentation for this struct was generated from the following file:
include/Eigen/src/LU/PartialPivLU.h