LIA_RAL: Eigen::internal::pardiso_run_selector< Index > Struct Template Reference
Eigen::internal::pardiso_run_selector< Index > Struct Template Reference
#include <PardisoSupport.h>
Static Public Member Functions
static Index run (_MKL_DSS_HANDLE_t pt, Index maxfct, Index mnum, Index type, Index phase, Index n, void *a, Index *ia, Index *ja, Index *perm, Index nrhs, Index *iparm, Index msglvl, void *b, void *x)
Detailed Description
template<typename Index>
struct Eigen::internal::pardiso_run_selector< Index >
Definition at line 44 of file PardisoSupport.h.
Member Function Documentation
template<typename Index> static Index Eigen::internal::pardiso_run_selector< Index >::run (_MKL_DSS_HANDLE_t pt, Index maxfct, Index mnum, Index type, Index phase, Index n, void * a, Index * ia, Index * ja, Index * perm, Index nrhs, Index * iparm, Index msglvl, void * b, void * x) inline static
Definition at line 46 of file PardisoSupport.h.
Referenced by Eigen::PardisoImpl< Derived >::_solve(), Eigen::PardisoImpl< Derived >::analyzePattern(), Eigen::PardisoImpl< Derived >::compute(), Eigen::PardisoImpl< Derived >::factorize(), and Eigen::PardisoImpl< PardisoLU< MatrixType > >::pardisoRelease().
The documentation for this struct was generated from the following file:
include/Eigen/src/PardisoSupport/PardisoSupport.h