LIA_RAL: Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor > Struct Template Reference
Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor > Struct Template Reference
#include <GeneralMatrixMatrix.h>
Public Types
typedef scalar_product_traits
< LhsScalar, RhsScalar >
::ReturnType ResScalar
Static Public Member Functions
static void run (Index rows, Index cols, Index depth, const LhsScalar *_lhs, Index lhsStride, const RhsScalar *_rhs, Index rhsStride, ResScalar *res, Index resStride, ResScalar alpha, level3_blocking< LhsScalar, RhsScalar > &blocking, GemmParallelInfo< Index > *info=0)
Detailed Description
template<typename Index, typename LhsScalar, int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar, int RhsStorageOrder, bool ConjugateRhs>
struct Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >
Definition at line 51 of file GeneralMatrixMatrix.h.
Member Typedef Documentation
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs> typedef scalar_product_traits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::ResScalar
Definition at line 53 of file GeneralMatrixMatrix.h.
Member Function Documentation
template<typename Index , typename LhsScalar , int LhsStorageOrder, bool ConjugateLhs, typename RhsScalar , int RhsStorageOrder, bool ConjugateRhs> static void Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor >::run (Index rows, Index cols, Index depth, const LhsScalar * _lhs, Index lhsStride, const RhsScalar * _rhs, Index rhsStride, ResScalar * res, Index resStride, ResScalar alpha, level3_blocking< LhsScalar, RhsScalar > & blocking, GemmParallelInfo< Index > * info = 0) inline static
Definition at line 54 of file GeneralMatrixMatrix.h.
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockW(), ei_declare_aligned_stack_constructed_variable, eigen_internal_assert, EIGEN_UNUSED_VARIABLE, info(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc(), and min().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/products/GeneralMatrixMatrix.h