LIA_RAL: Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector > Struct Template Reference
Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector > Struct Template Reference
#include <PlainObjectBase.h>
Public Types
typedef Derived::Index Index
Static Public Member Functions
static void run (DenseBase< Derived > &_this, Index rows, Index cols)
static void run (DenseBase< Derived > &_this, const DenseBase< OtherDerived > &other)
Detailed Description
template<typename Derived, typename OtherDerived = Derived, bool IsVector = bool(Derived::IsVectorAtCompileTime)>
struct Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >
Definition at line 37 of file PlainObjectBase.h.
Member Typedef Documentation
template<typename Derived , typename OtherDerived = Derived, bool IsVector = bool(Derived::IsVectorAtCompileTime)> typedef Derived::Index Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::Index
Definition at line 659 of file PlainObjectBase.h.
Member Function Documentation
template<typename Derived , typename OtherDerived = Derived, bool IsVector = bool(Derived::IsVectorAtCompileTime)> static void Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run (DenseBase< Derived > & _this, Index rows, Index cols) inline static
Definition at line 660 of file PlainObjectBase.h.
References Eigen::DenseBase< Derived >::block(), Eigen::internal::check_rows_cols_for_overflow(), Eigen::PlainObjectBase< Derived >::cols(), EIGEN_STATIC_ASSERT_DYNAMIC_SIZE, min(), Eigen::PlainObjectBase< Derived >::rows(), and Eigen::DenseBase< Derived >::swap().
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResize(), and Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::conservativeResizeLike().
template<typename Derived , typename OtherDerived = Derived, bool IsVector = bool(Derived::IsVectorAtCompileTime)> static void Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run (DenseBase< Derived > & _this, const DenseBase< OtherDerived > & other) inline static
Definition at line 682 of file PlainObjectBase.h.
References Eigen::DenseBase< Derived >::block(), Eigen::DenseBase< Derived >::bottomRightCorner(), Eigen::DenseBase< Derived >::bottomRows(), EIGEN_STATIC_ASSERT_DYNAMIC_SIZE, min(), Eigen::DenseBase< Derived >::rightCols(), and Eigen::DenseBase< Derived >::swap().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/PlainObjectBase.h