LIA_RAL: Eigen::internal::lpNorm_selector< Derived, p > Struct Template Reference
Eigen::internal::lpNorm_selector< Derived, p > Struct Template Reference
#include <Dot.h>
Public Types
typedef NumTraits< typename
traits< Derived >::Scalar >
::Real RealScalar
Static Public Member Functions
static RealScalar run (const MatrixBase< Derived > &m)
Detailed Description
template<typename Derived, int p>
struct Eigen::internal::lpNorm_selector< Derived, p >
Definition at line 163 of file Dot.h.
Member Typedef Documentation
template<typename Derived , int p> typedef NumTraits<typename traits<Derived>::Scalar>::Real Eigen::internal::lpNorm_selector< Derived, p >::RealScalar
Definition at line 165 of file Dot.h.
Member Function Documentation
template<typename Derived , int p> static RealScalar Eigen::internal::lpNorm_selector< Derived, p >::run (const MatrixBase< Derived > & m) inline static
Definition at line 166 of file Dot.h.
References Eigen::MatrixBase< Derived >::cwiseAbs(), and pow().
Referenced by Eigen::MatrixBase< Derived >::lpNorm().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/Dot.h