LIA_RAL: Eigen::internal::llt_inplace< Scalar, Lower > Struct Template Reference
Eigen::internal::llt_inplace< Scalar, Lower > Struct Template Reference
#include <LLT.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Static Public Member Functions
template<typename MatrixType >
static MatrixType::Index unblocked (MatrixType &mat)
template<typename MatrixType >
static MatrixType::Index blocked (MatrixType &m)
template<typename MatrixType , typename VectorType >
static MatrixType::Index rankUpdate (MatrixType &mat, const VectorType &vec, const RealScalar &sigma)
Detailed Description
template<typename Scalar>
struct Eigen::internal::llt_inplace< Scalar, Lower >
Definition at line 260 of file LLT.h.
Member Typedef Documentation
template<typename Scalar > typedef NumTraits<Scalar>::Real Eigen::internal::llt_inplace< Scalar, Lower >::RealScalar
Definition at line 262 of file LLT.h.
Member Function Documentation
template<typename Scalar > template<typename MatrixType > static MatrixType::Index Eigen::internal::llt_inplace< Scalar, Lower >::blocked (MatrixType & m) inline static
Definition at line 290 of file LLT.h.
References eigen_assert, max(), and min().
template<typename Scalar > template<typename MatrixType , typename VectorType > static MatrixType::Index Eigen::internal::llt_inplace< Scalar, Lower >::rankUpdate (MatrixType & mat, const VectorType & vec, const RealScalar & sigma) inline static
Definition at line 323 of file LLT.h.
References Eigen::internal::llt_rank_update_lower().
template<typename Scalar > template<typename MatrixType > static MatrixType::Index Eigen::internal::llt_inplace< Scalar, Lower >::unblocked (MatrixType & mat) inline static
Definition at line 264 of file LLT.h.
References Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeffRef(), eigen_assert, real(), and sqrt().
The documentation for this struct was generated from the following file:
include/Eigen/src/Cholesky/LLT.h