LIA_RAL: Eigen::internal::ldlt_inplace< Lower > Struct Template Reference
Eigen::internal::ldlt_inplace< Lower > Struct Template Reference
#include <LDLT.h>
Static Public Member Functions
template<typename MatrixType , typename TranspositionType , typename Workspace >
static bool unblocked (MatrixType &mat, TranspositionType &transpositions, Workspace &temp, int *sign=0)
template<typename MatrixType , typename WDerived >
static bool updateInPlace (MatrixType &mat, MatrixBase< WDerived > &w, typename MatrixType::RealScalar sigma=1)
template<typename MatrixType , typename TranspositionType , typename Workspace , typename WType >
static bool update (MatrixType &mat, const TranspositionType &transpositions, Workspace &tmp, const WType &w, typename MatrixType::RealScalar sigma=1)
Detailed Description
template<>
struct Eigen::internal::ldlt_inplace< Lower >
Definition at line 246 of file LDLT.h.
Member Function Documentation
template<typename MatrixType , typename TranspositionType , typename Workspace > static bool Eigen::internal::ldlt_inplace< Lower >::unblocked (MatrixType & mat, TranspositionType & transpositions, Workspace & temp, int * sign = 0) inline static
Definition at line 249 of file LDLT.h.
References abs(), Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel, HasDirectAccess >::coeffRef(), eigen_assert, real(), and swap().
template<typename MatrixType , typename TranspositionType , typename Workspace , typename WType > static bool Eigen::internal::ldlt_inplace< Lower >::update (MatrixType & mat, const TranspositionType & transpositions, Workspace & tmp, const WType & w, typename MatrixType::RealScalar sigma = 1) inline static
Definition at line 381 of file LDLT.h.
template<typename MatrixType , typename WDerived > static bool Eigen::internal::ldlt_inplace< Lower >::updateInPlace (MatrixType & mat, MatrixBase< WDerived > & w, typename MatrixType::RealScalar sigma = 1) inline static
Definition at line 342 of file LDLT.h.
References abs2(), eigen_assert, Eigen::internal::isfinite(), real(), and Eigen::DenseBase< Derived >::tail().
The documentation for this struct was generated from the following file:
include/Eigen/src/Cholesky/LDLT.h