LIA_RAL: Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum { Vectorizable = Traits::Vectorizable, LhsProgress = Traits::LhsProgress, RhsProgress = Traits::RhsProgress, ResPacketSize = Traits::ResPacketSize }
typedef gebp_traits< LhsScalar,
RhsScalar, ConjugateLhs,
ConjugateRhs > Traits
typedef Traits::ResScalar ResScalar
typedef Traits::LhsPacket LhsPacket
typedef Traits::RhsPacket RhsPacket
typedef Traits::ResPacket ResPacket
typedef Traits::AccPacket AccPacket
Public Member Functions
EIGEN_DONT_INLINE
EIGEN_FLATTEN_ATTRIB void operator() (ResScalar *res, Index resStride, const LhsScalar *blockA, const RhsScalar *blockB, Index rows, Index depth, Index cols, ResScalar alpha, Index strideA=-1, Index strideB=-1, Index offsetA=0, Index offsetB=0, RhsScalar *unpackedB=0)
Detailed Description
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs>
struct Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >
Definition at line 514 of file GeneralBlockPanelKernel.h.
Member Typedef Documentation
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::AccPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::AccPacket
Definition at line 521 of file GeneralBlockPanelKernel.h.
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::LhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::LhsPacket
Definition at line 518 of file GeneralBlockPanelKernel.h.
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::ResPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::ResPacket
Definition at line 520 of file GeneralBlockPanelKernel.h.
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::ResScalar Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::ResScalar
Definition at line 517 of file GeneralBlockPanelKernel.h.
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::RhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPacket
Definition at line 519 of file GeneralBlockPanelKernel.h.
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef gebp_traits<LhsScalar,RhsScalar,ConjugateLhs,ConjugateRhs> Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::Traits
Definition at line 516 of file GeneralBlockPanelKernel.h.
Member Enumeration Documentation
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> anonymous enum
Enumerator
Vectorizable
LhsProgress
RhsProgress
ResPacketSize
Definition at line 523 of file GeneralBlockPanelKernel.h.
Member Function Documentation
template<typename LhsScalar, typename RhsScalar, typename Index, int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> EIGEN_DONT_INLINE EIGEN_FLATTEN_ATTRIB void Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::operator() (ResScalar * res, Index resStride, const LhsScalar * blockA, const RhsScalar * blockB, Index rows, Index depth, Index cols, ResScalar alpha, Index strideA = -1, Index strideB = -1, Index offsetA = 0, Index offsetB = 0, RhsScalar * unpackedB = 0) inline
Definition at line 531 of file GeneralBlockPanelKernel.h.
References Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::acc(), EIGEN_ASM_COMMENT, Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::initAcc(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::LhsProgress, Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadLhs(), Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::loadRhs(), MADD, Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::madd(), Eigen::internal::prefetch(), Eigen::internal::pstoreu(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::ResPacketSize, Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjugateLhs, ConjugateRhs >::RhsProgress, and Eigen::internal::gebp_traits< _LhsScalar, _RhsScalar, _ConjLhs, _ConjRhs >::unpackRhs().
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/products/GeneralBlockPanelKernel.h