LIA_RAL: Eigen::EigenBase< Derived > Struct Template Reference
Eigen::EigenBase< Derived > Struct Template Reference
#include <EigenBase.h>
Public Types
typedef internal::traits
< Derived >::StorageKind StorageKind
typedef internal::traits
< Derived >::Index Index
Public Member Functions
Derived & derived ()
const Derived & derived () const
Derived & const_cast_derived () const
const Derived & const_derived () const
Index rows () const
Index cols () const
Index size () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void subTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
Detailed Description
template<typename Derived>
struct Eigen::EigenBase< Derived >
Common base class for all classes T such that MatrixBase has an operator=(T) and a constructor MatrixBase(T).
In other words, an EigenBase object is an object that can be copied into a MatrixBase.
Besides MatrixBase-derived classes, this also includes special matrix classes such as diagonal matrices, etc.
Notice that this class is trivial, it is only used to disambiguate overloaded functions.
See Also
TopicClassHierarchy
Definition at line 26 of file EigenBase.h.
Member Typedef Documentation
template<typename Derived> typedef internal::traits<Derived>::Index Eigen::EigenBase< Derived >::Index
Definition at line 31 of file EigenBase.h.
template<typename Derived> typedef internal::traits<Derived>::StorageKind Eigen::EigenBase< Derived >::StorageKind
Definition at line 30 of file EigenBase.h.
Member Function Documentation
template<typename Derived> template<typename Dest > void Eigen::EigenBase< Derived >::addTo (Dest & dst) const inline
Definition at line 56 of file EigenBase.h.
template<typename Derived> template<typename Dest > void Eigen::EigenBase< Derived >::applyThisOnTheLeft (Dest & dst) const inline
Definition at line 84 of file EigenBase.h.
template<typename Derived> template<typename Dest > void Eigen::EigenBase< Derived >::applyThisOnTheRight (Dest & dst) const inline
Definition at line 76 of file EigenBase.h.
template<typename Derived> Index Eigen::EigenBase< Derived >::cols (void) const inline
Returns
the number of columns.
See Also
rows(), ColsAtCompileTime
Definition at line 46 of file EigenBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::addTo(), Eigen::Array< Index, 64, 1, DontAlign >::Array(), Eigen::internal::BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options >::BandMatrixWrapper(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonalLength(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo(), Eigen::Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::subTo(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::toDenseMatrix().
template<typename Derived> Derived& Eigen::EigenBase< Derived >::const_cast_derived () const inline
Definition at line 38 of file EigenBase.h.
template<typename Derived> const Derived& Eigen::EigenBase< Derived >::const_derived () const inline
Definition at line 40 of file EigenBase.h.
template<typename Derived> Derived& Eigen::EigenBase< Derived >::derived () inline
Returns
a reference to the derived object
Definition at line 34 of file EigenBase.h.
Referenced by Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheRight(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::applyThisOnTheLeft(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::applyThisOnTheRight(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), Eigen::SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::binaryExpr(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::coeffs(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::evalTo(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), Eigen::RotationBase< Derived, 3 >::operator*(), Eigen::Translation< Scalar, Dim >::operator*(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), Eigen::Transform< _Scalar, _Dim >::operator*(), Eigen::operator*(), Eigen::MatrixBase< Derived >::operator*=(), Eigen::DenseBase< Derived >::operator+=(), Eigen::DenseBase< Derived >::operator-=(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), Eigen::DenseBase< Derived >::operator=(), Eigen::Transform< _Scalar, _Dim >::operator=(), Eigen::Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, _PacketAccess >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), Eigen::MatrixBase< Derived >::operator=(), Eigen::SparseMatrix< Scalar, RowMajor >::operator=(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::subs(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::supers(), Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::toDenseMatrix(), Eigen::Transform< _Scalar, _Dim >::Transform(), and Eigen::PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose().
template<typename Derived> const Derived& Eigen::EigenBase< Derived >::derived () const inline
Returns
a const reference to the derived object
Definition at line 36 of file EigenBase.h.
template<typename Derived> template<typename Dest > void Eigen::EigenBase< Derived >::evalTo (Dest & dst) const inline
Definition at line 52 of file EigenBase.h.
Referenced by Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::addTo(), and Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::subTo().
template<typename Derived> Index Eigen::EigenBase< Derived >::rows (void) const inline
Returns
the number of rows.
See Also
cols(), RowsAtCompileTime
Definition at line 44 of file EigenBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::addTo(), Eigen::Array< Index, 64, 1, DontAlign >::Array(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::col(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonal(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::diagonalLength(), Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::evalTo(), Eigen::Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size(), Eigen::EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::subTo(), and Eigen::internal::BandMatrixBase< BandMatrixWrapper< _CoefficientsType, _Rows, _Cols, _Supers, _Subs, _Options > >::toDenseMatrix().
template<typename Derived> Index Eigen::EigenBase< Derived >::size () const inline
Returns
the number of coefficients, which is rows()*cols().
See Also
rows(), cols(), SizeAtCompileTime.
Definition at line 49 of file EigenBase.h.
Referenced by Eigen::PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match().
template<typename Derived> template<typename Dest > void Eigen::EigenBase< Derived >::subTo (Dest & dst) const inline
Definition at line 66 of file EigenBase.h.
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/EigenBase.h