LIA_RAL: Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false > Struct Template Reference
Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false > Struct Template Reference
#include <SelfAdjointEigenSolver.h>
Public Types
typedef SolverType::MatrixType MatrixType
typedef SolverType::RealVectorType VectorType
typedef SolverType::Scalar Scalar
Static Public Member Functions
static void computeRoots (const MatrixType &m, VectorType &roots)
static void run (SolverType &solver, const MatrixType &mat, int options)
Detailed Description
template<typename SolverType>
struct Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >
Definition at line 661 of file SelfAdjointEigenSolver.h.
Member Typedef Documentation
template<typename SolverType > typedef SolverType::MatrixType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::MatrixType
Definition at line 663 of file SelfAdjointEigenSolver.h.
template<typename SolverType > typedef SolverType::Scalar Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::Scalar
Definition at line 665 of file SelfAdjointEigenSolver.h.
template<typename SolverType > typedef SolverType::RealVectorType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::VectorType
Definition at line 664 of file SelfAdjointEigenSolver.h.
Member Function Documentation
template<typename SolverType > static void Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::computeRoots (const MatrixType & m, VectorType & roots) inline static
Definition at line 667 of file SelfAdjointEigenSolver.h.
References abs2(), and sqrt().
template<typename SolverType > static void Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run (SolverType & solver, const MatrixType & mat, int options) inline static
Definition at line 676 of file SelfAdjointEigenSolver.h.
References abs2(), Eigen::ComputeEigenvectors, eigen_assert, Eigen::EigVecMask, Eigen::GenEigMask, max(), sqrt(), and Eigen::Success.
The documentation for this struct was generated from the following file:
include/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h