LIA_RAL: Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor > Struct Template Reference
Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor > Struct Template Reference
#include <TriangularSolverMatrix.h>
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index size, Index otherSize, const Scalar *_tri, Index triStride, Scalar *_other, Index otherStride, level3_blocking< Scalar, Scalar > &blocking)
Detailed Description
template<typename Scalar, typename Index, int Mode, bool Conjugate, int TriStorageOrder>
struct Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >
Definition at line 39 of file TriangularSolverMatrix.h.
Member Function Documentation
template<typename Scalar , typename Index , int Mode, bool Conjugate, int TriStorageOrder> static EIGEN_DONT_INLINE void Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >::run (Index size, Index otherSize, const Scalar * _tri, Index triStride, Scalar * _other, Index otherStride, level3_blocking< Scalar, Scalar > & blocking) inline static
Definition at line 41 of file TriangularSolverMatrix.h.
References Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockA(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockB(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::blockW(), ei_declare_aligned_stack_constructed_variable, EIGEN_PLAIN_ENUM_MAX, Eigen::GetAction, Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::kc(), Eigen::Lower, Eigen::internal::manage_caching_sizes(), Eigen::internal::level3_blocking< _LhsScalar, _RhsScalar >::mc(), min(), Eigen::RowMajor, and Eigen::UnitDiag.
The documentation for this struct was generated from the following file:
include/Eigen/src/Core/products/TriangularSolverMatrix.h