LIA_RAL: LIA_SpkTools/include/SuperVectors.h File Reference
SuperVectors.h File Reference
#include <liatools.h>
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API void modelToSv (const MixtureGD &, RealVector< double > &)
LIA_SPKTOOLS_API void svToModel (RealVector< double > &, MixtureGD &)
LIA_SPKTOOLS_API void projectOnSubSpace (RealVector< double > &, Matrix< double > &, RealVector< double > &)
LIA_SPKTOOLS_API void computeNap (MixtureGD &, Matrix< double > &)
LIA_SPKTOOLS_API void computeNAPChannelEffect (MixtureGD &, MixtureGD &, Matrix< double > &)
LIA_SPKTOOLS_API void getFisherWeightVector (const MixtureGD &, const MixtureGD &, RealVector< double > &, Config &)
LIA_SPKTOOLS_API void getKLVector (MixtureGD &, RealVector< double > &, Config &)
LIA_SPKTOOLS_API void getSuperVector (RealVector< double > &, MixtureGD &, MixtureGD &, Config &)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file SuperVectors.h.
Function Documentation
LIA_SPKTOOLS_API void computeNap (MixtureGD & , Matrix< double > &)
Definition at line 128 of file SuperVectors.cpp.
References modelToSv(), projectOnSubSpace(), and svToModel().
Referenced by TrainTarget().
LIA_SPKTOOLS_API void computeNAPChannelEffect (MixtureGD & , MixtureGD & , Matrix< double > &)
Definition at line 147 of file SuperVectors.cpp.
References debug, max(), modelToSv(), projectOnSubSpace(), svToModel(), and verboseLevel.
Referenced by ComputeTestNAP().
LIA_SPKTOOLS_API void getFisherWeightVector (const MixtureGD & , const MixtureGD & , RealVector< double > & , Config &)
Definition at line 240 of file SuperVectors.cpp.
Referenced by getSuperVector().
LIA_SPKTOOLS_API void getKLVector (MixtureGD & , RealVector< double > & , Config &)
Definition at line 253 of file SuperVectors.cpp.
References sqrt().
Referenced by getSuperVector(), and loadMeanSv().
LIA_SPKTOOLS_API void getSuperVector (RealVector< double > & , MixtureGD & , MixtureGD & , Config &)
Definition at line 266 of file SuperVectors.cpp.
References getFisherWeightVector(), and getKLVector().
Referenced by TrainTarget().
LIA_SPKTOOLS_API void modelToSv (const MixtureGD & , RealVector< double > &)
Definition at line 70 of file SuperVectors.cpp.
Referenced by computeNap(), computeNAPChannelEffect(), FactorAnalysisStat::estimateXForKnownSpeaker(), getUbmOffset(), loadMeanSv(), main(), and FactorAnalysisStat::setYFromModel().
LIA_SPKTOOLS_API void projectOnSubSpace (RealVector< double > & , Matrix< double > & , RealVector< double > &)
Definition at line 108 of file SuperVectors.cpp.
References verboseLevel.
Referenced by computeNap(), computeNAPChannelEffect(), getUbmOffset(), nap(), and project().
LIA_SPKTOOLS_API void svToModel (RealVector< double > & , MixtureGD &)
Definition at line 79 of file SuperVectors.cpp.
Referenced by computeNap(), computeNAPChannelEffect(), FactorAnalysisStat::estimateXForKnownSpeaker(), FactorAnalysisStat::getSessionModel(), FactorAnalysisStat::getSpeakerModel(), TVAcc::getSpeakerModel(), JFAAcc::getSpeakerModel(), FactorAnalysisStat::getTrueSpeakerModel(), TrainTargetJFA(), and TrainTargetLFA().