LIA_RAL: LIA_SpkTools/src/SuperVectors.cpp File Reference
SuperVectors.cpp File Reference
#include "SuperVectors.h"
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
Macros
#define ALIZE_SuperVectors_cpp
Functions
void modelToSv (const MixtureGD &M, RealVector< double > &v)
void svToModel (RealVector< double > &v, MixtureGD &M)
void projectOnSubSpace (RealVector< double > &x, Matrix< double > &U, RealVector< double > &proj)
void computeNap (MixtureGD &M, Matrix< double > &U)
void computeNAPChannelEffect (MixtureGD &T, MixtureGD &M, Matrix< double > &U)
void getFisherWeightVector (const MixtureGD &world, const MixtureGD &clientMixture, RealVector< double > &v, Config &config)
void getKLVector (MixtureGD &model, RealVector< double > &v, Config &config)
void getSuperVector (RealVector< double > &v, MixtureGD &aprioriModel, MixtureGD &clientMixture, Config &config)
Macro Definition Documentation
#define ALIZE_SuperVectors_cpp
Definition at line 56 of file SuperVectors.cpp.
Function Documentation
void computeNap (MixtureGD & M, Matrix< double > & U)
Definition at line 128 of file SuperVectors.cpp.
References modelToSv(), projectOnSubSpace(), and svToModel().
Referenced by TrainTarget().
void computeNAPChannelEffect (MixtureGD & T, MixtureGD & M, Matrix< double > & U)
Definition at line 147 of file SuperVectors.cpp.
References debug, max(), modelToSv(), projectOnSubSpace(), svToModel(), and verboseLevel.
Referenced by ComputeTestNAP().
void getFisherWeightVector (const MixtureGD & world, const MixtureGD & clientMixture, RealVector< double > & v, Config & config)
Definition at line 240 of file SuperVectors.cpp.
Referenced by getSuperVector().
void getKLVector (MixtureGD & model, RealVector< double > & v, Config & config)
Definition at line 253 of file SuperVectors.cpp.
References sqrt().
Referenced by getSuperVector(), and loadMeanSv().
void getSuperVector (RealVector< double > & v, MixtureGD & aprioriModel, MixtureGD & clientMixture, Config & config)
Definition at line 266 of file SuperVectors.cpp.
References getFisherWeightVector(), and getKLVector().
Referenced by TrainTarget().
void modelToSv (const MixtureGD & M, RealVector< double > & v)
Definition at line 70 of file SuperVectors.cpp.
Referenced by computeNap(), computeNAPChannelEffect(), FactorAnalysisStat::estimateXForKnownSpeaker(), getUbmOffset(), loadMeanSv(), main(), and FactorAnalysisStat::setYFromModel().
void projectOnSubSpace (RealVector< double > & x, Matrix< double > & U, RealVector< double > & proj)
Definition at line 108 of file SuperVectors.cpp.
References verboseLevel.
Referenced by computeNap(), computeNAPChannelEffect(), getUbmOffset(), nap(), and project().
void svToModel (RealVector< double > & v, MixtureGD & M)
Definition at line 79 of file SuperVectors.cpp.
Referenced by computeNap(), computeNAPChannelEffect(), FactorAnalysisStat::estimateXForKnownSpeaker(), FactorAnalysisStat::getSessionModel(), FactorAnalysisStat::getSpeakerModel(), TVAcc::getSpeakerModel(), JFAAcc::getSpeakerModel(), FactorAnalysisStat::getTrueSpeakerModel(), TrainTargetJFA(), and TrainTargetLFA().