LIA_RAL: LIA_SpkTools/src/Tools.cpp File Reference
Tools.cpp File Reference
#include "Tools.h"
Macros
#define ALIZE_Tools_cpp
Functions
MixtureGD & learnModelFromSplit (Config &config, SegCluster &clusterSeg, StatServer &ss, FeatureServer &fs, MixtureServer &ms, unsigned long maxDistribCount, unsigned long deleteMixture, unsigned long nbIt)
void learnModel (Config &config, SegCluster &clusterSeg, StatServer &ss, FeatureServer &fs, MixtureServer &ms, MixtureGD &mInit)
void learnModelFromBaggedFrame (Config &config, SegCluster &clusterSeg, MixtureGD &world, StatServer &ss, FeatureServer &fs, MixtureServer &ms)
void modifyMAPConfig (Config &config, MAPCfg &cfg, String context)
bool findAlreadyUsed (SegCluster &clusterUsedSeg, unsigned long start, unsigned long length, String fileLabel)
void CreateInitHMM (Config &config, MAPCfg &cfg, SegCluster &clusterSeg, MixtureGD &world, hmm &hmmv, StatServer &ss, FeatureServer &fs, MixtureServer &ms)
void CreateInitHMM (Config &config, SegCluster &clusterSeg, hmm &hmmv, StatServer &ss, FeatureServer &fs, MixtureServer &ms)
void findNameClass (String &name, String &nameClass)
bool isNewSpeaker (String nameCluster)
void InitHMM (Config &config, SegServer &segmentsServer, MixtureGD &world, hmm &actualHMM)
void InitHMM (Config &config, SegServer &segmentsServer, MixtureGD &speech, MixtureGD &nonspeech, hmm &actualHMM)
void InitHMMOverlap (Config &config, SegServer &segmentsServer, MixtureGD &world, hmm &actualHMM)
void computeTransitions (Config &config, hmm &actualHMM, String transitionMethod, double gamma, SegServer &Server)
void computeTransitions (Config &config, hmm &actualHMM, SegServer &Server)
bool isComparableAndVerifSpeaker (Config &config, SegServer &segTemp, SegServer &actualSeg, DoubleVector &actualViterbiProb, DoubleVector &previousViterbiProb)
bool isComparable (Config &config, SegServer &segTemp, SegServer &actualSeg, DoubleVector &actualViterbiProb, DoubleVector &previousViterbiProb)
bool isDifferentSegmentation (Config &config, SegCluster &clusterA, SegCluster &clusterB)
bool isLessEpsilon (Config &config, DoubleVector &actualViterbiProb, DoubleVector &previousViterbiProb, double &epsilon)
bool isValidLengthOfLastSpeaker (Config &config, SegServer &actualSeg)
double ComputePath (Config &config, hmm &actualHMM, DoubleVector transitionsa, SegServer &actualSeg, XList &listseg, StatServer &ss)
double ComputePath (Config &config, hmm &actualHMM, DoubleVector transitionsa, SegServer &actualSeg, FeatureServer &fs, StatServer &ss, MixtureGD &world)
double computeLLKMeanOnOneCluster (Config &config, hmm &actualHMM, SegServer &actualSeg, unsigned long icluster, StatServer &ss, FeatureServer &fs)
void saveSegmentation (Config &config, SegServer &Resultat, FeatureServer &fs, String &outputFilesPath, int sorted)
void saveAcousticSegmentation (Config &config, SegServer &Resultat, FeatureServer &fs, String &outputFilesPath, int sorted)
void CleanSpeaker (Config &config, SegCluster &clusterToClean, SegCluster &clusterL0, unsigned long startSeg, LabelServer &labelServer)
void NoDataSpeakerVerification (Config &config, hmm &actualHMM, SegServer &actualSeg)
void accumulateStatLLKExt (StatServer &ss, FeatureServer &fs, MixtureStat &llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
int compare (const void *a, const void *b)
double meanLikelihoodExt (StatServer &ss, FeatureServer &fs, MixtureGD &model, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
void copySeg (SegCluster &cOld, SegCluster &cNew, SegServer &segTemp, LabelServer &labelServer, String l)
void createOneClusterPerSegment (SegServer &segmentServer, SegServer &segTemp)
void createOneClusterPerFixedSegment (SegServer &segmentServer, SegServer &segTemp)
void viterbiDecoding (Config &config, hmm &actualHMM, SegCluster &cluster, SegServer &segTemp, StatServer &ss, FeatureServer &fs, LabelServer &labelServer, DoubleVector &actualViterbiProb)
MixtureGD & mixtureInitBySplit (Config &config, MixtureServer &ms, StatServer &ss, FeatureServer &fs, SegCluster &selectedSegments, DoubleVector &globalMean, DoubleVector &globalCov, unsigned long maxDistribCount, TrainCfg &trainCfg, unsigned long deleteDistrib)
void copyPathInCluster (Config &config, SegServer &segTemp, const ULongVector &path, hmm &cHmm, LabelServer &labelServer, unsigned long start, String sourceName)
MixtureGD & createWorld (Config &config, SegCluster &cluster, StatServer &ss, FeatureServer &fs, MixtureServer &ms)
MixtureGD & createWorld (Config &config, SegCluster &cluster, StatServer &ss, FeatureServer &fs, MixtureServer &ms, unsigned long maxDistribCount)
void segAdaptation (Config &config, MAPCfg &mapCfg, hmm &actualHMM, MixtureGD &world, SegServer &previousSeg, SegServer &actualSeg, StatServer &ss, FeatureServer &fs, MixtureServer &ms)
void segEM (Config &config, hmm &actualHMM, SegServer &previousSeg, SegServer &actualSeg, StatServer &ss, FeatureServer &fs, MixtureServer &ms, unsigned long nbDistrib)
Macro Definition Documentation
#define ALIZE_Tools_cpp
Definition at line 56 of file Tools.cpp.
Function Documentation
void accumulateStatLLKExt (StatServer & ss, FeatureServer & fs, MixtureStat & llkAcc, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 920 of file Tools.cpp.
References compare(), and debug.
Referenced by meanLikelihoodExt().
void CleanSpeaker (Config & config, SegCluster & clusterToClean, SegCluster & clusterL0, unsigned long startSeg, LabelServer & labelServer)
Definition at line 852 of file Tools.cpp.
References moveSegmentFromOneClusterToAnother().
int compare (const void * a, const void * b)
Definition at line 967 of file Tools.cpp.
Referenced by accumulateStatLLKExt().
double computeLLKMeanOnOneCluster (Config & config, hmm & actualHMM, SegServer & actualSeg, unsigned long icluster, StatServer & ss, FeatureServer & fs)
Definition at line 654 of file Tools.cpp.
References hmm::getDensity(), and meanLikelihood().
double ComputePath (Config & config, hmm & actualHMM, DoubleVector transitionsa, SegServer & actualSeg, XList & listseg, StatServer & ss)
Definition at line 514 of file Tools.cpp.
References displayAllSegments(), hmm::getDensity(), hmm::getNbState(), hmm::getStateName(), log(), verbose, and verboseLevel.
double ComputePath (Config & config, hmm & actualHMM, DoubleVector transitionsa, SegServer & actualSeg, FeatureServer & fs, StatServer & ss, MixtureGD & world)
Definition at line 588 of file Tools.cpp.
References displayAllSegments(), hmm::getDensity(), hmm::getNbState(), hmm::getStateName(), log(), verbose, and verboseLevel.
void computeTransitions (Config & config, hmm & actualHMM, String transitionMethod, double gamma, SegServer & Server)
Definition at line 331 of file Tools.cpp.
References hmm::getNbState(), hmm::setTransition(), totalFrame(), verbose, and verboseLevel.
Referenced by AcousticSegmentationProcess(), addSpeaker(), computeTransitions(), InitHMM(), InitHMMOverlap(), isStopReSeg(), and NoDataSpeakerVerification().
void computeTransitions (Config & config, hmm & actualHMM, SegServer & Server)
Definition at line 413 of file Tools.cpp.
References computeTransitions().
void copyPathInCluster (Config & config, SegServer & segTemp, const ULongVector & path, hmm & cHmm, LabelServer & labelServer, unsigned long start, String sourceName)
Definition at line 1229 of file Tools.cpp.
References hmm::getStateName().
Referenced by viterbiDecoding().
void copySeg (SegCluster & cOld, SegCluster & cNew, SegServer & segTemp, LabelServer & labelServer, String l)
Definition at line 989 of file Tools.cpp.
void CreateInitHMM (Config & config, MAPCfg & cfg, SegCluster & clusterSeg, MixtureGD & world, hmm & hmmv, StatServer & ss, FeatureServer & fs, MixtureServer & ms)
Definition at line 221 of file Tools.cpp.
References adaptModel(), hmm::getDensity(), hmm::LoadState(), hmm::reset(), and verbose.
void CreateInitHMM (Config & config, SegCluster & clusterSeg, hmm & hmmv, StatServer & ss, FeatureServer & fs, MixtureServer & ms)
Definition at line 236 of file Tools.cpp.
References learnModelFromSplit(), hmm::reset(), and hmm::setDensity().
void createOneClusterPerFixedSegment (SegServer & segmentServer, SegServer & segTemp)
Definition at line 1007 of file Tools.cpp.
void createOneClusterPerSegment (SegServer & segmentServer, SegServer & segTemp)
Definition at line 998 of file Tools.cpp.
MixtureGD& createWorld (Config & config, SegCluster & cluster, StatServer & ss, FeatureServer & fs, MixtureServer & ms)
Definition at line 1259 of file Tools.cpp.
References learnModelFromSplit().
Referenced by ReSegmentationProcess(), and segmentationProcess().
MixtureGD& createWorld (Config & config, SegCluster & cluster, StatServer & ss, FeatureServer & fs, MixtureServer & ms, unsigned long maxDistribCount)
Definition at line 1273 of file Tools.cpp.
References learnModelFromSplit().
bool findAlreadyUsed (SegCluster & clusterUsedSeg, unsigned long start, unsigned long length, String fileLabel)
Definition at line 198 of file Tools.cpp.
Referenced by isSegAvailable(), and segmentSelection().
void findNameClass (String & name, String & nameClass)
Definition at line 247 of file Tools.cpp.
void InitHMM (Config & config, SegServer & segmentsServer, MixtureGD & world, hmm & actualHMM)
Definition at line 277 of file Tools.cpp.
References computeTransitions(), hmm::getNbState(), hmm::LoadState(), hmm::reset(), and verbose.
Referenced by ReSegmentationProcess().
void InitHMM (Config & config, SegServer & segmentsServer, MixtureGD & speech, MixtureGD & nonspeech, hmm & actualHMM)
Definition at line 293 of file Tools.cpp.
References computeTransitions(), hmm::getNbState(), hmm::LoadState(), hmm::reset(), and verbose.
void InitHMMOverlap (Config & config, SegServer & segmentsServer, MixtureGD & world, hmm & actualHMM)
Definition at line 310 of file Tools.cpp.
References computeTransitions(), hmm::getNbState(), hmm::LoadState(), hmm::reset(), and verbose.
bool isComparable (Config & config, SegServer & segTemp, SegServer & actualSeg, DoubleVector & actualViterbiProb, DoubleVector & previousViterbiProb)
Definition at line 433 of file Tools.cpp.
References debug, isDifferentSegmentation(), isLessEpsilon(), and verbose.
Referenced by isComparableAndVerifSpeaker().
bool isComparableAndVerifSpeaker (Config & config, SegServer & segTemp, SegServer & actualSeg, DoubleVector & actualViterbiProb, DoubleVector & previousViterbiProb)
Definition at line 422 of file Tools.cpp.
References isComparable().
Referenced by segmentationProcess().
bool isDifferentSegmentation (Config & config, SegCluster & clusterA, SegCluster & clusterB)
Definition at line 455 of file Tools.cpp.
References debug.
Referenced by isComparable(), isStopAcousticSegmentation(), isStopReSeg(), segAdaptation(), and segEM().
bool isLessEpsilon (Config & config, DoubleVector & actualViterbiProb, DoubleVector & previousViterbiProb, double & epsilon)
Definition at line 483 of file Tools.cpp.
References debug.
Referenced by isComparable(), isStopAcousticSegmentation(), and isStopReSeg().
bool isNewSpeaker (String nameCluster)
Definition at line 265 of file Tools.cpp.
bool isValidLengthOfLastSpeaker (Config & config, SegServer & actualSeg)
Definition at line 500 of file Tools.cpp.
References totalFrame().
void learnModel (Config & config, SegCluster & clusterSeg, StatServer & ss, FeatureServer & fs, MixtureServer & ms, MixtureGD & mInit)
Definition at line 92 of file Tools.cpp.
References globalMeanCov(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setNbTrainIt(), and trainModel().
void learnModelFromBaggedFrame (Config & config, SegCluster & clusterSeg, MixtureGD & world, StatServer & ss, FeatureServer & fs, MixtureServer & ms)
Definition at line 114 of file Tools.cpp.
References globalMeanCov(), mixtureInit(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setBaggedFrameProbabilityInit(), TrainCfg::setFinalVarFlooring(), TrainCfg::setInitVarFlooring(), TrainCfg::setNbTrainIt(), totalFrame(), trainModel(), and verbose.
MixtureGD& learnModelFromSplit (Config & config, SegCluster & clusterSeg, StatServer & ss, FeatureServer & fs, MixtureServer & ms, unsigned long maxDistribCount, unsigned long deleteMixture, unsigned long nbIt)
Definition at line 64 of file Tools.cpp.
References globalMeanCov(), mixtureInitBySplit(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setNbTrainIt(), trainModel(), and verbose.
Referenced by CreateInitHMM(), createWorld(), and segEM().
double meanLikelihoodExt (StatServer & ss, FeatureServer & fs, MixtureGD & model, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 975 of file Tools.cpp.
References accumulateStatLLKExt().
MixtureGD& mixtureInitBySplit (Config & config, MixtureServer & ms, StatServer & ss, FeatureServer & fs, SegCluster & selectedSegments, DoubleVector & globalMean, DoubleVector & globalCov, unsigned long maxDistribCount, TrainCfg & trainCfg, unsigned long deleteDistrib)
Definition at line 1065 of file Tools.cpp.
References accumulateStatEM(), TrainCfg::getFinalVarCeil(), TrainCfg::getFinalVarFloor(), TrainCfg::getInitVarCeil(), TrainCfg::getInitVarFloor(), TrainCfg::getNbTrainIt(), TrainCfg::getNormalizeModel(), meanLikelihood(), normalizeMixture(), normalizeWeights(), setItParameter(), TrainCfg::showConfig(), sqrt(), totalFrame(), varianceControl(), verbose, and verboseLevel.
Referenced by learnModelFromSplit().
void modifyMAPConfig (Config & config, MAPCfg & cfg, String context)
Definition at line 155 of file Tools.cpp.
References MAPCfg::getMeanAdapt(), MAPCfg::getVarAdapt(), MAPCfg::getWeightAdapt(), MAPCfg::setMeanAdapt(), MAPCfg::setMeanAlpha(), MAPCfg::setMeanReg(), MAPCfg::setMethod(), MAPCfg::setVarAdapt(), MAPCfg::setVarAlpha(), MAPCfg::setVarReg(), MAPCfg::setWeightAdapt(), MAPCfg::setWeightAlpha(), and MAPCfg::setWeightReg().
void NoDataSpeakerVerification (Config & config, hmm & actualHMM, SegServer & actualSeg)
Definition at line 870 of file Tools.cpp.
References computeTransitions(), hmm::deleteState(), totalFrame(), verbose, and verboseLevel.
Referenced by addSpeaker(), segAdaptation(), segAdaptationClass(), and segEM().
void saveAcousticSegmentation (Config & config, SegServer & Resultat, FeatureServer & fs, String & outputFilesPath, int sorted)
Definition at line 748 of file Tools.cpp.
References displayAllSegments(), and verbose.
Referenced by launchAcousticSegmentationProcess().
void saveSegmentation (Config & config, SegServer & Resultat, FeatureServer & fs, String & outputFilesPath, int sorted)
Definition at line 662 of file Tools.cpp.
References displayAllSegments(), and verbose.
Referenced by launchReSegmentationProcess(), launchSegmentationProcess(), and launchTurnDetectionProcess().
void segAdaptation (Config & config, MAPCfg & mapCfg, hmm & actualHMM, MixtureGD & world, SegServer & previousSeg, SegServer & actualSeg, StatServer & ss, FeatureServer & fs, MixtureServer & ms)
Definition at line 1290 of file Tools.cpp.
References adaptModel(), hmm::getDensity(), isDifferentSegmentation(), NoDataSpeakerVerification(), hmm::setDensity(), verbose, and verboseLevel.
Referenced by ReSegmentationProcess(), and segmentationProcess().
void segEM (Config & config, hmm & actualHMM, SegServer & previousSeg, SegServer & actualSeg, StatServer & ss, FeatureServer & fs, MixtureServer & ms, unsigned long nbDistrib)
Definition at line 1326 of file Tools.cpp.
References isDifferentSegmentation(), learnModelFromSplit(), NoDataSpeakerVerification(), hmm::setDensity(), verbose, and verboseLevel.
Referenced by segmentationProcess().
void viterbiDecoding (Config & config, hmm & actualHMM, SegCluster & cluster, SegServer & segTemp, StatServer & ss, FeatureServer & fs, LabelServer & labelServer, DoubleVector & actualViterbiProb)
Definition at line 1029 of file Tools.cpp.
References accumulateStatViterbi(), copyPathInCluster(), createAndInitializeViterbiAccum(), hmm::getNbState(), initializeCluster(), verbose, and verboseLevel.
Referenced by AcousticSegmentationProcess(), ReSegmentationProcess(), and segmentationProcess().