LIA_RAL: LIA_SpkTools/include/Tools.h File Reference
Tools.h File Reference
#include <alize.h>
#include "liatools.h"
#include "ClusteringCriterion.h"
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API MAPCfg & initMAPConfig (Config &, String)
LIA_SPKTOOLS_API void modifyMAPConfig (Config &, MAPCfg &, String)
LIA_SPKTOOLS_API MixtureGD & learnModelFromSplit (Config &, SegCluster &, StatServer &, FeatureServer &, MixtureServer &, unsigned long, unsigned long, unsigned long)
LIA_SPKTOOLS_API void learnModel (Config &, SegCluster &, StatServer &, FeatureServer &, MixtureServer &, MixtureGD &)
LIA_SPKTOOLS_API bool findAlreadyUsed (SegCluster &, unsigned long, unsigned long, String)
LIA_SPKTOOLS_API void CreateInitHMM (Config &, MAPCfg &, SegCluster &, MixtureGD &, hmm &, StatServer &, FeatureServer &, MixtureServer &)
LIA_SPKTOOLS_API void CreateInitHMM (Config &, SegCluster &, hmm &, StatServer &, FeatureServer &, MixtureServer &)
LIA_SPKTOOLS_API void findNameClass (String &, String &)
LIA_SPKTOOLS_API bool isNewSpeaker (String)
LIA_SPKTOOLS_API void InitHMM (Config &, SegServer &, MixtureGD &, hmm &)
LIA_SPKTOOLS_API void InitHMM (Config &, SegServer &, MixtureGD &, MixtureGD &, hmm &)
LIA_SPKTOOLS_API void InitHMMOverlap (Config &, SegServer &, MixtureGD &, hmm &)
LIA_SPKTOOLS_API void computeTransitions (Config &, hmm &, String, double, SegServer &)
LIA_SPKTOOLS_API void computeTransitions (Config &, hmm &, SegServer &)
LIA_SPKTOOLS_API bool isComparable (Config &, SegServer &, SegServer &, DoubleVector &, DoubleVector &)
LIA_SPKTOOLS_API bool isComparableAndVerifSpeaker (Config &, SegServer &, SegServer &, DoubleVector &, DoubleVector &)
LIA_SPKTOOLS_API bool isDifferentSegmentation (Config &, SegCluster &, SegCluster &)
LIA_SPKTOOLS_API bool isLessEpsilon (Config &, DoubleVector &, DoubleVector &, double &)
LIA_SPKTOOLS_API bool isValidLengthOfLastSpeaker (Config &, SegServer &)
LIA_SPKTOOLS_API double ComputePath (Config &, hmm &, DoubleVector, SegServer &, XList &, StatServer &)
LIA_SPKTOOLS_API double ComputeLLROnOneCluster (Config &, hmm &, SegServer &, unsigned long, StatServer &, FeatureServer &, DoubleVector &)
LIA_SPKTOOLS_API void saveSegmentation (Config &, SegServer &, FeatureServer &, String &, int)
LIA_SPKTOOLS_API void saveAcousticSegmentation (Config &, SegServer &, FeatureServer &, String &, int)
LIA_SPKTOOLS_API void CleanSpeaker (Config &, SegCluster &, SegCluster &, unsigned long, LabelServer &)
LIA_SPKTOOLS_API void NoDataSpeakerVerification (Config &, hmm &, SegServer &)
LIA_SPKTOOLS_API int compare (const void *, const void *)
LIA_SPKTOOLS_API double meanLikelihoodExt (StatServer &, FeatureServer &, MixtureGD &, unsigned long, unsigned long, Config &)
LIA_SPKTOOLS_API void accumulateStatLLKExt (StatServer &, FeatureServer &, MixtureStat &, unsigned long, unsigned long, Config &)
LIA_SPKTOOLS_API void viterbiDecoding (Config &, hmm &, SegCluster &, SegServer &, StatServer &, FeatureServer &, LabelServer &, DoubleVector &)
LIA_SPKTOOLS_API void copyPathInCluster (Config &, SegServer &, const ULongVector &, hmm &, LabelServer &, unsigned long, String)
LIA_SPKTOOLS_API void segAdaptation (Config &, MAPCfg &, hmm &, MixtureGD &, SegServer &, SegServer &, StatServer &, FeatureServer &, MixtureServer &)
LIA_SPKTOOLS_API void segEM (Config &, hmm &, SegServer &, SegServer &, StatServer &, FeatureServer &, MixtureServer &, unsigned long)
LIA_SPKTOOLS_API MixtureGD & createWorld (Config &, SegCluster &, StatServer &, FeatureServer &, MixtureServer &)
LIA_SPKTOOLS_API MixtureGD & createWorld (Config &, SegCluster &, StatServer &, FeatureServer &, MixtureServer &, unsigned long)
LIA_SPKTOOLS_API MixtureGD & mixtureInitBySplit (Config &, MixtureServer &, StatServer &, FeatureServer &, SegCluster &, DoubleVector &, DoubleVector &, unsigned long, TrainCfg &, unsigned long)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file Tools.h.
Function Documentation
LIA_SPKTOOLS_API void accumulateStatLLKExt (StatServer & , FeatureServer & , MixtureStat & , unsigned long, unsigned long, Config &)
Definition at line 920 of file Tools.cpp.
References compare(), and debug.
Referenced by meanLikelihoodExt().
LIA_SPKTOOLS_API void CleanSpeaker (Config & , SegCluster & , SegCluster & , unsigned long, LabelServer &)
Definition at line 852 of file Tools.cpp.
References moveSegmentFromOneClusterToAnother().
LIA_SPKTOOLS_API int compare (const void * , const void *)
Definition at line 967 of file Tools.cpp.
Referenced by accumulateStatLLKExt().
LIA_SPKTOOLS_API double ComputeLLROnOneCluster (Config & , hmm & , SegServer & , unsigned long, StatServer & , FeatureServer & , DoubleVector &)
LIA_SPKTOOLS_API double ComputePath (Config & , hmm & , DoubleVector , SegServer & , XList & , StatServer &)
Definition at line 514 of file Tools.cpp.
References displayAllSegments(), hmm::getDensity(), hmm::getNbState(), hmm::getStateName(), log(), verbose, and verboseLevel.
LIA_SPKTOOLS_API void computeTransitions (Config & , hmm & , String , double , SegServer &)
Definition at line 331 of file Tools.cpp.
References hmm::getNbState(), hmm::setTransition(), totalFrame(), verbose, and verboseLevel.
Referenced by AcousticSegmentationProcess(), addSpeaker(), computeTransitions(), InitHMM(), InitHMMOverlap(), isStopReSeg(), and NoDataSpeakerVerification().
LIA_SPKTOOLS_API void computeTransitions (Config & , hmm & , SegServer &)
Definition at line 413 of file Tools.cpp.
References computeTransitions().
LIA_SPKTOOLS_API void copyPathInCluster (Config & , SegServer & , const ULongVector & , hmm & , LabelServer & , unsigned long, String)
Definition at line 1229 of file Tools.cpp.
References hmm::getStateName().
Referenced by viterbiDecoding().
LIA_SPKTOOLS_API void CreateInitHMM (Config & , MAPCfg & , SegCluster & , MixtureGD & , hmm & , StatServer & , FeatureServer & , MixtureServer &)
Definition at line 221 of file Tools.cpp.
References adaptModel(), hmm::getDensity(), hmm::LoadState(), hmm::reset(), and verbose.
LIA_SPKTOOLS_API void CreateInitHMM (Config & , SegCluster & , hmm & , StatServer & , FeatureServer & , MixtureServer &)
Definition at line 236 of file Tools.cpp.
References learnModelFromSplit(), hmm::reset(), and hmm::setDensity().
LIA_SPKTOOLS_API MixtureGD& createWorld (Config & , SegCluster & , StatServer & , FeatureServer & , MixtureServer &)
Definition at line 1259 of file Tools.cpp.
References learnModelFromSplit().
Referenced by ReSegmentationProcess(), and segmentationProcess().
LIA_SPKTOOLS_API MixtureGD& createWorld (Config & , SegCluster & , StatServer & , FeatureServer & , MixtureServer & , unsigned long)
Definition at line 1273 of file Tools.cpp.
References learnModelFromSplit().
LIA_SPKTOOLS_API bool findAlreadyUsed (SegCluster & , unsigned long, unsigned long, String)
Definition at line 198 of file Tools.cpp.
Referenced by isSegAvailable(), and segmentSelection().
LIA_SPKTOOLS_API void findNameClass (String & , String &)
Definition at line 247 of file Tools.cpp.
LIA_SPKTOOLS_API void InitHMM (Config & , SegServer & , MixtureGD & , hmm &)
Definition at line 277 of file Tools.cpp.
References computeTransitions(), hmm::getNbState(), hmm::LoadState(), hmm::reset(), and verbose.
Referenced by ReSegmentationProcess().
LIA_SPKTOOLS_API void InitHMM (Config & , SegServer & , MixtureGD & , MixtureGD & , hmm &)
Definition at line 293 of file Tools.cpp.
References computeTransitions(), hmm::getNbState(), hmm::LoadState(), hmm::reset(), and verbose.
LIA_SPKTOOLS_API void InitHMMOverlap (Config & , SegServer & , MixtureGD & , hmm &)
Definition at line 310 of file Tools.cpp.
References computeTransitions(), hmm::getNbState(), hmm::LoadState(), hmm::reset(), and verbose.
LIA_SPKTOOLS_API MAPCfg& initMAPConfig (Config & , String)
LIA_SPKTOOLS_API bool isComparable (Config & , SegServer & , SegServer & , DoubleVector & , DoubleVector &)
Definition at line 433 of file Tools.cpp.
References debug, isDifferentSegmentation(), isLessEpsilon(), and verbose.
Referenced by isComparableAndVerifSpeaker().
LIA_SPKTOOLS_API bool isComparableAndVerifSpeaker (Config & , SegServer & , SegServer & , DoubleVector & , DoubleVector &)
Definition at line 422 of file Tools.cpp.
References isComparable().
Referenced by segmentationProcess().
LIA_SPKTOOLS_API bool isDifferentSegmentation (Config & , SegCluster & , SegCluster &)
Definition at line 455 of file Tools.cpp.
References debug.
Referenced by isComparable(), isStopAcousticSegmentation(), isStopReSeg(), segAdaptation(), and segEM().
LIA_SPKTOOLS_API bool isLessEpsilon (Config & , DoubleVector & , DoubleVector & , double &)
Definition at line 483 of file Tools.cpp.
References debug.
Referenced by isComparable(), isStopAcousticSegmentation(), and isStopReSeg().
LIA_SPKTOOLS_API bool isNewSpeaker (String)
Definition at line 265 of file Tools.cpp.
LIA_SPKTOOLS_API bool isValidLengthOfLastSpeaker (Config & , SegServer &)
Definition at line 500 of file Tools.cpp.
References totalFrame().
LIA_SPKTOOLS_API void learnModel (Config & , SegCluster & , StatServer & , FeatureServer & , MixtureServer & , MixtureGD &)
Definition at line 92 of file Tools.cpp.
References globalMeanCov(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setNbTrainIt(), and trainModel().
LIA_SPKTOOLS_API MixtureGD& learnModelFromSplit (Config & , SegCluster & , StatServer & , FeatureServer & , MixtureServer & , unsigned long, unsigned long, unsigned long)
Definition at line 64 of file Tools.cpp.
References globalMeanCov(), mixtureInitBySplit(), TrainCfg::setBaggedFrameProbability(), TrainCfg::setNbTrainIt(), trainModel(), and verbose.
Referenced by CreateInitHMM(), createWorld(), and segEM().
LIA_SPKTOOLS_API double meanLikelihoodExt (StatServer & , FeatureServer & , MixtureGD & , unsigned long, unsigned long, Config &)
Definition at line 975 of file Tools.cpp.
References accumulateStatLLKExt().
LIA_SPKTOOLS_API MixtureGD& mixtureInitBySplit (Config & , MixtureServer & , StatServer & , FeatureServer & , SegCluster & , DoubleVector & , DoubleVector & , unsigned long, TrainCfg & , unsigned long)
Definition at line 1065 of file Tools.cpp.
References accumulateStatEM(), TrainCfg::getFinalVarCeil(), TrainCfg::getFinalVarFloor(), TrainCfg::getInitVarCeil(), TrainCfg::getInitVarFloor(), TrainCfg::getNbTrainIt(), TrainCfg::getNormalizeModel(), meanLikelihood(), normalizeMixture(), normalizeWeights(), setItParameter(), TrainCfg::showConfig(), sqrt(), totalFrame(), varianceControl(), verbose, and verboseLevel.
Referenced by learnModelFromSplit().
LIA_SPKTOOLS_API void modifyMAPConfig (Config & , MAPCfg & , String)
Definition at line 155 of file Tools.cpp.
References MAPCfg::getMeanAdapt(), MAPCfg::getVarAdapt(), MAPCfg::getWeightAdapt(), MAPCfg::setMeanAdapt(), MAPCfg::setMeanAlpha(), MAPCfg::setMeanReg(), MAPCfg::setMethod(), MAPCfg::setVarAdapt(), MAPCfg::setVarAlpha(), MAPCfg::setVarReg(), MAPCfg::setWeightAdapt(), MAPCfg::setWeightAlpha(), and MAPCfg::setWeightReg().
LIA_SPKTOOLS_API void NoDataSpeakerVerification (Config & , hmm & , SegServer &)
Definition at line 870 of file Tools.cpp.
References computeTransitions(), hmm::deleteState(), totalFrame(), verbose, and verboseLevel.
Referenced by addSpeaker(), segAdaptation(), segAdaptationClass(), and segEM().
LIA_SPKTOOLS_API void saveAcousticSegmentation (Config & , SegServer & , FeatureServer & , String & , int)
Definition at line 748 of file Tools.cpp.
References displayAllSegments(), and verbose.
Referenced by launchAcousticSegmentationProcess().
LIA_SPKTOOLS_API void saveSegmentation (Config & , SegServer & , FeatureServer & , String & , int)
Definition at line 662 of file Tools.cpp.
References displayAllSegments(), and verbose.
Referenced by launchReSegmentationProcess(), launchSegmentationProcess(), and launchTurnDetectionProcess().
LIA_SPKTOOLS_API void segAdaptation (Config & , MAPCfg & , hmm & , MixtureGD & , SegServer & , SegServer & , StatServer & , FeatureServer & , MixtureServer &)
Definition at line 1290 of file Tools.cpp.
References adaptModel(), hmm::getDensity(), isDifferentSegmentation(), NoDataSpeakerVerification(), hmm::setDensity(), verbose, and verboseLevel.
Referenced by ReSegmentationProcess(), and segmentationProcess().
LIA_SPKTOOLS_API void segEM (Config & , hmm & , SegServer & , SegServer & , StatServer & , FeatureServer & , MixtureServer & , unsigned long)
Definition at line 1326 of file Tools.cpp.
References isDifferentSegmentation(), learnModelFromSplit(), NoDataSpeakerVerification(), hmm::setDensity(), verbose, and verboseLevel.
Referenced by segmentationProcess().
LIA_SPKTOOLS_API void viterbiDecoding (Config & , hmm & , SegCluster & , SegServer & , StatServer & , FeatureServer & , LabelServer & , DoubleVector &)
Definition at line 1029 of file Tools.cpp.
References accumulateStatViterbi(), copyPathInCluster(), createAndInitializeViterbiAccum(), hmm::getNbState(), initializeCluster(), verbose, and verboseLevel.
Referenced by AcousticSegmentationProcess(), ReSegmentationProcess(), and segmentationProcess().