LIA_RAL: LIA_SpkDet/TotalVariability/src/TotalVariability.cpp File Reference
TotalVariability.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "TotalVariability.h"
Macros
#define ALIZE_TotalVariability_cpp
Functions
int TotalVariability (Config &config)
Macro Definition Documentation
#define ALIZE_TotalVariability_cpp
Definition at line 57 of file TotalVariability.cpp.
Function Documentation
int TotalVariability (Config & config)
Definition at line 71 of file TotalVariability.cpp.
References TVAcc::approximateTcTc(), TVAcc::computeAndAccumulateTVStat(), TVAcc::computeEigenProblem(), TVAcc::estimateAandC(), TVAcc::estimateTETt(), TVAcc::getNDistrib(), TVAcc::getRankT(), TVAcc::getUbmMeans(), TVAcc::getWeightedCov(), TVAcc::initT(), TVAcc::loadF_X(), TVAcc::loadN(), TVAcc::loadT(), TVAcc::minDivergence(), TVAcc::normTMatrix(), TVAcc::orthonormalizeT(), TVAcc::resetTmpAcc(), TVAcc::saveAccs(), TVAcc::saveT(), TVAcc::substractM(), TVAcc::updateTestimate(), verboseLevel, and TVAcc::verifyEMLK().
Referenced by main().