LIA_RAL: LIA_SpkDet/TotalVariability/include/TotalVariability.h File Reference
TotalVariability.h File Reference
#include "alize.h"
#include "liatools.h"
Functions
int TotalVariability (Config &)
Function Documentation
int TotalVariability (Config &)
Definition at line 71 of file TotalVariability.cpp.
References TVAcc::approximateTcTc(), TVAcc::computeAndAccumulateTVStat(), TVAcc::computeEigenProblem(), TVAcc::estimateAandC(), TVAcc::estimateTETt(), TVAcc::getNDistrib(), TVAcc::getRankT(), TVAcc::getUbmMeans(), TVAcc::getWeightedCov(), TVAcc::initT(), TVAcc::loadF_X(), TVAcc::loadN(), TVAcc::loadT(), TVAcc::minDivergence(), TVAcc::normTMatrix(), TVAcc::orthonormalizeT(), TVAcc::resetTmpAcc(), TVAcc::saveAccs(), TVAcc::saveT(), TVAcc::substractM(), TVAcc::updateTestimate(), verboseLevel, and TVAcc::verifyEMLK().
Referenced by main().