LIA_RAL: LIA_SpkDet/TrainWorld/src/TrainWorld.cpp File Reference
TrainWorld.cpp File Reference
#include <iostream>
#include <cmath>
#include "liatools.h"
#include "TrainWorld.h"
Macros
#define ALIZE_TrainWorld_cpp
Functions
void featureStream (Config &config, String filename, FeatureServer *&fs, SegServer *&segServ, SegCluster *&segCluster, String labelSelectedFrames)
void reserveMem (FeatureServer **&fsTab, SegServer **&segServTab, SegCluster **&segTab, double *&weightTab, unsigned long nbStream)
void freeMem (FeatureServer **&fsTab, SegServer **&segServTab, SegCluster **&segTab, double *&weightTab, unsigned long nbStream)
int trainWorld (Config &config)
Macro Definition Documentation
#define ALIZE_TrainWorld_cpp
Definition at line 56 of file TrainWorld.cpp.
Function Documentation
void featureStream (Config & config, String filename, FeatureServer *& fs, SegServer *& segServ, SegCluster *& segCluster, String labelSelectedFrames)
Definition at line 66 of file TrainWorld.cpp.
References initializeClusters(), and verifyClusterFile().
Referenced by trainWorld().
void freeMem (FeatureServer **& fsTab, SegServer **& segServTab, SegCluster **& segTab, double *& weightTab, unsigned long nbStream)
Definition at line 89 of file TrainWorld.cpp.
Referenced by trainWorld().
void reserveMem (FeatureServer **& fsTab, SegServer **& segServTab, SegCluster **& segTab, double *& weightTab, unsigned long nbStream)
Definition at line 82 of file TrainWorld.cpp.
Referenced by trainWorld().
int trainWorld (Config & config)
Definition at line 101 of file TrainWorld.cpp.
References computeMeanCov(), debug, featureStream(), freeMem(), initialize01(), mixtureInit(), reserveMem(), trainModelStream(), verbose, and verboseLevel.