LIA_RAL: LIA_SpkDet/TrainTarget/include/TrainTarget.h File Reference
TrainTarget.h File Reference
#include "alize.h"
Functions
int InfoTarget (Config &config)
int TrainTarget (alize::Config &)
int TrainTargetLFA (alize::Config &)
int TrainTargetJFA (alize::Config &)
int TrainTargetByLabel (alize::Config &)
Function Documentation
int InfoTarget (Config & config)
Definition at line 72 of file IvExtractor.cpp.
References debug, initializeClusters(), and verbose.
int TrainTarget (alize::Config &)
Referenced by main().
int TrainTargetByLabel (alize::Config &)
Referenced by main().
int TrainTargetJFA (alize::Config &)
Referenced by main().
int TrainTargetLFA (alize::Config &)
Referenced by main().