LIA_RAL: LIA_SpkTools/include/TrainTools.h File Reference
TrainTools.h File Reference
#include <alize.h>
#include "liatools.h"
Classes
class MAPCfg
class TrainCfg
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API void fuseModels (const MixtureGD &, unsigned long, const MixtureGD &, unsigned long, MixtureGD &)
LIA_SPKTOOLS_API void copyMixture (DistribGD &, DistribGD &)
LIA_SPKTOOLS_API unsigned long selectComponent (bool selectCompA[], XList &distribL, MixtureGD &inputM)
LIA_SPKTOOLS_API unsigned long selectComponent (bool selectCompA[], double wFactor, MixtureGD &inputM)
LIA_SPKTOOLS_API unsigned long selectComponent (bool selectCompA[], unsigned long nbTop, MixtureGD &inputM)
LIA_SPKTOOLS_API double reduceModel (bool selectCompA[], MixtureGD &inputM, MixtureGD &outputM)
LIA_SPKTOOLS_API void normalizeWeights (MixtureGD &outputM)
LIA_SPKTOOLS_API void gaussianFusion (const DistribGD &g1, double w1, const DistribGD &g2, double w2, DistribGD &res, double &w)
LIA_SPKTOOLS_API void mixtureFusion (const MixtureGD &mixt, DistribGD &res, double &wres)
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD &mixt, const DoubleVector &meanSignal, const DoubleVector &covSignal, bool zeroOne, unsigned long nbIt, bool meanOnly, Config &config)
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD &mixt, const DoubleVector &meanSignal, const DoubleVector &covSignal, Config &config)
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD &mixt, Config &config)
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD &mixt, MAPCfg &mapCfg, Config &config)
LIA_SPKTOOLS_API double likelihoodLoss (const DistribGD &g1, double w1, const DistribGD &g2, double w2)
LIA_SPKTOOLS_API double * outputMAPTransformation (MixtureGD &world, MixtureGD &clientMixture, Config &config)
LIA_SPKTOOLS_API void computeMAP (MixtureServer &ms, const MixtureGD &world, MixtureGD &client, unsigned long frameCount, Config &config)
LIA_SPKTOOLS_API void computeMAP (MixtureServer &ms, const MixtureGD &world, MixtureGD &client, unsigned long frameCount, MAPCfg &cfg)
LIA_SPKTOOLS_API void copyMean (MixtureGD &mixtS, MixtureGD &mixtD)
LIA_SPKTOOLS_API void copyVar (MixtureGD &mixtS, MixtureGD &mixtD)
LIA_SPKTOOLS_API void copyWeight (MixtureGD &mixtS, MixtureGD &mixtD)
LIA_SPKTOOLS_API double setItParameter (double begin, double end, int nbIt, int it)
LIA_SPKTOOLS_API void varianceControl (MixtureGD &model, double flooring, double ceiling, const DoubleVector &covSignal)
LIA_SPKTOOLS_API unsigned long computeMeanCov (Config &config, FeatureServer **fsTab, SegCluster **segTab, unsigned long nbStream, DoubleVector &mean, DoubleVector &cov)
LIA_SPKTOOLS_API unsigned long computeMeanCov (Config &config, FeatureServer &fs, SegCluster &seg, DoubleVector &mean, DoubleVector &cov)
LIA_SPKTOOLS_API void initialize01 (unsigned long vectSize, DoubleVector &mean, DoubleVector &cov)
LIA_SPKTOOLS_API MixtureGD & mixtureInit (MixtureServer &ms, FeatureServer &fs, MixtureGD &world, SegCluster &selectedSegments, const DoubleVector &globalCov, Config &config)
LIA_SPKTOOLS_API MixtureGD & mixtureInit (MixtureServer &ms, FeatureServer &fs, MixtureGD &world, SegCluster &selectedSegments, const DoubleVector &globalCov, Config &config, TrainCfg &trainCfg)
LIA_SPKTOOLS_API MixtureGD & mixtureInit (MixtureServer &ms, FeatureServer **fsTab, SegCluster **segTab, double *weightTab, unsigned long nbStream, MixtureGD &world, const DoubleVector &globalCov, Config &config, TrainCfg &trainCfg)
LIA_SPKTOOLS_API MixtureGD & mixtureInit (MixtureServer &ms, FeatureServer **fsTab, SegCluster **segTab, double *weightTab, unsigned long nbStream, MixtureGD &world, const DoubleVector &globalCov, Config &config)
LIA_SPKTOOLS_API void adaptModel (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, MixtureGD &world, MixtureGD &clientMixture)
LIA_SPKTOOLS_API void adaptModel (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, MixtureGD &world, MixtureGD &clientMixture, MAPCfg &cfg)
LIA_SPKTOOLS_API void modelBasedadaptModel (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, MixtureGD &aprioriModel, MixtureGD &clientMixture, MixtureGD &initModel)
LIA_SPKTOOLS_API void trainModel (Config &config, StatServer &ss, FeatureServer &fs, SegCluster &selectedSegments, DoubleVector &globalMean, DoubleVector &globalCov, MixtureGD &world)
LIA_SPKTOOLS_API void trainModel (Config &config, StatServer &ss, FeatureServer &fs, SegCluster &selectedSegments, DoubleVector &globalMean, DoubleVector &globalCov, MixtureGD &world, TrainCfg &trainCfg)
LIA_SPKTOOLS_API void trainModelStream (Config &config, MixtureServer &ms, StatServer &ss, FeatureServer **fsTab, SegCluster **segTab, double *weightTab, unsigned long nbStream, DoubleVector &globalMean, DoubleVector &globalCov, MixtureGD *&world, TrainCfg &trainCfg)
LIA_SPKTOOLS_API void trainModel (Config &config, MixtureServer &ms, StatServer &ss, FeatureServer **fsTab, SegCluster **segTab, double *weightTab, unsigned long nbStream, DoubleVector &globalMean, DoubleVector &globalCov, MixtureGD *&world)
LIA_SPKTOOLS_API Matrix< double > computeMLLR (MixtureGD &inM, MixtureGD &outM, unsigned long frameCount, Config &config)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file TrainTools.h.
Function Documentation
LIA_SPKTOOLS_API void adaptModel (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, MixtureGD & world, MixtureGD & clientMixture)
Definition at line 908 of file TrainTools.cpp.
References adaptModel().
Referenced by clusteringCriterionByAdapt(), CreateInitHMM(), segAdaptation(), segAdaptationClass(), TrainTarget(), TrainTargetAdapt(), and TrainTargetByLabel().
LIA_SPKTOOLS_API void adaptModel (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, MixtureGD & world, MixtureGD & clientMixture, MAPCfg & cfg)
Definition at line 873 of file TrainTools.cpp.
References accumulateStatEM(), baggedSegments(), computeMAP(), computeMLLR(), debug, MAPCfg::getBaggedFrameProbability(), MAPCfg::getMethod(), MAPCfg::getNbTrainIt(), MAPCfg::getNormalizeModel(), meanLikelihood(), normalizeMixture(), MAPCfg::showConfig(), verbose, and verboseLevel.
Referenced by adaptModel().
LIA_SPKTOOLS_API void computeMAP (MixtureServer & ms, const MixtureGD & world, MixtureGD & client, unsigned long frameCount, Config & config)
Definition at line 543 of file TrainTools.cpp.
Referenced by adaptModel(), adaptModelMAP(), crossValid(), and modelBasedadaptModel().
LIA_SPKTOOLS_API void computeMAP (MixtureServer & ms, const MixtureGD & world, MixtureGD & client, unsigned long frameCount, MAPCfg & cfg)
Definition at line 548 of file TrainTools.cpp.
References computeMAPConst(), computeMAPConst2(), computeMAPOccDep(), computeModelBasedMAPOccDep(), debug, MAPCfg::getMethod(), and MAPCfg::showConfig().
LIA_SPKTOOLS_API unsigned long computeMeanCov (Config & config, FeatureServer ** fsTab, SegCluster ** segTab, unsigned long nbStream, DoubleVector & mean, DoubleVector & cov)
Definition at line 595 of file TrainTools.cpp.
References accumulateStatFrame(), and initialize01().
Referenced by normFeat(), and trainWorld().
LIA_SPKTOOLS_API unsigned long computeMeanCov (Config & config, FeatureServer & fs, SegCluster & seg, DoubleVector & mean, DoubleVector & cov)
Definition at line 605 of file TrainTools.cpp.
References accumulateStatFrame(), and initialize01().
LIA_SPKTOOLS_API Matrix<double> computeMLLR (MixtureGD & inM, MixtureGD & outM, unsigned long frameCount, Config & config)
Definition at line 790 of file TrainTools.cpp.
References copyVar(), copyWeight(), verbose, and verboseLevel.
Referenced by adaptModel().
LIA_SPKTOOLS_API void copyMean (MixtureGD & mixtS, MixtureGD & mixtD)
Definition at line 423 of file TrainTools.cpp.
LIA_SPKTOOLS_API void copyMixture (DistribGD & , DistribGD &)
Definition at line 166 of file TrainTools.cpp.
Referenced by reduceModel().
LIA_SPKTOOLS_API void copyVar (MixtureGD & mixtS, MixtureGD & mixtD)
Definition at line 432 of file TrainTools.cpp.
Referenced by computeMLLR().
LIA_SPKTOOLS_API void copyWeight (MixtureGD & mixtS, MixtureGD & mixtD)
Definition at line 441 of file TrainTools.cpp.
Referenced by computeMLLR().
LIA_SPKTOOLS_API void fuseModels (const MixtureGD & , unsigned long, const MixtureGD & , unsigned long, MixtureGD &)
Definition at line 236 of file TrainTools.cpp.
Referenced by computeMAPmodelFromEMones().
LIA_SPKTOOLS_API void gaussianFusion (const DistribGD & g1, double w1, const DistribGD & g2, double w2, DistribGD & res, double & w)
Definition at line 257 of file TrainTools.cpp.
Referenced by mixtureFusion().
LIA_SPKTOOLS_API void initialize01 (unsigned long vectSize, DoubleVector & mean, DoubleVector & cov)
Definition at line 614 of file TrainTools.cpp.
Referenced by computeMeanCov(), and trainWorld().
LIA_SPKTOOLS_API double likelihoodLoss (const DistribGD & g1, double w1, const DistribGD & g2, double w2)
Definition at line 338 of file TrainTools.cpp.
References log().
Referenced by energyDetector().
LIA_SPKTOOLS_API void mixtureFusion (const MixtureGD & mixt, DistribGD & res, double & wres)
Definition at line 271 of file TrainTools.cpp.
References gaussianFusion().
Referenced by normalizeMixture().
LIA_SPKTOOLS_API MixtureGD& mixtureInit (MixtureServer & ms, FeatureServer & fs, MixtureGD & world, SegCluster & selectedSegments, const DoubleVector & globalCov, Config & config)
Definition at line 769 of file TrainTools.cpp.
References mixtureInit().
Referenced by clusteringCriterionWithoutWorldInit(), learnModelFromBaggedFrame(), and trainWorld().
LIA_SPKTOOLS_API MixtureGD& mixtureInit (MixtureServer & ms, FeatureServer & fs, MixtureGD & world, SegCluster & selectedSegments, const DoubleVector & globalCov, Config & config, TrainCfg & trainCfg)
Definition at line 621 of file TrainTools.cpp.
References accumulateStatFrame(), baggedSegments(), TrainCfg::getBaggedFrameProbabilityInit(), and verbose.
Referenced by mixtureInit().
LIA_SPKTOOLS_API MixtureGD& mixtureInit (MixtureServer & ms, FeatureServer ** fsTab, SegCluster ** segTab, double * weightTab, unsigned long nbStream, MixtureGD & world, const DoubleVector & globalCov, Config & config, TrainCfg & trainCfg)
Definition at line 676 of file TrainTools.cpp.
References accumulateStatFrame(), baggedSegments(), debug, totalFrame(), and verbose.
LIA_SPKTOOLS_API MixtureGD& mixtureInit (MixtureServer & ms, FeatureServer ** fsTab, SegCluster ** segTab, double * weightTab, unsigned long nbStream, MixtureGD & world, const DoubleVector & globalCov, Config & config)
Definition at line 774 of file TrainTools.cpp.
References mixtureInit().
LIA_SPKTOOLS_API void modelBasedadaptModel (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, MixtureGD & aprioriModel, MixtureGD & clientMixture, MixtureGD & initModel)
Definition at line 917 of file TrainTools.cpp.
Referenced by TrainTarget().
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD & mixt, const DoubleVector & meanSignal, const DoubleVector & covSignal, bool zeroOne, unsigned long nbIt, bool meanOnly, Config & config)
Definition at line 287 of file TrainTools.cpp.
References mixtureFusion(), and sqrt().
Referenced by adaptModel(), adaptModelMAP(), crossValid(), mixtureInitBySplit(), modelBasedadaptModel(), normalizeMixture(), trainModel(), and trainModelStream().
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD & mixt, const DoubleVector & meanSignal, const DoubleVector & covSignal, Config & config)
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD & mixt, Config & config)
Definition at line 329 of file TrainTools.cpp.
References normalizeMixture().
LIA_SPKTOOLS_API void normalizeMixture (MixtureGD & mixt, MAPCfg & mapCfg, Config & config)
Definition at line 334 of file TrainTools.cpp.
References MAPCfg::getNormalizeModelMeanOnly(), MAPCfg::getNormalizeModelNbIt(), and normalizeMixture().
LIA_SPKTOOLS_API void normalizeWeights (MixtureGD & outputM)
Definition at line 223 of file TrainTools.cpp.
Referenced by mixtureInitBySplit(), and trainModelStream().
LIA_SPKTOOLS_API double* outputMAPTransformation (MixtureGD & world, MixtureGD & clientMixture, Config & config)
LIA_SPKTOOLS_API double reduceModel (bool selectCompA[], MixtureGD & inputM, MixtureGD & outputM)
Definition at line 206 of file TrainTools.cpp.
References copyMixture().
Referenced by trainModelStream().
LIA_SPKTOOLS_API unsigned long selectComponent (bool selectCompA[], XList & distribL, MixtureGD & inputM)
Definition at line 175 of file TrainTools.cpp.
Referenced by trainModelStream().
LIA_SPKTOOLS_API unsigned long selectComponent (bool selectCompA[], double wFactor, MixtureGD & inputM)
Definition at line 186 of file TrainTools.cpp.
LIA_SPKTOOLS_API unsigned long selectComponent (bool selectCompA[], unsigned long nbTop, MixtureGD & inputM)
Definition at line 197 of file TrainTools.cpp.
References TabWeight::getDistrib().
LIA_SPKTOOLS_API double setItParameter (double begin, double end, int nbIt, int it)
Definition at line 562 of file TrainTools.cpp.
Referenced by mixtureInitBySplit(), trainModel(), and trainModelStream().
LIA_SPKTOOLS_API void trainModel (Config & config, StatServer & ss, FeatureServer & fs, SegCluster & selectedSegments, DoubleVector & globalMean, DoubleVector & globalCov, MixtureGD & world)
Definition at line 1113 of file TrainTools.cpp.
References trainModel().
Referenced by clusteringCriterion(), clusteringCriterionWithoutWorldInit(), learnModel(), learnModelFromBaggedFrame(), and learnModelFromSplit().
LIA_SPKTOOLS_API void trainModel (Config & config, StatServer & ss, FeatureServer & fs, SegCluster & selectedSegments, DoubleVector & globalMean, DoubleVector & globalCov, MixtureGD & world, TrainCfg & trainCfg)
Definition at line 995 of file TrainTools.cpp.
References accumulateStatEM(), baggedSegments(), TrainCfg::getBaggedFrameProbability(), TrainCfg::getFinalVarCeil(), TrainCfg::getFinalVarFloor(), TrainCfg::getInitVarCeil(), TrainCfg::getInitVarFloor(), TrainCfg::getNbTrainIt(), TrainCfg::getNormalizeModel(), meanLikelihood(), normalizeMixture(), setItParameter(), TrainCfg::showConfig(), varianceControl(), verbose, and verboseLevel.
Referenced by trainModel().
LIA_SPKTOOLS_API void trainModel (Config & config, MixtureServer & ms, StatServer & ss, FeatureServer ** fsTab, SegCluster ** segTab, double * weightTab, unsigned long nbStream, DoubleVector & globalMean, DoubleVector & globalCov, MixtureGD *& world)
Definition at line 1118 of file TrainTools.cpp.
References TrainCfg::showConfig(), trainModelStream(), and verbose.
LIA_SPKTOOLS_API void trainModelStream (Config & config, MixtureServer & ms, StatServer & ss, FeatureServer ** fsTab, SegCluster ** segTab, double * weightTab, unsigned long nbStream, DoubleVector & globalMean, DoubleVector & globalCov, MixtureGD *& world, TrainCfg & trainCfg)
Definition at line 1032 of file TrainTools.cpp.
References accumulateStatEM(), baggedSegments(), debug, TrainCfg::getBaggedFrameProbability(), TrainCfg::getComponentReduction(), TrainCfg::getFinalVarCeil(), TrainCfg::getFinalVarFloor(), TrainCfg::getInitVarCeil(), TrainCfg::getInitVarFloor(), TrainCfg::getNbTrainIt(), TrainCfg::getNormalizeModel(), TrainCfg::getTargetDistribCount(), meanLikelihood(), normalizeMixture(), normalizeWeights(), reduceModel(), selectComponent(), setItParameter(), TrainCfg::showConfig(), totalFrame(), varianceControl(), verbose, and verboseLevel.
Referenced by trainModel(), and trainWorld().
LIA_SPKTOOLS_API void varianceControl (MixtureGD & model, double flooring, double ceiling, const DoubleVector & covSignal)
Definition at line 569 of file TrainTools.cpp.
References verbose.
Referenced by energyDetector(), mixtureInitBySplit(), trainModel(), and trainModelStream().