LIA_RAL: LIA_SpkDet/TrainTarget/src/TrainTarget.cpp File Reference
TrainTarget.cpp File Reference
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <liatools.h>
#include "TrainTarget.h"
Macros
#define ALIZE_TrainTarget_cpp
Functions
int InfoTarget (Config &config)
int TrainTarget (Config &config)
int TrainTargetByLabel (Config &config)
int TrainTargetFA (Config &config)
int TrainTargetJFA (Config &config)
int TrainTargetLFA (Config &config)
Macro Definition Documentation
#define ALIZE_TrainTarget_cpp
Definition at line 56 of file TrainTarget.cpp.
Function Documentation
int InfoTarget (Config & config)
Definition at line 72 of file TrainTarget.cpp.
References debug, initializeClusters(), and verbose.
Referenced by main().
int TrainTarget (Config & config)
Definition at line 137 of file TrainTarget.cpp.
References adaptModel(), computeNap(), getSuperVector(), initializeClusters(), modelBasedadaptModel(), verbose, and verifyClusterFile().
int TrainTargetByLabel (Config & config)
Definition at line 260 of file TrainTarget.cpp.
References adaptModel(), initializeClusters(), verbose, and verifyClusterFile().
int TrainTargetFA (Config & config)
**** Factor Analysis Stuff
**** End of FA
Definition at line 343 of file TrainTarget.cpp.
References FactorAnalysisStat::computeAndAccumulateGeneralFAStats(), FactorAnalysisStat::estimateAndInverseL(), FactorAnalysisStat::getFactorAnalysisModel(), FactorAnalysisStat::getLLK(), FactorAnalysisStat::getSessionModel(), FactorAnalysisStat::getTrueSpeakerModel(), FactorAnalysisStat::getXEstimate(), FactorAnalysisStat::getYEstimate(), initializeClusters(), FactorAnalysisStat::substractChannelStats(), FactorAnalysisStat::substractSpeakerStats(), verbose, and verifyClusterFile().
int TrainTargetJFA (Config & config)
Definition at line 457 of file TrainTarget.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_VU(), JFAAcc::estimateVUEVUT(), JFAAcc::estimateYX(), JFAAcc::estimateZ(), JFAAcc::getMplusVYplusDZ(), JFAAcc::getSvSize(), JFAAcc::getUbmInvVar(), JFAAcc::getVYplusDZ(), initializeClusters(), JFAAcc::initVU(), JFAAcc::loadD(), JFAAcc::loadEC(), JFAAcc::loadEV(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::saveX(), JFAAcc::saveY(), JFAAcc::saveZ(), JFAAcc::splitYX(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractMplusVUYX(), svToModel(), verbose, verboseLevel, and verifyClusterFile().
int TrainTargetLFA (Config & config)
Definition at line 684 of file TrainTarget.cpp.
References JFAAcc::computeAndAccumulateJFAStat(), JFAAcc::estimateAndInverseL_VU(), JFAAcc::estimateVUEVUT(), JFAAcc::estimateYX(), JFAAcc::estimateZMAP(), JFAAcc::getMplusVYplusDZ(), JFAAcc::getSvSize(), initializeClusters(), JFAAcc::initVU(), JFAAcc::loadD(), JFAAcc::loadEC(), JFAAcc::loadEV(), JFAAcc::resetTmpAcc(), JFAAcc::restoreAccs(), JFAAcc::splitYX(), sqrt(), JFAAcc::storeAccs(), JFAAcc::substractMplusDZ(), JFAAcc::substractMplusVUYX(), svToModel(), verbose, verboseLevel, and verifyClusterFile().