LIA_RAL: LIA_SpkSeg/TurnDetection/src/TurnDetection.cpp File Reference
TurnDetection.cpp File Reference
Description of turn speaker detection behavior.
#include "Tools.h"
#include "TurnDetection.h"
Macros
#define ALIZE_TurnDetection_cpp
Functions
double myabs (double value)
void TurnDetection (Config &config, SegCluster &cluster, SegServer &segOutputServer, StatServer &ss, FeatureServer &fs, MixtureServer &ms, LabelServer &labelServer)
The turn speaker detection process.
void launchTurnDetectionProcess (Config &config)
Launching of the turn speaker detection process.
Detailed Description
Description of turn speaker detection behavior.
Author
LIA
Version
2.0
Date
june 2011
This performs a basic speaker turn detection and a local speaker clustering. It can be used as a preliminary step for the segmentation phase if segments are finally assigned the general speech label (only the frontiers will be used to facilitate the segmentation process, not the labels !)
The algorithm is applied only to segments with length superior to 2 * winSize (parameter, default 50) :
Speaker turn detection
use of classical criterion as BIC, GLR, DGLR or DELTABIC (parameter clusteringCrit, default DGLR)
criterion applied on 2 consecutive 0.5s long windows (parameter winSize) at 0.05s step (parameter winStep)
All the values Xi calculated on the set of segments can be viewed as a curve on which selected peaks are considered as speaker turns
Xi is a relevant maximum peak if
Xi - MinLeft(Xi) > alpha * Std-Dev(X) and
Xi + MinRight(Xi) > alpha * Std-Dev(X)
MinLeft(Xi) = smaller value localized on the left of Xi
MinRight(Xi) = smaller value localized on the right of Xi
Std-Dev(X) = standard deviation calculated with all values X on the curve
parameter alpha (default value 0.7)
Local clustering
aggregation of consecutive segments is also based on a specified criterion associated with a decision threshold (parameter clusteringCritThresh)
Definition in file TurnDetection.cpp.
Macro Definition Documentation
#define ALIZE_TurnDetection_cpp
Definition at line 83 of file TurnDetection.cpp.
Function Documentation
void launchTurnDetectionProcess (Config & config)
Launching of the turn speaker detection process.
Definition at line 292 of file TurnDetection.cpp.
References displayAllSegments(), displayAllSegmentsFromRef(), initializeClusters(), saveSegmentation(), TurnDetection(), verbose, and verifyClusterFile().
Referenced by main().
double myabs (double value)
Definition at line 92 of file TurnDetection.cpp.
Referenced by TurnDetection().
void TurnDetection (Config & config, SegCluster & cluster, SegServer & segOutputServer, StatServer & ss, FeatureServer & fs, MixtureServer & ms, LabelServer & labelServer)
The turn speaker detection process.
Definition at line 101 of file TurnDetection.cpp.
References clusteringCriterionWithoutWorldInitOneGaus(), debug, displayAllClusters(), endSeg(), CritInfo::getValue(), myabs(), CritInfo::setDec(), CritInfo::setValue(), sqrt(), and verbose.
Referenced by launchTurnDetectionProcess().