LIA_RAL: LIA_SpkSeg/TurnDetection/include/TurnDetection.h File Reference
TurnDetection.h File Reference
Declaration of turn speaker detection functions.
#include <alize.h>
#include "Tools.h"
#include "SegTools.h"
Classes
class CritInfo
Functions
void TurnDetection (Config &, SegCluster &, SegServer &, StatServer &, FeatureServer &, MixtureServer &, LabelServer &)
The turn speaker detection process.
void launchTurnDetectionProcess (Config &)
Launching of the turn speaker detection process.
Detailed Description
Declaration of turn speaker detection functions.
Author
LIA
Version
2.0
Date
june 2011
Definition in file TurnDetection.h.
Function Documentation
void launchTurnDetectionProcess (Config &)
Launching of the turn speaker detection process.
Definition at line 292 of file TurnDetection.cpp.
References displayAllSegments(), displayAllSegmentsFromRef(), initializeClusters(), saveSegmentation(), TurnDetection(), verbose, and verifyClusterFile().
Referenced by main().
void TurnDetection (Config & , SegCluster & , SegServer & , StatServer & , FeatureServer & , MixtureServer & , LabelServer &)
The turn speaker detection process.
Definition at line 101 of file TurnDetection.cpp.
References clusteringCriterionWithoutWorldInitOneGaus(), debug, displayAllClusters(), endSeg(), CritInfo::getValue(), myabs(), CritInfo::setDec(), CritInfo::setValue(), sqrt(), and verbose.
Referenced by launchTurnDetectionProcess().