LIA_RAL: LIA_SpkTools/include/UnsupervisedTools.h File Reference
UnsupervisedTools.h File Reference
#include <alize.h>
#include "liatools.h"
Macros
#define LIA_SPKTOOLS_API
Functions
LIA_SPKTOOLS_API void accumulateStatLK (StatServer &ss, FeatureServer &fs, MixtureStat &acc, unsigned long idxBeginFrame, unsigned long nbFrames, Config &config)
LIA_SPKTOOLS_API void accumulateStatLK (StatServer &ss, FeatureServer &fs, MixtureStat &acc, Seg *seg, Config &config)
LIA_SPKTOOLS_API void accumulateStatLK (StatServer &ss, FeatureServer &fs, MixtureStat &acc, SegCluster &selectedSegments, Config &config)
LIA_SPKTOOLS_API void adaptModelEM (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, MixtureGD &world, MixtureGD &clientMixture)
LIA_SPKTOOLS_API void adaptModelEM (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, FeatureServer &fs2, SegCluster &selectedSegments2, MixtureGD &aprioriModel, MixtureGD &clientMixture, MAPCfg &mapCfg)
LIA_SPKTOOLS_API void adaptModelEM (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, FeatureServer &fs2, SegCluster &selectedSegments2, MixtureGD &aprioriModel, MixtureGD &clientMixture)
LIA_SPKTOOLS_API void adaptModelMAP (Config &config, StatServer &ss, MixtureServer &ms, MixtureGD &world, MixtureGD &clientMixture, unsigned long &frameCount)
LIA_SPKTOOLS_API void adaptModelMAP (Config &config, StatServer &ss, MixtureServer &ms, MixtureGD &aprioriModel, MixtureGD &clientMixture, MAPCfg &mapCfg, unsigned long &frameCount)
LIA_SPKTOOLS_API void modelBasedadaptModel (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, MixtureGD &aprioriModel, MixtureGD &clientMixture, MixtureGD &initModel)
LIA_SPKTOOLS_API void modelBasedadaptModelEM (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, MixtureGD &aprioriModel, MixtureGD &clientMixture, MixtureGD &initModel)
LIA_SPKTOOLS_API void modelBasedadaptModelEM (Config &config, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &selectedSegments, FeatureServer &fsTests, SegCluster &selectedSegmentsTests, MixtureGD &aprioriModel, MixtureGD &clientMixture, MixtureGD &initModel)
LIA_SPKTOOLS_API void adaptModel (Config &config, StatServer &ss, MixtureServer &ms, ObjectRefVector &FeatServ, ObjectRefVector &ClusterSeg, MixtureGD &aprioriModel, MixtureGD &clientMixture, DoubleVector &decision)
LIA_SPKTOOLS_API double computeLLR (StatServer &ss, FeatureServer &fsTests, MixtureGD &world, MixtureGD &clientMixture, SegCluster &selectedSegmentsTests)
LIA_SPKTOOLS_API double computeLLR (Config &config, StatServer &ss, FeatureServer &fsTests, MixtureGD &world, MixtureGD &clientMixture, SegCluster &selectedSegmentsTests, String &idTest)
LIA_SPKTOOLS_API double computeFastLLR (StatServer &ss, FeatureServer &fsTests, MixtureGD &world, MixtureGD &clientMixture, SegCluster &selectedSegmentsTests, String &idTest, Config &config)
LIA_SPKTOOLS_API double computeLLRGD (Config &config, MixtureGD &clientMixture, MixtureGD &world, MixtureGD &dataTest)
LIA_SPKTOOLS_API void expandLLR (DoubleVector &decision, Config &configTest)
LIA_SPKTOOLS_API void WMAP (DoubleVector &decision, Config &configTest)
LIA_SPKTOOLS_API void WMAPGMM (DoubleVector &decision, Config &configTest, MixtureGD &tar, MixtureGD &non, StatServer &ss)
LIA_SPKTOOLS_API void WMAPGMMFixedPriors (DoubleVector &decision, Config &configTest, MixtureGD &tar, MixtureGD &non, StatServer &ss)
LIA_SPKTOOLS_API String getFullFileName (String &id, Config &c)
LIA_SPKTOOLS_API String getFullMixtureName (String &id, Config &c)
LIA_SPKTOOLS_API bool FileExists (String &fullFileName)
LIA_SPKTOOLS_API void computeMAPmodelFromEMones (Config &config, StatServer &ss, MixtureServer &ms, DoubleVector &nbFramesSelected, MixtureGD &aprioriModel, MixtureGD &clientMixture, MixtureGD &aux, MixtureGD &tmp, DoubleVector &decision, XLine &testsToCompute)
LIA_SPKTOOLS_API double SegClusterFrame (SegCluster &SegC)
LIA_SPKTOOLS_API void addLineInXList (XLine &line, XList &list)
LIA_SPKTOOLS_API void computePriors (DoubleVector &decision, DoubleVector &priorImp, DoubleVector &priorTar, Config &configTest)
LIA_SPKTOOLS_API void loadTnormParam (String &inputClientListFileName, String &testFile, ObjectRefVector &stockTnorm, Config &config)
LIA_SPKTOOLS_API void computeAndStoreZnormParam (StatServer &ss, String &inputImpListFileName, String &idclient, MixtureGD &clientMixture, ObjectRefVector &stockZnorm, MixtureGD &world, Config &config, bool &ztnorm, ObjectRefVector &stockTnorm)
LIA_SPKTOOLS_API void learnMAPimpostorModels (Config &config, DoubleVector &NbFramesSelectedImp, MixtureServer &ms, StatServer &ss, MixtureGD &world)
LIA_SPKTOOLS_API void normalizeScore (String &test, double &decision, ObjectRefVector &stockNorm)
LIA_SPKTOOLS_API void normalizeScore (String &test, double &decision, ObjectRefVector &stockNorm, double &shift)
LIA_SPKTOOLS_API void resetWeights (DoubleVector &decision)
LIA_SPKTOOLS_API void Oracle (String &idTar, String &idTest, double &score, Config &config, MixtureGD &tar, MixtureGD &non, StatServer &ss)
LIA_SPKTOOLS_API void crossValid (Config &configTest, StatServer &ss, MixtureServer &ms, FeatureServer &fs, SegCluster &totalSegments, MixtureGD &aprioriModel, MixtureGD &bestModel, SegCluster &selectedSegments, String &idTest)
LIA_SPKTOOLS_API double searchLLRFromResFile (String &idTar, String &test, String &inputResFilename, Config &config)
LIA_SPKTOOLS_API unsigned long adaptModelEMweightedFrames (String &labelSelectedFrames, XLine &featureFileName, StatServer &ss, MixtureGD &world, MixtureGD &tar, MixtureGD &non, MixtureGD &MixtureforLLR, MixtureGD &MixtureEMOutput, Config &config, FeatureServer &fs, String &fullFileName, String &idTest)
LIA_SPKTOOLS_API String selectNearestTarModel (String &TARListFilename, String &fullFileName, Config &config, StatServer &ss, FeatureServer &fs, MixtureGD &world, SegCluster &selectedSegments, MixtureServer &ms)
LIA_SPKTOOLS_API void computeLLRmatrix (DoubleMatrix &LLR, XLine &models, XList &features, Config &config, StatServer &ss, MixtureGD &world, MixtureServer &ms, String &labelSelectedFrames)
LIA_SPKTOOLS_API void fuseMAP (Config &config, StatServer &ss, MixtureServer &ms, MixtureGD &aprioriModel, MixtureGD &clientMixture, MixtureGD &aux, MixtureGD &tmp, DoubleVector &decision, XLine &testsToCompute)
LIA_SPKTOOLS_API void fuseMAPMeans (const MixtureGD &model1, double &w1, const MixtureGD &model2, double &w2, MixtureGD &result)
LIA_SPKTOOLS_API double computeWeightedLLR (Config &config, StatServer &ss, FeatureServer &fsTests, MixtureServer &ms, MixtureGD &aprioriModel, SegCluster &selectedSegmentsTests, MixtureGD &aux, DoubleVector &decision, XLine &testsToCompute, String &idTest, String &fullfilename)
LIA_SPKTOOLS_API void copyCluster (SegCluster &source, SegCluster &dest)
LIA_SPKTOOLS_API int findClusterInRefvector (ObjectRefVector &SegServ, String &id)
LIA_SPKTOOLS_API void learnEMimpostorModels (Config &config, DoubleVector &NbFramesSelectedImp, MixtureServer &ms, StatServer &ss, MixtureGD &world)
LIA_SPKTOOLS_API double computeAdaptedTnorm (Config &configTest, MixtureServer &ms, StatServer &ss, MixtureGD &world, MixtureGD &auxMixture, MixtureGD &tmpMixture, double &nonorm_score, int &countTests, DoubleVector &decision, DoubleVector &NbFramesSelected, XLine &testsToCompute, DoubleVector &NbFramesSelectedImp, FeatureServer &fsTests, SegCluster &selectedSegmentsTests, String &idTest)
LIA_SPKTOOLS_API double findNearestLLRInMatrix (Matrix< double > &Mat, unsigned long &index, double &LLR)
LIA_SPKTOOLS_API void assessAdaptation (StatServer &ss, MixtureGD &adaptedMixture, SegCluster &selectedSegments, Config &configTest, FeatureServer &fs, MixtureGD &world, DoubleVector &tmp, String &fullFileNameTrain, int countTests, double &tarScore)
Macro Definition Documentation
#define LIA_SPKTOOLS_API
Definition at line 65 of file UnsupervisedTools.h.
Function Documentation
LIA_SPKTOOLS_API void accumulateStatLK (StatServer & ss, FeatureServer & fs, MixtureStat & acc, unsigned long idxBeginFrame, unsigned long nbFrames, Config & config)
Definition at line 180 of file UnsupervisedTools.cpp.
Referenced by accumulateStatLK().
LIA_SPKTOOLS_API void accumulateStatLK (StatServer & ss, FeatureServer & fs, MixtureStat & acc, Seg * seg, Config & config)
Definition at line 195 of file UnsupervisedTools.cpp.
References accumulateStatLK().
LIA_SPKTOOLS_API void accumulateStatLK (StatServer & ss, FeatureServer & fs, MixtureStat & acc, SegCluster & selectedSegments, Config & config)
Definition at line 203 of file UnsupervisedTools.cpp.
References accumulateStatLK().
LIA_SPKTOOLS_API void adaptModel (Config & config, StatServer & ss, MixtureServer & ms, ObjectRefVector & FeatServ, ObjectRefVector & ClusterSeg, MixtureGD & aprioriModel, MixtureGD & clientMixture, DoubleVector & decision)
Definition at line 219 of file UnsupervisedTools.cpp.
References accumulateStatEM(), baggedSegments(), computeMAP(), debug, MAPCfg::getBaggedFrameProbability(), MAPCfg::getNbTrainIt(), MAPCfg::getNormalizeModel(), meanLikelihood(), normalizeMixture(), MAPCfg::showConfig(), verbose, and verboseLevel.
Referenced by learnMAPimpostorModels().
LIA_SPKTOOLS_API void adaptModelEM (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, MixtureGD & world, MixtureGD & clientMixture)
Definition at line 622 of file UnsupervisedTools.cpp.
References adaptModelEM().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void adaptModelEM (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, FeatureServer & fs2, SegCluster & selectedSegments2, MixtureGD & aprioriModel, MixtureGD & clientMixture, MAPCfg & mapCfg)
Definition at line 632 of file UnsupervisedTools.cpp.
References accumulateStatEM(), baggedSegments(), MAPCfg::getBaggedFrameProbability(), MAPCfg::getNbTrainIt(), meanLikelihood(), verbose, and verboseLevel.
LIA_SPKTOOLS_API void adaptModelEM (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, FeatureServer & fs2, SegCluster & selectedSegments2, MixtureGD & aprioriModel, MixtureGD & clientMixture)
Definition at line 692 of file UnsupervisedTools.cpp.
References adaptModelEM().
LIA_SPKTOOLS_API unsigned long adaptModelEMweightedFrames (String & labelSelectedFrames, XLine & featureFileName, StatServer & ss, MixtureGD & world, MixtureGD & tar, MixtureGD & non, MixtureGD & MixtureforLLR, MixtureGD & MixtureEMOutput, Config & config, FeatureServer & fs, String & fullFileName, String & idTest)
Definition at line 1562 of file UnsupervisedTools.cpp.
References WindowLLR::accLLR(), WindowLLR::dec(), FileExists(), WindowLLR::getLLR(), initializeClusters(), WindowLLR::isEnd(), WindowLLR::isSet(), alize::FileInfo::loadTopInfo(), log(), WindowLLR::setNbClient(), WindowLLR::showConfig(), verbose, verboseLevel, verifyClusterFile(), WMAPGMMFixedPriors(), and alize::FileInfo::writeTopInfo().
LIA_SPKTOOLS_API void adaptModelMAP (Config & config, StatServer & ss, MixtureServer & ms, MixtureGD & world, MixtureGD & clientMixture, unsigned long & frameCount)
Definition at line 561 of file UnsupervisedTools.cpp.
References adaptModelMAP().
LIA_SPKTOOLS_API void adaptModelMAP (Config & config, StatServer & ss, MixtureServer & ms, MixtureGD & aprioriModel, MixtureGD & clientMixture, MAPCfg & mapCfg, unsigned long & frameCount)
Definition at line 540 of file UnsupervisedTools.cpp.
References computeMAP(), debug, MAPCfg::getNbTrainIt(), MAPCfg::getNormalizeModel(), and normalizeMixture().
Referenced by adaptModelMAP(), and computeMAPmodelFromEMones().
LIA_SPKTOOLS_API void addLineInXList (XLine & line, XList & list)
Definition at line 1733 of file UnsupervisedTools.cpp.
LIA_SPKTOOLS_API void assessAdaptation (StatServer & ss, MixtureGD & adaptedMixture, SegCluster & selectedSegments, Config & configTest, FeatureServer & fs, MixtureGD & world, DoubleVector & tmp, String & fullFileNameTrain, int countTests, double & tarScore)
Definition at line 2033 of file UnsupervisedTools.cpp.
References computeFastLLR().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API double computeAdaptedTnorm (Config & configTest, MixtureServer & ms, StatServer & ss, MixtureGD & world, MixtureGD & auxMixture, MixtureGD & tmpMixture, double & nonorm_score, int & countTests, DoubleVector & decision, DoubleVector & NbFramesSelected, XLine & testsToCompute, DoubleVector & NbFramesSelectedImp, FeatureServer & fsTests, SegCluster & selectedSegmentsTests, String & idTest)
Definition at line 1963 of file UnsupervisedTools.cpp.
References computeFastLLR(), computeMAPmodelFromEMones(), line, and sqrt().
LIA_SPKTOOLS_API void computeAndStoreZnormParam (StatServer & ss, String & inputImpListFileName, String & idclient, MixtureGD & clientMixture, ObjectRefVector & stockZnorm, MixtureGD & world, Config & config, bool & ztnorm, ObjectRefVector & stockTnorm)
Definition at line 1303 of file UnsupervisedTools.cpp.
References computeFastLLR(), computeLLR(), FileExists(), getFullFileName(), Norm::idTest, initializeClusters(), line, Norm::mu, normalizeScore(), Norm::sigma, sqrt(), verbose, verboseLevel, verifyClusterFile(), and znorm().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API double computeFastLLR (StatServer & ss, FeatureServer & fsTests, MixtureGD & world, MixtureGD & clientMixture, SegCluster & selectedSegmentsTests, String & idTest, Config & config)
Definition at line 812 of file UnsupervisedTools.cpp.
References alize::FileInfo::close(), debug, alize::FileInfo::loadTopInfo(), verbose, and verboseLevel.
Referenced by assessAdaptation(), computeAdaptedTnorm(), computeAndStoreZnormParam(), computeWeightedLLR(), selectNearestTarModel(), and TrainTargetAdapt().
LIA_SPKTOOLS_API double computeLLR (StatServer & ss, FeatureServer & fsTests, MixtureGD & world, MixtureGD & clientMixture, SegCluster & selectedSegmentsTests)
Definition at line 708 of file UnsupervisedTools.cpp.
References verbose, and verboseLevel.
Referenced by computeAndStoreZnormParam(), computeLLRmatrix(), crossValid(), selectNearestTarModel(), and TrainTargetAdapt().
LIA_SPKTOOLS_API double computeLLR (Config & config, StatServer & ss, FeatureServer & fsTests, MixtureGD & world, MixtureGD & clientMixture, SegCluster & selectedSegmentsTests, String & idTest)
Definition at line 748 of file UnsupervisedTools.cpp.
References alize::FileInfo::close(), verbose, verboseLevel, and alize::FileInfo::writeTopInfo().
LIA_SPKTOOLS_API double computeLLRGD (Config & config, MixtureGD & clientMixture, MixtureGD & world, MixtureGD & dataTest)
Definition at line 852 of file UnsupervisedTools.cpp.
References likelihoodGD(), verbose, and verboseLevel.
LIA_SPKTOOLS_API void computeLLRmatrix (DoubleMatrix & LLR, XLine & models, XList & features, Config & config, StatServer & ss, MixtureGD & world, MixtureServer & ms, String & labelSelectedFrames)
Definition at line 1685 of file UnsupervisedTools.cpp.
References computeLLR(), debug, initializeClusters(), line, and verifyClusterFile().
LIA_SPKTOOLS_API void computeMAPmodelFromEMones (Config & config, StatServer & ss, MixtureServer & ms, DoubleVector & nbFramesSelected, MixtureGD & aprioriModel, MixtureGD & clientMixture, MixtureGD & aux, MixtureGD & tmp, DoubleVector & decision, XLine & testsToCompute)
Definition at line 1130 of file UnsupervisedTools.cpp.
References adaptModelMAP(), debug, fuseModels(), verbose, and verboseLevel.
Referenced by computeAdaptedTnorm(), and TrainTargetAdapt().
LIA_SPKTOOLS_API void computePriors (DoubleVector & decision, DoubleVector & priorImp, DoubleVector & priorTar, Config & configTest)
Definition at line 1089 of file UnsupervisedTools.cpp.
References verbose, and verboseLevel.
Referenced by WMAPGMM().
LIA_SPKTOOLS_API double computeWeightedLLR (Config & config, StatServer & ss, FeatureServer & fsTests, MixtureServer & ms, MixtureGD & aprioriModel, SegCluster & selectedSegmentsTests, MixtureGD & aux, DoubleVector & decision, XLine & testsToCompute, String & idTest, String & fullfilename)
Definition at line 1804 of file UnsupervisedTools.cpp.
References computeFastLLR(), debug, verbose, and verboseLevel.
LIA_SPKTOOLS_API void copyCluster (SegCluster & source, SegCluster & dest)
Definition at line 1831 of file UnsupervisedTools.cpp.
Referenced by crossValid(), and TrainTargetAdapt().
LIA_SPKTOOLS_API void crossValid (Config & configTest, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & totalSegments, MixtureGD & aprioriModel, MixtureGD & bestModel, SegCluster & selectedSegments, String & idTest)
Definition at line 1459 of file UnsupervisedTools.cpp.
References accumulateStatEM(), baggedSegments(), computeLLR(), computeMAP(), copyCluster(), debug, MAPCfg::getNormalizeModel(), meanLikelihood(), normalizeMixture(), verbose, and verboseLevel.
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void expandLLR (DoubleVector & decision, Config & configTest)
Definition at line 874 of file UnsupervisedTools.cpp.
References exp().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API bool FileExists (String & fullFileName)
Definition at line 968 of file UnsupervisedTools.cpp.
Referenced by adaptModelEMweightedFrames(), computeAndStoreZnormParam(), learnEMimpostorModels(), learnMAPimpostorModels(), selectNearestTarModel(), and TrainTargetAdapt().
LIA_SPKTOOLS_API int findClusterInRefvector (ObjectRefVector & SegServ, String & id)
Definition at line 1839 of file UnsupervisedTools.cpp.
LIA_SPKTOOLS_API double findNearestLLRInMatrix (Matrix< double > & Mat, unsigned long & index, double & LLR)
Definition at line 2005 of file UnsupervisedTools.cpp.
References abs().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void fuseMAP (Config & config, StatServer & ss, MixtureServer & ms, MixtureGD & aprioriModel, MixtureGD & clientMixture, MixtureGD & aux, MixtureGD & tmp, DoubleVector & decision, XLine & testsToCompute)
Definition at line 1751 of file UnsupervisedTools.cpp.
References debug, fuseMAPMeans(), verbose, and verboseLevel.
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void fuseMAPMeans (const MixtureGD & model1, double & w1, const MixtureGD & model2, double & w2, MixtureGD & result)
Definition at line 1784 of file UnsupervisedTools.cpp.
Referenced by fuseMAP().
LIA_SPKTOOLS_API String getFullFileName (String & id, Config & c)
Definition at line 952 of file UnsupervisedTools.cpp.
Referenced by computeAndStoreZnormParam(), and TrainTargetAdapt().
LIA_SPKTOOLS_API String getFullMixtureName (String & id, Config & c)
Definition at line 959 of file UnsupervisedTools.cpp.
Referenced by learnEMimpostorModels(), learnMAPimpostorModels(), and TrainTargetAdapt().
LIA_SPKTOOLS_API void learnEMimpostorModels (Config & config, DoubleVector & NbFramesSelectedImp, MixtureServer & ms, StatServer & ss, MixtureGD & world)
Definition at line 1850 of file UnsupervisedTools.cpp.
References adaptModelEM(), FileExists(), getFullMixtureName(), initializeClusters(), line, SegClusterFrame(), verbose, and verifyClusterFile().
LIA_SPKTOOLS_API void learnMAPimpostorModels (Config & config, DoubleVector & NbFramesSelectedImp, MixtureServer & ms, StatServer & ss, MixtureGD & world)
Definition at line 1899 of file UnsupervisedTools.cpp.
References adaptModel(), FileExists(), getFullMixtureName(), initializeClusters(), line, SegClusterFrame(), verbose, and verifyClusterFile().
LIA_SPKTOOLS_API void loadTnormParam (String & inputClientListFileName, String & testFile, ObjectRefVector & stockTnorm, Config & config)
Definition at line 1211 of file UnsupervisedTools.cpp.
References debug, Norm::idTest, line, Norm::mu, Norm::sigma, and sqrt().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void modelBasedadaptModel (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, MixtureGD & aprioriModel, MixtureGD & clientMixture, MixtureGD & initModel)
Definition at line 917 of file TrainTools.cpp.
References accumulateStatEM(), baggedSegments(), computeMAP(), debug, MAPCfg::getBaggedFrameProbability(), MAPCfg::getNbEmIt(), MAPCfg::getNormalizeModel(), likelihoodGD(), meanLikelihood(), normalizeMixture(), MAPCfg::showConfig(), totalFrame(), verbose, and verboseLevel.
LIA_SPKTOOLS_API void modelBasedadaptModelEM (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, MixtureGD & aprioriModel, MixtureGD & clientMixture, MixtureGD & initModel)
Definition at line 423 of file UnsupervisedTools.cpp.
References accumulateStatEM(), baggedSegments(), debug, MAPCfg::getBaggedFrameProbability(), MAPCfg::getNbEmIt(), likelihoodGD(), and verbose.
LIA_SPKTOOLS_API void modelBasedadaptModelEM (Config & config, StatServer & ss, MixtureServer & ms, FeatureServer & fs, SegCluster & selectedSegments, FeatureServer & fsTests, SegCluster & selectedSegmentsTests, MixtureGD & aprioriModel, MixtureGD & clientMixture, MixtureGD & initModel)
Definition at line 288 of file UnsupervisedTools.cpp.
References accumulateStatEM(), baggedSegments(), debug, MAPCfg::getBaggedFrameProbability(), MAPCfg::getNbEmIt(), likelihoodGD(), meanLikelihood(), verbose, and verboseLevel.
LIA_SPKTOOLS_API void normalizeScore (String & test, double & decision, ObjectRefVector & stockNorm)
Definition at line 1264 of file UnsupervisedTools.cpp.
References verbose, and verboseLevel.
Referenced by computeAndStoreZnormParam(), and TrainTargetAdapt().
LIA_SPKTOOLS_API void normalizeScore (String & test, double & decision, ObjectRefVector & stockNorm, double & shift)
Definition at line 1284 of file UnsupervisedTools.cpp.
References verbose, and verboseLevel.
LIA_SPKTOOLS_API void Oracle (String & idTar, String & idTest, double & score, Config & config, MixtureGD & tar, MixtureGD & non, StatServer & ss)
Definition at line 1404 of file UnsupervisedTools.cpp.
References line, and WMAPGMMFixedPriors().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void resetWeights (DoubleVector & decision)
Definition at line 1390 of file UnsupervisedTools.cpp.
LIA_SPKTOOLS_API double searchLLRFromResFile (String & idTar, String & test, String & inputResFilename, Config & config)
Definition at line 1527 of file UnsupervisedTools.cpp.
References line.
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API double SegClusterFrame (SegCluster & SegC)
Definition at line 1183 of file UnsupervisedTools.cpp.
Referenced by learnEMimpostorModels(), learnMAPimpostorModels(), and TrainTargetAdapt().
LIA_SPKTOOLS_API String selectNearestTarModel (String & TARListFilename, String & fullFileName, Config & config, StatServer & ss, FeatureServer & fs, MixtureGD & world, SegCluster & selectedSegments, MixtureServer & ms)
Definition at line 1654 of file UnsupervisedTools.cpp.
References computeFastLLR(), computeLLR(), FileExists(), and line.
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void WMAP (DoubleVector & decision, Config & configTest)
Definition at line 901 of file UnsupervisedTools.cpp.
References exp(), and sqrt().
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void WMAPGMM (DoubleVector & decision, Config & configTest, MixtureGD & tar, MixtureGD & non, StatServer & ss)
Definition at line 1038 of file UnsupervisedTools.cpp.
References computePriors(), debug, exp(), verbose, and verboseLevel.
Referenced by TrainTargetAdapt().
LIA_SPKTOOLS_API void WMAPGMMFixedPriors (DoubleVector & decision, Config & configTest, MixtureGD & tar, MixtureGD & non, StatServer & ss)
Definition at line 985 of file UnsupervisedTools.cpp.
References debug, exp(), verbose, and verboseLevel.
Referenced by adaptModelEMweightedFrames(), Oracle(), and TrainTargetAdapt().